import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 1: hello, goodbye, your name, how are you. The reference for how a unit is written. */
export const u01: Unit = {
  slug: "bonjour",
  n: 1,
  cefr: "A1",
  title: tx("Hello!", "Hallo!"),
  goal: tx("Greet people, say your name and ask how they are", "Leute begrüßen, deinen Namen sagen und fragen, wie es geht"),
  emoji: "👋",
  words: [
    { id: "bonjour", fr: "bonjour", en: "hello", de: "hallo", alt: { en: ["good morning", "good day", "hi"], de: ["guten Tag", "guten Morgen"] }, kind: "phrase", emoji: "☀️", note: tx("Literally «good day». It's the polite hello for the whole day.", "Wörtlich „guter Tag“. Das höfliche Hallo für den ganzen Tag.") },
    { id: "salut", fr: "salut", en: "hi", de: "hallo", alt: { en: ["hello", "bye", "hey"], de: ["hi", "tschüss", "ciao"] }, kind: "phrase", emoji: "👋", note: tx("For friends, both hello and bye.", "Unter Freunden: hallo und tschüss zugleich.") },
    { id: "merci", fr: "merci", en: "thank you", de: "danke", alt: { en: ["thanks"] }, kind: "phrase", emoji: "🙏" },
    { id: "oui", fr: "oui", en: "yes", de: "ja", kind: "word", emoji: "👍" },
    { id: "non", fr: "non", en: "no", de: "nein", kind: "word", emoji: "👎" },
    { id: "bonsoir", fr: "bonsoir", en: "good evening", de: "guten Abend", kind: "phrase", emoji: "🌙", note: tx("Bon + soir: good + evening.", "Bon + soir: guter + Abend.") },
    { id: "au-revoir", fr: "au revoir", en: "goodbye", de: "auf Wiedersehen", alt: { en: ["bye"], de: ["tschüss"] }, kind: "phrase", emoji: "🚶" },
    { id: "a-bientot", fr: "à bientôt", en: "see you soon", de: "bis bald", kind: "phrase", emoji: "⏳" },
    { id: "merci-beaucoup", fr: "merci beaucoup", en: "thank you very much", de: "vielen Dank", alt: { en: ["thanks a lot", "many thanks"], de: ["danke schön", "danke sehr"] }, kind: "phrase", emoji: "💐" },
    { id: "madame", fr: "madame", en: "Mrs", de: "Frau", alt: { en: ["madam", "ma'am"] }, kind: "word", emoji: "👩" },
    { id: "je-m-appelle", fr: "je m'appelle", en: "my name is", de: "ich heiße", alt: { en: ["I am called"] }, kind: "phrase" },
    { id: "tu-t-appelles", fr: "tu t'appelles comment ?", en: "what's your name?", de: "wie heißt du?", alt: { fr: ["comment tu t'appelles ?"], en: ["what is your name?"] }, kind: "phrase" },
    { id: "je-suis", fr: "je suis", en: "I am", de: "ich bin", kind: "phrase", note: tx("From être, «to be». The most important verb of all.", "Von être, „sein“. Das wichtigste Verb überhaupt.") },
    { id: "tu-es", fr: "tu es", en: "you are", de: "du bist", kind: "phrase" },
    { id: "enchante", fr: "enchanté", en: "nice to meet you", de: "freut mich", alt: { fr: ["enchantée"], en: ["pleased to meet you"], de: ["sehr erfreut"] }, kind: "phrase", emoji: "🤝", note: tx("A girl or woman writes enchantée, with an extra e.", "Mädchen und Frauen schreiben enchantée, mit einem e mehr.") },
    { id: "comment-ca-va", fr: "comment ça va ?", en: "how are you?", de: "wie geht's?", alt: { fr: ["ça va ?"], en: ["how's it going?"], de: ["wie geht es dir?"] }, kind: "phrase" },
    { id: "ca-va", fr: "ça va", en: "I'm fine", de: "es geht mir gut", alt: { en: ["fine", "I'm good"], de: ["gut", "mir geht's gut"] }, kind: "phrase", emoji: "🙂" },
    { id: "bien", fr: "bien", en: "well", de: "gut", alt: { en: ["good", "fine"] }, kind: "adv" },
    { id: "tres", fr: "très", en: "very", de: "sehr", kind: "adv" },
    { id: "et-toi", fr: "et toi ?", en: "and you?", de: "und du?", alt: { de: ["und dir?"] }, kind: "phrase" },
    { id: "moi-aussi", fr: "moi aussi", en: "me too", de: "ich auch", alt: { de: ["mir auch"] }, kind: "phrase" },
    { id: "monsieur", fr: "monsieur", en: "Mr", de: "Herr", alt: { en: ["sir"] }, kind: "word", emoji: "👨" },
    { id: "pardon", fr: "pardon", en: "sorry", de: "Entschuldigung", alt: { en: ["excuse me", "pardon"], de: ["Verzeihung", "entschuldige"] }, kind: "phrase", emoji: "🙇", note: tx("Sorry, or excuse me when you need to get past someone.", "Entschuldigung, auch wenn du an jemandem vorbeimusst.") },
    { id: "comment-allez-vous", fr: "comment allez-vous ?", en: "how are you? (polite)", de: "wie geht es Ihnen?", kind: "phrase", note: tx("The polite question, for adults you don't know well, like Mrs Martin. Vous is a bit like Sie in German.", "Die höfliche Frage, für Erwachsene, die du nicht so gut kennst, wie Frau Martin. Vous ist wie Sie im Deutschen.") },
    { id: "et-vous", fr: "et vous ?", en: "and you? (polite)", de: "und Ihnen?", alt: { de: ["und Sie?"] }, kind: "phrase", note: tx("Polite, or for several people. To a friend you say et toi ?", "Höflich, oder für mehrere Leute. Zu Freunden sagst du et toi ?") },
    { id: "bonne-journee", fr: "bonne journée !", en: "have a nice day!", de: "schönen Tag noch!", alt: { en: ["have a good day!"], de: ["einen schönen Tag!"] }, kind: "phrase", emoji: "🌈", note: tx("Said when you leave, in shops too. Bonne, not bon: journée is feminine.", "Sagt man beim Gehen, auch im Laden. Bonne, nicht bon: journée ist weiblich.") },
    { id: "il-s-appelle", fr: "il s'appelle", en: "his name is", de: "er heißt", alt: { en: ["he is called"] }, kind: "phrase", note: tx("Like je m'appelle, but about someone else: il s'appelle Hugo.", "Wie je m'appelle, aber über jemand anderen: il s'appelle Hugo.") },
    { id: "elle-s-appelle", fr: "elle s'appelle", en: "her name is", de: "sie heißt", alt: { en: ["she is called"] }, kind: "phrase" },
    { id: "comme-ci-comme-ca", fr: "comme ci, comme ça", en: "so-so", de: "so lala", alt: { de: ["geht so", "es geht"] }, kind: "phrase", emoji: "🤷", note: tx("Literally «like this, like that»: not great, not bad.", "Wörtlich „so hier, so da“: nicht toll, nicht schlecht.") },
  ],
  gloss: [{ fr: "enchantée", en: "nice to meet you (said by a girl)", de: "freut mich (von einem Mädchen)" }],
  lessons: [
    { title: tx("Hello and thanks", "Hallo und danke"), words: ["bonjour", "salut", "merci", "oui", "non"] },
    { title: tx("Good evening, goodbye", "Guten Abend, tschüss"), words: ["bonsoir", "au-revoir", "a-bientot", "merci-beaucoup", "madame"] },
    { title: tx("My name is…", "Ich heiße …"), words: ["je-m-appelle", "tu-t-appelles", "je-suis", "tu-es", "enchante"] },
    { title: tx("How are you?", "Wie geht's?"), words: ["comment-ca-va", "ca-va", "bien", "tres", "et-toi", "moi-aussi"] },
    { title: tx("In the park", "Im Park"), words: ["monsieur", "pardon"] },
    { title: tx("Polite hello", "Höflich grüßen"), words: ["comment-allez-vous", "et-vous", "bonne-journee"] },
    { title: tx("Her name is Léa", "Sie heißt Léa"), words: ["il-s-appelle", "elle-s-appelle", "comme-ci-comme-ca"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u01.01", lesson: 1, fr: "Bonjour, Léa !", en: "Hello, Léa!", de: "Hallo, Léa!", alt: { en: ["Hi, Léa!", "Good morning, Léa!"], de: ["Guten Tag, Léa!", "Guten Morgen, Léa!", "Hi, Léa!"] } },
    { id: "u01.02", lesson: 1, fr: "Salut, Hugo !", en: "Hi, Hugo!", de: "Hallo, Hugo!", alt: { en: ["Hello, Hugo!", "Hey, Hugo!"], de: ["Hi, Hugo!"] } },
    { id: "u01.03", lesson: 1, fr: "Oui, merci.", en: "Yes, thank you.", de: "Ja, danke.", alt: { en: ["Yes, thanks."] } },
    { id: "u01.04", lesson: 1, fr: "Non, merci.", en: "No, thank you.", de: "Nein, danke.", alt: { en: ["No, thanks."] } },
    { id: "u01.05", lesson: 1, fr: "Merci, Léa !", en: "Thank you, Léa!", de: "Danke, Léa!", alt: { en: ["Thanks, Léa!"] } },
    { id: "u01.06", lesson: 1, fr: "Bonjour et merci !", en: "Hello and thank you!", de: "Hallo und danke!", alt: { en: ["Hello and thanks!", "Good morning and thank you!"], de: ["Guten Tag und danke!"] } },
    // Lesson 2
    { id: "u01.07", lesson: 2, fr: "Bonsoir, Madame Martin.", en: "Good evening, Mrs Martin.", de: "Guten Abend, Frau Martin." },
    { id: "u01.08", lesson: 2, fr: "Au revoir, Hugo !", en: "Goodbye, Hugo!", de: "Auf Wiedersehen, Hugo!", alt: { en: ["Bye, Hugo!"], de: ["Tschüss, Hugo!"] } },
    { id: "u01.09", lesson: 2, fr: "Salut, à bientôt !", en: "Bye, see you soon!", de: "Tschüss, bis bald!", alt: { en: ["Hi, see you soon!"], de: ["Ciao, bis bald!", "Hallo, bis bald!"] } },
    { id: "u01.10", lesson: 2, fr: "Merci beaucoup, Madame Martin !", en: "Thank you very much, Mrs Martin!", de: "Vielen Dank, Frau Martin!", alt: { en: ["Thanks a lot, Mrs Martin!", "Many thanks, Mrs Martin!"], de: ["Danke schön, Frau Martin!", "Danke sehr, Frau Martin!"] } },
    { id: "u01.11", lesson: 2, fr: "Au revoir et merci !", en: "Goodbye and thank you!", de: "Auf Wiedersehen und danke!", alt: { en: ["Goodbye and thanks!", "Bye and thank you!", "Bye and thanks!"], de: ["Tschüss und danke!"] } },
    { id: "u01.12", lesson: 2, fr: "Bonsoir, Léa.", en: "Good evening, Léa.", de: "Guten Abend, Léa." },
    // Lesson 3
    { id: "u01.13", lesson: 3, fr: "Je m'appelle Blob.", en: "My name is Blob.", de: "Ich heiße Blob.", alt: { en: ["I am called Blob.", "I am Blob."], de: ["Mein Name ist Blob.", "Ich bin Blob."] } },
    { id: "u01.14", lesson: 3, fr: "Tu t'appelles comment ?", en: "What's your name?", de: "Wie heißt du?", alt: { fr: ["Comment tu t'appelles ?", "Comment t'appelles-tu ?", "Vous vous appelez comment ?", "Comment vous appelez-vous ?"], en: ["What is your name?"] } },
    { id: "u01.15", lesson: 3, fr: "Je suis Léa.", en: "I am Léa.", de: "Ich bin Léa.", alt: { de: ["Ich heiße Léa."] } },
    { id: "u01.16", lesson: 3, fr: "Tu es Hugo ?", en: "Are you Hugo?", de: "Bist du Hugo?", alt: { fr: ["Es-tu Hugo ?", "Est-ce que tu es Hugo ?", "Vous êtes Hugo ?", "Êtes-vous Hugo ?"], en: ["You are Hugo?"], de: ["Du bist Hugo?"] } },
    { id: "u01.17", lesson: 3, fr: "Je m'appelle Hugo, et toi ?", en: "My name is Hugo, and you?", de: "Ich heiße Hugo, und du?", alt: { fr: ["Je m'appelle Hugo, et vous ?"], en: ["My name is Hugo, and yours?", "I am called Hugo, and you?", "I am Hugo, and you?"], de: ["Mein Name ist Hugo, und deiner?", "Ich bin Hugo, und du?"] } },
    { id: "u01.18", lesson: 3, fr: "Bonjour, je suis Blob.", en: "Hello, I am Blob.", de: "Hallo, ich bin Blob.", alt: { en: ["Hi, I am Blob.", "Good morning, I am Blob."], de: ["Guten Tag, ich bin Blob.", "Hallo, ich heiße Blob."] } },
    { id: "u01.19", lesson: 3, fr: "Enchanté, Léa !", en: "Nice to meet you, Léa!", de: "Freut mich, Léa!", alt: { fr: ["Enchantée, Léa !"], en: ["Pleased to meet you, Léa!"], de: ["Sehr erfreut, Léa!", "Schön, dich kennenzulernen, Léa!"] } },
    // Lesson 4
    { id: "u01.20", lesson: 4, fr: "Comment ça va ?", en: "How are you?", de: "Wie geht's?", alt: { fr: ["Ça va ?", "Comment vas-tu ?", "Comment allez-vous ?"], en: ["How's it going?", "How are things?"], de: ["Wie geht es dir?", "Wie geht es?"] } },
    { id: "u01.21", lesson: 4, fr: "Ça va bien, merci.", en: "I'm fine, thank you.", de: "Mir geht's gut, danke.", alt: { en: ["I'm fine, thanks.", "I'm good, thanks.", "I'm good, thank you.", "I'm well, thank you.", "I'm well, thanks.", "Fine, thanks.", "Fine, thank you."], de: ["Es geht mir gut, danke.", "Gut, danke.", "Es geht gut, danke.", "Mir geht es gut, danke."] } },
    { id: "u01.22", lesson: 4, fr: "Ça va très bien !", en: "I'm very well!", de: "Mir geht's sehr gut!", alt: { en: ["I'm very good!", "I'm doing very well!", "Very well!", "Very good!"], de: ["Es geht mir sehr gut!", "Sehr gut!", "Mir geht es sehr gut!"] } },
    { id: "u01.23", lesson: 4, fr: "Et toi ?", en: "And you?", de: "Und du?", alt: { fr: ["Et vous ?"], en: ["What about you?", "And yourself?"], de: ["Und dir?"] } },
    { id: "u01.24", lesson: 4, fr: "Moi aussi.", en: "Me too.", de: "Ich auch.", alt: { en: ["Me as well.", "So am I."], de: ["Mir auch."] } },
    { id: "u01.25", lesson: 4, fr: "Ça va, et toi ?", en: "I'm fine, and you?", de: "Gut, und dir?", alt: { fr: ["Ça va, et vous ?", "Ça va bien, et toi ?"], en: ["Fine, and you?", "I'm good, and you?", "Good, and you?", "I'm well, and you?"], de: ["Mir geht's gut, und dir?", "Gut, und du?", "Es geht mir gut, und dir?", "Mir geht es gut, und dir?"] } },
    { id: "u01.26", lesson: 4, fr: "Très bien, merci !", en: "Very well, thank you!", de: "Sehr gut, danke!", alt: { en: ["Very well, thanks!", "Very good, thanks!", "Very good, thank you!"] } },
    // Lesson 5
    { id: "u01.27", lesson: 5, fr: "Bonjour, Monsieur Martin !", en: "Hello, Mr Martin!", de: "Guten Tag, Herr Martin!", alt: { en: ["Good morning, Mr Martin!", "Hi, Mr Martin!", "Good day, Mr Martin!"], de: ["Hallo, Herr Martin!", "Guten Morgen, Herr Martin!"] } },
    { id: "u01.28", lesson: 5, fr: "Oui, je suis Blob !", en: "Yes, I am Blob!", de: "Ja, ich bin Blob!" },
    { id: "u01.29", lesson: 5, fr: "Au revoir, Monsieur Martin.", en: "Goodbye, Mr Martin.", de: "Auf Wiedersehen, Herr Martin.", alt: { en: ["Bye, Mr Martin."], de: ["Tschüss, Herr Martin."] } },
    { id: "u01.30", lesson: 5, fr: "Bonsoir, Monsieur Martin !", en: "Good evening, Mr Martin!", de: "Guten Abend, Herr Martin!" },
    { id: "u01.31", lesson: 5, fr: "Pardon, Monsieur Martin !", en: "Sorry, Mr Martin!", de: "Entschuldigung, Herr Martin!", alt: { en: ["Excuse me, Mr Martin!", "Pardon me, Mr Martin!", "I'm sorry, Mr Martin!"], de: ["Verzeihung, Herr Martin!", "Entschuldigen Sie, Herr Martin!"] } },
    { id: "u01.32", lesson: 5, fr: "Pardon, tu es Hugo ?", en: "Excuse me, are you Hugo?", de: "Entschuldigung, bist du Hugo?", alt: { fr: ["Pardon, es-tu Hugo ?", "Pardon, est-ce que tu es Hugo ?", "Pardon, vous êtes Hugo ?", "Pardon, êtes-vous Hugo ?"], en: ["Sorry, are you Hugo?", "Excuse me, you are Hugo?"], de: ["Entschuldigung, du bist Hugo?", "Verzeihung, bist du Hugo?", "Entschuldige, bist du Hugo?"] } },
    // Lesson 6
    { id: "u01.33", lesson: 6, fr: "Comment allez-vous, Madame Martin ?", en: "How are you, Mrs Martin?", de: "Wie geht es Ihnen, Frau Martin?", alt: { fr: ["Madame Martin, comment allez-vous ?", "Vous allez bien, Madame Martin ?", "Comment ça va, Madame Martin ?"], en: ["Mrs Martin, how are you?", "How are you doing, Mrs Martin?"], de: ["Frau Martin, wie geht es Ihnen?", "Wie geht's Ihnen, Frau Martin?"] } },
    { id: "u01.34", lesson: 6, fr: "Très bien, merci. Et vous ?", en: "Very well, thank you. And you?", de: "Sehr gut, danke. Und Ihnen?", alt: { fr: ["Ça va très bien, merci. Et vous ?", "Très bien, merci. Et toi ?"], en: ["Very well, thanks. And you?", "Very good, thank you. And you?", "Very well, thank you. What about you?", "Very well, thank you. And yourself?"], de: ["Sehr gut, danke. Und Sie?", "Sehr gut, danke. Und euch?", "Mir geht's sehr gut, danke. Und Ihnen?"] } },
    { id: "u01.35", lesson: 6, fr: "Bonne journée, Monsieur Martin !", en: "Have a nice day, Mr Martin!", de: "Schönen Tag noch, Herr Martin!", alt: { en: ["Have a good day, Mr Martin!"], de: ["Einen schönen Tag, Herr Martin!", "Einen schönen Tag noch, Herr Martin!", "Schönen Tag, Herr Martin!"] } },
    { id: "u01.36", lesson: 6, fr: "Merci, bonne journée !", en: "Thank you, have a nice day!", de: "Danke, schönen Tag noch!", alt: { en: ["Thanks, have a nice day!", "Thank you, have a good day!", "Thanks, have a good day!"], de: ["Danke, einen schönen Tag!", "Danke, einen schönen Tag noch!", "Danke, schönen Tag!"] } },
    { id: "u01.37", lesson: 6, fr: "Salut, Hugo ! Ça va ?", en: "Hi, Hugo! How are you?", de: "Hallo, Hugo! Wie geht's?", alt: { fr: ["Salut, Hugo ! Comment ça va ?", "Salut, Hugo ! Tu vas bien ?"], en: ["Hi, Hugo! How's it going?", "Hello, Hugo! How are you?", "Hey, Hugo! How are you?", "Hi, Hugo! How are things?"], de: ["Hallo, Hugo! Wie geht es dir?", "Hi, Hugo! Wie geht's?", "Hallo, Hugo! Wie geht es?"] } },
    { id: "u01.38", lesson: 6, fr: "Bonsoir, Madame. Comment allez-vous ?", en: "Good evening, madam. How are you?", de: "Guten Abend! Wie geht es Ihnen?", alt: { fr: ["Bonsoir, Madame. Vous allez bien ?", "Bonsoir, Madame. Comment ça va ?"], en: ["Good evening. How are you?", "Good evening, ma'am. How are you?", "Good evening, madam. How are you doing?"], de: ["Guten Abend! Wie geht's Ihnen?"] } },
    { id: "u01.39", lesson: 6, fr: "Au revoir, Madame Martin, et bonne journée !", en: "Goodbye, Mrs Martin, and have a nice day!", de: "Auf Wiedersehen, Frau Martin, und schönen Tag noch!", alt: { en: ["Goodbye, Mrs Martin, and have a good day!", "Bye, Mrs Martin, and have a nice day!", "Bye, Mrs Martin, and have a good day!"], de: ["Auf Wiedersehen, Frau Martin, und einen schönen Tag!", "Auf Wiedersehen, Frau Martin, und einen schönen Tag noch!", "Tschüss, Frau Martin, und schönen Tag noch!"] } },
    { id: "u01.40", lesson: 6, fr: "Et vous, Monsieur Martin ?", en: "And you, Mr Martin?", de: "Und Ihnen, Herr Martin?", alt: { en: ["What about you, Mr Martin?", "And yourself, Mr Martin?"], de: ["Und Sie, Herr Martin?"] } },
    // Lesson 7
    { id: "u01.41", lesson: 7, fr: "Il s'appelle Hugo.", en: "His name is Hugo.", de: "Er heißt Hugo.", alt: { en: ["He is called Hugo."], de: ["Sein Name ist Hugo."] } },
    { id: "u01.42", lesson: 7, fr: "Elle s'appelle comment ?", en: "What's her name?", de: "Wie heißt sie?", alt: { fr: ["Comment elle s'appelle ?", "Comment s'appelle-t-elle ?"], en: ["What is she called?"] } },
    { id: "u01.43", lesson: 7, fr: "Et elle, elle s'appelle Léa.", en: "And her name is Léa.", de: "Und sie heißt Léa.", alt: { fr: ["Et elle s'appelle Léa."], en: ["And she is called Léa.", "And her, her name is Léa."], de: ["Und ihr Name ist Léa."] } },
    { id: "u01.44", lesson: 7, fr: "Ça va ? Comme ci, comme ça.", en: "How are you? So-so.", de: "Wie geht's? So lala.", alt: { fr: ["Comment ça va ? Comme ci, comme ça."], en: ["How's it going? So-so.", "How are things? So-so."], de: ["Wie geht's? Geht so.", "Wie geht es dir? So lala.", "Wie geht es dir? Geht so.", "Wie geht's? Es geht."] } },
    { id: "u01.45", lesson: 7, fr: "Ça ne va pas, Hugo ?", en: "Aren't you well, Hugo?", de: "Geht's dir nicht gut, Hugo?", alt: { fr: ["Hugo, ça ne va pas ?", "Ça va pas, Hugo ?"], en: ["Are you not well, Hugo?", "Aren't you okay, Hugo?", "Are you not okay, Hugo?", "Aren't you feeling well, Hugo?", "Are you not feeling well, Hugo?", "Is something wrong, Hugo?", "Hugo, aren't you well?", "Hugo, are you not well?"], de: ["Geht es dir nicht gut, Hugo?", "Hugo, geht's dir nicht gut?", "Hugo, geht es dir nicht gut?", "Ist was, Hugo?"] } },
    { id: "u01.46", lesson: 7, fr: "Non, ça ne va pas très bien.", en: "No, I'm not very well.", de: "Nein, mir geht's nicht so gut.", alt: { fr: ["Non, ça va pas très bien."], en: ["No, I am not doing very well.", "No, not very well.", "No, I'm not too well.", "No, I am not feeling very well."], de: ["Nein, es geht mir nicht so gut.", "Nein, mir geht es nicht so gut.", "Nein, mir geht's nicht sehr gut.", "Nein, mir geht es nicht sehr gut.", "Nein, es geht mir nicht sehr gut.", "Nein, nicht so gut.", "Nein, nicht sehr gut."] } },
    { id: "u01.47", lesson: 7, fr: "Tu es Léa ? Non, je suis Emma.", en: "Are you Léa? No, I'm Emma.", de: "Bist du Léa? Nein, ich bin Emma.", alt: { fr: ["Tu es Léa ? Non, je m'appelle Emma.", "Es-tu Léa ? Non, je suis Emma.", "Est-ce que tu es Léa ? Non, je suis Emma.", "Vous êtes Léa ? Non, je suis Emma."], en: ["Are you Léa? No, my name is Emma.", "Are you Léa? No, I am called Emma.", "You are Léa? No, I am Emma."], de: ["Bist du Léa? Nein, ich heiße Emma.", "Du bist Léa? Nein, ich bin Emma."] } },
    { id: "u01.48", lesson: 7, fr: "Il s'appelle Blob, et elle s'appelle Léa.", en: "His name is Blob, and her name is Léa.", de: "Er heißt Blob, und sie heißt Léa.", alt: { en: ["He is called Blob, and she is called Léa.", "His name is Blob, and she is called Léa.", "He is called Blob, and her name is Léa."], de: ["Sein Name ist Blob, und ihr Name ist Léa."] } },
  ],
  drills: [
    { id: "u01.d1", lesson: 3, fr: "Je ___ Blob.", options: ["suis", "es", "est"], answer: 0, en: "I am Blob.", de: "Ich bin Blob.", why: tx("With **je** (I), être is **suis**: je suis.", "Mit **je** (ich) heißt être **suis**: je suis.") },
    { id: "u01.d2", lesson: 3, fr: "Tu ___ Léa ?", options: ["es", "suis", "est"], answer: 0, en: "Are you Léa?", de: "Bist du Léa?", why: tx("With **tu** (you), it's **es**: tu es.", "Mit **tu** (du) heißt es **es**: tu es.") },
    { id: "u01.d3", lesson: 3, fr: "Je m'___ Hugo.", options: ["appelle", "appelles", "appeler"], answer: 0, en: "My name is Hugo.", de: "Ich heiße Hugo.", why: tx("With **je** the ending is **-e**: je m'appell**e**.", "Mit **je** endet es auf **-e**: je m'appell**e**.") },
    { id: "u01.d4", lesson: 3, fr: "Tu t'___ comment ?", options: ["appelles", "appelle", "appeler"], answer: 0, en: "What's your name?", de: "Wie heißt du?", why: tx("With **tu** the ending is **-es**: tu t'appell**es**. You don't hear the s.", "Mit **tu** endet es auf **-es**: tu t'appell**es**. Das s hört man nicht.") },
    { id: "u01.d5", lesson: 3, fr: "Léa : « ___, Hugo ! »", options: ["Enchantée", "Enchanté"], answer: 0, en: "Léa: «Nice to meet you, Hugo!»", de: "Léa: „Freut mich, Hugo!“", why: tx("Léa is a girl, so she writes **enchantée** with an extra e. Hugo writes enchanté.", "Léa ist ein Mädchen, darum schreibt sie **enchantée** mit einem e mehr. Hugo schreibt enchanté.") },
    { id: "u01.d6", lesson: 2, fr: "Il est 21 heures : « ___, Madame ! »", options: ["Bonsoir", "Bonjour", "Salut"], answer: 0, en: "It's 9 pm: «Good evening, madam!»", de: "Es ist 21 Uhr: „Guten Abend!“", why: tx("In the evening it's **bonsoir**. Bonjour is for the day, salut only for friends.", "Am Abend sagt man **bonsoir**. Bonjour ist für den Tag, salut nur für Freunde.") },
    { id: "u01.d7", lesson: 4, fr: "Ça va ___ bien !", options: ["très", "beaucoup"], answer: 0, en: "I'm very well!", de: "Mir geht's sehr gut!", why: tx("**Très** means very: très bien. Beaucoup goes with merci: merci beaucoup.", "**Très** heißt sehr: très bien. Beaucoup gehört zu merci: merci beaucoup.") },
    { id: "u01.d8", lesson: 2, fr: "Merci ___ !", options: ["beaucoup", "très"], answer: 0, en: "Thank you very much!", de: "Vielen Dank!", why: tx("Thank you very much is **merci beaucoup**. (Très goes with words like bien: très bien.)", "Vielen Dank heißt **merci beaucoup**. (Très steht vor Wörtern wie bien: très bien.)") },
    { id: "u01.d9", lesson: 4, fr: "Comment ça ___ ?", options: ["va", "es", "suis"], answer: 0, en: "How are you?", de: "Wie geht's?", why: tx("**Ça va** means «it goes». Comment ça va ? = How is it going?", "**Ça va** heißt „es geht“. Comment ça va ? = Wie geht's?") },
    { id: "u01.d10", lesson: 4, fr: "— Ça va bien ! — Moi ___ !", options: ["aussi", "très", "toi"], answer: 0, en: "— I'm fine! — Me too!", de: "— Mir geht's gut! — Mir auch!", why: tx("**Moi aussi** = me too.", "**Moi aussi** = ich auch / mir auch.") },
    { id: "u01.d11", lesson: 6, fr: "Bonjour, Madame Martin. Comment allez-___ ?", options: ["vous", "tu"], answer: 0, en: "Hello, Mrs Martin. How are you?", de: "Guten Tag, Frau Martin. Wie geht es Ihnen?", why: tx("Allez goes with **vous**: comment allez-**vous** ? It's the polite question for adults like Mrs Martin.", "Allez gehört zu **vous**: comment allez-**vous** ? Das ist die höfliche Frage für Erwachsene wie Frau Martin.") },
    { id: "u01.d12", lesson: 6, fr: "Très bien, merci. Et ___, Madame ?", options: ["vous", "tu"], answer: 0, en: "Very well, thank you. And you, madam?", de: "Sehr gut, danke. Und Ihnen?", why: tx("Alone after et, it's **vous** (polite) or toi (for friends), never tu: et **vous** ?", "Allein nach et steht **vous** (höflich) oder toi (für Freunde), nie tu: et **vous** ?") },
    { id: "u01.d13", lesson: 6, fr: "Au revoir, Monsieur. ___ journée !", options: ["Bonne", "Bon"], answer: 0, en: "Goodbye, sir. Have a nice day!", de: "Auf Wiedersehen. Schönen Tag noch!", why: tx("Journée is feminine, so it's **bonne** journée. Bonjour is bon + jour.", "Journée ist weiblich, darum **bonne** journée. Bonjour ist bon + jour.") },
    { id: "u01.d14", lesson: 7, fr: "Et lui ? Il s'___ Hugo.", options: ["appelle", "appelles", "appeler"], answer: 0, en: "And him? His name is Hugo.", de: "Und er? Er heißt Hugo.", why: tx("With il or elle the ending is **-e**, just like with je: il s'appell**e**.", "Mit il oder elle endet es auf **-e**, genau wie bei je: il s'appell**e**.") },
    { id: "u01.d15", lesson: 7, fr: "Et elle ? ___ s'appelle Léa.", options: ["Elle", "Il", "Je"], answer: 0, en: "And her? Her name is Léa.", de: "Und sie? Sie heißt Léa.", why: tx("Léa is a girl: **elle** s'appelle Léa. For a boy: il s'appelle Hugo.", "Léa ist ein Mädchen: **elle** s'appelle Léa. Bei einem Jungen: il s'appelle Hugo.") },
    { id: "u01.d16", lesson: 7, fr: "Non, ça ___ va pas très bien.", options: ["ne", "pas", "non"], answer: 0, en: "No, I'm not very well.", de: "Nein, mir geht's nicht so gut.", why: tx("Not comes in two parts around the verb: ça **ne** va **pas**.", "Nicht hat zwei Teile um das Verb herum: ça **ne** va **pas**.") },
  ],
  dialogues: [
    {
      id: "u01.dialogue",
      lesson: 5,
      title: tx("Blob meets Léa and Hugo", "Blob trifft Léa und Hugo"),
      lines: [
        { who: "blob", fr: "Bonjour ! Je m'appelle Blob. Et toi ?", en: "Hello! My name is Blob. And you?", de: "Hallo! Ich heiße Blob. Und du?" },
        { who: "lea", fr: "Salut, Blob ! Je m'appelle Léa.", en: "Hi, Blob! My name is Léa.", de: "Hallo, Blob! Ich heiße Léa." },
        { who: "blob", fr: "Enchanté, Léa ! Comment ça va ?", en: "Nice to meet you, Léa! How are you?", de: "Freut mich, Léa! Wie geht's?" },
        { who: "lea", fr: "Ça va bien, merci. Et toi ?", en: "I'm fine, thank you. And you?", de: "Mir geht's gut, danke. Und dir?" },
        { who: "blob", fr: "Très bien ! Salut, toi ! Tu t'appelles comment ?", en: "Very well! Hi there! What's your name?", de: "Sehr gut! Hallo, du! Wie heißt du?" },
        { who: "hugo", fr: "Je m'appelle Hugo. Enchanté, Blob !", en: "My name is Hugo. Nice to meet you, Blob!", de: "Ich heiße Hugo. Freut mich, Blob!" },
        { who: "lea", fr: "Au revoir, Blob ! À bientôt !", en: "Goodbye, Blob! See you soon!", de: "Tschüss, Blob! Bis bald!" },
        { who: "blob", fr: "Au revoir ! Merci !", en: "Goodbye! Thank you!", de: "Auf Wiedersehen! Danke!" },
      ],
      questions: [
        { q: tx("What is the girl called?", "Wie heißt das Mädchen?"), options: ["Léa", "Hugo", tx("Mrs Martin", "Frau Martin")], answer: 0 },
        { q: tx("How is Léa?", "Wie geht es Léa?"), options: [tx("She is fine.", "Ihr geht es gut."), tx("She is not well.", "Ihr geht es schlecht."), tx("She doesn't say.", "Sie sagt es nicht.")], answer: 0 },
        { q: tx("What does Léa say at the end?", "Was sagt Léa am Ende?"), options: [tx("Goodbye, see you soon!", "Tschüss, bis bald!"), tx("Good evening!", "Guten Abend!"), tx("Thank you very much!", "Vielen Dank!")], answer: 0 },
      ],
    },
    {
      id: "u01.dialogue2",
      lesson: 7,
      title: tx("Polite Blob", "Der höfliche Blob"),
      lines: [
        { who: "blob", fr: "Bonjour, Madame Martin ! Comment allez-vous ?", en: "Hello, Mrs Martin! How are you?", de: "Guten Tag, Frau Martin! Wie geht es Ihnen?" },
        { who: "madame", fr: "Très bien, merci, Blob. Bonne journée !", en: "Very well, thank you, Blob. Have a nice day!", de: "Sehr gut, danke, Blob. Schönen Tag noch!" },
        { who: "blob", fr: "Bonne journée ! Et bonjour, Hugo. Comment allez-vous ?", en: "Have a nice day! And hello, Hugo. How are you?", de: "Schönen Tag noch! Und guten Tag, Hugo. Wie geht es Ihnen?" },
        { who: "hugo", fr: "Vous ? Blob, je suis Hugo, pas Monsieur Martin !", en: "«Vous»? Blob, I'm Hugo, not Mr Martin!", de: "Sie? Blob, ich bin Hugo, nicht Herr Martin!" },
        { who: "blob", fr: "Pardon ! Salut, Hugo ! Ça va ?", en: "Sorry! Hi, Hugo! How's it going?", de: "Entschuldigung! Hallo, Hugo! Wie geht's?" },
        { who: "hugo", fr: "Comme ci, comme ça.", en: "So-so.", de: "So lala." },
        { who: "blob", fr: "Et Madame Martin, elle s'appelle comment ?", en: "And what's Mrs Martin's first name?", de: "Und wie heißt Frau Martin mit Vornamen?" },
        { who: "hugo", fr: "Madame Martin ? Elle s'appelle Anne.", en: "Mrs Martin? Her name is Anne.", de: "Frau Martin? Sie heißt Anne." },
        { who: "blob", fr: "Salut, Anne ! Bonne journée !", en: "Hi, Anne! Have a nice day!", de: "Hallo, Anne! Schönen Tag noch!" },
        { who: "hugo", fr: "Non, Blob ! Avec Madame Martin, c'est « bonjour » et « vous » !", en: "No, Blob! With Mrs Martin, it's «bonjour» and «vous»!", de: "Nein, Blob! Bei Frau Martin heißt es „bonjour“ und „vous“!" },
      ],
      questions: [
        { q: tx("How is Mrs Martin?", "Wie geht es Frau Martin?"), options: [tx("Very well", "Sehr gut"), tx("So-so", "So lala"), tx("Not well", "Nicht gut")], answer: 0 },
        { q: tx("How is Hugo?", "Wie geht es Hugo?"), options: [tx("So-so", "So lala"), tx("Very well", "Sehr gut"), tx("He doesn't say.", "Er sagt es nicht.")], answer: 0 },
        { q: tx("What does Blob get wrong?", "Was macht Blob falsch?"), options: [tx("He says vous to Hugo and «salut, Anne» to Mrs Martin.", "Er sagt vous zu Hugo und „salut, Anne“ zu Frau Martin."), tx("He forgets Hugo's name.", "Er vergisst Hugos Namen."), tx("He says good evening in the morning.", "Er sagt morgens guten Abend.")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Hello and goodbye", "Hallo und tschüss"),
      body: tx(
        "**Bonjour** is the safe hello: for teachers, shops and people you don't know, all day long. With friends you say **salut**, which also means bye.\n\nIn the evening, **bonsoir**. To leave: **au revoir**, or **à bientôt** (see you soon).",
        "**Bonjour** ist das sichere Hallo: für Lehrer, Geschäfte und Leute, die du nicht kennst, den ganzen Tag. Unter Freunden sagst du **salut**, das heißt auch tschüss.\n\nAm Abend: **bonsoir**. Zum Abschied: **au revoir** oder **à bientôt** (bis bald).",
      ),
      examples: [
        { fr: "Bonjour, Madame Martin !", en: "Hello, Mrs Martin!", de: "Guten Tag, Frau Martin!" },
        { fr: "Salut, Hugo !", en: "Hi, Hugo!", de: "Hallo, Hugo!" },
        { fr: "Au revoir et à bientôt !", en: "Goodbye and see you soon!", de: "Tschüss und bis bald!" },
      ],
    },
    {
      title: tx("Je suis, tu es: I am, you are", "Je suis, tu es: ich bin, du bist"),
      body: tx(
        "**Être** (to be) is the most important verb. Start with two forms: **je suis** (I am) and **tu es** (you are).\n\nYour name: **je m'appelle** Léa, literally «I call myself Léa». Asking: **tu t'appelles comment ?**",
        "**Être** (sein) ist das wichtigste Verb. Fang mit zwei Formen an: **je suis** (ich bin) und **tu es** (du bist).\n\nDein Name: **je m'appelle** Léa, wörtlich „ich nenne mich Léa“. Fragen: **tu t'appelles comment ?**",
      ),
      examples: [
        { fr: "Je suis Blob.", en: "I am Blob.", de: "Ich bin Blob." },
        { fr: "Tu es Léa ?", en: "Are you Léa?", de: "Bist du Léa?" },
        { fr: "Je m'appelle Hugo.", en: "My name is Hugo.", de: "Ich heiße Hugo." },
      ],
      table: {
        head: [tx("person", "Person"), "être", "s'appeler"],
        rows: [
          [tx("I", "ich"), "je suis", "je m'appelle"],
          [tx("you", "du"), "tu es", "tu t'appelles"],
        ],
      },
    },
    {
      title: tx("Ça va? How are you?", "Ça va? Wie geht's?"),
      body: tx(
        "**Ça va ?** is the everyday «how are you?». The answer is the same words: **ça va** (I'm fine). Add **bien** (well) or **très bien** (very well), and ask back: **et toi ?**\n\nA girl writes **enchantée**, a boy **enchanté**: it sounds the same.",
        "**Ça va ?** ist das alltägliche „Wie geht's?“. Die Antwort sind dieselben Wörter: **ça va** (gut). Mit **bien** (gut) oder **très bien** (sehr gut) und zurückfragen: **et toi ?**\n\nEin Mädchen schreibt **enchantée**, ein Junge **enchanté**: Es klingt gleich.",
      ),
      examples: [
        { fr: "Comment ça va ?", en: "How are you?", de: "Wie geht's?" },
        { fr: "Ça va bien, merci. Et toi ?", en: "I'm fine, thank you. And you?", de: "Mir geht's gut, danke. Und dir?" },
        { fr: "Moi aussi !", en: "Me too!", de: "Ich auch!" },
      ],
    },
    {
      title: tx("Tu or vous?", "Tu oder vous?"),
      body: tx(
        "**Tu** is for friends, family and children. For adults you don't know well, like Mrs Martin, say **vous**: it's polite, like Sie in German. So it's **comment allez-vous ?** and **et vous ?**, and when you leave: **bonne journée !**\n\nAbout someone else: **il s'appelle** Hugo, **elle s'appelle** Léa.\n\nNot so great today? **Comme ci, comme ça** (so-so), or **ça ne va pas** (I'm not well).",
        "**Tu** sagst du zu Freunden, zur Familie und zu Kindern. Zu Erwachsenen, die du nicht gut kennst, wie Frau Martin, sagst du **vous**: Das ist höflich, wie Sie im Deutschen. Also **comment allez-vous ?** und **et vous ?**, und zum Abschied: **bonne journée !**\n\nÜber andere: **il s'appelle** Hugo, **elle s'appelle** Léa.\n\nHeute nicht so gut? **Comme ci, comme ça** (so lala) oder **ça ne va pas** (mir geht's nicht gut).",
      ),
      examples: [
        { fr: "Bonjour, Madame Martin. Comment allez-vous ?", en: "Hello, Mrs Martin. How are you?", de: "Guten Tag, Frau Martin. Wie geht es Ihnen?" },
        { fr: "Salut, Hugo ! Ça va ?", en: "Hi, Hugo! How are you?", de: "Hallo, Hugo! Wie geht's?" },
        { fr: "Elle s'appelle Léa.", en: "Her name is Léa.", de: "Sie heißt Léa." },
        { fr: "Ça va ? Comme ci, comme ça.", en: "How are you? So-so.", de: "Wie geht's? So lala." },
      ],
      table: {
        head: [tx("meaning", "Bedeutung"), tx("friends: tu", "Freunde: tu"), tx("polite: vous", "höflich: vous")],
        rows: [
          [tx("hello", "hallo"), "salut", "bonjour"],
          [tx("how are you?", "wie geht's?"), "ça va ?", "comment allez-vous ?"],
          [tx("and you?", "und du? / und Ihnen?"), "et toi ?", "et vous ?"],
        ],
      },
    },
  ],
};
