import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 2: who people are, where they're from, être in all its forms, c'est and ne … pas. */
export const u02: Unit = {
  slug: "qui-es-tu",
  n: 2,
  cefr: "A1",
  title: tx("Who's who?", "Wer ist wer?"),
  goal: tx("Say who people are and where they're from, and say what something is not", "Sagen, wer jemand ist und woher er kommt, und sagen, was etwas nicht ist"),
  emoji: "🧑‍🤝‍🧑",
  words: [
    { id: "c-est", fr: "c'est", en: "this is", de: "das ist", alt: { en: ["it is", "that is"], de: ["es ist"] }, kind: "phrase", note: tx("Ce + est: the e drops before a vowel. Use it with names: c'est Hugo.", "Ce + est: Das e fällt vor einem Vokal weg. Mit Namen: c'est Hugo.") },
    { id: "qui-est-ce", fr: "qui est-ce ?", en: "who is it?", de: "wer ist das?", alt: { en: ["who's that?", "who is this?"], de: ["wer ist es?"] }, kind: "phrase", note: tx("Friends often just say «c'est qui ?».", "Unter Freunden sagt man oft einfach „c'est qui ?“.") },
    { id: "il-est", fr: "il est", en: "he is", de: "er ist", kind: "phrase" },
    { id: "elle-est", fr: "elle est", en: "she is", de: "sie ist", kind: "phrase" },
    { id: "sympa", fr: "sympa", en: "nice", de: "nett", alt: { en: ["friendly"], de: ["sympathisch"] }, kind: "adj", note: tx("Short for sympathique. The same for boys and girls: il est sympa, elle est sympa.", "Kurz für sympathique. Gleich für Jungen und Mädchen: il est sympa, elle est sympa.") },
    { id: "garcon", fr: "le garçon", en: "the boy", de: "der Junge", g: "m", kind: "noun", emoji: "👦", note: tx("The ç sounds like an s: gar-SON.", "Das ç klingt wie ein scharfes s: gar-SON.") },
    { id: "fille", fr: "la fille", en: "the girl", de: "das Mädchen", alt: { en: ["the daughter"], de: ["die Tochter"] }, g: "f", kind: "noun", emoji: "👧", note: tx("La fille also means the daughter.", "La fille heißt auch die Tochter.") },
    { id: "ami", fr: "l'ami", en: "the friend", de: "der Freund", g: "m", kind: "noun", note: tx("Before a vowel, le and la shrink to l': l'ami.", "Vor einem Vokal werden le und la zu l': l'ami.") },
    { id: "amie", fr: "l'amie", en: "the friend (female)", de: "die Freundin", g: "f", kind: "noun", note: tx("Sounds just like l'ami: only the spelling shows it's a girl.", "Klingt genau wie l'ami: Nur die Schreibung zeigt, dass es ein Mädchen ist.") },
    { id: "content", fr: "content", en: "happy", de: "froh", alt: { en: ["glad", "pleased"], de: ["zufrieden"] }, kind: "adj", emoji: "😃", note: tx("It means happy or glad. A girl is contente, and then you hear the t.", "Heißt froh. Ein Mädchen ist contente, dann hört man das t.") },
    { id: "fatigue", fr: "fatigué", en: "tired", de: "müde", kind: "adj", emoji: "😴", note: tx("A girl is fatiguée: it sounds just the same.", "Ein Mädchen ist fatiguée: Es klingt genau gleich.") },
    { id: "d-ou", fr: "tu es d'où ?", en: "where are you from?", de: "woher kommst du?", alt: { fr: ["d'où es-tu ?"], de: ["wo kommst du her?"] }, kind: "phrase", note: tx("D'où = de + où: from where. The answer: je suis de Paris.", "D'où = de + où: woher. Die Antwort: je suis de Paris.") },
    { id: "francais", fr: "français", en: "French", de: "französisch", alt: { de: ["Franzose", "Französin"] }, kind: "adj", emoji: "🇫🇷", note: tx("A girl is française: now you hear the s, like a z.", "Ein Mädchen ist française: Jetzt hört man das s, weich wie in „Rose“.") },
    { id: "allemand", fr: "allemand", en: "German", de: "deutsch", alt: { de: ["Deutscher", "Deutsche"] }, kind: "adj", emoji: "🇩🇪", note: tx("A girl is allemande: now you hear the d.", "Ein Mädchen ist allemande: Jetzt hört man das d.") },
    { id: "anglais", fr: "anglais", en: "English", de: "englisch", alt: { de: ["Engländer", "Engländerin"] }, kind: "adj", emoji: "🇬🇧", note: tx("French writes nationalities with a small letter: anglais, not Anglais.", "Im Französischen schreibt man Nationalitäten klein: anglais.") },
    { id: "suisse", fr: "suisse", en: "Swiss", de: "schweizerisch", alt: { de: ["Schweizer", "Schweizerin"] }, kind: "adj", emoji: "🇨🇭", note: tx("It already ends in -e, so it's the same for boys and girls.", "Es endet schon auf -e, also gleich für Jungen und Mädchen.") },
    { id: "nous-sommes", fr: "nous sommes", en: "we are", de: "wir sind", kind: "phrase" },
    { id: "vous-etes", fr: "vous êtes", en: "you are (plural / polite)", de: "ihr seid / Sie sind", kind: "phrase", note: tx("For several people, or politely for one adult: Monsieur Martin, vous êtes…", "Für mehrere Leute (ihr) oder höflich für einen Erwachsenen (Sie): Monsieur Martin, vous êtes …") },
    { id: "ils-sont", fr: "ils sont", en: "they are", de: "sie sind", kind: "phrase", note: tx("Ils for boys or a mixed group. Only girls or women: elles sont.", "Ils für Jungen oder gemischte Gruppen. Nur Mädchen oder Frauen: elles sont.") },
    { id: "elles-sont", fr: "elles sont", en: "they are (all female)", de: "sie sind (alle weiblich)", kind: "phrase" },
    { id: "ne-pas", fr: "ne … pas", en: "not", de: "nicht", kind: "word", note: tx("Two parts around the verb: je ne suis pas. Before a vowel: elle n'est pas.", "Zwei Teile um das Verb herum: je ne suis pas. Vor einem Vokal: elle n'est pas.") },
    { id: "un-peu", fr: "un peu", en: "a bit", de: "ein bisschen", alt: { en: ["a little"], de: ["etwas"] }, kind: "adv", emoji: "🤏" },
    { id: "voisin", fr: "le voisin", en: "the neighbour", de: "der Nachbar", g: "m", kind: "noun" },
    { id: "voisine", fr: "la voisine", en: "the neighbour (female)", de: "die Nachbarin", g: "f", kind: "noun" },
  ],
  gloss: [
    { fr: "sommes", en: "are (we)", de: "sind (wir)" },
    { fr: "êtes", en: "are (you, plural / polite)", de: "seid / sind (Sie)" },
    { fr: "contente", en: "happy (feminine)", de: "froh (weiblich)" },
    { fr: "fatiguée", en: "tired (feminine)", de: "müde (weiblich)" },
    { fr: "fatigués", en: "tired (plural)", de: "müde (Plural)" },
    { fr: "fatiguées", en: "tired (feminine plural)", de: "müde (weiblich, Plural)" },
    { fr: "française", en: "French (feminine)", de: "französisch (weiblich)" },
    { fr: "allemande", en: "German (feminine)", de: "deutsch (weiblich)" },
    { fr: "allemands", en: "German (plural)", de: "deutsch (Plural)" },
    { fr: "anglaise", en: "English (feminine)", de: "englisch (weiblich)" },
    { fr: "sympas", en: "nice (plural)", de: "nett (Plural)" },
    { fr: "regarde", en: "look", de: "schau" },
    { fr: "béret", en: "beret", de: "Baskenmütze" },
    { fr: "passeport", en: "passport", de: "Pass" },
    { fr: "violet", en: "purple", de: "lila" },
  ],
  lessons: [
    { title: tx("Who's that?", "Wer ist das?"), words: ["c-est", "qui-est-ce", "il-est", "elle-est", "sympa"] },
    { title: tx("Friends", "Freunde"), words: ["garcon", "fille", "ami", "amie", "content", "fatigue"] },
    { title: tx("Where are you from?", "Woher kommst du?"), words: ["d-ou", "francais", "allemand", "anglais", "suisse"] },
    { title: tx("We, you, they", "Wir, ihr, sie"), words: ["nous-sommes", "vous-etes", "ils-sont", "elles-sont"] },
    { title: tx("It's not Hugo!", "Das ist nicht Hugo!"), words: ["ne-pas", "un-peu", "voisin", "voisine"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u02.01", lesson: 1, fr: "Qui est-ce ? C'est Hugo.", en: "Who's that? It's Hugo.", de: "Wer ist das? Das ist Hugo.", alt: { fr: ["C'est qui ? C'est Hugo.", "Qui c'est ? C'est Hugo."], en: ["Who is that? That is Hugo.", "Who is it? It is Hugo.", "Who is this? This is Hugo.", "Who is this? It is Hugo.", "Who is it? That is Hugo.", "Who is that? This is Hugo."], de: ["Wer ist das? Es ist Hugo.", "Wer ist es? Das ist Hugo.", "Wer ist es? Es ist Hugo."] } },
    { id: "u02.02", lesson: 1, fr: "Il est sympa.", en: "He is nice.", de: "Er ist nett.", alt: { fr: ["Il est sympathique.", "Il est gentil."], en: ["He is friendly."], de: ["Er ist sympathisch.", "Er ist freundlich."] } },
    { id: "u02.03", lesson: 1, fr: "C'est Léa, elle est très sympa.", en: "This is Léa, she is very nice.", de: "Das ist Léa, sie ist sehr nett.", alt: { fr: ["C'est Léa, elle est très sympathique.", "C'est Léa, elle est très gentille."], en: ["That is Léa, she is very nice.", "It is Léa, she is very nice.", "This is Léa, she is really nice.", "That is Léa, she is really nice.", "This is Léa, she is very friendly.", "That is Léa, she is very friendly."], de: ["Das ist Léa, sie ist sehr sympathisch.", "Das ist Léa, sie ist sehr freundlich."] } },
    { id: "u02.04", lesson: 1, fr: "C'est Monsieur Martin ? Oui, c'est lui.", en: "Is that Mr Martin? Yes, it's him.", de: "Ist das Herr Martin? Ja, das ist er.", alt: { fr: ["Est-ce que c'est Monsieur Martin ? Oui, c'est lui.", "Est-ce Monsieur Martin ? Oui, c'est lui."], en: ["Is it Mr Martin? Yes, it is him.", "Is that Mr Martin? Yes, that is him.", "Is this Mr Martin? Yes, it is him.", "Is that Mr Martin? Yes, it is.", "Is it Mr Martin? Yes, it is."], de: ["Ist das Herr Martin? Ja, er ist es.", "Ist es Herr Martin? Ja, das ist er."] } },
    { id: "u02.05", lesson: 1, fr: "Elle est sympa, Madame Martin.", en: "Mrs Martin is nice.", de: "Frau Martin ist nett.", alt: { fr: ["Madame Martin est sympa.", "Madame Martin, elle est sympa."], en: ["She is nice, Mrs Martin.", "Mrs Martin is friendly."], de: ["Sie ist nett, Frau Martin.", "Frau Martin ist sympathisch.", "Frau Martin ist freundlich."] } },
    { id: "u02.06", lesson: 1, fr: "C'est sympa !", en: "That's nice!", de: "Das ist nett!", alt: { fr: ["C'est sympathique !", "C'est gentil !"], en: ["It is nice!", "How nice!", "That is kind!"], de: ["Wie nett!", "Das ist lieb!"] } },
    { id: "u02.07", lesson: 1, fr: "Il s'appelle comment ?", en: "What's his name?", de: "Wie heißt er?", alt: { fr: ["Comment il s'appelle ?", "Comment s'appelle-t-il ?"], en: ["What is he called?"] } },
    // Lesson 2
    { id: "u02.08", lesson: 2, fr: "C'est un garçon ou une fille ?", en: "Is it a boy or a girl?", de: "Ist das ein Junge oder ein Mädchen?", alt: { fr: ["Est-ce un garçon ou une fille ?", "Est-ce que c'est un garçon ou une fille ?"], en: ["Is that a boy or a girl?", "Is this a boy or a girl?"], de: ["Ist es ein Junge oder ein Mädchen?"] } },
    { id: "u02.09", lesson: 2, fr: "Hugo, c'est un ami.", en: "Hugo is a friend.", de: "Hugo ist ein Freund.", alt: { fr: ["Hugo est un ami.", "C'est un ami, Hugo."], en: ["Hugo is a friend of mine."], de: ["Hugo ist ein Kumpel."] } },
    { id: "u02.10", lesson: 2, fr: "Léa est une amie très sympa.", en: "Léa is a very nice friend.", de: "Léa ist eine sehr nette Freundin.", alt: { fr: ["Léa, c'est une amie très sympa.", "C'est une amie très sympa, Léa."], en: ["Léa is a really nice friend."], de: ["Léa ist eine sehr sympathische Freundin."] } },
    { id: "u02.11", lesson: 2, fr: "Je suis fatigué.", en: "I am tired.", de: "Ich bin müde.", alt: { fr: ["Je suis fatiguée."] } },
    { id: "u02.12", lesson: 2, fr: "Tu es contente, Léa ?", en: "Are you happy, Léa?", de: "Bist du froh, Léa?", alt: { fr: ["Léa, tu es contente ?", "Es-tu contente, Léa ?", "Est-ce que tu es contente, Léa ?", "Vous êtes contente, Léa ?", "Êtes-vous contente, Léa ?"], en: ["Léa, are you happy?", "Are you glad, Léa?", "Are you pleased, Léa?", "You are happy, Léa?"], de: ["Léa, bist du froh?", "Bist du zufrieden, Léa?", "Bist du glücklich, Léa?", "Du bist froh, Léa?"] } },
    { id: "u02.13", lesson: 2, fr: "Le garçon est très content.", en: "The boy is very happy.", de: "Der Junge ist sehr froh.", alt: { en: ["The boy is very glad.", "The boy is really happy.", "The boy is very pleased."], de: ["Der Junge ist sehr glücklich.", "Der Junge ist sehr zufrieden."] } },
    { id: "u02.14", lesson: 2, fr: "Elle est fatiguée, mais contente.", en: "She is tired, but happy.", de: "Sie ist müde, aber froh.", alt: { en: ["She is tired, but glad.", "She is tired, but pleased."], de: ["Sie ist müde, aber zufrieden.", "Sie ist müde, aber glücklich."] } },
    // Lesson 3
    { id: "u02.15", lesson: 3, fr: "Tu es d'où ?", en: "Where are you from?", de: "Woher kommst du?", alt: { fr: ["D'où es-tu ?", "D'où tu es ?", "Tu viens d'où ?", "D'où viens-tu ?", "Vous êtes d'où ?", "D'où êtes-vous ?", "Vous venez d'où ?", "D'où venez-vous ?"], en: ["Where do you come from?"], de: ["Wo kommst du her?", "Woher bist du?"] } },
    { id: "u02.16", lesson: 3, fr: "Je suis de Paris.", en: "I am from Paris.", de: "Ich bin aus Paris.", alt: { fr: ["Je viens de Paris."], en: ["I come from Paris."], de: ["Ich komme aus Paris."] } },
    { id: "u02.17", lesson: 3, fr: "Léa est française, elle est de Lyon.", en: "Léa is French, she is from Lyon.", de: "Léa ist Französin, sie ist aus Lyon.", alt: { fr: ["Léa est française, elle vient de Lyon."], en: ["Léa is French, she comes from Lyon.", "Léa is French and she is from Lyon.", "Léa is French, from Lyon."], de: ["Léa ist Französin, sie kommt aus Lyon.", "Léa ist Französin und kommt aus Lyon."] } },
    { id: "u02.18", lesson: 3, fr: "Max est allemand, il est de Berlin.", en: "Max is German, he is from Berlin.", de: "Max ist Deutscher, er ist aus Berlin.", alt: { fr: ["Max est allemand, il vient de Berlin."], en: ["Max is German, he comes from Berlin.", "Max is German and he is from Berlin.", "Max is German, from Berlin."], de: ["Max ist Deutscher, er kommt aus Berlin.", "Max ist Deutscher und kommt aus Berlin."] } },
    { id: "u02.19", lesson: 3, fr: "Tu es anglaise, Emma ?", en: "Are you English, Emma?", de: "Bist du Engländerin, Emma?", alt: { fr: ["Emma, tu es anglaise ?", "Es-tu anglaise, Emma ?", "Est-ce que tu es anglaise, Emma ?", "Vous êtes anglaise, Emma ?", "Êtes-vous anglaise, Emma ?"], en: ["Emma, are you English?", "You are English, Emma?"], de: ["Emma, bist du Engländerin?", "Du bist Engländerin, Emma?"] } },
    { id: "u02.20", lesson: 3, fr: "Je suis suisse, et toi ?", en: "I am Swiss, and you?", de: "Ich bin Schweizer, und du?", alt: { fr: ["Je suis suisse, et vous ?"], en: ["I am Swiss, what about you?", "I am Swiss, and yourself?"], de: ["Ich bin Schweizerin, und du?"] } },
    { id: "u02.21", lesson: 3, fr: "Il est français ou allemand ?", en: "Is he French or German?", de: "Ist er Franzose oder Deutscher?", alt: { fr: ["Est-il français ou allemand ?", "Est-ce qu'il est français ou allemand ?"], en: ["He is French or German?"] } },
    // Lesson 4
    { id: "u02.22", lesson: 4, fr: "Nous sommes français.", en: "We are French.", de: "Wir sind Franzosen.", alt: { fr: ["Nous sommes françaises.", "On est français.", "On est françaises."], de: ["Wir sind Französinnen."] } },
    { id: "u02.23", lesson: 4, fr: "Monsieur Martin, vous êtes d'où ?", en: "Mr Martin, where are you from?", de: "Herr Martin, woher kommen Sie?", alt: { fr: ["Vous êtes d'où, Monsieur Martin ?", "Monsieur Martin, d'où êtes-vous ?", "D'où êtes-vous, Monsieur Martin ?", "Monsieur Martin, vous venez d'où ?", "Monsieur Martin, d'où venez-vous ?"], en: ["Where are you from, Mr Martin?", "Mr Martin, where do you come from?", "Where do you come from, Mr Martin?"], de: ["Woher kommen Sie, Herr Martin?", "Herr Martin, wo kommen Sie her?"] } },
    { id: "u02.24", lesson: 4, fr: "Ils sont allemands.", en: "They are German.", de: "Sie sind Deutsche.", alt: { fr: ["Elles sont allemandes."] } },
    { id: "u02.25", lesson: 4, fr: "Elles sont très fatiguées.", en: "They are very tired.", de: "Sie sind sehr müde.", alt: { fr: ["Ils sont très fatigués."], en: ["They are really tired."] } },
    { id: "u02.26", lesson: 4, fr: "Hugo et Léa, vous êtes fatigués ?", en: "Hugo and Léa, are you tired?", de: "Hugo und Léa, seid ihr müde?", alt: { fr: ["Hugo et Léa, êtes-vous fatigués ?", "Vous êtes fatigués, Hugo et Léa ?", "Hugo et Léa, est-ce que vous êtes fatigués ?"], en: ["Are you tired, Hugo and Léa?", "Hugo and Léa, you are tired?"], de: ["Seid ihr müde, Hugo und Léa?"] } },
    { id: "u02.27", lesson: 4, fr: "Vous êtes anglais ?", en: "Are you English?", de: "Seid ihr Engländer?", alt: { fr: ["Êtes-vous anglais ?", "Est-ce que vous êtes anglais ?", "Vous êtes anglaise ?", "Vous êtes anglaises ?", "Êtes-vous anglaise ?", "Êtes-vous anglaises ?", "Tu es anglais ?", "Tu es anglaise ?", "Es-tu anglais ?", "Es-tu anglaise ?", "Est-ce que tu es anglais ?", "Est-ce que tu es anglaise ?"], en: ["You are English?"], de: ["Sind Sie Engländer?", "Sind Sie Engländerin?", "Seid ihr Engländerinnen?"] } },
    { id: "u02.28", lesson: 4, fr: "Ils sont sympas, Hugo et Léa.", en: "Hugo and Léa are nice.", de: "Hugo und Léa sind nett.", alt: { fr: ["Hugo et Léa sont sympas.", "Hugo et Léa, ils sont sympas."], en: ["They are nice, Hugo and Léa.", "Hugo and Léa are friendly."], de: ["Sie sind nett, Hugo und Léa.", "Hugo und Léa sind sympathisch."] } },
    // Lesson 5
    { id: "u02.29", lesson: 5, fr: "Je ne suis pas fatigué.", en: "I am not tired.", de: "Ich bin nicht müde.", alt: { fr: ["Je ne suis pas fatiguée."] } },
    { id: "u02.30", lesson: 5, fr: "Ce n'est pas Hugo, c'est Max !", en: "That's not Hugo, it's Max!", de: "Das ist nicht Hugo, das ist Max!", alt: { en: ["It is not Hugo, it is Max!", "That is not Hugo, that is Max!", "This is not Hugo, it is Max!", "This is not Hugo, this is Max!", "It is not Hugo, that is Max!"], de: ["Das ist nicht Hugo, sondern Max!", "Das ist nicht Hugo, es ist Max!"] } },
    { id: "u02.31", lesson: 5, fr: "Elle n'est pas anglaise, elle est suisse.", en: "She is not English, she is Swiss.", de: "Sie ist keine Engländerin, sie ist Schweizerin.", alt: { de: ["Sie ist nicht Engländerin, sie ist Schweizerin.", "Sie ist keine Engländerin, sondern Schweizerin."] } },
    { id: "u02.32", lesson: 5, fr: "C'est Madame Martin, la voisine.", en: "That's Mrs Martin, the neighbour.", de: "Das ist Frau Martin, die Nachbarin.", alt: { en: ["This is Mrs Martin, the neighbour.", "It is Mrs Martin, the neighbour.", "That is Mrs Martin, our neighbour.", "This is Mrs Martin, our neighbour."], de: ["Das ist Frau Martin, unsere Nachbarin."] } },
    { id: "u02.33", lesson: 5, fr: "Le voisin n'est pas très sympa.", en: "The neighbour is not very nice.", de: "Der Nachbar ist nicht sehr nett.", alt: { en: ["The neighbour is not very friendly."], de: ["Der Nachbar ist nicht sehr sympathisch.", "Der Nachbar ist nicht sehr freundlich."] } },
    { id: "u02.34", lesson: 5, fr: "Je suis un peu fatiguée.", en: "I am a bit tired.", de: "Ich bin ein bisschen müde.", alt: { fr: ["Je suis un peu fatigué."], en: ["I am a little tired.", "I am a little bit tired.", "I am slightly tired."], de: ["Ich bin etwas müde.", "Ich bin ein wenig müde."] } },
    { id: "u02.35", lesson: 5, fr: "Nous ne sommes pas allemands.", en: "We are not German.", de: "Wir sind keine Deutschen.", alt: { fr: ["Nous ne sommes pas allemandes.", "On n'est pas allemands.", "On n'est pas allemandes."] } },
  ],
  drills: [
    { id: "u02.d1", lesson: 1, fr: "Qui est-ce ? ___ Hugo.", options: ["C'est", "Il est", "Elle est"], answer: 0, en: "Who's that? It's Hugo.", de: "Wer ist das? Das ist Hugo.", why: tx("Before a name, say **c'est**: c'est Hugo. Il est goes with describing words: il est sympa.", "Vor einem Namen sagst du **c'est**: c'est Hugo. Il est steht vor beschreibenden Wörtern: il est sympa.") },
    { id: "u02.d2", lesson: 1, fr: "Léa ? ___ est très sympa.", options: ["Elle", "Il"], answer: 0, en: "Léa? She is very nice.", de: "Léa? Sie ist sehr nett.", why: tx("Léa is a girl, so it's **elle** (she). Il means he.", "Léa ist ein Mädchen, also **elle** (sie). Il heißt er.") },
    { id: "u02.d3", lesson: 2, fr: "Léa est ___.", options: ["contente", "content"], answer: 0, en: "Léa is happy.", de: "Léa ist froh.", why: tx("For a girl or woman, add **-e**: content → **contente**. Now you hear the t.", "Bei Mädchen und Frauen kommt ein **-e** dazu: content → **contente**. Jetzt hört man das t.") },
    { id: "u02.d4", lesson: 2, fr: "Hugo, c'est ___ ami.", options: ["un", "une"], answer: 0, en: "Hugo is a friend.", de: "Hugo ist ein Freund.", why: tx("Hugo is a boy: **un ami**. A girl is une amie.", "Hugo ist ein Junge: **un ami**. Ein Mädchen ist une amie.") },
    { id: "u02.d5", lesson: 3, fr: "Léa est ___, elle est de Lyon.", options: ["française", "français"], answer: 0, en: "Léa is French, she is from Lyon.", de: "Léa ist Französin, sie ist aus Lyon.", why: tx("Léa is a girl: **française**, with an e.", "Léa ist ein Mädchen: **française**, mit e.") },
    { id: "u02.d6", lesson: 3, fr: "— Tu es d'où ? — Je suis ___ Paris.", options: ["de", "à", "en"], answer: 0, en: "— Where are you from? — I am from Paris.", de: "— Woher kommst du? — Ich bin aus Paris.", why: tx("Where you're from: **de** + the town. Je suis de Paris. (Je suis à Paris means I am in Paris.)", "Woher du kommst: **de** + Stadt. Je suis de Paris. (Je suis à Paris heißt: Ich bin in Paris.)") },
    { id: "u02.d7", lesson: 4, fr: "Nous ___ français.", options: ["sommes", "êtes", "sont"], answer: 0, en: "We are French.", de: "Wir sind Franzosen.", why: tx("With **nous** (we), être is **sommes**.", "Mit **nous** (wir) heißt être **sommes**.") },
    { id: "u02.d8", lesson: 4, fr: "Monsieur Martin, vous ___ d'où ?", options: ["êtes", "es", "sommes"], answer: 0, en: "Mr Martin, where are you from?", de: "Herr Martin, woher kommen Sie?", why: tx("With **vous** it's **êtes**: vous êtes. Polite for one adult, or for several people.", "Mit **vous** heißt es **êtes**: vous êtes. Höflich für einen Erwachsenen (Sie) oder für mehrere (ihr).") },
    { id: "u02.d9", lesson: 4, fr: "Hugo et Léa ___ sympas.", options: ["sont", "est", "êtes"], answer: 0, en: "Hugo and Léa are nice.", de: "Hugo und Léa sind nett.", why: tx("Hugo and Léa = they, so it's **sont**, like ils sont.", "Hugo und Léa = sie, also **sont**, wie ils sont.") },
    { id: "u02.d10", lesson: 4, fr: "Elles sont très ___.", options: ["fatiguées", "fatigués", "fatiguée"], answer: 0, en: "They are very tired.", de: "Sie sind sehr müde.", why: tx("**Elles** means only girls or women: **-e** for feminine, **-s** for plural: fatigu**ées**.", "**Elles** heißt nur Mädchen oder Frauen: **-e** für weiblich, **-s** für Plural: fatigu**ées**.") },
    { id: "u02.d11", lesson: 5, fr: "Je ___ suis pas fatigué.", options: ["ne", "pas", "non"], answer: 0, en: "I am not tired.", de: "Ich bin nicht müde.", why: tx("Not is two words around the verb: **ne** suis **pas**.", "Nicht sind zwei Wörter um das Verb herum: **ne** suis **pas**.") },
    { id: "u02.d12", lesson: 5, fr: "Ce ___ pas Hugo, c'est Max !", options: ["n'est", "ne est", "est"], answer: 0, en: "That's not Hugo, it's Max!", de: "Das ist nicht Hugo, das ist Max!", why: tx("Before a vowel, ne shrinks to **n'**: ce **n'est** pas.", "Vor einem Vokal wird ne zu **n'**: ce **n'est** pas.") },
  ],
  dialogue: {
    id: "u02.dialogue",
    lesson: 5,
    title: tx("Blob, a French blob?", "Blob, ein französischer Blob?"),
    lines: [
      { who: "blob", fr: "Salut, Léa ! Qui est-ce ?", en: "Hi, Léa! Who's that?", de: "Hallo, Léa! Wer ist das?" },
      { who: "lea", fr: "C'est Max, un ami. Il est allemand, il est de Berlin.", en: "That's Max, a friend. He's German, he's from Berlin.", de: "Das ist Max, ein Freund. Er ist Deutscher, er ist aus Berlin." },
      { who: "blob", fr: "Enchanté, Max ! Et la fille, elle est allemande aussi ?", en: "Nice to meet you, Max! And the girl, is she German too?", de: "Freut mich, Max! Und das Mädchen, ist das auch eine Deutsche?" },
      { who: "lea", fr: "Non, c'est Emma. Elle n'est pas allemande, elle est anglaise.", en: "No, that's Emma. She isn't German, she's English.", de: "Nein, das ist Emma. Sie ist keine Deutsche, sie ist Engländerin." },
      { who: "hugo", fr: "Et toi, Blob, tu es d'où ?", en: "And you, Blob, where are you from?", de: "Und du, Blob, woher kommst du?" },
      { who: "blob", fr: "Moi ? Je suis très français. Regarde mon béret !", en: "Me? I'm very French. Look at my beret!", de: "Ich? Ich bin sehr französisch. Schau, meine Baskenmütze!" },
      { who: "hugo", fr: "Un béret, ce n'est pas un passeport, Blob !", en: "A beret isn't a passport, Blob!", de: "Eine Baskenmütze ist kein Pass, Blob!" },
      { who: "lea", fr: "Blob n'est pas français, il est… violet !", en: "Blob isn't French, he's… purple!", de: "Blob ist kein Franzose, er ist … lila!" },
      { who: "blob", fr: "Violet, français… et très content !", en: "Purple, French… and very happy!", de: "Lila, französisch … und sehr froh!" },
    ],
    questions: [
      { q: tx("Where is Max from?", "Woher kommt Max?"), options: ["Berlin", "Lyon", "Paris"], answer: 0 },
      { q: tx("What nationality is Emma?", "Welche Nationalität hat Emma?"), options: [tx("English", "Engländerin"), tx("German", "Deutsche"), tx("Swiss", "Schweizerin")], answer: 0 },
      { q: tx("Why does Blob think he is French?", "Warum glaubt Blob, dass er Franzose ist?"), options: [tx("Because of his beret", "Wegen seiner Baskenmütze"), tx("Because he is from Paris", "Weil er aus Paris kommt"), tx("Because he is purple", "Weil er lila ist")], answer: 0 },
    ],
  },
  tips: [
    {
      title: tx("Être: I am, you are, we are…", "Être: ich bin, du bist, wir sind …"),
      body: tx(
        "**Être** (to be) has its own form for every person: learn the table by heart.\n\n**Vous** is for several people, or politely for one adult: Monsieur Martin, **vous êtes** d'où ? **Ils** is for boys or a mixed group, **elles** only for girls and women.\n\nBefore a name, say **c'est**: c'est Hugo. **Il est** and **elle est** go with describing words: il est sympa.",
        "**Être** (sein) hat für jede Person eine eigene Form: Lern die Tabelle auswendig.\n\n**Vous** ist für mehrere Leute (ihr) oder höflich für einen Erwachsenen (Sie): Monsieur Martin, **vous êtes** d'où ? **Ils** steht für Jungen oder gemischte Gruppen, **elles** nur für Mädchen und Frauen.\n\nVor einem Namen sagst du **c'est**: c'est Hugo. **Il est** und **elle est** stehen vor beschreibenden Wörtern: il est sympa.",
      ),
      examples: [
        { fr: "Nous sommes français.", en: "We are French.", de: "Wir sind Franzosen." },
        { fr: "Monsieur Martin, vous êtes d'où ?", en: "Mr Martin, where are you from?", de: "Herr Martin, woher kommen Sie?" },
        { fr: "C'est Hugo, il est sympa.", en: "This is Hugo, he's nice.", de: "Das ist Hugo, er ist nett." },
      ],
      table: {
        head: [tx("person", "Person"), "être"],
        rows: [
          [tx("I", "ich"), "je suis"],
          [tx("you", "du"), "tu es"],
          [tx("he / she", "er / sie"), "il / elle est"],
          [tx("we", "wir"), "nous sommes"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous êtes"],
          [tx("they", "sie"), "ils / elles sont"],
        ],
      },
    },
    {
      title: tx("Français, française", "Français, française"),
      body: tx(
        "Describing words change with the person. For a girl or woman, add **-e**: il est français, elle est français**e**. For several people, add **-s**: ils sont fatigué**s**, elles sont fatigué**es**.\n\nThe -e often lets you hear the last letter: française, allemande, contente. A word that already ends in -e doesn't get a second one: il est **suisse**, elle est **suisse**. **Sympa** stays the same for girls too, only several people are sympa**s**.\n\nNationalities are written with a small letter: anglais.",
        "Beschreibende Wörter passen sich der Person an. Bei Mädchen und Frauen kommt ein **-e** dazu: il est français, elle est français**e**. Bei mehreren ein **-s**: ils sont fatigué**s**, elles sont fatigué**es**.\n\nDurch das -e hört man oft den letzten Buchstaben: française, allemande, contente. Ein Wort, das schon auf -e endet, bekommt kein zweites: il est **suisse**, elle est **suisse**. Auch **sympa** bleibt bei Mädchen gleich, nur im Plural heißt es sympa**s**.\n\nNationalitäten schreibt man klein: anglais.",
      ),
      examples: [
        { fr: "Hugo est français.", en: "Hugo is French.", de: "Hugo ist Franzose." },
        { fr: "Léa est française.", en: "Léa is French.", de: "Léa ist Französin." },
        { fr: "Elles sont fatiguées.", en: "They are tired.", de: "Sie sind müde." },
      ],
      table: {
        head: [tx("meaning", "Bedeutung"), tx("masculine", "männlich"), tx("feminine", "weiblich")],
        rows: [
          [tx("French", "französisch"), "français", "française"],
          [tx("German", "deutsch"), "allemand", "allemande"],
          [tx("English", "englisch"), "anglais", "anglaise"],
          [tx("happy", "froh"), "content", "contente"],
          [tx("tired", "müde"), "fatigué", "fatiguée"],
          [tx("Swiss", "schweizerisch"), "suisse", "suisse"],
        ],
      },
    },
    {
      title: tx("Ne … pas: not", "Ne … pas: nicht"),
      body: tx(
        "To say not, put **ne** before the verb and **pas** after it: je **ne** suis **pas** fatigué. A little sandwich around the verb!\n\nBefore a vowel, ne shrinks to **n'**: elle **n'**est **pas** anglaise, ce **n'**est **pas** Hugo.",
        "Für „nicht“ kommt **ne** vor das Verb und **pas** dahinter: je **ne** suis **pas** fatigué. Ein kleines Sandwich um das Verb!\n\nVor einem Vokal wird ne zu **n'**: elle **n'**est **pas** anglaise, ce **n'**est **pas** Hugo.",
      ),
      examples: [
        { fr: "Je ne suis pas fatigué.", en: "I'm not tired.", de: "Ich bin nicht müde." },
        { fr: "Elle n'est pas anglaise, elle est suisse.", en: "She isn't English, she's Swiss.", de: "Sie ist keine Engländerin, sie ist Schweizerin." },
        { fr: "Ce n'est pas Hugo, c'est Max !", en: "That's not Hugo, it's Max!", de: "Das ist nicht Hugo, das ist Max!" },
      ],
    },
  ],
};
