import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 3: food and drinks, le/la/les, un/une/des, du/de la, manger, aimer, boire. */
export const u03: Unit = {
  slug: "manger",
  n: 3,
  cefr: "A1",
  title: tx("Bon appétit!", "Guten Appetit!"),
  goal: tx("Name food and drinks, say what you eat and what you like", "Essen und Getränke benennen, sagen, was du isst und was du magst"),
  emoji: "🥐",
  words: [
    { id: "croissant", fr: "le croissant", en: "the croissant", de: "das Croissant", g: "m", kind: "noun", emoji: "🥐", note: tx("Croissant means «growing», like the crescent moon.", "Croissant heißt „wachsend“, wie die Mondsichel.") },
    { id: "pomme", fr: "la pomme", en: "the apple", de: "der Apfel", g: "f", kind: "noun", emoji: "🍎", note: tx("A pomme de terre, an «apple of the earth», is a potato!", "Eine pomme de terre, ein „Erdapfel“, ist eine Kartoffel!") },
    { id: "banane", fr: "la banane", en: "the banana", de: "die Banane", g: "f", kind: "noun", emoji: "🍌" },
    { id: "pizza", fr: "la pizza", en: "the pizza", de: "die Pizza", g: "f", kind: "noun", emoji: "🍕" },
    { id: "je-mange", fr: "je mange", en: "I eat", de: "ich esse", alt: { en: ["I'm eating"] }, kind: "verb", note: tx("From manger, to eat. The e at the end is silent.", "Von manger, essen. Das e am Ende ist stumm.") },
    { id: "c-est-bon", fr: "c'est bon", en: "it's good", de: "das ist lecker", alt: { en: ["it's tasty"], de: ["das schmeckt gut"] }, kind: "phrase", emoji: "😋" },
    { id: "pain", fr: "le pain", en: "the bread", de: "das Brot", g: "m", kind: "noun", emoji: "🥖", note: tx("Many French people buy fresh bread every day, often a baguette.", "Viele Franzosen kaufen jeden Tag frisches Brot, oft ein Baguette.") },
    { id: "fromage", fr: "le fromage", en: "the cheese", de: "der Käse", g: "m", kind: "noun", emoji: "🧀", note: tx("France has more than a thousand cheeses. Blob wants to taste them all.", "Frankreich hat über tausend Käsesorten. Blob will alle probieren.") },
    { id: "eau", fr: "l'eau", en: "the water", de: "das Wasser", g: "f", kind: "noun", emoji: "💧", note: tx("Three letters, one sound: eau sounds like «oh».", "Drei Buchstaben, ein Laut: eau klingt wie „o“.") },
    { id: "lait", fr: "le lait", en: "the milk", de: "die Milch", g: "m", kind: "noun", emoji: "🥛", note: tx("The t is silent: «leh».", "Das t ist stumm: „lä“. Und anders als im Deutschen männlich: le lait.") },
    { id: "je-bois", fr: "je bois", en: "I drink", de: "ich trinke", alt: { en: ["I'm drinking"] }, kind: "verb", note: tx("From boire, to drink. Sounds like «bwa».", "Von boire, trinken. Klingt wie „bwa“.") },
    { id: "tu-bois", fr: "tu bois", en: "you drink", de: "du trinkst", kind: "verb", note: tx("Sounds just like je bois: the s is silent.", "Klingt genau wie je bois: Das s ist stumm.") },
    { id: "chocolat", fr: "le chocolat", en: "the chocolate", de: "die Schokolade", g: "m", kind: "noun", emoji: "🍫", note: tx("The t is silent: cho-co-LA.", "Das t ist stumm: scho-ko-LA.") },
    { id: "poisson", fr: "le poisson", en: "the fish", de: "der Fisch", g: "m", kind: "noun", emoji: "🐟", note: tx("Careful: poisson (fish) has a hissing ss. With one s, poison means poison!", "Achtung: poisson (Fisch) hat ein scharfes ss. Mit einem s heißt poison Gift!") },
    { id: "salade", fr: "la salade", en: "the salad", de: "der Salat", g: "f", kind: "noun", emoji: "🥗" },
    { id: "j-aime", fr: "j'aime", en: "I like", de: "ich mag", alt: { en: ["I love"], de: ["ich liebe"] }, kind: "verb", note: tx("Je + aime = j'aime. About people it means I love!", "Je + aime = j'aime. Bei Menschen heißt es: ich liebe!") },
    { id: "tu-aimes", fr: "tu aimes", en: "you like", de: "du magst", kind: "verb" },
    { id: "j-adore", fr: "j'adore", en: "I love", de: "ich liebe", alt: { en: ["I adore"] }, kind: "verb", note: tx("Stronger than j'aime. The French say it all the time: j'adore !", "Stärker als j'aime. Die Franzosen sagen es ständig: j'adore !") },
    { id: "tu-manges", fr: "tu manges", en: "you eat", de: "du isst", kind: "verb" },
    { id: "il-mange", fr: "il mange", en: "he eats", de: "er isst", kind: "verb", note: tx("Je mange, tu manges, il mange: all three sound the same.", "Je mange, tu manges, il mange: Alle drei klingen gleich.") },
    { id: "il-aime", fr: "il aime", en: "he likes", de: "er mag", kind: "verb" },
    { id: "il-boit", fr: "il boit", en: "he drinks", de: "er trinkt", kind: "verb", note: tx("Je bois, tu bois, but il boit, with a silent t.", "Je bois, tu bois, aber il boit, mit stummem t.") },
    { id: "frites", fr: "les frites", en: "the chips", de: "die Pommes", alt: { en: ["the fries"], de: ["die Pommes frites"] }, g: "f", kind: "noun", emoji: "🍟", note: tx("Chips in Britain, fries in America, frites in France.", "Pommes frites heißt eigentlich „frittierte Kartoffeln“.") },
    { id: "delicieux", fr: "délicieux", en: "delicious", de: "köstlich", alt: { de: ["lecker"] }, kind: "adj", note: tx("For a feminine word: délicieuse. La pizza est délicieuse.", "Bei weiblichen Wörtern: délicieuse. La pizza est délicieuse.") },
    { id: "bon-appetit", fr: "bon appétit !", en: "enjoy your meal!", de: "guten Appetit!", alt: { en: ["bon appétit!"] }, kind: "phrase", emoji: "🍽️", note: tx("Said before every meal in France, at home and at school.", "Sagt man in Frankreich vor jedem Essen, zu Hause und in der Schule.") },
    { id: "nous-mangeons", fr: "nous mangeons", en: "we eat", de: "wir essen", alt: { en: ["we're eating"] }, kind: "verb", note: tx("Mangeons keeps an e after the g, so the g stays soft: «mon-JON».", "Mangeons behält ein e nach dem g, damit das g weich bleibt: „man-SCHON“.") },
    { id: "vous-mangez", fr: "vous mangez", en: "you eat (plural / polite)", de: "ihr esst / Sie essen", kind: "verb" },
    { id: "ils-mangent", fr: "ils mangent", en: "they eat", de: "sie essen", kind: "verb", note: tx("The -ent is silent: ils mangent sounds just like il mange.", "Das -ent ist stumm: ils mangent klingt genau wie il mange.") },
    { id: "pates", fr: "les pâtes", en: "the pasta", de: "die Nudeln", alt: { de: ["die Pasta"] }, g: "f", kind: "noun", emoji: "🍝", note: tx("Always plural in French: les pâtes.", "Im Französischen immer Plural: les pâtes.") },
    { id: "soupe", fr: "la soupe", en: "the soup", de: "die Suppe", g: "f", kind: "noun", emoji: "🍲" },
    { id: "oeuf", fr: "l'œuf", en: "the egg", de: "das Ei", g: "m", kind: "noun", emoji: "🥚", note: tx("Un œuf: you hear the f. Des œufs: the f is silent, «day-zuh».", "Un œuf: Man hört das f. Des œufs: Das f ist stumm, „dä-sö“.") },
    { id: "riz", fr: "le riz", en: "the rice", de: "der Reis", g: "m", kind: "noun", emoji: "🍚", note: tx("The z is silent: «ree».", "Das z ist stumm: „ri“.") },
  ],
  gloss: [
    { fr: "bon", en: "good", de: "gut" },
    { fr: "manges", en: "eat (you)", de: "isst (du)" },
    { fr: "mange", en: "eats / eat", de: "isst / esse" },
    { fr: "aime", en: "likes / like", de: "mag" },
    { fr: "boit", en: "drinks", de: "trinkt" },
    { fr: "bois", en: "drink (I / you)", de: "trinke / trinkst" },
    { fr: "pommes", en: "apples", de: "Äpfel" },
    { fr: "bananes", en: "bananas", de: "Bananen" },
    { fr: "croissants", en: "croissants", de: "Croissants" },
    { fr: "délicieuse", en: "delicious (feminine)", de: "köstlich (weiblich)" },
    { fr: "qu'est-ce que", en: "what", de: "was" },
    { fr: "tout", en: "all", de: "ganz / alles" },
    { fr: "maman", en: "mum", de: "Mama" },
    { fr: "ce n'est pas grave", en: "never mind", de: "macht nichts" },
    { fr: "mangeons", en: "eat (we)", de: "essen (wir)" },
    { fr: "mangez", en: "eat (you, plural / polite)", de: "esst / essen (Sie)" },
    { fr: "mangent", en: "eat (they)", de: "essen (sie)" },
    { fr: "aimez", en: "like (you, plural / polite)", de: "mögt / mögen (Sie)" },
    { fr: "adorons", en: "love (we)", de: "lieben (wir)" },
    { fr: "œufs", en: "eggs", de: "Eier" },
  ],
  lessons: [
    { title: tx("An apple, a croissant", "Ein Apfel, ein Croissant"), words: ["croissant", "pomme", "banane", "pizza", "je-mange", "c-est-bon"] },
    { title: tx("Bread and water", "Brot und Wasser"), words: ["pain", "fromage", "eau", "lait", "je-bois", "tu-bois"] },
    { title: tx("I like chocolate", "Ich mag Schokolade"), words: ["chocolat", "poisson", "salade", "j-aime", "tu-aimes", "j-adore"] },
    { title: tx("What is Hugo eating?", "Was isst Hugo?"), words: ["tu-manges", "il-mange", "il-aime", "il-boit", "frites"] },
    { title: tx("At Léa's", "Bei Léa"), words: ["delicieux", "bon-appetit"] },
    { title: tx("We're eating pasta", "Wir essen Nudeln"), words: ["nous-mangeons", "vous-mangez", "ils-mangent", "pates"] },
    { title: tx("Soup, eggs and rice", "Suppe, Eier und Reis"), words: ["soupe", "oeuf", "riz"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u03.01", lesson: 1, fr: "Je mange une pomme.", en: "I'm eating an apple.", de: "Ich esse einen Apfel.", alt: { en: ["I eat an apple."] } },
    { id: "u03.02", lesson: 1, fr: "Je mange un croissant. Et toi ?", en: "I'm eating a croissant. What about you?", de: "Ich esse ein Croissant. Und du?", alt: { fr: ["Je mange un croissant. Et vous ?"], en: ["I am eating a croissant. And you?", "I eat a croissant. And you?", "I eat a croissant. What about you?", "I am eating a croissant. How about you?"] } },
    { id: "u03.03", lesson: 1, fr: "C'est bon !", en: "It's good!", de: "Das ist lecker!", alt: { en: ["That is good!", "It is tasty!", "That is tasty!", "Tasty!", "Yummy!"], de: ["Das schmeckt gut!", "Lecker!", "Das ist gut!", "Es ist lecker!", "Es schmeckt gut!"] } },
    { id: "u03.04", lesson: 1, fr: "C'est une banane ou une pomme ?", en: "Is it a banana or an apple?", de: "Ist das eine Banane oder ein Apfel?", alt: { fr: ["Est-ce une banane ou une pomme ?", "Est-ce que c'est une banane ou une pomme ?"], en: ["Is that a banana or an apple?", "Is this a banana or an apple?"], de: ["Ist es eine Banane oder ein Apfel?"] } },
    { id: "u03.05", lesson: 1, fr: "Je mange une pizza avec Léa.", en: "I'm eating a pizza with Léa.", de: "Ich esse eine Pizza mit Léa.", alt: { fr: ["Je mange de la pizza avec Léa."], en: ["I eat a pizza with Léa.", "I am eating pizza with Léa.", "I eat pizza with Léa."], de: ["Ich esse mit Léa eine Pizza.", "Ich esse mit Léa Pizza.", "Ich esse Pizza mit Léa."] } },
    { id: "u03.06", lesson: 1, fr: "C'est très bon, merci !", en: "It's very good, thank you!", de: "Das ist sehr lecker, danke!", alt: { en: ["It is very good, thanks!", "That is very good, thank you!", "That is very good, thanks!", "It is really good, thank you!", "It is really good, thanks!", "It is very tasty, thank you!"], de: ["Das ist sehr gut, danke!", "Das schmeckt sehr gut, danke!", "Es ist sehr lecker, danke!", "Das ist sehr lecker, vielen Dank!"] } },
    { id: "u03.07", lesson: 1, fr: "Une pomme ? Non, une pizza !", en: "An apple? No, a pizza!", de: "Einen Apfel? Nein, eine Pizza!", alt: { de: ["Ein Apfel? Nein, eine Pizza!"] } },
    // Lesson 2
    { id: "u03.08", lesson: 2, fr: "Je mange du pain.", en: "I eat bread.", de: "Ich esse Brot.", alt: { en: ["I am eating bread.", "I am eating some bread.", "I eat some bread."], de: ["Ich esse etwas Brot."] } },
    { id: "u03.09", lesson: 2, fr: "Je bois de l'eau.", en: "I drink water.", de: "Ich trinke Wasser.", alt: { en: ["I am drinking water.", "I drink some water.", "I am drinking some water."], de: ["Ich trinke etwas Wasser."] } },
    { id: "u03.10", lesson: 2, fr: "Tu bois du lait ?", en: "Do you drink milk?", de: "Trinkst du Milch?", alt: { fr: ["Bois-tu du lait ?", "Est-ce que tu bois du lait ?", "Vous buvez du lait ?", "Buvez-vous du lait ?"], en: ["Are you drinking milk?", "You drink milk?", "Do you drink any milk?", "Are you drinking any milk?"], de: ["Du trinkst Milch?"] } },
    { id: "u03.11", lesson: 2, fr: "Du pain et du fromage, merci !", en: "Bread and cheese, thank you!", de: "Brot und Käse, danke!", alt: { en: ["Bread and cheese, thanks!", "Some bread and some cheese, thank you!", "Some bread and cheese, thank you!", "Some bread and cheese, thanks!", "Some bread and some cheese, thanks!"] } },
    { id: "u03.12", lesson: 2, fr: "Tu bois de l'eau ou du lait ?", en: "Are you drinking water or milk?", de: "Trinkst du Wasser oder Milch?", alt: { fr: ["Bois-tu de l'eau ou du lait ?", "Est-ce que tu bois de l'eau ou du lait ?", "Vous buvez de l'eau ou du lait ?", "Buvez-vous de l'eau ou du lait ?"], en: ["Do you drink water or milk?", "You are drinking water or milk?"], de: ["Du trinkst Wasser oder Milch?"] } },
    { id: "u03.13", lesson: 2, fr: "Je mange du fromage avec du pain.", en: "I eat cheese with bread.", de: "Ich esse Käse mit Brot.", alt: { en: ["I am eating cheese with bread.", "I eat some cheese with some bread.", "I eat cheese with some bread.", "I am eating some cheese with some bread.", "I am eating cheese with some bread."] } },
    { id: "u03.14", lesson: 2, fr: "Un croissant et du lait, merci.", en: "A croissant and milk, thank you.", de: "Ein Croissant und Milch, danke.", alt: { en: ["A croissant and some milk, thank you.", "A croissant and milk, thanks.", "A croissant and some milk, thanks."] } },
    // Lesson 3
    { id: "u03.15", lesson: 3, fr: "J'aime le fromage.", en: "I like cheese.", de: "Ich mag Käse.", alt: { en: ["I love cheese.", "I like the cheese.", "I love the cheese."], de: ["Ich esse gern Käse.", "Ich esse gerne Käse.", "Ich liebe Käse.", "Ich mag den Käse."] } },
    { id: "u03.16", lesson: 3, fr: "Tu aimes le poisson ?", en: "Do you like fish?", de: "Magst du Fisch?", alt: { fr: ["Aimes-tu le poisson ?", "Est-ce que tu aimes le poisson ?", "Vous aimez le poisson ?", "Aimez-vous le poisson ?"], en: ["You like fish?", "Do you like the fish?"], de: ["Isst du gern Fisch?", "Isst du gerne Fisch?", "Du magst Fisch?", "Magst du den Fisch?"] } },
    { id: "u03.17", lesson: 3, fr: "J'adore la pizza !", en: "I love pizza!", de: "Ich liebe Pizza!", alt: { fr: ["J'aime la pizza !"], en: ["I adore pizza!", "I love the pizza!"], de: ["Ich liebe die Pizza!"] } },
    { id: "u03.18", lesson: 3, fr: "Non, je n'aime pas la salade.", en: "No, I don't like salad.", de: "Nein, ich mag keinen Salat.", alt: { en: ["No, I don't like the salad."], de: ["Nein, ich mag Salat nicht.", "Nein, ich esse nicht gern Salat.", "Nein, ich mag den Salat nicht."] } },
    { id: "u03.19", lesson: 3, fr: "J'aime les pommes et les bananes.", en: "I like apples and bananas.", de: "Ich mag Äpfel und Bananen.", alt: { en: ["I love apples and bananas.", "I like the apples and the bananas."], de: ["Ich esse gern Äpfel und Bananen.", "Ich esse gerne Äpfel und Bananen."] } },
    { id: "u03.20", lesson: 3, fr: "Tu aimes le chocolat, Blob ?", en: "Do you like chocolate, Blob?", de: "Magst du Schokolade, Blob?", alt: { fr: ["Blob, tu aimes le chocolat ?", "Aimes-tu le chocolat, Blob ?", "Est-ce que tu aimes le chocolat, Blob ?"], en: ["Blob, do you like chocolate?", "You like chocolate, Blob?", "Do you like the chocolate, Blob?"], de: ["Blob, magst du Schokolade?", "Isst du gern Schokolade, Blob?", "Isst du gerne Schokolade, Blob?", "Magst du die Schokolade, Blob?"] } },
    { id: "u03.21", lesson: 3, fr: "Oui, j'adore le chocolat !", en: "Yes, I love chocolate!", de: "Ja, ich liebe Schokolade!", alt: { fr: ["Oui, j'aime le chocolat !"], en: ["Yes, I adore chocolate!", "Yes, I love the chocolate!"], de: ["Ja, ich liebe die Schokolade!"] } },
    // Lesson 4
    { id: "u03.22", lesson: 4, fr: "Qu'est-ce que tu manges ?", en: "What are you eating?", de: "Was isst du?", alt: { fr: ["Tu manges quoi ?", "Que manges-tu ?", "Qu'est-ce que vous mangez ?", "Vous mangez quoi ?", "Que mangez-vous ?"], en: ["What do you eat?"] } },
    { id: "u03.23", lesson: 4, fr: "Hugo ? Il mange des frites.", en: "Hugo? He's eating chips.", de: "Hugo? Er isst Pommes.", alt: { en: ["Hugo? He is eating fries.", "Hugo? He eats chips.", "Hugo? He eats fries.", "Hugo? He is eating French fries.", "Hugo? He eats French fries."], de: ["Hugo? Er isst Pommes frites.", "Hugo? Er isst Fritten."] } },
    { id: "u03.24", lesson: 4, fr: "Elle aime la salade, il aime les frites.", en: "She likes salad, he likes chips.", de: "Sie mag Salat, er mag Pommes.", alt: { fr: ["Elle aime la salade et il aime les frites."], en: ["She likes salad and he likes chips.", "She likes salad, he likes fries.", "She likes salad and he likes fries.", "She loves salad, he loves chips."], de: ["Sie mag Salat und er mag Pommes.", "Sie mag Salat, er mag Pommes frites.", "Sie isst gern Salat, er isst gern Pommes."] } },
    { id: "u03.25", lesson: 4, fr: "Léa boit de l'eau.", en: "Léa is drinking water.", de: "Léa trinkt Wasser.", alt: { en: ["Léa drinks water.", "Léa is drinking some water.", "Léa drinks some water."] } },
    { id: "u03.26", lesson: 4, fr: "Tu manges du poisson ?", en: "Do you eat fish?", de: "Isst du Fisch?", alt: { fr: ["Manges-tu du poisson ?", "Est-ce que tu manges du poisson ?", "Vous mangez du poisson ?", "Mangez-vous du poisson ?"], en: ["Are you eating fish?", "You eat fish?", "Do you eat any fish?"], de: ["Du isst Fisch?"] } },
    { id: "u03.27", lesson: 4, fr: "Il boit du lait au chocolat.", en: "He's drinking chocolate milk.", de: "Er trinkt Kakao.", alt: { en: ["He drinks chocolate milk."], de: ["Er trinkt Schokomilch.", "Er trinkt Schokoladenmilch."] } },
    { id: "u03.28", lesson: 4, fr: "Madame Martin mange de la salade.", en: "Mrs Martin is eating salad.", de: "Frau Martin isst Salat.", alt: { fr: ["Madame Martin mange une salade."], en: ["Mrs Martin eats salad.", "Mrs Martin is eating some salad.", "Mrs Martin eats some salad.", "Mrs Martin is eating a salad.", "Mrs Martin eats a salad."], de: ["Frau Martin isst einen Salat.", "Frau Martin isst etwas Salat."] } },
    // Lesson 5
    { id: "u03.29", lesson: 5, fr: "Bon appétit !", en: "Enjoy your meal!", de: "Guten Appetit!", alt: { en: ["Bon appétit!", "Enjoy!"], de: ["Lass es dir schmecken!", "Mahlzeit!"] } },
    { id: "u03.30", lesson: 5, fr: "Le chocolat est délicieux !", en: "The chocolate is delicious!", de: "Die Schokolade ist köstlich!", alt: { fr: ["Le chocolat, c'est délicieux !"], en: ["Chocolate is delicious!"], de: ["Die Schokolade ist lecker!", "Schokolade ist köstlich!", "Schokolade ist lecker!"] } },
    { id: "u03.31", lesson: 5, fr: "La pizza est délicieuse.", en: "The pizza is delicious.", de: "Die Pizza ist köstlich.", alt: { de: ["Die Pizza ist lecker."] } },
    { id: "u03.32", lesson: 5, fr: "Je ne mange pas de poisson.", en: "I don't eat fish.", de: "Ich esse keinen Fisch.", alt: { en: ["I am not eating fish.", "I don't eat any fish.", "I am not eating any fish."] } },
    { id: "u03.33", lesson: 5, fr: "Tu ne bois pas de lait ?", en: "Don't you drink milk?", de: "Trinkst du keine Milch?", alt: { fr: ["Vous ne buvez pas de lait ?"], en: ["You don't drink milk?", "Aren't you drinking milk?", "You are not drinking milk?", "Don't you drink any milk?", "Aren't you drinking any milk?"], de: ["Du trinkst keine Milch?"] } },
    { id: "u03.34", lesson: 5, fr: "Merci, c'est délicieux !", en: "Thank you, it's delicious!", de: "Danke, das ist köstlich!", alt: { en: ["Thanks, it is delicious!", "Thank you, that is delicious!", "Thanks, that is delicious!", "Thank you, this is delicious!", "Thanks, this is delicious!"], de: ["Danke, das ist lecker!", "Danke, es ist köstlich!", "Danke, es ist lecker!", "Danke, das schmeckt köstlich!"] } },
    { id: "u03.35", lesson: 5, fr: "Les croissants sont délicieux.", en: "The croissants are delicious.", de: "Die Croissants sind köstlich.", alt: { en: ["Croissants are delicious."], de: ["Die Croissants sind lecker.", "Croissants sind köstlich.", "Croissants sind lecker."] } },
    // Lesson 6
    { id: "u03.36", lesson: 6, fr: "Nous mangeons des pâtes.", en: "We're eating pasta.", de: "Wir essen Nudeln.", alt: { fr: ["On mange des pâtes."], en: ["We eat pasta.", "We are eating some pasta.", "We eat some pasta."], de: ["Wir essen Pasta."] } },
    { id: "u03.37", lesson: 6, fr: "Vous mangez du fromage ?", en: "Do you eat cheese?", de: "Esst ihr Käse?", alt: { fr: ["Mangez-vous du fromage ?", "Est-ce que vous mangez du fromage ?", "Tu manges du fromage ?", "Manges-tu du fromage ?", "Est-ce que tu manges du fromage ?"], en: ["Are you eating cheese?", "You eat cheese?", "Do you eat any cheese?", "Are you eating any cheese?"], de: ["Essen Sie Käse?", "Ihr esst Käse?"] } },
    { id: "u03.38", lesson: 6, fr: "Ils mangent une pizza.", en: "They're eating a pizza.", de: "Sie essen eine Pizza.", alt: { fr: ["Elles mangent une pizza.", "Ils mangent de la pizza.", "Elles mangent de la pizza."], en: ["They eat a pizza.", "They are eating pizza.", "They eat pizza."], de: ["Sie essen Pizza."] } },
    { id: "u03.39", lesson: 6, fr: "Hugo et Léa mangent des frites.", en: "Hugo and Léa are eating chips.", de: "Hugo und Léa essen Pommes.", alt: { en: ["Hugo and Léa eat chips.", "Hugo and Léa are eating fries.", "Hugo and Léa eat fries."], de: ["Hugo und Léa essen Pommes frites."] } },
    { id: "u03.40", lesson: 6, fr: "Nous ne mangeons pas de poisson.", en: "We don't eat fish.", de: "Wir essen keinen Fisch.", alt: { fr: ["On ne mange pas de poisson."], en: ["We are not eating fish.", "We don't eat any fish.", "We are not eating any fish."] } },
    { id: "u03.41", lesson: 6, fr: "Vous aimez les pâtes ?", en: "Do you like pasta?", de: "Mögt ihr Nudeln?", alt: { fr: ["Aimez-vous les pâtes ?", "Est-ce que vous aimez les pâtes ?", "Tu aimes les pâtes ?", "Aimes-tu les pâtes ?", "Est-ce que tu aimes les pâtes ?"], en: ["You like pasta?", "Do you like the pasta?"], de: ["Mögen Sie Nudeln?", "Esst ihr gern Nudeln?", "Esst ihr gerne Nudeln?", "Mögt ihr Pasta?", "Ihr mögt Nudeln?"] } },
    { id: "u03.42", lesson: 6, fr: "Oui, nous adorons les pâtes !", en: "Yes, we love pasta!", de: "Ja, wir lieben Nudeln!", alt: { fr: ["Oui, on adore les pâtes !", "Oui, nous aimons les pâtes !", "Oui, on aime les pâtes !"], en: ["Yes, we adore pasta!"], de: ["Ja, wir lieben Pasta!"] } },
    { id: "u03.43", lesson: 6, fr: "Monsieur et Madame Martin mangent du pain.", en: "Mr and Mrs Martin are eating bread.", de: "Herr und Frau Martin essen Brot.", alt: { en: ["Mr and Mrs Martin eat bread.", "Mr and Mrs Martin are eating some bread.", "Mr and Mrs Martin eat some bread."], de: ["Herr und Frau Martin essen etwas Brot."] } },
    // Lesson 7
    { id: "u03.44", lesson: 7, fr: "Je mange un œuf.", en: "I'm eating an egg.", de: "Ich esse ein Ei.", alt: { en: ["I eat an egg."] } },
    { id: "u03.45", lesson: 7, fr: "Il y a de la soupe ?", en: "Is there any soup?", de: "Gibt es Suppe?", alt: { fr: ["Est-ce qu'il y a de la soupe ?", "Y a-t-il de la soupe ?"], en: ["Is there soup?", "Is there some soup?"] } },
    { id: "u03.46", lesson: 7, fr: "Tu manges des œufs avec du pain ?", en: "Do you eat eggs with bread?", de: "Isst du Eier mit Brot?", alt: { fr: ["Manges-tu des œufs avec du pain ?", "Est-ce que tu manges des œufs avec du pain ?", "Vous mangez des œufs avec du pain ?", "Mangez-vous des œufs avec du pain ?"], en: ["Are you eating eggs with bread?", "You eat eggs with bread?", "Do you eat eggs with some bread?"], de: ["Du isst Eier mit Brot?"] } },
    { id: "u03.47", lesson: 7, fr: "Léa n'aime pas la soupe.", en: "Léa doesn't like soup.", de: "Léa mag keine Suppe.", alt: { en: ["Léa doesn't like the soup."], de: ["Léa mag Suppe nicht.", "Léa isst nicht gern Suppe.", "Léa isst nicht gerne Suppe.", "Léa mag die Suppe nicht."] } },
    { id: "u03.48", lesson: 7, fr: "Nous mangeons du riz et du poisson.", en: "We're eating rice and fish.", de: "Wir essen Reis und Fisch.", alt: { fr: ["On mange du riz et du poisson."], en: ["We eat rice and fish.", "We are eating some rice and some fish.", "We are eating some rice and fish.", "We eat some rice and some fish."] } },
    { id: "u03.49", lesson: 7, fr: "La soupe est délicieuse !", en: "The soup is delicious!", de: "Die Suppe ist köstlich!", alt: { de: ["Die Suppe ist lecker!"] } },
    { id: "u03.50", lesson: 7, fr: "Il ne mange pas d'œufs.", en: "He doesn't eat eggs.", de: "Er isst keine Eier.", alt: { fr: ["Il ne mange pas d'œuf."], en: ["He doesn't eat any eggs.", "He is not eating eggs.", "He is not eating any eggs."] } },
    { id: "u03.51", lesson: 7, fr: "Vous mangez de la soupe ou du riz ?", en: "Are you having soup or rice?", de: "Esst ihr Suppe oder Reis?", alt: { fr: ["Mangez-vous de la soupe ou du riz ?", "Est-ce que vous mangez de la soupe ou du riz ?", "Tu manges de la soupe ou du riz ?", "Manges-tu de la soupe ou du riz ?", "Est-ce que tu manges de la soupe ou du riz ?"], en: ["Are you eating soup or rice?", "Do you eat soup or rice?", "You are eating soup or rice?"], de: ["Essen Sie Suppe oder Reis?", "Ihr esst Suppe oder Reis?"] } },
  ],
  drills: [
    { id: "u03.d1", lesson: 1, fr: "Je mange ___ pomme.", options: ["une", "un"], answer: 0, en: "I'm eating an apple.", de: "Ich esse einen Apfel.", why: tx("Pomme is feminine: **une** pomme.", "Pomme ist weiblich: **une** pomme.") },
    { id: "u03.d2", lesson: 1, fr: "C'est ___ croissant.", options: ["un", "une"], answer: 0, en: "It's a croissant.", de: "Das ist ein Croissant.", why: tx("Croissant is masculine: **un** croissant.", "Croissant ist männlich: **un** croissant.") },
    { id: "u03.d3", lesson: 2, fr: "Je bois ___ lait.", options: ["du", "de la", "de l'"], answer: 0, en: "I drink milk.", de: "Ich trinke Milch.", why: tx("Some milk: lait is masculine, so **du** lait (du = de + le).", "Etwas Milch: lait ist männlich, also **du** lait (du = de + le).") },
    { id: "u03.d4", lesson: 2, fr: "Tu bois ___ l'eau ?", options: ["de", "du", "des"], answer: 0, en: "Are you drinking water?", de: "Trinkst du Wasser?", why: tx("Before l' it's just **de**: de l'eau. Never «du l'eau».", "Vor l' steht nur **de**: de l'eau. Nie „du l'eau“.") },
    { id: "u03.d5", lesson: 3, fr: "J'aime ___ chocolat.", options: ["le", "du", "la"], answer: 0, en: "I like chocolate.", de: "Ich mag Schokolade.", why: tx("You like chocolate in general: **le** chocolat (it's masculine, so not la). Du is for eating some: je mange du chocolat.", "Schokolade ganz allgemein: **le** chocolat (männlich, also nicht la). „du“ steht, wenn du etwas davon isst: je mange du chocolat.") },
    { id: "u03.d6", lesson: 3, fr: "Tu ___ la pizza ?", options: ["aimes", "aime", "aimer"], answer: 0, en: "Do you like pizza?", de: "Magst du Pizza?", why: tx("With tu: **aimes**, with an s you don't hear.", "Mit tu: **aimes**, mit einem s, das man nicht hört.") },
    { id: "u03.d7", lesson: 3, fr: "___aime le fromage.", options: ["J'", "Je "], answer: 0, en: "I like cheese.", de: "Ich mag Käse.", why: tx("Je + aime → **j'aime**: je drops its e before a vowel.", "Je + aime → **j'aime**: Vor einem Vokal fällt das e von je weg.") },
    { id: "u03.d8", lesson: 4, fr: "Hugo ___ des frites.", options: ["mange", "manges", "manger"], answer: 0, en: "Hugo is eating chips.", de: "Hugo isst Pommes.", why: tx("With il, elle or a name: **mange**, no s.", "Mit il, elle oder einem Namen: **mange**, ohne s.") },
    { id: "u03.d9", lesson: 4, fr: "Léa ___ de l'eau.", options: ["boit", "bois", "boire"], answer: 0, en: "Léa is drinking water.", de: "Léa trinkt Wasser.", why: tx("Il and elle: **boit**, with a silent t. Je bois, tu bois.", "Il und elle: **boit**, mit stummem t. Je bois, tu bois.") },
    { id: "u03.d10", lesson: 4, fr: "Qu'est-ce que tu ___ ?", options: ["manges", "mange", "manger"], answer: 0, en: "What are you eating?", de: "Was isst du?", why: tx("With tu: **manges**, with an s you don't hear.", "Mit tu: **manges**, mit einem s, das man nicht hört.") },
    { id: "u03.d11", lesson: 5, fr: "Je ne mange pas ___ poisson.", options: ["de", "du", "de la"], answer: 0, en: "I don't eat fish.", de: "Ich esse keinen Fisch.", why: tx("After ne … pas, du becomes just **de**: pas de poisson.", "Nach ne … pas wird du zu **de**: pas de poisson.") },
    { id: "u03.d12", lesson: 5, fr: "La pizza est ___.", options: ["délicieuse", "délicieux"], answer: 0, en: "The pizza is delicious.", de: "Die Pizza ist köstlich.", why: tx("Pizza is feminine: **délicieuse**.", "Pizza ist weiblich: **délicieuse**.") },
    { id: "u03.d13", lesson: 6, fr: "Nous ___ des pâtes.", options: ["mangeons", "mangons", "mangez"], answer: 0, en: "We're eating pasta.", de: "Wir essen Nudeln.", why: tx("With **nous**: mang**eons**. The e keeps the g soft, as in manger.", "Mit **nous**: mang**eons**. Das e hält das g weich, wie in manger.") },
    { id: "u03.d14", lesson: 6, fr: "Vous ___ du fromage ?", options: ["mangez", "mangeons", "mange"], answer: 0, en: "Do you eat cheese?", de: "Esst ihr Käse?", why: tx("With **vous**, the ending is **-ez**: vous mang**ez**.", "Mit **vous** endet es auf **-ez**: vous mang**ez**.") },
    { id: "u03.d15", lesson: 6, fr: "Hugo et Léa ___ des frites.", options: ["mangent", "mange", "mangez"], answer: 0, en: "Hugo and Léa are eating chips.", de: "Hugo und Léa essen Pommes.", why: tx("Two people = ils: **mangent**. The -ent is silent!", "Zwei Leute = ils: **mangent**. Das -ent ist stumm!") },
    { id: "u03.d16", lesson: 7, fr: "Je mange ___ œuf.", options: ["un", "une"], answer: 0, en: "I'm eating an egg.", de: "Ich esse ein Ei.", why: tx("Œuf is masculine: **un** œuf.", "Œuf ist männlich: **un** œuf.") },
    { id: "u03.d17", lesson: 7, fr: "Il y a ___ soupe ?", options: ["de la", "du", "des"], answer: 0, en: "Is there any soup?", de: "Gibt es Suppe?", why: tx("Soupe is feminine: **de la** soupe.", "Soupe ist weiblich: **de la** soupe.") },
    { id: "u03.d18", lesson: 7, fr: "Il ne mange pas ___œufs.", options: ["d'", "de "], answer: 0, en: "He doesn't eat eggs.", de: "Er isst keine Eier.", why: tx("After ne … pas it's **de**, and before a vowel **d'**: pas **d'**œufs.", "Nach ne … pas steht **de**, vor einem Vokal **d'**: pas **d'**œufs.") },
  ],
  dialogues: [
    {
      id: "u03.dialogue",
      lesson: 5,
      title: tx("Dinner at Léa's", "Abendessen bei Léa"),
      lines: [
        { who: "maman", fr: "Il y a du pain, du fromage et du poisson. Bon appétit !", en: "There's bread, cheese and fish. Enjoy your meal!", de: "Es gibt Brot, Käse und Fisch. Guten Appetit!" },
        { who: "blob", fr: "Merci ! J'adore le fromage français.", en: "Thank you! I love French cheese.", de: "Danke! Ich liebe französischen Käse." },
        { who: "lea", fr: "Tu ne manges pas de poisson, Blob ?", en: "Aren't you having any fish, Blob?", de: "Isst du keinen Fisch, Blob?" },
        { who: "blob", fr: "Non, merci, pas de poisson ! Je mange du fromage… et du fromage !", en: "No, thanks, no fish! I'm eating cheese… and cheese!", de: "Nein, danke, keinen Fisch! Ich esse Käse … und Käse!" },
        { who: "maman", fr: "Et tu bois de l'eau ou du lait ?", en: "And are you drinking water or milk?", de: "Und trinkst du Wasser oder Milch?" },
        { who: "blob", fr: "Du lait, merci. C'est bon avec le fromage !", en: "Milk, thanks. It's good with cheese!", de: "Milch, danke. Das passt gut zum Käse!" },
        { who: "lea", fr: "Maman, Blob mange tout le fromage !", en: "Mum, Blob is eating all the cheese!", de: "Mama, Blob isst den ganzen Käse!" },
        { who: "maman", fr: "Ce n'est pas grave. Il y a aussi des croissants !", en: "Never mind. There are croissants too!", de: "Macht nichts. Es gibt auch Croissants!" },
        { who: "blob", fr: "Des croissants ? C'est délicieux !", en: "Croissants? They're delicious!", de: "Croissants? Die sind köstlich!" },
      ],
      questions: [
        { q: tx("What does Blob love?", "Was liebt Blob?"), options: [tx("French cheese", "Französischen Käse"), tx("Fish", "Fisch"), tx("Salad", "Salat")], answer: 0 },
        { q: tx("What does Blob drink?", "Was trinkt Blob?"), options: [tx("Milk", "Milch"), tx("Water", "Wasser"), tx("Chocolate milk", "Kakao")], answer: 0 },
        { q: tx("What's the problem?", "Was ist das Problem?"), options: [tx("Blob is eating all the cheese.", "Blob isst den ganzen Käse."), tx("There's no bread.", "Es gibt kein Brot."), tx("Léa doesn't like fish.", "Léa mag keinen Fisch.")], answer: 0 },
      ],
    },
    {
      id: "u03.dialogue2",
      lesson: 7,
      title: tx("Blob cooks", "Blob kocht"),
      lines: [
        { who: "blob", fr: "Salut ! Il y a de la soupe chez moi !", en: "Hi! There's soup at my place!", de: "Hallo! Bei mir gibt es Suppe!" },
        { who: "hugo", fr: "De la soupe ? C'est une soupe de poisson ?", en: "Soup? Is it fish soup?", de: "Suppe? Ist das eine Fischsuppe?" },
        { who: "blob", fr: "Non, c'est une soupe au chocolat !", en: "No, it's chocolate soup!", de: "Nein, das ist eine Schokoladensuppe!" },
        { who: "lea", fr: "Une soupe au chocolat ? Et avec la soupe, tu manges quoi ?", en: "Chocolate soup? And what do you eat with the soup?", de: "Schokoladensuppe? Und was isst du zur Suppe?" },
        { who: "blob", fr: "Avec la soupe ? Des frites et un œuf ! J'adore !", en: "With the soup? Chips and an egg! I love it!", de: "Zur Suppe? Pommes und ein Ei! Ich liebe das!" },
        { who: "hugo", fr: "Blob, nous ne mangeons pas de soupe au chocolat.", en: "Blob, we don't eat chocolate soup.", de: "Blob, wir essen keine Schokoladensuppe." },
        { who: "lea", fr: "Il y a des pâtes ?", en: "Is there any pasta?", de: "Gibt es Nudeln?" },
        { who: "blob", fr: "Oui ! Des pâtes au fromage… et au chocolat !", en: "Yes! Pasta with cheese… and chocolate!", de: "Ja! Nudeln mit Käse … und Schokolade!" },
        { who: "hugo", fr: "Au fromage, merci, Blob !", en: "With cheese, thanks, Blob!", de: "Mit Käse, danke, Blob!" },
        { who: "blob", fr: "Et pour moi, le chocolat. Bon appétit !", en: "And the chocolate for me. Enjoy your meal!", de: "Und für mich die Schokolade. Guten Appetit!" },
      ],
      questions: [
        { q: tx("What soup does Blob make?", "Was für eine Suppe kocht Blob?"), options: [tx("Chocolate soup", "Schokoladensuppe"), tx("Fish soup", "Fischsuppe"), tx("Cheese soup", "Käsesuppe")], answer: 0 },
        { q: tx("What does Blob eat with his soup?", "Was isst Blob zu seiner Suppe?"), options: [tx("Chips and an egg", "Pommes und ein Ei"), tx("Bread and cheese", "Brot und Käse"), tx("Rice", "Reis")], answer: 0 },
        { q: tx("What does Hugo want?", "Was möchte Hugo?"), options: [tx("Pasta with cheese", "Nudeln mit Käse"), tx("Chocolate soup", "Schokoladensuppe"), tx("Fish", "Fisch")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Le, la, les – un, une, des", "Le, la, les – un, une, des"),
      body: tx(
        "Every French noun is masculine or feminine, so learn it with its little word: **le** pain, **la** pomme. Before a vowel both become **l'**: l'eau. In the plural it's always **les**.\n\n**Un** and **une** mean a: un croissant, une pomme. In the plural it's **des**: des frites (some chips).",
        "Jedes französische Nomen ist männlich oder weiblich, also lern es mit seinem kleinen Wort: **le** pain, **la** pomme. Vor einem Vokal werden beide zu **l'**: l'eau. Im Plural heißt es immer **les**.\n\n**Un** und **une** heißen ein und eine: un croissant, une pomme. Im Plural: **des** frites (Pommes).\n\nAchtung, das Geschlecht ist oft anders als im Deutschen: **le** lait, aber **die** Milch.",
      ),
      examples: [
        { fr: "Le fromage est délicieux.", en: "The cheese is delicious.", de: "Der Käse ist köstlich." },
        { fr: "Je mange une pomme.", en: "I'm eating an apple.", de: "Ich esse einen Apfel." },
        { fr: "Il mange des frites.", en: "He's eating chips.", de: "Er isst Pommes." },
      ],
      table: {
        head: [tx("article", "Artikel"), tx("masculine", "männlich"), tx("feminine", "weiblich"), tx("plural", "Plural")],
        rows: [
          [tx("the", "der, die, das"), "le pain", "la pomme", "les frites"],
          [tx("the (before a vowel)", "vor einem Vokal"), "l'ami", "l'eau", "les amis"],
          [tx("a, some", "ein, eine"), "un croissant", "une pomme", "des frites"],
        ],
      },
    },
    {
      title: tx("Du, de la: some", "Du, de la: etwas davon"),
      body: tx(
        "When you eat or drink some of something, French says **du** (masculine), **de la** (feminine) or **de l'** (before a vowel): je mange **du** pain, je bois **de l'**eau. English often says nothing at all: I eat bread.\n\nWhen you like or don't like something in general, it's le, la, les: j'aime **le** fromage.\n\nAfter ne … pas, it's just **de**: je ne mange pas **de** poisson.",
        "Wenn du etwas von etwas isst oder trinkst, sagt das Französische **du** (männlich), **de la** (weiblich) oder **de l'** (vor einem Vokal): je mange **du** pain, je bois **de l'**eau. Im Deutschen steht da oft gar nichts: Ich esse Brot.\n\nWenn du etwas allgemein magst oder nicht magst, nimmst du le, la, les: j'aime **le** fromage.\n\nNach ne … pas steht nur **de**: je ne mange pas **de** poisson.",
      ),
      examples: [
        { fr: "Je mange du pain.", en: "I eat bread.", de: "Ich esse Brot." },
        { fr: "Je bois de l'eau.", en: "I drink water.", de: "Ich trinke Wasser." },
        { fr: "J'aime le fromage.", en: "I like cheese.", de: "Ich mag Käse." },
        { fr: "Je ne mange pas de poisson.", en: "I don't eat fish.", de: "Ich esse keinen Fisch." },
      ],
    },
    {
      title: tx("Manger, aimer, boire", "Manger, aimer, boire"),
      body: tx(
        "**Manger** (to eat) and **aimer** (to like) end in -er, like most French verbs. Je mange, tu manges, il mange: all three sound exactly the same! Only the spelling changes.\n\nBefore a vowel, je becomes **j'**: j'aime, j'adore.\n\n**Boire** (to drink) has its own forms: je bois, tu bois, il boit.",
        "**Manger** (essen) und **aimer** (mögen) enden auf -er, wie die meisten französischen Verben. Je mange, tu manges, il mange: Alle drei klingen genau gleich! Nur die Schreibung ändert sich.\n\nVor einem Vokal wird je zu **j'**: j'aime, j'adore.\n\n**Boire** (trinken) hat eigene Formen: je bois, tu bois, il boit.",
      ),
      examples: [
        { fr: "Je mange une pomme.", en: "I'm eating an apple.", de: "Ich esse einen Apfel." },
        { fr: "Tu aimes le chocolat ?", en: "Do you like chocolate?", de: "Magst du Schokolade?" },
        { fr: "Il boit de l'eau.", en: "He's drinking water.", de: "Er trinkt Wasser." },
      ],
      table: {
        head: [tx("person", "Person"), "manger", "aimer", "boire"],
        rows: [
          [tx("I", "ich"), "je mange", "j'aime", "je bois"],
          [tx("you", "du"), "tu manges", "tu aimes", "tu bois"],
          [tx("he / she", "er / sie"), "il / elle mange", "il / elle aime", "il / elle boit"],
        ],
      },
    },
    {
      title: tx("Nous mangeons, vous mangez, ils mangent", "Nous mangeons, vous mangez, ils mangent"),
      body: tx(
        "With more people, manger has three more forms: **nous mangeons**, **vous mangez**, **ils mangent**. Nous mang**e**ons keeps an e so the g stays soft. The **-ent** of ils mangent is silent: it sounds just like il mange.\n\nAimer and adorer work the same way: nous aim**ons**, vous aim**ez**, ils aim**ent**.\n\nAfter ne … pas, des becomes **de**, or **d'** before a vowel: il ne mange pas **d'**œufs.",
        "Mit mehreren Leuten hat manger drei weitere Formen: **nous mangeons**, **vous mangez**, **ils mangent**. Nous mang**e**ons behält ein e, damit das g weich bleibt. Das **-ent** von ils mangent ist stumm: Es klingt genau wie il mange.\n\nAimer und adorer gehen genauso: nous aim**ons**, vous aim**ez**, ils aim**ent**.\n\nNach ne … pas wird des zu **de**, vor einem Vokal zu **d'**: il ne mange pas **d'**œufs.",
      ),
      examples: [
        { fr: "Nous mangeons des pâtes.", en: "We're eating pasta.", de: "Wir essen Nudeln." },
        { fr: "Vous aimez la soupe ?", en: "Do you like soup?", de: "Mögt ihr Suppe?" },
        { fr: "Hugo et Léa mangent des frites.", en: "Hugo and Léa are eating chips.", de: "Hugo und Léa essen Pommes." },
        { fr: "Il ne mange pas d'œufs.", en: "He doesn't eat eggs.", de: "Er isst keine Eier." },
      ],
      table: {
        head: [tx("person", "Person"), "manger", "aimer"],
        rows: [
          [tx("I", "ich"), "je mange", "j'aime"],
          [tx("you", "du"), "tu manges", "tu aimes"],
          [tx("he / she", "er / sie"), "il / elle mange", "il / elle aime"],
          [tx("we", "wir"), "nous mangeons", "nous aimons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous mangez", "vous aimez"],
          [tx("they", "sie"), "ils / elles mangent", "ils / elles aiment"],
        ],
      },
    },
  ],
};
