import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 4: family and pets, avoir in all its forms, mon/ma/mes, ton/ta/tes, son/sa/ses. */
export const u04: Unit = {
  slug: "famille",
  n: 4,
  cefr: "A1",
  title: tx("My family", "Meine Familie"),
  goal: tx("Talk about your family and pets, and say what you have", "Über deine Familie und Haustiere sprechen und sagen, was du hast"),
  emoji: "👨‍👩‍👧",
  words: [
    { id: "mere", fr: "la mère", en: "the mother", de: "die Mutter", g: "f", kind: "noun", note: tx("At home you just say maman.", "Zu Hause sagt man einfach maman.") },
    { id: "pere", fr: "le père", en: "the father", de: "der Vater", g: "m", kind: "noun", note: tx("At home you just say papa.", "Zu Hause sagt man einfach papa.") },
    { id: "parents", fr: "les parents", en: "the parents", de: "die Eltern", g: "m", kind: "noun" },
    { id: "maman", fr: "maman", en: "mum", de: "Mama", alt: { en: ["mom"] }, kind: "word" },
    { id: "papa", fr: "papa", en: "dad", de: "Papa", alt: { en: ["daddy"] }, kind: "word" },
    { id: "famille", fr: "la famille", en: "the family", de: "die Familie", g: "f", kind: "noun", emoji: "👨‍👩‍👧‍👦", note: tx("Say «fa-MEE-y»: the double l sounds like a y.", "Sprich „fa-MIJ“: Das doppelte l klingt wie ein j.") },
    { id: "frere", fr: "le frère", en: "the brother", de: "der Bruder", g: "m", kind: "noun", note: tx("The è sounds like the e in «bed».", "Das è klingt wie das ä in „Bär“.") },
    { id: "soeur", fr: "la sœur", en: "the sister", de: "die Schwester", g: "f", kind: "noun", note: tx("œ is o and e glued together. Sœur sounds a bit like «sir».", "œ sind o und e zusammengeklebt. Sœur klingt ungefähr wie „Sör“.") },
    { id: "j-ai", fr: "j'ai", en: "I have", de: "ich habe", alt: { en: ["I've got"] }, kind: "verb", note: tx("Je + ai = j'ai. From avoir, to have.", "Je + ai = j'ai. Von avoir, haben.") },
    { id: "tu-as", fr: "tu as", en: "you have", de: "du hast", kind: "verb" },
    { id: "bebe", fr: "le bébé", en: "the baby", de: "das Baby", g: "m", kind: "noun", emoji: "👶", note: tx("Always le bébé, even for a baby girl!", "Immer le bébé, auch bei einem Mädchen!") },
    { id: "chien", fr: "le chien", en: "the dog", de: "der Hund", g: "m", kind: "noun", emoji: "🐶", note: tx("A French dog says «ouaf ouaf».", "Ein französischer Hund macht „ouaf ouaf“.") },
    { id: "chat", fr: "le chat", en: "the cat", de: "die Katze", g: "m", kind: "noun", emoji: "🐱", note: tx("The t is silent: «sha». A French cat says «miaou».", "Das t ist stumm: „scha“. Eine französische Katze macht „miaou“.") },
    { id: "lapin", fr: "le lapin", en: "the rabbit", de: "das Kaninchen", alt: { de: ["der Hase"] }, g: "m", kind: "noun", emoji: "🐰" },
    { id: "il-a", fr: "il a", en: "he has", de: "er hat", kind: "verb", note: tx("Just one letter: a. Elle a = she has.", "Nur ein Buchstabe: a. Elle a = sie hat.") },
    { id: "petit", fr: "petit", en: "small", de: "klein", alt: { en: ["little"] }, kind: "adj", note: tx("It goes before the noun: un petit chat. Feminine: petite.", "Es steht vor dem Nomen: un petit chat. Weiblich: petite.") },
    { id: "grand", fr: "grand", en: "big", de: "groß", alt: { en: ["tall"] }, kind: "adj", note: tx("Big or tall, and it goes before the noun: un grand chien.", "Groß, auch für Menschen, und es steht vor dem Nomen: un grand chien.") },
    { id: "grand-mere", fr: "la grand-mère", en: "the grandmother", de: "die Großmutter", alt: { en: ["the grandma"], de: ["die Oma"] }, g: "f", kind: "noun", emoji: "👵", note: tx("Grand + mère. Kids often say mamie.", "Grand + mère. Kinder sagen oft mamie.") },
    { id: "grand-pere", fr: "le grand-père", en: "the grandfather", de: "der Großvater", alt: { en: ["the grandad"], de: ["der Opa"] }, g: "m", kind: "noun", emoji: "👴", note: tx("Grand + père. Kids often say papi.", "Grand + père. Kinder sagen oft papi.") },
    { id: "grands-parents", fr: "les grands-parents", en: "the grandparents", de: "die Großeltern", g: "m", kind: "noun", note: tx("Grand gets an s here too: les grands-parents.", "Auch grand bekommt hier ein s: les grands-parents.") },
    { id: "nous-avons", fr: "nous avons", en: "we have", de: "wir haben", kind: "verb" },
    { id: "vous-avez", fr: "vous avez", en: "you have (plural / polite)", de: "ihr habt / Sie haben", kind: "verb" },
    { id: "ils-ont", fr: "ils ont", en: "they have", de: "sie haben", kind: "verb", note: tx("Ils ont (they have) has a z sound. Ils sont (they are) has an s.", "Ils ont (sie haben) mit weichem s wie in „Sonne“. Ils sont (sie sind) mit scharfem s.") },
    { id: "cousin", fr: "le cousin", en: "the cousin", de: "der Cousin", g: "m", kind: "noun" },
    { id: "cousine", fr: "la cousine", en: "the cousin (female)", de: "die Cousine", g: "f", kind: "noun", note: tx("Like ami and amie: add -e for a girl. Now you hear the n.", "Wie ami und amie: -e für ein Mädchen. Jetzt hört man das n.") },
    { id: "oncle", fr: "l'oncle", en: "the uncle", de: "der Onkel", g: "m", kind: "noun", note: tx("Le becomes l' before a vowel: l'oncle. A or an: un oncle.", "Vor einem Vokal wird le zu l': l'oncle. Ein Onkel: un oncle.") },
    { id: "tante", fr: "la tante", en: "the aunt", de: "die Tante", g: "f", kind: "noun", note: tx("Almost like German Tante, but through the nose: «tont».", "Fast wie das deutsche Tante, aber durch die Nase: „tant“.") },
    { id: "enfant", fr: "l'enfant", en: "the child", de: "das Kind", alt: { en: ["the kid"] }, g: "m", kind: "noun", emoji: "🧒", note: tx("Un enfant for a boy, une enfant for a girl. In les enfants you hear a z: «lay-zon-fon».", "Un enfant für einen Jungen, une enfant für ein Mädchen. Bei les enfants hört man ein weiches s: „le-san-fan“.") },
    { id: "notre", fr: "notre", en: "our", de: "unser", alt: { de: ["unsere"] }, kind: "word", note: tx("One thing: notre chat. Several: nos chats.", "Eine Sache: notre chat. Mehrere: nos chats.") },
    { id: "votre", fr: "votre", en: "your (plural / polite)", de: "euer / Ihr", alt: { de: ["eure", "Ihre"] }, kind: "word", note: tx("For several people, or politely: votre chien, Madame ? Several things: vos.", "Für mehrere Leute oder höflich: votre chien, Madame ? Mehrere Sachen: vos.") },
    { id: "leur", fr: "leur", en: "their", de: "ihr (von mehreren)", kind: "word", note: tx("One thing: leur chien. Several: leurs chiens.", "Eine Sache: leur chien. Mehrere: leurs chiens.") },
  ],
  gloss: [
    { fr: "ce sont", en: "these are / they are", de: "das sind" },
    { fr: "petite", en: "small (feminine)", de: "klein (weiblich)" },
    { fr: "grande", en: "big (feminine)", de: "groß (weiblich)" },
    { fr: "avons", en: "have (we)", de: "haben (wir)" },
    { fr: "avez", en: "have (you, plural / polite)", de: "habt / haben (Sie)" },
    { fr: "ont", en: "have (they)", de: "haben (sie)" },
    { fr: "cousins", en: "cousins", de: "Cousins" },
    { fr: "photo", en: "photo", de: "Foto" },
    { fr: "violets", en: "purple (plural)", de: "lila" },
    { fr: "bérets", en: "berets", de: "Baskenmützen" },
    { fr: "enfants", en: "children", de: "Kinder" },
    { fr: "nos", en: "our", de: "unsere" },
    { fr: "vos", en: "your (plural / polite)", de: "eure / Ihre" },
    { fr: "leurs", en: "their", de: "ihre (von mehreren)" },
  ],
  lessons: [
    { title: tx("Mum and Dad", "Mama und Papa"), words: ["mere", "pere", "parents", "maman", "papa", "famille"] },
    { title: tx("Brothers and sisters", "Geschwister"), words: ["frere", "soeur", "j-ai", "tu-as", "bebe"] },
    { title: tx("Cats and dogs", "Hunde und Katzen"), words: ["chien", "chat", "lapin", "il-a", "petit", "grand"] },
    { title: tx("Grandma and Grandpa", "Oma und Opa"), words: ["grand-mere", "grand-pere", "grands-parents", "nous-avons", "vous-avez", "ils-ont"] },
    { title: tx("The family photo", "Das Familienfoto"), words: ["cousin", "cousine"] },
    { title: tx("Aunts and uncles", "Tanten und Onkel"), words: ["oncle", "tante", "enfant"] },
    { title: tx("Our, your, their", "Unser, euer, ihr"), words: ["notre", "votre", "leur"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u04.01", lesson: 1, fr: "C'est ma mère.", en: "This is my mother.", de: "Das ist meine Mutter.", alt: { en: ["That is my mother.", "It is my mother.", "This is my mum.", "That is my mum.", "This is my mom.", "That is my mom."], de: ["Das ist meine Mama."] } },
    { id: "u04.02", lesson: 1, fr: "Mon père s'appelle Paul.", en: "My father's name is Paul.", de: "Mein Vater heißt Paul.", alt: { en: ["My father is called Paul.", "My dad is called Paul.", "My dad's name is Paul."], de: ["Mein Papa heißt Paul."] } },
    { id: "u04.03", lesson: 1, fr: "Ce sont mes parents.", en: "These are my parents.", de: "Das sind meine Eltern.", alt: { fr: ["C'est mes parents."], en: ["Those are my parents.", "They are my parents."] } },
    { id: "u04.04", lesson: 1, fr: "Merci, maman !", en: "Thanks, Mum!", de: "Danke, Mama!", alt: { en: ["Thank you, Mum!", "Thanks, Mom!", "Thank you, Mom!"], de: ["Danke, Mutti!"] } },
    { id: "u04.05", lesson: 1, fr: "Papa, tu es fatigué ?", en: "Dad, are you tired?", de: "Papa, bist du müde?", alt: { fr: ["Tu es fatigué, papa ?", "Papa, es-tu fatigué ?", "Papa, est-ce que tu es fatigué ?"], en: ["Are you tired, Dad?", "Dad, you are tired?", "Daddy, are you tired?"], de: ["Bist du müde, Papa?"] } },
    { id: "u04.06", lesson: 1, fr: "Ma famille est très sympa.", en: "My family is very nice.", de: "Meine Familie ist sehr nett.", alt: { en: ["My family is really nice.", "My family is very friendly."], de: ["Meine Familie ist sehr sympathisch."] } },
    { id: "u04.07", lesson: 1, fr: "Tes parents sont français ?", en: "Are your parents French?", de: "Sind deine Eltern Franzosen?", alt: { fr: ["Vos parents sont français ?", "Est-ce que tes parents sont français ?", "Est-ce que vos parents sont français ?", "Tes parents, ils sont français ?"], en: ["Your parents are French?"], de: ["Deine Eltern sind Franzosen?"] } },
    // Lesson 2
    { id: "u04.08", lesson: 2, fr: "J'ai un frère.", en: "I have a brother.", de: "Ich habe einen Bruder.", alt: { en: ["I have got a brother."] } },
    { id: "u04.09", lesson: 2, fr: "Tu as une sœur ?", en: "Do you have a sister?", de: "Hast du eine Schwester?", alt: { fr: ["As-tu une sœur ?", "Est-ce que tu as une sœur ?", "Vous avez une sœur ?", "Avez-vous une sœur ?"], en: ["Have you got a sister?", "You have a sister?"], de: ["Du hast eine Schwester?"] } },
    { id: "u04.10", lesson: 2, fr: "Oui, j'ai une sœur et un frère.", en: "Yes, I have a sister and a brother.", de: "Ja, ich habe eine Schwester und einen Bruder.", alt: { en: ["Yes, I have got a sister and a brother."] } },
    { id: "u04.11", lesson: 2, fr: "C'est le bébé de ma sœur.", en: "It's my sister's baby.", de: "Das ist das Baby meiner Schwester.", alt: { en: ["This is my sister's baby.", "That is my sister's baby."], de: ["Das ist das Baby von meiner Schwester."] } },
    { id: "u04.12", lesson: 2, fr: "Ton frère est sympa ?", en: "Is your brother nice?", de: "Ist dein Bruder nett?", alt: { fr: ["Est-ce que ton frère est sympa ?", "Ton frère, il est sympa ?", "Votre frère est sympa ?"], en: ["Your brother is nice?", "Is your brother friendly?"], de: ["Dein Bruder ist nett?", "Ist dein Bruder sympathisch?"] } },
    { id: "u04.13", lesson: 2, fr: "Je n'ai pas de sœur.", en: "I don't have a sister.", de: "Ich habe keine Schwester.", alt: { fr: ["Je n'ai pas de sœurs."], en: ["I have not got a sister.", "I have no sister.", "I don't have any sisters.", "I have no sisters."] } },
    { id: "u04.14", lesson: 2, fr: "Ta sœur s'appelle comment ?", en: "What's your sister's name?", de: "Wie heißt deine Schwester?", alt: { fr: ["Comment s'appelle ta sœur ?", "Comment elle s'appelle, ta sœur ?", "Elle s'appelle comment, ta sœur ?", "Comment ta sœur s'appelle ?", "Votre sœur s'appelle comment ?", "Comment s'appelle votre sœur ?"], en: ["What is your sister called?"] } },
    // Lesson 3
    { id: "u04.15", lesson: 3, fr: "Léa a un chien.", en: "Léa has a dog.", de: "Léa hat einen Hund.", alt: { en: ["Léa has got a dog.", "Léa's got a dog."] } },
    { id: "u04.16", lesson: 3, fr: "Il a un petit chat.", en: "He has a small cat.", de: "Er hat eine kleine Katze.", alt: { en: ["He has a little cat.", "He has got a small cat.", "He has got a little cat.", "He's got a small cat.", "He's got a little cat."] } },
    { id: "u04.17", lesson: 3, fr: "Son chien est très grand.", en: "His dog is very big.", de: "Sein Hund ist sehr groß.", alt: { en: ["Her dog is very big.", "His dog is very large.", "Her dog is very large.", "His dog is really big.", "Her dog is really big."], de: ["Ihr Hund ist sehr groß."] } },
    { id: "u04.18", lesson: 3, fr: "Sa petite sœur s'appelle Chloé.", en: "Her little sister is called Chloé.", de: "Ihre kleine Schwester heißt Chloé.", alt: { en: ["His little sister is called Chloé.", "Her little sister's name is Chloé.", "His little sister's name is Chloé.", "Her younger sister is called Chloé.", "His younger sister is called Chloé.", "Her younger sister's name is Chloé.", "His younger sister's name is Chloé."], de: ["Seine kleine Schwester heißt Chloé.", "Ihre jüngere Schwester heißt Chloé.", "Seine jüngere Schwester heißt Chloé."] } },
    { id: "u04.19", lesson: 3, fr: "Tu as un chat ou un chien ?", en: "Do you have a cat or a dog?", de: "Hast du eine Katze oder einen Hund?", alt: { fr: ["As-tu un chat ou un chien ?", "Est-ce que tu as un chat ou un chien ?", "Vous avez un chat ou un chien ?", "Avez-vous un chat ou un chien ?"], en: ["Have you got a cat or a dog?", "You have a cat or a dog?"] } },
    { id: "u04.20", lesson: 3, fr: "Mon lapin s'appelle Caramel.", en: "My rabbit is called Caramel.", de: "Mein Kaninchen heißt Caramel.", alt: { en: ["My rabbit's name is Caramel."], de: ["Mein Hase heißt Caramel."] } },
    { id: "u04.21", lesson: 3, fr: "Elle a un grand chien.", en: "She has a big dog.", de: "Sie hat einen großen Hund.", alt: { en: ["She has got a big dog.", "She's got a big dog.", "She has a large dog.", "She has got a large dog.", "She's got a large dog."] } },
    // Lesson 4
    { id: "u04.22", lesson: 4, fr: "Nous avons un chien et un chat.", en: "We have a dog and a cat.", de: "Wir haben einen Hund und eine Katze.", alt: { fr: ["On a un chien et un chat."], en: ["We have got a dog and a cat."] } },
    { id: "u04.23", lesson: 4, fr: "Madame Martin, vous avez un chat ?", en: "Mrs Martin, do you have a cat?", de: "Frau Martin, haben Sie eine Katze?", alt: { fr: ["Vous avez un chat, Madame Martin ?", "Madame Martin, avez-vous un chat ?", "Madame Martin, est-ce que vous avez un chat ?", "Avez-vous un chat, Madame Martin ?"], en: ["Mrs Martin, have you got a cat?", "Do you have a cat, Mrs Martin?", "Have you got a cat, Mrs Martin?"], de: ["Haben Sie eine Katze, Frau Martin?"] } },
    { id: "u04.24", lesson: 4, fr: "Mes grands-parents ont un lapin.", en: "My grandparents have a rabbit.", de: "Meine Großeltern haben ein Kaninchen.", alt: { en: ["My grandparents have got a rabbit."], de: ["Meine Großeltern haben einen Hasen."] } },
    { id: "u04.25", lesson: 4, fr: "Ma grand-mère est très sympa.", en: "My grandmother is very nice.", de: "Meine Oma ist sehr nett.", alt: { en: ["My grandma is very nice.", "My granny is very nice.", "My nan is very nice.", "My grandmother is really nice.", "My grandma is really nice."], de: ["Meine Großmutter ist sehr nett.", "Meine Oma ist sehr sympathisch."] } },
    { id: "u04.26", lesson: 4, fr: "Mon grand-père est allemand.", en: "My grandfather is German.", de: "Mein Opa ist Deutscher.", alt: { en: ["My grandad is German.", "My granddad is German.", "My grandpa is German."], de: ["Mein Großvater ist Deutscher."] } },
    { id: "u04.27", lesson: 4, fr: "Ils ont un grand chien.", en: "They have a big dog.", de: "Sie haben einen großen Hund.", alt: { fr: ["Elles ont un grand chien."], en: ["They have got a big dog.", "They have a large dog.", "They have got a large dog."] } },
    { id: "u04.28", lesson: 4, fr: "Vous avez une grande famille ?", en: "Do you have a big family?", de: "Habt ihr eine große Familie?", alt: { fr: ["Avez-vous une grande famille ?", "Est-ce que vous avez une grande famille ?", "Tu as une grande famille ?", "As-tu une grande famille ?", "Est-ce que tu as une grande famille ?"], en: ["Have you got a big family?", "Do you have a large family?", "Have you got a large family?", "You have a big family?"], de: ["Haben Sie eine große Familie?"] } },
    // Lesson 5
    { id: "u04.29", lesson: 5, fr: "J'ai un cousin à Berlin.", en: "I have a cousin in Berlin.", de: "Ich habe einen Cousin in Berlin.", alt: { fr: ["J'ai une cousine à Berlin."], en: ["I have got a cousin in Berlin."] } },
    { id: "u04.30", lesson: 5, fr: "Ma cousine est anglaise.", en: "My cousin is English.", de: "Meine Cousine ist Engländerin.", alt: { fr: ["Mon cousin est anglais."] } },
    { id: "u04.31", lesson: 5, fr: "Nous n'avons pas de chat.", en: "We don't have a cat.", de: "Wir haben keine Katze.", alt: { fr: ["On n'a pas de chat."], en: ["We have not got a cat.", "We have no cat.", "We don't have any cats.", "We have no cats."] } },
    { id: "u04.32", lesson: 5, fr: "Ses cousins sont très sympas.", en: "His cousins are very nice.", de: "Seine Cousins sind sehr nett.", alt: { fr: ["Ses cousines sont très sympas."], en: ["Her cousins are very nice.", "His cousins are really nice.", "Her cousins are really nice.", "His cousins are very friendly.", "Her cousins are very friendly."], de: ["Ihre Cousins sind sehr nett.", "Seine Cousins sind sehr sympathisch.", "Ihre Cousins sind sehr sympathisch."] } },
    { id: "u04.33", lesson: 5, fr: "Ta cousine a un bébé ?", en: "Does your cousin have a baby?", de: "Hat deine Cousine ein Baby?", alt: { fr: ["Ton cousin a un bébé ?", "Est-ce que ta cousine a un bébé ?", "Est-ce que ton cousin a un bébé ?", "Votre cousine a un bébé ?", "Votre cousin a un bébé ?"], en: ["Has your cousin got a baby?", "Your cousin has a baby?"], de: ["Deine Cousine hat ein Baby?"] } },
    { id: "u04.34", lesson: 5, fr: "Mon cousin n'a pas de frère.", en: "My cousin doesn't have a brother.", de: "Mein Cousin hat keinen Bruder.", alt: { fr: ["Ma cousine n'a pas de frère."], en: ["My cousin has not got a brother.", "My cousin has no brother.", "My cousin doesn't have any brothers.", "My cousin has no brothers."] } },
    { id: "u04.35", lesson: 5, fr: "J'ai un grand frère et une petite sœur.", en: "I have a big brother and a little sister.", de: "Ich habe einen großen Bruder und eine kleine Schwester.", alt: { en: ["I have an older brother and a younger sister.", "I have got a big brother and a little sister.", "I have got an older brother and a younger sister.", "I have a big brother and a younger sister.", "I have an older brother and a little sister."], de: ["Ich habe einen älteren Bruder und eine jüngere Schwester."] } },
    // Lesson 6
    { id: "u04.36", lesson: 6, fr: "J'ai un oncle et une tante.", en: "I have an uncle and an aunt.", de: "Ich habe einen Onkel und eine Tante.", alt: { en: ["I have got an uncle and an aunt."] } },
    { id: "u04.37", lesson: 6, fr: "Mon oncle n'a pas d'enfants.", en: "My uncle doesn't have any children.", de: "Mein Onkel hat keine Kinder.", alt: { fr: ["Mon oncle n'a pas d'enfant."], en: ["My uncle has no children.", "My uncle hasn't got any children.", "My uncle doesn't have children.", "My uncle doesn't have any kids.", "My uncle has no kids."] } },
    { id: "u04.38", lesson: 6, fr: "Vous avez des enfants, Monsieur Martin ?", en: "Do you have children, Mr Martin?", de: "Haben Sie Kinder, Herr Martin?", alt: { fr: ["Monsieur Martin, vous avez des enfants ?", "Avez-vous des enfants, Monsieur Martin ?", "Monsieur Martin, avez-vous des enfants ?", "Est-ce que vous avez des enfants, Monsieur Martin ?"], en: ["Have you got children, Mr Martin?", "Do you have any children, Mr Martin?", "Have you got any children, Mr Martin?", "Mr Martin, do you have children?", "Mr Martin, do you have any children?"], de: ["Herr Martin, haben Sie Kinder?"] } },
    { id: "u04.39", lesson: 6, fr: "Les enfants de ma tante sont très sympas.", en: "My aunt's children are very nice.", de: "Die Kinder meiner Tante sind sehr nett.", alt: { en: ["My aunt's children are really nice.", "My aunt's kids are very nice.", "My aunt's children are very friendly."], de: ["Die Kinder von meiner Tante sind sehr nett.", "Die Kinder meiner Tante sind sehr sympathisch."] } },
    { id: "u04.40", lesson: 6, fr: "Ton oncle est allemand ?", en: "Is your uncle German?", de: "Ist dein Onkel Deutscher?", alt: { fr: ["Est-ce que ton oncle est allemand ?", "Ton oncle, il est allemand ?", "Votre oncle est allemand ?", "Est-ce que votre oncle est allemand ?"], en: ["Your uncle is German?"], de: ["Dein Onkel ist Deutscher?"] } },
    { id: "u04.41", lesson: 6, fr: "Sa tante a un grand chien.", en: "His aunt has a big dog.", de: "Seine Tante hat einen großen Hund.", alt: { en: ["Her aunt has a big dog.", "His aunt has got a big dog.", "Her aunt has got a big dog.", "His aunt has a large dog.", "Her aunt has a large dog."], de: ["Ihre Tante hat einen großen Hund."] } },
    { id: "u04.42", lesson: 6, fr: "Ils ont des enfants ?", en: "Do they have children?", de: "Haben sie Kinder?", alt: { fr: ["Elles ont des enfants ?", "Ont-ils des enfants ?", "Ont-elles des enfants ?", "Est-ce qu'ils ont des enfants ?", "Est-ce qu'elles ont des enfants ?"], en: ["Have they got children?", "Do they have any children?", "Have they got any children?", "They have children?"], de: ["Sie haben Kinder?"] } },
    { id: "u04.43", lesson: 6, fr: "Mon oncle et ma tante ont un lapin.", en: "My uncle and aunt have a rabbit.", de: "Mein Onkel und meine Tante haben ein Kaninchen.", alt: { en: ["My uncle and my aunt have a rabbit.", "My uncle and aunt have got a rabbit.", "My uncle and my aunt have got a rabbit."], de: ["Mein Onkel und meine Tante haben einen Hasen."] } },
    // Lesson 7
    { id: "u04.44", lesson: 7, fr: "C'est notre chat.", en: "This is our cat.", de: "Das ist unsere Katze.", alt: { en: ["That is our cat.", "It is our cat."] } },
    { id: "u04.45", lesson: 7, fr: "Nos parents sont fatigués.", en: "Our parents are tired.", de: "Unsere Eltern sind müde." },
    { id: "u04.46", lesson: 7, fr: "C'est votre chien, Madame Martin ?", en: "Is that your dog, Mrs Martin?", de: "Ist das Ihr Hund, Frau Martin?", alt: { fr: ["Madame Martin, c'est votre chien ?", "Est-ce que c'est votre chien, Madame Martin ?", "Est-ce votre chien, Madame Martin ?"], en: ["Is this your dog, Mrs Martin?", "Is it your dog, Mrs Martin?", "Mrs Martin, is that your dog?"], de: ["Frau Martin, ist das Ihr Hund?"] } },
    { id: "u04.47", lesson: 7, fr: "Non, ce n'est pas notre chien.", en: "No, it's not our dog.", de: "Nein, das ist nicht unser Hund.", alt: { en: ["No, that is not our dog.", "No, this is not our dog."], de: ["Nein, es ist nicht unser Hund."] } },
    { id: "u04.48", lesson: 7, fr: "Vos enfants sont très sympas !", en: "Your children are very nice!", de: "Eure Kinder sind sehr nett!", alt: { fr: ["Tes enfants sont très sympas !"], en: ["Your kids are very nice!", "Your children are really nice!"], de: ["Ihre Kinder sind sehr nett!", "Eure Kinder sind sehr sympathisch!", "Deine Kinder sind sehr nett!"] } },
    { id: "u04.49", lesson: 7, fr: "Leur chien est très petit.", en: "Their dog is very small.", de: "Ihr Hund ist sehr klein.", alt: { en: ["Their dog is very little.", "Their dog is really small."] } },
    { id: "u04.50", lesson: 7, fr: "Ce sont leurs enfants ?", en: "Are those their children?", de: "Sind das ihre Kinder?", alt: { fr: ["Est-ce que ce sont leurs enfants ?", "C'est leurs enfants ?"], en: ["Are these their children?", "Are they their children?", "Are those their kids?", "Those are their children?"], de: ["Das sind ihre Kinder?"] } },
    { id: "u04.51", lesson: 7, fr: "Notre famille n'est pas très grande.", en: "Our family isn't very big.", de: "Unsere Familie ist nicht sehr groß.", alt: { en: ["Our family isn't very large."], de: ["Unsere Familie ist nicht besonders groß."] } },
  ],
  drills: [
    { id: "u04.d1", lesson: 1, fr: "C'est ___ mère.", options: ["ma", "mon", "mes"], answer: 0, en: "This is my mother.", de: "Das ist meine Mutter.", why: tx("Mère is feminine: **ma** mère.", "Mère ist weiblich: **ma** mère.") },
    { id: "u04.d2", lesson: 1, fr: "Ce sont ___ parents.", options: ["mes", "mon", "ma"], answer: 0, en: "These are my parents.", de: "Das sind meine Eltern.", why: tx("Parents is plural: **mes** parents.", "Parents ist Plural: **mes** parents.") },
    { id: "u04.d3", lesson: 2, fr: "J'___ un frère.", options: ["ai", "as", "a"], answer: 0, en: "I have a brother.", de: "Ich habe einen Bruder.", why: tx("With je it's **j'ai** (je + ai).", "Mit je heißt es **j'ai** (je + ai).") },
    { id: "u04.d4", lesson: 2, fr: "C'est ___ frère ?", options: ["ton", "ta", "tes"], answer: 0, en: "Is that your brother?", de: "Ist das dein Bruder?", why: tx("Frère is masculine: **ton** frère.", "Frère ist männlich: **ton** frère.") },
    { id: "u04.d5", lesson: 3, fr: "Léa ___ un chien.", options: ["a", "as", "ai"], answer: 0, en: "Léa has a dog.", de: "Léa hat einen Hund.", why: tx("With il, elle or a name: **a**. Léa a un chien.", "Mit il, elle oder einem Namen: **a**. Léa a un chien.") },
    { id: "u04.d6", lesson: 3, fr: "Hugo a une ___ sœur.", options: ["petite", "petit"], answer: 0, en: "Hugo has a little sister.", de: "Hugo hat eine kleine Schwester.", why: tx("Sœur is feminine: **petite**, and you hear the t.", "Sœur ist weiblich: **petite**, und man hört das t.") },
    { id: "u04.d7", lesson: 3, fr: "Léa ? ___ chat est petit.", options: ["Son", "Sa", "Ses"], answer: 0, en: "Léa? Her cat is small.", de: "Léa? Ihre Katze ist klein.", why: tx("Chat is masculine, so it's **son** chat, even when it's Léa's. Son, sa, ses agree with the thing, not the owner.", "Chat ist männlich, also **son** chat, auch wenn er Léa gehört. Son, sa, ses richten sich nach der Sache, nicht nach dem Besitzer.") },
    { id: "u04.d8", lesson: 4, fr: "Nous ___ un chat.", options: ["avons", "avez", "ont"], answer: 0, en: "We have a cat.", de: "Wir haben eine Katze.", why: tx("With **nous** it's **avons**.", "Mit **nous** heißt es **avons**.") },
    { id: "u04.d9", lesson: 4, fr: "Vous ___ une grande famille ?", options: ["avez", "avons", "as"], answer: 0, en: "Do you have a big family?", de: "Habt ihr eine große Familie?", why: tx("With **vous** it's **avez**.", "Mit **vous** heißt es **avez**.") },
    { id: "u04.d10", lesson: 4, fr: "Mes grands-parents ___ un lapin.", options: ["ont", "sont", "a"], answer: 0, en: "My grandparents have a rabbit.", de: "Meine Großeltern haben ein Kaninchen.", why: tx("They have: **ont**. Careful, sont means they are.", "Sie haben: **ont**. Vorsicht, sont heißt sie sind.") },
    { id: "u04.d11", lesson: 5, fr: "C'est ___ cousine.", options: ["ma", "mon"], answer: 0, en: "This is my cousin.", de: "Das ist meine Cousine.", why: tx("A girl cousin is feminine: **ma** cousine. A boy is mon cousin.", "Cousine ist weiblich: **ma** cousine. Ein Junge ist mon cousin.") },
    { id: "u04.d12", lesson: 5, fr: "Je n'ai pas ___ cousin.", options: ["de", "du", "des"], answer: 0, en: "I don't have a cousin.", de: "Ich habe keinen Cousin.", why: tx("After ne … pas, un becomes **de**: pas de cousin.", "Nach ne … pas wird un zu **de**: pas de cousin.") },
    { id: "u04.d13", lesson: 6, fr: "J'ai un oncle et ___ tante.", options: ["une", "un"], answer: 0, en: "I have an uncle and an aunt.", de: "Ich habe einen Onkel und eine Tante.", why: tx("Tante is feminine: **une** tante.", "Tante ist weiblich: **une** tante.") },
    { id: "u04.d14", lesson: 6, fr: "Ils ___ des enfants ?", options: ["ont", "a", "avez"], answer: 0, en: "Do they have children?", de: "Haben sie Kinder?", why: tx("With **ils**, avoir is **ont**: ils ont.", "Mit **ils** heißt avoir **ont**: ils ont.") },
    { id: "u04.d15", lesson: 6, fr: "Hugo ? ___ tante est anglaise.", options: ["Sa", "Son", "Ses"], answer: 0, en: "Hugo? His aunt is English.", de: "Hugo? Seine Tante ist Engländerin.", why: tx("Tante is feminine: **sa** tante, even for Hugo's aunt. Son, sa, ses agree with the thing, not the owner.", "Tante ist weiblich: **sa** tante, auch bei Hugos Tante. Son, sa, ses richten sich nach der Sache, nicht nach dem Besitzer.") },
    { id: "u04.d16", lesson: 7, fr: "Nous avons un chat. C'est ___ chat.", options: ["notre", "nos", "nous"], answer: 0, en: "We have a cat. It's our cat.", de: "Wir haben eine Katze. Das ist unsere Katze.", why: tx("One cat: **notre** chat. Several cats: nos chats.", "Eine Katze: **notre** chat. Mehrere Katzen: nos chats.") },
    { id: "u04.d17", lesson: 7, fr: "Madame Martin, ce sont ___ enfants ?", options: ["vos", "votre"], answer: 0, en: "Mrs Martin, are those your children?", de: "Frau Martin, sind das Ihre Kinder?", why: tx("Enfants is plural: **vos** enfants. Just one: votre enfant.", "Enfants ist Plural: **vos** enfants. Nur eins: votre enfant.") },
    { id: "u04.d18", lesson: 7, fr: "Monsieur et Madame Martin ? ___ chien est petit.", options: ["Leur", "Leurs", "Ils"], answer: 0, en: "Mr and Mrs Martin? Their dog is small.", de: "Herr und Frau Martin? Ihr Hund ist klein.", why: tx("Two owners, one dog: **leur** chien. Several dogs: leurs chiens.", "Zwei Besitzer, ein Hund: **leur** chien. Mehrere Hunde: leurs chiens.") },
  ],
  dialogues: [
    {
      id: "u04.dialogue",
      lesson: 5,
      title: tx("The family photo", "Das Familienfoto"),
      lines: [
        { who: "lea", fr: "Blob, c'est une photo de ma famille.", en: "Blob, this is a photo of my family.", de: "Blob, das ist ein Foto von meiner Familie." },
        { who: "blob", fr: "Qui est-ce ? C'est ton père ?", en: "Who's that? Is it your father?", de: "Wer ist das? Ist das dein Vater?" },
        { who: "lea", fr: "Non, c'est mon grand-père. Il a un grand chien.", en: "No, that's my grandfather. He has a big dog.", de: "Nein, das ist mein Opa. Er hat einen großen Hund." },
        { who: "blob", fr: "Et la petite fille, c'est ta sœur ?", en: "And the little girl, is that your sister?", de: "Und das kleine Mädchen, ist das deine Schwester?" },
        { who: "lea", fr: "Oui, ma sœur Chloé. Et le bébé, c'est mon cousin.", en: "Yes, my sister Chloé. And the baby is my cousin.", de: "Ja, meine Schwester Chloé. Und das Baby ist mein Cousin." },
        { who: "blob", fr: "Vous avez un chat aussi ?", en: "Do you have a cat too?", de: "Habt ihr auch eine Katze?" },
        { who: "lea", fr: "Non, nous avons un lapin. Et toi, tu as une famille ?", en: "No, we have a rabbit. And you, do you have a family?", de: "Nein, wir haben ein Kaninchen. Und du, hast du eine Familie?" },
        { who: "blob", fr: "Oui ! Une grande famille. Ils sont violets et ils ont des bérets !", en: "Yes! A big family. They're purple and they have berets!", de: "Ja! Eine große Familie. Sie sind lila und haben Baskenmützen!" },
        { who: "lea", fr: "Une famille de Blobs avec des bérets ? J'adore !", en: "A family of Blobs with berets? I love it!", de: "Eine Blob-Familie mit Baskenmützen? Wie toll!" },
      ],
      questions: [
        { q: tx("Who has a big dog?", "Wer hat einen großen Hund?"), options: [tx("Léa's grandfather", "Léas Opa"), tx("Léa's father", "Léas Vater"), tx("Léa's cousin", "Léas Cousin")], answer: 0 },
        { q: tx("Who is the baby?", "Wer ist das Baby?"), options: [tx("Léa's cousin", "Léas Cousin"), tx("Léa's sister", "Léas Schwester"), tx("Léa's brother", "Léas Bruder")], answer: 0 },
        { q: tx("Which pet does Léa have at home?", "Welches Haustier hat Léa zu Hause?"), options: [tx("A rabbit", "Ein Kaninchen"), tx("A cat", "Eine Katze"), tx("A fish", "Einen Fisch")], answer: 0 },
      ],
    },
    {
      id: "u04.dialogue2",
      lesson: 7,
      title: tx("Whose dog is it?", "Wem gehört der Hund?"),
      lines: [
        { who: "hugo", fr: "Regarde, Blob ! Un petit chien !", en: "Look, Blob! A little dog!", de: "Schau, Blob! Ein kleiner Hund!" },
        { who: "blob", fr: "C'est ton chien, Hugo ?", en: "Is it your dog, Hugo?", de: "Ist das dein Hund, Hugo?" },
        { who: "hugo", fr: "Non, ce n'est pas mon chien. Je n'ai pas de chien.", en: "No, it's not my dog. I don't have a dog.", de: "Nein, das ist nicht mein Hund. Ich habe keinen Hund." },
        { who: "blob", fr: "Madame Martin ! C'est votre chien ?", en: "Mrs Martin! Is it your dog?", de: "Frau Martin! Ist das Ihr Hund?" },
        { who: "madame", fr: "Non, ce n'est pas notre chien. Nous avons un chat.", en: "No, it's not our dog. We have a cat.", de: "Nein, das ist nicht unser Hund. Wir haben eine Katze." },
        { who: "lea", fr: "C'est le chien de mon oncle et de ma tante !", en: "It's my uncle and aunt's dog!", de: "Das ist der Hund von meinem Onkel und meiner Tante!" },
        { who: "blob", fr: "Il s'appelle comment, leur chien ?", en: "What's their dog called?", de: "Wie heißt denn ihr Hund?" },
        { who: "lea", fr: "Il s'appelle Béret !", en: "He's called Béret!", de: "Er heißt Béret!" },
        { who: "blob", fr: "Béret ? Un chien qui s'appelle Béret ? J'adore !", en: "Béret? A dog called Béret? I love it!", de: "Béret? Ein Hund, der Béret heißt? Toll!" },
        { who: "lea", fr: "Et il mange les bérets, Blob !", en: "And he eats berets, Blob!", de: "Und er frisst Baskenmützen, Blob!" },
      ],
      questions: [
        { q: tx("Does Hugo have a dog?", "Hat Hugo einen Hund?"), options: [tx("No", "Nein"), tx("Yes, a little dog", "Ja, einen kleinen Hund"), tx("Yes, a big dog", "Ja, einen großen Hund")], answer: 0 },
        { q: tx("Whose dog is it?", "Wem gehört der Hund?"), options: [tx("Léa's uncle and aunt's", "Léas Onkel und Tante"), tx("Mrs Martin's", "Frau Martin"), tx("Hugo's", "Hugo")], answer: 0 },
        { q: tx("What is the dog called?", "Wie heißt der Hund?"), options: ["Béret", "Caramel", "Blob"], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Avoir: to have", "Avoir: haben"),
      body: tx(
        "**Avoir** (to have) is the second big verb, next to être. Je + ai = **j'ai**.\n\nDon't mix up **ils ont** (they have) and **ils sont** (they are). In ils ont you hear a z: «il-ZON». In ils sont you hear an s.",
        "**Avoir** (haben) ist neben être das zweite große Verb. Je + ai = **j'ai**.\n\nVerwechsle **ils ont** (sie haben) nicht mit **ils sont** (sie sind). Bei ils ont hört man ein weiches s wie in „Sonne“, bei ils sont ein scharfes s wie in „Bus“.",
      ),
      examples: [
        { fr: "J'ai un frère.", en: "I have a brother.", de: "Ich habe einen Bruder." },
        { fr: "Nous avons un chien et un chat.", en: "We have a dog and a cat.", de: "Wir haben einen Hund und eine Katze." },
        { fr: "Ils ont un grand chien.", en: "They have a big dog.", de: "Sie haben einen großen Hund." },
      ],
      table: {
        head: [tx("person", "Person"), "avoir"],
        rows: [
          [tx("I", "ich"), "j'ai"],
          [tx("you", "du"), "tu as"],
          [tx("he / she", "er / sie"), "il / elle a"],
          [tx("we", "wir"), "nous avons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous avez"],
          [tx("they", "sie"), "ils / elles ont"],
        ],
      },
    },
    {
      title: tx("Mon, ma, mes: my", "Mon, ma, mes: mein"),
      body: tx(
        "My, your, his and her change with the noun that follows: **mon** père, **ma** mère, **mes** parents.\n\n**Son, sa, ses** mean both his and her. They agree with the thing, not with the owner: Léa's dog is **son** chien, Hugo's family is **sa** famille.\n\nBefore a vowel, ma becomes **mon**: mon amie.",
        "Mein, dein, sein und ihr richten sich nach dem Nomen danach: **mon** père, **ma** mère, **mes** parents.\n\n**Son, sa, ses** heißen sein und ihr. Sie richten sich nach der Sache, nicht nach dem Besitzer: Léas Hund ist **son** chien, Hugos Familie ist **sa** famille.\n\nVor einem Vokal wird ma zu **mon**: mon amie.",
      ),
      examples: [
        { fr: "C'est ma mère.", en: "This is my mother.", de: "Das ist meine Mutter." },
        { fr: "Ton frère est sympa ?", en: "Is your brother nice?", de: "Ist dein Bruder nett?" },
        { fr: "Son chien est très grand.", en: "His (or her) dog is very big.", de: "Sein (oder ihr) Hund ist sehr groß." },
      ],
      table: {
        head: [tx("whose", "wessen"), tx("masculine", "männlich"), tx("feminine", "weiblich"), tx("plural", "Plural")],
        rows: [
          [tx("my", "mein"), "mon père", "ma mère", "mes parents"],
          [tx("your", "dein"), "ton frère", "ta sœur", "tes cousins"],
          [tx("his / her", "sein / ihr"), "son chien", "sa famille", "ses grands-parents"],
        ],
      },
    },
    {
      title: tx("Petit, grand: before the noun", "Petit, grand: vor dem Nomen"),
      body: tx(
        "Most describing words come after the noun (le fromage français), but **petit** and **grand** come before it: un **petit** chat, un **grand** chien.\n\nWith a feminine noun they add -e, and you hear the last letter: une peti**te** sœur, une gran**de** famille.\n\nUn **grand frère** is a big (older) brother.",
        "Die meisten beschreibenden Wörter stehen nach dem Nomen (le fromage français), aber **petit** und **grand** stehen davor: un **petit** chat, un **grand** chien.\n\nBei weiblichen Nomen kommt ein -e dazu, und man hört den letzten Buchstaben: une peti**te** sœur, une gran**de** famille.\n\nUn **grand frère** ist ein großer (älterer) Bruder.",
      ),
      examples: [
        { fr: "Il a un petit chat.", en: "He has a small cat.", de: "Er hat eine kleine Katze." },
        { fr: "Vous avez une grande famille ?", en: "Do you have a big family?", de: "Habt ihr eine große Familie?" },
        { fr: "J'ai un grand frère et une petite sœur.", en: "I have a big brother and a little sister.", de: "Ich habe einen großen Bruder und eine kleine Schwester." },
      ],
    },
    {
      title: tx("Notre, votre, leur: our, your, their", "Notre, votre, leur: unser, euer, ihr"),
      body: tx(
        "When things belong to several people: **notre** (our), **votre** (your, for several people or polite) and **leur** (their). They're the same for masculine and feminine: notre chat, notre famille.\n\nWith a plural noun they become **nos**, **vos**, **leurs**: nos parents, vos enfants, leurs chiens.",
        "Wenn etwas mehreren gehört: **notre** (unser), **votre** (euer, oder höflich Ihr) und **leur** (ihr, von mehreren). Sie sind für männlich und weiblich gleich: notre chat, notre famille.\n\nVor einem Nomen im Plural werden sie zu **nos**, **vos**, **leurs**: nos parents, vos enfants, leurs chiens.",
      ),
      examples: [
        { fr: "C'est notre chat.", en: "This is our cat.", de: "Das ist unsere Katze." },
        { fr: "C'est votre chien, Madame Martin ?", en: "Is that your dog, Mrs Martin?", de: "Ist das Ihr Hund, Frau Martin?" },
        { fr: "Leur chien est très petit.", en: "Their dog is very small.", de: "Ihr Hund ist sehr klein." },
        { fr: "Vos enfants sont très sympas !", en: "Your children are very nice!", de: "Eure Kinder sind sehr nett!" },
      ],
      table: {
        head: [tx("whose", "wessen"), tx("one thing", "eine Sache"), tx("several", "mehrere")],
        rows: [
          [tx("our", "unser"), "notre chat", "nos chats"],
          [tx("your (plural / polite)", "euer / Ihr"), "votre chien", "vos chiens"],
          [tx("their", "ihr (von mehreren)"), "leur famille", "leurs enfants"],
        ],
      },
    },
  ],
};
