import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 5: numbers 1 to 20, age with avoir, il y a, combien, birthdays. */
export const u05: Unit = {
  slug: "nombres",
  n: 5,
  cefr: "A1",
  title: tx("Numbers and birthdays", "Zahlen und Geburtstage"),
  goal: tx("Count to twenty, say how old you are and ask how many there are", "Bis zwanzig zählen, sagen, wie alt du bist, und fragen, wie viele es gibt"),
  emoji: "🔢",
  words: [
    { id: "num-1", fr: "un", en: "one", de: "eins", kind: "word", emoji: "1️⃣", note: tx("Before a feminine word it becomes une: une pomme.", "Vor weiblichen Wörtern wird es zu une: une pomme.") },
    { id: "num-2", fr: "deux", en: "two", de: "zwei", kind: "word", emoji: "2️⃣", note: tx("The x is silent: «duh». Before a vowel it sounds like z: deux amis.", "Das x ist stumm: „dö“. Vor einem Vokal klingt es wie ein weiches s: deux amis.") },
    { id: "num-3", fr: "trois", en: "three", de: "drei", kind: "word", emoji: "3️⃣", note: tx("Sounds like «trwa».", "Klingt wie „troa“.") },
    { id: "num-4", fr: "quatre", en: "four", de: "vier", kind: "word", emoji: "4️⃣" },
    { id: "num-5", fr: "cinq", en: "five", de: "fünf", kind: "word", emoji: "5️⃣", note: tx("Here the q is pronounced: «sank».", "Hier spricht man das q, wie ein k.") },
    { id: "num-6", fr: "six", en: "six", de: "sechs", kind: "word", emoji: "6️⃣", note: tx("Alone it's «sees», before a consonant just «see»: six chats.", "Allein hört man das x wie ein scharfes s, vor einem Konsonanten ist es stumm: six chats.") },
    { id: "num-7", fr: "sept", en: "seven", de: "sieben", kind: "word", emoji: "7️⃣", note: tx("The p is silent: «set».", "Das p ist stumm.") },
    { id: "num-8", fr: "huit", en: "eight", de: "acht", kind: "word", emoji: "8️⃣", note: tx("Say «weet».", "Sprich „üit“.") },
    { id: "num-9", fr: "neuf", en: "nine", de: "neun", kind: "word", emoji: "9️⃣", note: tx("Neuf also means new!", "Neuf heißt auch neu!") },
    { id: "num-10", fr: "dix", en: "ten", de: "zehn", kind: "word", emoji: "🔟", note: tx("Say «dees».", "Das x klingt wie ein scharfes s.") },
    { id: "num-11", fr: "onze", en: "eleven", de: "elf", kind: "word" },
    { id: "num-12", fr: "douze", en: "twelve", de: "zwölf", kind: "word", note: tx("Une douzaine d'œufs: a dozen eggs.", "Une douzaine d'œufs: ein Dutzend Eier.") },
    { id: "num-13", fr: "treize", en: "thirteen", de: "dreizehn", kind: "word" },
    { id: "num-14", fr: "quatorze", en: "fourteen", de: "vierzehn", kind: "word", note: tx("Don't mix it up with quatre (4)!", "Nicht mit quatre (4) verwechseln!") },
    { id: "num-15", fr: "quinze", en: "fifteen", de: "fünfzehn", kind: "word" },
    { id: "num-16", fr: "seize", en: "sixteen", de: "sechzehn", kind: "word", note: tx("Seize is 16: nothing to do with English «seize»!", "Seize ist 16, nicht 6 (six)!") },
    { id: "num-17", fr: "dix-sept", en: "seventeen", de: "siebzehn", kind: "word", note: tx("From 17 on, French adds: ten + seven.", "Ab 17 wird addiert: zehn + sieben.") },
    { id: "num-18", fr: "dix-huit", en: "eighteen", de: "achtzehn", kind: "word" },
    { id: "num-19", fr: "dix-neuf", en: "nineteen", de: "neunzehn", kind: "word" },
    { id: "num-20", fr: "vingt", en: "twenty", de: "zwanzig", kind: "word", note: tx("The g and the t are silent: «van».", "g und t sind stumm: „wän“, durch die Nase.") },
    { id: "ans", fr: "ans", en: "years", de: "Jahre", alt: { en: ["years old"], de: ["Jahre alt"] }, kind: "word", note: tx("J'ai douze ans: in French you have your age!", "J'ai douze ans: Auf Französisch hat man sein Alter!") },
    { id: "quel-age", fr: "tu as quel âge ?", en: "how old are you?", de: "wie alt bist du?", alt: { fr: ["quel âge as-tu ?"] }, kind: "phrase", note: tx("Literally «you have what age?».", "Wörtlich „du hast welches Alter?“.") },
    { id: "il-y-a", fr: "il y a", en: "there is / there are", de: "es gibt", kind: "phrase", note: tx("It never changes: il y a un chat, il y a deux chats.", "Bleibt immer gleich: il y a un chat, il y a deux chats.") },
    { id: "combien", fr: "combien", en: "how many", de: "wie viele", alt: { en: ["how much"], de: ["wie viel"] }, kind: "word", note: tx("Combien de + noun: combien de chats ?", "Combien de + Nomen: combien de chats ?") },
    { id: "anniversaire", fr: "l'anniversaire", en: "the birthday", de: "der Geburtstag", g: "m", kind: "noun", emoji: "🎈", note: tx("Bon anniversaire ! = Happy birthday!", "Bon anniversaire ! = Alles Gute zum Geburtstag!") },
    { id: "aujourd-hui", fr: "aujourd'hui", en: "today", de: "heute", kind: "adv", emoji: "📅" },
    { id: "cadeau", fr: "le cadeau", en: "the present", de: "das Geschenk", alt: { en: ["the gift"] }, g: "m", kind: "noun", emoji: "🎁", note: tx("Plural with an x: les cadeaux.", "Plural mit x: les cadeaux.") },
    { id: "zero", fr: "zéro", en: "zero", de: "null", alt: { en: ["nought", "nothing"] }, kind: "word", emoji: "0️⃣" },
    { id: "plus", fr: "plus", en: "plus", de: "plus", kind: "word", emoji: "➕", note: tx("In maths you hear the s: «plooss».", "Beim Rechnen hört man das s: „plüss“.") },
    { id: "moins", fr: "moins", en: "minus", de: "minus", alt: { en: ["take away"], de: ["weniger"] }, kind: "word", emoji: "➖", note: tx("The s is silent: «mwan».", "Das s ist stumm: „moän“.") },
    { id: "egale", fr: "égale", en: "equals", de: "gleich", alt: { en: ["is", "makes"], de: ["ist", "ergibt"] }, kind: "word", note: tx("2 + 2 = 4: deux plus deux égale quatre.", "2 + 2 = 4: deux plus deux égale quatre.") },
    { id: "bougie", fr: "la bougie", en: "the candle", de: "die Kerze", g: "f", kind: "noun", emoji: "🕯️", note: tx("On a birthday cake: one bougie for every year!", "Auf dem Geburtstagskuchen: eine bougie für jedes Jahr!") },
    { id: "bonbon", fr: "le bonbon", en: "the sweet", de: "das Bonbon", alt: { en: ["the candy"], de: ["die Süßigkeit"] }, g: "m", kind: "noun", emoji: "🍬", note: tx("Bon + bon: «good good». No wonder Blob loves them.", "Bon + bon: „gut gut“. Kein Wunder, dass Blob sie liebt.") },
  ],
  gloss: [
    { fr: "chats", en: "cats", de: "Katzen" },
    { fr: "frères", en: "brothers", de: "Brüder" },
    { fr: "sœurs", en: "sisters", de: "Schwestern" },
    { fr: "lapins", en: "rabbits", de: "Kaninchen" },
    { fr: "filles", en: "girls", de: "Mädchen" },
    { fr: "garçons", en: "boys", de: "Jungen" },
    { fr: "quel âge", en: "how old", de: "wie alt" },
    { fr: "bon anniversaire", en: "happy birthday", de: "alles Gute zum Geburtstag" },
    { fr: "alors", en: "so / then", de: "also / dann" },
    { fr: "enfin", en: "well…", de: "na ja …" },
    { fr: "cadeaux", en: "presents", de: "Geschenke" },
    { fr: "bougies", en: "candles", de: "Kerzen" },
    { fr: "bonbons", en: "sweets", de: "Bonbons" },
    { fr: "il n'y a pas", en: "there isn't / there aren't", de: "es gibt kein" },
  ],
  lessons: [
    { title: tx("One, two, three", "Eins, zwei, drei"), words: ["num-1", "num-2", "num-3", "num-4", "num-5", "num-6", "num-7"] },
    { title: tx("How old are you?", "Wie alt bist du?"), words: ["num-8", "num-9", "num-10", "num-11", "num-12", "ans", "quel-age"] },
    { title: tx("How many are there?", "Wie viele gibt es?"), words: ["num-13", "num-14", "num-15", "num-16", "il-y-a", "combien"] },
    { title: tx("Up to twenty", "Bis zwanzig"), words: ["num-17", "num-18", "num-19", "num-20", "anniversaire"] },
    { title: tx("Happy birthday!", "Alles Gute zum Geburtstag!"), words: ["aujourd-hui", "cadeau"] },
    { title: tx("Plus and minus", "Plus und minus"), words: ["zero", "plus", "moins", "egale"] },
    { title: tx("Candles and sweets", "Kerzen und Bonbons"), words: ["bougie", "bonbon"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u05.01", lesson: 1, fr: "Un, deux, trois, quatre !", en: "One, two, three, four!", de: "Eins, zwei, drei, vier!", alt: { en: ["1, 2, 3, 4!"], de: ["1, 2, 3, 4!"] } },
    { id: "u05.02", lesson: 1, fr: "J'ai deux chats.", en: "I have two cats.", de: "Ich habe zwei Katzen.", alt: { en: ["I have got two cats.", "I have 2 cats.", "I have got 2 cats."], de: ["Ich habe 2 Katzen."] } },
    { id: "u05.03", lesson: 1, fr: "Tu as trois frères ?", en: "Do you have three brothers?", de: "Hast du drei Brüder?", alt: { fr: ["As-tu trois frères ?", "Est-ce que tu as trois frères ?", "Vous avez trois frères ?", "Avez-vous trois frères ?"], en: ["Have you got three brothers?", "You have three brothers?", "Do you have 3 brothers?", "Have you got 3 brothers?", "You have 3 brothers?"], de: ["Du hast drei Brüder?", "Hast du 3 Brüder?", "Du hast 3 Brüder?"] } },
    { id: "u05.04", lesson: 1, fr: "Nous sommes cinq.", en: "There are five of us.", de: "Wir sind zu fünft.", alt: { fr: ["On est cinq."], en: ["We are five.", "There are 5 of us.", "We are 5."], de: ["Wir sind fünf.", "Wir sind 5."] } },
    { id: "u05.05", lesson: 1, fr: "Je mange six croissants !", en: "I'm eating six croissants!", de: "Ich esse sechs Croissants!", alt: { en: ["I eat six croissants!", "I am eating 6 croissants!", "I eat 6 croissants!"], de: ["Ich esse 6 Croissants!"] } },
    { id: "u05.06", lesson: 1, fr: "Elle a sept lapins !", en: "She has seven rabbits!", de: "Sie hat sieben Kaninchen!", alt: { en: ["She has got seven rabbits!", "She's got seven rabbits!", "She has 7 rabbits!", "She has got 7 rabbits!", "She's got 7 rabbits!"], de: ["Sie hat 7 Kaninchen!", "Sie hat sieben Hasen!", "Sie hat 7 Hasen!"] } },
    { id: "u05.07", lesson: 1, fr: "J'ai un frère et deux sœurs.", en: "I have one brother and two sisters.", de: "Ich habe einen Bruder und zwei Schwestern.", alt: { en: ["I have a brother and two sisters.", "I have got one brother and two sisters.", "I have got a brother and two sisters.", "I have 1 brother and 2 sisters.", "I have a brother and 2 sisters.", "I have one brother and 2 sisters."], de: ["Ich habe einen Bruder und 2 Schwestern.", "Ich habe 1 Bruder und 2 Schwestern."] } },
    // Lesson 2
    { id: "u05.08", lesson: 2, fr: "Tu as quel âge ?", en: "How old are you?", de: "Wie alt bist du?", alt: { fr: ["Quel âge as-tu ?", "Quel âge tu as ?", "Vous avez quel âge ?", "Quel âge avez-vous ?"], en: ["What age are you?"] } },
    { id: "u05.09", lesson: 2, fr: "J'ai douze ans.", en: "I am twelve.", de: "Ich bin zwölf.", alt: { en: ["I am 12.", "I am twelve years old.", "I am 12 years old."], de: ["Ich bin 12.", "Ich bin zwölf Jahre alt.", "Ich bin 12 Jahre alt."] } },
    { id: "u05.10", lesson: 2, fr: "Ma sœur a dix ans.", en: "My sister is ten.", de: "Meine Schwester ist zehn.", alt: { en: ["My sister is 10.", "My sister is ten years old.", "My sister is 10 years old."], de: ["Meine Schwester ist 10.", "Meine Schwester ist zehn Jahre alt.", "Meine Schwester ist 10 Jahre alt."] } },
    { id: "u05.11", lesson: 2, fr: "Mon chien a neuf ans.", en: "My dog is nine.", de: "Mein Hund ist neun.", alt: { en: ["My dog is 9.", "My dog is nine years old.", "My dog is 9 years old."], de: ["Mein Hund ist 9.", "Mein Hund ist neun Jahre alt.", "Mein Hund ist 9 Jahre alt."] } },
    { id: "u05.12", lesson: 2, fr: "Et ton frère, il a quel âge ?", en: "And your brother, how old is he?", de: "Und dein Bruder, wie alt ist er?", alt: { fr: ["Et ton frère a quel âge ?", "Et quel âge a ton frère ?", "Et ton frère, quel âge a-t-il ?", "Et votre frère, il a quel âge ?"], en: ["And how old is your brother?"], de: ["Und wie alt ist dein Bruder?"] } },
    { id: "u05.13", lesson: 2, fr: "Mes cousins ont huit et dix ans.", en: "My cousins are eight and ten.", de: "Meine Cousins sind acht und zehn.", alt: { fr: ["Mes cousines ont huit et dix ans."], en: ["My cousins are 8 and 10.", "My cousins are eight and ten years old.", "My cousins are 8 and 10 years old."], de: ["Meine Cousins sind 8 und 10.", "Meine Cousins sind acht und zehn Jahre alt.", "Meine Cousins sind 8 und 10 Jahre alt."] } },
    { id: "u05.14", lesson: 2, fr: "Tu as onze ou douze ans ?", en: "Are you eleven or twelve?", de: "Bist du elf oder zwölf?", alt: { fr: ["As-tu onze ou douze ans ?", "Est-ce que tu as onze ou douze ans ?", "Vous avez onze ou douze ans ?"], en: ["Are you 11 or 12?", "Are you eleven or twelve years old?", "Are you 11 or 12 years old?"], de: ["Bist du 11 oder 12?", "Bist du elf oder zwölf Jahre alt?", "Bist du 11 oder 12 Jahre alt?"] } },
    // Lesson 3
    { id: "u05.15", lesson: 3, fr: "Il y a du pain ?", en: "Is there any bread?", de: "Gibt es Brot?", alt: { fr: ["Est-ce qu'il y a du pain ?", "Y a-t-il du pain ?"], en: ["Is there bread?", "Is there some bread?"] } },
    { id: "u05.16", lesson: 3, fr: "Il y a treize croissants !", en: "There are thirteen croissants!", de: "Es gibt dreizehn Croissants!", alt: { en: ["There are 13 croissants!"], de: ["Da sind dreizehn Croissants!", "Es gibt 13 Croissants!", "Da sind 13 Croissants!"] } },
    { id: "u05.17", lesson: 3, fr: "Tu as combien de frères ?", en: "How many brothers do you have?", de: "Wie viele Brüder hast du?", alt: { fr: ["Combien de frères as-tu ?", "Combien de frères tu as ?", "Combien de frères est-ce que tu as ?", "Vous avez combien de frères ?", "Combien de frères avez-vous ?"], en: ["How many brothers have you got?"] } },
    { id: "u05.18", lesson: 3, fr: "Il y a combien de chats ?", en: "How many cats are there?", de: "Wie viele Katzen gibt es?", alt: { fr: ["Combien de chats y a-t-il ?", "Combien il y a de chats ?", "Combien de chats il y a ?", "Combien de chats est-ce qu'il y a ?"], de: ["Wie viele Katzen sind da?", "Wie viele Katzen sind es?"] } },
    { id: "u05.19", lesson: 3, fr: "Quatorze ? Non, quatre !", en: "Fourteen? No, four!", de: "Vierzehn? Nein, vier!", alt: { en: ["14? No, 4!"], de: ["14? Nein, 4!"] } },
    { id: "u05.20", lesson: 3, fr: "Ma grand-mère a seize chats.", en: "My grandmother has sixteen cats.", de: "Meine Oma hat sechzehn Katzen.", alt: { en: ["My grandma has sixteen cats.", "My granny has sixteen cats.", "My grandmother has got sixteen cats.", "My grandma has got sixteen cats.", "My grandmother has 16 cats.", "My grandma has 16 cats.", "My granny has 16 cats.", "My grandmother has got 16 cats."], de: ["Meine Großmutter hat sechzehn Katzen.", "Meine Oma hat 16 Katzen.", "Meine Großmutter hat 16 Katzen."] } },
    { id: "u05.21", lesson: 3, fr: "Il y a quinze filles et treize garçons.", en: "There are fifteen girls and thirteen boys.", de: "Es gibt fünfzehn Mädchen und dreizehn Jungen.", alt: { en: ["There are 15 girls and 13 boys."], de: ["Da sind fünfzehn Mädchen und dreizehn Jungen.", "Es gibt 15 Mädchen und 13 Jungen.", "Da sind 15 Mädchen und 13 Jungen.", "Es gibt fünfzehn Mädchen und dreizehn Jungs."] } },
    // Lesson 4
    { id: "u05.22", lesson: 4, fr: "J'ai dix-sept ans.", en: "I am seventeen.", de: "Ich bin siebzehn.", alt: { en: ["I am 17.", "I am seventeen years old.", "I am 17 years old."], de: ["Ich bin 17.", "Ich bin siebzehn Jahre alt.", "Ich bin 17 Jahre alt."] } },
    { id: "u05.23", lesson: 4, fr: "C'est mon anniversaire !", en: "It's my birthday!", de: "Ich habe Geburtstag!", alt: { de: ["Es ist mein Geburtstag!", "Das ist mein Geburtstag!"] } },
    { id: "u05.24", lesson: 4, fr: "Bon anniversaire, Léa !", en: "Happy birthday, Léa!", de: "Alles Gute zum Geburtstag, Léa!", alt: { de: ["Herzlichen Glückwunsch zum Geburtstag, Léa!"] } },
    { id: "u05.25", lesson: 4, fr: "Mon frère a dix-neuf ans.", en: "My brother is nineteen.", de: "Mein Bruder ist neunzehn.", alt: { en: ["My brother is 19.", "My brother is nineteen years old.", "My brother is 19 years old."], de: ["Mein Bruder ist 19.", "Mein Bruder ist neunzehn Jahre alt.", "Mein Bruder ist 19 Jahre alt."] } },
    { id: "u05.26", lesson: 4, fr: "Tu as vingt ans ? Moi aussi !", en: "You're twenty? Me too!", de: "Du bist zwanzig? Ich auch!", alt: { fr: ["As-tu vingt ans ? Moi aussi !", "Vous avez vingt ans ? Moi aussi !"], en: ["Are you twenty? Me too!", "You are 20? Me too!", "Are you 20? Me too!", "You are twenty? So am I!", "Are you twenty? So am I!", "You are twenty years old? Me too!", "Are you twenty years old? Me too!"], de: ["Bist du zwanzig? Ich auch!", "Du bist 20? Ich auch!", "Bist du 20? Ich auch!"] } },
    { id: "u05.27", lesson: 4, fr: "Seize, dix-sept, dix-huit, dix-neuf, vingt !", en: "Sixteen, seventeen, eighteen, nineteen, twenty!", de: "Sechzehn, siebzehn, achtzehn, neunzehn, zwanzig!", alt: { en: ["16, 17, 18, 19, 20!"], de: ["16, 17, 18, 19, 20!"] } },
    { id: "u05.28", lesson: 4, fr: "C'est l'anniversaire de ma grand-mère.", en: "It's my grandmother's birthday.", de: "Meine Oma hat Geburtstag.", alt: { en: ["It's my grandma's birthday.", "It's my granny's birthday."], de: ["Meine Großmutter hat Geburtstag.", "Es ist der Geburtstag meiner Oma.", "Es ist der Geburtstag meiner Großmutter.", "Es ist der Geburtstag von meiner Oma."] } },
    // Lesson 5
    { id: "u05.29", lesson: 5, fr: "Aujourd'hui, j'ai quatorze ans !", en: "Today I'm fourteen!", de: "Heute werde ich vierzehn!", alt: { fr: ["J'ai quatorze ans aujourd'hui !"], en: ["I am fourteen today!", "Today I am 14!", "I am 14 today!", "Today I turn fourteen!", "I turn fourteen today!", "Today I am fourteen years old!"], de: ["Heute bin ich vierzehn!", "Heute werde ich 14!", "Heute bin ich 14!", "Ich werde heute vierzehn!", "Ich bin heute vierzehn!"] } },
    { id: "u05.30", lesson: 5, fr: "C'est l'anniversaire de Léa aujourd'hui.", en: "It's Léa's birthday today.", de: "Léa hat heute Geburtstag.", alt: { fr: ["Aujourd'hui, c'est l'anniversaire de Léa."], en: ["Today is Léa's birthday.", "Today it's Léa's birthday."], de: ["Heute hat Léa Geburtstag.", "Heute ist Léas Geburtstag.", "Es ist heute Léas Geburtstag."] } },
    { id: "u05.31", lesson: 5, fr: "Aujourd'hui, il y a de la pizza !", en: "Today there's pizza!", de: "Heute gibt es Pizza!", alt: { fr: ["Il y a de la pizza aujourd'hui !"], en: ["There is pizza today!", "Today there is some pizza!", "There is some pizza today!"], de: ["Es gibt heute Pizza!"] } },
    { id: "u05.32", lesson: 5, fr: "Tu as quel âge aujourd'hui ?", en: "How old are you today?", de: "Wie alt bist du heute?", alt: { fr: ["Quel âge as-tu aujourd'hui ?", "Quel âge tu as aujourd'hui ?", "Aujourd'hui, tu as quel âge ?", "Vous avez quel âge aujourd'hui ?", "Quel âge avez-vous aujourd'hui ?"], de: ["Wie alt wirst du heute?"] } },
    { id: "u05.33", lesson: 5, fr: "Je n'ai pas quinze ans, j'ai treize ans.", en: "I'm not fifteen, I'm thirteen.", de: "Ich bin nicht fünfzehn, ich bin dreizehn.", alt: { en: ["I am not 15, I am 13.", "I am not fifteen years old, I am thirteen.", "I am not fifteen, I am thirteen years old."], de: ["Ich bin nicht 15, ich bin 13.", "Ich bin nicht fünfzehn, sondern dreizehn.", "Ich bin nicht 15, sondern 13."] } },
    { id: "u05.34", lesson: 5, fr: "Aujourd'hui, nous sommes vingt !", en: "Today there are twenty of us!", de: "Heute sind wir zwanzig Leute!", alt: { fr: ["Nous sommes vingt aujourd'hui !", "Aujourd'hui, on est vingt !", "On est vingt aujourd'hui !"], en: ["There are twenty of us today!", "Today there are 20 of us!", "There are 20 of us today!"], de: ["Heute sind wir zwanzig!", "Wir sind heute zwanzig Leute!", "Heute sind wir 20 Leute!", "Heute sind wir 20!", "Wir sind heute zu zwanzigst!"] } },
    { id: "u05.35", lesson: 5, fr: "Mon lapin a deux ans aujourd'hui !", en: "My rabbit is two today!", de: "Mein Kaninchen wird heute zwei!", alt: { fr: ["Aujourd'hui, mon lapin a deux ans !"], en: ["My rabbit is 2 today!", "My rabbit turns two today!", "My rabbit is two years old today!", "Today my rabbit is two!", "Today my rabbit turns two!"], de: ["Mein Kaninchen ist heute zwei!", "Mein Kaninchen wird heute 2!", "Mein Hase wird heute zwei!", "Heute wird mein Kaninchen zwei!", "Mein Kaninchen ist heute zwei Jahre alt!"] } },
    { id: "u05.36", lesson: 5, fr: "Merci pour le cadeau !", en: "Thank you for the present!", de: "Danke für das Geschenk!", alt: { en: ["Thanks for the present!", "Thank you for the gift!", "Thanks for the gift!"], de: ["Vielen Dank für das Geschenk!", "Danke fürs Geschenk!"] } },
    // Lesson 6
    { id: "u05.37", lesson: 6, fr: "Deux plus deux égale quatre.", en: "Two plus two equals four.", de: "Zwei plus zwei ist vier.", alt: { fr: ["Deux plus deux font quatre.", "Deux et deux font quatre.", "Deux plus deux égalent quatre.", "Deux plus deux, ça fait quatre."], en: ["Two plus two is four.", "Two and two make four.", "Two plus two makes four.", "2 plus 2 equals 4.", "2 plus 2 is 4."], de: ["Zwei plus zwei gleich vier.", "Zwei plus zwei ergibt vier.", "Zwei und zwei ist vier.", "2 plus 2 ist 4.", "2 plus 2 gleich 4."] } },
    { id: "u05.38", lesson: 6, fr: "Dix moins trois égale sept.", en: "Ten minus three equals seven.", de: "Zehn minus drei ist sieben.", alt: { fr: ["Dix moins trois font sept.", "Dix moins trois égalent sept.", "Dix moins trois, ça fait sept."], en: ["Ten minus three is seven.", "Ten take away three is seven.", "Ten take away three equals seven.", "10 minus 3 equals 7.", "10 minus 3 is 7."], de: ["Zehn minus drei gleich sieben.", "Zehn weniger drei ist sieben.", "Zehn minus drei ergibt sieben.", "10 minus 3 ist 7.", "10 minus 3 gleich 7."] } },
    { id: "u05.39", lesson: 6, fr: "Huit plus huit égale combien ?", en: "What's eight plus eight?", de: "Wie viel ist acht plus acht?", alt: { fr: ["Huit plus huit, ça fait combien ?", "Combien font huit plus huit ?", "Huit plus huit font combien ?", "Combien égale huit plus huit ?"], en: ["How much is eight plus eight?", "Eight plus eight equals what?", "What does eight plus eight make?", "What is 8 plus 8?", "How much is 8 plus 8?"], de: ["Was ist acht plus acht?", "Acht plus acht ist wie viel?", "Acht plus acht gleich wie viel?", "Wie viel ist 8 plus 8?", "Was ist 8 plus 8?"] } },
    { id: "u05.40", lesson: 6, fr: "Vingt moins vingt égale zéro.", en: "Twenty minus twenty equals zero.", de: "Zwanzig minus zwanzig ist null.", alt: { fr: ["Vingt moins vingt font zéro.", "Vingt moins vingt, ça fait zéro."], en: ["Twenty minus twenty is zero.", "Twenty take away twenty is zero.", "Twenty minus twenty is nothing.", "20 minus 20 equals 0.", "20 minus 20 is 0."], de: ["Zwanzig minus zwanzig gleich null.", "Zwanzig minus zwanzig ergibt null.", "20 minus 20 ist 0.", "20 minus 20 gleich 0."] } },
    { id: "u05.41", lesson: 6, fr: "Cinq plus cinq égale dix, pas onze !", en: "Five plus five equals ten, not eleven!", de: "Fünf plus fünf ist zehn, nicht elf!", alt: { fr: ["Cinq plus cinq égale dix, et pas onze !", "Cinq plus cinq font dix, pas onze !"], en: ["Five plus five is ten, not eleven!", "Five and five make ten, not eleven!", "5 plus 5 equals 10, not 11!", "5 plus 5 is 10, not 11!"], de: ["Fünf plus fünf gleich zehn, nicht elf!", "Fünf plus fünf ergibt zehn, nicht elf!", "Fünf und fünf ist zehn, nicht elf!", "5 plus 5 ist 10, nicht 11!"] } },
    { id: "u05.42", lesson: 6, fr: "Zéro croissant ? Blob, tu manges tout !", en: "Zero croissants? Blob, you're eating everything!", de: "Null Croissants? Blob, du isst alles!", alt: { en: ["Zero croissants? Blob, you eat everything!", "No croissants? Blob, you are eating everything!", "No croissants? Blob, you eat everything!", "No croissants left? Blob, you are eating everything!", "0 croissants? Blob, you are eating everything!"], de: ["Keine Croissants? Blob, du isst alles!", "Keine Croissants mehr? Blob, du isst alles!", "Null Croissants? Blob, du isst ja alles!", "0 Croissants? Blob, du isst alles!"] } },
    { id: "u05.43", lesson: 6, fr: "Il y a combien de garçons ? Zéro !", en: "How many boys are there? None!", de: "Wie viele Jungen gibt es? Keine!", alt: { fr: ["Combien de garçons y a-t-il ? Zéro !", "Combien il y a de garçons ? Zéro !", "Combien de garçons il y a ? Zéro !", "Il y a combien de garçons ? Aucun !"], en: ["How many boys are there? Zero!", "How many boys are there? Not one!", "How many boys are there? 0!"], de: ["Wie viele Jungen gibt es? Null!", "Wie viele Jungen sind da? Keine!", "Wie viele Jungen sind da? Null!", "Wie viele Jungs gibt es? Keine!", "Wie viele Jungen gibt es? 0!"] } },
    { id: "u05.44", lesson: 6, fr: "Quatorze moins quatre égale dix.", en: "Fourteen minus four equals ten.", de: "Vierzehn minus vier ist zehn.", alt: { fr: ["Quatorze moins quatre font dix.", "Quatorze moins quatre, ça fait dix."], en: ["Fourteen minus four is ten.", "Fourteen take away four is ten.", "14 minus 4 equals 10.", "14 minus 4 is 10."], de: ["Vierzehn minus vier gleich zehn.", "Vierzehn minus vier ergibt zehn.", "14 minus 4 ist 10.", "14 minus 4 gleich 10."] } },
    // Lesson 7
    { id: "u05.45", lesson: 7, fr: "Il y a quinze bougies !", en: "There are fifteen candles!", de: "Es gibt fünfzehn Kerzen!", alt: { en: ["There are 15 candles!"], de: ["Da sind fünfzehn Kerzen!", "Es gibt 15 Kerzen!", "Da sind 15 Kerzen!"] } },
    { id: "u05.46", lesson: 7, fr: "Il y a combien de bonbons ?", en: "How many sweets are there?", de: "Wie viele Bonbons gibt es?", alt: { fr: ["Combien de bonbons y a-t-il ?", "Combien il y a de bonbons ?", "Combien de bonbons il y a ?", "Combien de bonbons est-ce qu'il y a ?"], en: ["How many candies are there?"], de: ["Wie viele Bonbons sind da?", "Wie viele Bonbons sind es?"] } },
    { id: "u05.47", lesson: 7, fr: "Il n'y a pas de bonbons ?", en: "Aren't there any sweets?", de: "Gibt es keine Bonbons?", alt: { fr: ["Il n'y a pas de bonbon ?", "Il y a pas de bonbons ?"], en: ["Are there no sweets?", "There are no sweets?", "Are there not any sweets?", "There aren't any sweets?", "Are there no candies?", "Aren't there any candies?"], de: ["Es gibt keine Bonbons?", "Sind keine Bonbons da?"] } },
    { id: "u05.48", lesson: 7, fr: "Nous avons quinze ans, et vous ?", en: "We're fifteen, and you?", de: "Wir sind fünfzehn, und ihr?", alt: { fr: ["Nous avons quinze ans, et toi ?", "On a quinze ans, et vous ?", "On a quinze ans, et toi ?"], en: ["We are 15, and you?", "We are fifteen years old, and you?", "We are 15 years old, and you?", "We are fifteen, what about you?"], de: ["Wir sind 15, und ihr?", "Wir sind fünfzehn Jahre alt, und ihr?", "Wir sind 15 Jahre alt, und ihr?", "Wir sind fünfzehn, und Sie?"] } },
    { id: "u05.49", lesson: 7, fr: "Ils ont seize ans ? Non, quinze.", en: "Are they sixteen? No, fifteen.", de: "Sind sie sechzehn? Nein, fünfzehn.", alt: { fr: ["Elles ont seize ans ? Non, quinze.", "Ont-ils seize ans ? Non, quinze.", "Est-ce qu'ils ont seize ans ? Non, quinze.", "Ils ont seize ans ? Non, quinze ans."], en: ["Are they 16? No, 15.", "Are they sixteen years old? No, fifteen.", "Are they sixteen? No, they are fifteen.", "They are sixteen? No, fifteen."], de: ["Sind sie 16? Nein, 15.", "Sind sie sechzehn Jahre alt? Nein, fünfzehn.", "Sie sind sechzehn? Nein, fünfzehn."] } },
    { id: "u05.50", lesson: 7, fr: "Il y a dix cadeaux pour Léa !", en: "There are ten presents for Léa!", de: "Es gibt zehn Geschenke für Léa!", alt: { en: ["There are 10 presents for Léa!", "There are ten gifts for Léa!", "There are 10 gifts for Léa!"], de: ["Da sind zehn Geschenke für Léa!", "Es gibt 10 Geschenke für Léa!", "Da sind 10 Geschenke für Léa!"] } },
    { id: "u05.51", lesson: 7, fr: "Tu manges combien de bonbons ?", en: "How many sweets are you eating?", de: "Wie viele Bonbons isst du?", alt: { fr: ["Combien de bonbons tu manges ?", "Combien de bonbons manges-tu ?", "Vous mangez combien de bonbons ?", "Combien de bonbons mangez-vous ?"], en: ["How many sweets do you eat?", "How many candies are you eating?", "How many candies do you eat?"], de: ["Wie viele Süßigkeiten isst du?"] } },
    { id: "u05.52", lesson: 7, fr: "Une bougie, deux bougies, trois bougies…", en: "One candle, two candles, three candles…", de: "Eine Kerze, zwei Kerzen, drei Kerzen …", alt: { en: ["1 candle, 2 candles, 3 candles…"], de: ["1 Kerze, 2 Kerzen, 3 Kerzen …"] } },
  ],
  drills: [
    { id: "u05.d1", lesson: 1, fr: "J'ai deux ___.", options: ["chats", "chat"], answer: 0, en: "I have two cats.", de: "Ich habe zwei Katzen.", why: tx("More than one: add **-s**: deux chat**s**. You don't hear it.", "Mehr als eins: **-s** dazu: deux chat**s**. Man hört es nicht.") },
    { id: "u05.d2", lesson: 1, fr: "Nous ___ cinq.", options: ["sommes", "ont"], answer: 0, en: "There are five of us.", de: "Wir sind zu fünft.", why: tx("How many people you are: **nous sommes** cinq, with être, not avoir.", "Wie viele Leute ihr seid: **nous sommes** cinq, mit être, nicht mit avoir.") },
    { id: "u05.d3", lesson: 2, fr: "___ douze ans.", options: ["J'ai", "Je suis"], answer: 0, en: "I am twelve.", de: "Ich bin zwölf.", why: tx("In French you **have** your age: **j'ai** douze ans.", "Auf Französisch **hat** man sein Alter: **j'ai** douze ans.") },
    { id: "u05.d4", lesson: 2, fr: "Ma sœur ___ dix ans.", options: ["a", "est", "as"], answer: 0, en: "My sister is ten.", de: "Meine Schwester ist zehn.", why: tx("Age with avoir: elle **a** dix ans.", "Alter mit avoir: elle **a** dix ans.") },
    { id: "u05.d5", lesson: 2, fr: "Tu as quel ___ ?", options: ["âge", "ans"], answer: 0, en: "How old are you?", de: "Wie alt bist du?", why: tx("**Quel âge** = what age. Ans comes after a number: douze ans.", "**Quel âge** = welches Alter. Ans steht nach einer Zahl: douze ans.") },
    { id: "u05.d6", lesson: 3, fr: "Il y ___ treize croissants.", options: ["a", "sont", "est"], answer: 0, en: "There are thirteen croissants.", de: "Es gibt dreizehn Croissants.", why: tx("**Il y a** never changes, even for lots of things.", "**Il y a** bleibt immer gleich, auch bei vielen Dingen.") },
    { id: "u05.d7", lesson: 3, fr: "Tu as combien ___ frères ?", options: ["de", "des", "les"], answer: 0, en: "How many brothers do you have?", de: "Wie viele Brüder hast du?", why: tx("After combien it's just **de**: combien de frères.", "Nach combien steht nur **de**: combien de frères.") },
    { id: "u05.d8", lesson: 4, fr: "C'est ___ anniversaire !", options: ["mon", "ma"], answer: 0, en: "It's my birthday!", de: "Ich habe Geburtstag!", why: tx("Anniversaire is masculine: **mon** anniversaire.", "Anniversaire ist männlich: **mon** anniversaire.") },
    { id: "u05.d9", lesson: 4, fr: "Ils ___ vingt ans.", options: ["ont", "sont"], answer: 0, en: "They are twenty.", de: "Sie sind zwanzig.", why: tx("Age with avoir: ils **ont** vingt ans. Ils sont means «they are».", "Alter mit avoir: ils **ont** vingt ans. Ils sont heißt „sie sind“.") },
    { id: "u05.d10", lesson: 5, fr: "Aujourd'hui, Léa ___ quatorze ans.", options: ["a", "est"], answer: 0, en: "Léa is fourteen today.", de: "Léa wird heute vierzehn.", why: tx("Age with avoir: Léa **a** quatorze ans.", "Alter mit avoir: Léa **a** quatorze ans.") },
    { id: "u05.d11", lesson: 5, fr: "Je n'___ pas quinze ans.", options: ["ai", "suis"], answer: 0, en: "I'm not fifteen.", de: "Ich bin nicht fünfzehn.", why: tx("Age with avoir, also after ne: je **n'ai** pas quinze ans.", "Alter mit avoir, auch nach ne: je **n'ai** pas quinze ans.") },
    { id: "u05.d12", lesson: 6, fr: "Dix ___ trois égale sept.", options: ["moins", "plus"], answer: 0, en: "Ten minus three equals seven.", de: "Zehn minus drei ist sieben.", why: tx("10 − 3 = 7: dix **moins** trois. Plus is +.", "10 − 3 = 7: dix **moins** trois. Plus ist +.") },
    { id: "u05.d13", lesson: 6, fr: "Huit plus huit égale ___.", options: ["seize", "six", "dix-huit"], answer: 0, en: "Eight plus eight equals sixteen.", de: "Acht plus acht ist sechzehn.", why: tx("8 + 8 = 16: **seize**. Six is 6, dix-huit is 18.", "8 + 8 = 16: **seize**. Six ist 6, dix-huit ist 18.") },
    { id: "u05.d14", lesson: 6, fr: "Dix plus quatre égale ___.", options: ["quatorze", "quatre"], answer: 0, en: "Ten plus four equals fourteen.", de: "Zehn plus vier ist vierzehn.", why: tx("10 + 4 = 14: **quatorze**. Quatre is just 4.", "10 + 4 = 14: **quatorze**. Quatre ist nur 4.") },
    { id: "u05.d15", lesson: 7, fr: "Il y a dix ___ pour Léa !", options: ["cadeaux", "cadeaus", "cadeau"], answer: 0, en: "There are ten presents for Léa!", de: "Es gibt zehn Geschenke für Léa!", why: tx("Nouns in -eau take an **x** in the plural: cadeau**x**. You don't hear it.", "Nomen auf -eau bekommen im Plural ein **x**: cadeau**x**. Man hört es nicht.") },
    { id: "u05.d16", lesson: 7, fr: "Il ___y a pas de bonbons ?", options: ["n'", "ne "], answer: 0, en: "Aren't there any sweets?", de: "Gibt es keine Bonbons?", why: tx("Before y, ne shrinks to **n'**: il **n'y a pas** de bonbons.", "Vor y wird ne zu **n'**: il **n'y a pas** de bonbons.") },
    { id: "u05.d17", lesson: 7, fr: "Nous ___ quinze ans.", options: ["avons", "sommes", "êtes"], answer: 0, en: "We're fifteen.", de: "Wir sind fünfzehn.", why: tx("Age with avoir: **nous avons** quinze ans.", "Alter mit avoir: **nous avons** quinze ans.") },
  ],
  dialogues: [
    {
      id: "u05.dialogue",
      lesson: 5,
      title: tx("Léa's birthday", "Léas Geburtstag"),
      lines: [
        { who: "hugo", fr: "Bon anniversaire, Léa ! Tu as quel âge aujourd'hui ?", en: "Happy birthday, Léa! How old are you today?", de: "Alles Gute zum Geburtstag, Léa! Wie alt wirst du heute?" },
        { who: "lea", fr: "Merci ! J'ai quatorze ans.", en: "Thanks! I'm fourteen.", de: "Danke! Ich werde vierzehn." },
        { who: "blob", fr: "Quatorze ? Alors il y a quatorze croissants pour toi !", en: "Fourteen? Then there are fourteen croissants for you!", de: "Vierzehn? Dann gibt es vierzehn Croissants für dich!" },
        { who: "lea", fr: "Merci, Blob ! Un, deux, trois… treize croissants ?", en: "Thanks, Blob! One, two, three… thirteen croissants?", de: "Danke, Blob! Eins, zwei, drei … dreizehn Croissants?" },
        { who: "hugo", fr: "Treize ? Blob, tu manges un croissant ?", en: "Thirteen? Blob, are you eating a croissant?", de: "Dreizehn? Blob, isst du etwa ein Croissant?" },
        { who: "blob", fr: "Non ! Enfin… oui, un petit croissant.", en: "No! Well… yes, a little croissant.", de: "Nein! Na ja … doch, ein kleines Croissant." },
        { who: "lea", fr: "Ce n'est pas grave, Blob. Et toi, tu as quel âge ?", en: "Never mind, Blob. And how old are you?", de: "Macht nichts, Blob. Und wie alt bist du?" },
        { who: "blob", fr: "Moi ? J'ai deux ans… et un béret !", en: "Me? I'm two… and I've got a beret!", de: "Ich? Ich bin zwei … und habe eine Baskenmütze!" },
      ],
      questions: [
        { q: tx("How old is Léa today?", "Wie alt wird Léa heute?"), options: ["14", "13", "2"], answer: 0 },
        { q: tx("Who ate a croissant?", "Wer hat ein Croissant gegessen?"), options: ["Blob", "Hugo", "Léa"], answer: 0 },
        { q: tx("How old is Blob?", "Wie alt ist Blob?"), options: ["2", "14", "20"], answer: 0 },
      ],
    },
    {
      id: "u05.dialogue2",
      lesson: 7,
      title: tx("Hugo's birthday", "Hugos Geburtstag"),
      lines: [
        { who: "hugo", fr: "Aujourd'hui, j'ai quinze ans !", en: "I'm fifteen today!", de: "Heute werde ich fünfzehn!" },
        { who: "blob", fr: "Bon anniversaire, Hugo ! Il y a un cadeau pour toi.", en: "Happy birthday, Hugo! There's a present for you.", de: "Alles Gute zum Geburtstag, Hugo! Hier ist ein Geschenk für dich." },
        { who: "hugo", fr: "Merci, Blob ! C'est quoi ?", en: "Thanks, Blob! What is it?", de: "Danke, Blob! Was ist das?" },
        { who: "blob", fr: "Ce sont des bougies : quinze bougies !", en: "They're candles: fifteen candles!", de: "Das sind Kerzen: fünfzehn Kerzen!" },
        { who: "lea", fr: "Un, deux, trois… Blob, il y a combien de bougies ?", en: "One, two, three… Blob, how many candles are there?", de: "Eins, zwei, drei … Blob, wie viele Kerzen sind das?" },
        { who: "blob", fr: "Quatorze bougies… plus un Blob égale quinze !", en: "Fourteen candles… plus one Blob equals fifteen!", de: "Vierzehn Kerzen … plus ein Blob ist fünfzehn!" },
        { who: "hugo", fr: "Blob, tu n'es pas une bougie !", en: "Blob, you're not a candle!", de: "Blob, du bist doch keine Kerze!" },
        { who: "lea", fr: "Et les bonbons, Blob ? Il y a combien de bonbons ?", en: "And the sweets, Blob? How many sweets are there?", de: "Und die Bonbons, Blob? Wie viele Bonbons gibt es?" },
        { who: "blob", fr: "Zéro… Ils sont délicieux. Pardon, Hugo !", en: "Zero… They're delicious. Sorry, Hugo!", de: "Null … Sie sind köstlich. Entschuldigung, Hugo!" },
      ],
      questions: [
        { q: tx("How old is Hugo today?", "Wie alt wird Hugo heute?"), options: ["15", "14", "2"], answer: 0 },
        { q: tx("What is Blob's present?", "Was ist Blobs Geschenk?"), options: [tx("Candles", "Kerzen"), tx("Sweets", "Bonbons"), tx("A croissant", "Ein Croissant")], answer: 0 },
        { q: tx("Where are the sweets?", "Wo sind die Bonbons?"), options: [tx("Blob ate them.", "Blob hat sie gegessen."), tx("In the present", "Im Geschenk"), tx("At Léa's", "Bei Léa")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Counting to twenty", "Bis zwanzig zählen"),
      body: tx(
        "Learn 1 to 16 by heart. From 17 on, French simply adds: **dix-sept** = ten-seven, **dix-huit**, **dix-neuf**. Then **vingt** (20): the g and the t are silent.\n\n**Un** becomes **une** before a feminine word: une pomme, un croissant.",
        "1 bis 16 lernst du auswendig. Ab 17 wird einfach addiert: **dix-sept** = zehn-sieben, **dix-huit**, **dix-neuf**. Dann **vingt** (20): g und t sind stumm.\n\n**Un** wird vor weiblichen Wörtern zu **une**: une pomme, un croissant.",
      ),
      examples: [
        { fr: "Un, deux, trois, quatre !", en: "One, two, three, four!", de: "Eins, zwei, drei, vier!" },
        { fr: "Il y a treize croissants !", en: "There are thirteen croissants!", de: "Es gibt dreizehn Croissants!" },
        { fr: "Seize, dix-sept, dix-huit, dix-neuf, vingt !", en: "Sixteen, seventeen, eighteen, nineteen, twenty!", de: "Sechzehn, siebzehn, achtzehn, neunzehn, zwanzig!" },
      ],
      table: {
        head: [tx("number", "Zahl"), tx("French", "Französisch"), tx("number", "Zahl"), tx("French", "Französisch")],
        rows: [
          ["1", "un", "11", "onze"],
          ["2", "deux", "12", "douze"],
          ["3", "trois", "13", "treize"],
          ["4", "quatre", "14", "quatorze"],
          ["5", "cinq", "15", "quinze"],
          ["6", "six", "16", "seize"],
          ["7", "sept", "17", "dix-sept"],
          ["8", "huit", "18", "dix-huit"],
          ["9", "neuf", "19", "dix-neuf"],
          ["10", "dix", "20", "vingt"],
        ],
      },
    },
    {
      title: tx("Your age: j'ai douze ans", "Dein Alter: j'ai douze ans"),
      body: tx(
        "In French you **have** your age: **j'ai douze ans**, literally «I have twelve years». Never say je suis douze, and don't forget **ans**.\n\nTo ask: **tu as quel âge ?** Politely: vous avez quel âge ?",
        "Auf Französisch **hat** man sein Alter: **j'ai douze ans**, wörtlich „ich habe zwölf Jahre“. Sag nie je suis douze, und vergiss **ans** nicht.\n\nSo fragst du: **tu as quel âge ?** Höflich: vous avez quel âge ?",
      ),
      examples: [
        { fr: "Tu as quel âge ?", en: "How old are you?", de: "Wie alt bist du?" },
        { fr: "J'ai douze ans.", en: "I'm twelve.", de: "Ich bin zwölf." },
        { fr: "Mon chien a neuf ans.", en: "My dog is nine.", de: "Mein Hund ist neun." },
      ],
      table: {
        head: [tx("person", "Person"), tx("age with avoir", "Alter mit avoir")],
        rows: [
          [tx("I", "ich"), "j'ai douze ans"],
          [tx("you", "du"), "tu as quinze ans"],
          [tx("he / she", "er / sie"), "il / elle a dix ans"],
          [tx("we", "wir"), "nous avons treize ans"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous avez vingt ans"],
          [tx("they", "sie"), "ils / elles ont huit ans"],
        ],
      },
    },
    {
      title: tx("Il y a and combien", "Il y a und combien"),
      body: tx(
        "**Il y a** means there is or there are, and it never changes: il y a **un** chat, il y a **treize** croissants. With a question mark it asks: il y a du pain ?\n\n**Combien de** + noun asks how many: **combien de** frères ? Before a vowel: combien **d'**amis ?",
        "**Il y a** heißt es gibt (oder da ist, da sind), und es ändert sich nie: il y a **un** chat, il y a **treize** croissants. Mit Fragezeichen fragt es: il y a du pain ?\n\n**Combien de** + Nomen fragt nach wie viele: **combien de** frères ? Vor einem Vokal: combien **d'**amis ?",
      ),
      examples: [
        { fr: "Il y a du pain ?", en: "Is there any bread?", de: "Gibt es Brot?" },
        { fr: "Il y a combien de chats ?", en: "How many cats are there?", de: "Wie viele Katzen gibt es?" },
        { fr: "Tu as combien de frères ?", en: "How many brothers do you have?", de: "Wie viele Brüder hast du?" },
      ],
    },
    {
      title: tx("Plus, moins, égale", "Plus, moins, égale"),
      body: tx(
        "Maths in French: **plus** (+), **moins** (−) and **égale** (=): deux plus deux égale quatre. Nothing at all is **zéro**.\n\nTo say there isn't any: **il n'y a pas de** + noun: il n'y a pas de bonbons.\n\nMost nouns add a silent **-s** in the plural (des bougie**s**), but nouns in -eau add an **x**: un cadeau, des cadeau**x**.",
        "Rechnen auf Französisch: **plus** (+), **moins** (−) und **égale** (=): deux plus deux égale quatre. Gar nichts ist **zéro**.\n\nEs gibt kein …: **il n'y a pas de** + Nomen: il n'y a pas de bonbons.\n\nDie meisten Nomen bekommen im Plural ein stummes **-s** (des bougie**s**), Nomen auf -eau aber ein **x**: un cadeau, des cadeau**x**.",
      ),
      examples: [
        { fr: "Deux plus deux égale quatre.", en: "Two plus two equals four.", de: "Zwei plus zwei ist vier." },
        { fr: "Dix moins trois égale sept.", en: "Ten minus three equals seven.", de: "Zehn minus drei ist sieben." },
        { fr: "Il n'y a pas de bonbons ?", en: "Aren't there any sweets?", de: "Gibt es keine Bonbons?" },
        { fr: "Il y a dix cadeaux pour Léa !", en: "There are ten presents for Léa!", de: "Es gibt zehn Geschenke für Léa!" },
      ],
      table: {
        head: [tx("sign", "Zeichen"), tx("French", "Französisch"), tx("example", "Beispiel")],
        rows: [
          ["+", "plus", "deux plus deux"],
          ["−", "moins", "dix moins trois"],
          ["=", "égale", "… égale sept"],
          ["0", "zéro", "vingt moins vingt égale zéro"],
        ],
      },
    },
  ],
};
