import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 6: school things, -er verbs (parler, écouter, regarder, travailler) and est-ce que. */
export const u06: Unit = {
  slug: "ecole",
  n: 6,
  cefr: "A1",
  title: tx("At school", "In der Schule"),
  goal: tx("Talk about school and what you do there, and ask yes/no questions", "Über die Schule sprechen, was du dort machst, und Ja/Nein-Fragen stellen"),
  emoji: "🎒",
  words: [
    { id: "ecole", fr: "l'école", en: "the school", de: "die Schule", g: "f", kind: "noun", emoji: "🏫", note: tx("Le and la shrink to l' before a vowel: l'école.", "Le und la werden vor einem Vokal zu l': l'école.") },
    { id: "classe", fr: "la classe", en: "the class", de: "die Klasse", alt: { en: ["the classroom"], de: ["das Klassenzimmer"] }, g: "f", kind: "noun", note: tx("Your class and the classroom. En classe: in class.", "Deine Klasse und das Klassenzimmer. En classe: im Unterricht.") },
    { id: "sac", fr: "le sac", en: "the bag", de: "die Tasche", alt: { en: ["the schoolbag", "the backpack"], de: ["der Rucksack", "die Schultasche"] }, g: "m", kind: "noun", emoji: "🎒" },
    { id: "livre", fr: "le livre", en: "the book", de: "das Buch", g: "m", kind: "noun", emoji: "📖" },
    { id: "stylo", fr: "le stylo", en: "the pen", de: "der Stift", alt: { de: ["der Kugelschreiber", "der Kuli"] }, g: "m", kind: "noun", emoji: "🖊️" },
    { id: "cahier", fr: "le cahier", en: "the exercise book", de: "das Heft", alt: { en: ["the notebook"], de: ["das Schulheft"] }, g: "m", kind: "noun", emoji: "📓" },
    { id: "je-parle", fr: "je parle", en: "I speak", de: "ich spreche", alt: { en: ["I talk"], de: ["ich rede"] }, kind: "verb", emoji: "🗣️", note: tx("From parler, to speak. Most French verbs end in -er and work just like it.", "Von parler, sprechen. Die meisten französischen Verben enden auf -er und funktionieren genauso.") },
    { id: "tu-parles", fr: "tu parles", en: "you speak", de: "du sprichst", alt: { en: ["you talk"], de: ["du redest"] }, kind: "verb", note: tx("The s is silent: tu parles sounds just like je parle.", "Das s ist stumm: tu parles klingt genau wie je parle.") },
    { id: "il-parle", fr: "il parle", en: "he speaks", de: "er spricht", alt: { en: ["he talks"], de: ["er redet"] }, kind: "verb", note: tx("Elle parle: she speaks. Léa parle, Hugo parle: the same form.", "Elle parle: sie spricht. Léa parle, Hugo parle: dieselbe Form.") },
    { id: "professeur", fr: "le professeur", en: "the teacher", de: "der Lehrer", g: "m", kind: "noun", emoji: "🧑‍🏫", note: tx("Short and everyday: le prof, la prof. A woman teacher is often la professeure.", "Kurz und alltäglich: le prof, la prof. Eine Lehrerin heißt oft la professeure.") },
    { id: "eleve", fr: "l'élève", en: "the pupil", de: "der Schüler", alt: { en: ["the student"], de: ["die Schülerin"] }, g: "m", kind: "noun", emoji: "🧑‍🎓", note: tx("One word for boys and girls: un élève, une élève.", "Ein Wort für Jungen und Mädchen: un élève (Schüler), une élève (Schülerin).") },
    { id: "nous-parlons", fr: "nous parlons", en: "we speak", de: "wir sprechen", alt: { en: ["we talk"], de: ["wir reden"] }, kind: "verb", note: tx("With nous, -er verbs end in -ons: nous parlons, nous écoutons. (Être is the odd one out: nous sommes.)", "Mit nous enden -er-Verben auf -ons: nous parlons, nous écoutons. (Être tanzt aus der Reihe: nous sommes.)") },
    { id: "vous-parlez", fr: "vous parlez", en: "you speak (plural / polite)", de: "ihr sprecht / Sie sprechen", kind: "verb", note: tx("Vous is for several people, or one person you call Monsieur or Madame. With -er verbs it ends in -ez.", "Vous ist für mehrere Leute oder für eine Person, die du siezt. Bei -er-Verben endet es auf -ez.") },
    { id: "est-ce-que", fr: "est-ce que", en: "(starts a yes/no question)", de: "(leitet eine Ja/Nein-Frage ein)", kind: "phrase", note: tx("Literally «is it that». Put it in front of a sentence and it's a question. Before a vowel: est-ce qu'il…", "Wörtlich „ist es, dass“. Vor einen Satz gestellt, wird er zur Frage. Vor einem Vokal: est-ce qu'il …") },
    { id: "question", fr: "la question", en: "the question", de: "die Frage", g: "f", kind: "noun", emoji: "🙋" },
    { id: "j-ecoute", fr: "j'écoute", en: "I listen", de: "ich höre zu", alt: { en: ["I am listening"] }, kind: "verb", emoji: "👂", note: tx("No «to» in French: j'écoute le professeur, I listen to the teacher.", "Ein Wort, ohne „zu“: j'écoute le professeur, ich höre dem Lehrer zu.") },
    { id: "je-regarde", fr: "je regarde", en: "I look at", de: "ich schaue … an", alt: { en: ["I watch"], de: ["ich sehe … an"] }, kind: "verb", emoji: "👀", note: tx("No «at» in French: je regarde le tableau, I'm looking at the board.", "Ein Wort, ohne „an“: je regarde le livre, ich schaue das Buch an.") },
    { id: "je-travaille", fr: "je travaille", en: "I work", de: "ich arbeite", alt: { en: ["I study"], de: ["ich lerne"] }, kind: "verb", note: tx("At school, travailler is also to study: je travaille bien.", "In der Schule heißt travailler auch lernen: je travaille bien.") },
    { id: "devoirs", fr: "les devoirs", en: "the homework", de: "die Hausaufgaben", g: "m", kind: "noun", emoji: "📝", note: tx("Always plural in French: les devoirs sont difficiles.", "Immer Plural, wie im Deutschen: les devoirs sont difficiles.") },
    { id: "tableau", fr: "le tableau", en: "the board", de: "die Tafel", alt: { en: ["the blackboard", "the whiteboard"] }, g: "m", kind: "noun", note: tx("Le tableau is also a painting.", "Le tableau ist auch ein Gemälde.") },
    { id: "facile", fr: "facile", en: "easy", de: "leicht", alt: { de: ["einfach"] }, kind: "adj", note: tx("Facile and difficile end in -e: the same for boys and girls.", "Facile und difficile enden auf -e: gleich für männlich und weiblich.") },
    { id: "difficile", fr: "difficile", en: "difficult", de: "schwer", alt: { en: ["hard"], de: ["schwierig"] }, kind: "adj" },
    { id: "reponse", fr: "la réponse", en: "the answer", de: "die Antwort", g: "f", kind: "noun", emoji: "💡" },
  ],
  gloss: [
    { fr: "parle", en: "speak / speaks", de: "spreche / spricht" },
    { fr: "parles", en: "speak (you)", de: "sprichst" },
    { fr: "parlons", en: "speak (we)", de: "sprechen (wir)" },
    { fr: "parlez", en: "speak (you, plural / polite)", de: "sprecht / sprechen (Sie)" },
    { fr: "parlent", en: "speak (they)", de: "sprechen (sie)" },
    { fr: "écoute", en: "listen / listens", de: "höre zu / hört zu" },
    { fr: "écoutes", en: "listen (you)", de: "hörst zu" },
    { fr: "écoutent", en: "listen (they)", de: "hören zu (sie)" },
    { fr: "regarde", en: "look (at) / looks (at)", de: "schaue / schaut (an)" },
    { fr: "regardes", en: "look at (you)", de: "schaust an" },
    { fr: "travaille", en: "work / works", de: "arbeite / arbeitet" },
    { fr: "travaillons", en: "work (we)", de: "arbeiten (wir)" },
    { fr: "travaillent", en: "work (they)", de: "arbeiten (sie)" },
    { fr: "est-ce qu'il", en: "(question) he", de: "(Frage) er" },
    { fr: "est-ce qu'elle", en: "(question) she", de: "(Frage) sie" },
    { fr: "grande", en: "big (feminine)", de: "groß (weiblich)" },
    { fr: "petite", en: "small (feminine)", de: "klein (weiblich)" },
    { fr: "difficiles", en: "difficult (plural)", de: "schwer (Plural)" },
    { fr: "élèves", en: "pupils", de: "Schüler" },
    { fr: "beaucoup", en: "a lot", de: "viel" },
    { fr: "aujourd'hui", en: "today", de: "heute" },
    { fr: "bonne", en: "good / right (feminine)", de: "gut / richtig" },
    { fr: "maintenant", en: "now", de: "jetzt" },
    { fr: "euh", en: "er / um", de: "äh" },
  ],
  lessons: [
    { title: tx("My school bag", "Meine Schultasche"), words: ["ecole", "classe", "sac", "livre", "stylo", "cahier"] },
    { title: tx("I speak French", "Ich spreche Französisch"), words: ["je-parle", "tu-parles", "il-parle", "professeur", "eleve"] },
    { title: tx("Questions, questions", "Fragen über Fragen"), words: ["nous-parlons", "vous-parlez", "est-ce-que", "question"] },
    { title: tx("Listen and look", "Zuhören und hinschauen"), words: ["j-ecoute", "je-regarde", "je-travaille", "devoirs", "tableau"] },
    { title: tx("Easy or difficult?", "Leicht oder schwer?"), words: ["facile", "difficile", "reponse"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u06.01", lesson: 1, fr: "C'est mon livre.", en: "It's my book.", de: "Das ist mein Buch.", alt: { en: ["This is my book.", "That's my book."], de: ["Es ist mein Buch."] } },
    { id: "u06.02", lesson: 1, fr: "J'ai un stylo et un cahier.", en: "I have a pen and an exercise book.", de: "Ich habe einen Stift und ein Heft.", alt: { en: ["I have a pen and a notebook.", "I have got a pen and an exercise book.", "I have got a pen and a notebook."], de: ["Ich habe einen Kugelschreiber und ein Heft.", "Ich habe einen Kuli und ein Heft."] } },
    { id: "u06.03", lesson: 1, fr: "Le livre est dans le sac.", en: "The book is in the bag.", de: "Das Buch ist in der Tasche.", alt: { en: ["The book is in the schoolbag.", "The book is in the backpack."], de: ["Das Buch ist im Rucksack.", "Das Buch ist in der Schultasche."] } },
    { id: "u06.04", lesson: 1, fr: "L'école est grande.", en: "The school is big.", de: "Die Schule ist groß.", alt: { en: ["The school is large."] } },
    { id: "u06.05", lesson: 1, fr: "Il y a un stylo dans le sac.", en: "There's a pen in the bag.", de: "In der Tasche ist ein Stift.", alt: { en: ["There is a pen in the schoolbag.", "There is a pen in the backpack."], de: ["Es gibt einen Stift in der Tasche.", "In der Tasche liegt ein Stift.", "Da ist ein Stift in der Tasche.", "Im Rucksack ist ein Stift.", "In der Tasche ist ein Kuli."] } },
    { id: "u06.06", lesson: 1, fr: "C'est la classe de Léa.", en: "This is Léa's class.", de: "Das ist Léas Klasse.", alt: { en: ["It's Léa's class.", "That's Léa's class.", "This is Léa's classroom.", "It's Léa's classroom.", "That's Léa's classroom."], de: ["Das ist die Klasse von Léa.", "Das ist Léas Klassenzimmer.", "Das ist das Klassenzimmer von Léa."] } },
    { id: "u06.07", lesson: 1, fr: "Tu as un stylo ?", en: "Do you have a pen?", de: "Hast du einen Stift?", alt: { fr: ["Est-ce que tu as un stylo ?", "As-tu un stylo ?", "Vous avez un stylo ?", "Est-ce que vous avez un stylo ?", "Avez-vous un stylo ?"], en: ["Have you got a pen?", "You have a pen?"], de: ["Hast du einen Kuli?", "Hast du einen Kugelschreiber?", "Du hast einen Stift?"] } },
    // Lesson 2
    { id: "u06.08", lesson: 2, fr: "Je parle français.", en: "I speak French.", de: "Ich spreche Französisch.", alt: { en: ["I am speaking French."] } },
    { id: "u06.09", lesson: 2, fr: "Tu parles anglais ?", en: "Do you speak English?", de: "Sprichst du Englisch?", alt: { fr: ["Est-ce que tu parles anglais ?", "Parles-tu anglais ?", "Vous parlez anglais ?", "Est-ce que vous parlez anglais ?", "Parlez-vous anglais ?"], en: ["You speak English?", "Are you speaking English?"], de: ["Du sprichst Englisch?"] } },
    { id: "u06.10", lesson: 2, fr: "Le professeur parle allemand.", en: "The teacher speaks German.", de: "Der Lehrer spricht Deutsch.", alt: { en: ["The teacher is speaking German."] } },
    { id: "u06.11", lesson: 2, fr: "Léa parle très bien anglais.", en: "Léa speaks English very well.", de: "Léa spricht sehr gut Englisch.", alt: { fr: ["Léa parle très bien l'anglais.", "Léa parle anglais très bien."], en: ["Léa speaks very good English."], de: ["Léa spricht Englisch sehr gut."] } },
    { id: "u06.12", lesson: 2, fr: "L'élève ne parle pas.", en: "The pupil isn't talking.", de: "Der Schüler spricht nicht.", alt: { en: ["The pupil is not speaking.", "The pupil does not talk.", "The pupil does not speak.", "The student is not talking.", "The student is not speaking.", "The student does not talk.", "The student does not speak."], de: ["Die Schülerin spricht nicht.", "Der Schüler redet nicht.", "Die Schülerin redet nicht."] } },
    { id: "u06.13", lesson: 2, fr: "Il parle avec le professeur.", en: "He's talking to the teacher.", de: "Er spricht mit dem Lehrer.", alt: { fr: ["Il parle au professeur."], en: ["He is talking with the teacher.", "He is speaking to the teacher.", "He is speaking with the teacher.", "He talks to the teacher.", "He talks with the teacher.", "He speaks to the teacher.", "He speaks with the teacher."], de: ["Er redet mit dem Lehrer."] } },
    { id: "u06.14", lesson: 2, fr: "Elle parle anglais et français.", en: "She speaks English and French.", de: "Sie spricht Englisch und Französisch.", alt: { fr: ["Elle parle français et anglais."], en: ["She is speaking English and French."] } },
    // Lesson 3
    { id: "u06.15", lesson: 3, fr: "Nous parlons français en classe.", en: "We speak French in class.", de: "Wir sprechen im Unterricht Französisch.", alt: { fr: ["En classe, nous parlons français."], en: ["We are speaking French in class.", "In class we speak French.", "We speak French in the classroom."], de: ["Wir sprechen Französisch im Unterricht.", "Im Unterricht sprechen wir Französisch.", "Wir sprechen in der Klasse Französisch.", "In der Klasse sprechen wir Französisch.", "Wir sprechen Französisch in der Klasse."] } },
    { id: "u06.16", lesson: 3, fr: "Vous parlez anglais, Monsieur Martin ?", en: "Do you speak English, Mr Martin?", de: "Sprechen Sie Englisch, Herr Martin?", alt: { fr: ["Est-ce que vous parlez anglais, Monsieur Martin ?", "Parlez-vous anglais, Monsieur Martin ?", "Monsieur Martin, vous parlez anglais ?", "Monsieur Martin, est-ce que vous parlez anglais ?", "Monsieur Martin, parlez-vous anglais ?"], en: ["Mr Martin, do you speak English?", "You speak English, Mr Martin?"], de: ["Herr Martin, sprechen Sie Englisch?"] } },
    { id: "u06.17", lesson: 3, fr: "Est-ce que tu parles allemand ?", en: "Do you speak German?", de: "Sprichst du Deutsch?", alt: { fr: ["Tu parles allemand ?", "Parles-tu allemand ?", "Est-ce que vous parlez allemand ?", "Vous parlez allemand ?", "Parlez-vous allemand ?"], en: ["Are you speaking German?", "You speak German?"], de: ["Du sprichst Deutsch?"] } },
    { id: "u06.18", lesson: 3, fr: "Est-ce que vous êtes le professeur ?", en: "Are you the teacher?", de: "Sind Sie der Lehrer?", alt: { fr: ["Vous êtes le professeur ?", "Êtes-vous le professeur ?", "Est-ce que tu es le professeur ?", "Tu es le professeur ?", "Es-tu le professeur ?"], en: ["You are the teacher?"], de: ["Sind Sie die Lehrerin?"] } },
    { id: "u06.19", lesson: 3, fr: "J'ai une question.", en: "I have a question.", de: "Ich habe eine Frage.", alt: { en: ["I have got a question."] } },
    { id: "u06.20", lesson: 3, fr: "Est-ce qu'il parle français ?", en: "Does he speak French?", de: "Spricht er Französisch?", alt: { fr: ["Il parle français ?", "Parle-t-il français ?"], en: ["Is he speaking French?"] } },
    { id: "u06.21", lesson: 3, fr: "Nous ne parlons pas allemand.", en: "We don't speak German.", de: "Wir sprechen kein Deutsch.", alt: { en: ["We are not speaking German."], de: ["Wir sprechen nicht Deutsch."] } },
    // Lesson 4
    { id: "u06.22", lesson: 4, fr: "J'écoute le professeur.", en: "I'm listening to the teacher.", de: "Ich höre dem Lehrer zu.", alt: { en: ["I listen to the teacher."] } },
    { id: "u06.23", lesson: 4, fr: "Je regarde le tableau.", en: "I'm looking at the board.", de: "Ich schaue an die Tafel.", alt: { en: ["I look at the board.", "I am looking at the blackboard.", "I am looking at the whiteboard.", "I look at the blackboard.", "I look at the whiteboard."], de: ["Ich schaue zur Tafel.", "Ich schaue auf die Tafel.", "Ich schaue die Tafel an.", "Ich sehe an die Tafel.", "Ich sehe zur Tafel.", "Ich sehe auf die Tafel.", "Ich sehe die Tafel an.", "Ich gucke an die Tafel."] } },
    { id: "u06.24", lesson: 4, fr: "Les élèves travaillent.", en: "The pupils are working.", de: "Die Schüler arbeiten.", alt: { en: ["The pupils work.", "The students are working.", "The students work."], de: ["Die Schülerinnen arbeiten.", "Die Schülerinnen und Schüler arbeiten.", "Die Schüler lernen."] } },
    { id: "u06.25", lesson: 4, fr: "Je travaille avec Hugo.", en: "I'm working with Hugo.", de: "Ich arbeite mit Hugo.", alt: { en: ["I work with Hugo.", "I am studying with Hugo.", "I study with Hugo."], de: ["Ich lerne mit Hugo."] } },
    { id: "u06.26", lesson: 4, fr: "Tu écoutes ?", en: "Are you listening?", de: "Hörst du zu?", alt: { fr: ["Est-ce que tu écoutes ?", "Écoutes-tu ?", "Vous écoutez ?", "Est-ce que vous écoutez ?", "Écoutez-vous ?"], en: ["You are listening?", "Do you listen?"], de: ["Du hörst zu?"] } },
    { id: "u06.27", lesson: 4, fr: "Blob regarde les devoirs de Léa.", en: "Blob is looking at Léa's homework.", de: "Blob schaut sich Léas Hausaufgaben an.", alt: { en: ["Blob looks at Léa's homework."], de: ["Blob sieht sich Léas Hausaufgaben an.", "Blob schaut Léas Hausaufgaben an.", "Blob sieht Léas Hausaufgaben an.", "Blob schaut sich die Hausaufgaben von Léa an.", "Blob sieht sich die Hausaufgaben von Léa an.", "Blob schaut die Hausaufgaben von Léa an."] } },
    { id: "u06.28", lesson: 4, fr: "Les élèves écoutent le professeur.", en: "The pupils are listening to the teacher.", de: "Die Schüler hören dem Lehrer zu.", alt: { en: ["The pupils listen to the teacher.", "The students are listening to the teacher.", "The students listen to the teacher."], de: ["Die Schülerinnen hören dem Lehrer zu.", "Die Schülerinnen und Schüler hören dem Lehrer zu."] } },
    // Lesson 5
    { id: "u06.29", lesson: 5, fr: "Les devoirs sont difficiles.", en: "The homework is difficult.", de: "Die Hausaufgaben sind schwer.", alt: { en: ["The homework is hard."], de: ["Die Hausaufgaben sind schwierig."] } },
    { id: "u06.30", lesson: 5, fr: "C'est facile !", en: "It's easy!", de: "Das ist leicht!", alt: { en: ["That's easy!", "This is easy!"], de: ["Das ist einfach!", "Es ist leicht!", "Es ist einfach!"] } },
    { id: "u06.31", lesson: 5, fr: "Est-ce que c'est difficile ?", en: "Is it difficult?", de: "Ist das schwer?", alt: { fr: ["C'est difficile ?"], en: ["Is it hard?", "Is that difficult?", "Is that hard?", "Is this difficult?", "Is this hard?"], de: ["Ist es schwer?", "Ist das schwierig?", "Ist es schwierig?"] } },
    { id: "u06.32", lesson: 5, fr: "Je ne travaille pas aujourd'hui.", en: "I'm not working today.", de: "Ich arbeite heute nicht.", alt: { fr: ["Aujourd'hui, je ne travaille pas."], en: ["I don't work today.", "Today I am not working.", "I am not studying today."], de: ["Heute arbeite ich nicht.", "Ich lerne heute nicht.", "Heute lerne ich nicht."] } },
    { id: "u06.33", lesson: 5, fr: "Aujourd'hui, nous travaillons beaucoup.", en: "Today we're working a lot.", de: "Heute arbeiten wir viel.", alt: { fr: ["Nous travaillons beaucoup aujourd'hui."], en: ["We are working a lot today.", "Today we work a lot.", "We work a lot today.", "Today we are working hard.", "We are working hard today."], de: ["Wir arbeiten heute viel.", "Heute lernen wir viel.", "Wir lernen heute viel."] } },
    { id: "u06.34", lesson: 5, fr: "Le professeur est sympa.", en: "The teacher is nice.", de: "Der Lehrer ist nett.", alt: { en: ["The teacher is friendly."], de: ["Der Lehrer ist sympathisch."] } },
    { id: "u06.35", lesson: 5, fr: "C'est la bonne réponse !", en: "That's the right answer!", de: "Das ist die richtige Antwort!", alt: { en: ["It's the right answer!", "This is the right answer!", "That's the correct answer!", "It's the correct answer!", "This is the correct answer!"] } },
  ],
  drills: [
    { id: "u06.d1", lesson: 1, fr: "J'ai ___ stylo.", options: ["un", "une"], answer: 0, en: "I have a pen.", de: "Ich habe einen Stift.", why: tx("**Stylo** is masculine: **un** stylo, le stylo. Une is for feminine words: une école.", "**Stylo** ist männlich: **un** stylo, le stylo. Une steht vor weiblichen Wörtern: une école.") },
    { id: "u06.d2", lesson: 1, fr: "___école est grande.", options: ["L'", "La", "Le"], answer: 0, en: "The school is big.", de: "Die Schule ist groß.", why: tx("Before a vowel, le and la shrink to **l'**: **l'école**, l'élève.", "Vor einem Vokal werden le und la zu **l'**: **l'école**, l'élève.") },
    { id: "u06.d3", lesson: 2, fr: "Je ___ français.", options: ["parle", "parles", "parlez"], answer: 0, en: "I speak French.", de: "Ich spreche Französisch.", why: tx("With **je** the ending is **-e**: je parl**e**.", "Mit **je** endet es auf **-e**: je parl**e**.") },
    { id: "u06.d4", lesson: 2, fr: "Tu ___ anglais ?", options: ["parles", "parle", "parlons"], answer: 0, en: "Do you speak English?", de: "Sprichst du Englisch?", why: tx("With **tu** the ending is **-es**: tu parl**es**. You don't hear the s.", "Mit **tu** endet es auf **-es**: tu parl**es**. Das s hört man nicht.") },
    { id: "u06.d5", lesson: 2, fr: "Léa ___ allemand.", options: ["parle", "parles", "parlent"], answer: 0, en: "Léa speaks German.", de: "Léa spricht Deutsch.", why: tx("Léa is one person, like **il** or **elle**: Léa **parle**.", "Léa ist eine Person, wie **il** oder **elle**: Léa **parle**.") },
    { id: "u06.d6", lesson: 3, fr: "Nous ___ français en classe.", options: ["parlons", "parlez", "parle"], answer: 0, en: "We speak French in class.", de: "Wir sprechen im Unterricht Französisch.", why: tx("With **nous** the ending is **-ons**: nous parl**ons**.", "Mit **nous** endet es auf **-ons**: nous parl**ons**.") },
    { id: "u06.d7", lesson: 3, fr: "Vous ___ anglais, Madame Martin ?", options: ["parlez", "parlons", "parles"], answer: 0, en: "Do you speak English, Mrs Martin?", de: "Sprechen Sie Englisch, Frau Martin?", why: tx("With **vous** the ending is **-ez**: vous parl**ez**. It sounds like parler.", "Mit **vous** endet es auf **-ez**: vous parl**ez**. Es klingt wie parler.") },
    { id: "u06.d8", lesson: 3, fr: "Est-ce ___ parle français ?", options: ["qu'il", "que il"], answer: 0, en: "Does he speak French?", de: "Spricht er Französisch?", why: tx("Before a vowel, que shrinks to **qu'**: est-ce **qu'il** parle français ?", "Vor einem Vokal wird que zu **qu'**: est-ce **qu'il** parle français ?") },
    { id: "u06.d9", lesson: 4, fr: "Les élèves ___ le professeur.", options: ["écoutent", "écoute", "écoutez"], answer: 0, en: "The pupils are listening to the teacher.", de: "Die Schüler hören dem Lehrer zu.", why: tx("With **ils / elles** (the pupils) the ending is **-ent**, and it's silent: ils écout**ent** sounds like il écoute.", "Mit **ils / elles** (die Schüler) endet es auf **-ent**, und das ist stumm: ils écout**ent** klingt wie il écoute.") },
    { id: "u06.d10", lesson: 4, fr: "Tu ___ le tableau ?", options: ["regardes", "regarde", "regardez"], answer: 0, en: "Are you looking at the board?", de: "Schaust du zur Tafel?", why: tx("With **tu**, -er verbs end in **-es**: tu regard**es**, like tu parles.", "Mit **tu** enden -er-Verben auf **-es**: tu regard**es**, wie tu parles.") },
    { id: "u06.d11", lesson: 5, fr: "Les devoirs sont ___.", options: ["difficiles", "difficile"], answer: 0, en: "The homework is difficult.", de: "Die Hausaufgaben sind schwer.", why: tx("**Les devoirs** is plural, so the adjective gets an **s** too: difficile**s**. You don't hear it.", "**Les devoirs** ist Plural, also bekommt das Adjektiv auch ein **s**: difficile**s**. Man hört es nicht.") },
    { id: "u06.d12", lesson: 5, fr: "Je ne travaille ___ aujourd'hui.", options: ["pas", "non", "ne"], answer: 0, en: "I'm not working today.", de: "Ich arbeite heute nicht.", why: tx("Not comes in two parts around the verb: je **ne** travaille **pas**.", "Die Verneinung hat zwei Teile um das Verb herum: je **ne** travaille **pas**.") },
  ],
  dialogue: {
    id: "u06.dialogue",
    lesson: 5,
    title: tx("Blob's first day at school", "Blobs erster Schultag"),
    lines: [
      { who: "prof", fr: "Bonjour ! Aujourd'hui, nous parlons français.", en: "Good morning! Today we're speaking French.", de: "Guten Morgen! Heute sprechen wir Französisch." },
      { who: "blob", fr: "Bonjour, Monsieur ! J'ai une question.", en: "Good morning, sir! I have a question.", de: "Guten Morgen! Ich habe eine Frage." },
      { who: "prof", fr: "Oui, Blob ?", en: "Yes, Blob?", de: "Ja, Blob?" },
      { who: "blob", fr: "Est-ce que les devoirs sont difficiles ?", en: "Is the homework difficult?", de: "Sind die Hausaufgaben schwer?" },
      { who: "prof", fr: "Non, c'est facile. Tu as ton livre et ton cahier ?", en: "No, it's easy. Do you have your book and your exercise book?", de: "Nein, das ist leicht. Hast du dein Buch und dein Heft?" },
      { who: "blob", fr: "Euh… dans mon sac, il y a un croissant.", en: "Er… in my bag there's a croissant.", de: "Äh … in meiner Tasche ist ein Croissant." },
      { who: "hugo", fr: "Blob, j'ai un stylo pour toi !", en: "Blob, I have a pen for you!", de: "Blob, ich habe einen Stift für dich!" },
      { who: "lea", fr: "Et moi, j'ai un cahier !", en: "And I have an exercise book!", de: "Und ich habe ein Heft!" },
      { who: "blob", fr: "Merci ! Et le croissant, c'est pour le professeur !", en: "Thank you! And the croissant is for the teacher!", de: "Danke! Und das Croissant ist für den Lehrer!" },
      { who: "prof", fr: "Merci, Blob ! Mais maintenant, on travaille !", en: "Thank you, Blob! But now, let's get to work!", de: "Danke, Blob! Aber jetzt wird gearbeitet!" },
    ],
    questions: [
      { q: tx("What is in Blob's bag?", "Was ist in Blobs Tasche?"), options: [tx("A croissant", "Ein Croissant"), tx("A book", "Ein Buch"), tx("An exercise book", "Ein Heft")], answer: 0 },
      { q: tx("Is the homework difficult?", "Sind die Hausaufgaben schwer?"), options: [tx("No, it's easy.", "Nein, sie sind leicht."), tx("Yes, very difficult.", "Ja, sehr schwer."), tx("The teacher doesn't say.", "Der Lehrer sagt es nicht.")], answer: 0 },
      { q: tx("What does Hugo have for Blob?", "Was hat Hugo für Blob?"), options: [tx("A pen", "Einen Stift"), tx("An exercise book", "Ein Heft"), tx("A croissant", "Ein Croissant")], answer: 0 },
    ],
  },
  tips: [
    {
      title: tx("-er verbs: one pattern for hundreds", "Verben auf -er: ein Muster für Hunderte"),
      body: tx(
        "Most French verbs end in **-er**: parler (to speak), écouter (to listen), regarder (to look at), travailler (to work). Take off -er and add the ending.\n\n**Je parle, tu parles, il parle, ils parlent** all sound the same! Only **nous parlons** and **vous parlez** sound different. **Vous** is for several people, or for one person you call Monsieur or Madame.",
        "Die meisten französischen Verben enden auf **-er**: parler (sprechen), écouter (zuhören), regarder (anschauen), travailler (arbeiten). Nimm -er weg und häng die Endung an.\n\n**Je parle, tu parles, il parle, ils parlent** klingen alle gleich! Nur **nous parlons** und **vous parlez** klingen anders. **Vous** ist für mehrere Leute oder für eine Person, die du siezt.",
      ),
      examples: [
        { fr: "Je parle français.", en: "I speak French.", de: "Ich spreche Französisch." },
        { fr: "Nous parlons anglais.", en: "We speak English.", de: "Wir sprechen Englisch." },
        { fr: "Les élèves écoutent.", en: "The pupils are listening.", de: "Die Schüler hören zu." },
      ],
      table: {
        head: [tx("person", "Person"), "parler", "écouter"],
        rows: [
          [tx("I", "ich"), "je parle", "j'écoute"],
          [tx("you", "du"), "tu parles", "tu écoutes"],
          [tx("he / she", "er / sie"), "il / elle parle", "il / elle écoute"],
          [tx("we", "wir"), "nous parlons", "nous écoutons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous parlez", "vous écoutez"],
          [tx("they", "sie"), "ils / elles parlent", "ils / elles écoutent"],
        ],
      },
    },
    {
      title: tx("Est-ce que: yes/no questions", "Est-ce que: Ja/Nein-Fragen"),
      body: tx(
        "The easiest question is a normal sentence with your voice going up: **Tu parles français ?**\n\nOr put **est-ce que** in front, and nothing else changes: **est-ce que** tu parles français ? Before a vowel it becomes **est-ce qu'**: est-ce qu'il parle anglais ?",
        "Die einfachste Frage ist ein normaler Satz, bei dem die Stimme am Ende hochgeht: **Tu parles français ?**\n\nOder stell **est-ce que** davor, sonst ändert sich nichts: **est-ce que** tu parles français ? Vor einem Vokal wird es zu **est-ce qu'**: est-ce qu'il parle anglais ?",
      ),
      examples: [
        { fr: "Tu parles anglais ?", en: "Do you speak English?", de: "Sprichst du Englisch?" },
        { fr: "Est-ce que vous êtes le professeur ?", en: "Are you the teacher?", de: "Sind Sie der Lehrer?" },
        { fr: "Est-ce qu'il parle français ?", en: "Does he speak French?", de: "Spricht er Französisch?" },
      ],
    },
    {
      title: tx("Listen to, look at: no little word", "Zuhören, anschauen: ohne Extrawort"),
      body: tx(
        "English says listen **to** and look **at**. French doesn't need a little word: **j'écoute le professeur**, **je regarde le tableau**.\n\nAnd **je** shrinks to **j'** before a vowel: **j'écoute**, j'ai, j'aime.",
        "Im Deutschen hängt oft ein Extrateil am Verb: Ich höre dem Lehrer **zu**, ich schaue das Buch **an**. Französisch braucht nur ein Wort: **j'écoute le professeur**, **je regarde le livre**.\n\nUnd **je** wird vor einem Vokal zu **j'**: **j'écoute**, j'ai, j'aime.",
      ),
      examples: [
        { fr: "J'écoute le professeur.", en: "I'm listening to the teacher.", de: "Ich höre dem Lehrer zu." },
        { fr: "Je regarde le tableau.", en: "I'm looking at the board.", de: "Ich schaue an die Tafel." },
      ],
    },
  ],
};
