import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 7: places in town, aller (all forms), au / à la / à l' / aux, où, and asking the way. */
export const u07: Unit = {
  slug: "ville",
  n: 7,
  cefr: "A1",
  title: tx("In town", "In der Stadt"),
  goal: tx("Say where you're going and find your way around town", "Sagen, wohin du gehst, und dich in der Stadt zurechtfinden"),
  emoji: "🏙️",
  words: [
    { id: "ville", fr: "la ville", en: "the town", de: "die Stadt", alt: { en: ["the city"] }, g: "f", kind: "noun", emoji: "🏙️", note: tx("En ville: in town, into town.", "En ville: in der Stadt, in die Stadt.") },
    { id: "maison", fr: "la maison", en: "the house", de: "das Haus", alt: { en: ["the home"], de: ["das Zuhause"] }, g: "f", kind: "noun", emoji: "🏠", note: tx("À la maison: at home, or home.", "À la maison: zu Hause oder nach Hause.") },
    { id: "parc", fr: "le parc", en: "the park", de: "der Park", g: "m", kind: "noun", emoji: "🌳" },
    { id: "gare", fr: "la gare", en: "the station", de: "der Bahnhof", alt: { en: ["the train station", "the railway station"] }, g: "f", kind: "noun", emoji: "🚉", note: tx("Feminine: la gare, à la gare.", "Weiblich, anders als der Bahnhof: la gare.") },
    { id: "ou", fr: "où", en: "where", de: "wo", alt: { de: ["wohin"] }, kind: "word", note: tx("With an accent, où means where. Without it, ou means or.", "Mit Akzent heißt où wo. Ohne Akzent heißt ou oder.") },
    { id: "je-vais", fr: "je vais", en: "I go", de: "ich gehe", alt: { en: ["I am going"], de: ["ich fahre"] }, kind: "verb", note: tx("From aller, to go. Irregular, but you'll use it every day.", "Von aller, gehen. Unregelmäßig, aber du brauchst es jeden Tag.") },
    { id: "tu-vas", fr: "tu vas", en: "you go", de: "du gehst", alt: { en: ["you are going"], de: ["du fährst"] }, kind: "verb" },
    { id: "il-va", fr: "il va", en: "he goes", de: "er geht", alt: { en: ["he is going"], de: ["er fährt"] }, kind: "verb", note: tx("Elle va: she goes. And ça va? Literally «it goes»!", "Elle va: sie geht. Und ça va? Wörtlich „es geht“!") },
    { id: "cinema", fr: "le cinéma", en: "the cinema", de: "das Kino", alt: { en: ["the movies"] }, g: "m", kind: "noun", emoji: "🎬" },
    { id: "boulangerie", fr: "la boulangerie", en: "the bakery", de: "die Bäckerei", alt: { de: ["der Bäcker"] }, g: "f", kind: "noun", note: tx("Where the baguettes and croissants come from. The baker: le boulanger.", "Hier gibt es Baguettes und Croissants. Der Bäcker: le boulanger.") },
    { id: "nous-allons", fr: "nous allons", en: "we go", de: "wir gehen", alt: { en: ["we are going"], de: ["wir fahren"] }, kind: "verb" },
    { id: "vous-allez", fr: "vous allez", en: "you go (plural / polite)", de: "ihr geht / Sie gehen", kind: "verb", note: tx("Like vous parlez: -ez. Allez ! on its own means «go!» or «come on!».", "Wie vous parlez: -ez. Allez ! allein heißt „los!“.") },
    { id: "ils-vont", fr: "ils vont", en: "they go", de: "sie gehen", alt: { en: ["they are going"], de: ["sie fahren"] }, kind: "verb", note: tx("Elles vont for a group of girls or women.", "Elles vont für eine Gruppe von Mädchen oder Frauen.") },
    { id: "piscine", fr: "la piscine", en: "the swimming pool", de: "das Schwimmbad", alt: { en: ["the pool"] }, g: "f", kind: "noun", emoji: "🏊" },
    { id: "plage", fr: "la plage", en: "the beach", de: "der Strand", g: "f", kind: "noun", emoji: "🏖️" },
    { id: "musee", fr: "le musée", en: "the museum", de: "das Museum", g: "m", kind: "noun", emoji: "🏛️", note: tx("Masculine, even with -ée at the end: le musée.", "Männlich, trotz -ée am Ende: le musée.") },
    { id: "excusez-moi", fr: "excusez-moi", en: "excuse me", de: "Entschuldigung", alt: { de: ["entschuldigen Sie"] }, kind: "phrase", note: tx("The polite way to stop someone in the street. To a friend: excuse-moi.", "So sprichst du höflich jemanden auf der Straße an. Zu Freunden: excuse-moi.") },
    { id: "a-droite", fr: "à droite", en: "on the right", de: "rechts", alt: { en: ["to the right"], de: ["nach rechts"] }, kind: "phrase", emoji: "➡️" },
    { id: "a-gauche", fr: "à gauche", en: "on the left", de: "links", alt: { en: ["to the left"], de: ["nach links"] }, kind: "phrase", emoji: "⬅️" },
    { id: "tout-droit", fr: "tout droit", en: "straight on", de: "geradeaus", alt: { en: ["straight ahead"] }, kind: "phrase", emoji: "⬆️", note: tx("Careful: droit means straight, droite with an e means right.", "Vorsicht: droit heißt gerade, droite mit e heißt rechts.") },
    { id: "supermarche", fr: "le supermarché", en: "the supermarket", de: "der Supermarkt", g: "m", kind: "noun", emoji: "🛒" },
    { id: "loin", fr: "loin", en: "far", de: "weit", alt: { en: ["far away"], de: ["weit weg"] }, kind: "adv" },
    { id: "pres", fr: "près", en: "near", de: "nah", alt: { en: ["close"], de: ["in der Nähe"] }, kind: "adv", note: tx("Near the station: près de la gare. Near the park: près du parc.", "In der Nähe des Bahnhofs: près de la gare. Beim Park: près du parc.") },
  ],
  gloss: [
    { fr: "allons", en: "go (we)", de: "gehen (wir)" },
    { fr: "allez", en: "go (you, plural / polite)", de: "geht / gehen (Sie)" },
    { fr: "vont", en: "go (they)", de: "gehen (sie)" },
    { fr: "tournez", en: "turn (you, plural / polite)", de: "biegt ab / biegen (Sie) ab" },
    { fr: "puis", en: "then", de: "dann" },
    { fr: "derrière", en: "behind", de: "hinter" },
    { fr: "croissants", en: "croissants", de: "Croissants" },
    { fr: "oh", en: "oh", de: "oh" },
  ],
  lessons: [
    { title: tx("Where is it?", "Wo ist das?"), words: ["ville", "maison", "parc", "gare", "ou"] },
    { title: tx("I'm going to the cinema", "Ich gehe ins Kino"), words: ["je-vais", "tu-vas", "il-va", "cinema", "boulangerie"] },
    { title: tx("We're going to the beach", "Wir fahren an den Strand"), words: ["nous-allons", "vous-allez", "ils-vont", "piscine", "plage", "musee"] },
    { title: tx("Left, right, straight on", "Links, rechts, geradeaus"), words: ["excusez-moi", "a-droite", "a-gauche", "tout-droit"] },
    { title: tx("Near or far?", "Nah oder weit?"), words: ["supermarche", "loin", "pres"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u07.01", lesson: 1, fr: "Où est la gare ?", en: "Where is the station?", de: "Wo ist der Bahnhof?", alt: { fr: ["La gare est où ?"], en: ["Where is the train station?", "Where is the railway station?"] } },
    { id: "u07.02", lesson: 1, fr: "C'est une grande ville.", en: "It's a big town.", de: "Das ist eine große Stadt.", alt: { en: ["It's a big city.", "This is a big town.", "This is a big city.", "That's a big town.", "That's a big city.", "It's a large town.", "It's a large city."], de: ["Es ist eine große Stadt."] } },
    { id: "u07.03", lesson: 1, fr: "Le parc est grand.", en: "The park is big.", de: "Der Park ist groß.", alt: { en: ["The park is large."] } },
    { id: "u07.04", lesson: 1, fr: "Où est ta maison ?", en: "Where is your house?", de: "Wo ist dein Haus?", alt: { fr: ["Ta maison est où ?", "Où est votre maison ?", "Votre maison est où ?"], en: ["Where's your house?", "Where is your home?"] } },
    { id: "u07.05", lesson: 1, fr: "Ma maison est petite.", en: "My house is small.", de: "Mein Haus ist klein.", alt: { en: ["My house is little."] } },
    { id: "u07.06", lesson: 1, fr: "Il y a un parc dans la ville.", en: "There's a park in the town.", de: "In der Stadt gibt es einen Park.", alt: { fr: ["Dans la ville, il y a un parc."], en: ["There is a park in the city.", "There is a park in town."], de: ["Es gibt einen Park in der Stadt.", "In der Stadt ist ein Park."] } },
    { id: "u07.07", lesson: 1, fr: "Je suis à la maison.", en: "I'm at home.", de: "Ich bin zu Hause.", alt: { en: ["I am home.", "I am at the house."], de: ["Ich bin zuhause.", "Ich bin daheim."] } },
    // Lesson 2
    { id: "u07.08", lesson: 2, fr: "Je vais au cinéma.", en: "I'm going to the cinema.", de: "Ich gehe ins Kino.", alt: { en: ["I go to the cinema.", "I am going to the movies.", "I go to the movies."] } },
    { id: "u07.09", lesson: 2, fr: "Tu vas à la boulangerie ?", en: "Are you going to the bakery?", de: "Gehst du zur Bäckerei?", alt: { fr: ["Est-ce que tu vas à la boulangerie ?", "Vas-tu à la boulangerie ?", "Vous allez à la boulangerie ?", "Est-ce que vous allez à la boulangerie ?", "Allez-vous à la boulangerie ?"], en: ["You are going to the bakery?", "Do you go to the bakery?"], de: ["Gehst du in die Bäckerei?", "Gehst du zum Bäcker?", "Du gehst zur Bäckerei?"] } },
    { id: "u07.10", lesson: 2, fr: "Il va à la gare.", en: "He's going to the station.", de: "Er geht zum Bahnhof.", alt: { en: ["He goes to the station.", "He is going to the train station.", "He goes to the train station."], de: ["Er fährt zum Bahnhof."] } },
    { id: "u07.11", lesson: 2, fr: "Elle va au parc avec le chien.", en: "She's going to the park with the dog.", de: "Sie geht mit dem Hund in den Park.", alt: { en: ["She goes to the park with the dog."], de: ["Sie geht mit dem Hund zum Park.", "Sie geht in den Park mit dem Hund."] } },
    { id: "u07.12", lesson: 2, fr: "Je vais à l'école.", en: "I'm going to school.", de: "Ich gehe zur Schule.", alt: { en: ["I go to school.", "I am going to the school.", "I go to the school."], de: ["Ich gehe in die Schule."] } },
    { id: "u07.13", lesson: 2, fr: "Tu vas où ?", en: "Where are you going?", de: "Wohin gehst du?", alt: { fr: ["Où vas-tu ?", "Où est-ce que tu vas ?", "Où tu vas ?", "Vous allez où ?", "Où allez-vous ?", "Où est-ce que vous allez ?"], en: ["Where do you go?"], de: ["Wo gehst du hin?"] } },
    { id: "u07.14", lesson: 2, fr: "Hugo ne va pas à l'école.", en: "Hugo isn't going to school.", de: "Hugo geht nicht zur Schule.", alt: { en: ["Hugo does not go to school.", "Hugo is not going to the school."], de: ["Hugo geht nicht in die Schule."] } },
    // Lesson 3
    { id: "u07.15", lesson: 3, fr: "Nous allons à la plage.", en: "We're going to the beach.", de: "Wir gehen an den Strand.", alt: { en: ["We go to the beach."], de: ["Wir gehen zum Strand.", "Wir fahren an den Strand.", "Wir fahren zum Strand."] } },
    { id: "u07.16", lesson: 3, fr: "Vous allez au musée ?", en: "Are you going to the museum?", de: "Geht ihr ins Museum?", alt: { fr: ["Est-ce que vous allez au musée ?", "Allez-vous au musée ?", "Tu vas au musée ?", "Est-ce que tu vas au musée ?", "Vas-tu au musée ?"], en: ["You are going to the museum?", "Do you go to the museum?"], de: ["Gehen Sie ins Museum?", "Ihr geht ins Museum?"] } },
    { id: "u07.17", lesson: 3, fr: "Ils vont à la piscine.", en: "They're going to the swimming pool.", de: "Sie gehen ins Schwimmbad.", alt: { fr: ["Elles vont à la piscine."], en: ["They are going to the pool.", "They go to the swimming pool.", "They go to the pool."], de: ["Sie gehen ins Hallenbad.", "Sie gehen ins Freibad."] } },
    { id: "u07.18", lesson: 3, fr: "Léa et Hugo vont au cinéma.", en: "Léa and Hugo are going to the cinema.", de: "Léa und Hugo gehen ins Kino.", alt: { en: ["Léa and Hugo go to the cinema.", "Léa and Hugo are going to the movies.", "Léa and Hugo go to the movies."] } },
    { id: "u07.19", lesson: 3, fr: "Où est-ce que vous allez, Madame Martin ?", en: "Where are you going, Mrs Martin?", de: "Wohin gehen Sie, Frau Martin?", alt: { fr: ["Où allez-vous, Madame Martin ?", "Vous allez où, Madame Martin ?", "Madame Martin, où est-ce que vous allez ?", "Madame Martin, où allez-vous ?", "Madame Martin, vous allez où ?"], en: ["Mrs Martin, where are you going?"], de: ["Wo gehen Sie hin, Frau Martin?", "Frau Martin, wohin gehen Sie?"] } },
    { id: "u07.20", lesson: 3, fr: "Nous n'allons pas à la piscine.", en: "We're not going to the swimming pool.", de: "Wir gehen nicht ins Schwimmbad.", alt: { en: ["We aren't going to the swimming pool.", "We are not going to the pool.", "We don't go to the swimming pool.", "We don't go to the pool."] } },
    { id: "u07.21", lesson: 3, fr: "Le professeur parle aux élèves.", en: "The teacher is talking to the pupils.", de: "Der Lehrer spricht mit den Schülern.", alt: { en: ["The teacher talks to the pupils.", "The teacher is speaking to the pupils.", "The teacher speaks to the pupils.", "The teacher is talking to the students.", "The teacher talks to the students.", "The teacher is speaking to the students.", "The teacher speaks to the students."], de: ["Der Lehrer redet mit den Schülern.", "Der Lehrer spricht zu den Schülern."] } },
    // Lesson 4
    { id: "u07.22", lesson: 4, fr: "Excusez-moi, où est le musée ?", en: "Excuse me, where is the museum?", de: "Entschuldigung, wo ist das Museum?", alt: { fr: ["Excuse-moi, où est le musée ?"], en: ["Excuse me, where's the museum?"], de: ["Entschuldigen Sie, wo ist das Museum?"] } },
    { id: "u07.23", lesson: 4, fr: "La piscine est à droite.", en: "The swimming pool is on the right.", de: "Das Schwimmbad ist rechts.", alt: { en: ["The pool is on the right.", "The swimming pool is to the right.", "The pool is to the right."], de: ["Das Schwimmbad ist auf der rechten Seite.", "Rechts ist das Schwimmbad."] } },
    { id: "u07.24", lesson: 4, fr: "Allez tout droit !", en: "Go straight on!", de: "Gehen Sie geradeaus!", alt: { fr: ["Va tout droit !"], en: ["Go straight ahead!", "Keep going straight on!", "Keep going straight ahead!"], de: ["Geht geradeaus!", "Immer geradeaus!"] } },
    { id: "u07.25", lesson: 4, fr: "La boulangerie est à gauche.", en: "The bakery is on the left.", de: "Die Bäckerei ist links.", alt: { en: ["The bakery is to the left."], de: ["Die Bäckerei ist auf der linken Seite.", "Links ist die Bäckerei."] } },
    { id: "u07.26", lesson: 4, fr: "Tournez à droite, puis à gauche.", en: "Turn right, then left.", de: "Biegen Sie rechts ab, dann links.", alt: { fr: ["Tournez à droite et puis à gauche.", "Tourne à droite, puis à gauche."], en: ["Turn right and then left.", "Turn right, then turn left.", "Turn to the right, then to the left."], de: ["Biegen Sie rechts ab und dann links.", "Biegt rechts ab, dann links.", "Biegt rechts ab und dann links.", "Rechts abbiegen, dann links."] } },
    { id: "u07.27", lesson: 4, fr: "Excusez-moi, Monsieur, la gare est à gauche ?", en: "Excuse me, is the station on the left?", de: "Entschuldigung, ist der Bahnhof links?", alt: { fr: ["Excusez-moi, Monsieur, est-ce que la gare est à gauche ?", "Excusez-moi, la gare est à gauche ?", "Excusez-moi, est-ce que la gare est à gauche ?"], en: ["Excuse me, sir, is the station on the left?", "Excuse me, is the station to the left?", "Excuse me, sir, is the station to the left?"], de: ["Entschuldigen Sie, ist der Bahnhof links?"] } },
    { id: "u07.28", lesson: 4, fr: "Le cinéma est tout droit.", en: "The cinema is straight ahead.", de: "Das Kino ist geradeaus.", alt: { fr: ["Le cinéma, c'est tout droit."], en: ["The cinema is straight on."] } },
    // Lesson 5
    { id: "u07.29", lesson: 5, fr: "C'est loin ?", en: "Is it far?", de: "Ist es weit?", alt: { fr: ["Est-ce que c'est loin ?"], en: ["Is that far?", "Is it far away?", "Is that far away?"], de: ["Ist das weit?", "Ist es weit weg?", "Ist das weit weg?"] } },
    { id: "u07.30", lesson: 5, fr: "Non, ce n'est pas loin.", en: "No, it's not far.", de: "Nein, es ist nicht weit.", alt: { en: ["No, it is not far away.", "No, that's not far."], de: ["Nein, das ist nicht weit.", "Nein, es ist nicht weit weg.", "Nein, das ist nicht weit weg."] } },
    { id: "u07.31", lesson: 5, fr: "Le supermarché est près de la gare.", en: "The supermarket is near the station.", de: "Der Supermarkt ist in der Nähe des Bahnhofs.", alt: { en: ["The supermarket is close to the station.", "The supermarket is near the train station."], de: ["Der Supermarkt ist in der Nähe vom Bahnhof.", "Der Supermarkt ist nah am Bahnhof.", "Der Supermarkt ist nahe am Bahnhof.", "Der Supermarkt ist beim Bahnhof."] } },
    { id: "u07.32", lesson: 5, fr: "Mes parents vont au supermarché.", en: "My parents are going to the supermarket.", de: "Meine Eltern gehen in den Supermarkt.", alt: { en: ["My parents go to the supermarket."], de: ["Meine Eltern gehen zum Supermarkt.", "Meine Eltern fahren zum Supermarkt.", "Meine Eltern fahren in den Supermarkt."] } },
    { id: "u07.33", lesson: 5, fr: "Où sont Léa et Hugo ?", en: "Where are Léa and Hugo?", de: "Wo sind Léa und Hugo?", alt: { fr: ["Léa et Hugo sont où ?"] } },
    { id: "u07.34", lesson: 5, fr: "La plage est très loin.", en: "The beach is very far away.", de: "Der Strand ist sehr weit weg.", alt: { en: ["The beach is very far.", "The beach is a long way away."], de: ["Der Strand ist sehr weit.", "Der Strand ist sehr weit entfernt."] } },
  ],
  drills: [
    { id: "u07.d1", lesson: 1, fr: "___ est la gare ?", options: ["Où", "Ou"], answer: 0, en: "Where is the station?", de: "Wo ist der Bahnhof?", why: tx("**Où** with an accent means where. Ou without it means or.", "**Où** mit Akzent heißt wo. Ou ohne Akzent heißt oder.") },
    { id: "u07.d2", lesson: 2, fr: "Je ___ au cinéma.", options: ["vais", "vas", "va"], answer: 0, en: "I'm going to the cinema.", de: "Ich gehe ins Kino.", why: tx("With **je**, aller is **vais**: je vais.", "Mit **je** heißt aller **vais**: je vais.") },
    { id: "u07.d3", lesson: 2, fr: "Tu ___ à la boulangerie ?", options: ["vas", "vais", "va"], answer: 0, en: "Are you going to the bakery?", de: "Gehst du zur Bäckerei?", why: tx("With **tu**: tu **vas**. The s is silent.", "Mit **tu**: tu **vas**. Das s ist stumm.") },
    { id: "u07.d4", lesson: 2, fr: "Je vais ___ cinéma.", options: ["au", "à la", "à le"], answer: 0, en: "I'm going to the cinema.", de: "Ich gehe ins Kino.", why: tx("**À + le** always melts into **au**: au cinéma, au parc. «À le» doesn't exist.", "**À + le** wird immer zu **au**: au cinéma, au parc. „À le“ gibt es nicht.") },
    { id: "u07.d5", lesson: 2, fr: "Il va ___ gare.", options: ["à la", "au", "à l'"], answer: 0, en: "He's going to the station.", de: "Er geht zum Bahnhof.", why: tx("**Gare** is feminine: **à la** gare. À la never changes.", "**Gare** ist weiblich: **à la** gare. À la bleibt immer so.") },
    { id: "u07.d6", lesson: 3, fr: "Nous ___ à la plage.", options: ["allons", "allez", "vont"], answer: 0, en: "We're going to the beach.", de: "Wir gehen an den Strand.", why: tx("With **nous**: nous **allons**.", "Mit **nous**: nous **allons**.") },
    { id: "u07.d7", lesson: 3, fr: "Léa et Hugo ___ au musée.", options: ["vont", "va", "allons"], answer: 0, en: "Léa and Hugo are going to the museum.", de: "Léa und Hugo gehen ins Museum.", why: tx("Léa and Hugo = **ils**: ils **vont**.", "Léa und Hugo = **ils** (sie): ils **vont**.") },
    { id: "u07.d8", lesson: 3, fr: "Vous ___ à la piscine ?", options: ["allez", "allons", "vas"], answer: 0, en: "Are you going to the swimming pool?", de: "Geht ihr ins Schwimmbad?", why: tx("With **vous**: vous **allez**, with -ez like vous parlez.", "Mit **vous**: vous **allez**, mit -ez wie vous parlez.") },
    { id: "u07.d9", lesson: 3, fr: "Nous allons ___école.", options: ["à l'", "à la", "au"], answer: 0, en: "We're going to school.", de: "Wir gehen zur Schule.", why: tx("Before a vowel, le and la shrink to l', so it's **à l'**: à l'école. No au, no à la.", "Vor einem Vokal werden le und la zu l', also **à l'**: à l'école. Kein au, kein à la.") },
    { id: "u07.d10", lesson: 3, fr: "Le professeur parle ___ élèves.", options: ["aux", "à les", "au"], answer: 0, en: "The teacher is talking to the pupils.", de: "Der Lehrer spricht mit den Schülern.", why: tx("**À + les** melts into **aux**: aux élèves. Before a vowel you hear a z: aux‿élèves.", "**À + les** wird zu **aux**: aux élèves. Vor einem Vokal hört man ein weiches s: aux‿élèves.") },
    { id: "u07.d11", lesson: 4, fr: "La boulangerie est ___ gauche.", options: ["à", "au", "la"], answer: 0, en: "The bakery is on the left.", de: "Die Bäckerei ist links.", why: tx("Left and right: **à** gauche, **à** droite. Always with à.", "Links und rechts: **à** gauche, **à** droite. Immer mit à.") },
    { id: "u07.d12", lesson: 5, fr: "Le supermarché est près ___ la gare.", options: ["de", "à", "au"], answer: 0, en: "The supermarket is near the station.", de: "Der Supermarkt ist in der Nähe des Bahnhofs.", why: tx("Near is **près de**: près de la gare. With le it becomes du: près du parc.", "In der Nähe von heißt **près de**: près de la gare. Mit le wird es zu du: près du parc.") },
  ],
  dialogue: {
    id: "u07.dialogue",
    lesson: 5,
    title: tx("Where is the bakery?", "Wo ist die Bäckerei?"),
    lines: [
      { who: "blob", fr: "Excusez-moi, Madame Martin ! Où est la boulangerie ?", en: "Excuse me, Mrs Martin! Where is the bakery?", de: "Entschuldigung, Frau Martin! Wo ist die Bäckerei?" },
      { who: "madame", fr: "Bonjour, Blob ! Tu vas à la boulangerie ?", en: "Hello, Blob! Are you going to the bakery?", de: "Hallo, Blob! Gehst du zur Bäckerei?" },
      { who: "blob", fr: "Oui ! J'aime les croissants. C'est loin ?", en: "Yes! I love croissants. Is it far?", de: "Ja! Ich liebe Croissants. Ist es weit?" },
      { who: "madame", fr: "Non, c'est très près. Regarde…", en: "No, it's very close. Look…", de: "Nein, ganz nah. Schau mal …" },
      { who: "blob", fr: "Merci ! Je vais tout droit !", en: "Thanks! I'm going straight on!", de: "Danke! Ich gehe geradeaus!" },
      { who: "madame", fr: "Non, Blob ! Pas tout droit ! La boulangerie est à gauche… derrière toi !", en: "No, Blob! Not straight on! The bakery is on the left… behind you!", de: "Nein, Blob! Nicht geradeaus! Die Bäckerei ist links … hinter dir!" },
      { who: "blob", fr: "Oh ! Merci, Madame. Et vous, vous allez où ?", en: "Oh! Thank you. And you, where are you going?", de: "Oh! Danke. Und Sie, wohin gehen Sie?" },
      { who: "madame", fr: "Moi ? Je vais à la boulangerie aussi. Pour les croissants !", en: "Me? I'm going to the bakery too. For the croissants!", de: "Ich? Ich gehe auch zur Bäckerei. Wegen der Croissants!" },
    ],
    questions: [
      { q: tx("Where does Blob want to go?", "Wohin will Blob?"), options: [tx("To the bakery", "Zur Bäckerei"), tx("To the station", "Zum Bahnhof"), tx("To the supermarket", "Zum Supermarkt")], answer: 0 },
      { q: tx("Where is the bakery?", "Wo ist die Bäckerei?"), options: [tx("On the left, behind Blob", "Links, hinter Blob"), tx("Straight on, very far away", "Geradeaus, sehr weit weg"), tx("On the right, near the station", "Rechts, beim Bahnhof")], answer: 0 },
      { q: tx("Where is Mrs Martin going?", "Wohin geht Frau Martin?"), options: [tx("To the bakery too", "Auch zur Bäckerei"), tx("To the park", "In den Park"), tx("Home", "Nach Hause")], answer: 0 },
    ],
  },
  tips: [
    {
      title: tx("Aller: to go", "Aller: gehen"),
      body: tx(
        "**Aller** (to go) is irregular, so learn it by heart. You'll need it every day: **je vais** à l'école, **tu vas** au cinéma ?\n\nFrench doesn't care how you get there: on foot, by bike or by car, it's always aller.",
        "**Aller** (gehen) ist unregelmäßig, also lern es auswendig. Du brauchst es jeden Tag: **je vais** à l'école, **tu vas** au cinéma ?\n\nAller heißt auch fahren: Ob zu Fuß, mit dem Rad oder mit dem Auto, es ist immer aller.",
      ),
      examples: [
        { fr: "Je vais à l'école.", en: "I'm going to school.", de: "Ich gehe zur Schule." },
        { fr: "Nous allons à la plage.", en: "We're going to the beach.", de: "Wir fahren an den Strand." },
        { fr: "Ils vont au cinéma.", en: "They're going to the cinema.", de: "Sie gehen ins Kino." },
      ],
      table: {
        head: [tx("person", "Person"), "aller"],
        rows: [
          [tx("I", "ich"), "je vais"],
          [tx("you", "du"), "tu vas"],
          [tx("he / she", "er / sie"), "il / elle va"],
          [tx("we", "wir"), "nous allons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous allez"],
          [tx("they", "sie"), "ils / elles vont"],
        ],
      },
    },
    {
      title: tx("Au, à la, à l', aux", "Au, à la, à l', aux"),
      body: tx(
        "**À** means to or at. Before le and les it melts into one word: **à + le = au**, **à + les = aux**. À la and à l' stay as they are.\n\nSo four forms do the work of «to the» and «at the».",
        "**À** heißt zu, in, an oder nach. Vor le und les verschmilzt es zu einem Wort: **à + le = au**, **à + les = aux**. À la und à l' bleiben, wie sie sind.\n\nDiese vier Formen ersetzen zum, zur, ins, in den, an den …",
      ),
      examples: [
        { fr: "Je vais au parc.", en: "I'm going to the park.", de: "Ich gehe in den Park." },
        { fr: "Tu vas à la gare ?", en: "Are you going to the station?", de: "Gehst du zum Bahnhof?" },
        { fr: "Le professeur parle aux élèves.", en: "The teacher is talking to the pupils.", de: "Der Lehrer spricht mit den Schülern." },
      ],
      table: {
        head: [tx("à + …", "à + …"), tx("becomes", "wird zu"), tx("example", "Beispiel")],
        rows: [
          ["le", "au", "au cinéma"],
          ["la", "à la", "à la plage"],
          ["l'", "à l'", "à l'école"],
          ["les", "aux", "aux élèves"],
        ],
      },
    },
    {
      title: tx("Asking the way", "Nach dem Weg fragen"),
      body: tx(
        "Start politely with **excusez-moi**, then ask **où est** + the place: excusez-moi, où est la gare ?\n\nThe answers: **à droite** (on the right), **à gauche** (on the left), **tout droit** (straight on). Careful: **droit** without an e means straight, **droite** with an e means right!",
        "Fang höflich mit **excusez-moi** an, dann frag **où est** + Ort: excusez-moi, où est la gare ?\n\nDie Antworten: **à droite** (rechts), **à gauche** (links), **tout droit** (geradeaus). Vorsicht: **droit** ohne e heißt gerade, **droite** mit e heißt rechts!",
      ),
      examples: [
        { fr: "Excusez-moi, où est le musée ?", en: "Excuse me, where is the museum?", de: "Entschuldigung, wo ist das Museum?" },
        { fr: "Allez tout droit, puis à gauche.", en: "Go straight on, then left.", de: "Gehen Sie geradeaus, dann links." },
        { fr: "C'est loin ? Non, c'est près.", en: "Is it far? No, it's close.", de: "Ist es weit? Nein, es ist nah." },
      ],
    },
  ],
};
