import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 8: sport, music and the days of the week; faire (all forms), jouer au / jouer de la. */
export const u08: Unit = {
  slug: "loisirs",
  n: 8,
  cefr: "A1",
  title: tx("Free time", "Freizeit"),
  goal: tx("Talk about sports, music and what you do at the weekend", "Über Sport, Musik und dein Wochenende sprechen"),
  emoji: "⚽",
  words: [
    { id: "je-fais", fr: "je fais", en: "I do", de: "ich mache", alt: { en: ["I make"], de: ["ich tue"] }, kind: "verb", note: tx("From faire: to do and to make. One verb for both!", "Von faire: machen und tun.") },
    { id: "tu-fais", fr: "tu fais", en: "you do", de: "du machst", alt: { en: ["you make"] }, kind: "verb" },
    { id: "sport", fr: "le sport", en: "sport", de: "der Sport", alt: { en: ["sports"] }, g: "m", kind: "noun", emoji: "🏅", note: tx("Faire du sport: to do sport.", "Faire du sport: Sport machen.") },
    { id: "velo", fr: "le vélo", en: "the bike", de: "das Fahrrad", alt: { en: ["the bicycle"], de: ["das Rad"] }, g: "m", kind: "noun", emoji: "🚲", note: tx("Faire du vélo: to ride a bike, to go cycling.", "Faire du vélo: Fahrrad fahren.") },
    { id: "musique", fr: "la musique", en: "music", de: "die Musik", g: "f", kind: "noun", emoji: "🎵" },
    { id: "foot", fr: "le foot", en: "football", de: "der Fußball", alt: { en: ["soccer"] }, g: "m", kind: "noun", emoji: "⚽", note: tx("Short for le football. Jouer au foot: to play football.", "Kurz für le football. Jouer au foot: Fußball spielen.") },
    { id: "je-joue", fr: "je joue", en: "I play", de: "ich spiele", alt: { en: ["I am playing"] }, kind: "verb", note: tx("Jouer au for sports and games, jouer de la / du for instruments.", "Jouer au für Sport und Spiele, jouer de la / du für Instrumente.") },
    { id: "il-fait", fr: "il fait", en: "he does", de: "er macht", alt: { en: ["he makes"] }, kind: "verb", note: tx("Elle fait: she does. With a t, like il est.", "Elle fait: sie macht. Mit t, wie il est.") },
    { id: "guitare", fr: "la guitare", en: "the guitar", de: "die Gitarre", g: "f", kind: "noun", emoji: "🎸" },
    { id: "piano", fr: "le piano", en: "the piano", de: "das Klavier", g: "m", kind: "noun", emoji: "🎹" },
    { id: "tennis", fr: "le tennis", en: "tennis", de: "das Tennis", g: "m", kind: "noun", emoji: "🎾" },
    { id: "nous-faisons", fr: "nous faisons", en: "we do", de: "wir machen", alt: { en: ["we make"] }, kind: "verb", note: tx("Written fais-, but it sounds like «fe»: nous faisons.", "Geschrieben fais-, aber es klingt wie „fe“: nous faisons.") },
    { id: "vous-faites", fr: "vous faites", en: "you do (plural / polite)", de: "ihr macht / Sie machen", kind: "verb", note: tx("Never «faisez»! Vous faites, like vous êtes.", "Nie „faisez“! Vous faites, wie vous êtes.") },
    { id: "ils-font", fr: "ils font", en: "they do", de: "sie machen", alt: { en: ["they make"] }, kind: "verb", note: tx("Like ils sont, ils ont, ils vont: -ont.", "Wie ils sont, ils ont, ils vont: -ont.") },
    { id: "nager", fr: "nager", en: "to swim", de: "schwimmen", kind: "verb", note: tx("The whole verb, as in the dictionary. J'aime nager: I like swimming.", "Das ganze Verb, wie im Wörterbuch. J'aime nager: Ich schwimme gern.") },
    { id: "danser", fr: "danser", en: "to dance", de: "tanzen", kind: "verb", emoji: "💃" },
    { id: "lundi", fr: "lundi", en: "Monday", de: "Montag", kind: "word", note: tx("Lundi comes from la lune, the moon: Monday is moon day in English and German too.", "Lundi kommt von la lune, dem Mond: Auch der Montag ist der Tag des Mondes.") },
    { id: "mardi", fr: "mardi", en: "Tuesday", de: "Dienstag", kind: "word", note: tx("Days are written small in French: mardi, not Mardi.", "Wochentage schreibt man klein: mardi, nicht Mardi.") },
    { id: "mercredi", fr: "mercredi", en: "Wednesday", de: "Mittwoch", kind: "word", note: tx("Many French pupils have Wednesday afternoon off!", "Viele französische Schüler haben am Mittwochnachmittag frei!") },
    { id: "jeudi", fr: "jeudi", en: "Thursday", de: "Donnerstag", kind: "word" },
    { id: "vendredi", fr: "vendredi", en: "Friday", de: "Freitag", kind: "word" },
    { id: "samedi", fr: "samedi", en: "Saturday", de: "Samstag", alt: { de: ["Sonnabend"] }, kind: "word" },
    { id: "dimanche", fr: "dimanche", en: "Sunday", de: "Sonntag", kind: "word" },
    { id: "week-end", fr: "le week-end", en: "the weekend", de: "das Wochenende", g: "m", kind: "noun", note: tx("Borrowed from English, with a hyphen. Le week-end: at the weekend.", "Aus dem Englischen, mit Bindestrich. Le week-end: am Wochenende.") },
  ],
  gloss: [
    { fr: "fais", en: "do / make", de: "mache / machst" },
    { fr: "fait", en: "does / makes", de: "macht" },
    { fr: "font", en: "do / make (they)", de: "machen (sie)" },
    { fr: "joue", en: "play / plays", de: "spiele / spielt" },
    { fr: "joues", en: "play (you)", de: "spielst" },
    { fr: "jouent", en: "play (they)", de: "spielen (sie)" },
    { fr: "danse", en: "dance / dances", de: "tanze / tanzt" },
    { fr: "aimons", en: "like (we)", de: "mögen (wir)" },
    { fr: "qu'est-ce que", en: "what", de: "was" },
    { fr: "super", en: "great", de: "super" },
    { fr: "rien", en: "nothing", de: "nichts" },
    { fr: "après", en: "afterwards", de: "danach" },
  ],
  lessons: [
    { title: tx("Sport and music", "Sport und Musik"), words: ["je-fais", "tu-fais", "sport", "velo", "musique", "foot"] },
    { title: tx("I play…", "Ich spiele …"), words: ["je-joue", "il-fait", "guitare", "piano", "tennis"] },
    { title: tx("Swimming and dancing", "Schwimmen und tanzen"), words: ["nous-faisons", "vous-faites", "ils-font", "nager", "danser"] },
    { title: tx("The school week", "Die Schulwoche"), words: ["lundi", "mardi", "mercredi", "jeudi", "vendredi"] },
    { title: tx("The weekend", "Das Wochenende"), words: ["samedi", "dimanche", "week-end"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u08.01", lesson: 1, fr: "Je fais du sport.", en: "I do sport.", de: "Ich mache Sport.", alt: { en: ["I do sports.", "I play sport.", "I play sports.", "I am doing sport."], de: ["Ich treibe Sport."] } },
    { id: "u08.02", lesson: 1, fr: "Tu fais du vélo ?", en: "Do you ride a bike?", de: "Fährst du Fahrrad?", alt: { fr: ["Est-ce que tu fais du vélo ?", "Fais-tu du vélo ?", "Vous faites du vélo ?", "Est-ce que vous faites du vélo ?", "Faites-vous du vélo ?"], en: ["Do you cycle?", "Do you go cycling?", "Do you ride a bicycle?", "Are you cycling?", "Are you riding a bike?"], de: ["Fährst du Rad?", "Du fährst Fahrrad?"] } },
    { id: "u08.03", lesson: 1, fr: "Je fais de la musique.", en: "I make music.", de: "Ich mache Musik.", alt: { en: ["I play music.", "I do music.", "I am making music."] } },
    { id: "u08.04", lesson: 1, fr: "J'aime le foot.", en: "I like football.", de: "Ich mag Fußball.", alt: { en: ["I love football.", "I like soccer.", "I love soccer."], de: ["Ich liebe Fußball."] } },
    { id: "u08.05", lesson: 1, fr: "Tu fais du sport avec Hugo ?", en: "Do you do sport with Hugo?", de: "Machst du mit Hugo Sport?", alt: { fr: ["Est-ce que tu fais du sport avec Hugo ?", "Fais-tu du sport avec Hugo ?", "Vous faites du sport avec Hugo ?", "Est-ce que vous faites du sport avec Hugo ?"], en: ["Are you doing sport with Hugo?", "Do you do sports with Hugo?", "Are you doing sports with Hugo?", "Do you play sport with Hugo?", "Do you play sports with Hugo?"], de: ["Machst du Sport mit Hugo?", "Treibst du mit Hugo Sport?", "Treibst du Sport mit Hugo?"] } },
    { id: "u08.06", lesson: 1, fr: "Je ne fais pas de sport.", en: "I don't do any sport.", de: "Ich mache keinen Sport.", alt: { en: ["I don't do sport.", "I don't do sports.", "I don't do any sports.", "I don't play sport.", "I don't play any sport.", "I am not doing any sport."], de: ["Ich treibe keinen Sport."] } },
    { id: "u08.07", lesson: 1, fr: "La musique, c'est super !", en: "Music is great!", de: "Musik ist super!", alt: { fr: ["C'est super, la musique !"], en: ["Music is super!", "Music is brilliant!"], de: ["Musik ist toll!", "Musik ist klasse!"] } },
    // Lesson 2
    { id: "u08.08", lesson: 2, fr: "Je joue au foot.", en: "I play football.", de: "Ich spiele Fußball.", alt: { en: ["I am playing football.", "I play soccer.", "I am playing soccer."] } },
    { id: "u08.09", lesson: 2, fr: "Je joue de la guitare.", en: "I play the guitar.", de: "Ich spiele Gitarre.", alt: { en: ["I play guitar.", "I am playing the guitar.", "I am playing guitar."] } },
    { id: "u08.10", lesson: 2, fr: "Hugo joue du piano.", en: "Hugo plays the piano.", de: "Hugo spielt Klavier.", alt: { en: ["Hugo plays piano.", "Hugo is playing the piano.", "Hugo is playing piano."] } },
    { id: "u08.11", lesson: 2, fr: "Tu joues au tennis ?", en: "Do you play tennis?", de: "Spielst du Tennis?", alt: { fr: ["Est-ce que tu joues au tennis ?", "Joues-tu au tennis ?", "Vous jouez au tennis ?", "Est-ce que vous jouez au tennis ?", "Jouez-vous au tennis ?"], en: ["Are you playing tennis?", "You play tennis?"], de: ["Du spielst Tennis?"] } },
    { id: "u08.12", lesson: 2, fr: "Il fait du vélo avec son chien.", en: "He's cycling with his dog.", de: "Er fährt mit seinem Hund Fahrrad.", alt: { en: ["He is riding his bike with his dog.", "He is riding a bike with his dog.", "He rides his bike with his dog.", "He rides a bike with his dog.", "He goes cycling with his dog.", "He cycles with his dog."], de: ["Er fährt Fahrrad mit seinem Hund.", "Er fährt mit seinem Hund Rad.", "Er fährt Rad mit seinem Hund."] } },
    { id: "u08.13", lesson: 2, fr: "Qu'est-ce que tu fais ?", en: "What are you doing?", de: "Was machst du?", alt: { fr: ["Tu fais quoi ?", "Que fais-tu ?", "Qu'est-ce que vous faites ?", "Vous faites quoi ?", "Que faites-vous ?"], en: ["What do you do?"] } },
    { id: "u08.14", lesson: 2, fr: "Léa joue au foot avec Hugo.", en: "Léa plays football with Hugo.", de: "Léa spielt mit Hugo Fußball.", alt: { en: ["Léa is playing football with Hugo.", "Léa plays soccer with Hugo.", "Léa is playing soccer with Hugo."], de: ["Léa spielt Fußball mit Hugo."] } },
    // Lesson 3
    { id: "u08.15", lesson: 3, fr: "Nous faisons de la musique.", en: "We make music.", de: "Wir machen Musik.", alt: { en: ["We play music.", "We do music.", "We are making music."] } },
    { id: "u08.16", lesson: 3, fr: "Vous faites du sport ?", en: "Do you do any sport?", de: "Macht ihr Sport?", alt: { fr: ["Est-ce que vous faites du sport ?", "Faites-vous du sport ?", "Tu fais du sport ?", "Est-ce que tu fais du sport ?", "Fais-tu du sport ?"], en: ["Do you do sport?", "Do you do sports?", "Do you do any sports?", "Do you play sport?", "Do you play any sport?", "Do you play sports?"], de: ["Machen Sie Sport?", "Treibt ihr Sport?", "Treiben Sie Sport?"] } },
    { id: "u08.17", lesson: 3, fr: "Ils font du vélo.", en: "They're cycling.", de: "Sie fahren Fahrrad.", alt: { fr: ["Elles font du vélo."], en: ["They are riding their bikes.", "They are riding bikes.", "They ride bikes.", "They go cycling.", "They are going cycling.", "They cycle."], de: ["Sie fahren Rad."] } },
    { id: "u08.18", lesson: 3, fr: "J'aime nager.", en: "I like swimming.", de: "Ich schwimme gern.", alt: { en: ["I like to swim.", "I love swimming.", "I love to swim."], de: ["Ich schwimme gerne."] } },
    { id: "u08.19", lesson: 3, fr: "Tu aimes danser ?", en: "Do you like dancing?", de: "Tanzt du gern?", alt: { fr: ["Est-ce que tu aimes danser ?", "Aimes-tu danser ?", "Vous aimez danser ?", "Est-ce que vous aimez danser ?", "Aimez-vous danser ?"], en: ["Do you like to dance?", "Do you love dancing?", "Do you love to dance?"], de: ["Tanzt du gerne?", "Magst du tanzen?"] } },
    { id: "u08.20", lesson: 3, fr: "Nous aimons nager et danser.", en: "We like swimming and dancing.", de: "Wir schwimmen und tanzen gern.", alt: { en: ["We like to swim and dance.", "We like to swim and to dance.", "We love swimming and dancing.", "We love to swim and dance."], de: ["Wir schwimmen und tanzen gerne."] } },
    { id: "u08.21", lesson: 3, fr: "Ils ne font pas de sport.", en: "They don't do any sport.", de: "Sie machen keinen Sport.", alt: { fr: ["Elles ne font pas de sport."], en: ["They don't do sport.", "They don't do sports.", "They don't do any sports.", "They don't play sport.", "They don't play any sport."], de: ["Sie treiben keinen Sport."] } },
    // Lesson 4
    { id: "u08.22", lesson: 4, fr: "Lundi, je joue au foot.", en: "On Monday I'm playing football.", de: "Am Montag spiele ich Fußball.", alt: { fr: ["Je joue au foot lundi."], en: ["On Monday I play football.", "I am playing football on Monday.", "I play football on Monday.", "On Monday I am playing soccer.", "On Monday I play soccer.", "I am playing soccer on Monday."], de: ["Montag spiele ich Fußball.", "Ich spiele am Montag Fußball."] } },
    { id: "u08.23", lesson: 4, fr: "Le mardi, je fais du vélo.", en: "On Tuesdays I go cycling.", de: "Dienstags fahre ich Fahrrad.", alt: { fr: ["Je fais du vélo le mardi."], en: ["On Tuesdays I ride my bike.", "On Tuesdays I ride a bike.", "On Tuesdays I cycle.", "I go cycling on Tuesdays.", "I ride my bike on Tuesdays.", "I cycle on Tuesdays.", "Every Tuesday I go cycling."], de: ["Dienstags fahre ich Rad.", "Ich fahre dienstags Fahrrad.", "Ich fahre dienstags Rad.", "Jeden Dienstag fahre ich Fahrrad."] } },
    { id: "u08.24", lesson: 4, fr: "Mercredi, nous allons à la piscine.", en: "On Wednesday we're going to the swimming pool.", de: "Am Mittwoch gehen wir ins Schwimmbad.", alt: { fr: ["Nous allons à la piscine mercredi."], en: ["On Wednesday we are going to the pool.", "We are going to the swimming pool on Wednesday.", "We are going to the pool on Wednesday.", "On Wednesday we go to the swimming pool.", "On Wednesday we go to the pool."], de: ["Mittwoch gehen wir ins Schwimmbad.", "Wir gehen am Mittwoch ins Schwimmbad."] } },
    { id: "u08.25", lesson: 4, fr: "Le jeudi, Hugo joue au tennis.", en: "On Thursdays Hugo plays tennis.", de: "Donnerstags spielt Hugo Tennis.", alt: { fr: ["Hugo joue au tennis le jeudi."], en: ["Hugo plays tennis on Thursdays.", "Every Thursday Hugo plays tennis."], de: ["Hugo spielt donnerstags Tennis.", "Jeden Donnerstag spielt Hugo Tennis."] } },
    { id: "u08.26", lesson: 4, fr: "Vendredi, Léa danse avec Blob.", en: "On Friday Léa is dancing with Blob.", de: "Am Freitag tanzt Léa mit Blob.", alt: { fr: ["Léa danse avec Blob vendredi."], en: ["On Friday Léa dances with Blob.", "Léa is dancing with Blob on Friday.", "Léa dances with Blob on Friday."], de: ["Freitag tanzt Léa mit Blob.", "Léa tanzt am Freitag mit Blob."] } },
    { id: "u08.27", lesson: 4, fr: "Tu fais quoi lundi ?", en: "What are you doing on Monday?", de: "Was machst du am Montag?", alt: { fr: ["Qu'est-ce que tu fais lundi ?", "Que fais-tu lundi ?", "Vous faites quoi lundi ?", "Qu'est-ce que vous faites lundi ?", "Que faites-vous lundi ?"], en: ["What are you doing Monday?", "What do you do on Monday?"], de: ["Was machst du Montag?"] } },
    { id: "u08.28", lesson: 4, fr: "Le mercredi, je joue de la guitare.", en: "On Wednesdays I play the guitar.", de: "Mittwochs spiele ich Gitarre.", alt: { fr: ["Je joue de la guitare le mercredi."], en: ["On Wednesdays I play guitar.", "I play the guitar on Wednesdays.", "I play guitar on Wednesdays.", "Every Wednesday I play the guitar."], de: ["Ich spiele mittwochs Gitarre.", "Jeden Mittwoch spiele ich Gitarre."] } },
    // Lesson 5
    { id: "u08.29", lesson: 5, fr: "Le week-end, je fais du vélo.", en: "At the weekend I go cycling.", de: "Am Wochenende fahre ich Fahrrad.", alt: { fr: ["Je fais du vélo le week-end."], en: ["At weekends I go cycling.", "On weekends I go cycling.", "On the weekend I go cycling.", "At the weekend I ride my bike.", "At the weekend I cycle.", "I go cycling at the weekend.", "I go cycling at weekends.", "I go cycling on weekends.", "I ride my bike at the weekend."], de: ["Am Wochenende fahre ich Rad.", "Ich fahre am Wochenende Fahrrad.", "Ich fahre am Wochenende Rad."] } },
    { id: "u08.30", lesson: 5, fr: "Samedi, nous allons au cinéma.", en: "On Saturday we're going to the cinema.", de: "Am Samstag gehen wir ins Kino.", alt: { fr: ["Nous allons au cinéma samedi."], en: ["We are going to the cinema on Saturday.", "On Saturday we go to the cinema.", "On Saturday we are going to the movies.", "We are going to the movies on Saturday."], de: ["Samstag gehen wir ins Kino.", "Wir gehen am Samstag ins Kino.", "Am Sonnabend gehen wir ins Kino."] } },
    { id: "u08.31", lesson: 5, fr: "Le dimanche, je ne fais rien.", en: "On Sundays I don't do anything.", de: "Sonntags mache ich nichts.", alt: { fr: ["Je ne fais rien le dimanche."], en: ["On Sundays I do nothing.", "I do nothing on Sundays.", "I don't do anything on Sundays."], de: ["Ich mache sonntags nichts.", "Sonntags tue ich nichts."] } },
    { id: "u08.32", lesson: 5, fr: "Tu fais quoi ce week-end ?", en: "What are you doing this weekend?", de: "Was machst du dieses Wochenende?", alt: { fr: ["Qu'est-ce que tu fais ce week-end ?", "Que fais-tu ce week-end ?", "Vous faites quoi ce week-end ?", "Qu'est-ce que vous faites ce week-end ?", "Que faites-vous ce week-end ?"], en: ["What do you do this weekend?"], de: ["Was machst du am Wochenende?", "Was machst du an diesem Wochenende?"] } },
    { id: "u08.33", lesson: 5, fr: "Dimanche, Léa et Hugo jouent au tennis.", en: "On Sunday Léa and Hugo are playing tennis.", de: "Am Sonntag spielen Léa und Hugo Tennis.", alt: { fr: ["Léa et Hugo jouent au tennis dimanche."], en: ["On Sunday Léa and Hugo play tennis.", "Léa and Hugo are playing tennis on Sunday.", "Léa and Hugo play tennis on Sunday."], de: ["Sonntag spielen Léa und Hugo Tennis.", "Léa und Hugo spielen am Sonntag Tennis."] } },
    { id: "u08.34", lesson: 5, fr: "J'aime le samedi !", en: "I love Saturdays!", de: "Ich liebe Samstage!", alt: { en: ["I like Saturdays!", "I love Saturday!", "I like Saturday!"], de: ["Ich mag Samstage!", "Ich mag den Samstag!", "Ich liebe den Samstag!"] } },
  ],
  drills: [
    { id: "u08.d1", lesson: 1, fr: "Je fais ___ sport.", options: ["du", "de la", "de l'"], answer: 0, en: "I do sport.", de: "Ich mache Sport.", why: tx("**Sport** is masculine: faire **du** sport (de + le = du).", "**Sport** ist männlich: faire **du** sport (de + le = du).") },
    { id: "u08.d2", lesson: 1, fr: "Tu fais ___ musique ?", options: ["de la", "du", "des"], answer: 0, en: "Do you make music?", de: "Machst du Musik?", why: tx("**Musique** is feminine: faire **de la** musique.", "**Musique** ist weiblich: faire **de la** musique.") },
    { id: "u08.d3", lesson: 1, fr: "Je ne fais pas ___ sport.", options: ["de", "du", "le"], answer: 0, en: "I don't do any sport.", de: "Ich mache keinen Sport.", why: tx("After ne … pas, du and de la become just **de**: je ne fais pas **de** sport.", "Nach ne … pas werden du und de la einfach zu **de**: je ne fais pas **de** sport.") },
    { id: "u08.d4", lesson: 2, fr: "Je joue ___ foot.", options: ["au", "du", "de la"], answer: 0, en: "I play football.", de: "Ich spiele Fußball.", why: tx("Sports and games: jouer **à**, and à + le = **au**: au foot, au tennis.", "Sport und Spiele: jouer **à**, und à + le = **au**: au foot, au tennis.") },
    { id: "u08.d5", lesson: 2, fr: "Hugo joue ___ guitare.", options: ["de la", "à la", "au"], answer: 0, en: "Hugo plays the guitar.", de: "Hugo spielt Gitarre.", why: tx("Instruments: jouer **de**: **de la** guitare, **du** piano.", "Instrumente: jouer **de**: **de la** guitare, **du** piano.") },
    { id: "u08.d6", lesson: 2, fr: "Léa ___ du vélo.", options: ["fait", "fais", "faites"], answer: 0, en: "Léa rides a bike.", de: "Léa fährt Fahrrad.", why: tx("With il / elle (Léa): **fait**, with a t.", "Mit il / elle (Léa): **fait**, mit t.") },
    { id: "u08.d7", lesson: 3, fr: "Nous ___ de la musique.", options: ["faisons", "faites", "font"], answer: 0, en: "We make music.", de: "Wir machen Musik.", why: tx("With **nous**: nous **faisons**, ending in -ons like nous parlons.", "Mit **nous**: nous **faisons**, mit -ons wie nous parlons.") },
    { id: "u08.d8", lesson: 3, fr: "Vous ___ du sport ?", options: ["faites", "faisons", "faisez"], answer: 0, en: "Do you do any sport?", de: "Macht ihr Sport?", why: tx("Faire is irregular: vous **faites**. «Faisez» doesn't exist!", "Faire ist unregelmäßig: vous **faites**. „Faisez“ gibt es nicht!") },
    { id: "u08.d9", lesson: 3, fr: "Ils ___ du vélo.", options: ["font", "fait", "faisent"], answer: 0, en: "They're cycling.", de: "Sie fahren Fahrrad.", why: tx("They: ils **font**. Like ils sont, ils ont, ils vont.", "Sie (Plural): ils **font**. Wie ils sont, ils ont, ils vont.") },
    { id: "u08.d10", lesson: 3, fr: "J'aime ___.", options: ["nager", "nage", "nages"], answer: 0, en: "I like swimming.", de: "Ich schwimme gern.", why: tx("After j'aime, the verb stays whole: j'aime **nager**, j'aime danser.", "Nach j'aime bleibt das Verb ganz (Infinitiv): j'aime **nager**, j'aime danser.") },
    { id: "u08.d11", lesson: 4, fr: "___ lundi, je joue au foot.", options: ["Le", "Au", "En"], answer: 0, en: "On Mondays I play football.", de: "Montags spiele ich Fußball.", why: tx("Every Monday: **le** lundi. Just lundi means this Monday. And no word for «on»!", "Jeden Montag (montags): **le** lundi. Nur lundi heißt diesen Montag. Und kein Wort für „am“!") },
    { id: "u08.d12", lesson: 5, fr: "Le dimanche, je ne fais ___.", options: ["rien", "pas", "de"], answer: 0, en: "On Sundays I don't do anything.", de: "Sonntags mache ich nichts.", why: tx("Nothing is **ne … rien**: it goes around the verb, just like ne … pas.", "Nichts heißt **ne … rien**: Es steht um das Verb herum, genau wie ne … pas.") },
  ],
  dialogue: {
    id: "u08.dialogue",
    lesson: 5,
    title: tx("Blob's busy weekend", "Blobs volles Wochenende"),
    lines: [
      { who: "lea", fr: "Blob, qu'est-ce que tu fais ce week-end ?", en: "Blob, what are you doing this weekend?", de: "Blob, was machst du dieses Wochenende?" },
      { who: "blob", fr: "Samedi, je joue au foot avec Hugo.", en: "On Saturday I'm playing football with Hugo.", de: "Am Samstag spiele ich mit Hugo Fußball." },
      { who: "hugo", fr: "Et après, nous allons à la piscine !", en: "And afterwards we're going to the swimming pool!", de: "Und danach gehen wir ins Schwimmbad!" },
      { who: "lea", fr: "Super ! Et dimanche ?", en: "Great! And on Sunday?", de: "Super! Und am Sonntag?" },
      { who: "blob", fr: "Dimanche, je fais du vélo, je danse et je joue de la guitare !", en: "On Sunday I'm cycling, dancing and playing the guitar!", de: "Am Sonntag fahre ich Fahrrad, tanze und spiele Gitarre!" },
      { who: "hugo", fr: "Tu joues de la guitare, Blob ?", en: "You play the guitar, Blob?", de: "Du spielst Gitarre, Blob?" },
      { who: "blob", fr: "Euh… non. Mais j'aime la musique !", en: "Er… no. But I love music!", de: "Äh … nein. Aber ich liebe Musik!" },
      { who: "lea", fr: "Et lundi ?", en: "And on Monday?", de: "Und am Montag?" },
      { who: "blob", fr: "Lundi, je ne fais rien. Je suis très fatigué !", en: "On Monday I'm doing nothing. I'm very tired!", de: "Am Montag mache ich nichts. Ich bin sehr müde!" },
    ],
    questions: [
      { q: tx("What does Blob do on Saturday?", "Was macht Blob am Samstag?"), options: [tx("He plays football with Hugo.", "Er spielt mit Hugo Fußball."), tx("He plays the guitar.", "Er spielt Gitarre."), tx("He does nothing.", "Er macht nichts.")], answer: 0 },
      { q: tx("Where do Blob and Hugo go after football?", "Wohin gehen Blob und Hugo nach dem Fußball?"), options: [tx("To the swimming pool", "Ins Schwimmbad"), tx("To the cinema", "Ins Kino"), tx("To the beach", "An den Strand")], answer: 0 },
      { q: tx("Does Blob play the guitar?", "Spielt Blob Gitarre?"), options: [tx("No, but he loves music.", "Nein, aber er liebt Musik."), tx("Yes, very well.", "Ja, sehr gut."), tx("Yes, on Mondays.", "Ja, montags.")], answer: 0 },
    ],
  },
  tips: [
    {
      title: tx("Faire: to do, to make", "Faire: machen, tun"),
      body: tx(
        "**Faire** means to do and to make. It's irregular: **vous faites** (never «faisez») and **ils font**.\n\nFor many activities French says **faire du / de la**: faire du sport, faire du vélo (to ride a bike), faire de la musique. After ne … pas it's just **de**: je ne fais pas **de** sport.",
        "**Faire** heißt machen und tun. Es ist unregelmäßig: **vous faites** (nie „faisez“) und **ils font**.\n\nFür viele Aktivitäten sagt man **faire du / de la**: faire du sport, faire du vélo (Fahrrad fahren), faire de la musique. Nach ne … pas nur **de**: je ne fais pas **de** sport.",
      ),
      examples: [
        { fr: "Je fais du sport.", en: "I do sport.", de: "Ich mache Sport." },
        { fr: "Vous faites de la musique ?", en: "Do you make music?", de: "Macht ihr Musik?" },
        { fr: "Ils ne font pas de vélo.", en: "They don't ride bikes.", de: "Sie fahren nicht Fahrrad." },
      ],
      table: {
        head: [tx("person", "Person"), "faire"],
        rows: [
          [tx("I", "ich"), "je fais"],
          [tx("you", "du"), "tu fais"],
          [tx("he / she", "er / sie"), "il / elle fait"],
          [tx("we", "wir"), "nous faisons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous faites"],
          [tx("they", "sie"), "ils / elles font"],
        ],
      },
    },
    {
      title: tx("Jouer au foot, jouer de la guitare", "Jouer au foot, jouer de la guitare"),
      body: tx(
        "Two kinds of playing. Sports and games: **jouer à**, so **au** foot, **au** tennis (à + le = au).\n\nInstruments: **jouer de**, so **de la** guitare, **du** piano (de + le = du). English and German just say «play».",
        "Zwei Arten von Spielen. Sport und Spiele: **jouer à**, also **au** foot, **au** tennis (à + le = au).\n\nInstrumente: **jouer de**, also **de la** guitare, **du** piano (de + le = du). Im Deutschen heißt beides einfach „spielen“.",
      ),
      examples: [
        { fr: "Je joue au foot.", en: "I play football.", de: "Ich spiele Fußball." },
        { fr: "Hugo joue du piano.", en: "Hugo plays the piano.", de: "Hugo spielt Klavier." },
        { fr: "Tu joues de la guitare ?", en: "Do you play the guitar?", de: "Spielst du Gitarre?" },
      ],
    },
    {
      title: tx("Days of the week", "Die Wochentage"),
      body: tx(
        "The days are **masculine** and written **small**: lundi, mardi…\n\nThere's no word for «on»: **lundi** = on Monday (this Monday). With **le** it's every week: **le lundi** = on Mondays. The same for **le week-end**: at the weekend.",
        "Die Tage sind **männlich** und werden **klein** geschrieben: lundi, mardi …\n\nEs gibt kein Wort für „am“: **lundi** = am Montag (diesen Montag). Mit **le** ist es jede Woche: **le lundi** = montags. Genauso **le week-end**: am Wochenende.",
      ),
      examples: [
        { fr: "Lundi, je joue au foot.", en: "On Monday I'm playing football.", de: "Am Montag spiele ich Fußball." },
        { fr: "Le samedi, je fais du vélo.", en: "On Saturdays I go cycling.", de: "Samstags fahre ich Fahrrad." },
      ],
      table: {
        head: [tx("French", "Französisch"), tx("meaning", "Bedeutung")],
        rows: [
          ["lundi", tx("Monday", "Montag")],
          ["mardi", tx("Tuesday", "Dienstag")],
          ["mercredi", tx("Wednesday", "Mittwoch")],
          ["jeudi", tx("Thursday", "Donnerstag")],
          ["vendredi", tx("Friday", "Freitag")],
          ["samedi", tx("Saturday", "Samstag")],
          ["dimanche", tx("Sunday", "Sonntag")],
        ],
      },
    },
  ],
};
