import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 8: sport, music and the days of the week; faire (all forms), jouer au / jouer de la. */
export const u08: Unit = {
  slug: "loisirs",
  n: 8,
  cefr: "A1",
  title: tx("Free time", "Freizeit"),
  goal: tx("Talk about sports, music and what you do at the weekend", "Über Sport, Musik und dein Wochenende sprechen"),
  emoji: "⚽",
  words: [
    { id: "je-fais", fr: "je fais", en: "I do", de: "ich mache", alt: { en: ["I make"], de: ["ich tue"] }, kind: "verb", note: tx("From faire: to do and to make. One verb for both!", "Von faire: machen und tun.") },
    { id: "tu-fais", fr: "tu fais", en: "you do", de: "du machst", alt: { en: ["you make"] }, kind: "verb" },
    { id: "sport", fr: "le sport", en: "the sport", de: "der Sport", g: "m", kind: "noun", emoji: "🏅", note: tx("Faire du sport: to do sport.", "Faire du sport: Sport machen.") },
    { id: "velo", fr: "le vélo", en: "the bike", de: "das Fahrrad", alt: { en: ["the bicycle"], de: ["das Rad"] }, g: "m", kind: "noun", emoji: "🚲", note: tx("Faire du vélo: to ride a bike, to go cycling.", "Faire du vélo: Fahrrad fahren.") },
    { id: "musique", fr: "la musique", en: "the music", de: "die Musik", g: "f", kind: "noun", emoji: "🎵" },
    { id: "foot", fr: "le foot", en: "the football", de: "der Fußball", alt: { en: ["soccer"] }, g: "m", kind: "noun", emoji: "⚽", note: tx("Short for le football. Jouer au foot: to play football.", "Kurz für le football. Jouer au foot: Fußball spielen.") },
    { id: "je-joue", fr: "je joue", en: "I play", de: "ich spiele", alt: { en: ["I am playing"] }, kind: "verb", note: tx("Jouer au for sports and games, jouer de la / du for instruments.", "Jouer au für Sport und Spiele, jouer de la / du für Instrumente.") },
    { id: "il-fait", fr: "il fait", en: "he does", de: "er macht", alt: { en: ["he makes"] }, kind: "verb", note: tx("Elle fait: she does. With a t, like il est.", "Elle fait: sie macht. Mit t, wie il est.") },
    { id: "guitare", fr: "la guitare", en: "the guitar", de: "die Gitarre", g: "f", kind: "noun", emoji: "🎸" },
    { id: "piano", fr: "le piano", en: "the piano", de: "das Klavier", g: "m", kind: "noun", emoji: "🎹" },
    { id: "tennis", fr: "le tennis", en: "the tennis", de: "das Tennis", g: "m", kind: "noun", emoji: "🎾" },
    { id: "nous-faisons", fr: "nous faisons", en: "we do", de: "wir machen", alt: { en: ["we make"] }, kind: "verb", note: tx("Written fais-, but it sounds like «fe»: nous faisons.", "Geschrieben fais-, aber es klingt wie „fe“: nous faisons.") },
    { id: "vous-faites", fr: "vous faites", en: "you do (plural / polite)", de: "ihr macht / Sie machen", kind: "verb", note: tx("Never «faisez»! Vous faites, like vous êtes.", "Nie „faisez“! Vous faites, wie vous êtes.") },
    { id: "ils-font", fr: "ils font", en: "they do", de: "sie machen", alt: { en: ["they make"] }, kind: "verb", note: tx("Like ils sont, ils ont, ils vont: -ont.", "Wie ils sont, ils ont, ils vont: -ont.") },
    { id: "nager", fr: "nager", en: "to swim", de: "schwimmen", kind: "verb", note: tx("The whole verb, as in the dictionary. J'aime nager: I like swimming.", "Das ganze Verb, wie im Wörterbuch. J'aime nager: Ich schwimme gern.") },
    { id: "danser", fr: "danser", en: "to dance", de: "tanzen", kind: "verb", emoji: "💃" },
    { id: "lundi", fr: "lundi", en: "Monday", de: "Montag", kind: "word", note: tx("Lundi comes from la lune, the moon: Monday is moon day in English and German too.", "Lundi kommt von la lune, dem Mond: Auch der Montag ist der Tag des Mondes.") },
    { id: "mardi", fr: "mardi", en: "Tuesday", de: "Dienstag", kind: "word", note: tx("Days are written small in French: mardi, not Mardi.", "Wochentage schreibt man klein: mardi, nicht Mardi.") },
    { id: "mercredi", fr: "mercredi", en: "Wednesday", de: "Mittwoch", kind: "word", note: tx("Many French pupils have Wednesday afternoon off!", "Viele französische Schüler haben am Mittwochnachmittag frei!") },
    { id: "jeudi", fr: "jeudi", en: "Thursday", de: "Donnerstag", kind: "word" },
    { id: "vendredi", fr: "vendredi", en: "Friday", de: "Freitag", kind: "word" },
    { id: "samedi", fr: "samedi", en: "Saturday", de: "Samstag", alt: { de: ["Sonnabend"] }, kind: "word" },
    { id: "dimanche", fr: "dimanche", en: "Sunday", de: "Sonntag", kind: "word" },
    { id: "week-end", fr: "le week-end", en: "the weekend", de: "das Wochenende", g: "m", kind: "noun", note: tx("Borrowed from English, with a hyphen. Le week-end: at the weekend.", "Aus dem Englischen, mit Bindestrich. Le week-end: am Wochenende.") },
    { id: "il-fait-beau", fr: "il fait beau", en: "the weather is nice", de: "das Wetter ist schön", alt: { en: ["it's nice weather", "it's sunny"], de: ["es ist schönes Wetter"] }, kind: "phrase", emoji: "😎", note: tx("The weather uses faire: il fait beau, literally «it makes nice».", "Beim Wetter steht faire: il fait beau, wörtlich „es macht schön“.") },
    { id: "il-pleut", fr: "il pleut", en: "it's raining", de: "es regnet", alt: { en: ["it rains"] }, kind: "phrase", emoji: "🌧️", note: tx("Rain has a verb of its own: pleuvoir. Il pleut: it's raining.", "Regen hat ein eigenes Verb: pleuvoir. Il pleut: Es regnet.") },
    { id: "jeux-video", fr: "les jeux vidéo", en: "video games", de: "die Videospiele", alt: { en: ["the video games", "computer games"], de: ["Videospiele", "die Computerspiele"] }, g: "m", kind: "noun", emoji: "🎮", note: tx("Un jeu vidéo, des jeux vidéo: the plural takes an x. Jouer aux jeux vidéo: to play video games.", "Un jeu vidéo, des jeux vidéo: Der Plural bekommt ein x. Jouer aux jeux vidéo: Videospiele spielen.") },
  ],
  gloss: [
    { fr: "fais", en: "do / make", de: "mache / machst" },
    { fr: "fait", en: "does / makes", de: "macht" },
    { fr: "font", en: "do / make (they)", de: "machen (sie)" },
    { fr: "joue", en: "play / plays", de: "spiele / spielt" },
    { fr: "joues", en: "play (you)", de: "spielst" },
    { fr: "jouent", en: "play (they)", de: "spielen (sie)" },
    { fr: "danse", en: "dance / dances", de: "tanze / tanzt" },
    { fr: "aimons", en: "like (we)", de: "mögen (wir)" },
    { fr: "qu'est-ce que", en: "what", de: "was" },
    { fr: "super", en: "great", de: "super" },
    { fr: "rien", en: "nothing", de: "nichts" },
    { fr: "après", en: "afterwards", de: "danach" },
    { fr: "pleut", en: "rains", de: "regnet" },
    { fr: "beau", en: "nice / beautiful", de: "schön" },
    { fr: "jouons", en: "play (we)", de: "spielen (wir)" },
    { fr: "jouez", en: "play (you, plural / polite)", de: "spielt / spielen (Sie)" },
    { fr: "dansons", en: "dance (we)", de: "tanzen (wir)" },
    { fr: "amis", en: "friends", de: "Freunde" },
  ],
  lessons: [
    { title: tx("Sport and music", "Sport und Musik"), words: ["je-fais", "tu-fais", "sport", "velo", "musique", "foot"] },
    { title: tx("I play…", "Ich spiele …"), words: ["je-joue", "il-fait", "guitare", "piano", "tennis"] },
    { title: tx("Swimming and dancing", "Schwimmen und tanzen"), words: ["nous-faisons", "vous-faites", "ils-font", "nager", "danser"] },
    { title: tx("The school week", "Die Schulwoche"), words: ["lundi", "mardi", "mercredi", "jeudi", "vendredi"] },
    { title: tx("The weekend", "Das Wochenende"), words: ["samedi", "dimanche", "week-end"] },
    { title: tx("Sun or rain?", "Sonne oder Regen?"), words: ["il-fait-beau", "il-pleut"] },
    { title: tx("Video games", "Videospiele"), words: ["jeux-video"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u08.01", lesson: 1, fr: "Je fais du sport.", en: "I do sport.", de: "Ich mache Sport.", alt: { en: ["I do sports.", "I play sport.", "I play sports.", "I am doing sport."], de: ["Ich treibe Sport."] } },
    { id: "u08.02", lesson: 1, fr: "Tu fais du vélo ?", en: "Do you ride a bike?", de: "Fährst du Fahrrad?", alt: { fr: ["Est-ce que tu fais du vélo ?", "Fais-tu du vélo ?", "Vous faites du vélo ?", "Est-ce que vous faites du vélo ?", "Faites-vous du vélo ?"], en: ["Do you cycle?", "Do you go cycling?", "Do you ride a bicycle?", "Are you cycling?", "Are you riding a bike?"], de: ["Fährst du Rad?", "Du fährst Fahrrad?"] } },
    { id: "u08.03", lesson: 1, fr: "Je fais de la musique.", en: "I make music.", de: "Ich mache Musik.", alt: { en: ["I play music.", "I do music.", "I am making music."] } },
    { id: "u08.04", lesson: 1, fr: "J'aime le foot.", en: "I like football.", de: "Ich mag Fußball.", alt: { en: ["I love football.", "I like soccer.", "I love soccer."], de: ["Ich liebe Fußball."] } },
    { id: "u08.05", lesson: 1, fr: "Tu fais du sport avec Hugo ?", en: "Do you do sport with Hugo?", de: "Machst du mit Hugo Sport?", alt: { fr: ["Est-ce que tu fais du sport avec Hugo ?", "Fais-tu du sport avec Hugo ?", "Vous faites du sport avec Hugo ?", "Est-ce que vous faites du sport avec Hugo ?"], en: ["Are you doing sport with Hugo?", "Do you do sports with Hugo?", "Are you doing sports with Hugo?", "Do you play sport with Hugo?", "Do you play sports with Hugo?"], de: ["Machst du Sport mit Hugo?", "Treibst du mit Hugo Sport?", "Treibst du Sport mit Hugo?"] } },
    { id: "u08.06", lesson: 1, fr: "Je ne fais pas de sport.", en: "I don't do any sport.", de: "Ich mache keinen Sport.", alt: { en: ["I don't do sport.", "I don't do sports.", "I don't do any sports.", "I don't play sport.", "I don't play any sport.", "I am not doing any sport."], de: ["Ich treibe keinen Sport."] } },
    { id: "u08.07", lesson: 1, fr: "La musique, c'est super !", en: "Music is great!", de: "Musik ist super!", alt: { fr: ["C'est super, la musique !"], en: ["Music is super!", "Music is brilliant!"], de: ["Musik ist toll!", "Musik ist klasse!"] } },
    // Lesson 2
    { id: "u08.08", lesson: 2, fr: "Je joue au foot.", en: "I play football.", de: "Ich spiele Fußball.", alt: { en: ["I am playing football.", "I play soccer.", "I am playing soccer."] } },
    { id: "u08.09", lesson: 2, fr: "Je joue de la guitare.", en: "I play the guitar.", de: "Ich spiele Gitarre.", alt: { en: ["I play guitar.", "I am playing the guitar.", "I am playing guitar."] } },
    { id: "u08.10", lesson: 2, fr: "Hugo joue du piano.", en: "Hugo plays the piano.", de: "Hugo spielt Klavier.", alt: { en: ["Hugo plays piano.", "Hugo is playing the piano.", "Hugo is playing piano."] } },
    { id: "u08.11", lesson: 2, fr: "Tu joues au tennis ?", en: "Do you play tennis?", de: "Spielst du Tennis?", alt: { fr: ["Est-ce que tu joues au tennis ?", "Joues-tu au tennis ?", "Vous jouez au tennis ?", "Est-ce que vous jouez au tennis ?", "Jouez-vous au tennis ?"], en: ["Are you playing tennis?", "You play tennis?"], de: ["Du spielst Tennis?"] } },
    { id: "u08.12", lesson: 2, fr: "Il fait du vélo avec son chien.", en: "He's cycling with his dog.", de: "Er fährt mit seinem Hund Fahrrad.", alt: { en: ["He is riding his bike with his dog.", "He is riding a bike with his dog.", "He rides his bike with his dog.", "He rides a bike with his dog.", "He goes cycling with his dog.", "He cycles with his dog."], de: ["Er fährt Fahrrad mit seinem Hund.", "Er fährt mit seinem Hund Rad.", "Er fährt Rad mit seinem Hund."] } },
    { id: "u08.13", lesson: 2, fr: "Qu'est-ce que tu fais ?", en: "What are you doing?", de: "Was machst du?", alt: { fr: ["Tu fais quoi ?", "Que fais-tu ?", "Qu'est-ce que vous faites ?", "Vous faites quoi ?", "Que faites-vous ?"], en: ["What do you do?"] } },
    { id: "u08.14", lesson: 2, fr: "Léa joue au foot avec Hugo.", en: "Léa plays football with Hugo.", de: "Léa spielt mit Hugo Fußball.", alt: { en: ["Léa is playing football with Hugo.", "Léa plays soccer with Hugo.", "Léa is playing soccer with Hugo."], de: ["Léa spielt Fußball mit Hugo."] } },
    // Lesson 3
    { id: "u08.15", lesson: 3, fr: "Nous faisons de la musique.", en: "We make music.", de: "Wir machen Musik.", alt: { en: ["We play music.", "We do music.", "We are making music."] } },
    { id: "u08.16", lesson: 3, fr: "Vous faites du sport ?", en: "Do you do any sport?", de: "Macht ihr Sport?", alt: { fr: ["Est-ce que vous faites du sport ?", "Faites-vous du sport ?", "Tu fais du sport ?", "Est-ce que tu fais du sport ?", "Fais-tu du sport ?"], en: ["Do you do sport?", "Do you do sports?", "Do you do any sports?", "Do you play sport?", "Do you play any sport?", "Do you play sports?"], de: ["Machen Sie Sport?", "Treibt ihr Sport?", "Treiben Sie Sport?"] } },
    { id: "u08.17", lesson: 3, fr: "Ils font du vélo.", en: "They're cycling.", de: "Sie fahren Fahrrad.", alt: { fr: ["Elles font du vélo."], en: ["They are riding their bikes.", "They are riding bikes.", "They ride bikes.", "They go cycling.", "They are going cycling.", "They cycle."], de: ["Sie fahren Rad."] } },
    { id: "u08.18", lesson: 3, fr: "J'aime nager.", en: "I like swimming.", de: "Ich schwimme gern.", alt: { en: ["I like to swim.", "I love swimming.", "I love to swim."], de: ["Ich schwimme gerne.", "Ich mag schwimmen."] } },
    { id: "u08.19", lesson: 3, fr: "Tu aimes danser ?", en: "Do you like dancing?", de: "Tanzt du gern?", alt: { fr: ["Est-ce que tu aimes danser ?", "Aimes-tu danser ?", "Vous aimez danser ?", "Est-ce que vous aimez danser ?", "Aimez-vous danser ?"], en: ["Do you like to dance?", "Do you love dancing?", "Do you love to dance?"], de: ["Tanzt du gerne?", "Magst du tanzen?"] } },
    { id: "u08.20", lesson: 3, fr: "Nous aimons nager et danser.", en: "We like swimming and dancing.", de: "Wir schwimmen und tanzen gern.", alt: { en: ["We like to swim and dance.", "We like to swim and to dance.", "We love swimming and dancing.", "We love to swim and dance."], de: ["Wir schwimmen und tanzen gerne.", "Wir mögen schwimmen und tanzen."] } },
    { id: "u08.21", lesson: 3, fr: "Ils ne font pas de sport.", en: "They don't do any sport.", de: "Sie machen keinen Sport.", alt: { fr: ["Elles ne font pas de sport."], en: ["They don't do sport.", "They don't do sports.", "They don't do any sports.", "They don't play sport.", "They don't play any sport."], de: ["Sie treiben keinen Sport."] } },
    // Lesson 4
    { id: "u08.22", lesson: 4, fr: "Lundi, je joue au foot.", en: "On Monday I'm playing football.", de: "Am Montag spiele ich Fußball.", alt: { fr: ["Je joue au foot lundi."], en: ["On Monday I play football.", "I am playing football on Monday.", "I play football on Monday.", "On Monday I am playing soccer.", "On Monday I play soccer.", "I am playing soccer on Monday."], de: ["Montag spiele ich Fußball.", "Ich spiele am Montag Fußball."] } },
    { id: "u08.23", lesson: 4, fr: "Le mardi, je fais du vélo.", en: "On Tuesdays I go cycling.", de: "Dienstags fahre ich Fahrrad.", alt: { fr: ["Je fais du vélo le mardi."], en: ["On Tuesdays I ride my bike.", "On Tuesdays I ride a bike.", "On Tuesdays I cycle.", "I go cycling on Tuesdays.", "I ride my bike on Tuesdays.", "I cycle on Tuesdays.", "Every Tuesday I go cycling."], de: ["Dienstags fahre ich Rad.", "Ich fahre dienstags Fahrrad.", "Ich fahre dienstags Rad.", "Jeden Dienstag fahre ich Fahrrad."] } },
    { id: "u08.24", lesson: 4, fr: "Mercredi, nous allons à la piscine.", en: "On Wednesday we're going to the swimming pool.", de: "Am Mittwoch gehen wir ins Schwimmbad.", alt: { fr: ["Nous allons à la piscine mercredi."], en: ["On Wednesday we are going to the pool.", "We are going to the swimming pool on Wednesday.", "We are going to the pool on Wednesday.", "On Wednesday we go to the swimming pool.", "On Wednesday we go to the pool."], de: ["Mittwoch gehen wir ins Schwimmbad.", "Wir gehen am Mittwoch ins Schwimmbad."] } },
    { id: "u08.25", lesson: 4, fr: "Le jeudi, Hugo joue au tennis.", en: "On Thursdays Hugo plays tennis.", de: "Donnerstags spielt Hugo Tennis.", alt: { fr: ["Hugo joue au tennis le jeudi."], en: ["Hugo plays tennis on Thursdays.", "Every Thursday Hugo plays tennis."], de: ["Hugo spielt donnerstags Tennis.", "Jeden Donnerstag spielt Hugo Tennis."] } },
    { id: "u08.26", lesson: 4, fr: "Vendredi, Léa danse avec Blob.", en: "On Friday Léa is dancing with Blob.", de: "Am Freitag tanzt Léa mit Blob.", alt: { fr: ["Léa danse avec Blob vendredi."], en: ["On Friday Léa dances with Blob.", "Léa is dancing with Blob on Friday.", "Léa dances with Blob on Friday."], de: ["Freitag tanzt Léa mit Blob.", "Léa tanzt am Freitag mit Blob."] } },
    { id: "u08.27", lesson: 4, fr: "Tu fais quoi lundi ?", en: "What are you doing on Monday?", de: "Was machst du am Montag?", alt: { fr: ["Qu'est-ce que tu fais lundi ?", "Que fais-tu lundi ?", "Vous faites quoi lundi ?", "Qu'est-ce que vous faites lundi ?", "Que faites-vous lundi ?"], en: ["What are you doing Monday?", "What do you do on Monday?"], de: ["Was machst du Montag?"] } },
    { id: "u08.28", lesson: 4, fr: "Le mercredi, je joue de la guitare.", en: "On Wednesdays I play the guitar.", de: "Mittwochs spiele ich Gitarre.", alt: { fr: ["Je joue de la guitare le mercredi."], en: ["On Wednesdays I play guitar.", "I play the guitar on Wednesdays.", "I play guitar on Wednesdays.", "Every Wednesday I play the guitar."], de: ["Ich spiele mittwochs Gitarre.", "Jeden Mittwoch spiele ich Gitarre."] } },
    // Lesson 5
    { id: "u08.29", lesson: 5, fr: "Le week-end, je fais du vélo.", en: "At the weekend I go cycling.", de: "Am Wochenende fahre ich Fahrrad.", alt: { fr: ["Je fais du vélo le week-end."], en: ["At weekends I go cycling.", "On weekends I go cycling.", "On the weekend I go cycling.", "At the weekend I ride my bike.", "At the weekend I cycle.", "I go cycling at the weekend.", "I go cycling at weekends.", "I go cycling on weekends.", "I ride my bike at the weekend."], de: ["Am Wochenende fahre ich Rad.", "Ich fahre am Wochenende Fahrrad.", "Ich fahre am Wochenende Rad."] } },
    { id: "u08.30", lesson: 5, fr: "Samedi, nous allons au cinéma.", en: "On Saturday we're going to the cinema.", de: "Am Samstag gehen wir ins Kino.", alt: { fr: ["Nous allons au cinéma samedi."], en: ["We are going to the cinema on Saturday.", "On Saturday we go to the cinema.", "On Saturday we are going to the movies.", "We are going to the movies on Saturday."], de: ["Samstag gehen wir ins Kino.", "Wir gehen am Samstag ins Kino.", "Am Sonnabend gehen wir ins Kino."] } },
    { id: "u08.31", lesson: 5, fr: "Le dimanche, je ne fais rien.", en: "On Sundays I don't do anything.", de: "Sonntags mache ich nichts.", alt: { fr: ["Je ne fais rien le dimanche."], en: ["On Sundays I do nothing.", "I do nothing on Sundays.", "I don't do anything on Sundays."], de: ["Ich mache sonntags nichts.", "Sonntags tue ich nichts."] } },
    { id: "u08.32", lesson: 5, fr: "Tu fais quoi ce week-end ?", en: "What are you doing this weekend?", de: "Was machst du dieses Wochenende?", alt: { fr: ["Qu'est-ce que tu fais ce week-end ?", "Que fais-tu ce week-end ?", "Vous faites quoi ce week-end ?", "Qu'est-ce que vous faites ce week-end ?", "Que faites-vous ce week-end ?"], en: ["What do you do this weekend?"], de: ["Was machst du am Wochenende?", "Was machst du an diesem Wochenende?"] } },
    { id: "u08.33", lesson: 5, fr: "Dimanche, Léa et Hugo jouent au tennis.", en: "On Sunday Léa and Hugo are playing tennis.", de: "Am Sonntag spielen Léa und Hugo Tennis.", alt: { fr: ["Léa et Hugo jouent au tennis dimanche."], en: ["On Sunday Léa and Hugo play tennis.", "Léa and Hugo are playing tennis on Sunday.", "Léa and Hugo play tennis on Sunday."], de: ["Sonntag spielen Léa und Hugo Tennis.", "Léa und Hugo spielen am Sonntag Tennis."] } },
    { id: "u08.34", lesson: 5, fr: "J'aime le samedi !", en: "I love Saturdays!", de: "Ich liebe Samstage!", alt: { en: ["I like Saturdays!", "I love Saturday!", "I like Saturday!"], de: ["Ich mag Samstage!", "Ich mag den Samstag!", "Ich liebe den Samstag!"] } },
    // Lesson 6
    { id: "u08.35", lesson: 6, fr: "Il fait beau aujourd'hui !", en: "The weather is nice today!", de: "Heute ist schönes Wetter!", alt: { fr: ["Aujourd'hui, il fait beau !"], en: ["It's nice weather today!", "The weather is lovely today!", "It's lovely weather today!", "It's sunny today!", "It's a nice day today!"], de: ["Das Wetter ist heute schön!", "Heute ist das Wetter schön!", "Es ist heute schönes Wetter!"] } },
    { id: "u08.36", lesson: 6, fr: "Il pleut, je ne fais pas de vélo.", en: "It's raining, I'm not cycling.", de: "Es regnet, ich fahre nicht Fahrrad.", alt: { en: ["It's raining, I'm not riding my bike.", "It's raining, so I'm not cycling.", "It's raining, I'm not going cycling.", "It's raining, so I'm not riding my bike."], de: ["Es regnet, ich fahre nicht Rad.", "Es regnet, ich fahre kein Fahrrad.", "Es regnet, also fahre ich nicht Fahrrad."] } },
    { id: "u08.37", lesson: 6, fr: "Quand il pleut, je joue du piano.", en: "When it rains, I play the piano.", de: "Wenn es regnet, spiele ich Klavier.", alt: { fr: ["Je joue du piano quand il pleut."], en: ["When it rains, I play piano.", "When it's raining, I play the piano.", "I play the piano when it rains.", "I play piano when it rains."], de: ["Ich spiele Klavier, wenn es regnet."] } },
    { id: "u08.38", lesson: 6, fr: "Il fait beau, nous allons à la plage !", en: "The weather is nice, we're going to the beach!", de: "Das Wetter ist schön, wir fahren an den Strand!", alt: { fr: ["Il fait beau, on va à la plage !"], en: ["It's nice weather, we're going to the beach!", "It's sunny, we're going to the beach!", "The weather is lovely, we're going to the beach!", "It's a nice day, we're going to the beach!"], de: ["Es ist schönes Wetter, wir fahren an den Strand!", "Das Wetter ist schön, wir gehen an den Strand!", "Das Wetter ist schön, wir fahren zum Strand!", "Es ist schönes Wetter, wir gehen an den Strand!"] } },
    { id: "u08.39", lesson: 6, fr: "Qu'est-ce que vous faites quand il pleut ?", en: "What do you do when it rains?", de: "Was macht ihr, wenn es regnet?", alt: { fr: ["Vous faites quoi quand il pleut ?", "Que faites-vous quand il pleut ?", "Qu'est-ce que tu fais quand il pleut ?", "Tu fais quoi quand il pleut ?", "Que fais-tu quand il pleut ?"], en: ["What do you do when it's raining?"], de: ["Was machen Sie, wenn es regnet?"] } },
    { id: "u08.40", lesson: 6, fr: "Nous faisons du sport quand il fait beau.", en: "We do sport when the weather is nice.", de: "Wir machen Sport, wenn das Wetter schön ist.", alt: { fr: ["Quand il fait beau, nous faisons du sport.", "On fait du sport quand il fait beau."], en: ["We do sports when the weather is nice.", "We do sport when it's nice weather.", "We play sport when the weather is nice.", "When the weather is nice, we do sport.", "We do sport when it's sunny."], de: ["Wir treiben Sport, wenn das Wetter schön ist.", "Wenn das Wetter schön ist, machen wir Sport.", "Wir machen Sport, wenn schönes Wetter ist."] } },
    { id: "u08.41", lesson: 6, fr: "Est-ce qu'il pleut ?", en: "Is it raining?", de: "Regnet es?", alt: { fr: ["Il pleut ?", "Pleut-il ?"] } },
    { id: "u08.42", lesson: 6, fr: "Ils ne jouent pas au foot, il pleut.", en: "They're not playing football, it's raining.", de: "Sie spielen nicht Fußball, es regnet.", alt: { fr: ["Elles ne jouent pas au foot, il pleut."], en: ["They aren't playing football, it's raining.", "They're not playing football because it's raining.", "They're not playing soccer, it's raining."], de: ["Sie spielen keinen Fußball, es regnet."] } },
    // Lesson 7
    { id: "u08.43", lesson: 7, fr: "Je joue aux jeux vidéo.", en: "I play video games.", de: "Ich spiele Videospiele.", alt: { en: ["I am playing video games.", "I play computer games."], de: ["Ich spiele Computerspiele."] } },
    { id: "u08.44", lesson: 7, fr: "Tu joues aux jeux vidéo avec Hugo ?", en: "Do you play video games with Hugo?", de: "Spielst du mit Hugo Videospiele?", alt: { fr: ["Est-ce que tu joues aux jeux vidéo avec Hugo ?", "Joues-tu aux jeux vidéo avec Hugo ?", "Vous jouez aux jeux vidéo avec Hugo ?", "Est-ce que vous jouez aux jeux vidéo avec Hugo ?"], en: ["Are you playing video games with Hugo?", "Do you play computer games with Hugo?", "You play video games with Hugo?"], de: ["Spielst du Videospiele mit Hugo?", "Spielst du mit Hugo Computerspiele?", "Du spielst mit Hugo Videospiele?"] } },
    { id: "u08.45", lesson: 7, fr: "Le dimanche, mes frères jouent aux jeux vidéo.", en: "On Sundays my brothers play video games.", de: "Sonntags spielen meine Brüder Videospiele.", alt: { fr: ["Mes frères jouent aux jeux vidéo le dimanche."], en: ["My brothers play video games on Sundays.", "On Sundays my brothers play computer games.", "Every Sunday my brothers play video games."], de: ["Meine Brüder spielen sonntags Videospiele.", "Sonntags spielen meine Brüder Computerspiele.", "Jeden Sonntag spielen meine Brüder Videospiele."] } },
    { id: "u08.46", lesson: 7, fr: "Nous ne jouons pas aux jeux vidéo.", en: "We don't play video games.", de: "Wir spielen keine Videospiele.", alt: { en: ["We are not playing video games.", "We don't play computer games."], de: ["Wir spielen keine Computerspiele."] } },
    { id: "u08.47", lesson: 7, fr: "Vous faites quoi le samedi ?", en: "What do you do on Saturdays?", de: "Was macht ihr samstags?", alt: { fr: ["Qu'est-ce que vous faites le samedi ?", "Que faites-vous le samedi ?", "Tu fais quoi le samedi ?", "Qu'est-ce que tu fais le samedi ?", "Que fais-tu le samedi ?"], en: ["What do you do on a Saturday?", "What do you do every Saturday?"], de: ["Was machen Sie samstags?", "Was macht ihr jeden Samstag?"] } },
    { id: "u08.48", lesson: 7, fr: "Mes amis font du sport le week-end.", en: "My friends do sport at the weekend.", de: "Meine Freunde machen am Wochenende Sport.", alt: { fr: ["Le week-end, mes amis font du sport."], en: ["My friends do sports at the weekend.", "My friends do sport at weekends.", "My friends play sport at the weekend.", "My friends do sport on the weekend.", "My friends do sport on weekends."], de: ["Meine Freunde treiben am Wochenende Sport.", "Am Wochenende machen meine Freunde Sport.", "Meine Freunde machen Sport am Wochenende."] } },
    { id: "u08.49", lesson: 7, fr: "Est-ce que ton père fait du vélo ?", en: "Does your father go cycling?", de: "Fährt dein Vater Fahrrad?", alt: { fr: ["Ton père fait du vélo ?", "Est-ce que votre père fait du vélo ?", "Votre père fait du vélo ?"], en: ["Does your dad go cycling?", "Does your father ride a bike?", "Does your dad ride a bike?", "Does your father cycle?", "Does your dad cycle?"], de: ["Fährt dein Vater Rad?", "Fährt dein Papa Fahrrad?"] } },
    { id: "u08.50", lesson: 7, fr: "Vous jouez de la guitare, Madame Martin ?", en: "Do you play the guitar, Mrs Martin?", de: "Spielen Sie Gitarre, Frau Martin?", alt: { fr: ["Est-ce que vous jouez de la guitare, Madame Martin ?", "Jouez-vous de la guitare, Madame Martin ?", "Madame Martin, vous jouez de la guitare ?", "Madame Martin, est-ce que vous jouez de la guitare ?"], en: ["Mrs Martin, do you play the guitar?", "Do you play guitar, Mrs Martin?"], de: ["Frau Martin, spielen Sie Gitarre?"] } },
  ],
  drills: [
    { id: "u08.d1", lesson: 1, fr: "Je fais ___ sport.", options: ["du", "de la", "de l'"], answer: 0, en: "I do sport.", de: "Ich mache Sport.", why: tx("**Sport** is masculine: faire **du** sport (de + le = du).", "**Sport** ist männlich: faire **du** sport (de + le = du).") },
    { id: "u08.d2", lesson: 1, fr: "Tu fais ___ musique ?", options: ["de la", "du", "des"], answer: 0, en: "Do you make music?", de: "Machst du Musik?", why: tx("**Musique** is feminine: faire **de la** musique.", "**Musique** ist weiblich: faire **de la** musique.") },
    { id: "u08.d3", lesson: 1, fr: "Je ne fais pas ___ sport.", options: ["de", "du", "le"], answer: 0, en: "I don't do any sport.", de: "Ich mache keinen Sport.", why: tx("After ne … pas, du and de la become just **de**: je ne fais pas **de** sport.", "Nach ne … pas werden du und de la einfach zu **de**: je ne fais pas **de** sport.") },
    { id: "u08.d4", lesson: 2, fr: "Je joue ___ foot.", options: ["au", "du", "de la"], answer: 0, en: "I play football.", de: "Ich spiele Fußball.", why: tx("Sports and games: jouer **à**, and à + le = **au**: au foot, au tennis.", "Sport und Spiele: jouer **à**, und à + le = **au**: au foot, au tennis.") },
    { id: "u08.d5", lesson: 2, fr: "Hugo joue ___ guitare.", options: ["de la", "à la", "au"], answer: 0, en: "Hugo plays the guitar.", de: "Hugo spielt Gitarre.", why: tx("Instruments: jouer **de**: **de la** guitare, **du** piano.", "Instrumente: jouer **de**: **de la** guitare, **du** piano.") },
    { id: "u08.d6", lesson: 2, fr: "Léa ___ du vélo.", options: ["fait", "fais", "faites"], answer: 0, en: "Léa rides a bike.", de: "Léa fährt Fahrrad.", why: tx("With il / elle (Léa): **fait**, with a t.", "Mit il / elle (Léa): **fait**, mit t.") },
    { id: "u08.d7", lesson: 3, fr: "Nous ___ de la musique.", options: ["faisons", "faites", "font"], answer: 0, en: "We make music.", de: "Wir machen Musik.", why: tx("With **nous**: nous **faisons**, ending in -ons like nous parlons.", "Mit **nous**: nous **faisons**, mit -ons wie nous parlons.") },
    { id: "u08.d8", lesson: 3, fr: "Vous ___ du sport ?", options: ["faites", "faisons", "faisez"], answer: 0, en: "Do you do any sport?", de: "Macht ihr Sport?", why: tx("Faire is irregular: vous **faites**. «Faisez» doesn't exist!", "Faire ist unregelmäßig: vous **faites**. „Faisez“ gibt es nicht!") },
    { id: "u08.d9", lesson: 3, fr: "Ils ___ du vélo.", options: ["font", "fait", "faisent"], answer: 0, en: "They're cycling.", de: "Sie fahren Fahrrad.", why: tx("They: ils **font**. Like ils sont, ils ont, ils vont.", "Sie (Plural): ils **font**. Wie ils sont, ils ont, ils vont.") },
    { id: "u08.d10", lesson: 3, fr: "J'aime ___.", options: ["nager", "nage", "nages"], answer: 0, en: "I like swimming.", de: "Ich schwimme gern.", why: tx("After j'aime, the verb stays whole: j'aime **nager**, j'aime danser.", "Nach j'aime bleibt das Verb ganz (Infinitiv): j'aime **nager**, j'aime danser.") },
    { id: "u08.d11", lesson: 4, fr: "___ lundi, je joue au foot.", options: ["Le", "Au", "En"], answer: 0, en: "On Mondays I play football.", de: "Montags spiele ich Fußball.", why: tx("Every Monday: **le** lundi. Just lundi means this Monday. And no word for «on»!", "Jeden Montag (montags): **le** lundi. Nur lundi heißt diesen Montag. Und kein Wort für „am“!") },
    { id: "u08.d12", lesson: 5, fr: "Le dimanche, je ne fais ___.", options: ["rien", "pas", "de"], answer: 0, en: "On Sundays I don't do anything.", de: "Sonntags mache ich nichts.", why: tx("Nothing is **ne … rien**: it goes around the verb, just like ne … pas.", "Nichts heißt **ne … rien**: Es steht um das Verb herum, genau wie ne … pas.") },
    { id: "u08.d13", lesson: 6, fr: "Il ___ beau aujourd'hui !", options: ["fait", "fais", "font"], answer: 0, en: "The weather is nice today!", de: "Heute ist schönes Wetter!", why: tx("The weather uses faire: **il fait** beau. With il, faire is **fait**, with a t.", "Beim Wetter steht faire: **il fait** beau. Mit il heißt faire **fait**, mit t.") },
    { id: "u08.d14", lesson: 6, fr: "Qu'est-ce que vous ___ quand il pleut ?", options: ["faites", "faisez", "font"], answer: 0, en: "What do you do when it rains?", de: "Was macht ihr, wenn es regnet?", why: tx("With **vous**, faire is **faites**. «Faisez» doesn't exist!", "Mit **vous** heißt faire **faites**. „Faisez“ gibt es nicht!") },
    { id: "u08.d15", lesson: 6, fr: "Ils ne ___ pas au foot, il pleut.", options: ["jouent", "joue", "jouez"], answer: 0, en: "They're not playing football, it's raining.", de: "Sie spielen nicht Fußball, es regnet.", why: tx("With **ils**, -er verbs end in **-ent**: ils ne jou**ent** pas.", "Mit **ils** enden -er-Verben auf **-ent**: ils ne jou**ent** pas.") },
    { id: "u08.d16", lesson: 7, fr: "Je joue ___ jeux vidéo.", options: ["aux", "au", "à les"], answer: 0, en: "I play video games.", de: "Ich spiele Videospiele.", why: tx("Games take jouer à, and à + les = **aux**: aux jeux vidéo. Au is for one: au foot.", "Spiele haben jouer à, und à + les = **aux**: aux jeux vidéo. Au steht bei einem: au foot.") },
    { id: "u08.d17", lesson: 7, fr: "Nous ne ___ pas aux jeux vidéo.", options: ["jouons", "jouez", "jouent"], answer: 0, en: "We don't play video games.", de: "Wir spielen keine Videospiele.", why: tx("With **nous**: nous jou**ons**, like nous parlons.", "Mit **nous**: nous jou**ons**, wie nous parlons.") },
    { id: "u08.d18", lesson: 7, fr: "Mes amis ___ du sport le week-end.", options: ["font", "fait", "faisons"], answer: 0, en: "My friends do sport at the weekend.", de: "Meine Freunde machen am Wochenende Sport.", why: tx("Mes amis = **ils**: ils **font**. Like ils sont, ils ont, ils vont.", "Mes amis = **ils**: ils **font**. Wie ils sont, ils ont, ils vont.") },
  ],
  dialogues: [
    {
      id: "u08.dialogue",
      lesson: 5,
      title: tx("Blob's busy weekend", "Blobs volles Wochenende"),
      lines: [
        { who: "lea", fr: "Blob, qu'est-ce que tu fais ce week-end ?", en: "Blob, what are you doing this weekend?", de: "Blob, was machst du dieses Wochenende?" },
        { who: "blob", fr: "Samedi, je joue au foot avec Hugo.", en: "On Saturday I'm playing football with Hugo.", de: "Am Samstag spiele ich mit Hugo Fußball." },
        { who: "hugo", fr: "Et après, nous allons à la piscine !", en: "And afterwards we're going to the swimming pool!", de: "Und danach gehen wir ins Schwimmbad!" },
        { who: "lea", fr: "Super ! Et dimanche ?", en: "Great! And on Sunday?", de: "Super! Und am Sonntag?" },
        { who: "blob", fr: "Dimanche, je fais du vélo, je danse et je joue de la guitare !", en: "On Sunday I'm cycling, dancing and playing the guitar!", de: "Am Sonntag fahre ich Fahrrad, tanze und spiele Gitarre!" },
        { who: "hugo", fr: "Tu joues de la guitare, Blob ?", en: "You play the guitar, Blob?", de: "Du spielst Gitarre, Blob?" },
        { who: "blob", fr: "Euh… non. Mais j'aime la musique !", en: "Er… no. But I love music!", de: "Äh … nein. Aber ich liebe Musik!" },
        { who: "lea", fr: "Et lundi ?", en: "And on Monday?", de: "Und am Montag?" },
        { who: "blob", fr: "Lundi, je ne fais rien. Je suis très fatigué !", en: "On Monday I'm doing nothing. I'm very tired!", de: "Am Montag mache ich nichts. Ich bin sehr müde!" },
      ],
      questions: [
        { q: tx("What does Blob do on Saturday?", "Was macht Blob am Samstag?"), options: [tx("He plays football with Hugo.", "Er spielt mit Hugo Fußball."), tx("He plays the guitar.", "Er spielt Gitarre."), tx("He does nothing.", "Er macht nichts.")], answer: 0 },
        { q: tx("Where do Blob and Hugo go after football?", "Wohin gehen Blob und Hugo nach dem Fußball?"), options: [tx("To the swimming pool", "Ins Schwimmbad"), tx("To the cinema", "Ins Kino"), tx("To the beach", "An den Strand")], answer: 0 },
        { q: tx("Does Blob play the guitar?", "Spielt Blob Gitarre?"), options: [tx("No, but he loves music.", "Nein, aber er liebt Musik."), tx("Yes, very well.", "Ja, sehr gut."), tx("Yes, on Mondays.", "Ja, montags.")], answer: 0 },
      ],
    },
    {
      id: "u08.dialogue2",
      lesson: 7,
      title: tx("A rainy Saturday", "Ein verregneter Samstag"),
      lines: [
        { who: "lea", fr: "Il pleut ! Qu'est-ce que nous faisons aujourd'hui ?", en: "It's raining! What shall we do today?", de: "Es regnet! Was machen wir heute?" },
        { who: "hugo", fr: "Aujourd'hui ? On joue aux jeux vidéo !", en: "Today? Let's play video games!", de: "Heute? Wir spielen Videospiele!" },
        { who: "blob", fr: "Les jeux vidéo ? Non, c'est difficile pour moi !", en: "Video games? No, they're difficult for me!", de: "Videospiele? Nein, das ist schwer für mich!" },
        { who: "lea", fr: "Blob, qu'est-ce que tu fais quand il pleut ?", en: "Blob, what do you do when it rains?", de: "Blob, was machst du, wenn es regnet?" },
        { who: "blob", fr: "Quand il pleut ? Je danse !", en: "When it rains? I dance!", de: "Wenn es regnet? Ich tanze!" },
        { who: "hugo", fr: "Super ! Alors, on fait de la musique et on danse !", en: "Great! Then let's make music and dance!", de: "Super! Dann machen wir Musik und tanzen!" },
        { who: "lea", fr: "Je joue de la guitare et Hugo joue du piano.", en: "I'll play the guitar and Hugo will play the piano.", de: "Ich spiele Gitarre und Hugo spielt Klavier." },
        { who: "blob", fr: "Et moi, je danse !", en: "And I'll dance!", de: "Und ich tanze!" },
        { who: "madame", fr: "Bonjour, les enfants ! Qu'est-ce que vous faites ?", en: "Hello, children! What are you doing?", de: "Hallo, Kinder! Was macht ihr da?" },
        { who: "blob", fr: "Nous dansons, Madame Martin ! Il pleut, mais c'est super !", en: "We're dancing, Mrs Martin! It's raining, but it's great!", de: "Wir tanzen, Frau Martin! Es regnet, aber es ist super!" },
      ],
      questions: [
        { q: tx("What's the weather like?", "Wie ist das Wetter?"), options: [tx("It's raining.", "Es regnet."), tx("The weather is nice.", "Das Wetter ist schön."), tx("It's hot.", "Es ist heiß.")], answer: 0 },
        { q: tx("Why doesn't Blob want to play video games?", "Warum will Blob keine Videospiele spielen?"), options: [tx("They're difficult for him.", "Sie sind schwer für ihn."), tx("He's tired.", "Er ist müde."), tx("He doesn't have a game.", "Er hat kein Spiel.")], answer: 0 },
        { q: tx("What does Hugo play?", "Was spielt Hugo?"), options: [tx("The piano", "Klavier"), tx("The guitar", "Gitarre"), tx("Football", "Fußball")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Faire: to do, to make", "Faire: machen, tun"),
      body: tx(
        "**Faire** means to do and to make. It's irregular: **vous faites** (never «faisez») and **ils font**.\n\nFor many activities French says **faire du / de la**: faire du sport, faire du vélo (to ride a bike), faire de la musique. After ne … pas it's just **de**: je ne fais pas **de** sport.",
        "**Faire** heißt machen und tun. Es ist unregelmäßig: **vous faites** (nie „faisez“) und **ils font**.\n\nFür viele Aktivitäten sagt man **faire du / de la**: faire du sport, faire du vélo (Fahrrad fahren), faire de la musique. Nach ne … pas nur **de**: je ne fais pas **de** sport.",
      ),
      examples: [
        { fr: "Je fais du sport.", en: "I do sport.", de: "Ich mache Sport." },
        { fr: "Vous faites de la musique ?", en: "Do you make music?", de: "Macht ihr Musik?" },
        { fr: "Ils ne font pas de vélo.", en: "They don't ride bikes.", de: "Sie fahren nicht Fahrrad." },
      ],
      table: {
        head: [tx("person", "Person"), "faire"],
        rows: [
          [tx("I", "ich"), "je fais"],
          [tx("you", "du"), "tu fais"],
          [tx("he / she", "er / sie"), "il / elle fait"],
          [tx("we", "wir"), "nous faisons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous faites"],
          [tx("they", "sie"), "ils / elles font"],
        ],
      },
    },
    {
      title: tx("Jouer au foot, jouer de la guitare", "Jouer au foot, jouer de la guitare"),
      body: tx(
        "Two kinds of playing. Sports and games: **jouer à**, so **au** foot, **au** tennis (à + le = au).\n\nInstruments: **jouer de**, so **de la** guitare, **du** piano (de + le = du). English and German just say «play».",
        "Zwei Arten von Spielen. Sport und Spiele: **jouer à**, also **au** foot, **au** tennis (à + le = au).\n\nInstrumente: **jouer de**, also **de la** guitare, **du** piano (de + le = du). Im Deutschen heißt beides einfach „spielen“.",
      ),
      examples: [
        { fr: "Je joue au foot.", en: "I play football.", de: "Ich spiele Fußball." },
        { fr: "Hugo joue du piano.", en: "Hugo plays the piano.", de: "Hugo spielt Klavier." },
        { fr: "Tu joues de la guitare ?", en: "Do you play the guitar?", de: "Spielst du Gitarre?" },
      ],
    },
    {
      title: tx("Days of the week", "Die Wochentage"),
      body: tx(
        "The days are **masculine** and written **small**: lundi, mardi…\n\nThere's no word for «on»: **lundi** = on Monday (this Monday). With **le** it's every week: **le lundi** = on Mondays. The same for **le week-end**: at the weekend.",
        "Die Tage sind **männlich** und werden **klein** geschrieben: lundi, mardi …\n\nEs gibt kein Wort für „am“: **lundi** = am Montag (diesen Montag). Mit **le** ist es jede Woche: **le lundi** = montags. Genauso **le week-end**: am Wochenende.",
      ),
      examples: [
        { fr: "Lundi, je joue au foot.", en: "On Monday I'm playing football.", de: "Am Montag spiele ich Fußball." },
        { fr: "Le samedi, je fais du vélo.", en: "On Saturdays I go cycling.", de: "Samstags fahre ich Fahrrad." },
      ],
      table: {
        head: [tx("French", "Französisch"), tx("meaning", "Bedeutung")],
        rows: [
          ["lundi", tx("Monday", "Montag")],
          ["mardi", tx("Tuesday", "Dienstag")],
          ["mercredi", tx("Wednesday", "Mittwoch")],
          ["jeudi", tx("Thursday", "Donnerstag")],
          ["vendredi", tx("Friday", "Freitag")],
          ["samedi", tx("Saturday", "Samstag")],
          ["dimanche", tx("Sunday", "Sonntag")],
        ],
      },
    },
    {
      title: tx("Weather and video games", "Wetter und Videospiele"),
      body: tx(
        "For the weather, French uses **faire**: **il fait beau** (the weather is nice). Rain has a verb of its own: **il pleut** (it's raining). With **quand** (when): quand il pleut, je joue du piano.\n\nGames in the plural take **aux** (à + les): je joue **aux** jeux vidéo. So it's **au** foot, **aux** jeux vidéo, but **de la** guitare.",
        "Beim Wetter steht **faire**: **il fait beau** (das Wetter ist schön). Regen hat ein eigenes Verb: **il pleut** (es regnet). Mit **quand** (wenn): quand il pleut, je joue du piano.\n\nSpiele im Plural bekommen **aux** (à + les): je joue **aux** jeux vidéo. Also **au** foot, **aux** jeux vidéo, aber **de la** guitare.",
      ),
      examples: [
        { fr: "Il fait beau aujourd'hui !", en: "The weather is nice today!", de: "Heute ist schönes Wetter!" },
        { fr: "Quand il pleut, je joue du piano.", en: "When it rains, I play the piano.", de: "Wenn es regnet, spiele ich Klavier." },
        { fr: "Nous ne jouons pas aux jeux vidéo.", en: "We don't play video games.", de: "Wir spielen keine Videospiele." },
      ],
      table: {
        head: [tx("person", "Person"), "jouer"],
        rows: [
          [tx("I", "ich"), "je joue"],
          [tx("you", "du"), "tu joues"],
          [tx("he / she", "er / sie"), "il / elle joue"],
          [tx("we", "wir"), "nous jouons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous jouez"],
          [tx("they", "sie"), "ils / elles jouent"],
        ],
      },
    },
  ],
};
