import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 9: colours and clothes, adjective agreement and place, porter, ce / cette / ces. */
export const u09: Unit = {
  slug: "vetements",
  n: 9,
  cefr: "A1",
  title: tx("Clothes and colours", "Kleidung und Farben"),
  goal: tx("Describe clothes and colours, and say what you're wearing", "Kleidung und Farben beschreiben und sagen, was du trägst"),
  emoji: "👕",
  words: [
    { id: "rouge", fr: "rouge", en: "red", de: "rot", kind: "adj", emoji: "🔴", note: tx("It already ends in -e, so it stays the same: un pull rouge, une robe rouge.", "Endet schon auf -e, also bleibt es gleich: un pull rouge, une robe rouge.") },
    { id: "bleu", fr: "bleu", en: "blue", de: "blau", kind: "adj", emoji: "🔵", note: tx("Feminine: bleue. It sounds the same.", "Weiblich: bleue. Es klingt gleich.") },
    { id: "vert", fr: "vert", en: "green", de: "grün", kind: "adj", emoji: "🟢", note: tx("Feminine: verte, and now you hear the t.", "Weiblich: verte, und jetzt hört man das t.") },
    { id: "jaune", fr: "jaune", en: "yellow", de: "gelb", kind: "adj", emoji: "🟡" },
    { id: "noir", fr: "noir", en: "black", de: "schwarz", kind: "adj", emoji: "⚫", note: tx("Feminine: noire. It sounds the same.", "Weiblich: noire. Es klingt gleich.") },
    { id: "blanc", fr: "blanc", en: "white", de: "weiß", kind: "adj", emoji: "⚪", note: tx("A special feminine: blanche, with a «sh» sound at the end.", "Besondere weibliche Form: blanche, mit „sch“ am Ende.") },
    { id: "je-porte", fr: "je porte", en: "I wear", de: "ich trage", alt: { en: ["I am wearing"] }, kind: "verb", note: tx("Porter: to wear, and also to carry. A regular -er verb like parler.", "Porter: tragen (Kleidung und Taschen). Ein regelmäßiges -er-Verb wie parler.") },
    { id: "tu-portes", fr: "tu portes", en: "you wear", de: "du trägst", alt: { en: ["you are wearing"] }, kind: "verb" },
    { id: "il-porte", fr: "il porte", en: "he wears", de: "er trägt", alt: { en: ["he is wearing"] }, kind: "verb" },
    { id: "t-shirt", fr: "le t-shirt", en: "the T-shirt", de: "das T-Shirt", g: "m", kind: "noun", emoji: "👕" },
    { id: "pantalon", fr: "le pantalon", en: "the trousers", de: "die Hose", alt: { en: ["the pants"] }, g: "m", kind: "noun", emoji: "👖", note: tx("Singular in French: un pantalon, a pair of trousers. Mon pantalon est bleu: my trousers are blue.", "Singular, wie im Deutschen: un pantalon, eine Hose.") },
    { id: "pull", fr: "le pull", en: "the jumper", de: "der Pullover", alt: { en: ["the sweater", "the pullover"], de: ["der Pulli"] }, g: "m", kind: "noun", note: tx("Short for le pull-over.", "Kurz für le pull-over.") },
    { id: "robe", fr: "la robe", en: "the dress", de: "das Kleid", g: "f", kind: "noun", emoji: "👗" },
    { id: "jupe", fr: "la jupe", en: "the skirt", de: "der Rock", g: "f", kind: "noun" },
    { id: "chemise", fr: "la chemise", en: "the shirt", de: "das Hemd", g: "f", kind: "noun", emoji: "👔", note: tx("Feminine: une chemise blanche.", "Weiblich, anders als das Hemd: une chemise blanche.") },
    { id: "veste", fr: "la veste", en: "the jacket", de: "die Jacke", g: "f", kind: "noun", emoji: "🧥" },
    { id: "gris", fr: "gris", en: "grey", de: "grau", alt: { en: ["gray"] }, kind: "adj", emoji: "🩶", note: tx("Feminine: grise, and now you hear a z sound.", "Weiblich: grise, und jetzt hört man ein weiches s.") },
    { id: "joli", fr: "joli", en: "pretty", de: "schön", alt: { en: ["nice", "lovely"], de: ["hübsch"] }, kind: "adj", note: tx("Unlike colours, joli comes before the noun: une jolie robe.", "Anders als Farben steht joli vor dem Nomen: une jolie robe.") },
    { id: "chaussures", fr: "les chaussures", en: "the shoes", de: "die Schuhe", g: "f", kind: "noun", emoji: "👟", note: tx("Une chaussure, des chaussures: feminine.", "Une chaussure, des chaussures: weiblich.") },
    { id: "couleur", fr: "la couleur", en: "the colour", de: "die Farbe", alt: { en: ["the color"] }, g: "f", kind: "noun", emoji: "🎨", note: tx("Feminine: la couleur, cette couleur, une jolie couleur.", "Weiblich, wie die Farbe: la couleur, cette couleur.") },
    { id: "beret", fr: "le béret", en: "the beret", de: "die Baskenmütze", alt: { de: ["das Barett"] }, g: "m", kind: "noun", note: tx("Blob's favourite: the most French hat there is!", "Blobs Liebling: die französischste Mütze, die es gibt!") },
    { id: "nouveau", fr: "nouveau", en: "new", de: "neu", kind: "adj", emoji: "🆕", note: tx("Before the noun, like joli: un nouveau béret. Feminine: une nouvelle robe.", "Steht vor dem Nomen, wie joli: un nouveau béret. Weiblich: une nouvelle robe.") },
    { id: "chaussettes", fr: "les chaussettes", en: "the socks", de: "die Socken", g: "f", kind: "noun", emoji: "🧦", note: tx("Une chaussette, des chaussettes: feminine, like les chaussures.", "Une chaussette, des chaussettes: weiblich, wie les chaussures.") },
    { id: "casquette", fr: "la casquette", en: "the cap", de: "die Kappe", alt: { en: ["the baseball cap"], de: ["die Mütze", "die Schirmmütze", "das Cap"] }, g: "f", kind: "noun", emoji: "🧢" },
    { id: "rose", fr: "rose", en: "pink", de: "rosa", alt: { de: ["pink"] }, kind: "adj", emoji: "🩷", note: tx("It ends in -e like rouge, so it stays the same: un pull rose, une robe rose.", "Endet auf -e wie rouge, also bleibt es gleich: un pull rose, une robe rose.") },
    { id: "violet", fr: "violet", en: "purple", de: "lila", alt: { en: ["violet"], de: ["violett"] }, kind: "adj", emoji: "🟣", note: tx("Blob's colour! Feminine: violette, with a double t.", "Blobs Farbe! Weiblich: violette, mit Doppel-t.") },
  ],
  gloss: [
    { fr: "noires", en: "black (feminine plural)", de: "schwarz" },
    { fr: "verte", en: "green (feminine)", de: "grün (weiblich)" },
    { fr: "bleue", en: "blue (feminine)", de: "blau (weiblich)" },
    { fr: "noire", en: "black (feminine)", de: "schwarz (weiblich)" },
    { fr: "blanche", en: "white (feminine)", de: "weiß (weiblich)" },
    { fr: "blanches", en: "white (feminine plural)", de: "weiß (weiblich, Plural)" },
    { fr: "grise", en: "grey (feminine)", de: "grau (weiblich)" },
    { fr: "jolie", en: "pretty (feminine)", de: "schön (weiblich)" },
    { fr: "jolies", en: "pretty (feminine plural)", de: "schön (weiblich, Plural)" },
    { fr: "nouvelle", en: "new (feminine)", de: "neu (weiblich)" },
    { fr: "porte", en: "wear / wears", de: "trage / trägt" },
    { fr: "préférée", en: "favourite (feminine)", de: "Lieblings-" },
    { fr: "trop", en: "too", de: "zu" },
    { fr: "jambes", en: "legs", de: "Beine" },
    { fr: "parfait", en: "perfect", de: "perfekt" },
    { fr: "rouges", en: "red (plural)", de: "rot (Plural)" },
    { fr: "verts", en: "green (plural)", de: "grün (Plural)" },
    { fr: "roses", en: "pink (plural)", de: "rosa (Plural)" },
    { fr: "violette", en: "purple (feminine)", de: "lila (weiblich)" },
    { fr: "violettes", en: "purple (feminine plural)", de: "lila (weiblich, Plural)" },
    { fr: "nouvelles", en: "new (feminine plural)", de: "neu (weiblich, Plural)" },
    { fr: "pulls", en: "jumpers", de: "Pullover" },
    { fr: "chemises", en: "shirts", de: "Hemden" },
    { fr: "portons", en: "wear (we)", de: "tragen (wir)" },
    { fr: "portez", en: "wear (you, plural / polite)", de: "tragt / tragen (Sie)" },
    { fr: "portent", en: "wear (they)", de: "tragen (sie)" },
    { fr: "aimez", en: "like (you, plural / polite)", de: "mögt / mögen (Sie)" },
    { fr: "pieds", en: "feet", de: "Füße" },
  ],
  lessons: [
    { title: tx("Colours", "Farben"), words: ["rouge", "bleu", "vert", "jaune", "noir", "blanc"] },
    { title: tx("What are you wearing?", "Was trägst du?"), words: ["je-porte", "tu-portes", "il-porte", "t-shirt", "pantalon", "pull"] },
    { title: tx("A red dress", "Ein rotes Kleid"), words: ["robe", "jupe", "chemise", "veste", "gris"] },
    { title: tx("This dress, these shoes", "Dieses Kleid, diese Schuhe"), words: ["joli", "chaussures", "couleur"] },
    { title: tx("Blob's béret", "Blobs Baskenmütze"), words: ["beret", "nouveau"] },
    { title: tx("Socks and caps", "Socken und Kappen"), words: ["chaussettes", "casquette", "rose"] },
    { title: tx("Blob's colour", "Blobs Farbe"), words: ["violet"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u09.01", lesson: 1, fr: "Le stylo est rouge.", en: "The pen is red.", de: "Der Stift ist rot.", alt: { de: ["Der Kuli ist rot.", "Der Kugelschreiber ist rot."] } },
    { id: "u09.02", lesson: 1, fr: "Mon sac est noir.", en: "My bag is black.", de: "Meine Tasche ist schwarz.", alt: { en: ["My schoolbag is black.", "My backpack is black."], de: ["Mein Rucksack ist schwarz.", "Meine Schultasche ist schwarz."] } },
    { id: "u09.03", lesson: 1, fr: "La pomme est verte.", en: "The apple is green.", de: "Der Apfel ist grün." },
    { id: "u09.04", lesson: 1, fr: "La banane est jaune.", en: "The banana is yellow.", de: "Die Banane ist gelb." },
    { id: "u09.05", lesson: 1, fr: "J'ai un chat blanc.", en: "I have a white cat.", de: "Ich habe eine weiße Katze.", alt: { en: ["I have got a white cat."], de: ["Ich habe einen weißen Kater."] } },
    { id: "u09.06", lesson: 1, fr: "C'est un livre bleu.", en: "It's a blue book.", de: "Das ist ein blaues Buch.", alt: { en: ["This is a blue book.", "That's a blue book."], de: ["Es ist ein blaues Buch."] } },
    { id: "u09.07", lesson: 1, fr: "La maison est blanche.", en: "The house is white.", de: "Das Haus ist weiß." },
    // Lesson 2
    { id: "u09.08", lesson: 2, fr: "Je porte un t-shirt rouge.", en: "I'm wearing a red T-shirt.", de: "Ich trage ein rotes T-Shirt.", alt: { en: ["I wear a red T-shirt."], de: ["Ich habe ein rotes T-Shirt an."] } },
    { id: "u09.09", lesson: 2, fr: "Tu portes un pull bleu ?", en: "Are you wearing a blue jumper?", de: "Trägst du einen blauen Pullover?", alt: { fr: ["Est-ce que tu portes un pull bleu ?", "Portes-tu un pull bleu ?", "Vous portez un pull bleu ?", "Est-ce que vous portez un pull bleu ?", "Portez-vous un pull bleu ?"], en: ["Are you wearing a blue sweater?", "Are you wearing a blue pullover?", "Do you wear a blue jumper?", "Do you wear a blue sweater?", "You are wearing a blue jumper?"], de: ["Trägst du einen blauen Pulli?", "Hast du einen blauen Pullover an?", "Hast du einen blauen Pulli an?"] } },
    { id: "u09.10", lesson: 2, fr: "Hugo porte un pantalon noir.", en: "Hugo is wearing black trousers.", de: "Hugo trägt eine schwarze Hose.", alt: { en: ["Hugo wears black trousers.", "Hugo is wearing a pair of black trousers.", "Hugo is wearing black pants.", "Hugo wears black pants."], de: ["Hugo hat eine schwarze Hose an."] } },
    { id: "u09.11", lesson: 2, fr: "Il porte un t-shirt blanc.", en: "He's wearing a white T-shirt.", de: "Er trägt ein weißes T-Shirt.", alt: { en: ["He wears a white T-shirt."], de: ["Er hat ein weißes T-Shirt an."] } },
    { id: "u09.12", lesson: 2, fr: "Mon pantalon est bleu.", en: "My trousers are blue.", de: "Meine Hose ist blau.", alt: { en: ["My pants are blue."] } },
    { id: "u09.13", lesson: 2, fr: "Je ne porte pas de pull.", en: "I'm not wearing a jumper.", de: "Ich trage keinen Pullover.", alt: { en: ["I am not wearing a sweater.", "I am not wearing a pullover.", "I don't wear a jumper.", "I don't wear a sweater."], de: ["Ich trage keinen Pulli.", "Ich habe keinen Pullover an.", "Ich habe keinen Pulli an."] } },
    { id: "u09.14", lesson: 2, fr: "Léa porte un pull vert.", en: "Léa is wearing a green jumper.", de: "Léa trägt einen grünen Pullover.", alt: { en: ["Léa wears a green jumper.", "Léa is wearing a green sweater.", "Léa wears a green sweater.", "Léa is wearing a green pullover."], de: ["Léa trägt einen grünen Pulli.", "Léa hat einen grünen Pullover an.", "Léa hat einen grünen Pulli an."] } },
    // Lesson 3
    { id: "u09.15", lesson: 3, fr: "Elle porte une robe rouge.", en: "She's wearing a red dress.", de: "Sie trägt ein rotes Kleid.", alt: { en: ["She wears a red dress."], de: ["Sie hat ein rotes Kleid an."] } },
    { id: "u09.16", lesson: 3, fr: "J'aime la jupe verte.", en: "I like the green skirt.", de: "Ich mag den grünen Rock.", alt: { en: ["I love the green skirt."], de: ["Mir gefällt der grüne Rock.", "Ich liebe den grünen Rock."] } },
    { id: "u09.17", lesson: 3, fr: "Monsieur Martin porte une chemise blanche.", en: "Mr Martin is wearing a white shirt.", de: "Herr Martin trägt ein weißes Hemd.", alt: { en: ["Mr Martin wears a white shirt."], de: ["Herr Martin hat ein weißes Hemd an."] } },
    { id: "u09.18", lesson: 3, fr: "Ta veste est grise.", en: "Your jacket is grey.", de: "Deine Jacke ist grau.", alt: { fr: ["Votre veste est grise."], en: ["Your jacket is gray."] } },
    { id: "u09.19", lesson: 3, fr: "Madame Martin porte une veste noire.", en: "Mrs Martin is wearing a black jacket.", de: "Frau Martin trägt eine schwarze Jacke.", alt: { en: ["Mrs Martin wears a black jacket."], de: ["Frau Martin hat eine schwarze Jacke an."] } },
    { id: "u09.20", lesson: 3, fr: "J'ai une jupe grise et un pull gris.", en: "I have a grey skirt and a grey jumper.", de: "Ich habe einen grauen Rock und einen grauen Pullover.", alt: { en: ["I have got a grey skirt and a grey jumper.", "I have a grey skirt and a grey sweater.", "I have got a grey skirt and a grey sweater.", "I have a gray skirt and a gray sweater."], de: ["Ich habe einen grauen Rock und einen grauen Pulli."] } },
    { id: "u09.21", lesson: 3, fr: "Est-ce que tu portes une robe bleue ?", en: "Are you wearing a blue dress?", de: "Trägst du ein blaues Kleid?", alt: { fr: ["Tu portes une robe bleue ?", "Portes-tu une robe bleue ?", "Est-ce que vous portez une robe bleue ?", "Vous portez une robe bleue ?", "Portez-vous une robe bleue ?"], en: ["Do you wear a blue dress?", "You are wearing a blue dress?"], de: ["Hast du ein blaues Kleid an?"] } },
    // Lesson 4
    { id: "u09.22", lesson: 4, fr: "Ces chaussures sont jolies.", en: "These shoes are pretty.", de: "Diese Schuhe sind schön.", alt: { en: ["Those shoes are pretty.", "These shoes are nice.", "Those shoes are nice.", "These shoes are lovely.", "Those shoes are lovely."], de: ["Diese Schuhe sind hübsch."] } },
    { id: "u09.23", lesson: 4, fr: "Cette robe est très jolie.", en: "This dress is very pretty.", de: "Dieses Kleid ist sehr schön.", alt: { en: ["That dress is very pretty.", "This dress is very nice.", "That dress is very nice.", "This dress is really pretty.", "This dress is very lovely."], de: ["Dieses Kleid ist sehr hübsch.", "Das Kleid ist sehr schön."] } },
    { id: "u09.24", lesson: 4, fr: "J'aime ce pull.", en: "I like this jumper.", de: "Ich mag diesen Pullover.", alt: { en: ["I like that jumper.", "I like this sweater.", "I like that sweater.", "I like this pullover.", "I love this jumper."], de: ["Mir gefällt dieser Pullover.", "Ich mag diesen Pulli.", "Mir gefällt dieser Pulli."] } },
    { id: "u09.25", lesson: 4, fr: "C'est une jolie veste.", en: "It's a pretty jacket.", de: "Das ist eine schöne Jacke.", alt: { en: ["It's a nice jacket.", "That's a pretty jacket.", "That's a nice jacket.", "This is a pretty jacket.", "This is a nice jacket.", "It's a lovely jacket."], de: ["Das ist eine hübsche Jacke.", "Es ist eine schöne Jacke."] } },
    { id: "u09.26", lesson: 4, fr: "Tu aimes cette couleur ?", en: "Do you like this colour?", de: "Magst du diese Farbe?", alt: { fr: ["Est-ce que tu aimes cette couleur ?", "Aimes-tu cette couleur ?", "Vous aimez cette couleur ?", "Est-ce que vous aimez cette couleur ?", "Aimez-vous cette couleur ?"], en: ["Do you like that colour?", "Do you like this color?", "Do you like that color?"], de: ["Gefällt dir diese Farbe?", "Du magst diese Farbe?"] } },
    { id: "u09.27", lesson: 4, fr: "Mes chaussures sont blanches.", en: "My shoes are white.", de: "Meine Schuhe sind weiß." },
    { id: "u09.28", lesson: 4, fr: "Ma couleur préférée, c'est le bleu.", en: "My favourite colour is blue.", de: "Meine Lieblingsfarbe ist Blau.", alt: { fr: ["Ma couleur préférée est le bleu."], en: ["My favorite colour is blue.", "My favourite color is blue.", "My favorite color is blue."] } },
    // Lesson 5
    { id: "u09.29", lesson: 5, fr: "Blob porte un béret noir.", en: "Blob is wearing a black beret.", de: "Blob trägt eine schwarze Baskenmütze.", alt: { en: ["Blob wears a black beret."], de: ["Blob trägt ein schwarzes Barett.", "Blob hat eine schwarze Baskenmütze auf."] } },
    { id: "u09.30", lesson: 5, fr: "C'est un nouveau béret ?", en: "Is it a new beret?", de: "Ist das eine neue Baskenmütze?", alt: { fr: ["Est-ce que c'est un nouveau béret ?"], en: ["Is that a new beret?", "Is this a new beret?"], de: ["Ist das ein neues Barett?", "Ist es eine neue Baskenmütze?"] } },
    { id: "u09.31", lesson: 5, fr: "J'aime ton nouveau pull.", en: "I like your new jumper.", de: "Ich mag deinen neuen Pullover.", alt: { fr: ["J'aime votre nouveau pull."], en: ["I like your new sweater.", "I love your new jumper.", "I love your new sweater.", "I like your new pullover."], de: ["Mir gefällt dein neuer Pullover.", "Ich mag deinen neuen Pulli.", "Mir gefällt dein neuer Pulli."] } },
    { id: "u09.32", lesson: 5, fr: "J'ai une nouvelle robe.", en: "I have a new dress.", de: "Ich habe ein neues Kleid.", alt: { en: ["I have got a new dress."] } },
    { id: "u09.33", lesson: 5, fr: "Ce béret est trop grand !", en: "This beret is too big!", de: "Diese Baskenmütze ist zu groß!", alt: { en: ["That beret is too big!", "This beret is too large!"], de: ["Die Baskenmütze ist zu groß!", "Dieses Barett ist zu groß!"] } },
    { id: "u09.34", lesson: 5, fr: "Tu portes un béret aujourd'hui ?", en: "Are you wearing a beret today?", de: "Trägst du heute eine Baskenmütze?", alt: { fr: ["Est-ce que tu portes un béret aujourd'hui ?", "Aujourd'hui, tu portes un béret ?", "Vous portez un béret aujourd'hui ?", "Est-ce que vous portez un béret aujourd'hui ?"], en: ["You are wearing a beret today?"], de: ["Trägst du heute ein Barett?", "Hast du heute eine Baskenmütze auf?"] } },
    // Lesson 6
    { id: "u09.35", lesson: 6, fr: "Je porte des chaussettes rouges.", en: "I'm wearing red socks.", de: "Ich trage rote Socken.", alt: { en: ["I wear red socks."], de: ["Ich habe rote Socken an."] } },
    { id: "u09.36", lesson: 6, fr: "Hugo porte une casquette bleue.", en: "Hugo is wearing a blue cap.", de: "Hugo trägt eine blaue Kappe.", alt: { en: ["Hugo wears a blue cap.", "Hugo is wearing a blue baseball cap."], de: ["Hugo trägt eine blaue Mütze.", "Hugo trägt eine blaue Schirmmütze.", "Hugo hat eine blaue Kappe auf.", "Hugo trägt ein blaues Cap."] } },
    { id: "u09.37", lesson: 6, fr: "Ses chaussures sont roses.", en: "Her shoes are pink.", de: "Ihre Schuhe sind rosa.", alt: { en: ["His shoes are pink."], de: ["Seine Schuhe sind rosa.", "Ihre Schuhe sind pink."] } },
    { id: "u09.38", lesson: 6, fr: "Nous portons des pulls verts.", en: "We're wearing green jumpers.", de: "Wir tragen grüne Pullover.", alt: { en: ["We wear green jumpers.", "We are wearing green sweaters.", "We wear green sweaters.", "We are wearing green pullovers."], de: ["Wir tragen grüne Pullis.", "Wir haben grüne Pullover an."] } },
    { id: "u09.39", lesson: 6, fr: "Les élèves portent des chemises blanches.", en: "The pupils are wearing white shirts.", de: "Die Schüler tragen weiße Hemden.", alt: { en: ["The pupils wear white shirts.", "The students are wearing white shirts.", "The students wear white shirts."], de: ["Die Schülerinnen tragen weiße Hemden.", "Die Schüler haben weiße Hemden an."] } },
    { id: "u09.40", lesson: 6, fr: "Est-ce que tu portes une casquette ?", en: "Are you wearing a cap?", de: "Trägst du eine Kappe?", alt: { fr: ["Tu portes une casquette ?", "Portes-tu une casquette ?", "Est-ce que vous portez une casquette ?", "Vous portez une casquette ?", "Portez-vous une casquette ?"], en: ["Do you wear a cap?", "You are wearing a cap?"], de: ["Trägst du eine Mütze?", "Hast du eine Kappe auf?", "Trägst du ein Cap?", "Du trägst eine Kappe?"] } },
    { id: "u09.41", lesson: 6, fr: "Vous portez des chaussettes noires, Monsieur Martin ?", en: "Are you wearing black socks, Mr Martin?", de: "Tragen Sie schwarze Socken, Herr Martin?", alt: { fr: ["Est-ce que vous portez des chaussettes noires, Monsieur Martin ?", "Portez-vous des chaussettes noires, Monsieur Martin ?", "Monsieur Martin, vous portez des chaussettes noires ?", "Monsieur Martin, est-ce que vous portez des chaussettes noires ?"], en: ["Mr Martin, are you wearing black socks?", "Do you wear black socks, Mr Martin?"], de: ["Herr Martin, tragen Sie schwarze Socken?"] } },
    { id: "u09.42", lesson: 6, fr: "J'aime ton pull rose !", en: "I like your pink jumper!", de: "Ich mag deinen rosa Pullover!", alt: { fr: ["J'aime votre pull rose !"], en: ["I love your pink jumper!", "I like your pink sweater!", "I love your pink sweater!"], de: ["Mir gefällt dein rosa Pullover!", "Ich mag deinen rosa Pulli!", "Mir gefällt dein rosa Pulli!", "Ich mag deinen pinken Pullover!"] } },
    // Lesson 7
    { id: "u09.43", lesson: 7, fr: "Blob est violet.", en: "Blob is purple.", de: "Blob ist lila.", alt: { en: ["Blob is violet."], de: ["Blob ist violett."] } },
    { id: "u09.44", lesson: 7, fr: "Léa porte une robe violette.", en: "Léa is wearing a purple dress.", de: "Léa trägt ein lila Kleid.", alt: { en: ["Léa wears a purple dress.", "Léa is wearing a violet dress."], de: ["Léa trägt ein violettes Kleid.", "Léa hat ein lila Kleid an."] } },
    { id: "u09.45", lesson: 7, fr: "Ces chaussettes violettes sont jolies.", en: "These purple socks are pretty.", de: "Diese lila Socken sind schön.", alt: { en: ["Those purple socks are pretty.", "These purple socks are nice.", "Those purple socks are nice.", "These purple socks are lovely."], de: ["Diese lila Socken sind hübsch.", "Diese violetten Socken sind schön."] } },
    { id: "u09.46", lesson: 7, fr: "Il ne porte pas de casquette.", en: "He's not wearing a cap.", de: "Er trägt keine Kappe.", alt: { en: ["He isn't wearing a cap.", "He doesn't wear a cap."], de: ["Er trägt keine Mütze.", "Er hat keine Kappe auf.", "Er trägt kein Cap."] } },
    { id: "u09.47", lesson: 7, fr: "Est-ce que ce pull est trop grand ?", en: "Is this jumper too big?", de: "Ist dieser Pullover zu groß?", alt: { fr: ["Ce pull est trop grand ?"], en: ["Is that jumper too big?", "Is this sweater too big?", "Is that sweater too big?"], de: ["Ist dieser Pulli zu groß?", "Ist der Pullover zu groß?"] } },
    { id: "u09.48", lesson: 7, fr: "Mes nouvelles chaussures sont violettes.", en: "My new shoes are purple.", de: "Meine neuen Schuhe sind lila.", alt: { en: ["My new shoes are violet."], de: ["Meine neuen Schuhe sind violett."] } },
    { id: "u09.49", lesson: 7, fr: "Vous aimez cette casquette violette ?", en: "Do you like this purple cap?", de: "Gefällt euch diese lila Kappe?", alt: { fr: ["Est-ce que vous aimez cette casquette violette ?", "Aimez-vous cette casquette violette ?", "Tu aimes cette casquette violette ?", "Est-ce que tu aimes cette casquette violette ?"], en: ["Do you like that purple cap?"], de: ["Mögt ihr diese lila Kappe?", "Gefällt Ihnen diese lila Kappe?", "Mögen Sie diese lila Kappe?"] } },
    { id: "u09.50", lesson: 7, fr: "Il porte un pull violet et un pantalon gris.", en: "He's wearing a purple jumper and grey trousers.", de: "Er trägt einen lila Pullover und eine graue Hose.", alt: { en: ["He wears a purple jumper and grey trousers.", "He is wearing a purple sweater and grey trousers.", "He is wearing a purple jumper and gray trousers.", "He is wearing a purple jumper and grey pants."], de: ["Er trägt einen lila Pulli und eine graue Hose.", "Er trägt einen violetten Pullover und eine graue Hose.", "Er hat einen lila Pullover und eine graue Hose an."] } },
  ],
  drills: [
    { id: "u09.d1", lesson: 1, fr: "La pomme est ___.", options: ["verte", "vert", "verts"], answer: 0, en: "The apple is green.", de: "Der Apfel ist grün.", why: tx("**Pomme** is feminine, so the colour gets an **e**: vert**e**. Now you hear the t.", "**Pomme** ist weiblich, also bekommt die Farbe ein **e**: vert**e**. Jetzt hört man das t.") },
    { id: "u09.d2", lesson: 1, fr: "La maison est ___.", options: ["blanche", "blanc"], answer: 0, en: "The house is white.", de: "Das Haus ist weiß.", why: tx("**Blanc** has a special feminine: **blanche**.", "**Blanc** hat eine besondere weibliche Form: **blanche**.") },
    { id: "u09.d3", lesson: 1, fr: "J'ai un chat ___.", options: ["noir", "noire", "noirs"], answer: 0, en: "I have a black cat.", de: "Ich habe eine schwarze Katze.", why: tx("**Chat** is masculine and singular: un chat **noir**. And the colour comes after the noun.", "**Chat** ist männlich und Singular: un chat **noir**. Und die Farbe steht nach dem Nomen.") },
    { id: "u09.d4", lesson: 2, fr: "Tu ___ un pull bleu ?", options: ["portes", "porte", "portez"], answer: 0, en: "Are you wearing a blue jumper?", de: "Trägst du einen blauen Pullover?", why: tx("With **tu**: tu port**es**, like tu parles.", "Mit **tu**: tu port**es**, wie tu parles.") },
    { id: "u09.d5", lesson: 2, fr: "Hugo ___ un pantalon noir.", options: ["porte", "portes", "portent"], answer: 0, en: "Hugo is wearing black trousers.", de: "Hugo trägt eine schwarze Hose.", why: tx("Hugo is **il**: il port**e**.", "Hugo ist **il**: il port**e**.") },
    { id: "u09.d6", lesson: 3, fr: "Elle porte une jupe ___.", options: ["grise", "gris", "grises"], answer: 0, en: "She's wearing a grey skirt.", de: "Sie trägt einen grauen Rock.", why: tx("**Jupe** is feminine: gris becomes **grise**.", "**Jupe** ist weiblich: gris wird zu **grise**.") },
    { id: "u09.d7", lesson: 3, fr: "Monsieur Martin porte une chemise ___.", options: ["blanche", "blanc"], answer: 0, en: "Mr Martin is wearing a white shirt.", de: "Herr Martin trägt ein weißes Hemd.", why: tx("**Chemise** is feminine: une chemise **blanche**.", "**Chemise** ist weiblich, anders als das Hemd: une chemise **blanche**.") },
    { id: "u09.d8", lesson: 4, fr: "___ robe est très jolie.", options: ["Cette", "Ce", "Ces"], answer: 0, en: "This dress is very pretty.", de: "Dieses Kleid ist sehr schön.", why: tx("**Robe** is feminine: **cette** robe. Ce is for masculine words: ce pull.", "**Robe** ist weiblich: **cette** robe. Ce steht vor männlichen Wörtern: ce pull.") },
    { id: "u09.d9", lesson: 4, fr: "J'aime ___ pull.", options: ["ce", "cette", "ces"], answer: 0, en: "I like this jumper.", de: "Ich mag diesen Pullover.", why: tx("**Pull** is masculine: **ce** pull.", "**Pull** ist männlich: **ce** pull.") },
    { id: "u09.d10", lesson: 4, fr: "___ chaussures sont jolies.", options: ["Ces", "Cette", "Ce"], answer: 0, en: "These shoes are pretty.", de: "Diese Schuhe sind schön.", why: tx("Plural: **ces**, for masculine and feminine words.", "Plural: **ces**, für männliche und weibliche Wörter.") },
    { id: "u09.d11", lesson: 4, fr: "C'est une ___ veste.", options: ["jolie", "joli", "jolis"], answer: 0, en: "It's a pretty jacket.", de: "Das ist eine schöne Jacke.", why: tx("**Veste** is feminine: **jolie**. And joli comes **before** the noun, unlike colours.", "**Veste** ist weiblich: **jolie**. Und joli steht **vor** dem Nomen, anders als Farben.") },
    { id: "u09.d12", lesson: 5, fr: "J'ai une ___ robe.", options: ["nouvelle", "nouveau"], answer: 0, en: "I have a new dress.", de: "Ich habe ein neues Kleid.", why: tx("**Robe** is feminine, so nouveau becomes **nouvelle**.", "**Robe** ist weiblich, also wird nouveau zu **nouvelle**.") },
    { id: "u09.d13", lesson: 6, fr: "Je porte des chaussettes ___.", options: ["rouges", "rouge"], answer: 0, en: "I'm wearing red socks.", de: "Ich trage rote Socken.", why: tx("**Chaussettes** is plural, so the colour gets an **s**: rouge**s**. You don't hear it.", "**Chaussettes** ist Plural, also bekommt die Farbe ein **s**: rouge**s**. Man hört es nicht.") },
    { id: "u09.d14", lesson: 6, fr: "Les élèves ___ des chemises blanches.", options: ["portent", "porte", "portez"], answer: 0, en: "The pupils are wearing white shirts.", de: "Die Schüler tragen weiße Hemden.", why: tx("Les élèves = **ils**: ils port**ent**. The -ent is silent.", "Les élèves = **ils**: ils port**ent**. Das -ent ist stumm.") },
    { id: "u09.d15", lesson: 6, fr: "Hugo porte une casquette ___.", options: ["bleue", "bleu", "bleus"], answer: 0, en: "Hugo is wearing a blue cap.", de: "Hugo trägt eine blaue Kappe.", why: tx("**Casquette** is feminine: bleu becomes **bleue**. It sounds the same.", "**Casquette** ist weiblich: bleu wird zu **bleue**. Es klingt gleich.") },
    { id: "u09.d16", lesson: 7, fr: "Léa porte une robe ___.", options: ["violette", "violet", "violettes"], answer: 0, en: "Léa is wearing a purple dress.", de: "Léa trägt ein lila Kleid.", why: tx("**Robe** is feminine: violet becomes **violette**, with a double t.", "**Robe** ist weiblich: violet wird zu **violette**, mit Doppel-t.") },
    { id: "u09.d17", lesson: 7, fr: "Mes ___ chaussures sont violettes.", options: ["nouvelles", "nouveau", "nouvelle"], answer: 0, en: "My new shoes are purple.", de: "Meine neuen Schuhe sind lila.", why: tx("**Chaussures** is feminine and plural: **nouvelles**. And nouveau comes before the noun.", "**Chaussures** ist weiblich und Plural: **nouvelles**. Und nouveau steht vor dem Nomen.") },
    { id: "u09.d18", lesson: 7, fr: "___ casquette violette est jolie.", options: ["Cette", "Ce", "Ces"], answer: 0, en: "This purple cap is pretty.", de: "Diese lila Kappe ist schön.", why: tx("**Casquette** is feminine: **cette** casquette.", "**Casquette** ist weiblich: **cette** casquette.") },
  ],
  dialogues: [
    {
      id: "u09.dialogue",
      lesson: 5,
      title: tx("Blob goes shopping", "Blob geht einkaufen"),
      lines: [
        { who: "vendeur", fr: "Bonjour ! Un t-shirt, un pull, une chemise ?", en: "Hello! A T-shirt, a jumper, a shirt?", de: "Guten Tag! Ein T-Shirt, einen Pullover, ein Hemd?" },
        { who: "blob", fr: "Bonjour ! J'aime ce t-shirt jaune.", en: "Hello! I like this yellow T-shirt.", de: "Hallo! Ich mag dieses gelbe T-Shirt." },
        { who: "lea", fr: "Blob, il est trop petit !", en: "Blob, it's too small!", de: "Blob, das ist zu klein!" },
        { who: "vendeur", fr: "Et ce pantalon gris ? Il est très joli.", en: "And these grey trousers? They're very nice.", de: "Und diese graue Hose? Sie ist sehr schön." },
        { who: "blob", fr: "Un pantalon ? Mais je n'ai pas de jambes !", en: "Trousers? But I don't have any legs!", de: "Eine Hose? Aber ich habe keine Beine!" },
        { who: "hugo", fr: "Et ça, Blob ? Un béret noir !", en: "And this, Blob? A black beret!", de: "Und das hier, Blob? Eine schwarze Baskenmütze!" },
        { who: "blob", fr: "Oh, il est joli ! Regarde, je porte le béret !", en: "Oh, it's nice! Look, I'm wearing the beret!", de: "Oh, die ist schön! Schau mal, ich trage die Baskenmütze!" },
        { who: "lea", fr: "Parfait ! C'est très français !", en: "Perfect! It's very French!", de: "Perfekt! Das ist sehr französisch!" },
        { who: "blob", fr: "Merci ! Je porte mon béret le lundi, le mardi, le mercredi… et le week-end !", en: "Thank you! I'll wear my beret on Mondays, Tuesdays, Wednesdays… and at weekends!", de: "Danke! Ich trage meine Baskenmütze montags, dienstags, mittwochs … und am Wochenende!" },
      ],
      questions: [
        { q: tx("Why doesn't Blob take the yellow T-shirt?", "Warum nimmt Blob das gelbe T-Shirt nicht?"), options: [tx("It's too small.", "Es ist zu klein."), tx("Blob doesn't like yellow.", "Blob mag kein Gelb."), tx("It's too big.", "Es ist zu groß.")], answer: 0 },
        { q: tx("What's the problem with the trousers?", "Was ist das Problem mit der Hose?"), options: [tx("Blob has no legs.", "Blob hat keine Beine."), tx("They're grey.", "Sie ist grau."), tx("They're too small.", "Sie ist zu klein.")], answer: 0 },
        { q: tx("What colour is the beret?", "Welche Farbe hat die Baskenmütze?"), options: [tx("Black", "Schwarz"), tx("Yellow", "Gelb"), tx("Grey", "Grau")], answer: 0 },
      ],
    },
    {
      id: "u09.dialogue2",
      lesson: 7,
      title: tx("Everything in purple", "Alles in Lila"),
      lines: [
        { who: "vendeur", fr: "Bonjour, Blob ! Tu aimes ce pull rose ?", en: "Hello, Blob! Do you like this pink jumper?", de: "Hallo, Blob! Magst du diesen rosa Pullover?" },
        { who: "blob", fr: "Rose ? Non ! J'aime le violet !", en: "Pink? No! I like purple!", de: "Rosa? Nein! Ich mag Lila!" },
        { who: "vendeur", fr: "Violet ? Euh… j'ai des chaussettes violettes.", en: "Purple? Er… I have purple socks.", de: "Lila? Äh … ich habe lila Socken." },
        { who: "lea", fr: "Mais Blob, tu n'as pas de pieds !", en: "But Blob, you don't have any feet!", de: "Aber Blob, du hast keine Füße!" },
        { who: "blob", fr: "Oh… Alors, une casquette violette ?", en: "Oh… A purple cap, then?", de: "Oh … Dann eine lila Kappe?" },
        { who: "vendeur", fr: "Une casquette violette ? Non, mais j'ai un béret violet !", en: "A purple cap? No, but I have a purple beret!", de: "Eine lila Kappe? Nein, aber ich habe eine lila Baskenmütze!" },
        { who: "blob", fr: "Un nouveau béret violet ? J'adore !", en: "A new purple beret? I love it!", de: "Eine neue lila Baskenmütze? Toll!" },
        { who: "hugo", fr: "Blob, tu portes ton béret noir aujourd'hui…", en: "Blob, you're wearing your black beret today…", de: "Blob, du trägst heute deine schwarze Baskenmütze …" },
        { who: "blob", fr: "Oui, mais maintenant, j'ai deux bérets !", en: "Yes, but now I have two berets!", de: "Ja, aber jetzt habe ich zwei Baskenmützen!" },
      ],
      questions: [
        { q: tx("What colour does Blob like?", "Welche Farbe mag Blob?"), options: [tx("Purple", "Lila"), tx("Pink", "Rosa"), tx("Black", "Schwarz")], answer: 0 },
        { q: tx("Why are socks no good for Blob?", "Warum sind Socken nichts für Blob?"), options: [tx("He has no feet.", "Er hat keine Füße."), tx("They're pink.", "Sie sind rosa."), tx("They're too big.", "Sie sind zu groß.")], answer: 0 },
        { q: tx("What does Blob get in the end?", "Was bekommt Blob am Ende?"), options: [tx("A purple beret", "Eine lila Baskenmütze"), tx("A purple cap", "Eine lila Kappe"), tx("Purple socks", "Lila Socken")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Colours agree", "Farben passen sich an"),
      body: tx(
        "In French a colour comes **after** the noun and **agrees** with it: add **-e** for a feminine noun, **-s** for a plural one. Un pull vert, une robe vert**e**, des chaussures vert**es**.\n\nColours that already end in -e (rouge, jaune) don't get a second one: une robe rouge, but des robes rouge**s**. Watch out for **blanc → blanche**.",
        "Im Französischen steht die Farbe **nach** dem Nomen und **passt sich an**: **-e** für ein weibliches Nomen, **-s** für den Plural. Un pull vert, une robe vert**e**, des chaussures vert**es**.\n\nFarben, die schon auf -e enden (rouge, jaune), bekommen kein zweites: une robe rouge, aber des robes rouge**s**. Achtung: **blanc → blanche**.",
      ),
      examples: [
        { fr: "Je porte un pull vert.", en: "I'm wearing a green jumper.", de: "Ich trage einen grünen Pullover." },
        { fr: "Elle porte une robe rouge.", en: "She's wearing a red dress.", de: "Sie trägt ein rotes Kleid." },
        { fr: "Mes chaussures sont blanches.", en: "My shoes are white.", de: "Meine Schuhe sind weiß." },
      ],
      table: {
        head: [tx("colour", "Farbe"), tx("masculine", "männlich"), tx("feminine", "weiblich")],
        rows: [
          [tx("green", "grün"), "vert", "verte"],
          [tx("black", "schwarz"), "noir", "noire"],
          [tx("blue", "blau"), "bleu", "bleue"],
          [tx("grey", "grau"), "gris", "grise"],
          [tx("white", "weiß"), "blanc", "blanche"],
          [tx("red", "rot"), "rouge", "rouge"],
        ],
      },
    },
    {
      title: tx("Porter: to wear", "Porter: tragen"),
      body: tx(
        "**Porter** (to wear) is a regular -er verb, just like parler: je port**e**, tu port**es**, il port**e**…\n\nOne surprise: **un pantalon** is singular in French. Mon pantalon est bleu: my trousers are blue.",
        "**Porter** (tragen) ist ein regelmäßiges -er-Verb, genau wie parler: je port**e**, tu port**es**, il port**e** …\n\nWie im Deutschen ist **un pantalon** (die Hose) Singular: mon pantalon est bleu.",
      ),
      examples: [
        { fr: "Je porte un t-shirt rouge.", en: "I'm wearing a red T-shirt.", de: "Ich trage ein rotes T-Shirt." },
        { fr: "Tu portes une veste ?", en: "Are you wearing a jacket?", de: "Trägst du eine Jacke?" },
        { fr: "Hugo porte un pantalon noir.", en: "Hugo is wearing black trousers.", de: "Hugo trägt eine schwarze Hose." },
      ],
      table: {
        head: [tx("person", "Person"), "porter"],
        rows: [
          [tx("I", "ich"), "je porte"],
          [tx("you", "du"), "tu portes"],
          [tx("he / she", "er / sie"), "il / elle porte"],
          [tx("we", "wir"), "nous portons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous portez"],
          [tx("they", "sie"), "ils / elles portent"],
        ],
      },
    },
    {
      title: tx("Ce, cette, ces: this and these", "Ce, cette, ces: dieser, diese, dieses"),
      body: tx(
        "**Ce** for a masculine noun (ce pull), **cette** for a feminine one (cette robe), **ces** for the plural (ces chaussures). Before a vowel, ce becomes **cet**: cet élève.\n\nAnd a few adjectives like **joli** (pretty) and **nouveau** (new) come **before** the noun: une jolie robe, un nouveau béret.",
        "**Ce** vor einem männlichen Nomen (ce pull), **cette** vor einem weiblichen (cette robe), **ces** im Plural (ces chaussures). Vor einem Vokal wird ce zu **cet**: cet élève.\n\nUnd ein paar Adjektive wie **joli** (schön) und **nouveau** (neu) stehen **vor** dem Nomen: une jolie robe, un nouveau béret.",
      ),
      examples: [
        { fr: "J'aime ce pull.", en: "I like this jumper.", de: "Ich mag diesen Pullover." },
        { fr: "Cette robe est très jolie.", en: "This dress is very pretty.", de: "Dieses Kleid ist sehr schön." },
        { fr: "C'est un nouveau béret ?", en: "Is it a new beret?", de: "Ist das eine neue Baskenmütze?" },
      ],
    },
    {
      title: tx("Colours in the plural", "Farben im Plural"),
      body: tx(
        "With a plural noun, the colour is plural too: add **-s**. Des chaussettes rouge**s**, des pulls vert**s**, des chemises blanch**es**. You don't hear the s!\n\n**Violet** (purple, Blob's colour) doubles its t in the feminine: une robe **violette**. **Rose** (pink) already ends in -e, like rouge: un pull rose, une casquette rose.",
        "Bei einem Nomen im Plural steht auch die Farbe im Plural: mit **-s**. Des chaussettes rouge**s**, des pulls vert**s**, des chemises blanch**es**. Das s hört man nicht!\n\n**Violet** (lila, Blobs Farbe) verdoppelt in der weiblichen Form das t: une robe **violette**. **Rose** (rosa) endet schon auf -e, wie rouge: un pull rose, une casquette rose.",
      ),
      examples: [
        { fr: "Je porte des chaussettes rouges.", en: "I'm wearing red socks.", de: "Ich trage rote Socken." },
        { fr: "Léa porte une robe violette.", en: "Léa is wearing a purple dress.", de: "Léa trägt ein lila Kleid." },
        { fr: "Mes nouvelles chaussures sont violettes.", en: "My new shoes are purple.", de: "Meine neuen Schuhe sind lila." },
      ],
      table: {
        head: [tx("colour", "Farbe"), tx("singular (m / f)", "Singular (m / w)"), tx("plural (m / f)", "Plural (m / w)")],
        rows: [
          [tx("green", "grün"), "vert / verte", "verts / vertes"],
          [tx("purple", "lila"), "violet / violette", "violets / violettes"],
          [tx("white", "weiß"), "blanc / blanche", "blancs / blanches"],
          [tx("pink", "rosa"), "rose / rose", "roses / roses"],
        ],
      },
    },
  ],
};
