import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 10: ordering at the café with je voudrais, polite vous, and prices in euros. */
export const u10: Unit = {
  slug: "cafe",
  n: 10,
  cefr: "A1",
  title: tx("At the café", "Im Café"),
  goal: tx("Order food and drinks politely and pay", "Höflich Essen und Getränke bestellen und bezahlen"),
  emoji: "☕",
  words: [
    { id: "cafe", fr: "le café", en: "the coffee", de: "der Kaffee", alt: { en: ["the café"], de: ["das Café"] }, g: "m", kind: "noun", emoji: "☕", note: tx("The drink and the place where you drink it.", "Das Getränk und der Ort, wo man es trinkt.") },
    { id: "the", fr: "le thé", en: "the tea", de: "der Tee", g: "m", kind: "noun", emoji: "🍵" },
    { id: "limonade", fr: "la limonade", en: "the lemonade", de: "die Limonade", alt: { de: ["die Limo"] }, g: "f", kind: "noun", emoji: "🥤", note: tx("French limonade is clear and fizzy, like a lemon soda.", "Französische Limonade ist klar und sprudelt, wie eine Zitronenlimo.") },
    { id: "jus-d-orange", fr: "le jus d'orange", en: "the orange juice", de: "der Orangensaft", alt: { de: ["der O-Saft"] }, g: "m", kind: "noun", emoji: "🧃" },
    { id: "je-voudrais", fr: "je voudrais", en: "I would like", de: "ich hätte gern", alt: { de: ["ich möchte"] }, kind: "verb", note: tx("The polite way to ask for something. Much nicer than je veux (I want).", "Die höfliche Art, um etwas zu bitten. Viel netter als je veux (ich will).") },
    { id: "s-il-vous-plait", fr: "s'il vous plaît", en: "please", de: "bitte", kind: "phrase", note: tx("The polite please, with vous: to the waiter, to adults, to a group.", "Das höfliche Bitte, mit vous: zum Kellner, zu Erwachsenen, zu mehreren.") },
    { id: "crepe", fr: "la crêpe", en: "the crêpe", de: "die Crêpe", alt: { en: ["the pancake"], de: ["der Pfannkuchen"] }, g: "f", kind: "noun", emoji: "🥞", note: tx("Thin French pancakes, sweet or savoury. Une crêpe au chocolat !", "Dünne französische Pfannkuchen, süß oder herzhaft. Une crêpe au chocolat !") },
    { id: "glace", fr: "la glace", en: "the ice cream", de: "das Eis", g: "f", kind: "noun", emoji: "🍨", note: tx("La glace is also ice, and a mirror!", "La glace ist auch Eis zum Schlittschuhlaufen, und ein Spiegel!") },
    { id: "gateau", fr: "le gâteau", en: "the cake", de: "der Kuchen", alt: { de: ["die Torte"] }, g: "m", kind: "noun", emoji: "🍰", note: tx("Plural with an x: des gâteaux.", "Plural mit x: des gâteaux.") },
    { id: "croque-monsieur", fr: "le croque-monsieur", en: "the croque-monsieur", de: "der Croque Monsieur", alt: { en: ["the toasted ham and cheese sandwich"] }, g: "m", kind: "noun", emoji: "🥪", note: tx("A hot toasted sandwich with ham and cheese. With an egg on top, it's a croque-madame!", "Ein heißes Toastsandwich mit Schinken und Käse. Mit Spiegelei obendrauf ist es ein Croque Madame!") },
    { id: "s-il-te-plait", fr: "s'il te plaît", en: "please (to a friend)", de: "bitte (zu Freunden)", kind: "phrase", note: tx("With tu: to friends and family.", "Mit tu: zu Freunden und zur Familie.") },
    { id: "serveur", fr: "le serveur", en: "the waiter", de: "der Kellner", g: "m", kind: "noun", emoji: "🤵", note: tx("A waitress: la serveuse. To call them, just say Monsieur ! or Madame !", "Eine Kellnerin: la serveuse. Zum Rufen sagst du einfach Monsieur ! oder Madame !") },
    { id: "carte", fr: "la carte", en: "the menu", de: "die Karte", alt: { de: ["die Speisekarte"] }, g: "f", kind: "noun", note: tx("Also a card or a map. Careful: le menu is a set meal!", "Auch Karte oder Landkarte. Vorsicht: le menu ist ein festes Menü!") },
    { id: "vous-desirez", fr: "vous désirez ?", en: "what would you like?", de: "was darf es sein?", alt: { en: ["can I help you?"], de: ["Sie wünschen?"] }, kind: "phrase", note: tx("What the waiter says. Literally «you wish?»", "Das sagt der Kellner. Wörtlich „Sie wünschen?“") },
    { id: "voila", fr: "voilà", en: "here you are", de: "bitte schön", alt: { en: ["here it is", "there you go"], de: ["hier, bitte", "da ist es"] }, kind: "word", note: tx("Also: there it is, that's it. The French say it all the time!", "Auch: da ist es, das war's. Franzosen sagen es ständig!") },
    { id: "bien-sur", fr: "bien sûr", en: "of course", de: "natürlich", alt: { en: ["sure"], de: ["klar", "selbstverständlich"] }, kind: "phrase" },
    { id: "c-est-combien", fr: "c'est combien ?", en: "how much is it?", de: "was kostet das?", alt: { de: ["wie viel kostet das?"] }, kind: "phrase", note: tx("Point at something and ask: c'est combien ?", "Zeig auf etwas und frag: c'est combien ?") },
    { id: "euros", fr: "euros", en: "euros", de: "Euro", kind: "word", emoji: "💶", note: tx("The s is silent, but you link it: deux euros sounds like «deu-zeuros».", "Das s ist stumm, aber man bindet: deux euros klingt wie „dö-söro“ mit weichem s.") },
    { id: "addition", fr: "l'addition", en: "the bill", de: "die Rechnung", alt: { en: ["the check"] }, g: "f", kind: "noun", emoji: "🧾", note: tx("In maths it's adding up. At the café, it's the bill!", "In Mathe ist es das Addieren. Im Café ist es die Rechnung!") },
    { id: "et-avec-ca", fr: "et avec ça ?", en: "anything else?", de: "sonst noch etwas?", alt: { de: ["darf es noch etwas sein?"] }, kind: "phrase", note: tx("Literally «and with that?». You hear it in every café and shop.", "Wörtlich „und dazu?“. Das hörst du in jedem Café und Geschäft.") },
    { id: "chaud", fr: "chaud", en: "hot", de: "heiß", alt: { en: ["warm"], de: ["warm"] }, kind: "adj", emoji: "🔥", note: tx("Un chocolat chaud: a hot chocolate. Il fait chaud: it's hot (the weather).", "Un chocolat chaud: eine heiße Schokolade. Il fait chaud: Es ist heiß (das Wetter).") },
    { id: "froid", fr: "froid", en: "cold", de: "kalt", kind: "adj", emoji: "🧊", note: tx("Feminine: froide, and you hear the d.", "Weiblich: froide, und man hört das d.") },
  ],
  gloss: [
    { fr: "voudrais", en: "would like", de: "möchte / möchtest" },
    { fr: "bois", en: "drink", de: "trinke / trinkst" },
    { fr: "crêpes", en: "crêpes", de: "Crêpes" },
    { fr: "votre", en: "your (plural / polite)", de: "euer / Ihr" },
    { fr: "ça fait", en: "that makes / that's", de: "das macht" },
    { fr: "cinquante", en: "fifty", de: "fünfzig" },
    { fr: "attention", en: "careful / watch out", de: "Vorsicht" },
    { fr: "froide", en: "cold (feminine)", de: "kalt (weiblich)" },
    { fr: "bien froid", en: "nice and cold", de: "schön kalt" },
    { fr: "il fait chaud", en: "it's hot (weather)", de: "es ist heiß" },
    { fr: "papa", en: "dad", de: "Papa" },
    { fr: "bon", en: "well / OK", de: "na gut / gut" },
    { fr: "d'accord", en: "OK / all right", de: "einverstanden / okay" },
  ],
  lessons: [
    { title: tx("Something to drink", "Etwas zu trinken"), words: ["cafe", "the", "limonade", "jus-d-orange", "je-voudrais", "s-il-vous-plait"] },
    { title: tx("Something sweet", "Etwas Süßes"), words: ["crepe", "glace", "gateau", "croque-monsieur", "s-il-te-plait"] },
    { title: tx("The waiter", "Der Kellner"), words: ["serveur", "carte", "vous-desirez", "voila", "bien-sur"] },
    { title: tx("How much is it?", "Was kostet das?"), words: ["c-est-combien", "euros", "addition", "et-avec-ca"] },
    { title: tx("Hot and cold", "Heiß und kalt"), words: ["chaud", "froid"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u10.01", lesson: 1, fr: "Je voudrais un café, s'il vous plaît.", en: "I'd like a coffee, please.", de: "Ich hätte gern einen Kaffee, bitte.", alt: { fr: ["Je voudrais un café, s'il te plaît."], de: ["Ich hätte gerne einen Kaffee, bitte.", "Ich möchte einen Kaffee, bitte.", "Ich möchte bitte einen Kaffee.", "Ich hätte gern bitte einen Kaffee.", "Ich hätte bitte gern einen Kaffee."] } },
    { id: "u10.02", lesson: 1, fr: "Un thé, s'il vous plaît.", en: "A tea, please.", de: "Einen Tee, bitte.", alt: { fr: ["Un thé, s'il te plaît."], en: ["One tea, please."], de: ["Ein Tee, bitte."] } },
    { id: "u10.03", lesson: 1, fr: "Je voudrais une limonade.", en: "I'd like a lemonade.", de: "Ich hätte gern eine Limonade.", alt: { en: ["I'd like some lemonade."], de: ["Ich hätte gerne eine Limonade.", "Ich möchte eine Limonade.", "Ich hätte gern eine Limo.", "Ich möchte eine Limo."] } },
    { id: "u10.04", lesson: 1, fr: "Tu voudrais un jus d'orange ?", en: "Would you like an orange juice?", de: "Möchtest du einen Orangensaft?", alt: { fr: ["Est-ce que tu voudrais un jus d'orange ?", "Voudrais-tu un jus d'orange ?", "Tu veux un jus d'orange ?", "Vous voudriez un jus d'orange ?", "Vous voulez un jus d'orange ?", "Voulez-vous un jus d'orange ?"], en: ["Would you like some orange juice?", "Would you like orange juice?", "Do you want an orange juice?"], de: ["Hättest du gern einen Orangensaft?", "Möchtest du einen O-Saft?", "Willst du einen Orangensaft?"] } },
    { id: "u10.05", lesson: 1, fr: "Je ne bois pas de café.", en: "I don't drink coffee.", de: "Ich trinke keinen Kaffee.", alt: { en: ["I don't drink any coffee.", "I am not drinking coffee."] } },
    { id: "u10.06", lesson: 1, fr: "Pour moi, un jus d'orange.", en: "An orange juice for me.", de: "Für mich einen Orangensaft.", alt: { fr: ["Un jus d'orange pour moi."], en: ["For me, an orange juice."], de: ["Einen Orangensaft für mich.", "Für mich einen O-Saft.", "Für mich ein Orangensaft."] } },
    { id: "u10.07", lesson: 1, fr: "Un café et un thé, s'il vous plaît.", en: "A coffee and a tea, please.", de: "Einen Kaffee und einen Tee, bitte.", alt: { fr: ["Un café et un thé, s'il te plaît."], en: ["One coffee and one tea, please."], de: ["Ein Kaffee und ein Tee, bitte."] } },
    // Lesson 2
    { id: "u10.08", lesson: 2, fr: "Je voudrais une crêpe au chocolat.", en: "I'd like a chocolate crêpe.", de: "Ich hätte gern eine Crêpe mit Schokolade.", alt: { en: ["I'd like a crêpe with chocolate.", "I'd like a chocolate pancake."], de: ["Ich hätte gerne eine Crêpe mit Schokolade.", "Ich möchte eine Crêpe mit Schokolade.", "Ich hätte gern einen Crêpe mit Schokolade.", "Ich möchte einen Crêpe mit Schokolade.", "Ich hätte gern eine Schokoladencrêpe."] } },
    { id: "u10.09", lesson: 2, fr: "Une glace, s'il te plaît, papa !", en: "An ice cream, please, Dad!", de: "Ein Eis, bitte, Papa!", alt: { en: ["Ice cream, please, Dad!", "An ice cream, please, Daddy!"] } },
    { id: "u10.10", lesson: 2, fr: "Le gâteau est délicieux !", en: "The cake is delicious!", de: "Der Kuchen ist köstlich!", alt: { de: ["Der Kuchen ist lecker!", "Die Torte ist köstlich!", "Die Torte ist lecker!"] } },
    { id: "u10.11", lesson: 2, fr: "Tu voudrais un croque-monsieur ?", en: "Would you like a croque-monsieur?", de: "Möchtest du einen Croque Monsieur?", alt: { fr: ["Est-ce que tu voudrais un croque-monsieur ?", "Tu veux un croque-monsieur ?", "Vous voudriez un croque-monsieur ?", "Vous voulez un croque-monsieur ?", "Voulez-vous un croque-monsieur ?"], en: ["Would you like a toasted ham and cheese sandwich?", "Do you want a croque-monsieur?"], de: ["Hättest du gern einen Croque Monsieur?", "Willst du einen Croque Monsieur?"] } },
    { id: "u10.12", lesson: 2, fr: "Une crêpe pour moi et une glace pour Léa.", en: "A crêpe for me and an ice cream for Léa.", de: "Eine Crêpe für mich und ein Eis für Léa.", alt: { en: ["A pancake for me and an ice cream for Léa."], de: ["Einen Crêpe für mich und ein Eis für Léa."] } },
    { id: "u10.13", lesson: 2, fr: "J'aime le gâteau au chocolat.", en: "I like chocolate cake.", de: "Ich mag Schokoladenkuchen.", alt: { en: ["I love chocolate cake.", "I like the chocolate cake.", "I love the chocolate cake."], de: ["Ich liebe Schokoladenkuchen.", "Ich mag den Schokoladenkuchen.", "Ich mag Schokokuchen.", "Ich liebe Schokokuchen."] } },
    { id: "u10.14", lesson: 2, fr: "Tu aimes la glace ?", en: "Do you like ice cream?", de: "Magst du Eis?", alt: { fr: ["Est-ce que tu aimes la glace ?", "Aimes-tu la glace ?", "Vous aimez la glace ?", "Est-ce que vous aimez la glace ?", "Aimez-vous la glace ?"], en: ["Do you love ice cream?"], de: ["Isst du gern Eis?", "Isst du gerne Eis?"] } },
    // Lesson 3
    { id: "u10.15", lesson: 3, fr: "Vous désirez ?", en: "What would you like?", de: "Was darf es sein?", alt: { fr: ["Qu'est-ce que vous désirez ?", "Que désirez-vous ?"], en: ["What can I get you?", "Can I help you?"], de: ["Was möchten Sie?", "Was wünschen Sie?", "Sie wünschen?", "Was hätten Sie gern?", "Was möchtet ihr?"] } },
    { id: "u10.16", lesson: 3, fr: "La carte, s'il vous plaît.", en: "The menu, please.", de: "Die Karte, bitte.", alt: { fr: ["La carte, s'il te plaît."], de: ["Die Speisekarte, bitte."] } },
    { id: "u10.17", lesson: 3, fr: "Voilà la carte.", en: "Here's the menu.", de: "Hier ist die Karte.", alt: { en: ["Here you are, the menu.", "There's the menu."], de: ["Hier ist die Speisekarte.", "Bitte schön, die Karte.", "Da ist die Karte."] } },
    { id: "u10.18", lesson: 3, fr: "Le serveur est très sympa.", en: "The waiter is very nice.", de: "Der Kellner ist sehr nett.", alt: { en: ["The waiter is very friendly.", "The waiter is really nice."], de: ["Der Kellner ist sehr freundlich.", "Der Kellner ist sehr sympathisch."] } },
    { id: "u10.19", lesson: 3, fr: "Bien sûr, Madame Martin !", en: "Of course, Mrs Martin!", de: "Natürlich, Frau Martin!", alt: { en: ["Certainly, Mrs Martin!", "Sure, Mrs Martin!"], de: ["Selbstverständlich, Frau Martin!", "Klar, Frau Martin!", "Sicher, Frau Martin!"] } },
    { id: "u10.20", lesson: 3, fr: "Voilà votre café, Monsieur Martin.", en: "Here's your coffee, Mr Martin.", de: "Hier ist Ihr Kaffee, Herr Martin.", alt: { en: ["Here you are, your coffee, Mr Martin."], de: ["Bitte schön, Ihr Kaffee, Herr Martin."] } },
    { id: "u10.21", lesson: 3, fr: "Est-ce que vous avez des crêpes ?", en: "Do you have crêpes?", de: "Haben Sie Crêpes?", alt: { fr: ["Vous avez des crêpes ?", "Avez-vous des crêpes ?", "Est-ce que tu as des crêpes ?", "Tu as des crêpes ?"], en: ["Do you have any crêpes?", "Have you got crêpes?", "Have you got any crêpes?", "Do you have pancakes?", "Do you have any pancakes?"], de: ["Habt ihr Crêpes?", "Gibt es Crêpes?"] } },
    // Lesson 4
    { id: "u10.22", lesson: 4, fr: "C'est combien, le gâteau ?", en: "How much is the cake?", de: "Was kostet der Kuchen?", alt: { fr: ["Le gâteau, c'est combien ?", "Combien coûte le gâteau ?"], en: ["How much does the cake cost?"], de: ["Wie viel kostet der Kuchen?", "Wieviel kostet der Kuchen?"] } },
    { id: "u10.23", lesson: 4, fr: "C'est trois euros.", en: "It's three euros.", de: "Das kostet drei Euro.", alt: { fr: ["Ça fait trois euros."], en: ["It's 3 euros.", "That's three euros.", "That's 3 euros.", "It costs three euros.", "It costs 3 euros."], de: ["Das kostet 3 Euro.", "Das sind drei Euro.", "Das sind 3 Euro.", "Es kostet drei Euro.", "Es kostet 3 Euro.", "Das macht drei Euro.", "Das macht 3 Euro."] } },
    { id: "u10.24", lesson: 4, fr: "L'addition, s'il vous plaît !", en: "The bill, please!", de: "Die Rechnung, bitte!", alt: { fr: ["L'addition, s'il te plaît !"], en: ["The check, please!"], de: ["Zahlen, bitte!"] } },
    { id: "u10.25", lesson: 4, fr: "Ça fait douze euros.", en: "That's twelve euros.", de: "Das macht zwölf Euro.", alt: { fr: ["C'est douze euros."], en: ["That's 12 euros.", "That comes to twelve euros.", "That comes to 12 euros.", "That makes twelve euros.", "That makes 12 euros.", "It's twelve euros.", "It's 12 euros."], de: ["Das macht 12 Euro.", "Das sind zwölf Euro.", "Das sind 12 Euro.", "Das kostet zwölf Euro.", "Das kostet 12 Euro."] } },
    { id: "u10.26", lesson: 4, fr: "Et avec ça ?", en: "Anything else?", de: "Sonst noch etwas?", alt: { en: ["And with that?", "Is there anything else?", "Will there be anything else?", "Something else?"], de: ["Darf es noch etwas sein?", "Noch etwas?", "Sonst noch was?", "Und dazu?"] } },
    { id: "u10.27", lesson: 4, fr: "Une crêpe, c'est combien ?", en: "How much is a crêpe?", de: "Was kostet eine Crêpe?", alt: { fr: ["C'est combien, une crêpe ?", "Combien coûte une crêpe ?"], en: ["How much does a crêpe cost?", "How much is one crêpe?", "How much for a crêpe?"], de: ["Wie viel kostet eine Crêpe?", "Was kostet ein Crêpe?", "Wie viel kostet ein Crêpe?"] } },
    { id: "u10.28", lesson: 4, fr: "Le café, c'est deux euros cinquante.", en: "The coffee is two euros fifty.", de: "Der Kaffee kostet zwei Euro fünfzig.", alt: { fr: ["Le café, ça fait deux euros cinquante."], en: ["The coffee is 2.50 euros.", "The coffee costs two euros fifty.", "The coffee costs 2.50 euros.", "The coffee is two fifty."], de: ["Der Kaffee kostet 2,50 Euro.", "Der Kaffee kostet zwei fünfzig."] } },
    // Lesson 5
    { id: "u10.29", lesson: 5, fr: "Attention, le thé est très chaud !", en: "Careful, the tea is very hot!", de: "Vorsicht, der Tee ist sehr heiß!", alt: { en: ["Be careful, the tea is very hot!", "Watch out, the tea is very hot!"], de: ["Achtung, der Tee ist sehr heiß!"] } },
    { id: "u10.30", lesson: 5, fr: "La limonade est froide.", en: "The lemonade is cold.", de: "Die Limonade ist kalt.", alt: { de: ["Die Limo ist kalt."] } },
    { id: "u10.31", lesson: 5, fr: "Je voudrais un chocolat chaud.", en: "I'd like a hot chocolate.", de: "Ich hätte gern eine heiße Schokolade.", alt: { de: ["Ich hätte gerne eine heiße Schokolade.", "Ich möchte eine heiße Schokolade.", "Ich hätte gern einen Kakao.", "Ich hätte gerne einen Kakao.", "Ich möchte einen Kakao."] } },
    { id: "u10.32", lesson: 5, fr: "Le café n'est pas chaud !", en: "The coffee isn't hot!", de: "Der Kaffee ist nicht heiß!", alt: { en: ["The coffee is not warm!"], de: ["Der Kaffee ist nicht warm!"] } },
    { id: "u10.33", lesson: 5, fr: "Un jus d'orange bien froid, s'il vous plaît.", en: "A nice cold orange juice, please.", de: "Einen schön kalten Orangensaft, bitte.", alt: { fr: ["Un jus d'orange bien froid, s'il te plaît."], en: ["A very cold orange juice, please.", "An ice-cold orange juice, please."], de: ["Einen richtig kalten Orangensaft, bitte.", "Einen sehr kalten Orangensaft, bitte.", "Einen eiskalten Orangensaft, bitte."] } },
    { id: "u10.34", lesson: 5, fr: "Il fait chaud, je voudrais une glace !", en: "It's hot, I'd like an ice cream!", de: "Es ist heiß, ich hätte gern ein Eis!", alt: { en: ["It's warm, I'd like an ice cream!"], de: ["Es ist heiß, ich hätte gerne ein Eis!", "Es ist heiß, ich möchte ein Eis!", "Es ist warm, ich hätte gern ein Eis!", "Es ist warm, ich möchte ein Eis!"] } },
  ],
  drills: [
    { id: "u10.d1", lesson: 1, fr: "Je voudrais ___ café.", options: ["un", "une"], answer: 0, en: "I'd like a coffee.", de: "Ich hätte gern einen Kaffee.", why: tx("**Café** is masculine: **un** café, le café.", "**Café** ist männlich: **un** café, le café.") },
    { id: "u10.d2", lesson: 1, fr: "Je voudrais ___ limonade.", options: ["une", "un"], answer: 0, en: "I'd like a lemonade.", de: "Ich hätte gern eine Limonade.", why: tx("**Limonade** is feminine: **une** limonade.", "**Limonade** ist weiblich: **une** limonade.") },
    { id: "u10.d3", lesson: 1, fr: "Je ne bois pas ___ café.", options: ["de", "du"], answer: 0, en: "I don't drink coffee.", de: "Ich trinke keinen Kaffee.", why: tx("After ne … pas, du and un become **de**: pas **de** café.", "Nach ne … pas werden du und un zu **de**: pas **de** café.") },
    { id: "u10.d4", lesson: 2, fr: "Une glace, s'il ___ plaît, papa !", options: ["te", "vous"], answer: 0, en: "An ice cream, please, Dad!", de: "Ein Eis, bitte, Papa!", why: tx("To family and friends (tu): s'il **te** plaît. To the waiter: s'il vous plaît.", "Zu Familie und Freunden (tu): s'il **te** plaît. Zum Kellner: s'il vous plaît.") },
    { id: "u10.d5", lesson: 2, fr: "Je voudrais une crêpe ___ chocolat.", options: ["au", "à la", "du"], answer: 0, en: "I'd like a chocolate crêpe.", de: "Ich hätte gern eine Crêpe mit Schokolade.", why: tx("Flavours take à, and à + le = **au**: une crêpe **au** chocolat. Just like au cinéma!", "Geschmack mit à, und à + le = **au**: une crêpe **au** chocolat. Genau wie au cinéma!") },
    { id: "u10.d6", lesson: 3, fr: "Bonjour, Monsieur, ___ avez des crêpes ?", options: ["vous", "tu"], answer: 0, en: "Hello, do you have crêpes?", de: "Guten Tag, haben Sie Crêpes?", why: tx("To the waiter, say **vous**: it's polite. Tu is for friends and family.", "Zum Kellner sagst du **vous**: Das ist höflich. Tu ist für Freunde und Familie.") },
    { id: "u10.d7", lesson: 3, fr: "Voilà ___ café, Monsieur.", options: ["votre", "ton", "vos"], answer: 0, en: "Here's your coffee, sir.", de: "Hier ist Ihr Kaffee.", why: tx("With vous, «your» is **votre**: votre café. For more than one thing: vos.", "Bei vous heißt „Ihr“ **votre**: votre café. Für mehrere Dinge: vos.") },
    { id: "u10.d8", lesson: 4, fr: "Ça fait douze ___.", options: ["euros", "euro"], answer: 0, en: "That's twelve euros.", de: "Das macht zwölf Euro.", why: tx("More than one: **euros**, with an s you don't hear. Only un euro has no s.", "Mehr als einer: **euros**, mit einem s, das man nicht hört. Nur un euro hat kein s.") },
    { id: "u10.d9", lesson: 4, fr: "— C'est ___, le gâteau ? — Trois euros.", options: ["combien", "comment", "où"], answer: 0, en: "— How much is the cake? — Three euros.", de: "— Was kostet der Kuchen? — Drei Euro.", why: tx("How much: **combien**. Comment means how, où means where.", "Wie viel: **combien**. Comment heißt wie, où heißt wo.") },
    { id: "u10.d10", lesson: 4, fr: "___addition, s'il vous plaît !", options: ["L'", "La"], answer: 0, en: "The bill, please!", de: "Die Rechnung, bitte!", why: tx("**Addition** starts with a vowel: **l'addition**.", "**Addition** beginnt mit einem Vokal: **l'addition**.") },
    { id: "u10.d11", lesson: 5, fr: "La limonade est ___.", options: ["froide", "froid"], answer: 0, en: "The lemonade is cold.", de: "Die Limonade ist kalt.", why: tx("**Limonade** is feminine: **froide**, with an e. Now you hear the d.", "**Limonade** ist weiblich: **froide**, mit e. Jetzt hört man das d.") },
    { id: "u10.d12", lesson: 5, fr: "Le thé est ___.", options: ["chaud", "chaude"], answer: 0, en: "The tea is hot.", de: "Der Tee ist heiß.", why: tx("**Thé** is masculine: **chaud**, no e.", "**Thé** ist männlich: **chaud**, ohne e.") },
  ],
  dialogue: {
    id: "u10.dialogue",
    lesson: 5,
    title: tx("Blob orders everything", "Blob bestellt alles"),
    lines: [
      { who: "serveur", fr: "Bonjour ! Vous désirez ?", en: "Hello! What would you like?", de: "Guten Tag! Was darf es sein?" },
      { who: "lea", fr: "Je voudrais un jus d'orange, s'il vous plaît.", en: "I'd like an orange juice, please.", de: "Ich hätte gern einen Orangensaft, bitte." },
      { who: "blob", fr: "Et pour moi, un chocolat chaud, une crêpe et une glace !", en: "And for me, a hot chocolate, a crêpe and an ice cream!", de: "Und für mich eine heiße Schokolade, eine Crêpe und ein Eis!" },
      { who: "serveur", fr: "Bien sûr. Et avec ça ?", en: "Of course. Anything else?", de: "Natürlich. Sonst noch etwas?" },
      { who: "blob", fr: "Euh… un gâteau au chocolat aussi !", en: "Er… a chocolate cake too!", de: "Äh … und auch einen Schokoladenkuchen!" },
      { who: "lea", fr: "Blob ! C'est beaucoup !", en: "Blob! That's a lot!", de: "Blob! Das ist viel!" },
      { who: "serveur", fr: "Voilà ! Et l'addition : vingt euros, s'il vous plaît.", en: "Here you are! And the bill: twenty euros, please.", de: "Bitte schön! Und die Rechnung: zwanzig Euro, bitte." },
      { who: "blob", fr: "Vingt euros ? Euh, Léa, tu as vingt euros, s'il te plaît ?", en: "Twenty euros? Er, Léa, do you have twenty euros, please?", de: "Zwanzig Euro? Äh, Léa, hast du bitte zwanzig Euro?" },
      { who: "lea", fr: "Bon, d'accord… mais la crêpe, c'est pour moi !", en: "Well, OK… but the crêpe is for me!", de: "Na gut … aber die Crêpe ist für mich!" },
    ],
    questions: [
      { q: tx("What does Léa order?", "Was bestellt Léa?"), options: [tx("An orange juice", "Einen Orangensaft"), tx("A hot chocolate", "Eine heiße Schokolade"), tx("A coffee", "Einen Kaffee")], answer: 0 },
      { q: tx("How much is the bill?", "Wie hoch ist die Rechnung?"), options: [tx("Twenty euros", "Zwanzig Euro"), tx("Twelve euros", "Zwölf Euro"), tx("Two euros", "Zwei Euro")], answer: 0 },
      { q: tx("Who pays?", "Wer bezahlt?"), options: ["Léa", "Blob", tx("The waiter", "Der Kellner")], answer: 0 },
    ],
  },
  tips: [
    {
      title: tx("Je voudrais: ordering politely", "Je voudrais: höflich bestellen"),
      body: tx(
        "**Je voudrais** means «I would like». It's the polite way to order: je voudrais un café. **Je veux** (I want) sounds a bit rude to a waiter.\n\nAdd **s'il vous plaît** and you're perfect: je voudrais une crêpe, s'il vous plaît.",
        "**Je voudrais** heißt „ich hätte gern“ oder „ich möchte“. So bestellt man höflich: je voudrais un café. **Je veux** (ich will) klingt für den Kellner etwas unhöflich.\n\nMit **s'il vous plaît** ist es perfekt: je voudrais une crêpe, s'il vous plaît.",
      ),
      examples: [
        { fr: "Je voudrais un café, s'il vous plaît.", en: "I'd like a coffee, please.", de: "Ich hätte gern einen Kaffee, bitte." },
        { fr: "Tu voudrais un jus d'orange ?", en: "Would you like an orange juice?", de: "Möchtest du einen Orangensaft?" },
      ],
      table: {
        head: [tx("person", "Person"), tx("would like", "möchte")],
        rows: [
          [tx("I", "ich"), "je voudrais"],
          [tx("you", "du"), "tu voudrais"],
          [tx("he / she", "er / sie"), "il / elle voudrait"],
          [tx("we", "wir"), "nous voudrions"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous voudriez"],
          [tx("they", "sie"), "ils / elles voudraient"],
        ],
      },
    },
    {
      title: tx("Tu or vous?", "Tu oder vous?"),
      body: tx(
        "**Vous** is for people you don't know, adults you call Monsieur or Madame, the waiter, and any group. **Tu** is for friends, family and children.\n\nSo it's s'il **vous** plaît to the waiter, but s'il **te** plaît to your friend. And «your»: **votre** café (vous), **ton** café (tu).",
        "**Vous** ist für Leute, die du nicht kennst, Erwachsene, die du siezt, den Kellner und jede Gruppe. **Tu** ist für Freunde, Familie und Kinder.\n\nAlso s'il **vous** plaît zum Kellner, aber s'il **te** plaît zu deinem Freund. Und „dein / Ihr“: **votre** café (vous), **ton** café (tu).",
      ),
      examples: [
        { fr: "L'addition, s'il vous plaît !", en: "The bill, please!", de: "Die Rechnung, bitte!" },
        { fr: "Une glace, s'il te plaît, papa !", en: "An ice cream, please, Dad!", de: "Ein Eis, bitte, Papa!" },
        { fr: "Voilà votre café, Monsieur.", en: "Here's your coffee, sir.", de: "Hier ist Ihr Kaffee." },
      ],
      table: {
        head: [tx("meaning", "Bedeutung"), "tu", "vous"],
        rows: [
          [tx("please", "bitte"), "s'il te plaît", "s'il vous plaît"],
          [tx("your", "dein / Ihr"), "ton, ta, tes", "votre, vos"],
          [tx("you are", "du bist / Sie sind"), "tu es", "vous êtes"],
        ],
      },
    },
    {
      title: tx("Prices", "Preise"),
      body: tx(
        "Ask **c'est combien ?** The answer: **c'est** or **ça fait** + number + **euros**. Cents come after: deux euros cinquante (2,50 €).\n\nThe s of euros is silent, but numbers link to it: deux‿euros and trois‿euros with a z sound, vingt‿euros with a t.",
        "Frag **c'est combien ?** Die Antwort: **c'est** oder **ça fait** + Zahl + **euros**. Die Cents kommen danach: deux euros cinquante (2,50 €).\n\nDas s von euros ist stumm, aber die Zahl wird verbunden: deux‿euros und trois‿euros mit weichem s, vingt‿euros mit t.",
      ),
      examples: [
        { fr: "C'est combien, le gâteau ?", en: "How much is the cake?", de: "Was kostet der Kuchen?" },
        { fr: "Ça fait douze euros.", en: "That's twelve euros.", de: "Das macht zwölf Euro." },
        { fr: "Le café, c'est deux euros cinquante.", en: "The coffee is two euros fifty.", de: "Der Kaffee kostet zwei Euro fünfzig." },
      ],
    },
  ],
};
