import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 11: reflexive verbs (je me lève) and telling the time. */
export const u11: Unit = {
  slug: "ma-journee",
  n: 11,
  cefr: "A2",
  title: tx("My day", "Mein Tag"),
  goal: tx("Talk about your day and tell the time", "Über deinen Tag sprechen und die Uhrzeit sagen"),
  emoji: "⏰",
  words: [
    { id: "je-me-reveille", fr: "je me réveille", en: "I wake up", de: "ich wache auf", alt: { en: ["I am waking up"] }, kind: "verb", emoji: "🥱", note: tx("Se réveiller: your eyes open. The little me means «myself»: I wake myself up.", "Se réveiller: Die Augen gehen auf. Das kleine me heißt „mich“: Ich wecke mich.") },
    { id: "je-me-leve", fr: "je me lève", en: "I get up", de: "ich stehe auf", alt: { en: ["I am getting up"] }, kind: "verb", note: tx("Literally «I lift myself». First you wake up (je me réveille), then you get out of bed (je me lève).", "Wörtlich „ich hebe mich“. Erst wachst du auf (je me réveille), dann stehst du auf (je me lève).") },
    { id: "matin", fr: "le matin", en: "the morning", de: "der Morgen", alt: { de: ["der Vormittag"] }, g: "m", kind: "noun", emoji: "🌅", note: tx("Le matin also means «in the morning»: le matin, je bois un café.", "Le matin heißt auch „morgens“: le matin, je bois un café.") },
    { id: "heure", fr: "l'heure", en: "the hour", de: "die Stunde", alt: { en: ["the time"], de: ["die Uhrzeit", "die Uhr"] }, g: "f", kind: "noun", emoji: "⌚", note: tx("With a number it's o'clock: huit heures. It's feminine: une heure.", "Mit einer Zahl heißt es Uhr: huit heures = acht Uhr. Es ist weiblich: une heure.") },
    { id: "tot", fr: "tôt", en: "early", de: "früh", kind: "adv", emoji: "🐓", note: tx("The rooster's word. The t at the end is silent.", "Das Wort des Hahns. Das t am Ende ist stumm.") },
    { id: "quelle-heure", fr: "quelle heure est-il ?", en: "what time is it?", de: "wie spät ist es?", alt: { fr: ["il est quelle heure ?"], en: ["what's the time?"], de: ["wie viel Uhr ist es?"] }, kind: "phrase", note: tx("The answer starts with il est: il est huit heures. Here il means «it».", "Die Antwort beginnt mit il est: il est huit heures. Hier heißt il „es“.") },
    { id: "et-demie", fr: "et demie", en: "half past", de: "halb", alt: { en: ["thirty"], de: ["dreißig"] }, kind: "phrase", note: tx("Huit heures et demie is 8:30: «eight hours and a half».", "Achtung: huit heures et demie ist halb neun (8:30)! Französisch zählt von der vollen Stunde weiter.") },
    { id: "et-quart", fr: "et quart", en: "quarter past", de: "Viertel nach", alt: { en: ["a quarter past"] }, kind: "phrase", note: tx("Huit heures et quart is 8:15.", "Huit heures et quart ist Viertel nach acht (8:15).") },
    { id: "midi", fr: "midi", en: "midday", de: "Mittag", alt: { en: ["noon"], de: ["zwölf Uhr mittags"] }, kind: "word", emoji: "🕛", note: tx("No article: il est midi, à midi. Le Midi is also the south of France!", "Ohne Artikel: il est midi, à midi. Le Midi ist auch der Süden Frankreichs!") },
    { id: "minuit", fr: "minuit", en: "midnight", de: "Mitternacht", kind: "word", emoji: "🌃", note: tx("Mi + nuit: the middle of the night.", "Mi + nuit: die Mitte der Nacht.") },
    { id: "tard", fr: "tard", en: "late", de: "spät", kind: "adv", emoji: "🦉", note: tx("The owl's word. The d is silent: «tar».", "Das Wort der Eule. Das d ist stumm: „tar“.") },
    { id: "tu-te-leves", fr: "tu te lèves", en: "you get up", de: "du stehst auf", kind: "verb", note: tx("With tu the little word is te: tu te lèves. The -es is silent.", "Mit tu heißt das kleine Wort te: tu te lèves. Das -es ist stumm.") },
    { id: "il-se-leve", fr: "il se lève", en: "he gets up", de: "er steht auf", kind: "verb", note: tx("Il, elle and on take se: elle se lève, on se lève.", "Il, elle und on nehmen se: elle se lève, on se lève.") },
    { id: "je-me-lave", fr: "je me lave", en: "I wash", de: "ich wasche mich", alt: { en: ["I wash myself", "I have a wash"] }, kind: "verb", emoji: "🧼", note: tx("Without me, you wash something else: je lave la voiture.", "Ohne me wäschst du etwas anderes: je lave la voiture (das Auto).") },
    { id: "je-m-habille", fr: "je m'habille", en: "I get dressed", de: "ich ziehe mich an", alt: { en: ["I dress"] }, kind: "verb", emoji: "👚", note: tx("Before a vowel or a silent h, me shrinks to m': je m'habille.", "Vor einem Vokal oder stummen h wird me zu m': je m'habille.") },
    { id: "douche", fr: "la douche", en: "the shower", de: "die Dusche", g: "f", kind: "noun", emoji: "🚿", note: tx("To have a shower: prendre une douche, just like je prends un café.", "Duschen: prendre une douche, genau wie je prends un café.") },
    { id: "petit-dejeuner", fr: "le petit-déjeuner", en: "breakfast", de: "das Frühstück", alt: { en: ["the breakfast"] }, g: "m", kind: "noun", emoji: "🥣", note: tx("Literally «little lunch». A French breakfast: bread, a croissant, a hot chocolate in a bowl.", "Wörtlich „kleines Mittagessen“. Ein französisches Frühstück: Brot, ein Croissant, heiße Schokolade in einer Schüssel.") },
    { id: "dejeuner", fr: "le déjeuner", en: "lunch", de: "das Mittagessen", alt: { en: ["the lunch"] }, g: "m", kind: "noun", note: tx("Lunch, often at midi. In Belgium and Switzerland, le déjeuner is breakfast!", "Das Mittagessen, oft um midi. In Belgien und der Schweiz ist le déjeuner das Frühstück!") },
    { id: "diner", fr: "le dîner", en: "dinner", de: "das Abendessen", alt: { en: ["the dinner", "supper"], de: ["das Abendbrot"] }, g: "m", kind: "noun", note: tx("The evening meal, in France often quite late: à huit heures du soir.", "Die Mahlzeit am Abend, in Frankreich oft recht spät: à huit heures du soir.") },
    { id: "soir", fr: "le soir", en: "the evening", de: "der Abend", g: "m", kind: "noun", emoji: "🌆", note: tx("Bon + soir = bonsoir! Le soir also means «in the evening».", "Bon + soir = bonsoir! Le soir heißt auch „abends“.") },
    { id: "je-me-couche", fr: "je me couche", en: "I go to bed", de: "ich gehe ins Bett", alt: { en: ["I lie down"], de: ["ich gehe schlafen", "ich lege mich hin"] }, kind: "verb", emoji: "🛌", note: tx("Literally «I lay myself down».", "Wörtlich „ich lege mich hin“.") },
    { id: "d-abord", fr: "d'abord", en: "first", de: "zuerst", alt: { en: ["first of all", "at first"], de: ["erst"] }, kind: "adv", note: tx("The first step. Then come ensuite and après.", "Der erste Schritt. Danach kommen ensuite und après.") },
    { id: "ensuite", fr: "ensuite", en: "then", de: "dann", alt: { en: ["next", "after that"], de: ["danach", "anschließend"] }, kind: "adv" },
    { id: "apres", fr: "après", en: "after / afterwards", de: "nach / danach", alt: { en: ["after", "afterwards"], de: ["nach", "danach", "nachher"] }, kind: "word", note: tx("Before a noun: après le dîner (after dinner). Alone: après (afterwards).", "Vor einem Nomen: après le dîner (nach dem Abendessen). Allein: après (danach).") },
    { id: "nous-nous-levons", fr: "nous nous levons", en: "we get up", de: "wir stehen auf", kind: "verb", note: tx("Nous twice: once «we», once «ourselves». In everyday French, people often say on se lève.", "Zweimal nous: einmal „wir“, einmal „uns“. Im Alltag sagt man oft on se lève.") },
    { id: "vous-vous-levez", fr: "vous vous levez", en: "you get up (plural / polite)", de: "ihr steht auf / Sie stehen auf", kind: "verb", note: tx("Vous twice, just like nous nous levons.", "Zweimal vous, genau wie nous nous levons.") },
    { id: "ils-se-levent", fr: "ils se lèvent", en: "they get up", de: "sie stehen auf", kind: "verb", note: tx("The -ent is silent: ils se lèvent sounds just like il se lève.", "Das -ent ist stumm: ils se lèvent klingt genau wie il se lève.") },
    { id: "apres-midi", fr: "l'après-midi", en: "the afternoon", de: "der Nachmittag", g: "m", kind: "noun", emoji: "🕒", note: tx("After midday: après + midi. L'après-midi also means «in the afternoon».", "Nach dem Mittag: après + midi. L'après-midi heißt auch „nachmittags“.") },
    { id: "moins-le-quart", fr: "moins le quart", en: "quarter to", de: "Viertel vor", alt: { en: ["a quarter to"] }, kind: "phrase", note: tx("Literally «minus the quarter»: neuf heures moins le quart is 8:45.", "Wörtlich „minus das Viertel“: neuf heures moins le quart ist Viertel vor neun.") },
    { id: "je-me-depeche", fr: "je me dépêche", en: "I hurry", de: "ich beeile mich", alt: { en: ["I hurry up", "I am hurrying"] }, kind: "verb", emoji: "🏃", note: tx("Dépêche-toi ! means «hurry up!». Blob hears it every morning.", "Dépêche-toi ! heißt „beeil dich!“. Das hört Blob jeden Morgen.") },
    { id: "en-retard", fr: "en retard", en: "late (not on time)", de: "zu spät", alt: { en: ["late"], de: ["verspätet", "spät dran"] }, kind: "phrase", emoji: "🐌", note: tx("Je suis en retard: I'm late for something. Tard is just late in the day: je me couche tard.", "Je suis en retard: Ich bin zu spät dran. Tard ist einfach spät am Tag: je me couche tard.") },
    { id: "tous-les-jours", fr: "tous les jours", en: "every day", de: "jeden Tag", alt: { de: ["täglich"] }, kind: "phrase", note: tx("Literally «all the days».", "Wörtlich „alle die Tage“.") },
  ],
  gloss: [
    { fr: "lève", en: "get up / gets up", de: "stehe auf / steht auf" },
    { fr: "lèves", en: "get up (you)", de: "stehst auf" },
    { fr: "levons", en: "get up (we)", de: "stehen auf (wir)" },
    { fr: "levez", en: "get up (you, plural / polite)", de: "steht auf / stehen (Sie) auf" },
    { fr: "lèvent", en: "get up (they)", de: "stehen auf (sie)" },
    { fr: "se lève", en: "gets up", de: "steht auf" },
    { fr: "se lèvent", en: "get up (they)", de: "stehen auf (sie)" },
    { fr: "me lève", en: "get up (I)", de: "stehe auf" },
    { fr: "te lèves", en: "get up (you)", de: "stehst auf" },
    { fr: "levez-vous", en: "get up! (plural / polite)", de: "steht auf! / stehen Sie auf!" },
    { fr: "lève-toi", en: "get up!", de: "steh auf!" },
    { fr: "réveille", en: "wake up / wakes up", de: "wache auf / wacht auf" },
    { fr: "se réveille", en: "wakes up", de: "wacht auf" },
    { fr: "lave", en: "wash / washes", de: "wasche / wäscht" },
    { fr: "se lave", en: "washes", de: "wäscht sich" },
    { fr: "habille", en: "dress / dresses", de: "ziehe an / zieht an" },
    { fr: "s'habille", en: "gets dressed", de: "zieht sich an" },
    { fr: "t'habilles", en: "get dressed (you)", de: "ziehst dich an" },
    { fr: "couche", en: "go to bed / goes to bed", de: "gehe ins Bett / geht ins Bett" },
    { fr: "me couche", en: "go to bed (I)", de: "gehe ins Bett" },
    { fr: "se couche", en: "goes to bed", de: "geht ins Bett" },
    { fr: "se couchent", en: "go to bed (they)", de: "gehen ins Bett (sie)" },
    { fr: "couches", en: "go to bed (you)", de: "gehst ins Bett" },
    { fr: "couchez", en: "go to bed (you, plural / polite)", de: "geht / gehen (Sie) ins Bett" },
    { fr: "dépêche", en: "hurry / hurries", de: "beeile / beeilt" },
    { fr: "se dépêche", en: "hurries", de: "beeilt sich" },
    { fr: "dépêche-toi", en: "hurry up!", de: "beeil dich!" },
    { fr: "heures", en: "hours / o'clock", de: "Stunden / Uhr" },
    { fr: "il est une heure", en: "it's one o'clock", de: "es ist ein Uhr" },
    { fr: "il est sept heures", en: "it's seven o'clock", de: "es ist sieben Uhr" },
    { fr: "il est huit heures", en: "it's eight o'clock", de: "es ist acht Uhr" },
    { fr: "il est neuf heures", en: "it's nine o'clock", de: "es ist neun Uhr" },
    { fr: "il est midi", en: "it's midday", de: "es ist Mittag" },
    { fr: "il est minuit", en: "it's midnight", de: "es ist Mitternacht" },
    { fr: "il est quelle heure", en: "what time is it?", de: "wie spät ist es?" },
    { fr: "quelle heure", en: "what time", de: "wie spät / wie viel Uhr" },
    { fr: "le samedi", en: "on Saturdays", de: "samstags" },
    { fr: "le dimanche", en: "on Sundays", de: "sonntags" },
    { fr: "te couches", en: "go to bed (you)", de: "gehst ins Bett" },
    { fr: "quelle", en: "what / which", de: "welche / wie viel" },
    { fr: "à quelle heure", en: "at what time", de: "um wie viel Uhr" },
    { fr: "du matin", en: "in the morning", de: "morgens" },
    { fr: "du soir", en: "in the evening", de: "abends" },
    { fr: "avant", en: "before", de: "vor" },
    { fr: "ici", en: "here", de: "hier" },
    { fr: "tout le monde", en: "everyone", de: "alle" },
    { fr: "bonne nuit", en: "good night", de: "gute Nacht" },
    { fr: "comme", en: "like / as", de: "wie" },
    { fr: "cours", en: "run (I / you)", de: "renne / rennst" },
    { fr: "problème", en: "problem", de: "Problem" },
    { fr: "dîne", en: "have dinner / has dinner", de: "esse / isst zu Abend" },
  ],
  lessons: [
    { title: tx("Rise and shine", "Aufstehen!"), words: ["je-me-reveille", "je-me-leve", "matin", "heure", "tot"] },
    { title: tx("What time is it?", "Wie spät ist es?"), words: ["quelle-heure", "et-demie", "et-quart", "midi", "minuit", "tard"] },
    { title: tx("Getting ready", "Fertig machen"), words: ["tu-te-leves", "il-se-leve", "je-me-lave", "je-m-habille", "douche"] },
    { title: tx("Breakfast, lunch, dinner", "Frühstück, Mittag, Abendessen"), words: ["petit-dejeuner", "dejeuner", "diner", "soir", "je-me-couche"] },
    { title: tx("First, then", "Zuerst, dann"), words: ["d-abord", "ensuite", "apres", "nous-nous-levons"] },
    { title: tx("Everybody up!", "Alle aufstehen!"), words: ["vous-vous-levez", "ils-se-levent", "apres-midi", "moins-le-quart"] },
    { title: tx("Hurry up, Blob!", "Beeil dich, Blob!"), words: ["je-me-depeche", "en-retard", "tous-les-jours"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u11.01", lesson: 1, fr: "Je me réveille à sept heures.", en: "I wake up at seven o'clock.", de: "Ich wache um sieben Uhr auf.", alt: { fr: ["À sept heures, je me réveille."], en: ["I wake up at seven.", "I wake up at 7 o'clock.", "I wake up at 7.", "I wake up at 7:00."], de: ["Ich wache um sieben auf.", "Ich wache um 7 Uhr auf.", "Ich wache um 7 auf.", "Um sieben Uhr wache ich auf.", "Um 7 Uhr wache ich auf."] } },
    { id: "u11.02", lesson: 1, fr: "Je me lève tôt.", en: "I get up early.", de: "Ich stehe früh auf.", alt: { en: ["I am getting up early."] } },
    { id: "u11.03", lesson: 1, fr: "Le matin, je me réveille tôt.", en: "In the morning, I wake up early.", de: "Morgens wache ich früh auf.", alt: { fr: ["Je me réveille tôt le matin."], en: ["I wake up early in the morning."], de: ["Am Morgen wache ich früh auf.", "Ich wache morgens früh auf.", "Ich wache am Morgen früh auf."] } },
    { id: "u11.04", lesson: 1, fr: "Je me lève à huit heures.", en: "I get up at eight o'clock.", de: "Ich stehe um acht Uhr auf.", alt: { fr: ["À huit heures, je me lève."], en: ["I get up at eight.", "I get up at 8 o'clock.", "I get up at 8.", "I get up at 8:00."], de: ["Ich stehe um acht auf.", "Ich stehe um 8 Uhr auf.", "Ich stehe um 8 auf.", "Um acht Uhr stehe ich auf.", "Um 8 Uhr stehe ich auf."] } },
    { id: "u11.05", lesson: 1, fr: "Le matin, je bois un café.", en: "In the morning, I drink a coffee.", de: "Morgens trinke ich einen Kaffee.", alt: { fr: ["Je bois un café le matin."], en: ["I drink a coffee in the morning.", "In the morning, I have a coffee.", "I have a coffee in the morning."], de: ["Am Morgen trinke ich einen Kaffee.", "Ich trinke morgens einen Kaffee.", "Ich trinke am Morgen einen Kaffee."] } },
    { id: "u11.06", lesson: 1, fr: "Je ne me lève pas tôt.", en: "I don't get up early.", de: "Ich stehe nicht früh auf.", alt: { en: ["I am not getting up early."] } },
    { id: "u11.07", lesson: 1, fr: "Il est huit heures, je me lève !", en: "It's eight o'clock, I'm getting up!", de: "Es ist acht Uhr, ich stehe auf!", alt: { en: ["It's eight o'clock, I get up!", "It's eight, I'm getting up!", "It's 8 o'clock, I'm getting up!", "It's 8, I'm getting up!", "It's 8:00, I'm getting up!"], de: ["Es ist acht, ich stehe auf!", "Es ist 8 Uhr, ich stehe auf!"] } },
    // Lesson 2
    { id: "u11.08", lesson: 2, fr: "Quelle heure est-il ?", en: "What time is it?", de: "Wie spät ist es?", alt: { fr: ["Il est quelle heure ?", "Quelle heure il est ?"], en: ["What's the time?"], de: ["Wie viel Uhr ist es?", "Wieviel Uhr ist es?"] } },
    { id: "u11.09", lesson: 2, fr: "Il est sept heures et demie.", en: "It's half past seven.", de: "Es ist halb acht.", alt: { en: ["It's seven thirty.", "It's half seven.", "It's 7:30."], de: ["Es ist sieben Uhr dreißig.", "Es ist 7:30 Uhr.", "Es ist 7:30."] } },
    { id: "u11.10", lesson: 2, fr: "Il est midi !", en: "It's midday!", de: "Es ist Mittag!", alt: { en: ["It's noon!", "It's twelve o'clock!", "It's 12 o'clock!", "It's twelve!", "It's 12!"], de: ["Es ist zwölf Uhr!", "Es ist 12 Uhr!", "Es ist zwölf!"] } },
    { id: "u11.11", lesson: 2, fr: "Il est minuit, c'est tard !", en: "It's midnight, it's late!", de: "Es ist Mitternacht, es ist spät!", alt: { en: ["It's midnight, that's late!"], de: ["Es ist Mitternacht, das ist spät!"] } },
    { id: "u11.12", lesson: 2, fr: "Je me lève à six heures et quart.", en: "I get up at quarter past six.", de: "Ich stehe um Viertel nach sechs auf.", alt: { fr: ["À six heures et quart, je me lève."], en: ["I get up at a quarter past six.", "I get up at six fifteen.", "I get up at 6:15."], de: ["Ich stehe um sechs Uhr fünfzehn auf.", "Ich stehe um 6:15 Uhr auf.", "Ich stehe um 6:15 auf.", "Um Viertel nach sechs stehe ich auf."] } },
    { id: "u11.13", lesson: 2, fr: "Le samedi, je me réveille à midi.", en: "On Saturdays, I wake up at midday.", de: "Samstags wache ich um zwölf Uhr auf.", alt: { fr: ["Je me réveille à midi le samedi."], en: ["On Saturdays, I wake up at noon.", "On Saturday, I wake up at midday.", "On Saturday, I wake up at noon.", "I wake up at midday on Saturdays.", "I wake up at noon on Saturdays.", "On Saturdays, I wake up at twelve.", "On Saturdays, I wake up at 12."], de: ["Samstags wache ich um zwölf auf.", "Samstags wache ich um 12 Uhr auf.", "Samstags wache ich mittags auf.", "Am Samstag wache ich um zwölf Uhr auf.", "Am Samstag wache ich mittags auf.", "Ich wache samstags um zwölf Uhr auf.", "Ich wache samstags mittags auf."] } },
    { id: "u11.14", lesson: 2, fr: "Je me lève tard le dimanche.", en: "I get up late on Sundays.", de: "Sonntags stehe ich spät auf.", alt: { fr: ["Le dimanche, je me lève tard."], en: ["On Sundays, I get up late.", "I get up late on Sunday.", "On Sunday, I get up late."], de: ["Am Sonntag stehe ich spät auf.", "Ich stehe sonntags spät auf.", "Ich stehe am Sonntag spät auf."] } },
    // Lesson 3
    { id: "u11.15", lesson: 3, fr: "Tu te lèves à quelle heure ?", en: "What time do you get up?", de: "Um wie viel Uhr stehst du auf?", alt: { fr: ["À quelle heure tu te lèves ?", "À quelle heure est-ce que tu te lèves ?", "À quelle heure te lèves-tu ?", "Vous vous levez à quelle heure ?", "À quelle heure vous vous levez ?", "À quelle heure est-ce que vous vous levez ?", "À quelle heure vous levez-vous ?"], en: ["At what time do you get up?", "When do you get up?"], de: ["Wann stehst du auf?", "Um wieviel Uhr stehst du auf?"] } },
    { id: "u11.16", lesson: 3, fr: "Il se lève à sept heures et demie.", en: "He gets up at half past seven.", de: "Er steht um halb acht auf.", alt: { fr: ["À sept heures et demie, il se lève."], en: ["He gets up at seven thirty.", "He gets up at half seven.", "He gets up at 7:30."], de: ["Er steht um sieben Uhr dreißig auf.", "Er steht um 7:30 Uhr auf.", "Er steht um 7:30 auf.", "Um halb acht steht er auf."] } },
    { id: "u11.17", lesson: 3, fr: "Elle se lève tôt.", en: "She gets up early.", de: "Sie steht früh auf.", alt: { en: ["She is getting up early."] } },
    { id: "u11.18", lesson: 3, fr: "Je me lave et je m'habille.", en: "I wash and I get dressed.", de: "Ich wasche mich und ich ziehe mich an.", alt: { fr: ["Je me lave et m'habille."], en: ["I wash and get dressed.", "I have a wash and I get dressed.", "I have a wash and get dressed.", "I wash myself and I get dressed.", "I wash myself and get dressed."], de: ["Ich wasche mich und ziehe mich an."] } },
    { id: "u11.19", lesson: 3, fr: "Je prends une douche le matin.", en: "I have a shower in the morning.", de: "Ich dusche morgens.", alt: { fr: ["Le matin, je prends une douche."], en: ["I take a shower in the morning.", "In the morning, I have a shower.", "In the morning, I take a shower.", "I shower in the morning.", "In the morning, I shower."], de: ["Morgens dusche ich.", "Ich dusche am Morgen.", "Am Morgen dusche ich.", "Ich nehme morgens eine Dusche.", "Morgens nehme ich eine Dusche."] } },
    { id: "u11.20", lesson: 3, fr: "Tu te lèves tôt, Hugo !", en: "You get up early, Hugo!", de: "Du stehst früh auf, Hugo!", alt: { fr: ["Hugo, tu te lèves tôt !", "Vous vous levez tôt, Hugo !"], en: ["You're getting up early, Hugo!", "Hugo, you get up early!"], de: ["Hugo, du stehst früh auf!"] } },
    { id: "u11.21", lesson: 3, fr: "Elle s'habille pour l'école.", en: "She gets dressed for school.", de: "Sie zieht sich für die Schule an.", alt: { en: ["She is getting dressed for school."] } },
    // Lesson 4
    { id: "u11.22", lesson: 4, fr: "Je prends le petit-déjeuner à sept heures.", en: "I have breakfast at seven o'clock.", de: "Ich frühstücke um sieben Uhr.", alt: { fr: ["À sept heures, je prends le petit-déjeuner.", "Je prends mon petit-déjeuner à sept heures."], en: ["I have breakfast at seven.", "I have breakfast at 7 o'clock.", "I have breakfast at 7.", "I eat breakfast at seven o'clock.", "I eat breakfast at seven.", "I eat breakfast at 7."], de: ["Ich frühstücke um sieben.", "Ich frühstücke um 7 Uhr.", "Ich frühstücke um 7.", "Um sieben Uhr frühstücke ich.", "Um 7 Uhr frühstücke ich."] } },
    { id: "u11.23", lesson: 4, fr: "Le déjeuner est à midi.", en: "Lunch is at midday.", de: "Das Mittagessen ist um zwölf Uhr.", alt: { en: ["Lunch is at noon.", "Lunch is at twelve.", "Lunch is at twelve o'clock.", "Lunch is at 12.", "Lunch is at 12 o'clock."], de: ["Das Mittagessen ist um zwölf.", "Das Mittagessen ist um 12 Uhr.", "Mittagessen ist um zwölf Uhr.", "Mittagessen gibt es um zwölf Uhr.", "Das Mittagessen gibt es um zwölf Uhr."] } },
    { id: "u11.24", lesson: 4, fr: "Le soir, je me couche à dix heures.", en: "In the evening, I go to bed at ten o'clock.", de: "Abends gehe ich um zehn Uhr ins Bett.", alt: { fr: ["Je me couche à dix heures le soir.", "Je me couche à dix heures du soir."], en: ["In the evening, I go to bed at ten.", "In the evening, I go to bed at 10 o'clock.", "In the evening, I go to bed at 10.", "I go to bed at ten o'clock in the evening.", "I go to bed at ten in the evening.", "I go to bed at 10 in the evening.", "I go to bed at ten pm.", "I go to bed at 10 pm."], de: ["Abends gehe ich um zehn ins Bett.", "Abends gehe ich um 10 Uhr ins Bett.", "Am Abend gehe ich um zehn Uhr ins Bett.", "Ich gehe abends um zehn Uhr ins Bett.", "Ich gehe abends um 10 Uhr ins Bett.", "Ich gehe um zehn Uhr abends ins Bett.", "Ich gehe um 22 Uhr ins Bett.", "Ich gehe um zweiundzwanzig Uhr ins Bett."] } },
    { id: "u11.25", lesson: 4, fr: "Le dîner est délicieux !", en: "Dinner is delicious!", de: "Das Abendessen ist köstlich!", alt: { en: ["The dinner is delicious!"], de: ["Das Abendessen ist lecker!"] } },
    { id: "u11.26", lesson: 4, fr: "Je ne me couche pas tard.", en: "I don't go to bed late.", de: "Ich gehe nicht spät ins Bett.", alt: { de: ["Ich gehe nicht spät schlafen."] } },
    { id: "u11.27", lesson: 4, fr: "Au petit-déjeuner, je mange un croissant.", en: "For breakfast, I eat a croissant.", de: "Zum Frühstück esse ich ein Croissant.", alt: { fr: ["Je mange un croissant au petit-déjeuner."], en: ["For breakfast, I have a croissant.", "At breakfast, I eat a croissant.", "At breakfast, I have a croissant.", "I eat a croissant for breakfast.", "I have a croissant for breakfast."], de: ["Ich esse zum Frühstück ein Croissant.", "Zum Frühstück esse ich einen Croissant."] } },
    { id: "u11.28", lesson: 4, fr: "Le dîner est à huit heures du soir.", en: "Dinner is at eight in the evening.", de: "Das Abendessen ist um acht Uhr abends.", alt: { en: ["Dinner is at eight o'clock in the evening.", "Dinner is at 8 in the evening.", "Dinner is at 8 o'clock in the evening.", "Dinner is at eight pm.", "Dinner is at 8 pm."], de: ["Das Abendessen ist um 20 Uhr.", "Das Abendessen ist um zwanzig Uhr.", "Das Abendessen ist um 8 Uhr abends.", "Das Abendessen ist abends um acht Uhr.", "Das Abendessen ist abends um acht."] } },
    // Lesson 5
    { id: "u11.29", lesson: 5, fr: "D'abord je me lave, ensuite je m'habille.", en: "First I wash, then I get dressed.", de: "Zuerst wasche ich mich, dann ziehe ich mich an.", alt: { fr: ["D'abord je me lave, puis je m'habille.", "D'abord je me lave, après je m'habille."], en: ["First I have a wash, then I get dressed.", "First I wash myself, then I get dressed.", "First I wash, and then I get dressed."], de: ["Erst wasche ich mich, dann ziehe ich mich an.", "Zuerst wasche ich mich, danach ziehe ich mich an.", "Erst wasche ich mich, danach ziehe ich mich an."] } },
    { id: "u11.30", lesson: 5, fr: "Nous nous levons à sept heures.", en: "We get up at seven o'clock.", de: "Wir stehen um sieben Uhr auf.", alt: { fr: ["On se lève à sept heures.", "À sept heures, nous nous levons."], en: ["We get up at seven.", "We get up at 7 o'clock.", "We get up at 7.", "We get up at 7:00."], de: ["Wir stehen um sieben auf.", "Wir stehen um 7 Uhr auf.", "Wir stehen um 7 auf.", "Um sieben Uhr stehen wir auf.", "Um 7 Uhr stehen wir auf."] } },
    { id: "u11.31", lesson: 5, fr: "Après le petit-déjeuner, je vais à l'école.", en: "After breakfast, I go to school.", de: "Nach dem Frühstück gehe ich in die Schule.", alt: { fr: ["Je vais à l'école après le petit-déjeuner."], en: ["I go to school after breakfast."], de: ["Nach dem Frühstück gehe ich zur Schule.", "Ich gehe nach dem Frühstück in die Schule.", "Ich gehe nach dem Frühstück zur Schule."] } },
    { id: "u11.32", lesson: 5, fr: "Ensuite, je prends le bus.", en: "Then I take the bus.", de: "Dann nehme ich den Bus.", alt: { fr: ["Puis je prends le bus.", "Après, je prends le bus."], en: ["Then I get the bus.", "Next, I take the bus.", "After that, I take the bus.", "Then I catch the bus."], de: ["Danach nehme ich den Bus.", "Dann fahre ich mit dem Bus.", "Anschließend nehme ich den Bus."] } },
    { id: "u11.33", lesson: 5, fr: "Nous ne nous levons pas tard.", en: "We don't get up late.", de: "Wir stehen nicht spät auf.", alt: { fr: ["On ne se lève pas tard."] } },
    { id: "u11.34", lesson: 5, fr: "D'abord, le petit-déjeuner !", en: "Breakfast first!", de: "Zuerst das Frühstück!", alt: { fr: ["Le petit-déjeuner d'abord !"], en: ["First, breakfast!", "First breakfast!"], de: ["Erst das Frühstück!", "Zuerst Frühstück!", "Erst mal Frühstück!"] } },
    { id: "u11.35", lesson: 5, fr: "Après, nous jouons au foot.", en: "Afterwards, we play football.", de: "Danach spielen wir Fußball.", alt: { fr: ["Ensuite, nous jouons au foot.", "Après, on joue au foot.", "Ensuite, on joue au foot."], en: ["After that, we play football.", "Then we play football.", "Afterwards, we play soccer."], de: ["Nachher spielen wir Fußball.", "Dann spielen wir Fußball."] } },
    // Lesson 6
    { id: "u11.36", lesson: 6, fr: "Madame Martin, vous vous levez à quelle heure ?", en: "Mrs Martin, what time do you get up?", de: "Frau Martin, um wie viel Uhr stehen Sie auf?", alt: { fr: ["Madame Martin, à quelle heure vous levez-vous ?", "Madame Martin, à quelle heure est-ce que vous vous levez ?", "Madame Martin, à quelle heure vous vous levez ?", "Vous vous levez à quelle heure, Madame Martin ?"], en: ["What time do you get up, Mrs Martin?", "Mrs Martin, when do you get up?", "Mrs Martin, at what time do you get up?"], de: ["Frau Martin, wann stehen Sie auf?", "Um wie viel Uhr stehen Sie auf, Frau Martin?", "Frau Martin, um wieviel Uhr stehen Sie auf?"] } },
    { id: "u11.37", lesson: 6, fr: "Ils se lèvent à six heures moins le quart.", en: "They get up at quarter to six.", de: "Sie stehen um Viertel vor sechs auf.", alt: { fr: ["Elles se lèvent à six heures moins le quart."], en: ["They get up at a quarter to six.", "They get up at five forty-five.", "They get up at 5:45."], de: ["Sie stehen um fünf Uhr fünfundvierzig auf.", "Sie stehen um 5:45 Uhr auf.", "Sie stehen um 5:45 auf."] } },
    { id: "u11.38", lesson: 6, fr: "L'après-midi, je fais du sport.", en: "In the afternoon, I do sport.", de: "Nachmittags mache ich Sport.", alt: { fr: ["Je fais du sport l'après-midi."], en: ["I do sport in the afternoon.", "In the afternoon, I do sports.", "I do sports in the afternoon."], de: ["Am Nachmittag mache ich Sport.", "Ich mache nachmittags Sport.", "Ich mache am Nachmittag Sport."] } },
    { id: "u11.39", lesson: 6, fr: "Vous vous couchez tard !", en: "You go to bed late!", de: "Ihr geht spät ins Bett!", alt: { fr: ["Tu te couches tard !"], de: ["Sie gehen spät ins Bett!"] } },
    { id: "u11.40", lesson: 6, fr: "Il est neuf heures moins le quart.", en: "It's quarter to nine.", de: "Es ist Viertel vor neun.", alt: { en: ["It's a quarter to nine.", "It's eight forty-five.", "It's 8:45."], de: ["Es ist acht Uhr fünfundvierzig.", "Es ist 8:45 Uhr.", "Es ist 8:45.", "Es ist drei viertel neun."] } },
    { id: "u11.41", lesson: 6, fr: "Les enfants se lèvent tôt.", en: "The children get up early.", de: "Die Kinder stehen früh auf.", alt: { en: ["The kids get up early."] } },
    { id: "u11.42", lesson: 6, fr: "Est-ce que vous vous levez tôt le samedi ?", en: "Do you get up early on Saturdays?", de: "Steht ihr samstags früh auf?", alt: { fr: ["Vous vous levez tôt le samedi ?", "Vous levez-vous tôt le samedi ?", "Le samedi, vous vous levez tôt ?", "Est-ce que tu te lèves tôt le samedi ?", "Tu te lèves tôt le samedi ?", "Te lèves-tu tôt le samedi ?", "Le samedi, tu te lèves tôt ?"], en: ["Do you get up early on Saturday?"], de: ["Steht ihr am Samstag früh auf?", "Stehen Sie samstags früh auf?", "Stehen Sie am Samstag früh auf?"] } },
    { id: "u11.43", lesson: 6, fr: "Ils ne se couchent pas avant minuit.", en: "They don't go to bed before midnight.", de: "Sie gehen nicht vor Mitternacht ins Bett.", alt: { fr: ["Elles ne se couchent pas avant minuit."] } },
    // Lesson 7
    { id: "u11.44", lesson: 7, fr: "Je me dépêche, je suis en retard !", en: "I'm hurrying, I'm late!", de: "Ich beeile mich, ich bin zu spät!", alt: { en: ["I hurry, I'm late!", "I'm hurrying up, I'm late!"], de: ["Ich beeile mich, ich bin spät dran!", "Ich beeile mich, ich komme zu spät!"] } },
    { id: "u11.45", lesson: 7, fr: "Dépêche-toi, Blob !", en: "Hurry up, Blob!", de: "Beeil dich, Blob!", alt: { fr: ["Dépêchez-vous, Blob !"], en: ["Hurry, Blob!"], de: ["Beeile dich, Blob!"] } },
    { id: "u11.46", lesson: 7, fr: "Tu es en retard tous les jours !", en: "You're late every day!", de: "Du kommst jeden Tag zu spät!", alt: { fr: ["Tous les jours, tu es en retard !", "Vous êtes en retard tous les jours !"], de: ["Du bist jeden Tag zu spät!", "Du bist jeden Tag spät dran!"] } },
    { id: "u11.47", lesson: 7, fr: "Tous les jours, je me lève à sept heures.", en: "Every day, I get up at seven o'clock.", de: "Jeden Tag stehe ich um sieben Uhr auf.", alt: { fr: ["Je me lève à sept heures tous les jours."], en: ["Every day, I get up at seven.", "Every day, I get up at 7 o'clock.", "Every day, I get up at 7.", "I get up at seven o'clock every day.", "I get up at seven every day.", "I get up at 7 o'clock every day.", "I get up at 7 every day."], de: ["Jeden Tag stehe ich um sieben auf.", "Jeden Tag stehe ich um 7 Uhr auf.", "Ich stehe jeden Tag um sieben Uhr auf.", "Ich stehe jeden Tag um sieben auf.", "Ich stehe jeden Tag um 7 Uhr auf."] } },
    { id: "u11.48", lesson: 7, fr: "Elle ne se dépêche pas.", en: "She doesn't hurry.", de: "Sie beeilt sich nicht.", alt: { en: ["She isn't hurrying.", "She's not hurrying."] } },
    { id: "u11.49", lesson: 7, fr: "Pardon, Monsieur Martin, je suis en retard !", en: "Sorry, Mr Martin, I'm late!", de: "Entschuldigung, Herr Martin, ich bin zu spät!", alt: { en: ["Excuse me, Mr Martin, I'm late!", "I'm sorry, Mr Martin, I'm late!"], de: ["Entschuldigung, Herr Martin, ich komme zu spät!", "Verzeihung, Herr Martin, ich bin zu spät!", "Entschuldigen Sie, Herr Martin, ich bin zu spät!", "Entschuldigung, Herr Martin, ich bin spät dran!"] } },
    { id: "u11.50", lesson: 7, fr: "Le bus est en retard.", en: "The bus is late.", de: "Der Bus hat Verspätung.", alt: { de: ["Der Bus ist zu spät.", "Der Bus ist verspätet.", "Der Bus kommt zu spät."] } },
    { id: "u11.51", lesson: 7, fr: "Hugo se dépêche, il est huit heures !", en: "Hugo is hurrying, it's eight o'clock!", de: "Hugo beeilt sich, es ist acht Uhr!", alt: { en: ["Hugo hurries, it's eight o'clock!", "Hugo is hurrying, it's eight!", "Hugo is hurrying, it's 8 o'clock!", "Hugo is hurrying, it's 8!"], de: ["Hugo beeilt sich, es ist acht!", "Hugo beeilt sich, es ist 8 Uhr!"] } },
  ],
  drills: [
    { id: "u11.d1", lesson: 1, fr: "Je ___ lève tôt.", options: ["me", "se", "moi"], answer: 0, en: "I get up early.", de: "Ich stehe früh auf.", why: tx("Se lever needs a little pronoun that matches the person: je **me** lève. Se is for il and elle.", "Se lever braucht ein kleines Pronomen, das zur Person passt: je **me** lève. Se ist für il und elle.") },
    { id: "u11.d2", lesson: 1, fr: "Je ___ me lève pas tôt.", options: ["ne", "pas", "non"], answer: 0, en: "I don't get up early.", de: "Ich stehe nicht früh auf.", why: tx("**Ne** goes before the little pronoun, **pas** after the verb: je **ne** me lève **pas**.", "**Ne** steht vor dem kleinen Pronomen, **pas** nach dem Verb: je **ne** me lève **pas**.") },
    { id: "u11.d3", lesson: 1, fr: "Je me réveille ___ sept heures.", options: ["à", "au", "à la"], answer: 0, en: "I wake up at seven o'clock.", de: "Ich wache um sieben Uhr auf.", why: tx("A time takes **à**, with no article: **à** sept heures, **à** midi.", "Eine Uhrzeit bekommt **à**, ohne Artikel: **à** sept heures, **à** midi.") },
    { id: "u11.d4", lesson: 2, fr: "Il est sept heures et ___.", options: ["demie", "demi", "moitié"], answer: 0, en: "It's half past seven.", de: "Es ist halb acht.", why: tx("Heure is feminine, so half past is **et demie**, with an e.", "Heure ist weiblich, darum heißt es **et demie**, mit e.") },
    { id: "u11.d5", lesson: 2, fr: "Il est une ___.", options: ["heure", "heures"], answer: 0, en: "It's one o'clock.", de: "Es ist ein Uhr.", why: tx("One hour: une **heure**, no s. From two on: deux heure**s**.", "Eine Stunde: une **heure**, ohne s. Ab zwei: deux heure**s**.") },
    { id: "u11.d6", lesson: 2, fr: "___ heure est-il ?", options: ["Quelle", "Quel", "Qui"], answer: 0, en: "What time is it?", de: "Wie spät ist es?", why: tx("**Heure** is feminine: **quelle** heure ? (But quel âge: âge is masculine.)", "**Heure** ist weiblich: **quelle** heure ? (Aber quel âge: âge ist männlich.)") },
    { id: "u11.d7", lesson: 3, fr: "Tu ___ lèves à quelle heure ?", options: ["te", "se", "toi"], answer: 0, en: "What time do you get up?", de: "Um wie viel Uhr stehst du auf?", why: tx("With **tu**, the pronoun is **te**: tu **te** lèves.", "Mit **tu** heißt das Pronomen **te**: tu **te** lèves.") },
    { id: "u11.d8", lesson: 3, fr: "Il se ___ à sept heures et demie.", options: ["lève", "lèves", "lever"], answer: 0, en: "He gets up at half past seven.", de: "Er steht um halb acht auf.", why: tx("With il and elle the ending is **-e**, like with je: il se lèv**e**.", "Mit il und elle endet es auf **-e**, wie bei je: il se lèv**e**.") },
    { id: "u11.d9", lesson: 3, fr: "Je ___ pour l'école.", options: ["m'habille", "me habille", "habille"], answer: 0, en: "I get dressed for school.", de: "Ich ziehe mich für die Schule an.", why: tx("Before a vowel or a silent h, **me** becomes **m'**: je **m'habille**. And never without it!", "Vor einem Vokal oder stummen h wird **me** zu **m'**: je **m'habille**. Und nie ohne!") },
    { id: "u11.d10", lesson: 4, fr: "Je prends ___ petit-déjeuner à sept heures.", options: ["le", "la"], answer: 0, en: "I have breakfast at seven o'clock.", de: "Ich frühstücke um sieben Uhr.", why: tx("**Petit-déjeuner** is masculine: **le** petit-déjeuner, like le déjeuner and le dîner.", "**Petit-déjeuner** ist männlich: **le** petit-déjeuner, wie le déjeuner und le dîner.") },
    { id: "u11.d11", lesson: 4, fr: "Le dîner est à huit heures ___ soir.", options: ["du", "de la", "des"], answer: 0, en: "Dinner is at eight in the evening.", de: "Das Abendessen ist um acht Uhr abends.", why: tx("In the evening: **du soir** (soir is masculine). In the morning: du matin.", "Abends: **du soir** (soir ist männlich). Morgens: du matin.") },
    { id: "u11.d12", lesson: 4, fr: "Elle ne ___ couche pas tard.", options: ["se", "elle", "s'"], answer: 0, en: "She doesn't go to bed late.", de: "Sie geht nicht spät ins Bett.", why: tx("With elle the pronoun is **se**, and it stays between ne and the verb: elle ne **se** couche pas.", "Mit elle heißt das Pronomen **se**, und es bleibt zwischen ne und dem Verb: elle ne **se** couche pas.") },
    { id: "u11.d13", lesson: 5, fr: "Nous ___ levons à sept heures.", options: ["nous", "se", "nos"], answer: 0, en: "We get up at seven o'clock.", de: "Wir stehen um sieben Uhr auf.", why: tx("With **nous**, nous comes twice: nous **nous** levons. Se is only for il, elle, ils and elles.", "Mit **nous** steht nous zweimal: nous **nous** levons. Se ist nur für il, elle, ils und elles.") },
    { id: "u11.d14", lesson: 5, fr: "Nous nous ___ tard le dimanche.", options: ["levons", "lève", "levez"], answer: 0, en: "We get up late on Sundays.", de: "Sonntags stehen wir spät auf.", why: tx("With nous the ending is **-ons**: nous nous lev**ons**, and no accent on the e.", "Mit nous endet es auf **-ons**: nous nous lev**ons**, und ohne Akzent auf dem e.") },
    { id: "u11.d15", lesson: 5, fr: "Je vais à l'école ___ le petit-déjeuner.", options: ["après", "ensuite"], answer: 0, en: "I go to school after breakfast.", de: "Ich gehe nach dem Frühstück in die Schule.", why: tx("Before a noun, it's **après**: après le petit-déjeuner. Ensuite stands alone: ensuite, je vais à l'école.", "Vor einem Nomen steht **après**: après le petit-déjeuner. Ensuite steht allein: ensuite, je vais à l'école.") },
    { id: "u11.d16", lesson: 6, fr: "Vous ___ levez à quelle heure, Madame Martin ?", options: ["vous", "se", "te"], answer: 0, en: "What time do you get up, Mrs Martin?", de: "Um wie viel Uhr stehen Sie auf, Frau Martin?", why: tx("With **vous**, vous comes twice: vous **vous** levez.", "Mit **vous** steht vous zweimal: vous **vous** levez.") },
    { id: "u11.d17", lesson: 6, fr: "Ils se ___ à six heures.", options: ["lèvent", "lève", "levons"], answer: 0, en: "They get up at six o'clock.", de: "Sie stehen um sechs Uhr auf.", why: tx("With **ils** the ending is **-ent**, and you don't hear it: ils se lèv**ent**.", "Mit **ils** endet es auf **-ent**, und man hört es nicht: ils se lèv**ent**.") },
    { id: "u11.d18", lesson: 6, fr: "Il est neuf heures ___ le quart.", options: ["moins", "et", "plus"], answer: 0, en: "It's quarter to nine.", de: "Es ist Viertel vor neun.", why: tx("Quarter to is **moins le quart**: neuf heures **moins** le quart is 8:45. Quarter past is et quart, without le.", "Viertel vor heißt **moins le quart**: neuf heures **moins** le quart ist 8:45. Viertel nach ist et quart, ohne le.") },
    { id: "u11.d19", lesson: 7, fr: "Dépêche-___, Blob !", options: ["toi", "te", "tu"], answer: 0, en: "Hurry up, Blob!", de: "Beeil dich, Blob!", why: tx("When you tell someone to do it, the pronoun comes after, as **toi**: dépêche-**toi** !", "Wenn du jemanden aufforderst, kommt das Pronomen danach, als **toi**: dépêche-**toi** !") },
    { id: "u11.d20", lesson: 7, fr: "Tu es en retard ___ les jours !", options: ["tous", "tout", "toutes"], answer: 0, en: "You're late every day!", de: "Du kommst jeden Tag zu spät!", why: tx("**Jours** is masculine plural: **tous** les jours.", "**Jours** ist männlich und Plural: **tous** les jours.") },
    { id: "u11.d21", lesson: 7, fr: "Le bus est ___ retard.", options: ["en", "à", "au"], answer: 0, en: "The bus is late.", de: "Der Bus hat Verspätung.", why: tx("Late, not on time: **en retard**. Late in the day is just tard.", "Zu spät, nicht pünktlich: **en retard**. Spät am Tag ist einfach tard.") },
  ],
  dialogues: [
    {
      id: "u11.dialogue",
      lesson: 5,
      title: tx("Cousin Chloé's first morning", "Der erste Morgen von Cousine Chloé"),
      lines: [
        { who: "maman", fr: "Léa, Chloé, il est sept heures ! Levez-vous !", en: "Léa, Chloé, it's seven o'clock! Get up!", de: "Léa, Chloé, es ist sieben Uhr! Steht auf!" },
        { who: "chloe", fr: "Sept heures ? À Lyon, je me lève à huit heures !", en: "Seven o'clock? In Lyon I get up at eight!", de: "Sieben Uhr? In Lyon stehe ich um acht auf!" },
        { who: "lea", fr: "Ici, nous nous levons tôt. D'abord, la douche !", en: "Here we get up early. First, the shower!", de: "Hier stehen wir früh auf. Zuerst die Dusche!" },
        { who: "chloe", fr: "D'accord. Et ensuite ?", en: "OK. And then?", de: "Okay. Und dann?" },
        { who: "lea", fr: "Ensuite, on s'habille et on prend le petit-déjeuner.", en: "Then we get dressed and have breakfast.", de: "Dann ziehen wir uns an und frühstücken." },
        { who: "chloe", fr: "Et Blob ? Il se lève à quelle heure ?", en: "And Blob? What time does he get up?", de: "Und Blob? Wann steht er auf?" },
        { who: "maman", fr: "Blob ? Le samedi, il se lève à midi, comme le chat !", en: "Blob? On Saturdays he gets up at midday, like the cat!", de: "Blob? Samstags steht er um zwölf auf, wie die Katze!" },
        { who: "blob", fr: "Bonjour, tout le monde ! Il y a des croissants ?", en: "Good morning, everyone! Are there any croissants?", de: "Guten Morgen, alle zusammen! Gibt es Croissants?" },
        { who: "lea", fr: "Oui, deux croissants ! Mais il est sept heures et demie… tu te lèves tôt, Blob !", en: "Yes, two croissants! But it's half past seven… you're up early, Blob!", de: "Ja, zwei Croissants! Aber es ist halb acht … du bist früh auf, Blob!" },
        { who: "blob", fr: "Non, non. Je me couche maintenant. Bonne nuit !", en: "No, no. I'm going to bed now. Good night!", de: "Nein, nein. Ich gehe jetzt ins Bett. Gute Nacht!" },
      ],
      questions: [
        { q: tx("What time does Chloé get up in Lyon?", "Um wie viel Uhr steht Chloé in Lyon auf?"), options: [tx("At eight o'clock", "Um acht Uhr"), tx("At seven o'clock", "Um sieben Uhr"), tx("At midday", "Um zwölf Uhr")], answer: 0 },
        { q: tx("What do the girls do after the shower?", "Was machen die Mädchen nach der Dusche?"), options: [tx("They get dressed and have breakfast.", "Sie ziehen sich an und frühstücken."), tx("They go back to bed.", "Sie gehen wieder ins Bett."), tx("They play football.", "Sie spielen Fußball.")], answer: 0 },
        { q: tx("What does Blob do at half past seven?", "Was macht Blob um halb acht?"), options: [tx("He goes to bed.", "Er geht ins Bett."), tx("He has a shower.", "Er duscht."), tx("He goes to school.", "Er geht in die Schule.")], answer: 0 },
      ],
    },
    {
      id: "u11.dialogue2",
      lesson: 7,
      title: tx("Late again!", "Schon wieder zu spät!"),
      lines: [
        { who: "hugo", fr: "Blob ! Quelle heure est-il ?", en: "Blob! What time is it?", de: "Blob! Wie spät ist es?" },
        { who: "blob", fr: "Il est huit heures moins le quart.", en: "It's quarter to eight.", de: "Es ist Viertel vor acht." },
        { who: "hugo", fr: "Oh là là ! L'école, c'est à huit heures ! Je suis en retard !", en: "Oh dear! School is at eight! I'm late!", de: "Oje! Die Schule ist um acht! Ich bin zu spät!" },
        { who: "blob", fr: "Dépêche-toi ! Et le petit-déjeuner ?", en: "Hurry up! And breakfast?", de: "Beeil dich! Und das Frühstück?" },
        { who: "hugo", fr: "Pas de petit-déjeuner ! D'abord je m'habille, ensuite je cours !", en: "No breakfast! First I get dressed, then I run!", de: "Kein Frühstück! Erst ziehe ich mich an, dann renne ich!" },
        { who: "prof", fr: "Hugo, tu es en retard tous les jours !", en: "Hugo, you're late every day!", de: "Hugo, du kommst jeden Tag zu spät!" },
        { who: "hugo", fr: "Pardon ! Je me dépêche, mais le bus est en retard aussi.", en: "Sorry! I hurry, but the bus is late too.", de: "Entschuldigung! Ich beeile mich, aber der Bus ist auch zu spät." },
        { who: "prof", fr: "Et le soir, tu te couches à quelle heure ?", en: "And what time do you go to bed in the evening?", de: "Und wann gehst du abends ins Bett?" },
        { who: "hugo", fr: "Euh… je me couche à minuit. Je joue aux jeux vidéo.", en: "Er… I go to bed at midnight. I play video games.", de: "Äh … ich gehe um Mitternacht ins Bett. Ich spiele Videospiele." },
        { who: "prof", fr: "À minuit ? Voilà le problème !", en: "At midnight? There's the problem!", de: "Um Mitternacht? Da ist das Problem!" },
      ],
      questions: [
        { q: tx("What time is it when Hugo asks Blob?", "Wie spät ist es, als Hugo Blob fragt?"), options: [tx("Quarter to eight", "Viertel vor acht"), tx("Half past seven", "Halb acht"), tx("Eight o'clock", "Acht Uhr")], answer: 0 },
        { q: tx("Does Hugo have breakfast?", "Frühstückt Hugo?"), options: [tx("No, there's no time.", "Nein, dafür ist keine Zeit."), tx("Yes, a croissant.", "Ja, ein Croissant."), tx("Yes, with Blob.", "Ja, mit Blob.")], answer: 0 },
        { q: tx("Why is Hugo always late?", "Warum ist Hugo immer zu spät?"), options: [tx("He goes to bed at midnight.", "Er geht um Mitternacht ins Bett."), tx("He has no alarm clock.", "Er hat keinen Wecker."), tx("He lives far away.", "Er wohnt weit weg.")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Je me lève: verbs with me, te, se", "Je me lève: Verben mit me, te, se"),
      body: tx(
        "Some verbs come with a little pronoun that means «myself, yourself…»: **je me lève** (I get up), **je me réveille**, **je me lave**, **je me couche**. German does the same: ich wasche **mich**.\n\nThe pronoun changes with the person: **me, te, se, nous, vous, se**. Before a vowel or a silent h it shrinks: je **m'habille**, il **s'habille**.\n\nNever leave it out: «je lève» is wrong, it's **je me lève**.",
        "Manche Verben haben ein kleines Pronomen, das „mich, dich, sich …“ bedeutet: **je me lève** (ich stehe auf), **je me réveille**, **je me lave**, **je me couche**. Im Deutschen ist es ähnlich: Ich wasche **mich**.\n\nDas Pronomen ändert sich mit der Person: **me, te, se, nous, vous, se**. Vor einem Vokal oder stummen h wird es kurz: je **m'habille**, il **s'habille**.\n\nNie weglassen: „je lève“ ist falsch, es heißt **je me lève**.",
      ),
      examples: [
        { fr: "Je me lève tôt.", en: "I get up early.", de: "Ich stehe früh auf." },
        { fr: "Tu te lèves à quelle heure ?", en: "What time do you get up?", de: "Um wie viel Uhr stehst du auf?" },
        { fr: "Je me lave et je m'habille.", en: "I wash and I get dressed.", de: "Ich wasche mich und ich ziehe mich an." },
      ],
      table: {
        head: [tx("person", "Person"), "se lever", "s'habiller"],
        rows: [
          [tx("I", "ich"), "je me lève", "je m'habille"],
          [tx("you", "du"), "tu te lèves", "tu t'habilles"],
          [tx("he / she", "er / sie"), "il / elle se lève", "il / elle s'habille"],
          [tx("we", "wir"), "nous nous levons", "nous nous habillons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous vous levez", "vous vous habillez"],
          [tx("they", "sie"), "ils / elles se lèvent", "ils / elles s'habillent"],
        ],
      },
    },
    {
      title: tx("What time is it?", "Wie spät ist es?"),
      body: tx(
        "Ask **quelle heure est-il ?** The answer starts with **il est** (here il means «it») + number + **heures**: il est huit heures. One o'clock is **une heure**, without s.\n\nAt a time: **à** sept heures, **à** midi, **à** minuit. For am and pm, add **du matin** or **du soir**: huit heures du soir.",
        "Frag **quelle heure est-il ?** Die Antwort beginnt mit **il est** (hier heißt il „es“) + Zahl + **heures**: il est huit heures. Ein Uhr ist **une heure**, ohne s.\n\nUm eine Uhrzeit: **à** sept heures, **à** midi, **à** minuit. Morgens oder abends: **du matin** oder **du soir**: huit heures du soir.\n\nAchtung: **huit heures et demie** ist halb **neun**! Französisch zählt von der vollen Stunde aus weiter.",
      ),
      examples: [
        { fr: "Quelle heure est-il ?", en: "What time is it?", de: "Wie spät ist es?" },
        { fr: "Il est sept heures et demie.", en: "It's half past seven.", de: "Es ist halb acht." },
        { fr: "Je me couche à minuit.", en: "I go to bed at midnight.", de: "Ich gehe um Mitternacht ins Bett." },
      ],
      table: {
        head: [tx("time", "Uhrzeit"), tx("French", "Französisch")],
        rows: [
          ["8:00", "huit heures"],
          ["8:15", "huit heures et quart"],
          ["8:30", "huit heures et demie"],
          ["8:45", "neuf heures moins le quart"],
          ["12:00", tx("midi (day) / minuit (night)", "midi (Mittag) / minuit (Mitternacht)")],
        ],
      },
    },
    {
      title: tx("My day in order", "Mein Tag der Reihe nach"),
      body: tx(
        "Tell your day step by step: **d'abord** (first), **ensuite** (then), **après** (afterwards). Before a noun, use après: **après le dîner**.\n\nThe meals: **le petit-déjeuner**, **le déjeuner** (at midi), **le dîner** (in the evening). And **le matin**, **le soir**, **le samedi** also mean «in the morning», «in the evening», «on Saturdays».",
        "Erzähl deinen Tag Schritt für Schritt: **d'abord** (zuerst), **ensuite** (dann), **après** (danach). Vor einem Nomen steht après: **après le dîner** (nach dem Abendessen).\n\nDie Mahlzeiten: **le petit-déjeuner**, **le déjeuner** (um midi), **le dîner** (am Abend). Und **le matin**, **le soir**, **le samedi** heißen auch „morgens“, „abends“, „samstags“.",
      ),
      examples: [
        { fr: "D'abord je me lave, ensuite je m'habille.", en: "First I wash, then I get dressed.", de: "Zuerst wasche ich mich, dann ziehe ich mich an." },
        { fr: "Après le petit-déjeuner, je vais à l'école.", en: "After breakfast, I go to school.", de: "Nach dem Frühstück gehe ich in die Schule." },
        { fr: "Le soir, je me couche à dix heures.", en: "In the evening, I go to bed at ten o'clock.", de: "Abends gehe ich um zehn Uhr ins Bett." },
      ],
    },
    {
      title: tx("Don't hurry, hurry up!", "Beeil dich nicht, beeil dich!"),
      body: tx(
        "In a negative sentence, **ne** goes before the little pronoun and **pas** after the verb: je **ne me** lève **pas** tôt.\n\nTelling someone to do it, the pronoun comes after the verb with a dash: **dépêche-toi !** (hurry up!), **lève-toi !**, **levez-vous !**\n\nAnd two kinds of late: **en retard** (not on time) and **tard** (late in the day).",
        "In einem verneinten Satz steht **ne** vor dem kleinen Pronomen und **pas** nach dem Verb: je **ne me** lève **pas** tôt.\n\nWenn du jemanden aufforderst, kommt das Pronomen mit Bindestrich nach dem Verb: **dépêche-toi !** (beeil dich!), **lève-toi !**, **levez-vous !**\n\nUnd zweimal „spät“: **en retard** (zu spät, nicht pünktlich) und **tard** (spät am Tag).",
      ),
      examples: [
        { fr: "Ils ne se couchent pas avant minuit.", en: "They don't go to bed before midnight.", de: "Sie gehen nicht vor Mitternacht ins Bett." },
        { fr: "Dépêche-toi, Blob !", en: "Hurry up, Blob!", de: "Beeil dich, Blob!" },
        { fr: "Je me dépêche, je suis en retard !", en: "I'm hurrying, I'm late!", de: "Ich beeile mich, ich bin zu spät!" },
      ],
      table: {
        head: [tx("you", "du / ihr"), tx("not", "nicht"), tx("do it!", "Aufforderung")],
        rows: [
          ["tu te lèves", "tu ne te lèves pas", "lève-toi !"],
          ["vous vous levez", "vous ne vous levez pas", "levez-vous !"],
          ["tu te dépêches", "tu ne te dépêches pas", "dépêche-toi !"],
        ],
      },
    },
  ],
};
