import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 12: habiter, rooms and furniture, and where things are (devant, derrière, à côté de). */
export const u12: Unit = {
  slug: "chez-moi",
  n: 12,
  cefr: "A2",
  title: tx("At home", "Zu Hause"),
  goal: tx("Say where you live and where things are", "Sagen, wo du wohnst und wo etwas steht"),
  emoji: "🛋️",
  words: [
    { id: "j-habite", fr: "j'habite", en: "I live", de: "ich wohne", kind: "verb", note: tx("From habiter. The h is silent, so je becomes j': j'habite à Lyon.", "Von habiter. Das h ist stumm, darum wird je zu j': j'habite à Lyon.") },
    { id: "tu-habites", fr: "tu habites", en: "you live", de: "du wohnst", kind: "verb", note: tx("Tu habites où ? Where do you live? The s is silent.", "Tu habites où ? Wo wohnst du? Das s ist stumm.") },
    { id: "il-habite", fr: "il habite", en: "he lives", de: "er wohnt", kind: "verb", note: tx("You link the words: il‿habite sounds like «ee-la-beet».", "Man bindet: il‿habite klingt wie „i-la-bit“.") },
    { id: "appartement", fr: "l'appartement", en: "the flat", de: "die Wohnung", alt: { en: ["the apartment"], de: ["das Apartment"] }, g: "m", kind: "noun", emoji: "🏢", note: tx("Two p's in French, and it's masculine: un appartement.", "Mit zwei p und männlich: un appartement.") },
    { id: "chez-moi", fr: "chez moi", en: "at my place", de: "bei mir", alt: { en: ["at home", "my place", "home"], de: ["zu Hause", "bei mir zu Hause"] }, kind: "phrase", note: tx("Chez means «at the home of», like bei in German: chez moi, chez toi, chez Léa.", "Chez heißt „bei“: chez moi, chez toi, chez Léa.") },
    { id: "chambre", fr: "la chambre", en: "the bedroom", de: "das Schlafzimmer", alt: { en: ["the room"], de: ["das Zimmer"] }, g: "f", kind: "noun", note: tx("Careful: la chambre is the room you sleep in. Any room is une pièce.", "Vorsicht: la chambre ist das Zimmer, in dem du schläfst. Irgendein Zimmer ist une pièce.") },
    { id: "cuisine", fr: "la cuisine", en: "the kitchen", de: "die Küche", g: "f", kind: "noun", emoji: "🍳", note: tx("Also the cooking: la cuisine française.", "Auch das Kochen: la cuisine française, die französische Küche.") },
    { id: "salon", fr: "le salon", en: "the living room", de: "das Wohnzimmer", alt: { en: ["the lounge", "the sitting room"] }, g: "m", kind: "noun", note: tx("Where the sofa and the TV are.", "Wo das Sofa und der Fernseher stehen.") },
    { id: "salle-de-bains", fr: "la salle de bains", en: "the bathroom", de: "das Badezimmer", alt: { de: ["das Bad"] }, g: "f", kind: "noun", emoji: "🛁", note: tx("Salle = room, bains = baths. The toilet is often in its own little room: les toilettes.", "Salle = Raum, bains = Bäder. Die Toilette ist oft ein eigener kleiner Raum: les toilettes.") },
    { id: "jardin", fr: "le jardin", en: "the garden", de: "der Garten", g: "m", kind: "noun", emoji: "🏡", note: tx("Garden, jardin, Garten: the same old word.", "Garden, jardin, Garten: dasselbe alte Wort.") },
    { id: "lit", fr: "le lit", en: "the bed", de: "das Bett", g: "m", kind: "noun", emoji: "🛏️", note: tx("The t is silent: «lee».", "Das t ist stumm: „li“.") },
    { id: "table", fr: "la table", en: "the table", de: "der Tisch", g: "f", kind: "noun", note: tx("The same word as in English, but feminine: une table.", "Wie table im Englischen, aber weiblich: une table.") },
    { id: "chaise", fr: "la chaise", en: "the chair", de: "der Stuhl", g: "f", kind: "noun", emoji: "🪑" },
    { id: "canape", fr: "le canapé", en: "the sofa", de: "das Sofa", alt: { en: ["the couch"], de: ["die Couch"] }, g: "m", kind: "noun", emoji: "🛋️", note: tx("Also a little party snack on bread: un canapé!", "Auch ein kleiner Party-Happen auf Brot: un canapé!") },
    { id: "fenetre", fr: "la fenêtre", en: "the window", de: "das Fenster", g: "f", kind: "noun", emoji: "🪟", note: tx("The ê hides an old s: fenestra in Latin, Fenster in German.", "Das ê versteckt ein altes s: fenestra auf Latein, Fenster auf Deutsch.") },
    { id: "porte", fr: "la porte", en: "the door", de: "die Tür", g: "f", kind: "noun", emoji: "🚪", note: tx("Don't mix it up with il porte (he wears)!", "Nicht verwechseln mit il porte (er trägt)!") },
    { id: "devant", fr: "devant", en: "in front of", de: "vor", kind: "word", note: tx("No de after it: devant la porte.", "Ohne de danach: devant la porte.") },
    { id: "derriere", fr: "derrière", en: "behind", de: "hinter", kind: "word", note: tx("No de either: derrière la maison.", "Auch ohne de: derrière la maison.") },
    { id: "a-cote-de", fr: "à côté de", en: "next to", de: "neben", alt: { en: ["beside"] }, kind: "phrase", note: tx("De + le = du: à côté du lit. De la stays: à côté de la gare.", "De + le = du: à côté du lit. De la bleibt: à côté de la gare.") },
    { id: "entre", fr: "entre", en: "between", de: "zwischen", kind: "word", note: tx("Entre … et …: entre la table et la fenêtre.", "Entre … et …: entre la table et la fenêtre.") },
    { id: "il-n-y-a-pas-de", fr: "il n'y a pas de", en: "there is no", de: "es gibt kein", alt: { en: ["there isn't any", "there are no"], de: ["es gibt keine", "es gibt keinen"] }, kind: "phrase", note: tx("Il y a un jardin → il n'y a pas de jardin. Un, une and des all become de.", "Il y a un jardin → il n'y a pas de jardin. Un, une und des werden alle zu de.") },
    { id: "nous-habitons", fr: "nous habitons", en: "we live", de: "wir wohnen", kind: "verb", note: tx("You hear a z: nous‿habitons.", "Man hört ein weiches s: nous‿habitons.") },
    { id: "vous-habitez", fr: "vous habitez", en: "you live (plural / polite)", de: "ihr wohnt / Sie wohnen", kind: "verb" },
    { id: "etage", fr: "l'étage", en: "the floor", de: "der Stock", alt: { en: ["the storey"], de: ["das Stockwerk", "die Etage"] }, g: "m", kind: "noun", note: tx("The ground floor is le rez-de-chaussée. Le premier étage is one floor up.", "Das Erdgeschoss ist le rez-de-chaussée. Le premier étage ist der erste Stock.") },
    { id: "escalier", fr: "l'escalier", en: "the stairs", de: "die Treppe", alt: { en: ["the staircase"] }, g: "m", kind: "noun", note: tx("One word, singular and masculine: l'escalier.", "Ein Wort, Singular und männlich: l'escalier.") },
    { id: "en-haut", fr: "en haut", en: "upstairs", de: "oben", alt: { en: ["up", "at the top"] }, kind: "phrase", note: tx("The h is silent, but you don't link: en | haut.", "Das h ist stumm, aber man bindet nicht: en | haut.") },
    { id: "en-bas", fr: "en bas", en: "downstairs", de: "unten", alt: { en: ["down", "at the bottom"] }, kind: "phrase" },
    { id: "armoire", fr: "l'armoire", en: "the wardrobe", de: "der Kleiderschrank", alt: { de: ["der Schrank"] }, g: "f", kind: "noun", note: tx("Feminine, even with l': une armoire.", "Weiblich, auch mit l': une armoire.") },
    { id: "lampe", fr: "la lampe", en: "the lamp", de: "die Lampe", g: "f", kind: "noun" },
    { id: "tele", fr: "la télé", en: "the TV", de: "der Fernseher", alt: { en: ["the television", "the telly"], de: ["das Fernsehen"] }, g: "f", kind: "noun", emoji: "📺", note: tx("Short for la télévision. Watching TV: regarder la télé.", "Kurz für la télévision. Fernsehen: regarder la télé.") },
    { id: "cle", fr: "la clé", en: "the key", de: "der Schlüssel", alt: { fr: ["la clef"] }, g: "f", kind: "noun", emoji: "🔑", note: tx("Also spelled clef, with a silent f.", "Auch clef geschrieben, mit stummem f.") },
  ],
  gloss: [
    { fr: "habite", en: "live / lives", de: "wohne / wohnt" },
    { fr: "habites", en: "live (you)", de: "wohnst" },
    { fr: "habitons", en: "live (we)", de: "wohnen (wir)" },
    { fr: "habitez", en: "live (you, plural / polite)", de: "wohnt / wohnen (Sie)" },
    { fr: "habitent", en: "live (they)", de: "wohnen (sie)" },
    { fr: "à côté du", en: "next to the", de: "neben dem" },
    { fr: "à côté de la", en: "next to the", de: "neben der / dem" },
    { fr: "dort", en: "sleeps / is sleeping", de: "schläft" },
    { fr: "chaises", en: "chairs", de: "Stühle" },
    { fr: "vêtements", en: "clothes", de: "Kleider" },
    { fr: "ascenseur", en: "lift", de: "Aufzug" },
    { fr: "premier", en: "first", de: "erste(r)" },
    { fr: "troisième", en: "third", de: "dritte(r)" },
    { fr: "bienvenue", en: "welcome", de: "willkommen" },
    { fr: "chez toi", en: "at your place", de: "bei dir" },
    { fr: "regardez", en: "look (you, plural / polite)", de: "schaut / schauen Sie" },
    { fr: "pas de problème", en: "no problem", de: "kein Problem" },
    { fr: "elle porte", en: "she wears", de: "sie trägt" },
    { fr: "ne porte", en: "don't wear / doesn't wear", de: "trage / trägt nicht" },
  ],
  lessons: [
    { title: tx("Where do you live?", "Wo wohnst du?"), words: ["j-habite", "tu-habites", "il-habite", "appartement", "chez-moi"] },
    { title: tx("The rooms", "Die Zimmer"), words: ["chambre", "cuisine", "salon", "salle-de-bains", "jardin"] },
    { title: tx("Bed, table, chair", "Bett, Tisch, Stuhl"), words: ["lit", "table", "chaise", "canape", "fenetre", "porte"] },
    { title: tx("In front, behind, next to", "Vor, hinter, neben"), words: ["devant", "derriere", "a-cote-de", "entre"] },
    { title: tx("There's no garden", "Es gibt keinen Garten"), words: ["il-n-y-a-pas-de", "nous-habitons", "vous-habitez"] },
    { title: tx("Upstairs, downstairs", "Oben, unten"), words: ["etage", "escalier", "en-haut", "en-bas"] },
    { title: tx("Where's the key?", "Wo ist der Schlüssel?"), words: ["armoire", "lampe", "tele", "cle"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u12.01", lesson: 1, fr: "J'habite à Lyon.", en: "I live in Lyon.", de: "Ich wohne in Lyon." },
    { id: "u12.02", lesson: 1, fr: "Tu habites où ?", en: "Where do you live?", de: "Wo wohnst du?", alt: { fr: ["Où tu habites ?", "Où habites-tu ?", "Où est-ce que tu habites ?", "Vous habitez où ?", "Où vous habitez ?", "Où habitez-vous ?", "Où est-ce que vous habitez ?"] } },
    { id: "u12.03", lesson: 1, fr: "J'habite dans un appartement.", en: "I live in a flat.", de: "Ich wohne in einer Wohnung.", alt: { en: ["I live in an apartment."] } },
    { id: "u12.04", lesson: 1, fr: "Il habite dans une grande maison.", en: "He lives in a big house.", de: "Er wohnt in einem großen Haus.", alt: { en: ["He lives in a large house."] } },
    { id: "u12.05", lesson: 1, fr: "Le soir, je suis chez moi.", en: "In the evening, I'm at home.", de: "Abends bin ich zu Hause.", alt: { fr: ["Je suis chez moi le soir."], en: ["In the evening, I'm at my place.", "In the evening, I'm home.", "I'm at home in the evening.", "I'm home in the evening."], de: ["Am Abend bin ich zu Hause.", "Ich bin abends zu Hause.", "Abends bin ich bei mir.", "Abends bin ich daheim.", "Abends bin ich bei mir zu Hause."] } },
    { id: "u12.06", lesson: 1, fr: "L'appartement est petit mais joli.", en: "The flat is small but pretty.", de: "Die Wohnung ist klein, aber schön.", alt: { en: ["The apartment is small but pretty.", "The flat is small but nice.", "The apartment is small but nice."], de: ["Die Wohnung ist klein, aber hübsch."] } },
    { id: "u12.07", lesson: 1, fr: "Est-ce que Hugo habite à Paris ?", en: "Does Hugo live in Paris?", de: "Wohnt Hugo in Paris?", alt: { fr: ["Hugo habite à Paris ?", "Hugo habite-t-il à Paris ?"] } },
    // Lesson 2
    { id: "u12.08", lesson: 2, fr: "Ma chambre est petite.", en: "My bedroom is small.", de: "Mein Zimmer ist klein.", alt: { en: ["My room is small."], de: ["Mein Schlafzimmer ist klein."] } },
    { id: "u12.09", lesson: 2, fr: "Maman est dans la cuisine.", en: "Mum is in the kitchen.", de: "Mama ist in der Küche.", alt: { fr: ["Maman est à la cuisine."], en: ["Mom is in the kitchen."] } },
    { id: "u12.10", lesson: 2, fr: "Le soir, nous sommes dans le salon.", en: "In the evening, we're in the living room.", de: "Abends sind wir im Wohnzimmer.", alt: { fr: ["Nous sommes dans le salon le soir.", "Le soir, on est dans le salon."], en: ["In the evening, we're in the lounge.", "In the evening, we're in the sitting room.", "We're in the living room in the evening."], de: ["Am Abend sind wir im Wohnzimmer.", "Wir sind abends im Wohnzimmer."] } },
    { id: "u12.11", lesson: 2, fr: "La salle de bains est à droite.", en: "The bathroom is on the right.", de: "Das Badezimmer ist rechts.", alt: { de: ["Das Bad ist rechts."] } },
    { id: "u12.12", lesson: 2, fr: "Tu as un jardin ?", en: "Do you have a garden?", de: "Hast du einen Garten?", alt: { fr: ["Est-ce que tu as un jardin ?", "As-tu un jardin ?", "Vous avez un jardin ?", "Est-ce que vous avez un jardin ?", "Avez-vous un jardin ?"], en: ["Have you got a garden?"] } },
    { id: "u12.13", lesson: 2, fr: "Le chat dort dans le jardin.", en: "The cat is sleeping in the garden.", de: "Die Katze schläft im Garten.", alt: { en: ["The cat sleeps in the garden."] } },
    { id: "u12.14", lesson: 2, fr: "Je prends le petit-déjeuner dans la cuisine.", en: "I have breakfast in the kitchen.", de: "Ich frühstücke in der Küche.", alt: { fr: ["Je prends mon petit-déjeuner dans la cuisine."], en: ["I eat breakfast in the kitchen."] } },
    // Lesson 3
    { id: "u12.15", lesson: 3, fr: "Le chat est sur le lit.", en: "The cat is on the bed.", de: "Die Katze ist auf dem Bett.", alt: { de: ["Die Katze liegt auf dem Bett."] } },
    { id: "u12.16", lesson: 3, fr: "Le livre est sous la chaise.", en: "The book is under the chair.", de: "Das Buch ist unter dem Stuhl.", alt: { de: ["Das Buch liegt unter dem Stuhl."] } },
    { id: "u12.17", lesson: 3, fr: "Les croissants sont sur la table.", en: "The croissants are on the table.", de: "Die Croissants sind auf dem Tisch.", alt: { de: ["Die Croissants liegen auf dem Tisch."] } },
    { id: "u12.18", lesson: 3, fr: "Blob dort sur le canapé.", en: "Blob is sleeping on the sofa.", de: "Blob schläft auf dem Sofa.", alt: { en: ["Blob sleeps on the sofa.", "Blob is sleeping on the couch.", "Blob sleeps on the couch."], de: ["Blob schläft auf der Couch."] } },
    { id: "u12.19", lesson: 3, fr: "Il y a une grande fenêtre dans ma chambre.", en: "There's a big window in my bedroom.", de: "In meinem Zimmer gibt es ein großes Fenster.", alt: { fr: ["Dans ma chambre, il y a une grande fenêtre."], en: ["There's a large window in my bedroom.", "There's a big window in my room.", "There's a large window in my room.", "My bedroom has a big window.", "My room has a big window."], de: ["In meinem Zimmer ist ein großes Fenster.", "Es gibt ein großes Fenster in meinem Zimmer.", "Mein Zimmer hat ein großes Fenster.", "In meinem Schlafzimmer gibt es ein großes Fenster.", "Mein Schlafzimmer hat ein großes Fenster."] } },
    { id: "u12.20", lesson: 3, fr: "La porte de la cuisine est rouge.", en: "The kitchen door is red.", de: "Die Küchentür ist rot.", alt: { en: ["The door of the kitchen is red."], de: ["Die Tür der Küche ist rot."] } },
    { id: "u12.21", lesson: 3, fr: "Il y a quatre chaises dans la cuisine.", en: "There are four chairs in the kitchen.", de: "In der Küche gibt es vier Stühle.", alt: { fr: ["Dans la cuisine, il y a quatre chaises."], en: ["There are 4 chairs in the kitchen."], de: ["Es gibt vier Stühle in der Küche.", "In der Küche sind vier Stühle.", "In der Küche gibt es 4 Stühle.", "Es gibt 4 Stühle in der Küche."] } },
    // Lesson 4
    { id: "u12.22", lesson: 4, fr: "Le jardin est derrière la maison.", en: "The garden is behind the house.", de: "Der Garten ist hinter dem Haus.", alt: { de: ["Der Garten liegt hinter dem Haus."] } },
    { id: "u12.23", lesson: 4, fr: "Le vélo est devant la porte.", en: "The bike is in front of the door.", de: "Das Fahrrad ist vor der Tür.", alt: { en: ["The bicycle is in front of the door."], de: ["Das Fahrrad steht vor der Tür.", "Das Rad ist vor der Tür.", "Das Rad steht vor der Tür."] } },
    { id: "u12.24", lesson: 4, fr: "J'habite à côté de la gare.", en: "I live next to the station.", de: "Ich wohne neben dem Bahnhof.", alt: { en: ["I live beside the station.", "I live next to the train station."] } },
    { id: "u12.25", lesson: 4, fr: "La chaise est à côté du lit.", en: "The chair is next to the bed.", de: "Der Stuhl ist neben dem Bett.", alt: { en: ["The chair is beside the bed."], de: ["Der Stuhl steht neben dem Bett."] } },
    { id: "u12.26", lesson: 4, fr: "La table est entre le canapé et la fenêtre.", en: "The table is between the sofa and the window.", de: "Der Tisch ist zwischen dem Sofa und dem Fenster.", alt: { en: ["The table is between the couch and the window."], de: ["Der Tisch steht zwischen dem Sofa und dem Fenster.", "Der Tisch ist zwischen der Couch und dem Fenster.", "Der Tisch steht zwischen der Couch und dem Fenster."] } },
    { id: "u12.27", lesson: 4, fr: "Le chien est derrière le canapé !", en: "The dog is behind the sofa!", de: "Der Hund ist hinter dem Sofa!", alt: { en: ["The dog is behind the couch!"], de: ["Der Hund ist hinter der Couch!"] } },
    { id: "u12.28", lesson: 4, fr: "Il habite à côté de l'école.", en: "He lives next to the school.", de: "Er wohnt neben der Schule.", alt: { en: ["He lives beside the school."] } },
    // Lesson 5
    { id: "u12.29", lesson: 5, fr: "Il n'y a pas de jardin.", en: "There's no garden.", de: "Es gibt keinen Garten.", alt: { en: ["There isn't a garden.", "There isn't any garden."], de: ["Da ist kein Garten."] } },
    { id: "u12.30", lesson: 5, fr: "Nous habitons dans un appartement.", en: "We live in a flat.", de: "Wir wohnen in einer Wohnung.", alt: { fr: ["On habite dans un appartement."], en: ["We live in an apartment."] } },
    { id: "u12.31", lesson: 5, fr: "Vous habitez à Paris ?", en: "Do you live in Paris?", de: "Wohnt ihr in Paris?", alt: { fr: ["Est-ce que vous habitez à Paris ?", "Habitez-vous à Paris ?", "Tu habites à Paris ?", "Est-ce que tu habites à Paris ?", "Habites-tu à Paris ?"], de: ["Wohnen Sie in Paris?"] } },
    { id: "u12.32", lesson: 5, fr: "Il n'y a pas de canapé dans le salon.", en: "There's no sofa in the living room.", de: "Im Wohnzimmer gibt es kein Sofa.", alt: { fr: ["Dans le salon, il n'y a pas de canapé."], en: ["There isn't a sofa in the living room.", "There's no couch in the living room.", "There's no sofa in the lounge.", "There isn't a couch in the living room."], de: ["Es gibt kein Sofa im Wohnzimmer.", "Im Wohnzimmer ist kein Sofa.", "Im Wohnzimmer gibt es keine Couch."] } },
    { id: "u12.33", lesson: 5, fr: "Il n'y a pas de chaises !", en: "There are no chairs!", de: "Es gibt keine Stühle!", alt: { en: ["There aren't any chairs!"], de: ["Da sind keine Stühle!"] } },
    { id: "u12.34", lesson: 5, fr: "Nous habitons à côté du parc.", en: "We live next to the park.", de: "Wir wohnen neben dem Park.", alt: { fr: ["On habite à côté du parc."], en: ["We live beside the park."] } },
    { id: "u12.35", lesson: 5, fr: "Madame Martin, vous habitez ici ?", en: "Mrs Martin, do you live here?", de: "Frau Martin, wohnen Sie hier?", alt: { fr: ["Madame Martin, est-ce que vous habitez ici ?", "Madame Martin, habitez-vous ici ?", "Vous habitez ici, Madame Martin ?"], en: ["Do you live here, Mrs Martin?"], de: ["Wohnen Sie hier, Frau Martin?"] } },
    // Lesson 6
    { id: "u12.36", lesson: 6, fr: "Ma chambre est en haut.", en: "My bedroom is upstairs.", de: "Mein Zimmer ist oben.", alt: { en: ["My room is upstairs."], de: ["Mein Schlafzimmer ist oben."] } },
    { id: "u12.37", lesson: 6, fr: "La cuisine est en bas.", en: "The kitchen is downstairs.", de: "Die Küche ist unten." },
    { id: "u12.38", lesson: 6, fr: "J'habite au troisième étage.", en: "I live on the third floor.", de: "Ich wohne im dritten Stock.", alt: { en: ["I live on the 3rd floor."], de: ["Ich wohne im 3. Stock.", "Ich wohne in der dritten Etage.", "Ich wohne im dritten Stockwerk."] } },
    { id: "u12.39", lesson: 6, fr: "L'escalier est derrière la porte.", en: "The stairs are behind the door.", de: "Die Treppe ist hinter der Tür.", alt: { en: ["The staircase is behind the door."] } },
    { id: "u12.40", lesson: 6, fr: "Il n'y a pas d'ascenseur.", en: "There's no lift.", de: "Es gibt keinen Aufzug.", alt: { en: ["There isn't a lift.", "There's no elevator.", "There isn't an elevator."], de: ["Es gibt keinen Fahrstuhl.", "Da ist kein Aufzug."] } },
    { id: "u12.41", lesson: 6, fr: "Les toilettes sont en haut, à gauche.", en: "The toilets are upstairs, on the left.", de: "Die Toilette ist oben links.", alt: { en: ["The toilet is upstairs, on the left."], de: ["Die Toiletten sind oben links.", "Die Toilette ist oben auf der linken Seite."] } },
    { id: "u12.42", lesson: 6, fr: "Est-ce que ta chambre est en haut ou en bas ?", en: "Is your bedroom upstairs or downstairs?", de: "Ist dein Zimmer oben oder unten?", alt: { fr: ["Ta chambre est en haut ou en bas ?", "Votre chambre est en haut ou en bas ?", "Est-ce que votre chambre est en haut ou en bas ?"], en: ["Is your room upstairs or downstairs?"], de: ["Ist dein Schlafzimmer oben oder unten?"] } },
    { id: "u12.43", lesson: 6, fr: "Nous habitons au premier étage.", en: "We live on the first floor.", de: "Wir wohnen im ersten Stock.", alt: { fr: ["On habite au premier étage."], en: ["We live on the 1st floor."], de: ["Wir wohnen im 1. Stock.", "Wir wohnen in der ersten Etage.", "Wir wohnen im ersten Stockwerk."] } },
    // Lesson 7
    { id: "u12.44", lesson: 7, fr: "Mes vêtements sont dans l'armoire.", en: "My clothes are in the wardrobe.", de: "Meine Kleider sind im Kleiderschrank.", alt: { de: ["Meine Kleidung ist im Kleiderschrank.", "Meine Kleider sind im Schrank.", "Meine Kleidung ist im Schrank.", "Meine Klamotten sind im Schrank.", "Meine Sachen sind im Kleiderschrank."] } },
    { id: "u12.45", lesson: 7, fr: "Il y a une lampe à côté du lit.", en: "There's a lamp next to the bed.", de: "Neben dem Bett steht eine Lampe.", alt: { fr: ["À côté du lit, il y a une lampe."], en: ["There's a lamp beside the bed."], de: ["Neben dem Bett ist eine Lampe.", "Neben dem Bett gibt es eine Lampe.", "Es gibt eine Lampe neben dem Bett."] } },
    { id: "u12.46", lesson: 7, fr: "Je regarde la télé dans le salon.", en: "I watch TV in the living room.", de: "Ich sehe im Wohnzimmer fern.", alt: { en: ["I'm watching TV in the living room.", "I watch television in the living room.", "I watch TV in the lounge.", "I watch the telly in the living room."], de: ["Ich schaue im Wohnzimmer fern.", "Ich gucke im Wohnzimmer fern.", "Im Wohnzimmer sehe ich fern.", "Im Wohnzimmer schaue ich fern."] } },
    { id: "u12.47", lesson: 7, fr: "Où est la clé ?", en: "Where is the key?", de: "Wo ist der Schlüssel?", alt: { fr: ["La clé est où ?", "Elle est où, la clé ?", "Où est la clef ?"] } },
    { id: "u12.48", lesson: 7, fr: "La clé est dans mon sac.", en: "The key is in my bag.", de: "Der Schlüssel ist in meiner Tasche.", alt: { fr: ["La clef est dans mon sac."] } },
    { id: "u12.49", lesson: 7, fr: "Il n'y a pas de télé dans ma chambre.", en: "There's no TV in my bedroom.", de: "In meinem Zimmer gibt es keinen Fernseher.", alt: { fr: ["Dans ma chambre, il n'y a pas de télé."], en: ["There isn't a TV in my bedroom.", "There's no TV in my room.", "There isn't a TV in my room.", "There's no television in my bedroom.", "My bedroom has no TV.", "My room has no TV."], de: ["Es gibt keinen Fernseher in meinem Zimmer.", "In meinem Zimmer ist kein Fernseher.", "Mein Zimmer hat keinen Fernseher.", "In meinem Schlafzimmer gibt es keinen Fernseher."] } },
    { id: "u12.50", lesson: 7, fr: "Ils habitent dans une petite maison avec un jardin.", en: "They live in a small house with a garden.", de: "Sie wohnen in einem kleinen Haus mit Garten.", alt: { fr: ["Elles habitent dans une petite maison avec un jardin."], en: ["They live in a little house with a garden."], de: ["Sie wohnen in einem kleinen Haus mit einem Garten."] } },
    { id: "u12.51", lesson: 7, fr: "Blob cherche la clé derrière l'armoire.", en: "Blob is looking for the key behind the wardrobe.", de: "Blob sucht den Schlüssel hinter dem Kleiderschrank.", alt: { fr: ["Blob cherche la clef derrière l'armoire."], en: ["Blob looks for the key behind the wardrobe."], de: ["Blob sucht den Schlüssel hinter dem Schrank."] } },
  ],
  drills: [
    { id: "u12.d1", lesson: 1, fr: "___ à Lyon.", options: ["J'habite", "Je habite"], answer: 0, en: "I live in Lyon.", de: "Ich wohne in Lyon.", why: tx("The h of habiter is silent, so **je** shrinks to **j'**: **j'habite**.", "Das h von habiter ist stumm, darum wird **je** zu **j'**: **j'habite**.") },
    { id: "u12.d2", lesson: 1, fr: "Il ___ dans une grande maison.", options: ["habite", "habites", "habitent"], answer: 0, en: "He lives in a big house.", de: "Er wohnt in einem großen Haus.", why: tx("With **il** and **elle** the ending is **-e**: il habit**e**.", "Mit **il** und **elle** endet es auf **-e**: il habit**e**.") },
    { id: "u12.d3", lesson: 2, fr: "Tu ___ où ?", options: ["habites", "habite", "habitez"], answer: 0, en: "Where do you live?", de: "Wo wohnst du?", why: tx("With **tu** the ending is **-es**: tu habit**es** (the s is silent).", "Mit **tu** endet es auf **-es**: tu habit**es** (das s ist stumm).") },
    { id: "u12.d4", lesson: 2, fr: "Maman est dans ___ cuisine.", options: ["la", "le"], answer: 0, en: "Mum is in the kitchen.", de: "Mama ist in der Küche.", why: tx("**Cuisine** is feminine: **la** cuisine.", "**Cuisine** ist weiblich: **la** cuisine.") },
    { id: "u12.d5", lesson: 2, fr: "___ chambre est petite.", options: ["Ma", "Mon"], answer: 0, en: "My bedroom is small.", de: "Mein Zimmer ist klein.", why: tx("**Chambre** is feminine: **ma** chambre (and petit**e**).", "**Chambre** ist weiblich: **ma** chambre (und petit**e**).") },
    { id: "u12.d6", lesson: 3, fr: "Il y a quatre ___ dans la cuisine.", options: ["chaises", "chaise"], answer: 0, en: "There are four chairs in the kitchen.", de: "In der Küche gibt es vier Stühle.", why: tx("More than one: **chaises**, with an s you don't hear.", "Mehr als einer: **chaises**, mit einem s, das man nicht hört.") },
    { id: "u12.d7", lesson: 3, fr: "Le livre est sous ___ chaise.", options: ["la", "le"], answer: 0, en: "The book is under the chair.", de: "Das Buch ist unter dem Stuhl.", why: tx("**Chaise** is feminine: **la** chaise, even if der Stuhl is masculine in German.", "**Chaise** ist weiblich: **la** chaise, auch wenn der Stuhl männlich ist.") },
    { id: "u12.d8", lesson: 3, fr: "La porte ___ la cuisine est rouge.", options: ["de", "du"], answer: 0, en: "The kitchen door is red.", de: "Die Küchentür ist rot.", why: tx("The door of the kitchen: la porte **de** la cuisine. Du is only de + le: la porte du salon.", "Die Tür der Küche: la porte **de** la cuisine. Du ist nur de + le: la porte du salon.") },
    { id: "u12.d9", lesson: 4, fr: "La chaise est à côté ___ lit.", options: ["du", "de le", "de la"], answer: 0, en: "The chair is next to the bed.", de: "Der Stuhl ist neben dem Bett.", why: tx("De + le always melts into **du**: à côté **du** lit.", "De + le wird immer zu **du**: à côté **du** lit.") },
    { id: "u12.d10", lesson: 4, fr: "La table est entre le canapé ___ la fenêtre.", options: ["et", "ou", "à"], answer: 0, en: "The table is between the sofa and the window.", de: "Der Tisch ist zwischen dem Sofa und dem Fenster.", why: tx("**Entre** … **et** …: between the sofa **and** the window.", "**Entre** … **et** …: zwischen dem Sofa **und** dem Fenster.") },
    { id: "u12.d11", lesson: 4, fr: "Le jardin est ___ la maison.", options: ["derrière", "derrière de", "à côté"], answer: 0, en: "The garden is behind the house.", de: "Der Garten ist hinter dem Haus.", why: tx("**Devant** and **derrière** take no de: **derrière** la maison. Only à côté needs it: à côté de la maison.", "**Devant** und **derrière** stehen ohne de: **derrière** la maison. Nur à côté braucht es: à côté de la maison.") },
    { id: "u12.d12", lesson: 5, fr: "Il n'y a pas ___ jardin.", options: ["de", "du", "des"], answer: 0, en: "There's no garden.", de: "Es gibt keinen Garten.", why: tx("After **pas**, un, une, du and des all become **de**: il n'y a pas **de** jardin.", "Nach **pas** werden un, une, du und des alle zu **de**: il n'y a pas **de** jardin.") },
    { id: "u12.d13", lesson: 5, fr: "Nous ___ dans un appartement.", options: ["habitons", "habitez", "habite"], answer: 0, en: "We live in a flat.", de: "Wir wohnen in einer Wohnung.", why: tx("With **nous** the ending is **-ons**: nous habit**ons**.", "Mit **nous** endet es auf **-ons**: nous habit**ons**.") },
    { id: "u12.d14", lesson: 5, fr: "Vous ___ à Paris ?", options: ["habitez", "habitons", "habites"], answer: 0, en: "Do you live in Paris?", de: "Wohnt ihr in Paris?", why: tx("With **vous** the ending is **-ez**: vous habit**ez**.", "Mit **vous** endet es auf **-ez**: vous habit**ez**.") },
    { id: "u12.d15", lesson: 6, fr: "Il n'y a pas ___.", options: ["d'ascenseur", "de ascenseur", "des ascenseur"], answer: 0, en: "There's no lift.", de: "Es gibt keinen Aufzug.", why: tx("**De** shrinks to **d'** before a vowel: pas **d'ascenseur**.", "**De** wird vor einem Vokal zu **d'**: pas **d'ascenseur**.") },
    { id: "u12.d16", lesson: 6, fr: "Nous habitons ___ premier étage.", options: ["au", "à le", "en"], answer: 0, en: "We live on the first floor.", de: "Wir wohnen im ersten Stock.", why: tx("On a floor: à, and à + le = **au**: **au** premier étage.", "Im Stock: à, und à + le = **au**: **au** premier étage.") },
    { id: "u12.d17", lesson: 6, fr: "La cuisine est ___ bas.", options: ["en", "dans", "à"], answer: 0, en: "The kitchen is downstairs.", de: "Die Küche ist unten.", why: tx("Upstairs and downstairs: **en** haut, **en** bas.", "Oben und unten: **en** haut, **en** bas.") },
    { id: "u12.d18", lesson: 7, fr: "Mes vêtements sont dans ___.", options: ["l'armoire", "la armoire", "le armoire"], answer: 0, en: "My clothes are in the wardrobe.", de: "Meine Kleider sind im Kleiderschrank.", why: tx("Before a vowel, le and la become **l'**: **l'armoire**. (It's feminine: une armoire.)", "Vor einem Vokal werden le und la zu **l'**: **l'armoire**. (Es ist weiblich: une armoire.)") },
    { id: "u12.d19", lesson: 7, fr: "Ils ___ dans une petite maison avec un jardin.", options: ["habitent", "habite", "habitons"], answer: 0, en: "They live in a small house with a garden.", de: "Sie wohnen in einem kleinen Haus mit Garten.", why: tx("With **ils** the ending is **-ent**, and you don't hear it: ils habit**ent**.", "Mit **ils** endet es auf **-ent**, und man hört es nicht: ils habit**ent**.") },
    { id: "u12.d20", lesson: 7, fr: "Il n'y a pas ___ télé dans ma chambre.", options: ["de", "de la", "des"], answer: 0, en: "There's no TV in my bedroom.", de: "In meinem Zimmer gibt es keinen Fernseher.", why: tx("After **pas** it's just **de**: pas **de** télé.", "Nach **pas** steht nur **de**: pas **de** télé.") },
  ],
  dialogues: [
    {
      id: "u12.dialogue",
      lesson: 5,
      title: tx("Hugo's flat", "Hugos Wohnung"),
      lines: [
        { who: "hugo", fr: "Bienvenue chez moi ! Voilà notre appartement.", en: "Welcome to my place! Here's our flat.", de: "Willkommen bei mir! Das ist unsere Wohnung." },
        { who: "chloe", fr: "Il est grand ! Tu habites ici avec tes parents ?", en: "It's big! Do you live here with your parents?", de: "Sie ist groß! Wohnst du hier mit deinen Eltern?" },
        { who: "hugo", fr: "Oui, avec mes parents. Voilà la cuisine et le salon.", en: "Yes, with my parents. Here are the kitchen and the living room.", de: "Ja, mit meinen Eltern. Hier sind die Küche und das Wohnzimmer." },
        { who: "lea", fr: "Et ta chambre, elle est où ?", en: "And where's your room?", de: "Und wo ist dein Zimmer?" },
        { who: "hugo", fr: "À côté de la salle de bains. Il y a un lit, une chaise et ma guitare.", en: "Next to the bathroom. There's a bed, a chair and my guitar.", de: "Neben dem Badezimmer. Da sind ein Bett, ein Stuhl und meine Gitarre." },
        { who: "chloe", fr: "Il n'y a pas de jardin ?", en: "Isn't there a garden?", de: "Gibt es keinen Garten?" },
        { who: "hugo", fr: "Non, mais il y a une grande fenêtre. Regarde, le parc !", en: "No, but there's a big window. Look, the park!", de: "Nein, aber es gibt ein großes Fenster. Schau, der Park!" },
        { who: "lea", fr: "Super ! Mais… qui dort sur ton lit ?", en: "Great! But… who's sleeping on your bed?", de: "Super! Aber … wer schläft auf deinem Bett?" },
        { who: "blob", fr: "Moi ! Pardon, Hugo. Ici, c'est un peu ma chambre aussi !", en: "Me! Sorry, Hugo. This is a bit my room too!", de: "Ich! Entschuldigung, Hugo. Das ist ein bisschen auch mein Zimmer!" },
      ],
      questions: [
        { q: tx("Who does Hugo live with?", "Mit wem wohnt Hugo?"), options: [tx("With his parents", "Mit seinen Eltern"), tx("With his grandmother", "Mit seiner Großmutter"), tx("With Léa and Chloé", "Mit Léa und Chloé")], answer: 0 },
        { q: tx("Where is Hugo's room?", "Wo ist Hugos Zimmer?"), options: [tx("Next to the bathroom", "Neben dem Badezimmer"), tx("Next to the kitchen", "Neben der Küche"), tx("Upstairs", "Oben")], answer: 0 },
        { q: tx("What isn't there?", "Was gibt es nicht?"), options: [tx("A garden", "Einen Garten"), tx("A window", "Ein Fenster"), tx("A bed", "Ein Bett")], answer: 0 },
      ],
    },
    {
      id: "u12.dialogue2",
      lesson: 7,
      title: tx("Where's the key?", "Wo ist der Schlüssel?"),
      lines: [
        { who: "hugo", fr: "Oh là là ! Où est ma clé ?", en: "Oh dear! Where's my key?", de: "Oje! Wo ist mein Schlüssel?" },
        { who: "blob", fr: "Elle n'est pas dans ton sac ?", en: "Isn't it in your bag?", de: "Ist er nicht in deiner Tasche?" },
        { who: "hugo", fr: "Non. Dans mon sac, il y a un croissant, mais pas de clé !", en: "No. In my bag there's a croissant, but no key!", de: "Nein. In meiner Tasche ist ein Croissant, aber kein Schlüssel!" },
        { who: "madame", fr: "Bonjour, les garçons ! Pourquoi vous êtes devant la porte ?", en: "Hello, boys! Why are you in front of the door?", de: "Hallo, Jungs! Warum steht ihr vor der Tür?" },
        { who: "blob", fr: "Hugo n'a pas de clé, Madame Martin !", en: "Hugo doesn't have a key, Mrs Martin!", de: "Hugo hat keinen Schlüssel, Frau Martin!" },
        { who: "madame", fr: "Pas de problème ! J'ai une clé de chez toi, Hugo. Elle est en haut, chez moi.", en: "No problem! I have a key to your place, Hugo. It's upstairs, at mine.", de: "Kein Problem! Ich habe einen Schlüssel von euch, Hugo. Er ist oben, bei mir." },
        { who: "blob", fr: "Vous habitez au premier étage ?", en: "Do you live on the first floor?", de: "Wohnen Sie im ersten Stock?" },
        { who: "madame", fr: "Oui, au premier, à côté de l'escalier. Voilà la clé !", en: "Yes, on the first, next to the stairs. Here's the key!", de: "Ja, im ersten, neben der Treppe. Hier ist der Schlüssel!" },
        { who: "hugo", fr: "Merci, Madame Martin ! Oh… regardez, ma clé est sur la table, derrière la fenêtre !", en: "Thank you, Mrs Martin! Oh… look, my key is on the table, behind the window!", de: "Danke, Frau Martin! Oh … schauen Sie, mein Schlüssel liegt auf dem Tisch, hinter dem Fenster!" },
      ],
      questions: [
        { q: tx("What is in Hugo's bag?", "Was ist in Hugos Tasche?"), options: [tx("A croissant", "Ein Croissant"), tx("The key", "Der Schlüssel"), tx("A book", "Ein Buch")], answer: 0 },
        { q: tx("Where does Mrs Martin live?", "Wo wohnt Frau Martin?"), options: [tx("On the first floor, next to the stairs", "Im ersten Stock, neben der Treppe"), tx("Downstairs, next to the kitchen", "Unten, neben der Küche"), tx("Next to the station", "Neben dem Bahnhof")], answer: 0 },
        { q: tx("Where is Hugo's key in the end?", "Wo ist Hugos Schlüssel am Ende?"), options: [tx("On the table, behind the window", "Auf dem Tisch, hinter dem Fenster"), tx("Under the bed", "Unter dem Bett"), tx("In his bag", "In seiner Tasche")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Habiter: where you live", "Habiter: wo du wohnst"),
      body: tx(
        "**Habiter** (to live) is a regular -er verb, like parler. The h is silent, so it's **j'habite**, and you link: nous‿habitons, ils‿habitent.\n\nIn a town: **à** Lyon, **à** Paris. In a home: **dans** un appartement, **dans** une maison. And **chez moi** means «at my place», like bei mir in German.",
        "**Habiter** (wohnen) ist ein regelmäßiges -er-Verb wie parler. Das h ist stumm, darum heißt es **j'habite**, und man bindet: nous‿habitons, ils‿habitent.\n\nIn einer Stadt: **à** Lyon, **à** Paris. In einer Wohnung: **dans** un appartement, **dans** une maison. Und **chez moi** heißt „bei mir“ oder „zu Hause“.",
      ),
      examples: [
        { fr: "J'habite à Lyon.", en: "I live in Lyon.", de: "Ich wohne in Lyon." },
        { fr: "Tu habites où ?", en: "Where do you live?", de: "Wo wohnst du?" },
        { fr: "Nous habitons dans un appartement.", en: "We live in a flat.", de: "Wir wohnen in einer Wohnung." },
      ],
      table: {
        head: [tx("person", "Person"), "habiter"],
        rows: [
          [tx("I", "ich"), "j'habite"],
          [tx("you", "du"), "tu habites"],
          [tx("he / she", "er / sie"), "il / elle habite"],
          [tx("we", "wir"), "nous habitons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous habitez"],
          [tx("they", "sie"), "ils / elles habitent"],
        ],
      },
    },
    {
      title: tx("Rooms and furniture: le or la?", "Zimmer und Möbel: le oder la?"),
      body: tx(
        "Learn every room with its article: genders often differ from German. **La** chaise but der Stuhl, **la** table but der Tisch, **le** lit, **la** porte.\n\nWhere things are: **dans** (in), **sur** (on), **sous** (under): le chat est **sur** le lit, le livre est **sous** la chaise.",
        "Lerne jedes Zimmer mit Artikel: Das Geschlecht ist oft anders als im Deutschen. **La** chaise, aber der Stuhl, **la** table, aber der Tisch, **le** lit, **la** porte.\n\nWo etwas ist: **dans** (in), **sur** (auf), **sous** (unter): le chat est **sur** le lit, le livre est **sous** la chaise.",
      ),
      examples: [
        { fr: "Maman est dans la cuisine.", en: "Mum is in the kitchen.", de: "Mama ist in der Küche." },
        { fr: "Le chat est sur le lit.", en: "The cat is on the bed.", de: "Die Katze ist auf dem Bett." },
        { fr: "Le livre est sous la chaise.", en: "The book is under the chair.", de: "Das Buch ist unter dem Stuhl." },
      ],
      table: {
        head: [tx("masculine: le", "männlich: le"), tx("feminine: la", "weiblich: la")],
        rows: [
          ["le salon", "la cuisine"],
          ["le jardin", "la chambre"],
          ["le lit", "la table"],
          ["le canapé", "la chaise"],
        ],
      },
    },
    {
      title: tx("In front, behind, next to, between", "Vor, hinter, neben, zwischen"),
      body: tx(
        "**Devant** (in front of) and **derrière** (behind) go straight before the noun: derrière la maison. **À côté de** (next to) has a de, and de + le melts into **du**: à côté **du** lit. **Entre** … **et** … means between.\n\nThere's no…: **il n'y a pas de**. After pas, un, une and des become **de**: il y a un jardin → il n'y a pas **de** jardin.",
        "**Devant** (vor) und **derrière** (hinter) stehen direkt vor dem Nomen: derrière la maison. **À côté de** (neben) hat ein de, und de + le wird zu **du**: à côté **du** lit. **Entre** … **et** … heißt zwischen.\n\nEs gibt kein …: **il n'y a pas de**. Nach pas werden un, une und des zu **de**: il y a un jardin → il n'y a pas **de** jardin.",
      ),
      examples: [
        { fr: "Le jardin est derrière la maison.", en: "The garden is behind the house.", de: "Der Garten ist hinter dem Haus." },
        { fr: "La chaise est à côté du lit.", en: "The chair is next to the bed.", de: "Der Stuhl ist neben dem Bett." },
        { fr: "Il n'y a pas de jardin.", en: "There's no garden.", de: "Es gibt keinen Garten." },
      ],
      table: {
        head: [tx("next to…", "neben …"), tx("example", "Beispiel")],
        rows: [
          ["à côté du (le)", "à côté du lit"],
          ["à côté de la", "à côté de la gare"],
          ["à côté de l'", "à côté de l'école"],
          ["à côté des (les)", "à côté des toilettes"],
        ],
      },
    },
    {
      title: tx("Upstairs, downstairs", "Oben, unten"),
      body: tx(
        "**En haut** is upstairs, **en bas** downstairs. Floors: **au premier étage** (on the first floor), **au troisième étage**. The ground floor is le rez-de-chaussée.\n\nBefore a vowel, de shrinks to **d'**: il n'y a pas **d'ascenseur**. And le or la shrink to **l'**: l'escalier (masculine), l'armoire (feminine).",
        "**En haut** heißt oben, **en bas** unten. Stockwerke: **au premier étage** (im ersten Stock), **au troisième étage**. Das Erdgeschoss ist le rez-de-chaussée.\n\nVor einem Vokal wird de zu **d'**: il n'y a pas **d'ascenseur**. Und le oder la werden zu **l'**: l'escalier (männlich), l'armoire (weiblich).",
      ),
      examples: [
        { fr: "Ma chambre est en haut.", en: "My bedroom is upstairs.", de: "Mein Zimmer ist oben." },
        { fr: "J'habite au troisième étage.", en: "I live on the third floor.", de: "Ich wohne im dritten Stock." },
        { fr: "Il n'y a pas d'ascenseur.", en: "There's no lift.", de: "Es gibt keinen Aufzug." },
      ],
    },
  ],
};
