import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 13: the near future: aller + infinitive (je vais manger). */
export const u13: Unit = {
  slug: "projets",
  n: 13,
  cefr: "A2",
  title: tx("Plans", "Pläne"),
  goal: tx("Talk about what you're going to do", "Erzählen, was du vorhast"),
  emoji: "🗓️",
  words: [
    { id: "demain", fr: "demain", en: "tomorrow", de: "morgen", kind: "adv", note: tx("Demain matin: tomorrow morning. Demain soir: tomorrow evening.", "Demain matin: morgen früh. Demain soir: morgen Abend.") },
    { id: "ce-soir", fr: "ce soir", en: "this evening", de: "heute Abend", alt: { en: ["tonight"] }, kind: "phrase", note: tx("Ce = this, soir = evening.", "Ce = dieser, soir = Abend.") },
    { id: "manger", fr: "manger", en: "to eat", de: "essen", kind: "verb", note: tx("You know je mange. The infinitive ends in -er: manger. Je vais manger: I'm going to eat.", "Du kennst je mange. Der Infinitiv endet auf -er: manger. Je vais manger: Ich werde essen.") },
    { id: "faire", fr: "faire", en: "to do", de: "machen", alt: { en: ["to make"], de: ["tun"] }, kind: "verb", note: tx("Je fais, tu fais… and the infinitive: faire. Je vais faire du sport.", "Je fais, tu fais … und der Infinitiv: faire. Je vais faire du sport.") },
    { id: "voir", fr: "voir", en: "to see", de: "sehen", kind: "verb", note: tx("Voir is to see. Regarder is to look at, to watch.", "Voir heißt sehen. Regarder heißt anschauen.") },
    { id: "semaine-prochaine", fr: "la semaine prochaine", en: "next week", de: "nächste Woche", kind: "phrase", note: tx("Prochaine comes after the noun: la semaine prochaine.", "Prochaine steht nach dem Nomen: la semaine prochaine.") },
    { id: "visiter", fr: "visiter", en: "to visit", de: "besichtigen", alt: { de: ["besuchen"] }, kind: "verb", note: tx("Only for places: visiter Paris, visiter un musée. For people it's voir: voir sa grand-mère.", "Nur für Orte: visiter Paris, visiter un musée. Für Leute sagt man voir: voir sa grand-mère.") },
    { id: "acheter", fr: "acheter", en: "to buy", de: "kaufen", kind: "verb", emoji: "💳", note: tx("When you hear è, it's written è: j'achète. In the infinitive: acheter.", "Wenn man è hört, schreibt man è: j'achète. Im Infinitiv: acheter.") },
    { id: "aller", fr: "aller", en: "to go", de: "gehen", alt: { de: ["fahren"] }, kind: "verb", note: tx("Yes, aller twice: je vais aller au cinéma, I'm going to go to the cinema.", "Ja, zweimal aller: je vais aller au cinéma, ich werde ins Kino gehen.") },
    { id: "jouer", fr: "jouer", en: "to play", de: "spielen", kind: "verb" },
    { id: "bientot", fr: "bientôt", en: "soon", de: "bald", kind: "adv", note: tx("You know it from à bientôt, see you soon!", "Du kennst es von à bientôt, bis bald!") },
    { id: "plus-tard", fr: "plus tard", en: "later", de: "später", kind: "phrase", note: tx("Plus + tard: «more late».", "Plus + tard: „mehr spät“.") },
    { id: "dormir", fr: "dormir", en: "to sleep", de: "schlafen", kind: "verb", emoji: "💤", note: tx("Il dort: he's sleeping. The infinitive: dormir.", "Il dort: Er schläft. Der Infinitiv: dormir.") },
    { id: "partir", fr: "partir", en: "to leave", de: "weggehen", alt: { en: ["to go away", "to set off"], de: ["losgehen", "abfahren", "losfahren"] }, kind: "verb", note: tx("To leave, to set off: le bus va partir.", "Weggehen, losfahren: le bus va partir, der Bus fährt gleich ab.") },
    { id: "regarder", fr: "regarder", en: "to watch", de: "anschauen", alt: { en: ["to look at"], de: ["ansehen", "schauen"] }, kind: "verb" },
    { id: "inviter", fr: "inviter", en: "to invite", de: "einladen", kind: "verb", emoji: "💌" },
    { id: "preparer", fr: "préparer", en: "to prepare", de: "vorbereiten", alt: { en: ["to make", "to get ready"], de: ["zubereiten", "machen"] }, kind: "verb", note: tx("Préparer le dîner: to make dinner.", "Préparer le dîner: das Abendessen machen.") },
    { id: "rester", fr: "rester", en: "to stay", de: "bleiben", kind: "verb", note: tx("A false friend: rester is to stay, not to rest!", "Ein falscher Freund: rester heißt bleiben, nicht rasten!") },
    { id: "pique-nique", fr: "le pique-nique", en: "the picnic", de: "das Picknick", g: "m", kind: "noun", note: tx("Faire un pique-nique: to have a picnic.", "Faire un pique-nique: ein Picknick machen.") },
    { id: "ranger", fr: "ranger", en: "to tidy", de: "aufräumen", alt: { en: ["to tidy up"] }, kind: "verb", emoji: "🧹", note: tx("Ranger ta chambre: every parent's favourite sentence.", "Ranger ta chambre: der Lieblingssatz aller Eltern.") },
    { id: "travailler", fr: "travailler", en: "to work", de: "arbeiten", kind: "verb" },
    { id: "projet", fr: "le projet", en: "the plan", de: "der Plan", alt: { en: ["the project"], de: ["das Projekt", "das Vorhaben"] }, g: "m", kind: "noun", note: tx("Tu as des projets ? Do you have plans?", "Tu as des projets ? Hast du Pläne?") },
    { id: "ce-week-end", fr: "ce week-end", en: "this weekend", de: "dieses Wochenende", alt: { de: ["am Wochenende"] }, kind: "phrase" },
    { id: "apres-demain", fr: "après-demain", en: "the day after tomorrow", de: "übermorgen", kind: "adv", note: tx("Après + demain: after tomorrow.", "Après + demain: nach morgen.") },
    { id: "lire", fr: "lire", en: "to read", de: "lesen", kind: "verb", note: tx("An infinitive in -re, like faire.", "Ein Infinitiv auf -re, wie faire.") },
    { id: "annee-prochaine", fr: "l'année prochaine", en: "next year", de: "nächstes Jahr", kind: "phrase", note: tx("L'année is feminine: l'année prochaine.", "L'année ist weiblich: l'année prochaine.") },
    { id: "voyager", fr: "voyager", en: "to travel", de: "reisen", kind: "verb", note: tx("Un voyage is a trip. Bon voyage!", "Un voyage ist eine Reise. Bon voyage!") },
    { id: "apprendre", fr: "apprendre", en: "to learn", de: "lernen", kind: "verb", note: tx("Apprendre à + infinitive: apprendre à nager, to learn to swim.", "Apprendre à + Infinitiv: apprendre à nager, schwimmen lernen.") },
  ],
  gloss: [
    { fr: "vais", en: "go (I)", de: "gehe" },
    { fr: "vas", en: "go (you)", de: "gehst" },
    { fr: "prof", en: "teacher", de: "Lehrer" },
    { fr: "semaine", en: "week", de: "Woche" },
    { fr: "projets", en: "plans", de: "Pläne" },
    { fr: "pleuvoir", en: "to rain", de: "regnen" },
    { fr: "il va pleuvoir", en: "it's going to rain", de: "es wird regnen" },
    { fr: "habiter", en: "to live", de: "wohnen" },
    { fr: "être", en: "to be", de: "sein" },
    { fr: "me lever", en: "get up (myself)", de: "aufstehen" },
    { fr: "te lever", en: "get up (yourself)", de: "aufstehen" },
    { fr: "se lever", en: "get up (himself / herself)", de: "aufstehen" },
    { fr: "me coucher", en: "go to bed (myself)", de: "ins Bett gehen" },
    { fr: "te coucher", en: "go to bed (yourself)", de: "ins Bett gehen" },
    { fr: "se coucher", en: "go to bed (himself / herself)", de: "ins Bett gehen" },
    { fr: "toute", en: "all / the whole", de: "ganze" },
    { fr: "sandwichs", en: "sandwiches", de: "Sandwiches" },
    { fr: "boissons", en: "drinks", de: "Getränke" },
    { fr: "si", en: "yes (to a «no» question)", de: "doch" },
    { fr: "je reste", en: "I'm staying", de: "ich bleibe" },
    { fr: "ou pas", en: "or not", de: "oder nicht" },
  ],
  lessons: [
    { title: tx("Tomorrow", "Morgen"), words: ["demain", "ce-soir", "manger", "faire", "voir"] },
    { title: tx("Next week", "Nächste Woche"), words: ["semaine-prochaine", "visiter", "acheter", "aller", "jouer"] },
    { title: tx("Soon, later", "Bald, später"), words: ["bientot", "plus-tard", "dormir", "partir", "regarder"] },
    { title: tx("A picnic", "Ein Picknick"), words: ["inviter", "preparer", "rester", "pique-nique"] },
    { title: tx("Not going to", "Nicht vorhaben"), words: ["ranger", "travailler", "projet"] },
    { title: tx("This weekend", "Dieses Wochenende"), words: ["ce-week-end", "apres-demain", "lire"] },
    { title: tx("Next year", "Nächstes Jahr"), words: ["annee-prochaine", "voyager", "apprendre"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u13.01", lesson: 1, fr: "Demain, je vais manger une pizza.", en: "Tomorrow, I'm going to eat a pizza.", de: "Morgen esse ich eine Pizza.", alt: { fr: ["Je vais manger une pizza demain."], en: ["Tomorrow, I will eat a pizza.", "I'm going to eat a pizza tomorrow.", "I will eat a pizza tomorrow.", "Tomorrow, I'm eating a pizza.", "I'm eating a pizza tomorrow.", "Tomorrow, I'm going to have a pizza.", "I'm going to have a pizza tomorrow."], de: ["Morgen werde ich eine Pizza essen.", "Ich werde morgen eine Pizza essen.", "Ich esse morgen eine Pizza."] } },
    { id: "u13.02", lesson: 1, fr: "Ce soir, je vais voir Léa.", en: "This evening, I'm going to see Léa.", de: "Heute Abend sehe ich Léa.", alt: { fr: ["Je vais voir Léa ce soir."], en: ["Tonight, I'm going to see Léa.", "This evening, I will see Léa.", "Tonight, I will see Léa.", "I'm going to see Léa this evening.", "I'm going to see Léa tonight.", "I will see Léa this evening.", "I will see Léa tonight.", "I'm seeing Léa this evening.", "I'm seeing Léa tonight.", "Tonight, I'm seeing Léa.", "This evening, I'm seeing Léa."], de: ["Heute Abend werde ich Léa sehen.", "Ich sehe Léa heute Abend.", "Ich werde Léa heute Abend sehen.", "Heute Abend treffe ich Léa.", "Ich treffe Léa heute Abend."] } },
    { id: "u13.03", lesson: 1, fr: "Qu'est-ce que tu vas faire demain ?", en: "What are you going to do tomorrow?", de: "Was machst du morgen?", alt: { fr: ["Tu vas faire quoi demain ?", "Demain, tu vas faire quoi ?", "Que vas-tu faire demain ?", "Qu'est-ce que vous allez faire demain ?", "Vous allez faire quoi demain ?", "Qu'allez-vous faire demain ?"], en: ["What will you do tomorrow?", "What are you doing tomorrow?"], de: ["Was wirst du morgen machen?", "Was wirst du morgen tun?", "Was machst du denn morgen?"] } },
    { id: "u13.04", lesson: 1, fr: "Je vais faire du sport ce soir.", en: "I'm going to do sport this evening.", de: "Heute Abend mache ich Sport.", alt: { fr: ["Ce soir, je vais faire du sport."], en: ["I'm going to do sport tonight.", "I will do sport this evening.", "I will do sport tonight.", "This evening, I'm going to do sport.", "Tonight, I'm going to do sport.", "I'm doing sport tonight.", "I'm doing sport this evening.", "I'm going to do sports tonight.", "I'm going to do sports this evening."], de: ["Ich mache heute Abend Sport.", "Heute Abend werde ich Sport machen.", "Ich werde heute Abend Sport machen."] } },
    { id: "u13.05", lesson: 1, fr: "Tu vas manger avec nous ?", en: "Are you going to eat with us?", de: "Wirst du mit uns essen?", alt: { fr: ["Est-ce que tu vas manger avec nous ?", "Vas-tu manger avec nous ?", "Vous allez manger avec nous ?", "Est-ce que vous allez manger avec nous ?", "Allez-vous manger avec nous ?"], en: ["Will you eat with us?", "Are you eating with us?"], de: ["Isst du mit uns?"] } },
    { id: "u13.06", lesson: 1, fr: "Il va voir sa grand-mère demain.", en: "He's going to see his grandmother tomorrow.", de: "Er sieht morgen seine Großmutter.", alt: { fr: ["Demain, il va voir sa grand-mère."], en: ["He will see his grandmother tomorrow.", "Tomorrow, he's going to see his grandmother.", "He's seeing his grandmother tomorrow.", "He's going to visit his grandmother tomorrow.", "He's going to see his grandma tomorrow."], de: ["Er wird morgen seine Großmutter sehen.", "Morgen sieht er seine Großmutter.", "Er besucht morgen seine Großmutter.", "Morgen besucht er seine Großmutter.", "Er wird morgen seine Großmutter besuchen.", "Er besucht morgen seine Oma."] } },
    { id: "u13.07", lesson: 1, fr: "Ce soir, nous allons manger des crêpes !", en: "This evening, we're going to eat crêpes!", de: "Heute Abend essen wir Crêpes!", alt: { fr: ["Nous allons manger des crêpes ce soir !", "Ce soir, on va manger des crêpes !", "On va manger des crêpes ce soir !"], en: ["Tonight, we're going to eat crêpes!", "This evening, we will eat crêpes!", "Tonight, we will eat crêpes!", "We're going to eat crêpes tonight!", "We're going to eat crêpes this evening!", "We're eating crêpes tonight!", "We're having crêpes tonight!", "Tonight, we're having crêpes!", "We're going to have crêpes tonight!"], de: ["Heute Abend werden wir Crêpes essen!", "Wir essen heute Abend Crêpes!", "Wir werden heute Abend Crêpes essen!"] } },
    // Lesson 2
    { id: "u13.08", lesson: 2, fr: "La semaine prochaine, je vais visiter Paris.", en: "Next week, I'm going to visit Paris.", de: "Nächste Woche besuche ich Paris.", alt: { fr: ["Je vais visiter Paris la semaine prochaine."], en: ["Next week, I will visit Paris.", "I'm going to visit Paris next week.", "I will visit Paris next week.", "I'm visiting Paris next week.", "Next week, I'm visiting Paris."], de: ["Nächste Woche werde ich Paris besuchen.", "Ich besuche nächste Woche Paris.", "Ich werde nächste Woche Paris besuchen.", "Nächste Woche besichtige ich Paris.", "Ich werde nächste Woche Paris besichtigen."] } },
    { id: "u13.09", lesson: 2, fr: "Je vais acheter un cadeau pour Hugo.", en: "I'm going to buy a present for Hugo.", de: "Ich werde ein Geschenk für Hugo kaufen.", alt: { en: ["I will buy a present for Hugo.", "I'm going to buy Hugo a present.", "I will buy Hugo a present.", "I'm going to buy a gift for Hugo.", "I'm going to buy Hugo a gift."], de: ["Ich kaufe ein Geschenk für Hugo.", "Ich werde für Hugo ein Geschenk kaufen."] } },
    { id: "u13.10", lesson: 2, fr: "Nous allons aller à la plage.", en: "We're going to go to the beach.", de: "Wir werden an den Strand gehen.", alt: { fr: ["On va aller à la plage.", "Nous allons à la plage."], en: ["We will go to the beach.", "We're going to the beach."], de: ["Wir gehen an den Strand.", "Wir werden zum Strand gehen.", "Wir fahren an den Strand.", "Wir werden an den Strand fahren."] } },
    { id: "u13.11", lesson: 2, fr: "Tu vas jouer au foot samedi ?", en: "Are you going to play football on Saturday?", de: "Spielst du am Samstag Fußball?", alt: { fr: ["Est-ce que tu vas jouer au foot samedi ?", "Samedi, tu vas jouer au foot ?", "Vas-tu jouer au foot samedi ?", "Vous allez jouer au foot samedi ?", "Est-ce que vous allez jouer au foot samedi ?", "Allez-vous jouer au foot samedi ?"], en: ["Will you play football on Saturday?", "Are you playing football on Saturday?"], de: ["Wirst du am Samstag Fußball spielen?", "Spielst du Samstag Fußball?"] } },
    { id: "u13.12", lesson: 2, fr: "Elle va acheter une robe rouge.", en: "She's going to buy a red dress.", de: "Sie wird ein rotes Kleid kaufen.", alt: { en: ["She will buy a red dress."], de: ["Sie kauft ein rotes Kleid."] } },
    { id: "u13.13", lesson: 2, fr: "La semaine prochaine, ils vont visiter le musée.", en: "Next week, they're going to visit the museum.", de: "Nächste Woche besuchen sie das Museum.", alt: { fr: ["Ils vont visiter le musée la semaine prochaine.", "La semaine prochaine, elles vont visiter le musée.", "Elles vont visiter le musée la semaine prochaine."], en: ["Next week, they will visit the museum.", "They're going to visit the museum next week.", "They will visit the museum next week.", "They're visiting the museum next week."], de: ["Nächste Woche werden sie das Museum besuchen.", "Sie besuchen nächste Woche das Museum.", "Sie werden nächste Woche das Museum besuchen."] } },
    { id: "u13.14", lesson: 2, fr: "Je vais aller au cinéma avec Chloé.", en: "I'm going to go to the cinema with Chloé.", de: "Ich werde mit Chloé ins Kino gehen.", alt: { fr: ["Je vais au cinéma avec Chloé."], en: ["I will go to the cinema with Chloé.", "I'm going to the cinema with Chloé."], de: ["Ich gehe mit Chloé ins Kino."] } },
    // Lesson 3
    { id: "u13.15", lesson: 3, fr: "Je vais partir bientôt.", en: "I'm going to leave soon.", de: "Ich werde bald gehen.", alt: { fr: ["Je vais bientôt partir."], en: ["I will leave soon.", "I'm leaving soon."], de: ["Ich gehe bald.", "Ich fahre bald los.", "Ich werde bald losfahren.", "Ich gehe bald los.", "Bald gehe ich."] } },
    { id: "u13.16", lesson: 3, fr: "Tu vas dormir chez moi ?", en: "Are you going to sleep at my place?", de: "Schläfst du bei mir?", alt: { fr: ["Est-ce que tu vas dormir chez moi ?", "Vas-tu dormir chez moi ?", "Vous allez dormir chez moi ?", "Est-ce que vous allez dormir chez moi ?"], en: ["Will you sleep at my place?", "Are you sleeping at my place?", "Are you going to sleep at my house?", "Are you sleeping over at my place?"], de: ["Wirst du bei mir schlafen?", "Übernachtest du bei mir?"] } },
    { id: "u13.17", lesson: 3, fr: "Plus tard, je vais regarder la télé.", en: "Later, I'm going to watch TV.", de: "Später sehe ich fern.", alt: { fr: ["Je vais regarder la télé plus tard."], en: ["Later, I will watch TV.", "I'm going to watch TV later.", "I will watch TV later.", "Later, I'm going to watch television.", "I'm watching TV later."], de: ["Später werde ich fernsehen.", "Ich sehe später fern.", "Ich werde später fernsehen.", "Später schaue ich fern.", "Ich schaue später fern."] } },
    { id: "u13.18", lesson: 3, fr: "Le bus va partir !", en: "The bus is going to leave!", de: "Der Bus fährt gleich ab!", alt: { en: ["The bus will leave!", "The bus is about to leave!", "The bus is leaving!"], de: ["Der Bus wird abfahren!", "Der Bus fährt ab!", "Der Bus fährt gleich los!"] } },
    { id: "u13.19", lesson: 3, fr: "Blob va dormir sur le canapé.", en: "Blob is going to sleep on the sofa.", de: "Blob wird auf dem Sofa schlafen.", alt: { en: ["Blob will sleep on the sofa.", "Blob is going to sleep on the couch.", "Blob will sleep on the couch."], de: ["Blob wird auf der Couch schlafen."] } },
    { id: "u13.20", lesson: 3, fr: "Nous allons partir à huit heures.", en: "We're going to leave at eight o'clock.", de: "Wir fahren um acht Uhr los.", alt: { fr: ["On va partir à huit heures.", "À huit heures, nous allons partir."], en: ["We will leave at eight o'clock.", "We're going to leave at eight.", "We will leave at eight.", "We're leaving at eight o'clock.", "We're leaving at eight.", "We're going to leave at 8.", "We're going to leave at 8 o'clock.", "We will leave at 8."], de: ["Wir werden um acht Uhr losfahren.", "Wir fahren um acht los.", "Wir fahren um 8 Uhr los.", "Wir gehen um acht Uhr los.", "Wir werden um acht Uhr gehen.", "Wir gehen um acht Uhr."] } },
    { id: "u13.21", lesson: 3, fr: "Bonne nuit ! Je vais dormir.", en: "Good night! I'm going to sleep.", de: "Gute Nacht! Ich gehe schlafen.", alt: { en: ["Good night! I will sleep.", "Good night! I'm going to go to sleep."], de: ["Gute Nacht! Ich werde schlafen.", "Gute Nacht! Ich geh schlafen."] } },
    // Lesson 4
    { id: "u13.22", lesson: 4, fr: "Nous allons inviter nos amis.", en: "We're going to invite our friends.", de: "Wir werden unsere Freunde einladen.", alt: { fr: ["On va inviter nos amis."], en: ["We will invite our friends."], de: ["Wir laden unsere Freunde ein."] } },
    { id: "u13.23", lesson: 4, fr: "Vous allez préparer un pique-nique ?", en: "Are you going to make a picnic?", de: "Bereitet ihr ein Picknick vor?", alt: { fr: ["Est-ce que vous allez préparer un pique-nique ?", "Allez-vous préparer un pique-nique ?", "Tu vas préparer un pique-nique ?", "Est-ce que tu vas préparer un pique-nique ?"], en: ["Are you going to prepare a picnic?", "Will you make a picnic?", "Will you prepare a picnic?"], de: ["Werdet ihr ein Picknick vorbereiten?", "Macht ihr ein Picknick?", "Werdet ihr ein Picknick machen?", "Werden Sie ein Picknick vorbereiten?", "Bereiten Sie ein Picknick vor?", "Machen Sie ein Picknick?"] } },
    { id: "u13.24", lesson: 4, fr: "Je vais rester à la maison ce soir.", en: "I'm going to stay at home this evening.", de: "Heute Abend bleibe ich zu Hause.", alt: { fr: ["Ce soir, je vais rester à la maison.", "Je vais rester chez moi ce soir.", "Ce soir, je vais rester chez moi."], en: ["I'm going to stay at home tonight.", "I'm going to stay home tonight.", "I'm going to stay home this evening.", "I will stay at home tonight.", "I will stay at home this evening.", "I will stay home tonight.", "I'm staying at home tonight.", "I'm staying home tonight.", "I'm staying at home this evening.", "Tonight, I'm going to stay at home.", "This evening, I'm going to stay at home."], de: ["Ich bleibe heute Abend zu Hause.", "Heute Abend werde ich zu Hause bleiben.", "Ich werde heute Abend zu Hause bleiben."] } },
    { id: "u13.25", lesson: 4, fr: "Ils vont préparer le dîner.", en: "They're going to make dinner.", de: "Sie werden das Abendessen machen.", alt: { fr: ["Elles vont préparer le dîner."], en: ["They're going to prepare dinner.", "They will make dinner.", "They will prepare dinner.", "They're going to cook dinner."], de: ["Sie werden das Abendessen vorbereiten.", "Sie machen das Abendessen.", "Sie werden das Abendessen kochen."] } },
    { id: "u13.26", lesson: 4, fr: "Demain, on va faire un pique-nique au parc.", en: "Tomorrow, we're going to have a picnic in the park.", de: "Morgen machen wir ein Picknick im Park.", alt: { fr: ["Demain, nous allons faire un pique-nique au parc.", "On va faire un pique-nique au parc demain.", "Nous allons faire un pique-nique au parc demain."], en: ["Tomorrow, we will have a picnic in the park.", "We're going to have a picnic in the park tomorrow.", "We will have a picnic in the park tomorrow.", "We're having a picnic in the park tomorrow.", "Tomorrow, we're having a picnic in the park.", "Tomorrow, we're going to have a picnic at the park."], de: ["Morgen werden wir ein Picknick im Park machen.", "Wir machen morgen ein Picknick im Park.", "Wir werden morgen ein Picknick im Park machen."] } },
    { id: "u13.27", lesson: 4, fr: "Tu vas inviter Chloé ?", en: "Are you going to invite Chloé?", de: "Lädst du Chloé ein?", alt: { fr: ["Est-ce que tu vas inviter Chloé ?", "Vas-tu inviter Chloé ?", "Vous allez inviter Chloé ?", "Est-ce que vous allez inviter Chloé ?", "Allez-vous inviter Chloé ?"], en: ["Will you invite Chloé?", "Are you inviting Chloé?"], de: ["Wirst du Chloé einladen?"] } },
    { id: "u13.28", lesson: 4, fr: "Chloé va rester une semaine.", en: "Chloé is going to stay for a week.", de: "Chloé wird eine Woche bleiben.", alt: { en: ["Chloé is going to stay a week.", "Chloé will stay for a week.", "Chloé will stay a week.", "Chloé is staying for a week."], de: ["Chloé bleibt eine Woche."] } },
    // Lesson 5
    { id: "u13.29", lesson: 5, fr: "Je ne vais pas ranger ma chambre.", en: "I'm not going to tidy my bedroom.", de: "Ich werde mein Zimmer nicht aufräumen.", alt: { en: ["I won't tidy my bedroom.", "I'm not going to tidy my room.", "I won't tidy my room.", "I'm not going to tidy up my room.", "I'm not going to tidy up my bedroom.", "I won't tidy up my room."], de: ["Ich räume mein Zimmer nicht auf."] } },
    { id: "u13.30", lesson: 5, fr: "Ce soir, je ne vais pas travailler.", en: "This evening, I'm not going to work.", de: "Heute Abend arbeite ich nicht.", alt: { fr: ["Je ne vais pas travailler ce soir."], en: ["Tonight, I'm not going to work.", "I'm not going to work tonight.", "I'm not going to work this evening.", "I won't work tonight.", "I won't work this evening.", "Tonight, I won't work.", "I'm not working tonight.", "I'm not working this evening."], de: ["Ich arbeite heute Abend nicht.", "Heute Abend werde ich nicht arbeiten.", "Ich werde heute Abend nicht arbeiten."] } },
    { id: "u13.31", lesson: 5, fr: "Tu as des projets pour le week-end ?", en: "Do you have plans for the weekend?", de: "Hast du Pläne fürs Wochenende?", alt: { fr: ["Est-ce que tu as des projets pour le week-end ?", "As-tu des projets pour le week-end ?", "Vous avez des projets pour le week-end ?", "Est-ce que vous avez des projets pour le week-end ?", "Avez-vous des projets pour le week-end ?"], en: ["Have you got plans for the weekend?", "Do you have any plans for the weekend?", "Have you got any plans for the weekend?"], de: ["Hast du Pläne für das Wochenende?", "Hast du schon Pläne fürs Wochenende?"] } },
    { id: "u13.32", lesson: 5, fr: "Il ne va pas partir demain.", en: "He isn't going to leave tomorrow.", de: "Er fährt morgen nicht weg.", alt: { fr: ["Demain, il ne va pas partir."], en: ["He won't leave tomorrow.", "He isn't leaving tomorrow."], de: ["Er wird morgen nicht wegfahren.", "Er reist morgen nicht ab.", "Er wird morgen nicht abreisen.", "Er geht morgen nicht weg.", "Er wird morgen nicht weggehen.", "Morgen fährt er nicht weg."] } },
    { id: "u13.33", lesson: 5, fr: "Nous n'allons pas rester ici.", en: "We're not going to stay here.", de: "Wir werden nicht hier bleiben.", alt: { fr: ["On ne va pas rester ici."], en: ["We won't stay here.", "We aren't staying here."], de: ["Wir bleiben nicht hier.", "Wir werden hier nicht bleiben."] } },
    { id: "u13.34", lesson: 5, fr: "Mon projet ? Je vais travailler à Paris.", en: "My plan? I'm going to work in Paris.", de: "Mein Plan? Ich werde in Paris arbeiten.", alt: { en: ["My plan? I will work in Paris.", "My project? I'm going to work in Paris."], de: ["Mein Projekt? Ich werde in Paris arbeiten.", "Mein Vorhaben? Ich werde in Paris arbeiten."] } },
    { id: "u13.35", lesson: 5, fr: "Vous n'allez pas jouer aux jeux vidéo ce soir !", en: "You're not going to play video games tonight!", de: "Ihr spielt heute Abend keine Videospiele!", alt: { fr: ["Ce soir, vous n'allez pas jouer aux jeux vidéo !", "Tu ne vas pas jouer aux jeux vidéo ce soir !", "Ce soir, tu ne vas pas jouer aux jeux vidéo !"], en: ["You won't play video games tonight!", "You're not going to play video games this evening!", "You aren't playing video games tonight!"], de: ["Ihr werdet heute Abend keine Videospiele spielen!", "Heute Abend spielt ihr keine Videospiele!", "Sie werden heute Abend keine Videospiele spielen!"] } },
    // Lesson 6
    { id: "u13.36", lesson: 6, fr: "Ce week-end, je vais lire un livre.", en: "This weekend, I'm going to read a book.", de: "Dieses Wochenende lese ich ein Buch.", alt: { fr: ["Je vais lire un livre ce week-end."], en: ["This weekend, I will read a book.", "I'm going to read a book this weekend.", "I will read a book this weekend.", "I'm reading a book this weekend."], de: ["Am Wochenende lese ich ein Buch.", "Dieses Wochenende werde ich ein Buch lesen.", "Ich werde dieses Wochenende ein Buch lesen.", "Ich lese dieses Wochenende ein Buch.", "Am Wochenende werde ich ein Buch lesen."] } },
    { id: "u13.37", lesson: 6, fr: "Après-demain, c'est l'anniversaire de Léa.", en: "The day after tomorrow, it's Léa's birthday.", de: "Übermorgen hat Léa Geburtstag.", alt: { fr: ["C'est l'anniversaire de Léa après-demain."], en: ["The day after tomorrow is Léa's birthday.", "It's Léa's birthday the day after tomorrow."], de: ["Übermorgen ist Léas Geburtstag.", "Léa hat übermorgen Geburtstag."] } },
    { id: "u13.38", lesson: 6, fr: "Qu'est-ce que vous allez faire ce week-end ?", en: "What are you going to do this weekend?", de: "Was macht ihr dieses Wochenende?", alt: { fr: ["Vous allez faire quoi ce week-end ?", "Qu'allez-vous faire ce week-end ?", "Qu'est-ce que tu vas faire ce week-end ?", "Tu vas faire quoi ce week-end ?", "Que vas-tu faire ce week-end ?"], en: ["What will you do this weekend?", "What are you doing this weekend?"], de: ["Was macht ihr am Wochenende?", "Was werdet ihr dieses Wochenende machen?", "Was machen Sie dieses Wochenende?", "Was werden Sie dieses Wochenende machen?"] } },
    { id: "u13.39", lesson: 6, fr: "Ils vont voir leurs grands-parents après-demain.", en: "They're going to see their grandparents the day after tomorrow.", de: "Übermorgen besuchen sie ihre Großeltern.", alt: { fr: ["Après-demain, ils vont voir leurs grands-parents.", "Elles vont voir leurs grands-parents après-demain."], en: ["They will see their grandparents the day after tomorrow.", "They're seeing their grandparents the day after tomorrow.", "They're going to visit their grandparents the day after tomorrow."], de: ["Sie besuchen übermorgen ihre Großeltern.", "Übermorgen werden sie ihre Großeltern besuchen.", "Sie werden übermorgen ihre Großeltern besuchen.", "Übermorgen sehen sie ihre Großeltern.", "Sie sehen übermorgen ihre Großeltern."] } },
    { id: "u13.40", lesson: 6, fr: "Tu vas lire ou dormir ?", en: "Are you going to read or sleep?", de: "Wirst du lesen oder schlafen?", alt: { fr: ["Est-ce que tu vas lire ou dormir ?", "Vous allez lire ou dormir ?", "Est-ce que vous allez lire ou dormir ?"], en: ["Will you read or sleep?"], de: ["Liest du oder schläfst du?"] } },
    { id: "u13.41", lesson: 6, fr: "Ce week-end, il va pleuvoir.", en: "This weekend, it's going to rain.", de: "Dieses Wochenende wird es regnen.", alt: { fr: ["Il va pleuvoir ce week-end."], en: ["This weekend, it will rain.", "It's going to rain this weekend.", "It will rain this weekend."], de: ["Am Wochenende wird es regnen.", "Es wird dieses Wochenende regnen.", "Es wird am Wochenende regnen.", "Dieses Wochenende regnet es.", "Am Wochenende regnet es."] } },
    { id: "u13.42", lesson: 6, fr: "Après-demain, je vais me lever tôt.", en: "The day after tomorrow, I'm going to get up early.", de: "Übermorgen stehe ich früh auf.", alt: { fr: ["Je vais me lever tôt après-demain."], en: ["The day after tomorrow, I will get up early.", "I'm going to get up early the day after tomorrow.", "I will get up early the day after tomorrow."], de: ["Ich stehe übermorgen früh auf.", "Übermorgen werde ich früh aufstehen.", "Ich werde übermorgen früh aufstehen."] } },
    { id: "u13.43", lesson: 6, fr: "Tu vas te coucher tard ce week-end ?", en: "Are you going to go to bed late this weekend?", de: "Gehst du dieses Wochenende spät ins Bett?", alt: { fr: ["Est-ce que tu vas te coucher tard ce week-end ?", "Ce week-end, tu vas te coucher tard ?", "Vous allez vous coucher tard ce week-end ?", "Est-ce que vous allez vous coucher tard ce week-end ?"], en: ["Will you go to bed late this weekend?", "Are you going to bed late this weekend?"], de: ["Wirst du dieses Wochenende spät ins Bett gehen?", "Gehst du am Wochenende spät ins Bett?"] } },
    // Lesson 7
    { id: "u13.44", lesson: 7, fr: "L'année prochaine, je vais apprendre l'italien.", en: "Next year, I'm going to learn Italian.", de: "Nächstes Jahr lerne ich Italienisch.", alt: { fr: ["Je vais apprendre l'italien l'année prochaine."], en: ["Next year, I will learn Italian.", "I'm going to learn Italian next year.", "I will learn Italian next year."], de: ["Nächstes Jahr werde ich Italienisch lernen.", "Ich lerne nächstes Jahr Italienisch.", "Ich werde nächstes Jahr Italienisch lernen."] } },
    { id: "u13.45", lesson: 7, fr: "Nous allons voyager l'année prochaine.", en: "We're going to travel next year.", de: "Nächstes Jahr reisen wir.", alt: { fr: ["L'année prochaine, nous allons voyager.", "On va voyager l'année prochaine.", "L'année prochaine, on va voyager."], en: ["We will travel next year.", "Next year, we're going to travel.", "Next year, we will travel."], de: ["Wir reisen nächstes Jahr.", "Nächstes Jahr werden wir reisen.", "Wir werden nächstes Jahr reisen."] } },
    { id: "u13.46", lesson: 7, fr: "Tu vas apprendre à nager ?", en: "Are you going to learn to swim?", de: "Wirst du schwimmen lernen?", alt: { fr: ["Est-ce que tu vas apprendre à nager ?", "Vas-tu apprendre à nager ?", "Vous allez apprendre à nager ?", "Est-ce que vous allez apprendre à nager ?"], en: ["Will you learn to swim?", "Are you going to learn how to swim?"], de: ["Lernst du schwimmen?"] } },
    { id: "u13.47", lesson: 7, fr: "Hugo ne va pas voyager, il va travailler.", en: "Hugo isn't going to travel, he's going to work.", de: "Hugo wird nicht reisen, er wird arbeiten.", alt: { en: ["Hugo won't travel, he will work.", "Hugo's not going to travel, he's going to work."], de: ["Hugo reist nicht, er arbeitet."] } },
    { id: "u13.48", lesson: 7, fr: "L'année prochaine, ma sœur va habiter à Berlin.", en: "Next year, my sister is going to live in Berlin.", de: "Nächstes Jahr wohnt meine Schwester in Berlin.", alt: { fr: ["Ma sœur va habiter à Berlin l'année prochaine."], en: ["Next year, my sister will live in Berlin.", "My sister is going to live in Berlin next year.", "My sister will live in Berlin next year."], de: ["Nächstes Jahr wird meine Schwester in Berlin wohnen.", "Meine Schwester wird nächstes Jahr in Berlin wohnen.", "Meine Schwester wohnt nächstes Jahr in Berlin."] } },
    { id: "u13.49", lesson: 7, fr: "Je vais inviter toute la classe !", en: "I'm going to invite the whole class!", de: "Ich werde die ganze Klasse einladen!", alt: { en: ["I will invite the whole class!", "I'm going to invite all the class!"], de: ["Ich lade die ganze Klasse ein!"] } },
    { id: "u13.50", lesson: 7, fr: "Demain, Blob va préparer un gâteau… ou pas !", en: "Tomorrow, Blob is going to make a cake… or not!", de: "Morgen backt Blob einen Kuchen … oder auch nicht!", alt: { fr: ["Blob va préparer un gâteau demain… ou pas !"], en: ["Tomorrow, Blob will make a cake… or not!", "Blob is going to make a cake tomorrow… or not!", "Tomorrow, Blob is going to bake a cake… or not!", "Tomorrow, Blob is going to prepare a cake… or not!"], de: ["Morgen wird Blob einen Kuchen backen … oder auch nicht!", "Morgen backt Blob einen Kuchen … oder nicht!", "Morgen macht Blob einen Kuchen … oder auch nicht!", "Morgen wird Blob einen Kuchen machen … oder auch nicht!"] } },
  ],
  drills: [
    { id: "u13.d1", lesson: 1, fr: "Demain, je ___ manger une pizza.", options: ["vais", "va", "vas"], answer: 0, en: "Tomorrow, I'm going to eat a pizza.", de: "Morgen esse ich eine Pizza.", why: tx("The near future is **aller** + infinitive. With je: je **vais** manger.", "Die nahe Zukunft ist **aller** + Infinitiv. Mit je: je **vais** manger.") },
    { id: "u13.d2", lesson: 1, fr: "Ce soir, je vais ___ Léa.", options: ["voir", "vois", "vu"], answer: 0, en: "This evening, I'm going to see Léa.", de: "Heute Abend sehe ich Léa.", why: tx("Only aller changes. The second verb stays in the infinitive: je vais **voir**.", "Nur aller ändert sich. Das zweite Verb bleibt im Infinitiv: je vais **voir**.") },
    { id: "u13.d3", lesson: 1, fr: "Qu'est-ce que tu vas ___ demain ?", options: ["faire", "fais", "fait"], answer: 0, en: "What are you going to do tomorrow?", de: "Was machst du morgen?", why: tx("After tu vas comes the infinitive **faire**, not fais.", "Nach tu vas kommt der Infinitiv **faire**, nicht fais.") },
    { id: "u13.d4", lesson: 2, fr: "Tu ___ jouer au foot samedi ?", options: ["vas", "vais", "va"], answer: 0, en: "Are you going to play football on Saturday?", de: "Spielst du am Samstag Fußball?", why: tx("With **tu**: tu **vas**, with an s you don't hear.", "Mit **tu**: tu **vas**, mit einem stummen s.") },
    { id: "u13.d5", lesson: 2, fr: "Elle va ___ une robe rouge.", options: ["acheter", "achète", "acheté"], answer: 0, en: "She's going to buy a red dress.", de: "Sie wird ein rotes Kleid kaufen.", why: tx("After va, the infinitive in **-er**: elle va **acheter**. They all sound alike, so look at the ending!", "Nach va kommt der Infinitiv auf **-er**: elle va **acheter**. Alle klingen ähnlich, achte auf die Endung!") },
    { id: "u13.d6", lesson: 2, fr: "Nous allons ___ à la plage.", options: ["aller", "allons", "allez"], answer: 0, en: "We're going to go to the beach.", de: "Wir werden an den Strand gehen.", why: tx("Yes, aller twice: nous allons **aller**, we're going to go.", "Ja, zweimal aller: nous allons **aller**, wir werden gehen.") },
    { id: "u13.d7", lesson: 3, fr: "Je vais ___ bientôt.", options: ["partir", "pars", "parti"], answer: 0, en: "I'm going to leave soon.", de: "Ich werde bald gehen.", why: tx("Infinitives end in -er, -ir or -re: **partir**, dormir, lire.", "Infinitive enden auf -er, -ir oder -re: **partir**, dormir, lire.") },
    { id: "u13.d8", lesson: 3, fr: "Le bus ___ partir !", options: ["va", "vas", "vont"], answer: 0, en: "The bus is going to leave!", de: "Der Bus fährt gleich ab!", why: tx("One bus is like il: le bus **va** partir.", "Ein Bus ist wie il: le bus **va** partir.") },
    { id: "u13.d9", lesson: 4, fr: "Nous ___ inviter nos amis.", options: ["allons", "allez", "vont"], answer: 0, en: "We're going to invite our friends.", de: "Wir werden unsere Freunde einladen.", why: tx("With **nous**: nous **allons**.", "Mit **nous**: nous **allons**.") },
    { id: "u13.d10", lesson: 4, fr: "Vous ___ préparer un pique-nique ?", options: ["allez", "allons", "vas"], answer: 0, en: "Are you going to make a picnic?", de: "Bereitet ihr ein Picknick vor?", why: tx("With **vous**: vous **allez**.", "Mit **vous**: vous **allez**.") },
    { id: "u13.d11", lesson: 4, fr: "Ils ___ préparer le dîner.", options: ["vont", "va", "allons"], answer: 0, en: "They're going to make dinner.", de: "Sie werden das Abendessen machen.", why: tx("With **ils**: ils **vont**. Aller is irregular!", "Mit **ils**: ils **vont**. Aller ist unregelmäßig!") },
    { id: "u13.d12", lesson: 5, fr: "Je ___ vais pas ranger ma chambre.", options: ["ne", "pas", "non"], answer: 0, en: "I'm not going to tidy my bedroom.", de: "Ich werde mein Zimmer nicht aufräumen.", why: tx("**Ne** … **pas** goes around **vais**, not around the infinitive: je **ne** vais **pas** ranger.", "**Ne** … **pas** steht um **vais** herum, nicht um den Infinitiv: je **ne** vais **pas** ranger.") },
    { id: "u13.d13", lesson: 5, fr: "Nous ___ pas rester ici.", options: ["n'allons", "ne allons", "non allons"], answer: 0, en: "We're not going to stay here.", de: "Wir werden nicht hier bleiben.", why: tx("Before a vowel, ne becomes **n'**: nous **n'allons** pas rester.", "Vor einem Vokal wird ne zu **n'**: nous **n'allons** pas rester.") },
    { id: "u13.d14", lesson: 5, fr: "Il ne va pas ___ demain.", options: ["partir", "part", "parti"], answer: 0, en: "He isn't going to leave tomorrow.", de: "Er fährt morgen nicht weg.", why: tx("In the negative too, the second verb stays in the infinitive: il ne va pas **partir**.", "Auch verneint bleibt das zweite Verb im Infinitiv: il ne va pas **partir**.") },
    { id: "u13.d15", lesson: 6, fr: "Après-demain, je vais ___ lever tôt.", options: ["me", "se", "moi"], answer: 0, en: "The day after tomorrow, I'm going to get up early.", de: "Übermorgen stehe ich früh auf.", why: tx("The little pronoun still matches the person, right before the infinitive: je vais **me** lever.", "Das kleine Pronomen passt weiter zur Person und steht direkt vor dem Infinitiv: je vais **me** lever.") },
    { id: "u13.d16", lesson: 6, fr: "Tu vas ___ coucher tard ce week-end ?", options: ["te", "se", "toi"], answer: 0, en: "Are you going to go to bed late this weekend?", de: "Gehst du dieses Wochenende spät ins Bett?", why: tx("With tu, it's **te**: tu vas **te** coucher. Se is only for il, elle, ils and elles.", "Mit tu heißt es **te**: tu vas **te** coucher. Se ist nur für il, elle, ils und elles.") },
    { id: "u13.d17", lesson: 6, fr: "Ce week-end, il va ___.", options: ["pleuvoir", "pleut"], answer: 0, en: "This weekend, it's going to rain.", de: "Dieses Wochenende wird es regnen.", why: tx("After va comes the infinitive: **pleuvoir** (to rain). Il pleut is the present.", "Nach va kommt der Infinitiv: **pleuvoir** (regnen). Il pleut ist die Gegenwart.") },
    { id: "u13.d18", lesson: 7, fr: "Tu vas apprendre ___ nager ?", options: ["à", "de", "au"], answer: 0, en: "Are you going to learn to swim?", de: "Wirst du schwimmen lernen?", why: tx("Apprendre takes **à** before an infinitive: apprendre **à** nager.", "Apprendre braucht **à** vor einem Infinitiv: apprendre **à** nager.") },
    { id: "u13.d19", lesson: 7, fr: "L'année prochaine, nous allons ___.", options: ["voyager", "voyageons", "voyagé"], answer: 0, en: "Next year, we're going to travel.", de: "Nächstes Jahr reisen wir.", why: tx("Nous allons + infinitive: nous allons **voyager**. Only allons changes with the person.", "Nous allons + Infinitiv: nous allons **voyager**. Nur allons ändert sich mit der Person.") },
    { id: "u13.d20", lesson: 7, fr: "Hugo ne va pas voyager, il va ___.", options: ["travailler", "travaille", "travaillé"], answer: 0, en: "Hugo isn't going to travel, he's going to work.", de: "Hugo wird nicht reisen, er wird arbeiten.", why: tx("Il va + infinitive: il va **travailler**.", "Il va + Infinitiv: il va **travailler**.") },
  ],
  dialogues: [
    {
      id: "u13.dialogue",
      lesson: 5,
      title: tx("The big picnic", "Das große Picknick"),
      lines: [
        { who: "chloe", fr: "Léa, tu as des projets pour samedi ?", en: "Léa, do you have plans for Saturday?", de: "Léa, hast du Pläne für Samstag?" },
        { who: "lea", fr: "Oui ! Nous allons faire un pique-nique au parc avec Hugo et Blob.", en: "Yes! We're going to have a picnic in the park with Hugo and Blob.", de: "Ja! Wir machen mit Hugo und Blob ein Picknick im Park." },
        { who: "chloe", fr: "Super ! Et moi, qu'est-ce que je vais préparer ?", en: "Great! And what am I going to make?", de: "Super! Und was mache ich?" },
        { who: "lea", fr: "Tu vas préparer une salade. Moi, je vais faire des sandwichs.", en: "You're going to make a salad. I'm going to make sandwiches.", de: "Du machst einen Salat. Ich mache Sandwiches." },
        { who: "hugo", fr: "Et moi, je vais acheter les boissons.", en: "And I'm going to buy the drinks.", de: "Und ich kaufe die Getränke." },
        { who: "blob", fr: "Et moi, je vais inviter tout le monde !", en: "And I'm going to invite everyone!", de: "Und ich lade alle ein!" },
        { who: "lea", fr: "Tout le monde ? Qui, Blob ?", en: "Everyone? Who, Blob?", de: "Alle? Wen denn, Blob?" },
        { who: "blob", fr: "Madame Martin, le serveur, le prof… et le chat !", en: "Mrs Martin, the waiter, the teacher… and the cat!", de: "Frau Martin, den Kellner, den Lehrer … und die Katze!" },
        { who: "hugo", fr: "Oh là là, le pique-nique va être grand !", en: "Oh dear, the picnic is going to be big!", de: "Oje, das Picknick wird groß!" },
      ],
      questions: [
        { q: tx("What are they going to do on Saturday?", "Was machen sie am Samstag?"), options: [tx("Have a picnic in the park", "Ein Picknick im Park machen"), tx("Go to the cinema", "Ins Kino gehen"), tx("Play video games", "Videospiele spielen")], answer: 0 },
        { q: tx("What is Chloé going to make?", "Was macht Chloé?"), options: [tx("A salad", "Einen Salat"), tx("Sandwiches", "Sandwiches"), tx("A cake", "Einen Kuchen")], answer: 0 },
        { q: tx("Who is Blob going to invite?", "Wen lädt Blob ein?"), options: [tx("Everyone, even the cat", "Alle, sogar die Katze"), tx("Only Hugo", "Nur Hugo"), tx("Nobody", "Niemanden")], answer: 0 },
      ],
    },
    {
      id: "u13.dialogue2",
      lesson: 7,
      title: tx("Blob's big plans", "Blobs große Pläne"),
      lines: [
        { who: "madame", fr: "Blob, qu'est-ce que tu vas faire l'année prochaine ?", en: "Blob, what are you going to do next year?", de: "Blob, was machst du nächstes Jahr?" },
        { who: "blob", fr: "L'année prochaine, je vais voyager ! Je vais visiter Paris, Berlin et Marseille.", en: "Next year I'm going to travel! I'm going to visit Paris, Berlin and Marseille.", de: "Nächstes Jahr reise ich! Ich besuche Paris, Berlin und Marseille." },
        { who: "madame", fr: "Et l'école ?", en: "And school?", de: "Und die Schule?" },
        { who: "blob", fr: "L'école ? Euh… je vais apprendre l'allemand à Berlin !", en: "School? Er… I'm going to learn German in Berlin!", de: "Die Schule? Äh … ich lerne in Berlin Deutsch!" },
        { who: "hugo", fr: "Tu vas partir quand ?", en: "When are you going to leave?", de: "Wann fährst du los?" },
        { who: "blob", fr: "Bientôt ! Mais d'abord, je vais dormir un peu.", en: "Soon! But first I'm going to sleep a bit.", de: "Bald! Aber zuerst schlafe ich ein bisschen." },
        { who: "lea", fr: "Et nous ? Tu ne vas pas rester avec nous ?", en: "And us? Aren't you going to stay with us?", de: "Und wir? Bleibst du nicht bei uns?" },
        { who: "blob", fr: "Si ! Je vais voyager… plus tard. Ce soir, je reste ici !", en: "Yes, I am! I'm going to travel… later. Tonight I'm staying here!", de: "Doch! Ich reise … später. Heute Abend bleibe ich hier!" },
        { who: "madame", fr: "Très bien. Alors ce soir, je vais préparer des crêpes pour tout le monde !", en: "Very good. Then tonight I'm going to make crêpes for everyone!", de: "Sehr gut. Dann mache ich heute Abend Crêpes für alle!" },
      ],
      questions: [
        { q: tx("What is Blob going to do next year?", "Was macht Blob nächstes Jahr?"), options: [tx("Travel", "Reisen"), tx("Work in a café", "In einem Café arbeiten"), tx("Learn to swim", "Schwimmen lernen")], answer: 0 },
        { q: tx("What is Blob going to learn in Berlin?", "Was lernt Blob in Berlin?"), options: [tx("German", "Deutsch"), tx("Italian", "Italienisch"), tx("English", "Englisch")], answer: 0 },
        { q: tx("What is Mrs Martin going to make tonight?", "Was macht Frau Martin heute Abend?"), options: [tx("Crêpes for everyone", "Crêpes für alle"), tx("A cake for Blob", "Einen Kuchen für Blob"), tx("Sandwiches", "Sandwiches")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Je vais manger: the near future", "Je vais manger: die nahe Zukunft"),
      body: tx(
        "To talk about plans, take **aller** and add an infinitive: **je vais manger** (I'm going to eat). Only aller changes with the person; the second verb stays as it is in the dictionary, ending in -er, -ir or -re.\n\nIt's like «going to» in English. In German you'd say ich werde essen, or just the present with a time word: morgen esse ich.",
        "Für Pläne nimmst du **aller** und hängst einen Infinitiv an: **je vais manger** (ich werde essen). Nur aller ändert sich mit der Person; das zweite Verb bleibt wie im Wörterbuch, auf -er, -ir oder -re.\n\nIm Deutschen sagst du ich werde essen oder einfach die Gegenwart mit einem Zeitwort: morgen esse ich.",
      ),
      examples: [
        { fr: "Demain, je vais manger une pizza.", en: "Tomorrow, I'm going to eat a pizza.", de: "Morgen esse ich eine Pizza." },
        { fr: "Tu vas jouer au foot samedi ?", en: "Are you going to play football on Saturday?", de: "Spielst du am Samstag Fußball?" },
        { fr: "Nous allons aller à la plage.", en: "We're going to go to the beach.", de: "Wir werden an den Strand gehen." },
      ],
      table: {
        head: [tx("person", "Person"), "aller", tx("+ infinitive", "+ Infinitiv")],
        rows: [
          [tx("I", "ich"), "je vais", "manger"],
          [tx("you", "du"), "tu vas", "partir"],
          [tx("he / she", "er / sie"), "il / elle va", "dormir"],
          [tx("we", "wir"), "nous allons", "voir"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous allez", "faire"],
          [tx("they", "sie"), "ils / elles vont", "lire"],
        ],
      },
    },
    {
      title: tx("When? Words for later", "Wann? Wörter für später"),
      body: tx(
        "Time words go at the start or at the end: **demain**, je vais partir, or je vais partir **demain**.\n\n**Ce soir** is this evening, **la semaine prochaine** next week, **bientôt** soon, **plus tard** later. Prochaine comes after the noun, like many French adjectives.",
        "Zeitwörter stehen am Anfang oder am Ende: **demain**, je vais partir, oder je vais partir **demain**.\n\n**Ce soir** heißt heute Abend, **la semaine prochaine** nächste Woche, **bientôt** bald, **plus tard** später. Prochaine steht nach dem Nomen, wie viele französische Adjektive.",
      ),
      examples: [
        { fr: "Ce soir, je vais voir Léa.", en: "This evening, I'm going to see Léa.", de: "Heute Abend sehe ich Léa." },
        { fr: "Je vais visiter Paris la semaine prochaine.", en: "I'm going to visit Paris next week.", de: "Ich besuche nächste Woche Paris." },
        { fr: "Plus tard, je vais regarder la télé.", en: "Later, I'm going to watch TV.", de: "Später sehe ich fern." },
      ],
      table: {
        head: [tx("French", "Französisch"), tx("meaning", "Bedeutung")],
        rows: [
          ["ce soir", tx("this evening", "heute Abend")],
          ["demain", tx("tomorrow", "morgen")],
          ["après-demain", tx("the day after tomorrow", "übermorgen")],
          ["ce week-end", tx("this weekend", "dieses Wochenende")],
          ["la semaine prochaine", tx("next week", "nächste Woche")],
          ["l'année prochaine", tx("next year", "nächstes Jahr")],
        ],
      },
    },
    {
      title: tx("Not going to: ne … pas around aller", "Nicht vorhaben: ne … pas um aller"),
      body: tx(
        "In the negative, **ne** … **pas** goes around the form of aller, and the infinitive comes after: je **ne** vais **pas** travailler.\n\nBefore allons and allez, ne becomes **n'**: nous **n'allons** pas rester, vous **n'allez** pas jouer.",
        "Bei der Verneinung steht **ne** … **pas** um die Form von aller, der Infinitiv kommt danach: je **ne** vais **pas** travailler.\n\nVor allons und allez wird ne zu **n'**: nous **n'allons** pas rester, vous **n'allez** pas jouer.",
      ),
      examples: [
        { fr: "Je ne vais pas ranger ma chambre.", en: "I'm not going to tidy my bedroom.", de: "Ich werde mein Zimmer nicht aufräumen." },
        { fr: "Nous n'allons pas rester ici.", en: "We're not going to stay here.", de: "Wir werden nicht hier bleiben." },
        { fr: "Il ne va pas partir demain.", en: "He isn't going to leave tomorrow.", de: "Er fährt morgen nicht weg." },
      ],
    },
    {
      title: tx("Je vais me lever: me, te, se stay", "Je vais me lever: me, te, se bleiben"),
      body: tx(
        "With a reflexive verb, the little pronoun goes right before the infinitive and still matches the person: je vais **me** lever, tu vas **te** coucher, il va **se** lever.\n\nTo learn to do something: **apprendre à** + infinitive: apprendre à nager.\n\nAnd to say yes to a «no» question, French has a special word: — Tu ne vas pas rester ? — **Si !** (Yes, I am!), just like German doch.",
        "Bei einem reflexiven Verb steht das kleine Pronomen direkt vor dem Infinitiv und passt weiter zur Person: je vais **me** lever, tu vas **te** coucher, il va **se** lever.\n\nEtwas lernen: **apprendre à** + Infinitiv: apprendre à nager.\n\nUnd für ein Ja auf eine verneinte Frage gibt es ein eigenes Wort: — Tu ne vas pas rester ? — **Si !**, genau wie doch.",
      ),
      examples: [
        { fr: "Après-demain, je vais me lever tôt.", en: "The day after tomorrow, I'm going to get up early.", de: "Übermorgen stehe ich früh auf." },
        { fr: "Tu vas te coucher tard ce week-end ?", en: "Are you going to go to bed late this weekend?", de: "Gehst du dieses Wochenende spät ins Bett?" },
        { fr: "Tu vas apprendre à nager ?", en: "Are you going to learn to swim?", de: "Wirst du schwimmen lernen?" },
      ],
      table: {
        head: [tx("person", "Person"), "se lever"],
        rows: [
          [tx("I", "ich"), "je vais me lever"],
          [tx("you", "du"), "tu vas te lever"],
          [tx("he / she", "er / sie"), "il / elle va se lever"],
          [tx("we", "wir"), "nous allons nous lever"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous allez vous lever"],
          [tx("they", "sie"), "ils / elles vont se lever"],
        ],
      },
    },
  ],
};
