import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 14: the passé composé with avoir (j'ai mangé, j'ai fait). */
export const u14: Unit = {
  slug: "hier",
  n: 14,
  cefr: "A2",
  title: tx("Yesterday", "Gestern"),
  goal: tx("Say what you did", "Erzählen, was du gemacht hast"),
  emoji: "📷",
  words: [
    { id: "hier", fr: "hier", en: "yesterday", de: "gestern", kind: "adv", note: tx("Not the German hier! In French, hier is yesterday.", "Nicht das deutsche hier! Auf Französisch heißt hier gestern.") },
    { id: "pp-mange", fr: "mangé", en: "eaten / ate", de: "gegessen", kind: "verb", note: tx("The past of -er verbs: drop -er, add é. Manger → j'ai mangé.", "Die Vergangenheit der -er-Verben: -er weg, é dazu. Manger → j'ai mangé.") },
    { id: "pp-bu", fr: "bu", en: "drunk / drank", de: "getrunken", kind: "verb", note: tx("From boire: j'ai bu un café.", "Von boire: j'ai bu un café.") },
    { id: "pp-regarde", fr: "regardé", en: "watched", de: "angeschaut", alt: { en: ["looked at"], de: ["angesehen", "geschaut"] }, kind: "verb" },
    { id: "hier-soir", fr: "hier soir", en: "last night", de: "gestern Abend", alt: { en: ["yesterday evening", "last evening"] }, kind: "phrase" },
    { id: "tu-as-fait-quoi", fr: "tu as fait quoi ?", en: "what did you do?", de: "was hast du gemacht?", alt: { fr: ["qu'est-ce que tu as fait ?"] }, kind: "phrase", note: tx("Everyday French. A bit more careful: qu'est-ce que tu as fait ?", "Alltagsfranzösisch. Etwas sorgfältiger: qu'est-ce que tu as fait ?") },
    { id: "pp-fait", fr: "fait", en: "done / made", de: "gemacht", alt: { en: ["did"] }, kind: "verb", note: tx("From faire: j'ai fait mes devoirs.", "Von faire: j'ai fait mes devoirs.") },
    { id: "pp-joue", fr: "joué", en: "played", de: "gespielt", kind: "verb" },
    { id: "pp-parle", fr: "parlé", en: "spoken / talked", de: "gesprochen", alt: { en: ["spoke"], de: ["geredet"] }, kind: "verb" },
    { id: "ce-matin", fr: "ce matin", en: "this morning", de: "heute Morgen", alt: { de: ["heute früh"] }, kind: "phrase" },
    { id: "pp-vu", fr: "vu", en: "seen / saw", de: "gesehen", kind: "verb", note: tx("From voir: j'ai vu Hugo.", "Von voir: j'ai vu Hugo.") },
    { id: "pp-pris", fr: "pris", en: "taken / took", de: "genommen", kind: "verb", note: tx("From prendre: j'ai pris le bus. The s is silent.", "Von prendre: j'ai pris le bus. Das s ist stumm.") },
    { id: "pp-fini", fr: "fini", en: "finished", de: "beendet", alt: { de: ["fertig gemacht"] }, kind: "verb", note: tx("-ir verbs lose their r: finir → fini. J'ai fini ! = I'm done!", "-ir-Verben verlieren das r: finir → fini. J'ai fini ! = Ich bin fertig!") },
    { id: "semaine-derniere", fr: "la semaine dernière", en: "last week", de: "letzte Woche", alt: { de: ["vergangene Woche"] }, kind: "phrase", note: tx("Dernière comes after the noun, like prochaine.", "Dernière steht nach dem Nomen, wie prochaine.") },
    { id: "pp-achete", fr: "acheté", en: "bought", de: "gekauft", kind: "verb" },
    { id: "deja", fr: "déjà", en: "already", de: "schon", alt: { de: ["bereits"] }, kind: "adv", note: tx("It goes between avoir and the participle: j'ai déjà mangé. Déjà vu: «already seen»!", "Es steht zwischen avoir und dem Partizip: j'ai déjà mangé. Déjà-vu: „schon gesehen“!") },
    { id: "pas-encore", fr: "pas encore", en: "not yet", de: "noch nicht", kind: "phrase", note: tx("Je n'ai pas encore mangé: I haven't eaten yet.", "Je n'ai pas encore mangé: Ich habe noch nicht gegessen.") },
    { id: "pp-dormi", fr: "dormi", en: "slept", de: "geschlafen", kind: "verb", emoji: "😪" },
    { id: "pp-lu", fr: "lu", en: "read", de: "gelesen", kind: "verb", note: tx("From lire: j'ai lu un livre.", "Von lire: j'ai lu un livre.") },
    { id: "week-end-dernier", fr: "le week-end dernier", en: "last weekend", de: "letztes Wochenende", alt: { de: ["am letzten Wochenende"] }, kind: "phrase" },
    { id: "pp-travaille", fr: "travaillé", en: "worked", de: "gearbeitet", kind: "verb" },
    { id: "pp-ecoute", fr: "écouté", en: "listened", de: "zugehört", alt: { en: ["listened to"], de: ["gehört", "angehört"] }, kind: "verb" },
    { id: "ne-jamais", fr: "ne … jamais", en: "never", de: "nie", alt: { de: ["niemals"] }, kind: "word", note: tx("Like ne … pas, around the verb: je n'ai jamais vu Paris.", "Wie ne … pas, um das Verb herum: je n'ai jamais vu Paris.") },
    { id: "pp-eu", fr: "eu", en: "had", de: "gehabt", kind: "verb", note: tx("From avoir, and it sounds just like the letter u: j'ai eu.", "Von avoir, und es klingt wie der Buchstabe u: j'ai eu.") },
    { id: "pp-appris", fr: "appris", en: "learned", de: "gelernt", alt: { en: ["learnt"] }, kind: "verb", note: tx("From apprendre, like pris from prendre.", "Von apprendre, wie pris von prendre.") },
    { id: "match", fr: "le match", en: "the match", de: "das Spiel", alt: { en: ["the game"], de: ["das Match"] }, g: "m", kind: "noun", emoji: "🏟️" },
    { id: "pp-gagne", fr: "gagné", en: "won", de: "gewonnen", kind: "verb", emoji: "🏆" },
    { id: "pp-perdu", fr: "perdu", en: "lost", de: "verloren", kind: "verb" },
  ],
  gloss: [
    { fr: "j'ai fait", en: "I did / I made", de: "ich habe gemacht" },
    { fr: "elle fait", en: "she does / she makes", de: "sie macht" },
    { fr: "photos", en: "photos", de: "Fotos" },
    { fr: "tous", en: "all", de: "alle" },
    { fr: "tout le week-end", en: "all weekend", de: "das ganze Wochenende" },
    { fr: "la tour Eiffel", en: "the Eiffel Tower", de: "der Eiffelturm" },
    { fr: "note", en: "mark / grade", de: "Note" },
    { fr: "de la chance", en: "luck", de: "Glück" },
    { fr: "dit", en: "said", de: "gesagt" },
    { fr: "aidé", en: "helped", de: "geholfen" },
    { fr: "encore", en: "again / still", de: "wieder / noch" },
    { fr: "jamais", en: "never", de: "nie" },
    { fr: "là", en: "there / then", de: "da / dort" },
    { fr: "ballon", en: "ball", de: "Ball" },
    { fr: "pendant", en: "during", de: "während" },
    { fr: "j'ai eu faim", en: "I got hungry", de: "ich hatte Hunger" },
    { fr: "touché", en: "touched", de: "berührt" },
  ],
  lessons: [
    { title: tx("Yesterday I ate…", "Gestern habe ich gegessen …"), words: ["hier", "pp-mange", "pp-bu", "pp-regarde", "hier-soir"] },
    { title: tx("What did you do?", "Was hast du gemacht?"), words: ["tu-as-fait-quoi", "pp-fait", "pp-joue", "pp-parle", "ce-matin"] },
    { title: tx("I saw, I took", "Ich habe gesehen, ich habe genommen"), words: ["pp-vu", "pp-pris", "pp-fini", "semaine-derniere", "pp-achete"] },
    { title: tx("Not yet!", "Noch nicht!"), words: ["deja", "pas-encore", "pp-dormi", "pp-lu"] },
    { title: tx("Last weekend", "Letztes Wochenende"), words: ["week-end-dernier", "pp-travaille", "pp-ecoute"] },
    { title: tx("Never!", "Nie!"), words: ["ne-jamais", "pp-eu", "pp-appris"] },
    { title: tx("The match", "Das Spiel"), words: ["match", "pp-gagne", "pp-perdu"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u14.01", lesson: 1, fr: "Hier, j'ai mangé une pizza.", en: "Yesterday, I ate a pizza.", de: "Gestern habe ich eine Pizza gegessen.", alt: { fr: ["J'ai mangé une pizza hier."], en: ["I ate a pizza yesterday.", "Yesterday, I had a pizza.", "I had a pizza yesterday."], de: ["Ich habe gestern eine Pizza gegessen.", "Gestern aß ich eine Pizza.", "Ich aß gestern eine Pizza."] } },
    { id: "u14.02", lesson: 1, fr: "J'ai bu un chocolat chaud.", en: "I drank a hot chocolate.", de: "Ich habe eine heiße Schokolade getrunken.", alt: { en: ["I had a hot chocolate.", "I have drunk a hot chocolate.", "I have had a hot chocolate."], de: ["Ich trank eine heiße Schokolade.", "Ich habe einen Kakao getrunken."] } },
    { id: "u14.03", lesson: 1, fr: "Hier soir, j'ai regardé la télé.", en: "Last night, I watched TV.", de: "Gestern Abend habe ich ferngesehen.", alt: { fr: ["J'ai regardé la télé hier soir."], en: ["Yesterday evening, I watched TV.", "I watched TV last night.", "I watched TV yesterday evening.", "Last night, I watched television.", "Last evening, I watched TV."], de: ["Ich habe gestern Abend ferngesehen.", "Gestern Abend sah ich fern.", "Gestern Abend habe ich Fernsehen geschaut."] } },
    { id: "u14.04", lesson: 1, fr: "Tu as mangé ?", en: "Have you eaten?", de: "Hast du gegessen?", alt: { fr: ["Est-ce que tu as mangé ?", "As-tu mangé ?", "Vous avez mangé ?", "Est-ce que vous avez mangé ?", "Avez-vous mangé ?"], en: ["Did you eat?"] } },
    { id: "u14.05", lesson: 1, fr: "Il a bu tout le lait !", en: "He drank all the milk!", de: "Er hat die ganze Milch getrunken!", alt: { en: ["He has drunk all the milk!", "He drank all of the milk!"], de: ["Er trank die ganze Milch!", "Er hat die ganze Milch ausgetrunken!"] } },
    { id: "u14.06", lesson: 1, fr: "Nous avons mangé des crêpes hier soir.", en: "We ate crêpes last night.", de: "Wir haben gestern Abend Crêpes gegessen.", alt: { fr: ["Hier soir, nous avons mangé des crêpes.", "On a mangé des crêpes hier soir.", "Hier soir, on a mangé des crêpes."], en: ["We ate crêpes yesterday evening.", "Last night, we ate crêpes.", "We had crêpes last night.", "Last night, we had crêpes.", "We had crêpes yesterday evening."], de: ["Gestern Abend haben wir Crêpes gegessen.", "Gestern Abend aßen wir Crêpes.", "Wir aßen gestern Abend Crêpes."] } },
    { id: "u14.07", lesson: 1, fr: "Hier, Léa a regardé les photos.", en: "Yesterday, Léa looked at the photos.", de: "Gestern hat Léa die Fotos angeschaut.", alt: { fr: ["Léa a regardé les photos hier."], en: ["Léa looked at the photos yesterday.", "Yesterday, Léa looked at the pictures."], de: ["Léa hat gestern die Fotos angeschaut.", "Gestern hat Léa die Fotos angesehen.", "Léa hat gestern die Fotos angesehen.", "Gestern hat sich Léa die Fotos angeschaut.", "Gestern sah Léa die Fotos an."] } },
    // Lesson 2
    { id: "u14.08", lesson: 2, fr: "Tu as fait quoi hier ?", en: "What did you do yesterday?", de: "Was hast du gestern gemacht?", alt: { fr: ["Qu'est-ce que tu as fait hier ?", "Hier, tu as fait quoi ?", "Qu'as-tu fait hier ?", "Vous avez fait quoi hier ?", "Qu'est-ce que vous avez fait hier ?", "Qu'avez-vous fait hier ?"], de: ["Was hast du gestern getan?"] } },
    { id: "u14.09", lesson: 2, fr: "J'ai fait mes devoirs.", en: "I did my homework.", de: "Ich habe meine Hausaufgaben gemacht.", alt: { en: ["I have done my homework."], de: ["Ich machte meine Hausaufgaben."] } },
    { id: "u14.10", lesson: 2, fr: "Ce matin, j'ai joué au tennis.", en: "This morning, I played tennis.", de: "Heute Morgen habe ich Tennis gespielt.", alt: { fr: ["J'ai joué au tennis ce matin."], en: ["I played tennis this morning.", "I have played tennis this morning."], de: ["Ich habe heute Morgen Tennis gespielt.", "Heute früh habe ich Tennis gespielt.", "Heute Morgen spielte ich Tennis."] } },
    { id: "u14.11", lesson: 2, fr: "Elle a parlé avec le professeur.", en: "She spoke to the teacher.", de: "Sie hat mit dem Lehrer gesprochen.", alt: { en: ["She talked to the teacher.", "She spoke with the teacher.", "She talked with the teacher.", "She has spoken to the teacher.", "She has talked to the teacher."], de: ["Sie sprach mit dem Lehrer.", "Sie hat mit dem Lehrer geredet."] } },
    { id: "u14.12", lesson: 2, fr: "Nous avons joué aux jeux vidéo.", en: "We played video games.", de: "Wir haben Videospiele gespielt.", alt: { fr: ["On a joué aux jeux vidéo."], en: ["We have played video games."], de: ["Wir spielten Videospiele."] } },
    { id: "u14.13", lesson: 2, fr: "Qu'est-ce que vous avez fait ce matin ?", en: "What did you do this morning?", de: "Was habt ihr heute Morgen gemacht?", alt: { fr: ["Vous avez fait quoi ce matin ?", "Qu'avez-vous fait ce matin ?", "Qu'est-ce que tu as fait ce matin ?", "Tu as fait quoi ce matin ?", "Qu'as-tu fait ce matin ?"], en: ["What have you done this morning?"], de: ["Was haben Sie heute Morgen gemacht?", "Was habt ihr heute früh gemacht?"] } },
    { id: "u14.14", lesson: 2, fr: "Hugo a parlé français avec Chloé.", en: "Hugo spoke French with Chloé.", de: "Hugo hat mit Chloé Französisch gesprochen.", alt: { en: ["Hugo spoke French to Chloé.", "Hugo has spoken French with Chloé."], de: ["Hugo sprach mit Chloé Französisch.", "Hugo hat Französisch mit Chloé gesprochen."] } },
    // Lesson 3
    { id: "u14.15", lesson: 3, fr: "J'ai vu Hugo au parc.", en: "I saw Hugo in the park.", de: "Ich habe Hugo im Park gesehen.", alt: { en: ["I saw Hugo at the park.", "I have seen Hugo in the park.", "I have seen Hugo at the park."], de: ["Ich sah Hugo im Park."] } },
    { id: "u14.16", lesson: 3, fr: "Ce matin, j'ai pris le bus.", en: "This morning, I took the bus.", de: "Heute Morgen habe ich den Bus genommen.", alt: { fr: ["J'ai pris le bus ce matin."], en: ["I took the bus this morning.", "This morning, I caught the bus.", "This morning, I got the bus.", "I have taken the bus this morning."], de: ["Ich habe heute Morgen den Bus genommen.", "Heute Morgen bin ich mit dem Bus gefahren.", "Ich bin heute Morgen mit dem Bus gefahren.", "Heute Morgen nahm ich den Bus."] } },
    { id: "u14.17", lesson: 3, fr: "Tu as fini tes devoirs ?", en: "Have you finished your homework?", de: "Hast du deine Hausaufgaben fertig gemacht?", alt: { fr: ["Est-ce que tu as fini tes devoirs ?", "As-tu fini tes devoirs ?", "Vous avez fini vos devoirs ?", "Est-ce que vous avez fini vos devoirs ?", "Avez-vous fini vos devoirs ?"], en: ["Did you finish your homework?"], de: ["Bist du mit deinen Hausaufgaben fertig?", "Hast du deine Hausaufgaben gemacht?", "Hast du deine Hausaufgaben beendet?"] } },
    { id: "u14.18", lesson: 3, fr: "La semaine dernière, j'ai acheté un vélo.", en: "Last week, I bought a bike.", de: "Letzte Woche habe ich ein Fahrrad gekauft.", alt: { fr: ["J'ai acheté un vélo la semaine dernière."], en: ["I bought a bike last week.", "Last week, I bought a bicycle."], de: ["Ich habe letzte Woche ein Fahrrad gekauft.", "Letzte Woche kaufte ich ein Fahrrad.", "Letzte Woche habe ich ein Rad gekauft.", "Vergangene Woche habe ich ein Fahrrad gekauft."] } },
    { id: "u14.19", lesson: 3, fr: "Ils ont vu la tour Eiffel !", en: "They saw the Eiffel Tower!", de: "Sie haben den Eiffelturm gesehen!", alt: { fr: ["Elles ont vu la tour Eiffel !"], en: ["They have seen the Eiffel Tower!"], de: ["Sie sahen den Eiffelturm!"] } },
    { id: "u14.20", lesson: 3, fr: "Il a pris une photo.", en: "He took a photo.", de: "Er hat ein Foto gemacht.", alt: { en: ["He took a picture.", "He has taken a photo.", "He has taken a picture."], de: ["Er machte ein Foto.", "Er hat ein Foto geknipst."] } },
    { id: "u14.21", lesson: 3, fr: "Vous avez vu le chat de Madame Martin ?", en: "Have you seen Mrs Martin's cat?", de: "Habt ihr die Katze von Frau Martin gesehen?", alt: { fr: ["Est-ce que vous avez vu le chat de Madame Martin ?", "Avez-vous vu le chat de Madame Martin ?", "Tu as vu le chat de Madame Martin ?", "Est-ce que tu as vu le chat de Madame Martin ?", "As-tu vu le chat de Madame Martin ?"], en: ["Did you see Mrs Martin's cat?"], de: ["Haben Sie die Katze von Frau Martin gesehen?", "Habt ihr Frau Martins Katze gesehen?", "Haben Sie Frau Martins Katze gesehen?"] } },
    // Lesson 4
    { id: "u14.22", lesson: 4, fr: "J'ai déjà mangé.", en: "I've already eaten.", de: "Ich habe schon gegessen.", alt: { en: ["I already ate.", "I've eaten already."], de: ["Ich habe bereits gegessen."] } },
    { id: "u14.23", lesson: 4, fr: "Je n'ai pas encore fini.", en: "I haven't finished yet.", de: "Ich bin noch nicht fertig.", alt: { en: ["I'm not finished yet.", "I'm not done yet.", "I didn't finish yet."], de: ["Ich bin noch nicht fertig geworden.", "Ich habe es noch nicht beendet."] } },
    { id: "u14.24", lesson: 4, fr: "Je n'ai pas dormi !", en: "I didn't sleep!", de: "Ich habe nicht geschlafen!", alt: { en: ["I haven't slept!"], de: ["Ich schlief nicht!"] } },
    { id: "u14.25", lesson: 4, fr: "Tu as déjà lu ce livre ?", en: "Have you already read this book?", de: "Hast du dieses Buch schon gelesen?", alt: { fr: ["Est-ce que tu as déjà lu ce livre ?", "As-tu déjà lu ce livre ?", "Vous avez déjà lu ce livre ?", "Est-ce que vous avez déjà lu ce livre ?", "Avez-vous déjà lu ce livre ?"], en: ["Have you read this book yet?", "Did you already read this book?", "Have you ever read this book?", "Have you already read that book?"], de: ["Hast du das Buch schon gelesen?", "Hast du dieses Buch bereits gelesen?"] } },
    { id: "u14.26", lesson: 4, fr: "Il n'a pas mangé sa soupe.", en: "He didn't eat his soup.", de: "Er hat seine Suppe nicht gegessen.", alt: { en: ["He hasn't eaten his soup.", "He didn't have his soup."], de: ["Er aß seine Suppe nicht."] } },
    { id: "u14.27", lesson: 4, fr: "Blob a dormi sur le canapé.", en: "Blob slept on the sofa.", de: "Blob hat auf dem Sofa geschlafen.", alt: { en: ["Blob slept on the couch.", "Blob has slept on the sofa."], de: ["Blob schlief auf dem Sofa.", "Blob hat auf der Couch geschlafen."] } },
    { id: "u14.28", lesson: 4, fr: "Nous n'avons pas encore vu Chloé.", en: "We haven't seen Chloé yet.", de: "Wir haben Chloé noch nicht gesehen.", alt: { fr: ["On n'a pas encore vu Chloé."], en: ["We didn't see Chloé yet."] } },
    // Lesson 5
    { id: "u14.29", lesson: 5, fr: "Le week-end dernier, j'ai travaillé.", en: "Last weekend, I worked.", de: "Letztes Wochenende habe ich gearbeitet.", alt: { fr: ["J'ai travaillé le week-end dernier."], en: ["I worked last weekend."], de: ["Am letzten Wochenende habe ich gearbeitet.", "Ich habe letztes Wochenende gearbeitet.", "Ich habe am letzten Wochenende gearbeitet.", "Letztes Wochenende arbeitete ich."] } },
    { id: "u14.30", lesson: 5, fr: "Tu as écouté la musique de Hugo ?", en: "Did you listen to Hugo's music?", de: "Hast du Hugos Musik gehört?", alt: { fr: ["Est-ce que tu as écouté la musique de Hugo ?", "As-tu écouté la musique de Hugo ?", "Vous avez écouté la musique de Hugo ?", "Est-ce que vous avez écouté la musique de Hugo ?"], en: ["Have you listened to Hugo's music?"], de: ["Hast du dir Hugos Musik angehört?", "Hast du die Musik von Hugo gehört?"] } },
    { id: "u14.31", lesson: 5, fr: "Ils ont travaillé tout le week-end.", en: "They worked all weekend.", de: "Sie haben das ganze Wochenende gearbeitet.", alt: { fr: ["Elles ont travaillé tout le week-end."], en: ["They worked the whole weekend.", "They have worked all weekend."], de: ["Sie arbeiteten das ganze Wochenende."] } },
    { id: "u14.32", lesson: 5, fr: "Le week-end dernier, nous avons fait un pique-nique.", en: "Last weekend, we had a picnic.", de: "Letztes Wochenende haben wir ein Picknick gemacht.", alt: { fr: ["Nous avons fait un pique-nique le week-end dernier.", "Le week-end dernier, on a fait un pique-nique.", "On a fait un pique-nique le week-end dernier."], en: ["We had a picnic last weekend."], de: ["Am letzten Wochenende haben wir ein Picknick gemacht.", "Wir haben letztes Wochenende ein Picknick gemacht."] } },
    { id: "u14.33", lesson: 5, fr: "Je n'ai pas écouté le professeur.", en: "I didn't listen to the teacher.", de: "Ich habe dem Lehrer nicht zugehört.", alt: { en: ["I haven't listened to the teacher.", "I wasn't listening to the teacher."], de: ["Ich hörte dem Lehrer nicht zu."] } },
    { id: "u14.34", lesson: 5, fr: "Tu as fait quoi le week-end dernier ?", en: "What did you do last weekend?", de: "Was hast du letztes Wochenende gemacht?", alt: { fr: ["Qu'est-ce que tu as fait le week-end dernier ?", "Le week-end dernier, tu as fait quoi ?", "Qu'as-tu fait le week-end dernier ?", "Vous avez fait quoi le week-end dernier ?", "Qu'est-ce que vous avez fait le week-end dernier ?", "Qu'avez-vous fait le week-end dernier ?"], de: ["Was hast du am letzten Wochenende gemacht?", "Was hast du letztes Wochenende getan?"] } },
    { id: "u14.35", lesson: 5, fr: "Vous avez bien travaillé !", en: "You worked well!", de: "Ihr habt gut gearbeitet!", alt: { fr: ["Tu as bien travaillé !"], en: ["You have worked well!", "You did a good job!"], de: ["Sie haben gut gearbeitet!"] } },
    // Lesson 6
    { id: "u14.36", lesson: 6, fr: "Je n'ai jamais mangé de poisson.", en: "I've never eaten fish.", de: "Ich habe nie Fisch gegessen.", alt: { en: ["I never ate fish."], de: ["Ich habe noch nie Fisch gegessen.", "Ich habe niemals Fisch gegessen."] } },
    { id: "u14.37", lesson: 6, fr: "Il n'a jamais joué au tennis.", en: "He has never played tennis.", de: "Er hat nie Tennis gespielt.", alt: { en: ["He never played tennis.", "He's never played tennis."], de: ["Er hat noch nie Tennis gespielt.", "Er hat niemals Tennis gespielt."] } },
    { id: "u14.38", lesson: 6, fr: "J'ai eu une bonne note.", en: "I got a good mark.", de: "Ich habe eine gute Note bekommen.", alt: { en: ["I got a good grade.", "I had a good mark.", "I have got a good mark.", "I have got a good grade."], de: ["Ich hatte eine gute Note.", "Ich bekam eine gute Note.", "Ich habe eine gute Note gehabt."] } },
    { id: "u14.39", lesson: 6, fr: "Nous avons eu de la chance !", en: "We were lucky!", de: "Wir haben Glück gehabt!", alt: { fr: ["On a eu de la chance !"], en: ["We got lucky!", "We have been lucky!"], de: ["Wir hatten Glück!"] } },
    { id: "u14.40", lesson: 6, fr: "Tu as appris à nager ?", en: "Did you learn to swim?", de: "Hast du schwimmen gelernt?", alt: { fr: ["Est-ce que tu as appris à nager ?", "As-tu appris à nager ?", "Vous avez appris à nager ?", "Est-ce que vous avez appris à nager ?"], en: ["Have you learned to swim?", "Have you learnt to swim?", "Did you learn how to swim?"] } },
    { id: "u14.41", lesson: 6, fr: "Je n'ai jamais dit ça !", en: "I never said that!", de: "Das habe ich nie gesagt!", alt: { en: ["I've never said that!"], de: ["Ich habe das nie gesagt!", "Das hab ich nie gesagt!"] } },
    { id: "u14.42", lesson: 6, fr: "Elle a appris l'anglais à l'école.", en: "She learned English at school.", de: "Sie hat in der Schule Englisch gelernt.", alt: { en: ["She learnt English at school.", "She has learned English at school.", "She has learnt English at school."], de: ["Sie lernte in der Schule Englisch.", "Sie hat Englisch in der Schule gelernt."] } },
    { id: "u14.43", lesson: 6, fr: "Vous n'avez jamais eu de chien ?", en: "Have you never had a dog?", de: "Habt ihr nie einen Hund gehabt?", alt: { fr: ["Est-ce que vous n'avez jamais eu de chien ?", "Tu n'as jamais eu de chien ?", "Est-ce que tu n'as jamais eu de chien ?"], en: ["Did you never have a dog?", "You've never had a dog?"], de: ["Hattet ihr nie einen Hund?", "Haben Sie nie einen Hund gehabt?", "Hatten Sie nie einen Hund?", "Hattet ihr noch nie einen Hund?", "Habt ihr noch nie einen Hund gehabt?"] } },
    // Lesson 7
    { id: "u14.44", lesson: 7, fr: "Hier, nous avons gagné le match !", en: "Yesterday, we won the match!", de: "Gestern haben wir das Spiel gewonnen!", alt: { fr: ["Nous avons gagné le match hier !", "Hier, on a gagné le match !", "On a gagné le match hier !"], en: ["We won the match yesterday!", "Yesterday, we won the game!", "We won the game yesterday!"], de: ["Wir haben gestern das Spiel gewonnen!", "Gestern gewannen wir das Spiel!", "Gestern haben wir das Match gewonnen!"] } },
    { id: "u14.45", lesson: 7, fr: "Ils ont perdu le match.", en: "They lost the match.", de: "Sie haben das Spiel verloren.", alt: { fr: ["Elles ont perdu le match."], en: ["They lost the game.", "They have lost the match.", "They have lost the game."], de: ["Sie verloren das Spiel.", "Sie haben das Match verloren."] } },
    { id: "u14.46", lesson: 7, fr: "J'ai perdu ma clé !", en: "I've lost my key!", de: "Ich habe meinen Schlüssel verloren!", alt: { fr: ["J'ai perdu ma clef !"], en: ["I lost my key!"] } },
    { id: "u14.47", lesson: 7, fr: "Qui a gagné ?", en: "Who won?", de: "Wer hat gewonnen?", alt: { en: ["Who has won?"], de: ["Wer gewann?"] } },
    { id: "u14.48", lesson: 7, fr: "Tu as regardé le match hier soir ?", en: "Did you watch the match last night?", de: "Hast du gestern Abend das Spiel gesehen?", alt: { fr: ["Est-ce que tu as regardé le match hier soir ?", "Hier soir, tu as regardé le match ?", "Vous avez regardé le match hier soir ?", "Est-ce que vous avez regardé le match hier soir ?"], en: ["Did you watch the game last night?", "Did you watch the match yesterday evening?"], de: ["Hast du gestern Abend das Spiel angeschaut?", "Hast du das Spiel gestern Abend gesehen?", "Hast du gestern Abend das Spiel geguckt?", "Hast du gestern Abend das Match gesehen?"] } },
    { id: "u14.49", lesson: 7, fr: "Nous n'avons pas gagné, mais nous avons bien joué.", en: "We didn't win, but we played well.", de: "Wir haben nicht gewonnen, aber wir haben gut gespielt.", alt: { fr: ["On n'a pas gagné, mais on a bien joué."], en: ["We haven't won, but we have played well."], de: ["Wir haben nicht gewonnen, aber gut gespielt."] } },
    { id: "u14.50", lesson: 7, fr: "Blob a mangé tous les croissants !", en: "Blob ate all the croissants!", de: "Blob hat alle Croissants gegessen!", alt: { en: ["Blob has eaten all the croissants!", "Blob ate all of the croissants!"], de: ["Blob aß alle Croissants!"] } },
    { id: "u14.51", lesson: 7, fr: "Léa a déjà fini, et toi ?", en: "Léa has already finished, and you?", de: "Léa ist schon fertig, und du?", alt: { fr: ["Léa a déjà fini, et vous ?"], en: ["Léa already finished, and you?", "Léa is already done, and you?", "Léa has finished already, and you?", "Léa has already finished, what about you?"], de: ["Léa ist bereits fertig, und du?"] } },
  ],
  drills: [
    { id: "u14.d1", lesson: 1, fr: "Hier, j'ai ___ une pizza.", options: ["mangé", "manger", "mange"], answer: 0, en: "Yesterday, I ate a pizza.", de: "Gestern habe ich eine Pizza gegessen.", why: tx("The past is **avoir** + participle. -er verbs end in **-é**: j'ai mang**é**.", "Die Vergangenheit ist **avoir** + Partizip. -er-Verben enden auf **-é**: j'ai mang**é**.") },
    { id: "u14.d2", lesson: 1, fr: "Hier, ___ mangé une crêpe.", options: ["j'ai", "je suis", "je"], answer: 0, en: "Yesterday, I ate a crêpe.", de: "Gestern habe ich eine Crêpe gegessen.", why: tx("Most verbs make the past with **avoir**: **j'ai** mangé, never «je suis mangé». And the helper can't be left out.", "Die meisten Verben bilden die Vergangenheit mit **avoir**: **j'ai** mangé, nie „je suis mangé“. Und der Helfer darf nicht fehlen.") },
    { id: "u14.d3", lesson: 1, fr: "Il ___ bu tout le lait !", options: ["a", "as", "est"], answer: 0, en: "He drank all the milk!", de: "Er hat die ganze Milch getrunken!", why: tx("With il: il **a** bu. Boire takes avoir, like almost every verb.", "Mit il: il **a** bu. Boire nimmt avoir, wie fast jedes Verb.") },
    { id: "u14.d4", lesson: 2, fr: "Tu as ___ quoi hier ?", options: ["fait", "faire", "fais"], answer: 0, en: "What did you do yesterday?", de: "Was hast du gestern gemacht?", why: tx("The participle of faire is **fait**: tu as **fait** quoi ?", "Das Partizip von faire ist **fait**: tu as **fait** quoi ?") },
    { id: "u14.d5", lesson: 2, fr: "Nous ___ joué aux jeux vidéo.", options: ["avons", "avez", "sommes"], answer: 0, en: "We played video games.", de: "Wir haben Videospiele gespielt.", why: tx("With nous: nous **avons** joué. Jouer takes avoir.", "Mit nous: nous **avons** joué. Jouer nimmt avoir.") },
    { id: "u14.d6", lesson: 2, fr: "Qu'est-ce que vous ___ fait ce matin ?", options: ["avez", "avons", "êtes"], answer: 0, en: "What did you do this morning?", de: "Was habt ihr heute Morgen gemacht?", why: tx("With vous: vous **avez** fait.", "Mit vous: vous **avez** fait.") },
    { id: "u14.d7", lesson: 3, fr: "J'ai ___ Hugo au parc.", options: ["vu", "voir", "vois"], answer: 0, en: "I saw Hugo in the park.", de: "Ich habe Hugo im Park gesehen.", why: tx("The participle of voir is short: **vu**.", "Das Partizip von voir ist kurz: **vu**.") },
    { id: "u14.d8", lesson: 3, fr: "Ce matin, j'ai ___ le bus.", options: ["pris", "prendre", "prends"], answer: 0, en: "This morning, I took the bus.", de: "Heute Morgen habe ich den Bus genommen.", why: tx("Prendre → **pris**: j'ai **pris** le bus.", "Prendre → **pris**: j'ai **pris** le bus.") },
    { id: "u14.d9", lesson: 3, fr: "Ils ___ vu la tour Eiffel !", options: ["ont", "sont", "a"], answer: 0, en: "They saw the Eiffel Tower!", de: "Sie haben den Eiffelturm gesehen!", why: tx("With ils: ils **ont** vu.", "Mit ils: ils **ont** vu.") },
    { id: "u14.d10", lesson: 4, fr: "Je ___ pas dormi !", options: ["n'ai", "ne ai", "ai"], answer: 0, en: "I didn't sleep!", de: "Ich habe nicht geschlafen!", why: tx("**Ne** … **pas** goes around **ai**, and ne shrinks to n': je **n'ai pas** dormi.", "**Ne** … **pas** steht um **ai** herum, und ne wird zu n': je **n'ai pas** dormi.") },
    { id: "u14.d11", lesson: 4, fr: "Tu ___ déjà lu ce livre ?", options: ["as", "es", "a"], answer: 0, en: "Have you already read this book?", de: "Hast du dieses Buch schon gelesen?", why: tx("With tu: tu **as** lu. Déjà goes between as and the participle.", "Mit tu: tu **as** lu. Déjà steht zwischen as und dem Partizip.") },
    { id: "u14.d12", lesson: 4, fr: "Blob a ___ sur le canapé.", options: ["dormi", "dormir", "dort"], answer: 0, en: "Blob slept on the sofa.", de: "Blob hat auf dem Sofa geschlafen.", why: tx("-ir verbs drop the r: dormir → **dormi**.", "-ir-Verben verlieren das r: dormir → **dormi**.") },
    { id: "u14.d13", lesson: 5, fr: "La semaine ___, j'ai acheté un vélo.", options: ["dernière", "dernier"], answer: 0, en: "Last week, I bought a bike.", de: "Letzte Woche habe ich ein Fahrrad gekauft.", why: tx("Semaine is feminine: la semaine **dernière**. But le week-end dernier.", "Semaine ist weiblich: la semaine **dernière**. Aber le week-end dernier.") },
    { id: "u14.d14", lesson: 5, fr: "Le week-end dernier, j'ai ___.", options: ["travaillé", "travailler", "travaille"], answer: 0, en: "Last weekend, I worked.", de: "Letztes Wochenende habe ich gearbeitet.", why: tx("After j'ai, the participle: travaill**é**. Travailler and travaillé sound the same, so watch the ending!", "Nach j'ai kommt das Partizip: travaill**é**. Travailler und travaillé klingen gleich, achte auf die Endung!") },
    { id: "u14.d15", lesson: 5, fr: "Vous avez ___ travaillé !", options: ["bien", "bon"], answer: 0, en: "You worked well!", de: "Ihr habt gut gearbeitet!", why: tx("How you did it: **bien** (well), and it goes before the participle: vous avez **bien** travaillé.", "Wie man es gemacht hat: **bien** (gut), und es steht vor dem Partizip: vous avez **bien** travaillé.") },
    { id: "u14.d16", lesson: 6, fr: "Je n'ai ___ mangé de poisson.", options: ["jamais", "pas jamais", "non"], answer: 0, en: "I've never eaten fish.", de: "Ich habe nie Fisch gegessen.", why: tx("**Jamais** takes the place of pas: je n'ai **jamais** mangé. Never both together!", "**Jamais** steht an der Stelle von pas: je n'ai **jamais** mangé. Nie beide zusammen!") },
    { id: "u14.d17", lesson: 6, fr: "Je n'ai jamais mangé ___ poisson.", options: ["de", "du", "des"], answer: 0, en: "I've never eaten fish.", de: "Ich habe nie Fisch gegessen.", why: tx("After ne … jamais, just like after ne … pas, du becomes **de**: jamais **de** poisson.", "Nach ne … jamais, genau wie nach ne … pas, wird du zu **de**: jamais **de** poisson.") },
    { id: "u14.d18", lesson: 6, fr: "Nous avons ___ de la chance !", options: ["eu", "avoir", "avons"], answer: 0, en: "We were lucky!", de: "Wir haben Glück gehabt!", why: tx("The participle of avoir is just **eu**: nous avons **eu** de la chance.", "Das Partizip von avoir ist einfach **eu**: nous avons **eu** de la chance.") },
    { id: "u14.d19", lesson: 7, fr: "Hier, nous avons ___ le match !", options: ["gagné", "gagner", "gagnés"], answer: 0, en: "Yesterday, we won the match!", de: "Gestern haben wir das Spiel gewonnen!", why: tx("With avoir, the participle doesn't change for nous: nous avons **gagné**, no s.", "Mit avoir ändert sich das Partizip bei nous nicht: nous avons **gagné**, ohne s.") },
    { id: "u14.d20", lesson: 7, fr: "Qui ___ gagné ?", options: ["a", "as", "est"], answer: 0, en: "Who won?", de: "Wer hat gewonnen?", why: tx("Qui takes the il form: qui **a** gagné ?", "Qui nimmt die il-Form: qui **a** gagné ?") },
    { id: "u14.d21", lesson: 7, fr: "Blob a mangé ___ les croissants !", options: ["tous", "tout", "toutes"], answer: 0, en: "Blob ate all the croissants!", de: "Blob hat alle Croissants gegessen!", why: tx("Croissants is masculine plural: **tous** les croissants.", "Croissants ist männlich und Plural: **tous** les croissants.") },
  ],
  dialogues: [
    {
      id: "u14.dialogue",
      lesson: 5,
      title: tx("Monday morning", "Montagmorgen"),
      lines: [
        { who: "lea", fr: "Salut, Hugo ! Tu as fait quoi le week-end dernier ?", en: "Hi, Hugo! What did you do last weekend?", de: "Hallo, Hugo! Was hast du letztes Wochenende gemacht?" },
        { who: "hugo", fr: "Samedi, j'ai joué au foot, et dimanche, j'ai travaillé.", en: "On Saturday I played football, and on Sunday I worked.", de: "Am Samstag habe ich Fußball gespielt, und am Sonntag habe ich gearbeitet." },
        { who: "lea", fr: "Travaillé ? Tu as fait tes devoirs ?", en: "Worked? Did you do your homework?", de: "Gearbeitet? Hast du deine Hausaufgaben gemacht?" },
        { who: "hugo", fr: "Non, j'ai aidé mon père au café.", en: "No, I helped my dad at the café.", de: "Nein, ich habe meinem Vater im Café geholfen." },
        { who: "lea", fr: "Et toi, Blob ? Tu as bien dormi ?", en: "And you, Blob? Did you sleep well?", de: "Und du, Blob? Hast du gut geschlafen?" },
        { who: "blob", fr: "Oui ! J'ai dormi, j'ai mangé, j'ai regardé la télé… et j'ai encore dormi.", en: "Yes! I slept, I ate, I watched TV… and I slept again.", de: "Ja! Ich habe geschlafen, gegessen, ferngesehen … und wieder geschlafen." },
        { who: "prof", fr: "Bonjour ! Vous avez fini les devoirs de maths ?", en: "Good morning! Have you finished the maths homework?", de: "Guten Morgen! Habt ihr die Mathe-Hausaufgaben fertig?" },
        { who: "blob", fr: "Les devoirs ? Euh… pas encore !", en: "The homework? Er… not yet!", de: "Die Hausaufgaben? Äh … noch nicht!" },
        { who: "lea", fr: "Moi, j'ai déjà fini !", en: "I've already finished!", de: "Ich bin schon fertig!" },
      ],
      questions: [
        { q: tx("What did Hugo do on Saturday?", "Was hat Hugo am Samstag gemacht?"), options: [tx("He played football.", "Er hat Fußball gespielt."), tx("He worked.", "Er hat gearbeitet."), tx("He slept.", "Er hat geschlafen.")], answer: 0 },
        { q: tx("Where did Hugo work on Sunday?", "Wo hat Hugo am Sonntag gearbeitet?"), options: [tx("At the café, helping his dad", "Im Café, er hat seinem Vater geholfen"), tx("At school", "In der Schule"), tx("At the supermarket", "Im Supermarkt")], answer: 0 },
        { q: tx("Who has already finished the maths homework?", "Wer ist mit den Mathe-Hausaufgaben schon fertig?"), options: ["Léa", "Blob", "Hugo"], answer: 0 },
      ],
    },
    {
      id: "u14.dialogue2",
      lesson: 7,
      title: tx("The big match", "Das große Spiel"),
      lines: [
        { who: "chloe", fr: "Hugo, tu as gagné le match hier ?", en: "Hugo, did you win the match yesterday?", de: "Hugo, hast du gestern das Spiel gewonnen?" },
        { who: "hugo", fr: "Non, nous avons perdu. Trois à zéro…", en: "No, we lost. Three–nil…", de: "Nein, wir haben verloren. Drei zu null …" },
        { who: "chloe", fr: "Oh non ! Et Blob, il a joué ?", en: "Oh no! And Blob, did he play?", de: "Oh nein! Und Blob, hat er gespielt?" },
        { who: "hugo", fr: "Oui, il a joué… mais il a mangé des croissants pendant le match !", en: "Yes, he played… but he ate croissants during the match!", de: "Ja, er hat gespielt … aber er hat während des Spiels Croissants gegessen!" },
        { who: "blob", fr: "J'ai eu faim ! Mais j'ai bien joué, non ?", en: "I got hungry! But I played well, didn't I?", de: "Ich hatte Hunger! Aber ich habe gut gespielt, oder?" },
        { who: "hugo", fr: "Non, Blob. Tu n'as jamais touché le ballon !", en: "No, Blob. You never touched the ball!", de: "Nein, Blob. Du hast den Ball nie berührt!" },
        { who: "chloe", fr: "Et après le match, vous avez mangé où ?", en: "And after the match, where did you eat?", de: "Und nach dem Spiel, wo habt ihr gegessen?" },
        { who: "hugo", fr: "Chez Léa. Nous avons mangé une pizza.", en: "At Léa's. We ate a pizza.", de: "Bei Léa. Wir haben eine Pizza gegessen." },
        { who: "blob", fr: "Oui, et là, j'ai gagné : j'ai mangé toute la pizza !", en: "Yes, and there I won: I ate the whole pizza!", de: "Ja, und da habe ich gewonnen: Ich habe die ganze Pizza gegessen!" },
      ],
      questions: [
        { q: tx("Did Hugo's team win?", "Hat Hugos Mannschaft gewonnen?"), options: [tx("No, they lost three–nil.", "Nein, sie haben drei zu null verloren."), tx("Yes, three–nil.", "Ja, drei zu null."), tx("Nobody won.", "Niemand hat gewonnen.")], answer: 0 },
        { q: tx("What did Blob do during the match?", "Was hat Blob während des Spiels gemacht?"), options: [tx("He ate croissants.", "Er hat Croissants gegessen."), tx("He scored a goal.", "Er hat ein Tor geschossen."), tx("He slept.", "Er hat geschlafen.")], answer: 0 },
        { q: tx("Where did they eat after the match?", "Wo haben sie nach dem Spiel gegessen?"), options: [tx("At Léa's", "Bei Léa"), tx("At the café", "Im Café"), tx("At the park", "Im Park")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("J'ai mangé: the past with avoir", "J'ai mangé: die Vergangenheit mit avoir"),
      body: tx(
        "To say what you did, take **avoir** in the present and add the **participle**: j'ai mangé (I ate, I have eaten). It works like the German Perfekt: ich habe gegessen.\n\n-er verbs are easy: drop -er, add **é**: manger → mang**é**, jouer → jou**é**, regarder → regard**é**. You hear the same sound as in the infinitive, so watch the spelling!",
        "Um zu erzählen, was du gemacht hast, nimmst du **avoir** in der Gegenwart und das **Partizip**: j'ai mangé (ich habe gegessen). Das funktioniert wie das deutsche Perfekt.\n\n-er-Verben sind leicht: -er weg, **é** dazu: manger → mang**é**, jouer → jou**é**, regarder → regard**é**. Es klingt wie der Infinitiv, achte also auf die Schreibung!",
      ),
      examples: [
        { fr: "Hier, j'ai mangé une pizza.", en: "Yesterday, I ate a pizza.", de: "Gestern habe ich eine Pizza gegessen." },
        { fr: "Nous avons joué aux jeux vidéo.", en: "We played video games.", de: "Wir haben Videospiele gespielt." },
        { fr: "Elle a parlé avec le professeur.", en: "She spoke to the teacher.", de: "Sie hat mit dem Lehrer gesprochen." },
      ],
      table: {
        head: [tx("person", "Person"), "avoir", tx("+ participle", "+ Partizip")],
        rows: [
          [tx("I", "ich"), "j'ai", "mangé"],
          [tx("you", "du"), "tu as", "joué"],
          [tx("he / she", "er / sie"), "il / elle a", "regardé"],
          [tx("we", "wir"), "nous avons", "parlé"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous avez", "travaillé"],
          [tx("they", "sie"), "ils / elles ont", "écouté"],
        ],
      },
    },
    {
      title: tx("Fait, vu, bu, pris: irregular participles", "Fait, vu, bu, pris: unregelmäßige Partizipien"),
      body: tx(
        "Some common verbs have short participles you just learn: **fait** (faire), **vu** (voir), **bu** (boire), **pris** (prendre), **lu** (lire), **eu** (avoir).\n\n-ir verbs like finir and dormir drop the r: **fini**, **dormi**. And the everyday question: **tu as fait quoi ?** What did you do?",
        "Einige häufige Verben haben kurze Partizipien, die man einfach lernt: **fait** (faire), **vu** (voir), **bu** (boire), **pris** (prendre), **lu** (lire), **eu** (avoir).\n\n-ir-Verben wie finir und dormir verlieren das r: **fini**, **dormi**. Und die Alltagsfrage: **tu as fait quoi ?** Was hast du gemacht?",
      ),
      examples: [
        { fr: "Tu as fait quoi hier ?", en: "What did you do yesterday?", de: "Was hast du gestern gemacht?" },
        { fr: "J'ai vu Hugo au parc.", en: "I saw Hugo in the park.", de: "Ich habe Hugo im Park gesehen." },
        { fr: "Ce matin, j'ai pris le bus.", en: "This morning, I took the bus.", de: "Heute Morgen habe ich den Bus genommen." },
      ],
      table: {
        head: [tx("infinitive", "Infinitiv"), tx("participle", "Partizip"), tx("meaning", "Bedeutung")],
        rows: [
          ["faire", "fait", tx("done / made", "gemacht")],
          ["voir", "vu", tx("seen", "gesehen")],
          ["boire", "bu", tx("drunk", "getrunken")],
          ["prendre", "pris", tx("taken", "genommen")],
          ["finir", "fini", tx("finished", "beendet")],
          ["dormir", "dormi", tx("slept", "geschlafen")],
        ],
      },
    },
    {
      title: tx("Not, already, not yet", "Nicht, schon, noch nicht"),
      body: tx(
        "In the negative, **ne** … **pas** goes around **avoir**, not around the participle: je **n'ai pas** mangé.\n\n**Déjà** (already) sits between avoir and the participle: j'ai **déjà** mangé. Its opposite is **pas encore** (not yet): je n'ai **pas encore** fini.",
        "Bei der Verneinung steht **ne** … **pas** um **avoir** herum, nicht um das Partizip: je **n'ai pas** mangé.\n\n**Déjà** (schon) steht zwischen avoir und dem Partizip: j'ai **déjà** mangé. Das Gegenteil ist **pas encore** (noch nicht): je n'ai **pas encore** fini.",
      ),
      examples: [
        { fr: "Je n'ai pas dormi !", en: "I didn't sleep!", de: "Ich habe nicht geschlafen!" },
        { fr: "J'ai déjà mangé.", en: "I've already eaten.", de: "Ich habe schon gegessen." },
        { fr: "Je n'ai pas encore fini.", en: "I haven't finished yet.", de: "Ich bin noch nicht fertig." },
      ],
    },
    {
      title: tx("Never: ne … jamais", "Nie: ne … jamais"),
      body: tx(
        "**Jamais** takes the place of pas: je n'ai **jamais** vu Paris. After it, un, une and du become **de**, just like after pas: je n'ai jamais mangé **de** poisson.\n\nLittle words like **bien**, **déjà** and **jamais** go before the participle: nous avons **bien** joué. And with avoir the participle stays the same for every person: nous avons gagn**é**, elles ont perd**u**.",
        "**Jamais** steht an der Stelle von pas: je n'ai **jamais** vu Paris. Danach werden un, une und du zu **de**, genau wie nach pas: je n'ai jamais mangé **de** poisson.\n\nKleine Wörter wie **bien**, **déjà** und **jamais** stehen vor dem Partizip: nous avons **bien** joué. Und mit avoir bleibt das Partizip für jede Person gleich: nous avons gagn**é**, elles ont perd**u**.",
      ),
      examples: [
        { fr: "Je n'ai jamais mangé de poisson.", en: "I've never eaten fish.", de: "Ich habe nie Fisch gegessen." },
        { fr: "Nous avons eu de la chance !", en: "We were lucky!", de: "Wir haben Glück gehabt!" },
        { fr: "Nous n'avons pas gagné, mais nous avons bien joué.", en: "We didn't win, but we played well.", de: "Wir haben nicht gewonnen, aber wir haben gut gespielt." },
      ],
    },
  ],
};
