import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 15: the passé composé with être (je suis allé), transport and countries. */
export const u15: Unit = {
  slug: "voyage",
  n: 15,
  cefr: "A2",
  title: tx("On the road", "Unterwegs"),
  goal: tx("Talk about trips and where you went", "Über Reisen erzählen und wohin du gefahren bist"),
  emoji: "🧳",
  words: [
    { id: "pp-alle", fr: "allé", en: "gone / went", de: "gegangen", alt: { de: ["gefahren"] }, kind: "verb", note: tx("From aller, with être: je suis allé. A girl writes je suis allée.", "Von aller, mit être: je suis allé. Ein Mädchen schreibt je suis allée.") },
    { id: "train", fr: "le train", en: "the train", de: "der Zug", g: "m", kind: "noun", emoji: "🚆", note: tx("By train: en train.", "Mit dem Zug: en train.") },
    { id: "avion", fr: "l'avion", en: "the plane", de: "das Flugzeug", alt: { en: ["the aeroplane"] }, g: "m", kind: "noun", emoji: "✈️", note: tx("By plane: en avion.", "Mit dem Flugzeug: en avion.") },
    { id: "voiture", fr: "la voiture", en: "the car", de: "das Auto", g: "f", kind: "noun", emoji: "🚗", note: tx("By car: en voiture. Inside a vehicle, it's en.", "Mit dem Auto: en voiture. In einem Fahrzeug heißt es en.") },
    { id: "vacances", fr: "les vacances", en: "the holidays", de: "die Ferien", alt: { en: ["the vacation"], de: ["der Urlaub"] }, g: "f", kind: "noun", emoji: "🏝️", note: tx("Always plural. On holiday: en vacances.", "Immer Plural. In den Ferien: en vacances.") },
    { id: "pp-parti", fr: "parti", en: "left", de: "abgefahren", alt: { en: ["gone"], de: ["losgefahren", "weggegangen", "gegangen"] }, kind: "verb", note: tx("From partir, with être: le train est parti.", "Von partir, mit être: le train est parti.") },
    { id: "pp-arrive", fr: "arrivé", en: "arrived", de: "angekommen", kind: "verb", note: tx("From arriver, with être: je suis arrivé.", "Von arriver, mit être: je suis arrivé.") },
    { id: "valise", fr: "la valise", en: "the suitcase", de: "der Koffer", g: "f", kind: "noun", emoji: "🧳" },
    { id: "billet", fr: "le billet", en: "the ticket", de: "die Fahrkarte", alt: { de: ["das Ticket"] }, g: "m", kind: "noun", emoji: "🎫", note: tx("Also a banknote: un billet de dix euros.", "Auch ein Geldschein: un billet de dix euros.") },
    { id: "a-l-heure", fr: "à l'heure", en: "on time", de: "pünktlich", kind: "phrase", note: tx("The opposite of en retard.", "Das Gegenteil von en retard.") },
    { id: "france", fr: "la France", en: "France", de: "Frankreich", g: "f", kind: "noun", note: tx("To or in France: en France, with no article.", "Nach oder in Frankreich: en France, ohne Artikel.") },
    { id: "allemagne", fr: "l'Allemagne", en: "Germany", de: "Deutschland", g: "f", kind: "noun", note: tx("Feminine, like most countries ending in e: en Allemagne.", "Weiblich, wie die meisten Länder auf -e: en Allemagne.") },
    { id: "pays", fr: "le pays", en: "the country", de: "das Land", g: "m", kind: "noun", emoji: "🗺️", note: tx("The same in the plural: les pays.", "Im Plural gleich: les pays.") },
    { id: "italie", fr: "l'Italie", en: "Italy", de: "Italien", g: "f", kind: "noun", note: tx("En Italie: to Italy, in Italy.", "En Italie: nach Italien, in Italien.") },
    { id: "espagne", fr: "l'Espagne", en: "Spain", de: "Spanien", g: "f", kind: "noun" },
    { id: "mer", fr: "la mer", en: "the sea", de: "das Meer", alt: { en: ["the seaside"] }, g: "f", kind: "noun", emoji: "🌊", note: tx("À la mer: at the seaside.", "À la mer: am Meer.") },
    { id: "montagne", fr: "la montagne", en: "the mountains", de: "die Berge", alt: { en: ["the mountain"], de: ["der Berg", "das Gebirge"] }, g: "f", kind: "noun", emoji: "⛰️", note: tx("À la montagne: in the mountains. French uses the singular.", "À la montagne: in den Bergen. Französisch nimmt die Einzahl.") },
    { id: "pp-reste", fr: "resté", en: "stayed", de: "geblieben", kind: "verb", note: tx("From rester, with être: elle est restée.", "Von rester, mit être: elle est restée.") },
    { id: "pp-rentre", fr: "rentré", en: "come home / came home", de: "nach Hause gekommen", alt: { en: ["got back", "come back"], de: ["zurückgekommen"] }, kind: "verb", note: tx("Rentrer is to go back home: je suis rentré à minuit.", "Rentrer heißt nach Hause zurückkommen: je suis rentré à minuit.") },
    { id: "pp-venu", fr: "venu", en: "come / came", de: "gekommen", kind: "verb", note: tx("From venir, with être: elle est venue.", "Von venir, mit être: elle est venue.") },
    { id: "voyage", fr: "le voyage", en: "the trip", de: "die Reise", alt: { en: ["the journey"] }, g: "m", kind: "noun", note: tx("Bon voyage ! Have a good trip!", "Bon voyage ! Gute Reise!") },
    { id: "annee-derniere", fr: "l'année dernière", en: "last year", de: "letztes Jahr", alt: { de: ["voriges Jahr"] }, kind: "phrase" },
    { id: "aeroport", fr: "l'aéroport", en: "the airport", de: "der Flughafen", g: "m", kind: "noun", emoji: "🛫" },
    { id: "passeport", fr: "le passeport", en: "the passport", de: "der Reisepass", alt: { de: ["der Pass"] }, g: "m", kind: "noun", emoji: "🛂" },
    { id: "bateau", fr: "le bateau", en: "the boat", de: "das Schiff", alt: { de: ["das Boot"] }, g: "m", kind: "noun", emoji: "⛵", note: tx("By boat: en bateau. Plural with x: les bateaux.", "Mit dem Schiff: en bateau. Plural mit x: les bateaux.") },
    { id: "camping", fr: "le camping", en: "the campsite", de: "der Campingplatz", alt: { en: ["camping"], de: ["das Camping"] }, g: "m", kind: "noun", emoji: "⛺", note: tx("Faire du camping: to go camping.", "Faire du camping: zelten, campen.") },
    { id: "hotel", fr: "l'hôtel", en: "the hotel", de: "das Hotel", g: "m", kind: "noun", emoji: "🏨", note: tx("The h is silent: l'hôtel, à l'hôtel.", "Das h ist stumm: l'hôtel, à l'hôtel.") },
  ],
  gloss: [
    { fr: "allée", en: "gone / went (feminine)", de: "gegangen / gefahren" },
    { fr: "allés", en: "gone / went (plural)", de: "gegangen / gefahren" },
    { fr: "allées", en: "gone / went (feminine plural)", de: "gegangen / gefahren" },
    { fr: "je suis allé", en: "I went", de: "ich bin gegangen / gefahren" },
    { fr: "je suis allée", en: "I went", de: "ich bin gegangen / gefahren" },
    { fr: "il est allé", en: "he went", de: "er ist gegangen / gefahren" },
    { fr: "elle est allée", en: "she went", de: "sie ist gegangen / gefahren" },
    { fr: "partie", en: "left (feminine)", de: "abgefahren / gegangen" },
    { fr: "partis", en: "left (plural)", de: "abgefahren / gegangen" },
    { fr: "parties", en: "left (feminine plural)", de: "abgefahren / gegangen" },
    { fr: "arrivée", en: "arrived (feminine)", de: "angekommen" },
    { fr: "arrivés", en: "arrived (plural)", de: "angekommen" },
    { fr: "venue", en: "come / came (feminine)", de: "gekommen" },
    { fr: "venues", en: "come / came (feminine plural)", de: "gekommen" },
    { fr: "venus", en: "come / came (plural)", de: "gekommen" },
    { fr: "restée", en: "stayed (feminine)", de: "geblieben" },
    { fr: "restés", en: "stayed (plural)", de: "geblieben" },
    { fr: "restées", en: "stayed (feminine plural)", de: "geblieben" },
    { fr: "rentrée", en: "come home (feminine)", de: "nach Hause gekommen" },
    { fr: "rentrés", en: "come home (plural)", de: "nach Hause gekommen" },
    { fr: "rentrées", en: "come home (feminine plural)", de: "nach Hause gekommen" },
    { fr: "venir", en: "to come", de: "kommen" },
    { fr: "oublié", en: "forgotten / forgot", de: "vergessen" },
    { fr: "valises", en: "suitcases", de: "Koffer" },
    { fr: "né", en: "born", de: "geboren" },
    { fr: "quel", en: "which / what", de: "welcher / welches" },
    { fr: "préfères", en: "prefer (you)", de: "magst lieber" },
    { fr: "taxi", en: "taxi", de: "Taxi" },
    { fr: "mari", en: "husband", de: "Mann" },
    { fr: "bon voyage", en: "have a good trip", de: "gute Reise" },
  ],
  lessons: [
    { title: tx("I went…", "Ich bin gefahren …"), words: ["pp-alle", "train", "avion", "voiture", "vacances"] },
    { title: tx("Leaving and arriving", "Abfahren und ankommen"), words: ["pp-parti", "pp-arrive", "valise", "billet", "a-l-heure"] },
    { title: tx("Countries", "Länder"), words: ["france", "allemagne", "pays", "italie", "espagne"] },
    { title: tx("Sea or mountains?", "Meer oder Berge?"), words: ["mer", "montagne", "pp-reste", "pp-rentre"] },
    { title: tx("Who came?", "Wer ist gekommen?"), words: ["pp-venu", "voyage", "annee-derniere"] },
    { title: tx("At the airport", "Am Flughafen"), words: ["aeroport", "passeport", "bateau"] },
    { title: tx("Camping or hotel?", "Camping oder Hotel?"), words: ["camping", "hotel"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u15.01", lesson: 1, fr: "Je suis allé à Paris en train.", en: "I went to Paris by train.", de: "Ich bin mit dem Zug nach Paris gefahren.", alt: { fr: ["Je suis allée à Paris en train."], en: ["I have gone to Paris by train.", "I took the train to Paris."], de: ["Ich fuhr mit dem Zug nach Paris.", "Ich bin nach Paris mit dem Zug gefahren.", "Ich bin mit dem Zug nach Paris gereist."] } },
    { id: "u15.02", lesson: 1, fr: "Elle est allée à Lyon en voiture.", en: "She went to Lyon by car.", de: "Sie ist mit dem Auto nach Lyon gefahren.", alt: { en: ["She has gone to Lyon by car.", "She drove to Lyon."], de: ["Sie fuhr mit dem Auto nach Lyon.", "Sie ist nach Lyon mit dem Auto gefahren."] } },
    { id: "u15.03", lesson: 1, fr: "Nous sommes allés à la plage à vélo.", en: "We went to the beach by bike.", de: "Wir sind mit dem Fahrrad an den Strand gefahren.", alt: { fr: ["Nous sommes allées à la plage à vélo.", "On est allés à la plage à vélo.", "On est allées à la plage à vélo.", "On est allé à la plage à vélo."], en: ["We cycled to the beach.", "We went to the beach by bicycle.", "We have gone to the beach by bike."], de: ["Wir fuhren mit dem Fahrrad an den Strand.", "Wir sind mit dem Rad an den Strand gefahren.", "Wir sind mit dem Fahrrad zum Strand gefahren."] } },
    { id: "u15.04", lesson: 1, fr: "Tu es allé où en vacances ?", en: "Where did you go on holiday?", de: "Wohin bist du in den Ferien gefahren?", alt: { fr: ["Tu es allée où en vacances ?", "Où es-tu allé en vacances ?", "Où es-tu allée en vacances ?", "Où est-ce que tu es allé en vacances ?", "Où est-ce que tu es allée en vacances ?", "Vous êtes allé où en vacances ?", "Vous êtes allée où en vacances ?", "Vous êtes allés où en vacances ?", "Vous êtes allées où en vacances ?", "Où êtes-vous allé en vacances ?", "Où êtes-vous allée en vacances ?", "Où êtes-vous allés en vacances ?", "Où êtes-vous allées en vacances ?"], en: ["Where did you go for your holidays?", "Where did you go on vacation?", "Where have you been on holiday?"], de: ["Wo warst du in den Ferien?", "Wo warst du im Urlaub?", "Wohin bist du in den Urlaub gefahren?", "Wo bist du in den Ferien gewesen?"] } },
    { id: "u15.05", lesson: 1, fr: "Ils sont allés à Marseille en avion.", en: "They went to Marseille by plane.", de: "Sie sind nach Marseille geflogen.", alt: { fr: ["Elles sont allées à Marseille en avion."], en: ["They flew to Marseille.", "They have gone to Marseille by plane."], de: ["Sie flogen nach Marseille.", "Sie sind mit dem Flugzeug nach Marseille geflogen.", "Sie sind mit dem Flugzeug nach Marseille gereist."] } },
    { id: "u15.06", lesson: 1, fr: "Pendant les vacances, je suis allée chez ma grand-mère.", en: "During the holidays, I went to my grandmother's.", de: "In den Ferien bin ich zu meiner Großmutter gefahren.", alt: { fr: ["Pendant les vacances, je suis allé chez ma grand-mère.", "Je suis allée chez ma grand-mère pendant les vacances.", "Je suis allé chez ma grand-mère pendant les vacances."], en: ["In the holidays, I went to my grandmother's.", "During the holidays, I went to my grandma's.", "I went to my grandmother's during the holidays."], de: ["In den Ferien bin ich zu meiner Oma gefahren.", "In den Ferien war ich bei meiner Großmutter.", "In den Ferien war ich bei meiner Oma.", "Während der Ferien bin ich zu meiner Großmutter gefahren.", "In den Ferien fuhr ich zu meiner Großmutter."] } },
    { id: "u15.07", lesson: 1, fr: "Hugo est allé à l'école à pied.", en: "Hugo went to school on foot.", de: "Hugo ist zu Fuß zur Schule gegangen.", alt: { en: ["Hugo walked to school.", "Hugo has gone to school on foot."], de: ["Hugo ging zu Fuß zur Schule.", "Hugo ist zu Fuß in die Schule gegangen."] } },
    // Lesson 2
    { id: "u15.08", lesson: 2, fr: "Le train est parti à huit heures.", en: "The train left at eight o'clock.", de: "Der Zug ist um acht Uhr abgefahren.", alt: { en: ["The train left at eight.", "The train left at 8 o'clock.", "The train left at 8.", "The train departed at eight o'clock."], de: ["Der Zug fuhr um acht Uhr ab.", "Der Zug ist um acht abgefahren.", "Der Zug ist um 8 Uhr abgefahren.", "Der Zug fuhr um 8 Uhr ab."] } },
    { id: "u15.09", lesson: 2, fr: "Nous sommes arrivés à Paris à midi.", en: "We arrived in Paris at midday.", de: "Wir sind um zwölf Uhr in Paris angekommen.", alt: { fr: ["Nous sommes arrivées à Paris à midi.", "On est arrivés à Paris à midi.", "On est arrivées à Paris à midi.", "On est arrivé à Paris à midi.", "À midi, nous sommes arrivés à Paris."], en: ["We arrived in Paris at noon.", "We got to Paris at midday.", "We got to Paris at noon.", "We arrived in Paris at twelve.", "We arrived in Paris at 12."], de: ["Wir kamen um zwölf Uhr in Paris an.", "Wir sind mittags in Paris angekommen.", "Wir sind um zwölf in Paris angekommen.", "Wir sind um 12 Uhr in Paris angekommen."] } },
    { id: "u15.10", lesson: 2, fr: "J'ai oublié ma valise !", en: "I forgot my suitcase!", de: "Ich habe meinen Koffer vergessen!", alt: { en: ["I've forgotten my suitcase!"], de: ["Ich vergaß meinen Koffer!"] } },
    { id: "u15.11", lesson: 2, fr: "Tu as ton billet ?", en: "Do you have your ticket?", de: "Hast du deine Fahrkarte?", alt: { fr: ["Est-ce que tu as ton billet ?", "As-tu ton billet ?", "Vous avez votre billet ?", "Est-ce que vous avez votre billet ?", "Avez-vous votre billet ?"], en: ["Have you got your ticket?"], de: ["Hast du dein Ticket?"] } },
    { id: "u15.12", lesson: 2, fr: "Le bus n'est pas arrivé à l'heure.", en: "The bus didn't arrive on time.", de: "Der Bus ist nicht pünktlich angekommen.", alt: { en: ["The bus wasn't on time.", "The bus hasn't arrived on time."], de: ["Der Bus kam nicht pünktlich an.", "Der Bus war nicht pünktlich."] } },
    { id: "u15.13", lesson: 2, fr: "Elle est partie avec deux valises.", en: "She left with two suitcases.", de: "Sie ist mit zwei Koffern abgereist.", alt: { en: ["She has left with two suitcases.", "She left with 2 suitcases."], de: ["Sie ist mit zwei Koffern weggefahren.", "Sie ist mit zwei Koffern losgefahren.", "Sie ist mit zwei Koffern gegangen.", "Sie reiste mit zwei Koffern ab.", "Sie ist mit 2 Koffern abgereist."] } },
    { id: "u15.14", lesson: 2, fr: "Je suis arrivé à l'heure !", en: "I arrived on time!", de: "Ich bin pünktlich angekommen!", alt: { fr: ["Je suis arrivée à l'heure !"], en: ["I got here on time!", "I have arrived on time!", "I was on time!"], de: ["Ich kam pünktlich an!", "Ich war pünktlich!"] } },
    // Lesson 3
    { id: "u15.15", lesson: 3, fr: "Je suis allée en Italie.", en: "I went to Italy.", de: "Ich bin nach Italien gefahren.", alt: { fr: ["Je suis allé en Italie."], en: ["I have been to Italy.", "I have gone to Italy."], de: ["Ich war in Italien.", "Ich bin in Italien gewesen.", "Ich bin nach Italien gereist.", "Ich fuhr nach Italien."] } },
    { id: "u15.16", lesson: 3, fr: "La France est un grand pays.", en: "France is a big country.", de: "Frankreich ist ein großes Land.", alt: { en: ["France is a large country."] } },
    { id: "u15.17", lesson: 3, fr: "Ils sont partis en Allemagne.", en: "They left for Germany.", de: "Sie sind nach Deutschland gefahren.", alt: { fr: ["Elles sont parties en Allemagne."], en: ["They went to Germany.", "They have left for Germany.", "They have gone to Germany."], de: ["Sie fuhren nach Deutschland.", "Sie sind nach Deutschland abgereist.", "Sie sind nach Deutschland aufgebrochen."] } },
    { id: "u15.18", lesson: 3, fr: "Tu es allé en Espagne ?", en: "Did you go to Spain?", de: "Bist du nach Spanien gefahren?", alt: { fr: ["Tu es allée en Espagne ?", "Est-ce que tu es allé en Espagne ?", "Est-ce que tu es allée en Espagne ?", "Es-tu allé en Espagne ?", "Es-tu allée en Espagne ?", "Vous êtes allé en Espagne ?", "Vous êtes allée en Espagne ?", "Vous êtes allés en Espagne ?", "Vous êtes allées en Espagne ?", "Est-ce que vous êtes allés en Espagne ?", "Êtes-vous allés en Espagne ?"], en: ["Have you been to Spain?", "Have you gone to Spain?"], de: ["Warst du in Spanien?", "Bist du in Spanien gewesen?", "Fuhrst du nach Spanien?"] } },
    { id: "u15.19", lesson: 3, fr: "Nous habitons en France, à Lyon.", en: "We live in France, in Lyon.", de: "Wir wohnen in Frankreich, in Lyon.", alt: { fr: ["On habite en France, à Lyon."] } },
    { id: "u15.20", lesson: 3, fr: "Mon père est allemand, il est né en Allemagne.", en: "My father is German, he was born in Germany.", de: "Mein Vater ist Deutscher, er ist in Deutschland geboren.", alt: { en: ["My dad is German, he was born in Germany."], de: ["Mein Vater ist Deutscher, er wurde in Deutschland geboren.", "Mein Vater ist deutsch, er ist in Deutschland geboren."] } },
    { id: "u15.21", lesson: 3, fr: "Quel pays ? L'Espagne ou l'Italie ?", en: "Which country? Spain or Italy?", de: "Welches Land? Spanien oder Italien?", alt: { en: ["What country? Spain or Italy?"] } },
    // Lesson 4
    { id: "u15.22", lesson: 4, fr: "Nous sommes allés à la mer.", en: "We went to the seaside.", de: "Wir sind ans Meer gefahren.", alt: { fr: ["Nous sommes allées à la mer.", "On est allés à la mer.", "On est allées à la mer.", "On est allé à la mer."], en: ["We went to the sea.", "We went to the coast.", "We have been to the seaside."], de: ["Wir fuhren ans Meer.", "Wir waren am Meer.", "Wir sind an das Meer gefahren."] } },
    { id: "u15.23", lesson: 4, fr: "Elle est restée à la montagne.", en: "She stayed in the mountains.", de: "Sie ist in den Bergen geblieben.", alt: { en: ["She has stayed in the mountains."], de: ["Sie blieb in den Bergen."] } },
    { id: "u15.24", lesson: 4, fr: "Je suis rentré à minuit.", en: "I got home at midnight.", de: "Ich bin um Mitternacht nach Hause gekommen.", alt: { fr: ["Je suis rentrée à minuit."], en: ["I came home at midnight.", "I came back at midnight.", "I went home at midnight.", "I got back at midnight."], de: ["Ich kam um Mitternacht nach Hause.", "Ich bin um Mitternacht zurückgekommen.", "Ich kam um Mitternacht zurück.", "Ich bin um Mitternacht heimgekommen."] } },
    { id: "u15.25", lesson: 4, fr: "Ils sont restés une semaine à la mer.", en: "They stayed at the seaside for a week.", de: "Sie sind eine Woche am Meer geblieben.", alt: { fr: ["Elles sont restées une semaine à la mer."], en: ["They stayed by the sea for a week.", "They stayed a week at the seaside.", "They stayed at the sea for a week.", "They stayed for a week at the seaside."], de: ["Sie blieben eine Woche am Meer."] } },
    { id: "u15.26", lesson: 4, fr: "Tu préfères la mer ou la montagne ?", en: "Do you prefer the sea or the mountains?", de: "Magst du lieber das Meer oder die Berge?", alt: { fr: ["Est-ce que tu préfères la mer ou la montagne ?", "Vous préférez la mer ou la montagne ?", "Est-ce que vous préférez la mer ou la montagne ?"], en: ["Do you prefer the seaside or the mountains?", "Which do you prefer, the sea or the mountains?"], de: ["Was magst du lieber, das Meer oder die Berge?", "Bevorzugst du das Meer oder die Berge?"] } },
    { id: "u15.27", lesson: 4, fr: "Nous sommes rentrés en train.", en: "We came back by train.", de: "Wir sind mit dem Zug zurückgefahren.", alt: { fr: ["Nous sommes rentrées en train.", "On est rentrés en train.", "On est rentrées en train.", "On est rentré en train."], en: ["We went home by train.", "We got back by train.", "We have come back by train."], de: ["Wir fuhren mit dem Zug zurück.", "Wir sind mit dem Zug nach Hause gefahren.", "Wir sind mit dem Zug heimgefahren."] } },
    { id: "u15.28", lesson: 4, fr: "Je ne suis pas resté à la maison.", en: "I didn't stay at home.", de: "Ich bin nicht zu Hause geblieben.", alt: { fr: ["Je ne suis pas restée à la maison.", "Je ne suis pas resté chez moi.", "Je ne suis pas restée chez moi."], en: ["I didn't stay home.", "I haven't stayed at home."], de: ["Ich blieb nicht zu Hause."] } },
    // Lesson 5
    { id: "u15.29", lesson: 5, fr: "Chloé est venue de Lyon en train.", en: "Chloé came from Lyon by train.", de: "Chloé ist mit dem Zug aus Lyon gekommen.", alt: { en: ["Chloé has come from Lyon by train."], de: ["Chloé kam mit dem Zug aus Lyon."] } },
    { id: "u15.30", lesson: 5, fr: "L'année dernière, je suis allé en Espagne.", en: "Last year, I went to Spain.", de: "Letztes Jahr bin ich nach Spanien gefahren.", alt: { fr: ["L'année dernière, je suis allée en Espagne.", "Je suis allé en Espagne l'année dernière.", "Je suis allée en Espagne l'année dernière."], en: ["I went to Spain last year."], de: ["Letztes Jahr war ich in Spanien.", "Ich bin letztes Jahr nach Spanien gefahren.", "Ich war letztes Jahr in Spanien.", "Letztes Jahr fuhr ich nach Spanien.", "Voriges Jahr bin ich nach Spanien gefahren."] } },
    { id: "u15.31", lesson: 5, fr: "Bon voyage, Chloé !", en: "Have a good trip, Chloé!", de: "Gute Reise, Chloé!", alt: { en: ["Have a nice trip, Chloé!", "Safe travels, Chloé!", "Have a good journey, Chloé!"] } },
    { id: "u15.32", lesson: 5, fr: "Elles sont venues en voiture.", en: "They came by car.", de: "Sie sind mit dem Auto gekommen.", alt: { fr: ["Ils sont venus en voiture."], en: ["They have come by car."], de: ["Sie kamen mit dem Auto."] } },
    { id: "u15.33", lesson: 5, fr: "Mes grands-parents sont venus l'année dernière.", en: "My grandparents came last year.", de: "Meine Großeltern sind letztes Jahr gekommen.", alt: { fr: ["L'année dernière, mes grands-parents sont venus."], en: ["My grandparents visited last year.", "Last year, my grandparents came."], de: ["Meine Großeltern kamen letztes Jahr.", "Letztes Jahr sind meine Großeltern gekommen.", "Meine Großeltern sind letztes Jahr zu Besuch gekommen."] } },
    { id: "u15.34", lesson: 5, fr: "Nous avons fait un grand voyage.", en: "We went on a big trip.", de: "Wir haben eine große Reise gemacht.", alt: { fr: ["On a fait un grand voyage."], en: ["We took a big trip.", "We went on a long trip.", "We made a long journey.", "We have been on a big trip."], de: ["Wir machten eine große Reise."] } },
    { id: "u15.35", lesson: 5, fr: "Pourquoi tu n'es pas venu ?", en: "Why didn't you come?", de: "Warum bist du nicht gekommen?", alt: { fr: ["Pourquoi tu n'es pas venue ?", "Pourquoi n'es-tu pas venu ?", "Pourquoi n'es-tu pas venue ?", "Pourquoi est-ce que tu n'es pas venu ?", "Pourquoi est-ce que tu n'es pas venue ?", "Pourquoi vous n'êtes pas venu ?", "Pourquoi vous n'êtes pas venue ?", "Pourquoi vous n'êtes pas venus ?", "Pourquoi vous n'êtes pas venues ?", "Pourquoi n'êtes-vous pas venus ?"], en: ["Why haven't you come?"], de: ["Warum kamst du nicht?"] } },
    // Lesson 6
    { id: "u15.36", lesson: 6, fr: "Nous sommes arrivés à l'aéroport en retard.", en: "We arrived at the airport late.", de: "Wir sind zu spät am Flughafen angekommen.", alt: { fr: ["Nous sommes arrivées à l'aéroport en retard.", "Nous sommes arrivés en retard à l'aéroport.", "On est arrivés à l'aéroport en retard.", "On est arrivées à l'aéroport en retard.", "On est arrivé à l'aéroport en retard."], en: ["We got to the airport late.", "We arrived late at the airport."], de: ["Wir kamen zu spät am Flughafen an.", "Wir sind verspätet am Flughafen angekommen."] } },
    { id: "u15.37", lesson: 6, fr: "Où est mon passeport ?", en: "Where is my passport?", de: "Wo ist mein Pass?", alt: { fr: ["Mon passeport est où ?"], de: ["Wo ist mein Reisepass?"] } },
    { id: "u15.38", lesson: 6, fr: "Ils sont partis en bateau.", en: "They left by boat.", de: "Sie sind mit dem Schiff abgefahren.", alt: { fr: ["Elles sont parties en bateau."], en: ["They went by boat.", "They have left by boat."], de: ["Sie fuhren mit dem Schiff ab.", "Sie sind mit dem Schiff gefahren.", "Sie sind mit dem Boot gefahren.", "Sie sind mit dem Boot abgefahren."] } },
    { id: "u15.39", lesson: 6, fr: "Tu n'as pas oublié ton passeport ?", en: "You haven't forgotten your passport?", de: "Du hast deinen Pass nicht vergessen?", alt: { fr: ["Vous n'avez pas oublié votre passeport ?"], en: ["Haven't you forgotten your passport?", "You didn't forget your passport?", "Didn't you forget your passport?"], de: ["Hast du deinen Pass nicht vergessen?", "Du hast deinen Reisepass nicht vergessen?"] } },
    { id: "u15.40", lesson: 6, fr: "L'avion est parti sans nous !", en: "The plane left without us!", de: "Das Flugzeug ist ohne uns abgeflogen!", alt: { en: ["The plane has left without us!", "The plane took off without us!"], de: ["Das Flugzeug flog ohne uns ab!", "Das Flugzeug ist ohne uns gestartet!"] } },
    { id: "u15.41", lesson: 6, fr: "Elle est rentrée d'Italie en bateau.", en: "She came back from Italy by boat.", de: "Sie ist mit dem Schiff aus Italien zurückgekommen.", alt: { en: ["She returned from Italy by boat.", "She has come back from Italy by boat."], de: ["Sie kam mit dem Schiff aus Italien zurück.", "Sie ist mit dem Boot aus Italien zurückgekommen."] } },
    { id: "u15.42", lesson: 6, fr: "Vous êtes allés à l'aéroport en taxi ?", en: "Did you go to the airport by taxi?", de: "Seid ihr mit dem Taxi zum Flughafen gefahren?", alt: { fr: ["Vous êtes allé à l'aéroport en taxi ?", "Vous êtes allée à l'aéroport en taxi ?", "Vous êtes allées à l'aéroport en taxi ?", "Est-ce que vous êtes allés à l'aéroport en taxi ?", "Êtes-vous allés à l'aéroport en taxi ?", "Tu es allé à l'aéroport en taxi ?", "Tu es allée à l'aéroport en taxi ?", "Est-ce que tu es allé à l'aéroport en taxi ?", "Est-ce que tu es allée à l'aéroport en taxi ?"], en: ["Did you take a taxi to the airport?", "Have you gone to the airport by taxi?"], de: ["Sind Sie mit dem Taxi zum Flughafen gefahren?", "Fuhrt ihr mit dem Taxi zum Flughafen?"] } },
    { id: "u15.43", lesson: 6, fr: "Mon passeport est resté à la maison !", en: "My passport stayed at home!", de: "Mein Pass ist zu Hause geblieben!", alt: { en: ["My passport was left at home!", "I left my passport at home!"], de: ["Mein Pass blieb zu Hause!", "Mein Reisepass ist zu Hause geblieben!"] } },
    // Lesson 7
    { id: "u15.44", lesson: 7, fr: "Nous avons fait du camping à la montagne.", en: "We went camping in the mountains.", de: "Wir haben in den Bergen gezeltet.", alt: { fr: ["On a fait du camping à la montagne."], en: ["We camped in the mountains.", "We did some camping in the mountains.", "We have been camping in the mountains."], de: ["Wir waren in den Bergen zelten.", "Wir haben in den Bergen gecampt.", "Wir waren in den Bergen campen."] } },
    { id: "u15.45", lesson: 7, fr: "Ils sont restés à l'hôtel.", en: "They stayed at the hotel.", de: "Sie sind im Hotel geblieben.", alt: { fr: ["Elles sont restées à l'hôtel."], en: ["They stayed in the hotel.", "They stayed in a hotel.", "They stayed at a hotel.", "They have stayed at the hotel."], de: ["Sie blieben im Hotel.", "Sie haben im Hotel übernachtet."] } },
    { id: "u15.46", lesson: 7, fr: "L'hôtel est à côté de la mer.", en: "The hotel is next to the sea.", de: "Das Hotel ist am Meer.", alt: { en: ["The hotel is by the sea.", "The hotel is beside the sea."], de: ["Das Hotel liegt am Meer.", "Das Hotel ist neben dem Meer."] } },
    { id: "u15.47", lesson: 7, fr: "Je suis allée au camping avec ma cousine.", en: "I went to the campsite with my cousin.", de: "Ich bin mit meiner Cousine auf den Campingplatz gefahren.", alt: { fr: ["Je suis allé au camping avec ma cousine."], en: ["I went camping with my cousin.", "I have been to the campsite with my cousin."], de: ["Ich war mit meiner Cousine auf dem Campingplatz.", "Ich war mit meiner Cousine campen.", "Ich bin mit meiner Cousine zum Campingplatz gefahren."] } },
    { id: "u15.48", lesson: 7, fr: "Les filles sont rentrées tard.", en: "The girls came home late.", de: "Die Mädchen sind spät nach Hause gekommen.", alt: { en: ["The girls got home late.", "The girls came back late.", "The girls got back late.", "The girls have come home late."], de: ["Die Mädchen kamen spät nach Hause.", "Die Mädchen sind spät zurückgekommen."] } },
    { id: "u15.49", lesson: 7, fr: "Blob n'est pas venu : il est resté à l'hôtel.", en: "Blob didn't come: he stayed at the hotel.", de: "Blob ist nicht gekommen: Er ist im Hotel geblieben.", alt: { en: ["Blob hasn't come: he has stayed at the hotel."], de: ["Blob kam nicht: Er blieb im Hotel."] } },
    { id: "u15.50", lesson: 7, fr: "Vous êtes partis à quelle heure ?", en: "What time did you leave?", de: "Um wie viel Uhr seid ihr losgefahren?", alt: { fr: ["Vous êtes parti à quelle heure ?", "Vous êtes partie à quelle heure ?", "Vous êtes parties à quelle heure ?", "À quelle heure êtes-vous partis ?", "À quelle heure est-ce que vous êtes partis ?", "Tu es parti à quelle heure ?", "Tu es partie à quelle heure ?", "À quelle heure es-tu parti ?", "À quelle heure es-tu partie ?"], en: ["At what time did you leave?", "When did you leave?"], de: ["Wann seid ihr losgefahren?", "Wann seid ihr abgefahren?", "Um wie viel Uhr sind Sie losgefahren?"] } },
  ],
  drills: [
    { id: "u15.d1", lesson: 1, fr: "___ allé à Paris en train.", options: ["Je suis", "J'ai", "Je"], answer: 0, en: "I went to Paris by train.", de: "Ich bin mit dem Zug nach Paris gefahren.", why: tx("Aller makes its past with **être**: **je suis** allé, never «j'ai allé».", "Aller bildet die Vergangenheit mit **être**: **je suis** allé, nie „j'ai allé“.") },
    { id: "u15.d2", lesson: 1, fr: "Elle est ___ à Lyon en voiture.", options: ["allée", "allé", "allés"], answer: 0, en: "She went to Lyon by car.", de: "Sie ist mit dem Auto nach Lyon gefahren.", why: tx("With être, the participle agrees like an adjective: elle est all**ée**, with an extra e.", "Mit être passt sich das Partizip an wie ein Adjektiv: elle est all**ée**, mit einem e mehr.") },
    { id: "u15.d3", lesson: 1, fr: "Ils sont allés à Marseille ___ avion.", options: ["en", "à", "au"], answer: 0, en: "They went to Marseille by plane.", de: "Sie sind nach Marseille geflogen.", why: tx("Inside a vehicle: **en** avion, en train, en voiture. On a bike or on foot: à vélo, à pied.", "In einem Fahrzeug: **en** avion, en train, en voiture. Auf dem Fahrrad oder zu Fuß: à vélo, à pied.") },
    { id: "u15.d4", lesson: 2, fr: "Le train est ___ à huit heures.", options: ["parti", "partir", "partis"], answer: 0, en: "The train left at eight o'clock.", de: "Der Zug ist um acht Uhr abgefahren.", why: tx("Partir takes être, and the train is one, masculine: il est **parti**.", "Partir nimmt être, und der Zug ist einer, männlich: il est **parti**.") },
    { id: "u15.d5", lesson: 2, fr: "Nous ___ arrivés à Paris à midi.", options: ["sommes", "avons", "êtes"], answer: 0, en: "We arrived in Paris at midday.", de: "Wir sind um zwölf Uhr in Paris angekommen.", why: tx("Arriver takes **être**: nous **sommes** arrivés.", "Arriver nimmt **être**: nous **sommes** arrivés.") },
    { id: "u15.d6", lesson: 2, fr: "Elle est ___ avec deux valises.", options: ["partie", "parti", "parties"], answer: 0, en: "She left with two suitcases.", de: "Sie ist mit zwei Koffern abgereist.", why: tx("Elle: add an e: elle est part**ie**.", "Elle: ein e dazu: elle est part**ie**.") },
    { id: "u15.d7", lesson: 3, fr: "Je suis allée ___ Italie.", options: ["en", "à", "au"], answer: 0, en: "I went to Italy.", de: "Ich bin nach Italien gefahren.", why: tx("Most countries are feminine and take **en**: en France, **en** Italie. Towns take à: à Paris.", "Die meisten Länder sind weiblich und nehmen **en**: en France, **en** Italie. Städte nehmen à: à Paris.") },
    { id: "u15.d8", lesson: 3, fr: "Ils sont partis en ___.", options: ["Allemagne", "l'Allemagne"], answer: 0, en: "They left for Germany.", de: "Sie sind nach Deutschland gefahren.", why: tx("After en, no article: en **Allemagne**, en France.", "Nach en kein Artikel: en **Allemagne**, en France.") },
    { id: "u15.d9", lesson: 3, fr: "La France est ___ grand pays.", options: ["un", "une"], answer: 0, en: "France is a big country.", de: "Frankreich ist ein großes Land.", why: tx("Pays is masculine: **un** grand pays, even if la France is feminine.", "Pays ist männlich: **un** grand pays, auch wenn la France weiblich ist.") },
    { id: "u15.d10", lesson: 4, fr: "Elle est ___ à la montagne.", options: ["restée", "resté", "restés"], answer: 0, en: "She stayed in the mountains.", de: "Sie ist in den Bergen geblieben.", why: tx("Elle: rest**ée**, with an extra e.", "Elle: rest**ée**, mit einem e mehr.") },
    { id: "u15.d11", lesson: 4, fr: "Je ___ rentré à minuit.", options: ["suis", "ai", "es"], answer: 0, en: "I got home at midnight.", de: "Ich bin um Mitternacht nach Hause gekommen.", why: tx("Rentrer (to come home) takes **être**: je **suis** rentré.", "Rentrer (nach Hause kommen) nimmt **être**: je **suis** rentré.") },
    { id: "u15.d12", lesson: 4, fr: "Ils sont ___ une semaine à la mer.", options: ["restés", "resté", "restées"], answer: 0, en: "They stayed at the seaside for a week.", de: "Sie sind eine Woche am Meer geblieben.", why: tx("Ils: add an s: ils sont rest**és**. Only elles takes -ées.", "Ils: ein s dazu: ils sont rest**és**. Nur elles bekommt -ées.") },
    { id: "u15.d13", lesson: 5, fr: "Chloé est ___ de Lyon en train.", options: ["venue", "venu", "venues"], answer: 0, en: "Chloé came from Lyon by train.", de: "Chloé ist mit dem Zug aus Lyon gekommen.", why: tx("Venir takes être, and Chloé is a girl: elle est ven**ue**.", "Venir nimmt être, und Chloé ist ein Mädchen: elle est ven**ue**.") },
    { id: "u15.d14", lesson: 5, fr: "Elles sont ___ en voiture.", options: ["venues", "venus", "venue"], answer: 0, en: "They came by car.", de: "Sie sind mit dem Auto gekommen.", why: tx("Elles: e for feminine, s for plural: ven**ues**.", "Elles: e für weiblich, s für Plural: ven**ues**.") },
    { id: "u15.d15", lesson: 5, fr: "Nous ___ fait un grand voyage.", options: ["avons", "sommes"], answer: 0, en: "We went on a big trip.", de: "Wir haben eine große Reise gemacht.", why: tx("Faire takes **avoir**: nous **avons** fait. Only verbs of coming and going take être.", "Faire nimmt **avoir**: nous **avons** fait. Nur Verben der Bewegung nehmen être.") },
    { id: "u15.d16", lesson: 6, fr: "Nous sommes arrivés à ___ en retard.", options: ["l'aéroport", "le aéroport", "la aéroport"], answer: 0, en: "We arrived at the airport late.", de: "Wir sind zu spät am Flughafen angekommen.", why: tx("Aéroport starts with a vowel: **l'aéroport**.", "Aéroport beginnt mit einem Vokal: **l'aéroport**.") },
    { id: "u15.d17", lesson: 6, fr: "Tu n'as pas oublié ___ passeport ?", options: ["ton", "ta"], answer: 0, en: "You haven't forgotten your passport?", de: "Du hast deinen Pass nicht vergessen?", why: tx("Passeport is masculine: **ton** passeport.", "Passeport ist männlich: **ton** passeport.") },
    { id: "u15.d18", lesson: 6, fr: "Mon passeport est ___ à la maison !", options: ["resté", "restée", "restés"], answer: 0, en: "My passport stayed at home!", de: "Mein Pass ist zu Hause geblieben!", why: tx("The participle agrees with the subject: mon passeport (masculine, one) est rest**é**.", "Das Partizip passt sich dem Subjekt an: mon passeport (männlich, einer) est rest**é**.") },
    { id: "u15.d19", lesson: 7, fr: "Ils sont restés ___ l'hôtel.", options: ["à", "en", "au"], answer: 0, en: "They stayed at the hotel.", de: "Sie sind im Hotel geblieben.", why: tx("At the hotel: **à** l'hôtel.", "Im Hotel: **à** l'hôtel.") },
    { id: "u15.d20", lesson: 7, fr: "Les filles sont ___ tard.", options: ["rentrées", "rentrés", "rentré"], answer: 0, en: "The girls came home late.", de: "Die Mädchen sind spät nach Hause gekommen.", why: tx("Les filles: feminine plural, so rentr**ées**.", "Les filles: weiblich und Plural, also rentr**ées**.") },
    { id: "u15.d21", lesson: 7, fr: "Blob ___ pas venu : il est resté à l'hôtel.", options: ["n'est", "n'a", "ne est"], answer: 0, en: "Blob didn't come: he stayed at the hotel.", de: "Blob ist nicht gekommen: Er ist im Hotel geblieben.", why: tx("Venir takes être, and ne … pas goes around it: Blob **n'est** pas venu.", "Venir nimmt être, und ne … pas steht darum herum: Blob **n'est** pas venu.") },
  ],
  dialogues: [
    {
      id: "u15.dialogue",
      lesson: 5,
      title: tx("Chloé's suitcase", "Chloés Koffer"),
      lines: [
        { who: "hugo", fr: "Chloé, tu es venue comment de Lyon ?", en: "Chloé, how did you get here from Lyon?", de: "Chloé, wie bist du aus Lyon gekommen?" },
        { who: "chloe", fr: "Je suis venue en train. Je suis partie à sept heures.", en: "I came by train. I left at seven o'clock.", de: "Ich bin mit dem Zug gekommen. Ich bin um sieben Uhr abgefahren." },
        { who: "hugo", fr: "Et tu es arrivée à quelle heure ?", en: "And what time did you arrive?", de: "Und um wie viel Uhr bist du angekommen?" },
        { who: "chloe", fr: "Je suis arrivée à midi. Mais ma valise n'est pas arrivée !", en: "I arrived at midday. But my suitcase didn't arrive!", de: "Ich bin um zwölf angekommen. Aber mein Koffer ist nicht angekommen!" },
        { who: "lea", fr: "Oh non ! Elle est où, ta valise ?", en: "Oh no! Where's your suitcase?", de: "Oh nein! Wo ist dein Koffer?" },
        { who: "chloe", fr: "Elle est restée dans le train… elle est partie à Marseille !", en: "It stayed on the train… it went off to Marseille!", de: "Er ist im Zug geblieben … er ist nach Marseille gefahren!" },
        { who: "blob", fr: "Ta valise est allée en vacances à la mer !", en: "Your suitcase went on holiday to the seaside!", de: "Dein Koffer ist in den Urlaub ans Meer gefahren!" },
        { who: "hugo", fr: "Et tes vêtements ?", en: "And your clothes?", de: "Und deine Kleider?" },
        { who: "chloe", fr: "Léa est gentille : je porte ses vêtements !", en: "Léa is kind: I'm wearing her clothes!", de: "Léa ist lieb: Ich trage ihre Kleider!" },
      ],
      questions: [
        { q: tx("How did Chloé come from Lyon?", "Wie ist Chloé aus Lyon gekommen?"), options: [tx("By train", "Mit dem Zug"), tx("By car", "Mit dem Auto"), tx("By plane", "Mit dem Flugzeug")], answer: 0 },
        { q: tx("Where is Chloé's suitcase?", "Wo ist Chloés Koffer?"), options: [tx("It stayed on the train and went to Marseille.", "Er ist im Zug geblieben und nach Marseille gefahren."), tx("At Léa's house", "Bei Léa zu Hause"), tx("At the hotel", "Im Hotel")], answer: 0 },
        { q: tx("Whose clothes is Chloé wearing?", "Wessen Kleider trägt Chloé?"), options: [tx("Léa's", "Léas"), tx("Blob's", "Blobs"), tx("Her own", "Ihre eigenen")], answer: 0 },
      ],
    },
    {
      id: "u15.dialogue2",
      lesson: 7,
      title: tx("Mrs Martin's holiday", "Frau Martins Urlaub"),
      lines: [
        { who: "blob", fr: "Bonjour, Madame Martin ! Vous êtes rentrée ?", en: "Hello, Mrs Martin! Are you back?", de: "Guten Tag, Frau Martin! Sind Sie zurück?" },
        { who: "madame", fr: "Oui, Blob. Je suis rentrée hier soir.", en: "Yes, Blob. I got back last night.", de: "Ja, Blob. Ich bin gestern Abend zurückgekommen." },
        { who: "blob", fr: "Vous êtes allée où ?", en: "Where did you go?", de: "Wo waren Sie?" },
        { who: "madame", fr: "En Italie, avec mon mari. Nous sommes partis en voiture.", en: "To Italy, with my husband. We went by car.", de: "Nach Italien, mit meinem Mann. Wir sind mit dem Auto gefahren." },
        { who: "blob", fr: "Vous êtes restés à l'hôtel ?", en: "Did you stay at a hotel?", de: "Waren Sie im Hotel?" },
        { who: "madame", fr: "Non, nous avons fait du camping à la montagne !", en: "No, we went camping in the mountains!", de: "Nein, wir haben in den Bergen gezeltet!" },
        { who: "blob", fr: "Du camping ? Super ! Et vous avez vu la mer ?", en: "Camping? Great! And did you see the sea?", de: "Camping? Super! Und haben Sie das Meer gesehen?" },
        { who: "madame", fr: "Oui, le week-end dernier, nous sommes allés à la plage.", en: "Yes, last weekend we went to the beach.", de: "Ja, letztes Wochenende sind wir an den Strand gefahren." },
        { who: "blob", fr: "L'année prochaine, je vais venir avec vous !", en: "Next year, I'm going to come with you!", de: "Nächstes Jahr komme ich mit!" },
        { who: "madame", fr: "Bien sûr, Blob… mais pas dans ma valise !", en: "Of course, Blob… but not in my suitcase!", de: "Natürlich, Blob … aber nicht in meinem Koffer!" },
      ],
      questions: [
        { q: tx("Where did Mrs Martin go?", "Wohin ist Frau Martin gefahren?"), options: [tx("To Italy", "Nach Italien"), tx("To Spain", "Nach Spanien"), tx("To Germany", "Nach Deutschland")], answer: 0 },
        { q: tx("Where did the Martins sleep?", "Wo haben die Martins geschlafen?"), options: [tx("At a campsite in the mountains", "Auf einem Campingplatz in den Bergen"), tx("In a hotel by the sea", "In einem Hotel am Meer"), tx("On a boat", "Auf einem Schiff")], answer: 0 },
        { q: tx("What does Blob want to do next year?", "Was will Blob nächstes Jahr machen?"), options: [tx("Go with Mrs Martin", "Mit Frau Martin mitfahren"), tx("Stay at home", "Zu Hause bleiben"), tx("Go to Germany", "Nach Deutschland fahren")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Je suis allé: the past with être", "Je suis allé: die Vergangenheit mit être"),
      body: tx(
        "A few verbs of coming and going make their past with **être** instead of avoir: **aller, partir, arriver, venir, rester, rentrer**. So it's **je suis allé**, never «j'ai allé».\n\nGerman does something similar: ich **bin** gefahren, ich **bin** gekommen, ich **bin** geblieben. Where German says bin, French often says suis.",
        "Ein paar Verben der Bewegung bilden die Vergangenheit mit **être** statt avoir: **aller, partir, arriver, venir, rester, rentrer**. Also **je suis allé**, nie „j'ai allé“.\n\nDas Deutsche macht es ähnlich: ich **bin** gefahren, ich **bin** gekommen, ich **bin** geblieben. Wenn du im Deutschen „sein“ nimmst, liegst du oft richtig.",
      ),
      examples: [
        { fr: "Je suis allé à Paris en train.", en: "I went to Paris by train.", de: "Ich bin mit dem Zug nach Paris gefahren." },
        { fr: "Le train est parti à huit heures.", en: "The train left at eight o'clock.", de: "Der Zug ist um acht Uhr abgefahren." },
        { fr: "Je suis rentré à minuit.", en: "I got home at midnight.", de: "Ich bin um Mitternacht nach Hause gekommen." },
      ],
      table: {
        head: [tx("person", "Person"), "être", tx("+ participle", "+ Partizip")],
        rows: [
          [tx("I", "ich"), "je suis", "allé / allée"],
          [tx("you", "du"), "tu es", "allé / allée"],
          [tx("he / she", "er / sie"), "il est / elle est", "allé / allée"],
          [tx("we", "wir"), "nous sommes", "allés / allées"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous êtes", "allé(e) / allé(e)s"],
          [tx("they", "sie"), "ils sont / elles sont", "allés / allées"],
        ],
      },
    },
    {
      title: tx("Allé, allée, allés, allées", "Allé, allée, allés, allées"),
      body: tx(
        "With être, the participle agrees with the subject, like an adjective: add **e** for a girl or woman, **s** for more than one, **es** for several girls.\n\nYou don't hear it (allé and allée sound the same), but you write it: **elle est allée**, **ils sont partis**, **elles sont venues**. A mixed group takes the masculine: Léa et Hugo sont allés au cinéma.",
        "Mit être passt sich das Partizip an das Subjekt an, wie ein Adjektiv: **e** für ein Mädchen oder eine Frau, **s** für mehrere, **es** für mehrere Mädchen.\n\nMan hört es nicht (allé und allée klingen gleich), aber man schreibt es: **elle est allée**, **ils sont partis**, **elles sont venues**. Eine gemischte Gruppe nimmt die männliche Form: Léa et Hugo sont allés au cinéma.",
      ),
      examples: [
        { fr: "Elle est allée à Lyon en voiture.", en: "She went to Lyon by car.", de: "Sie ist mit dem Auto nach Lyon gefahren." },
        { fr: "Ils sont restés une semaine à la mer.", en: "They stayed at the seaside for a week.", de: "Sie sind eine Woche am Meer geblieben." },
        { fr: "Les filles sont rentrées tard.", en: "The girls came home late.", de: "Die Mädchen sind spät nach Hause gekommen." },
      ],
      table: {
        head: [tx("who", "wer"), tx("one", "einer / eine"), tx("more than one", "mehrere")],
        rows: [
          [tx("masculine", "männlich"), "il est allé", "ils sont allés"],
          [tx("feminine", "weiblich"), "elle est allée", "elles sont allées"],
        ],
      },
    },
    {
      title: tx("En train, à vélo, en France", "En train, à vélo, en France"),
      body: tx(
        "How you travel: inside a vehicle it's **en**: en train, en avion, en voiture, en bateau, en bus. On top of it or on your feet it's **à**: **à** vélo, **à** pied.\n\nWhere: towns take **à** (à Paris, à Lyon), most countries are feminine and take **en**, with no article: **en** France, **en** Allemagne, **en** Italie.",
        "Wie du reist: in einem Fahrzeug heißt es **en**: en train, en avion, en voiture, en bateau, en bus. Obendrauf oder zu Fuß heißt es **à**: **à** vélo, **à** pied.\n\nWohin: Städte nehmen **à** (à Paris, à Lyon), die meisten Länder sind weiblich und nehmen **en**, ohne Artikel: **en** France, **en** Allemagne, **en** Italie.",
      ),
      examples: [
        { fr: "Ils sont allés à Marseille en avion.", en: "They went to Marseille by plane.", de: "Sie sind nach Marseille geflogen." },
        { fr: "Nous sommes allés à la plage à vélo.", en: "We went to the beach by bike.", de: "Wir sind mit dem Fahrrad an den Strand gefahren." },
        { fr: "Je suis allée en Italie.", en: "I went to Italy.", de: "Ich bin nach Italien gefahren." },
      ],
      table: {
        head: [tx("how / where", "wie / wohin"), "en", "à"],
        rows: [
          [tx("transport", "Verkehrsmittel"), "en train, en voiture, en avion", "à vélo, à pied"],
          [tx("places", "Orte"), "en France, en Allemagne", "à Paris, à Lyon"],
        ],
      },
    },
    {
      title: tx("Être or avoir?", "Être oder avoir?"),
      body: tx(
        "Almost every verb takes **avoir**: j'ai mangé, nous avons fait du camping, j'ai oublié ma valise. Only the verbs of coming and going take **être**: je suis allé, elle est venue, nous sommes rentrés.\n\nIn the negative, ne … pas goes around the helper, whichever it is: je **ne suis pas** resté, je **n'ai pas** oublié.",
        "Fast jedes Verb nimmt **avoir**: j'ai mangé, nous avons fait du camping, j'ai oublié ma valise. Nur die Verben der Bewegung nehmen **être**: je suis allé, elle est venue, nous sommes rentrés.\n\nBei der Verneinung steht ne … pas um den Helfer herum, egal welcher es ist: je **ne suis pas** resté, je **n'ai pas** oublié.",
      ),
      examples: [
        { fr: "Nous avons fait du camping à la montagne.", en: "We went camping in the mountains.", de: "Wir haben in den Bergen gezeltet." },
        { fr: "Ils sont restés à l'hôtel.", en: "They stayed at the hotel.", de: "Sie sind im Hotel geblieben." },
        { fr: "Blob n'est pas venu : il est resté à l'hôtel.", en: "Blob didn't come: he stayed at the hotel.", de: "Blob ist nicht gekommen: Er ist im Hotel geblieben." },
      ],
    },
  ],
};
