import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 16: acheter, quantities with de, numbers to 100. */
export const u16: Unit = {
  slug: "marche",
  n: 16,
  cefr: "A2",
  title: tx("At the market", "Auf dem Markt"),
  goal: tx("Buy food, ask for amounts and understand prices", "Lebensmittel kaufen, Mengen verlangen und Preise verstehen"),
  emoji: "🧺",
  words: [
    { id: "marche", fr: "le marché", en: "the market", de: "der Markt", g: "m", kind: "noun", emoji: "🧺", note: tx("Most French towns have an open-air market once or twice a week. Super + marché = supermarché!", "Fast jede französische Stadt hat ein- oder zweimal pro Woche Markt unter freiem Himmel. Super + marché = supermarché!") },
    { id: "fruits", fr: "les fruits", en: "the fruit", de: "das Obst", alt: { en: ["the fruits"], de: ["die Früchte"] }, g: "m", kind: "noun", emoji: "🍇", note: tx("French counts fruit: des fruits, plural. One piece: un fruit.", "Französisch zählt Obst: des fruits, im Plural. Ein Stück: un fruit.") },
    { id: "legumes", fr: "les légumes", en: "the vegetables", de: "das Gemüse", alt: { en: ["the veg"] }, g: "m", kind: "noun", emoji: "🥦", note: tx("Plural too: des légumes. One vegetable: un légume.", "Auch im Plural: des légumes. Ein Gemüse: un légume.") },
    { id: "j-achete", fr: "j'achète", en: "I buy", de: "ich kaufe", alt: { en: ["I'm buying"] }, kind: "verb", note: tx("From acheter, to buy. Watch the è: j'achète.", "Von acheter, kaufen. Achte auf das è: j'achète.") },
    { id: "tu-achetes", fr: "tu achètes", en: "you buy", de: "du kaufst", alt: { en: ["you're buying"] }, kind: "verb", note: tx("The s is silent: tu achètes sounds like j'achète.", "Das s ist stumm: tu achètes klingt wie j'achète.") },
    { id: "tomate", fr: "la tomate", en: "the tomato", de: "die Tomate", g: "f", kind: "noun", emoji: "🍅" },
    { id: "carotte", fr: "la carotte", en: "the carrot", de: "die Karotte", alt: { de: ["die Möhre"] }, g: "f", kind: "noun", emoji: "🥕" },
    { id: "fraise", fr: "la fraise", en: "the strawberry", de: "die Erdbeere", g: "f", kind: "noun", emoji: "🍓" },
    { id: "pomme-de-terre", fr: "la pomme de terre", en: "the potato", de: "die Kartoffel", g: "f", kind: "noun", emoji: "🥔", note: tx("Literally «apple of the earth». Plural: des pommes de terre.", "Wörtlich „Apfel der Erde“, wie Erdapfel in Österreich. Plural: des pommes de terre.") },
    { id: "il-achete", fr: "il achète", en: "he buys", de: "er kauft", alt: { en: ["he's buying"] }, kind: "verb", note: tx("Elle achète: she buys. It sounds just like j'achète.", "Elle achète: Sie kauft. Klingt genau wie j'achète.") },
    { id: "kilo", fr: "le kilo", en: "the kilo", de: "das Kilo", alt: { en: ["the kilogram"], de: ["das Kilogramm"] }, g: "m", kind: "noun", note: tx("Un kilo de tomates: after a quantity, just de.", "Un kilo de tomates: Nach einer Menge steht nur de.") },
    { id: "bouteille", fr: "la bouteille", en: "the bottle", de: "die Flasche", g: "f", kind: "noun", emoji: "🍾", note: tx("Une bouteille d'eau: a bottle of water. Before a vowel, de becomes d'.", "Une bouteille d'eau: eine Flasche Wasser. Vor einem Vokal wird de zu d'.") },
    { id: "beaucoup-de", fr: "beaucoup de", en: "a lot of", de: "viel / viele", alt: { en: ["lots of", "many", "much"], de: ["viel", "viele"] }, kind: "phrase", note: tx("Always just de, never des: beaucoup de fraises, beaucoup d'eau.", "Immer nur de, nie des: beaucoup de fraises, beaucoup d'eau.") },
    { id: "nous-achetons", fr: "nous achetons", en: "we buy", de: "wir kaufen", alt: { en: ["we're buying"] }, kind: "verb", note: tx("No accent with nous and vous: here the ending is spoken.", "Kein Akzent bei nous und vous: Hier hört man die Endung.") },
    { id: "vous-achetez", fr: "vous achetez", en: "you buy (plural / polite)", de: "ihr kauft / Sie kaufen", alt: { en: ["you buy", "you're buying"], de: ["ihr kauft", "Sie kaufen"] }, kind: "verb" },
    { id: "num-30", fr: "trente", en: "thirty", de: "dreißig", kind: "word", note: tx("Then trente et un (31), trente-deux (32)…", "Dann trente et un (31), trente-deux (32) …") },
    { id: "num-40", fr: "quarante", en: "forty", de: "vierzig", kind: "word", note: tx("Quatre → quarante, like four → forty.", "Quatre → quarante, wie vier → vierzig.") },
    { id: "num-50", fr: "cinquante", en: "fifty", de: "fünfzig", kind: "word", note: tx("Cinq → cinquante, like five → fifty.", "Cinq → cinquante, wie fünf → fünfzig.") },
    { id: "num-60", fr: "soixante", en: "sixty", de: "sechzig", kind: "word", note: tx("Say «swa-sant»: the x sounds like an s.", "Sprich „soa-ßant“: Das x klingt wie ein s.") },
    { id: "num-100", fr: "cent", en: "a hundred", de: "hundert", alt: { en: ["one hundred", "hundred"], de: ["einhundert"] }, kind: "word", emoji: "💯", note: tx("Just cent, without un: cent euros. Two hundred: deux cents.", "Einfach cent, ohne un: cent euros. Zweihundert: deux cents.") },
    { id: "cher", fr: "cher", en: "expensive", de: "teuer", alt: { en: ["dear"] }, kind: "adj", note: tx("It agrees: chère, chers, chères. Ce n'est pas cher: it's cheap.", "Es wird angepasst: chère, chers, chères. Ce n'est pas cher: Das ist billig.") },
    { id: "ca-coute", fr: "ça coûte", en: "it costs", de: "das kostet", alt: { en: ["that costs"], de: ["es kostet"] }, kind: "phrase", note: tx("Ça coûte combien ? How much is it? For more than one: les fraises coûtent…", "Ça coûte combien ? Was kostet das? Bei mehreren: les fraises coûtent …") },
    { id: "vendeur", fr: "le vendeur", en: "the seller", de: "der Verkäufer", alt: { en: ["the stallholder", "the shop assistant", "the salesman"] }, g: "m", kind: "noun", emoji: "🧑‍🌾", note: tx("A woman: la vendeuse.", "Eine Frau: la vendeuse.") },
    { id: "argent", fr: "l'argent", en: "the money", de: "das Geld", g: "m", kind: "noun", emoji: "💰", note: tx("Also silver! Je n'ai pas d'argent: I've got no money.", "Auch Silber! Je n'ai pas d'argent: Ich habe kein Geld.") },
    { id: "num-70", fr: "soixante-dix", en: "seventy", de: "siebzig", kind: "word", note: tx("60 + 10. In Belgium and Switzerland: septante.", "60 + 10. In Belgien und der Schweiz: septante.") },
    { id: "num-80", fr: "quatre-vingts", en: "eighty", de: "achtzig", kind: "word", note: tx("4 × 20! With an s at the end, but 81 is quatre-vingt-un.", "4 × 20! Mit s am Ende, aber 81 ist quatre-vingt-un.") },
    { id: "num-90", fr: "quatre-vingt-dix", en: "ninety", de: "neunzig", kind: "word", note: tx("4 × 20 + 10. Belgians and Swiss say nonante.", "4 × 20 + 10. In Belgien und der Schweiz sagt man nonante.") },
    { id: "ils-achetent", fr: "ils achètent", en: "they buy", de: "sie kaufen", alt: { en: ["they're buying"] }, kind: "verb", note: tx("The -ent is silent: ils achètent sounds like il achète.", "Das -ent ist stumm: ils achètent klingt wie il achète.") },
    { id: "douzaine", fr: "la douzaine", en: "the dozen", de: "das Dutzend", g: "f", kind: "noun", note: tx("Douze + aine: about twelve. Une douzaine d'œufs: a dozen eggs.", "Douze + aine: zwölf Stück. Une douzaine d'œufs: ein Dutzend Eier.") },
    { id: "courses", fr: "les courses", en: "the shopping", de: "die Einkäufe", alt: { en: ["the groceries"] }, g: "f", kind: "noun", emoji: "🛍️", note: tx("Faire les courses: to do the shopping. Une course is also a race!", "Faire les courses: einkaufen. Une course ist auch ein Wettrennen!") },
    { id: "cerise", fr: "la cerise", en: "the cherry", de: "die Kirsche", g: "f", kind: "noun", emoji: "🍒" },
  ],
  gloss: [
    { fr: "achète", en: "buy / buys", de: "kaufe / kauft" },
    { fr: "achètes", en: "buy (you)", de: "kaufst" },
    { fr: "achetons", en: "buy (we)", de: "kaufen (wir)" },
    { fr: "achetez", en: "buy (you, plural / polite)", de: "kauft / kaufen (Sie)" },
    { fr: "achètent", en: "buy (they)", de: "kaufen (sie)" },
    { fr: "acheté", en: "bought", de: "gekauft" },
    { fr: "j'ai acheté", en: "I bought / I have bought", de: "ich habe gekauft" },
    { fr: "fruit", en: "fruit", de: "Frucht / Obst" },
    { fr: "légume", en: "vegetable", de: "Gemüse" },
    { fr: "tomates", en: "tomatoes", de: "Tomaten" },
    { fr: "carottes", en: "carrots", de: "Karotten" },
    { fr: "fraises", en: "strawberries", de: "Erdbeeren" },
    { fr: "pommes de terre", en: "potatoes", de: "Kartoffeln" },
    { fr: "kilos", en: "kilos", de: "Kilo" },
    { fr: "cerises", en: "cherries", de: "Kirschen" },
    { fr: "chère", en: "expensive (feminine)", de: "teuer" },
    { fr: "chers", en: "expensive (plural)", de: "teuer" },
    { fr: "chères", en: "expensive (feminine plural)", de: "teuer" },
    { fr: "trop cher", en: "too expensive", de: "zu teuer" },
    { fr: "coûte", en: "costs", de: "kostet" },
    { fr: "coûtent", en: "cost (they)", de: "kosten" },
    { fr: "assez", en: "enough", de: "genug" },
    { fr: "cette semaine", en: "this week", de: "diese Woche" },
    { fr: "liste", en: "list", de: "Liste" },
    { fr: "la liste des courses", en: "the shopping list", de: "die Einkaufsliste" },
    { fr: "seulement", en: "only", de: "nur" },
    { fr: "délicieuses", en: "delicious (feminine plural)", de: "köstlich" },
    { fr: "vendeuse", en: "seller (woman)", de: "Verkäuferin" },
    { fr: "qui fait", en: "who does", de: "wer macht" },
  ],
  lessons: [
    { title: tx("At the market", "Auf dem Markt"), words: ["marche", "fruits", "legumes", "j-achete", "tu-achetes"] },
    { title: tx("Tomatoes and strawberries", "Tomaten und Erdbeeren"), words: ["tomate", "carotte", "fraise", "pomme-de-terre", "il-achete"] },
    { title: tx("A kilo of…", "Ein Kilo …"), words: ["kilo", "bouteille", "beaucoup-de", "nous-achetons", "vous-achetez"] },
    { title: tx("Thirty, forty, fifty", "Dreißig, vierzig, fünfzig"), words: ["num-30", "num-40", "num-50", "num-60", "num-100", "cher"] },
    { title: tx("How much does it cost?", "Was kostet das?"), words: ["ca-coute", "vendeur", "argent"] },
    { title: tx("Seventy, eighty, ninety", "Siebzig, achtzig, neunzig"), words: ["num-70", "num-80", "num-90", "ils-achetent", "douzaine"] },
    { title: tx("The shopping list", "Die Einkaufsliste"), words: ["courses", "cerise"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u16.01", lesson: 1, fr: "J'achète des fruits au marché.", en: "I'm buying fruit at the market.", de: "Ich kaufe Obst auf dem Markt.", alt: { fr: ["J'achète des fruits sur le marché."], en: ["I buy fruit at the market.", "I'm buying some fruit at the market.", "I buy some fruit at the market.", "I'm buying fruits at the market.", "I buy fruits at the market."], de: ["Ich kaufe auf dem Markt Obst.", "Ich kaufe Früchte auf dem Markt.", "Ich kaufe auf dem Markt Früchte."] } },
    { id: "u16.02", lesson: 1, fr: "Tu achètes des légumes ?", en: "Are you buying vegetables?", de: "Kaufst du Gemüse?", alt: { fr: ["Est-ce que tu achètes des légumes ?", "Achètes-tu des légumes ?", "Vous achetez des légumes ?", "Est-ce que vous achetez des légumes ?", "Achetez-vous des légumes ?"], en: ["Do you buy vegetables?", "Are you buying some vegetables?", "Are you buying any vegetables?"], de: ["Kaufst du etwas Gemüse?", "Du kaufst Gemüse?"] } },
    { id: "u16.03", lesson: 1, fr: "Il y a un marché le samedi.", en: "There's a market on Saturdays.", de: "Samstags gibt es einen Markt.", alt: { fr: ["Le samedi, il y a un marché."], en: ["There's a market on Saturday.", "There's a market every Saturday.", "On Saturdays there's a market."], de: ["Am Samstag gibt es einen Markt.", "Es gibt samstags einen Markt.", "Es gibt am Samstag einen Markt.", "Samstags ist Markt.", "Jeden Samstag gibt es einen Markt."] } },
    { id: "u16.04", lesson: 1, fr: "Les fruits du marché sont délicieux.", en: "The fruit from the market is delicious.", de: "Das Obst vom Markt ist köstlich.", alt: { en: ["The fruit at the market is delicious.", "The market fruit is delicious.", "The fruits from the market are delicious.", "The fruits at the market are delicious."], de: ["Das Obst vom Markt ist lecker.", "Das Obst auf dem Markt ist köstlich.", "Das Obst auf dem Markt ist lecker.", "Die Früchte vom Markt sind köstlich.", "Die Früchte vom Markt sind lecker."] } },
    { id: "u16.05", lesson: 1, fr: "Tu achètes du pain pour maman ?", en: "Are you buying bread for Mum?", de: "Kaufst du Brot für Mama?", alt: { fr: ["Est-ce que tu achètes du pain pour maman ?", "Achètes-tu du pain pour maman ?", "Vous achetez du pain pour maman ?", "Est-ce que vous achetez du pain pour maman ?"], en: ["Do you buy bread for Mum?", "Are you buying some bread for Mum?", "Are you buying bread for Mom?"], de: ["Kaufst du für Mama Brot?", "Du kaufst Brot für Mama?"] } },
    { id: "u16.06", lesson: 1, fr: "Je n'achète pas de légumes aujourd'hui.", en: "I'm not buying any vegetables today.", de: "Ich kaufe heute kein Gemüse.", alt: { fr: ["Aujourd'hui, je n'achète pas de légumes."], en: ["I'm not buying vegetables today.", "I don't buy any vegetables today.", "I don't buy vegetables today.", "Today I'm not buying any vegetables.", "Today I'm not buying vegetables."], de: ["Heute kaufe ich kein Gemüse."] } },
    { id: "u16.07", lesson: 1, fr: "Demain, je vais au marché avec Chloé.", en: "Tomorrow I'm going to the market with Chloé.", de: "Morgen gehe ich mit Chloé auf den Markt.", alt: { fr: ["Je vais au marché avec Chloé demain."], en: ["I'm going to the market with Chloé tomorrow.", "Tomorrow I go to the market with Chloé.", "Tomorrow I'll go to the market with Chloé.", "I'll go to the market with Chloé tomorrow."], de: ["Morgen gehe ich mit Chloé zum Markt.", "Ich gehe morgen mit Chloé auf den Markt.", "Ich gehe morgen mit Chloé zum Markt."] } },
    // Lesson 2
    { id: "u16.08", lesson: 2, fr: "Il achète des tomates et des carottes.", en: "He's buying tomatoes and carrots.", de: "Er kauft Tomaten und Karotten.", alt: { en: ["He buys tomatoes and carrots.", "He's buying some tomatoes and carrots."], de: ["Er kauft Tomaten und Möhren."] } },
    { id: "u16.09", lesson: 2, fr: "J'adore les fraises !", en: "I love strawberries!", de: "Ich liebe Erdbeeren!", alt: { en: ["I really love strawberries!"], de: ["Ich mag Erdbeeren sehr!", "Ich esse sehr gern Erdbeeren!"] } },
    { id: "u16.10", lesson: 2, fr: "La tomate, c'est un fruit ou un légume ?", en: "Is the tomato a fruit or a vegetable?", de: "Ist die Tomate Obst oder Gemüse?", alt: { fr: ["Est-ce que la tomate est un fruit ou un légume ?", "La tomate est un fruit ou un légume ?", "La tomate, est-ce un fruit ou un légume ?"], en: ["Is a tomato a fruit or a vegetable?", "Is the tomato fruit or vegetable?", "Is a tomato fruit or vegetable?"], de: ["Ist die Tomate eine Frucht oder ein Gemüse?", "Ist eine Tomate Obst oder Gemüse?", "Ist die Tomate ein Obst oder ein Gemüse?"] } },
    { id: "u16.11", lesson: 2, fr: "Léa achète des pommes de terre.", en: "Léa is buying potatoes.", de: "Léa kauft Kartoffeln.", alt: { en: ["Léa buys potatoes.", "Léa is buying some potatoes."] } },
    { id: "u16.12", lesson: 2, fr: "Hugo n'aime pas les carottes.", en: "Hugo doesn't like carrots.", de: "Hugo mag keine Karotten.", alt: { de: ["Hugo mag keine Möhren.", "Hugo mag Karotten nicht.", "Hugo mag Möhren nicht."] } },
    { id: "u16.13", lesson: 2, fr: "Il achète des fraises pour Léa.", en: "He's buying strawberries for Léa.", de: "Er kauft Erdbeeren für Léa.", alt: { en: ["He buys strawberries for Léa.", "He's buying some strawberries for Léa."], de: ["Er kauft für Léa Erdbeeren."] } },
    { id: "u16.14", lesson: 2, fr: "Il n'achète pas de fraises.", en: "He isn't buying strawberries.", de: "Er kauft keine Erdbeeren.", alt: { en: ["He doesn't buy strawberries.", "He isn't buying any strawberries.", "He doesn't buy any strawberries."] } },
    // Lesson 3
    { id: "u16.15", lesson: 3, fr: "Un kilo de tomates, s'il vous plaît.", en: "A kilo of tomatoes, please.", de: "Ein Kilo Tomaten, bitte.", alt: { fr: ["Un kilo de tomates, s'il te plaît."], en: ["One kilo of tomatoes, please.", "A kilogram of tomatoes, please."], de: ["Bitte ein Kilo Tomaten."] } },
    { id: "u16.16", lesson: 3, fr: "Nous achetons une bouteille d'eau.", en: "We're buying a bottle of water.", de: "Wir kaufen eine Flasche Wasser.", alt: { fr: ["On achète une bouteille d'eau."], en: ["We buy a bottle of water."] } },
    { id: "u16.17", lesson: 3, fr: "Il y a beaucoup de fraises au marché.", en: "There are lots of strawberries at the market.", de: "Auf dem Markt gibt es viele Erdbeeren.", alt: { fr: ["Au marché, il y a beaucoup de fraises."], en: ["There are a lot of strawberries at the market.", "There are many strawberries at the market.", "At the market there are lots of strawberries.", "At the market there are a lot of strawberries."], de: ["Es gibt viele Erdbeeren auf dem Markt.", "Auf dem Markt gibt es eine Menge Erdbeeren."] } },
    { id: "u16.18", lesson: 3, fr: "Vous achetez deux kilos de pommes ?", en: "Are you buying two kilos of apples?", de: "Kaufen Sie zwei Kilo Äpfel?", alt: { fr: ["Est-ce que vous achetez deux kilos de pommes ?", "Achetez-vous deux kilos de pommes ?", "Tu achètes deux kilos de pommes ?", "Est-ce que tu achètes deux kilos de pommes ?"], en: ["Are you buying 2 kilos of apples?", "Do you buy two kilos of apples?"], de: ["Kaufen Sie 2 Kilo Äpfel?", "Kauft ihr zwei Kilo Äpfel?"] } },
    { id: "u16.19", lesson: 3, fr: "Je bois beaucoup d'eau.", en: "I drink a lot of water.", de: "Ich trinke viel Wasser.", alt: { en: ["I drink lots of water.", "I drink loads of water."], de: ["Ich trinke eine Menge Wasser."] } },
    { id: "u16.20", lesson: 3, fr: "Maman achète un kilo de pommes de terre.", en: "Mum is buying a kilo of potatoes.", de: "Mama kauft ein Kilo Kartoffeln.", alt: { en: ["Mum buys a kilo of potatoes.", "Mom is buying a kilo of potatoes."] } },
    { id: "u16.21", lesson: 3, fr: "Vous achetez beaucoup de fruits, Madame Martin !", en: "You're buying a lot of fruit, Mrs Martin!", de: "Sie kaufen viel Obst, Frau Martin!", alt: { fr: ["Madame Martin, vous achetez beaucoup de fruits !"], en: ["You're buying lots of fruit, Mrs Martin!", "You buy a lot of fruit, Mrs Martin!", "You buy lots of fruit, Mrs Martin!", "Mrs Martin, you're buying a lot of fruit!"], de: ["Sie kaufen aber viel Obst, Frau Martin!", "Frau Martin, Sie kaufen viel Obst!"] } },
    // Lesson 4
    { id: "u16.22", lesson: 4, fr: "Ça fait trente euros.", en: "That's thirty euros.", de: "Das macht dreißig Euro.", alt: { fr: ["C'est trente euros."], en: ["That's 30 euros.", "That comes to thirty euros.", "That comes to 30 euros.", "It's thirty euros.", "It's 30 euros.", "That makes thirty euros."], de: ["Das macht 30 Euro.", "Das sind dreißig Euro.", "Das sind 30 Euro.", "Das kostet dreißig Euro.", "Das kostet 30 Euro."] } },
    { id: "u16.23", lesson: 4, fr: "Mon grand-père a soixante ans.", en: "My grandfather is sixty.", de: "Mein Großvater ist sechzig.", alt: { en: ["My grandfather is 60.", "My grandfather is sixty years old.", "My grandfather is 60 years old.", "My grandad is sixty.", "My granddad is sixty."], de: ["Mein Großvater ist 60.", "Mein Großvater ist sechzig Jahre alt.", "Mein Großvater ist 60 Jahre alt.", "Mein Opa ist sechzig.", "Mein Opa ist sechzig Jahre alt.", "Mein Opa ist 60."] } },
    { id: "u16.24", lesson: 4, fr: "Il y a trente élèves dans ma classe.", en: "There are thirty pupils in my class.", de: "In meiner Klasse sind dreißig Schüler.", alt: { fr: ["Dans ma classe, il y a trente élèves."], en: ["There are 30 pupils in my class.", "There are thirty students in my class.", "There are 30 students in my class.", "In my class there are thirty pupils."], de: ["In meiner Klasse sind 30 Schüler.", "Es gibt dreißig Schüler in meiner Klasse.", "In meiner Klasse gibt es dreißig Schüler.", "In meiner Klasse gibt es 30 Schüler.", "Meine Klasse hat dreißig Schüler."] } },
    { id: "u16.25", lesson: 4, fr: "Cinquante plus cinquante égale cent.", en: "Fifty plus fifty equals a hundred.", de: "Fünfzig plus fünfzig ist hundert.", alt: { en: ["Fifty plus fifty equals one hundred.", "Fifty plus fifty is a hundred.", "Fifty plus fifty is one hundred.", "Fifty plus fifty makes a hundred.", "50 plus 50 equals 100.", "50 plus 50 is 100."], de: ["Fünfzig plus fünfzig gleich hundert.", "Fünfzig plus fünfzig ergibt hundert.", "Fünfzig plus fünfzig ist einhundert.", "50 plus 50 ist 100."] } },
    { id: "u16.26", lesson: 4, fr: "Cent euros ? C'est trop cher !", en: "A hundred euros? That's too expensive!", de: "Hundert Euro? Das ist zu teuer!", alt: { en: ["One hundred euros? That's too expensive!", "100 euros? That's too expensive!", "A hundred euros? It's too expensive!", "One hundred euros? It's too expensive!", "100 euros? It's too expensive!"], de: ["100 Euro? Das ist zu teuer!", "Einhundert Euro? Das ist zu teuer!"] } },
    { id: "u16.27", lesson: 4, fr: "Les fraises sont chères.", en: "The strawberries are expensive.", de: "Die Erdbeeren sind teuer.", alt: { en: ["Strawberries are expensive."], de: ["Erdbeeren sind teuer."] } },
    { id: "u16.28", lesson: 4, fr: "Les tomates ne sont pas chères.", en: "The tomatoes aren't expensive.", de: "Die Tomaten sind nicht teuer.", alt: { en: ["Tomatoes aren't expensive.", "The tomatoes are cheap."], de: ["Tomaten sind nicht teuer.", "Die Tomaten sind billig.", "Die Tomaten sind günstig."] } },
    { id: "u16.29", lesson: 4, fr: "Ce pull est cher : quarante euros !", en: "This jumper is expensive: forty euros!", de: "Dieser Pullover ist teuer: vierzig Euro!", alt: { en: ["This jumper is expensive: 40 euros!", "This sweater is expensive: forty euros!", "This pullover is expensive: forty euros!"], de: ["Dieser Pullover ist teuer: 40 Euro!", "Dieser Pulli ist teuer: vierzig Euro!", "Dieser Pulli ist teuer: 40 Euro!"] } },
    // Lesson 5
    { id: "u16.30", lesson: 5, fr: "Ça coûte combien ?", en: "How much does it cost?", de: "Wie viel kostet das?", alt: { fr: ["Combien ça coûte ?", "Combien est-ce que ça coûte ?"], en: ["How much is it?", "How much does that cost?", "How much is that?"], de: ["Was kostet das?", "Wieviel kostet das?", "Wie viel kostet es?", "Was kostet es?"] } },
    { id: "u16.31", lesson: 5, fr: "Les fraises coûtent quatre euros le kilo.", en: "The strawberries cost four euros a kilo.", de: "Die Erdbeeren kosten vier Euro das Kilo.", alt: { fr: ["Les fraises, c'est quatre euros le kilo."], en: ["The strawberries cost 4 euros a kilo.", "Strawberries cost four euros a kilo.", "Strawberries cost 4 euros a kilo.", "The strawberries are four euros a kilo.", "The strawberries cost four euros per kilo.", "Strawberries are four euros a kilo."], de: ["Die Erdbeeren kosten 4 Euro das Kilo.", "Die Erdbeeren kosten vier Euro pro Kilo.", "Die Erdbeeren kosten 4 Euro pro Kilo.", "Erdbeeren kosten vier Euro das Kilo.", "Das Kilo Erdbeeren kostet vier Euro."] } },
    { id: "u16.32", lesson: 5, fr: "Je n'ai pas d'argent.", en: "I don't have any money.", de: "Ich habe kein Geld.", alt: { fr: ["J'ai pas d'argent."], en: ["I have no money.", "I haven't got any money.", "I don't have money.", "I've got no money."] } },
    { id: "u16.33", lesson: 5, fr: "Le vendeur est très gentil.", en: "The seller is very kind.", de: "Der Verkäufer ist sehr nett.", alt: { en: ["The seller is very nice.", "The stallholder is very kind.", "The stallholder is very nice."], de: ["Der Verkäufer ist sehr freundlich.", "Der Verkäufer ist sehr lieb."] } },
    { id: "u16.34", lesson: 5, fr: "Tu as assez d'argent pour les fraises ?", en: "Have you got enough money for the strawberries?", de: "Hast du genug Geld für die Erdbeeren?", alt: { fr: ["Est-ce que tu as assez d'argent pour les fraises ?", "As-tu assez d'argent pour les fraises ?", "Vous avez assez d'argent pour les fraises ?", "Est-ce que vous avez assez d'argent pour les fraises ?", "Avez-vous assez d'argent pour les fraises ?"], en: ["Do you have enough money for the strawberries?", "Have you enough money for the strawberries?"], de: ["Hast du für die Erdbeeren genug Geld?", "Hast du genügend Geld für die Erdbeeren?"] } },
    { id: "u16.35", lesson: 5, fr: "Une bouteille de jus d'orange coûte trois euros.", en: "A bottle of orange juice costs three euros.", de: "Eine Flasche Orangensaft kostet drei Euro.", alt: { en: ["A bottle of orange juice costs 3 euros.", "A bottle of orange juice is three euros.", "A bottle of orange juice is 3 euros."], de: ["Eine Flasche Orangensaft kostet 3 Euro.", "Eine Flasche O-Saft kostet drei Euro."] } },
    { id: "u16.36", lesson: 5, fr: "Pardon, les tomates coûtent combien ?", en: "Excuse me, how much are the tomatoes?", de: "Entschuldigung, was kosten die Tomaten?", alt: { fr: ["Pardon, combien coûtent les tomates ?", "Excusez-moi, les tomates coûtent combien ?", "Excusez-moi, combien coûtent les tomates ?", "Pardon, c'est combien, les tomates ?", "Excusez-moi, c'est combien, les tomates ?"], en: ["Excuse me, how much do the tomatoes cost?", "Sorry, how much are the tomatoes?"], de: ["Entschuldigung, wie viel kosten die Tomaten?", "Entschuldigen Sie, was kosten die Tomaten?", "Entschuldigen Sie, wie viel kosten die Tomaten?", "Verzeihung, was kosten die Tomaten?"] } },
    // Lesson 6
    { id: "u16.37", lesson: 6, fr: "Ma grand-mère a quatre-vingts ans.", en: "My grandmother is eighty.", de: "Meine Großmutter ist achtzig.", alt: { en: ["My grandmother is 80.", "My grandmother is eighty years old.", "My grandmother is 80 years old.", "My granny is eighty.", "My grandma is eighty."], de: ["Meine Großmutter ist 80.", "Meine Großmutter ist achtzig Jahre alt.", "Meine Großmutter ist 80 Jahre alt.", "Meine Oma ist achtzig.", "Meine Oma ist achtzig Jahre alt.", "Meine Oma ist 80."] } },
    { id: "u16.38", lesson: 6, fr: "Ils achètent une douzaine d'œufs.", en: "They're buying a dozen eggs.", de: "Sie kaufen ein Dutzend Eier.", alt: { fr: ["Elles achètent une douzaine d'œufs."], en: ["They buy a dozen eggs."] } },
    { id: "u16.39", lesson: 6, fr: "Le vélo coûte quatre-vingt-dix euros.", en: "The bike costs ninety euros.", de: "Das Fahrrad kostet neunzig Euro.", alt: { en: ["The bike costs 90 euros.", "The bicycle costs ninety euros.", "The bicycle costs 90 euros.", "The bike is ninety euros.", "The bike is 90 euros."], de: ["Das Fahrrad kostet 90 Euro.", "Das Rad kostet neunzig Euro.", "Das Rad kostet 90 Euro."] } },
    { id: "u16.40", lesson: 6, fr: "Soixante-dix euros ? Non merci, c'est trop cher.", en: "Seventy euros? No thanks, it's too expensive.", de: "Siebzig Euro? Nein danke, das ist zu teuer.", alt: { en: ["70 euros? No thanks, it's too expensive.", "Seventy euros? No thank you, it's too expensive.", "Seventy euros? No thanks, that's too expensive.", "Seventy euros? No thank you, that's too expensive.", "70 euros? No thanks, that's too expensive.", "70 euros? No thank you, it's too expensive."], de: ["70 Euro? Nein danke, das ist zu teuer.", "Siebzig Euro? Nein danke, das ist mir zu teuer."] } },
    { id: "u16.41", lesson: 6, fr: "Hier, j'ai acheté des fraises au marché.", en: "Yesterday I bought strawberries at the market.", de: "Gestern habe ich auf dem Markt Erdbeeren gekauft.", alt: { fr: ["J'ai acheté des fraises au marché hier."], en: ["I bought strawberries at the market yesterday.", "Yesterday I bought some strawberries at the market.", "I bought some strawberries at the market yesterday."], de: ["Ich habe gestern auf dem Markt Erdbeeren gekauft.", "Gestern habe ich Erdbeeren auf dem Markt gekauft.", "Ich habe gestern Erdbeeren auf dem Markt gekauft.", "Gestern kaufte ich auf dem Markt Erdbeeren."] } },
    { id: "u16.42", lesson: 6, fr: "Ils n'achètent pas de pommes de terre.", en: "They aren't buying potatoes.", de: "Sie kaufen keine Kartoffeln.", alt: { fr: ["Elles n'achètent pas de pommes de terre."], en: ["They don't buy potatoes.", "They aren't buying any potatoes.", "They don't buy any potatoes."] } },
    { id: "u16.43", lesson: 6, fr: "Nous allons acheter des fruits demain.", en: "We're going to buy fruit tomorrow.", de: "Wir werden morgen Obst kaufen.", alt: { fr: ["On va acheter des fruits demain.", "Demain, nous allons acheter des fruits.", "Demain, on va acheter des fruits."], en: ["We will buy fruit tomorrow.", "Tomorrow we're going to buy fruit.", "Tomorrow we will buy fruit.", "We're going to buy some fruit tomorrow."], de: ["Morgen kaufen wir Obst.", "Wir kaufen morgen Obst.", "Morgen werden wir Obst kaufen."] } },
    { id: "u16.44", lesson: 6, fr: "Une douzaine, c'est douze.", en: "A dozen is twelve.", de: "Ein Dutzend sind zwölf.", alt: { fr: ["Une douzaine, ça fait douze."], en: ["A dozen is 12.", "A dozen makes twelve."], de: ["Ein Dutzend ist zwölf.", "Ein Dutzend sind 12.", "Ein Dutzend ist 12."] } },
    // Lesson 7
    { id: "u16.45", lesson: 7, fr: "Le samedi, je fais les courses avec papa.", en: "On Saturdays I do the shopping with Dad.", de: "Samstags gehe ich mit Papa einkaufen.", alt: { fr: ["Je fais les courses avec papa le samedi."], en: ["On Saturday I do the shopping with Dad.", "I do the shopping with Dad on Saturdays.", "I do the shopping with Dad on Saturday.", "On Saturdays I go shopping with Dad.", "I go shopping with Dad on Saturdays."], de: ["Samstags kaufe ich mit Papa ein.", "Am Samstag gehe ich mit Papa einkaufen.", "Am Samstag kaufe ich mit Papa ein.", "Samstags mache ich mit Papa die Einkäufe.", "Ich gehe samstags mit Papa einkaufen.", "Ich kaufe samstags mit Papa ein."] } },
    { id: "u16.46", lesson: 7, fr: "Tu as fait les courses ?", en: "Did you do the shopping?", de: "Hast du eingekauft?", alt: { fr: ["Est-ce que tu as fait les courses ?", "As-tu fait les courses ?", "Vous avez fait les courses ?", "Est-ce que vous avez fait les courses ?", "Avez-vous fait les courses ?"], en: ["Have you done the shopping?", "Did you go shopping?", "Have you been shopping?"], de: ["Hast du die Einkäufe gemacht?", "Warst du einkaufen?"] } },
    { id: "u16.47", lesson: 7, fr: "Je voudrais un kilo de cerises, s'il vous plaît.", en: "I'd like a kilo of cherries, please.", de: "Ich hätte gern ein Kilo Kirschen, bitte.", alt: { fr: ["Je voudrais un kilo de cerises, s'il te plaît."], en: ["I'd like one kilo of cherries, please."], de: ["Ich hätte gerne ein Kilo Kirschen, bitte.", "Ich möchte ein Kilo Kirschen, bitte.", "Ich möchte bitte ein Kilo Kirschen."] } },
    { id: "u16.48", lesson: 7, fr: "Il n'y a pas de cerises aujourd'hui.", en: "There are no cherries today.", de: "Heute gibt es keine Kirschen.", alt: { fr: ["Aujourd'hui, il n'y a pas de cerises."], en: ["There aren't any cherries today.", "Today there are no cherries.", "Today there aren't any cherries."], de: ["Es gibt heute keine Kirschen."] } },
    { id: "u16.49", lesson: 7, fr: "Les cerises sont très chères cette semaine.", en: "Cherries are very expensive this week.", de: "Die Kirschen sind diese Woche sehr teuer.", alt: { fr: ["Cette semaine, les cerises sont très chères."], en: ["The cherries are very expensive this week.", "This week cherries are very expensive.", "This week the cherries are very expensive."], de: ["Kirschen sind diese Woche sehr teuer.", "Diese Woche sind die Kirschen sehr teuer.", "Diese Woche sind Kirschen sehr teuer."] } },
    { id: "u16.50", lesson: 7, fr: "Qui fait les courses chez toi ?", en: "Who does the shopping at your place?", de: "Wer kauft bei dir ein?", alt: { fr: ["Qui fait les courses chez vous ?", "Chez toi, qui fait les courses ?", "Chez vous, qui fait les courses ?"], en: ["Who does the shopping at your house?", "Who does the shopping in your family?", "Who does the shopping at your home?"], de: ["Wer macht bei dir die Einkäufe?", "Wer geht bei dir einkaufen?", "Wer kauft bei euch ein?", "Wer macht bei euch die Einkäufe?", "Wer geht bei euch einkaufen?"] } },
    { id: "u16.51", lesson: 7, fr: "Ils achètent des cerises pour le gâteau.", en: "They're buying cherries for the cake.", de: "Sie kaufen Kirschen für den Kuchen.", alt: { fr: ["Elles achètent des cerises pour le gâteau."], en: ["They buy cherries for the cake.", "They're buying some cherries for the cake."], de: ["Sie kaufen Kirschen für die Torte."] } },
  ],
  drills: [
    { id: "u16.d1", lesson: 1, fr: "J'___ des fruits au marché.", options: ["achète", "achètes", "achetons"], answer: 0, en: "I'm buying fruit at the market.", de: "Ich kaufe Obst auf dem Markt.", why: tx("With **je**: j'**achète**, with è and a silent e at the end. Achetons goes with nous.", "Mit **je**: j'**achète**, mit è und einem stummen e am Ende. Achetons gehört zu nous.") },
    { id: "u16.d2", lesson: 1, fr: "Tu ___ des légumes ?", options: ["achètes", "achète", "achetez"], answer: 0, en: "Are you buying vegetables?", de: "Kaufst du Gemüse?", why: tx("With **tu** the ending is **-es**: tu **achètes**. You don't hear the s.", "Mit **tu** endet es auf **-es**: tu **achètes**. Das s hört man nicht.") },
    { id: "u16.d3", lesson: 1, fr: "J'achète ___ légumes au marché.", options: ["des", "de", "du"], answer: 0, en: "I'm buying vegetables at the market.", de: "Ich kaufe Gemüse auf dem Markt.", why: tx("Some vegetables, plural: **des** légumes. Plain de only comes after a quantity (beaucoup de, un kilo de) or after ne … pas.", "Etwas Gemüse, Plural: **des** légumes. Nur de steht nach einer Menge (beaucoup de, un kilo de) oder nach ne … pas.") },
    { id: "u16.d4", lesson: 2, fr: "Léa ___ des pommes de terre.", options: ["achète", "achètes", "achètent"], answer: 0, en: "Léa is buying potatoes.", de: "Léa kauft Kartoffeln.", why: tx("Léa is one person, like **il / elle**: Léa **achète**, without s.", "Léa ist eine Person, wie **il / elle**: Léa **achète**, ohne s.") },
    { id: "u16.d5", lesson: 2, fr: "Hugo n'aime pas ___ carottes.", options: ["les", "de", "des"], answer: 0, en: "Hugo doesn't like carrots.", de: "Hugo mag keine Karotten.", why: tx("After **aimer**, keep **les**, even with ne … pas: il n'aime pas **les** carottes. Pas de is for buying and having: il n'achète pas de carottes.", "Nach **aimer** bleibt **les**, auch mit ne … pas: il n'aime pas **les** carottes. Pas de steht beim Kaufen und Haben: il n'achète pas de carottes.") },
    { id: "u16.d6", lesson: 2, fr: "Il n'achète pas ___ fraises.", options: ["de", "des"], answer: 0, en: "He isn't buying strawberries.", de: "Er kauft keine Erdbeeren.", why: tx("After **ne … pas**, des becomes **de**: pas **de** fraises.", "Nach **ne … pas** wird des zu **de**: pas **de** fraises.") },
    { id: "u16.d7", lesson: 3, fr: "Un kilo ___ tomates, s'il vous plaît.", options: ["de", "des", "du"], answer: 0, en: "A kilo of tomatoes, please.", de: "Ein Kilo Tomaten, bitte.", why: tx("After a quantity, just **de**: un kilo **de** tomates, une bouteille **de** lait.", "Nach einer Menge steht nur **de**: un kilo **de** tomates, une bouteille **de** lait.") },
    { id: "u16.d8", lesson: 3, fr: "Nous ___ une bouteille d'eau.", options: ["achetons", "achetez", "achètent"], answer: 0, en: "We're buying a bottle of water.", de: "Wir kaufen eine Flasche Wasser.", why: tx("With **nous**: nous **achetons**, ending -ons and no accent.", "Mit **nous**: nous **achetons**, Endung -ons und kein Akzent.") },
    { id: "u16.d9", lesson: 3, fr: "Il y a beaucoup ___ fraises au marché.", options: ["de", "des"], answer: 0, en: "There are lots of strawberries at the market.", de: "Auf dem Markt gibt es viele Erdbeeren.", why: tx("It's always **beaucoup de**, never des: beaucoup **de** fraises, beaucoup **d'**eau.", "Es heißt immer **beaucoup de**, nie des: beaucoup **de** fraises, beaucoup **d'**eau.") },
    { id: "u16.d10", lesson: 4, fr: "Les fraises sont ___.", options: ["chères", "cher", "chère"], answer: 0, en: "The strawberries are expensive.", de: "Die Erdbeeren sind teuer.", why: tx("Fraises is feminine and plural: **chères**, with è, e and s.", "Fraises ist weiblich und Plural: **chères**, mit è, e und s.") },
    { id: "u16.d11", lesson: 4, fr: "Ce pull est ___ : quarante euros !", options: ["cher", "chère", "chers"], answer: 0, en: "This jumper is expensive: forty euros!", de: "Dieser Pullover ist teuer: vierzig Euro!", why: tx("Pull is masculine and singular: **cher**, nothing added. La robe est chère.", "Pull ist männlich und Singular: **cher**, ohne Endung. La robe est chère.") },
    { id: "u16.d12", lesson: 4, fr: "Cinquante plus cinquante égale ___.", options: ["cent", "soixante", "quarante"], answer: 0, en: "Fifty plus fifty equals a hundred.", de: "Fünfzig plus fünfzig ist hundert.", why: tx("50 + 50 = 100: **cent**. Soixante is 60, quarante is 40.", "50 + 50 = 100: **cent**. Soixante ist 60, quarante ist 40.") },
    { id: "u16.d13", lesson: 5, fr: "Les fraises ___ quatre euros le kilo.", options: ["coûtent", "coûte"], answer: 0, en: "The strawberries cost four euros a kilo.", de: "Die Erdbeeren kosten vier Euro das Kilo.", why: tx("Les fraises is plural: they **coûtent** (you don't hear the -ent). One thing: ça coûte.", "Les fraises ist Plural: **coûtent** (das -ent hört man nicht). Bei einer Sache: ça coûte.") },
    { id: "u16.d14", lesson: 5, fr: "Je n'ai pas ___argent.", options: ["d'", "de l'"], answer: 0, en: "I don't have any money.", de: "Ich habe kein Geld.", why: tx("After ne … pas, du and de l' become **de**, and before a vowel **d'**: pas **d'**argent.", "Nach ne … pas werden du und de l' zu **de**, vor einem Vokal **d'**: pas **d'**argent.") },
    { id: "u16.d15", lesson: 6, fr: "Ils ___ une douzaine d'œufs.", options: ["achètent", "achetons", "achetez"], answer: 0, en: "They're buying a dozen eggs.", de: "Sie kaufen ein Dutzend Eier.", why: tx("With **ils**: ils **achètent**, with è. The -ent is silent.", "Mit **ils**: ils **achètent**, mit è. Das -ent ist stumm.") },
    { id: "u16.d16", lesson: 6, fr: "Ma grand-mère a quatre-___ ans.", options: ["vingts", "vingt"], answer: 0, en: "My grandmother is eighty.", de: "Meine Großmutter ist achtzig.", why: tx("Eighty is **quatre-vingts**, with an s when no other number follows. 81: quatre-vingt-un, without s.", "Achtzig ist **quatre-vingts**, mit s, wenn keine Zahl folgt. 81: quatre-vingt-un, ohne s.") },
    { id: "u16.d17", lesson: 7, fr: "Le samedi, je ___ les courses avec papa.", options: ["fais", "fait", "faisons"], answer: 0, en: "On Saturdays I do the shopping with Dad.", de: "Samstags gehe ich mit Papa einkaufen.", why: tx("With **je**: je **fais**. Faire les courses: to do the shopping.", "Mit **je**: je **fais**. Faire les courses: einkaufen.") },
    { id: "u16.d18", lesson: 7, fr: "Il n'y a pas ___ cerises aujourd'hui.", options: ["de", "des"], answer: 0, en: "There are no cherries today.", de: "Heute gibt es keine Kirschen.", why: tx("**Il n'y a pas de**: after the negation, des becomes **de**.", "**Il n'y a pas de**: Nach der Verneinung wird des zu **de**.") },
  ],
  dialogues: [
    {
      id: "u16.dialogue",
      lesson: 5,
      title: tx("Blob at the market", "Blob auf dem Markt"),
      lines: [
        { who: "vendeur", fr: "Bonjour ! Vous désirez ?", en: "Hello! What would you like?", de: "Guten Tag! Was darf es sein?" },
        { who: "lea", fr: "Un kilo de tomates et des carottes, s'il vous plaît.", en: "A kilo of tomatoes and some carrots, please.", de: "Ein Kilo Tomaten und Karotten, bitte." },
        { who: "vendeur", fr: "Voilà ! Et avec ça ?", en: "Here you are! Anything else?", de: "Bitte schön! Sonst noch etwas?" },
        { who: "blob", fr: "Les fraises, ça coûte combien ?", en: "How much are the strawberries?", de: "Was kosten die Erdbeeren?" },
        { who: "vendeur", fr: "Six euros le kilo.", en: "Six euros a kilo.", de: "Sechs Euro das Kilo." },
        { who: "blob", fr: "Six euros ? C'est cher ! Léa, tu as de l'argent ?", en: "Six euros? That's expensive! Léa, have you got any money?", de: "Sechs Euro? Das ist teuer! Léa, hast du Geld?" },
        { who: "lea", fr: "Non, je n'ai pas assez d'argent pour les fraises.", en: "No, I haven't got enough money for the strawberries.", de: "Nein, ich habe nicht genug Geld für die Erdbeeren." },
        { who: "vendeur", fr: "Bon… une fraise pour toi, c'est gratuit !", en: "Well… one strawberry for you, it's free!", de: "Na gut … eine Erdbeere für dich, gratis!" },
        { who: "blob", fr: "Merci, Monsieur ! Elle est délicieuse !", en: "Thank you, sir! It's delicious!", de: "Danke! Sie ist köstlich!" },
      ],
      questions: [
        { q: tx("What does Léa buy?", "Was kauft Léa?"), options: [tx("A kilo of tomatoes and some carrots", "Ein Kilo Tomaten und Karotten"), tx("A kilo of strawberries", "Ein Kilo Erdbeeren"), tx("A bottle of water", "Eine Flasche Wasser")], answer: 0 },
        { q: tx("How much are the strawberries?", "Was kosten die Erdbeeren?"), options: [tx("Six euros a kilo", "Sechs Euro das Kilo"), tx("Sixteen euros a kilo", "Sechzehn Euro das Kilo"), tx("Sixty euros", "Sechzig Euro")], answer: 0 },
        { q: tx("What does Blob get for free?", "Was bekommt Blob gratis?"), options: [tx("One strawberry", "Eine Erdbeere"), tx("A kilo of tomatoes", "Ein Kilo Tomaten"), tx("A carrot", "Eine Karotte")], answer: 0 },
      ],
    },
    {
      id: "u16.dialogue2",
      lesson: 7,
      title: tx("Eighty cherries", "Achtzig Kirschen"),
      lines: [
        { who: "chloe", fr: "Hugo, tu as la liste des courses ?", en: "Hugo, have you got the shopping list?", de: "Hugo, hast du die Einkaufsliste?" },
        { who: "hugo", fr: "Oui : des carottes, des pommes de terre et une bouteille de lait.", en: "Yes: carrots, potatoes and a bottle of milk.", de: "Ja: Karotten, Kartoffeln und eine Flasche Milch." },
        { who: "chloe", fr: "Et pour le gâteau de ta mère, on achète quoi ?", en: "And what are we buying for your mum's cake?", de: "Und was kaufen wir für den Kuchen deiner Mutter?" },
        { who: "hugo", fr: "Des cerises. Un kilo de cerises.", en: "Cherries. A kilo of cherries.", de: "Kirschen. Ein Kilo Kirschen." },
        { who: "blob", fr: "Moi, j'achète les cerises !", en: "I'll buy the cherries!", de: "Ich kaufe die Kirschen!" },
        { who: "chloe", fr: "Blob, tu as les cerises ?", en: "Blob, have you got the cherries?", de: "Blob, hast du die Kirschen?" },
        { who: "blob", fr: "Oui, voilà le sac. Il y a quatre-vingts cerises !", en: "Yes, here's the bag. There are eighty cherries!", de: "Ja, hier ist die Tüte. Da sind achtzig Kirschen drin!" },
        { who: "hugo", fr: "Quatre-vingts ? Mais il y a seulement cinquante cerises dans le sac…", en: "Eighty? But there are only fifty cherries in the bag…", de: "Achtzig? Aber in der Tüte sind nur fünfzig Kirschen …" },
        { who: "blob", fr: "Euh… les cerises du marché sont délicieuses !", en: "Er… the cherries from the market are delicious!", de: "Äh … die Kirschen vom Markt sind köstlich!" },
        { who: "chloe", fr: "Oh là là, Blob ! Tu as mangé trente cerises !", en: "Oh dear, Blob! You've eaten thirty cherries!", de: "Oje, Blob! Du hast dreißig Kirschen gegessen!" },
      ],
      questions: [
        { q: tx("What is on the shopping list?", "Was steht auf der Einkaufsliste?"), options: [tx("Carrots, potatoes and a bottle of milk", "Karotten, Kartoffeln und eine Flasche Milch"), tx("Strawberries and a bottle of water", "Erdbeeren und eine Flasche Wasser"), tx("A cake and some eggs", "Ein Kuchen und Eier")], answer: 0 },
        { q: tx("What do they need for the cake?", "Was brauchen sie für den Kuchen?"), options: [tx("A kilo of cherries", "Ein Kilo Kirschen"), tx("A dozen eggs", "Ein Dutzend Eier"), tx("Strawberries", "Erdbeeren")], answer: 0 },
        { q: tx("How many cherries are in the bag?", "Wie viele Kirschen sind in der Tüte?"), options: [tx("Fifty", "Fünfzig"), tx("Eighty", "Achtzig"), tx("Thirty", "Dreißig")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Acheter: when is it è?", "Acheter: Wann steht è?"),
      body: tx(
        "**Acheter** (to buy) is an -er verb with a little twist: when the ending is silent, the e before it becomes **è**: j'**achète**, tu **achètes**, il **achète**, ils **achètent**.\n\nWith **nous** and **vous** you hear the ending, so there's no accent: nous **achetons**, vous **achetez**.",
        "**Acheter** (kaufen) ist ein -er-Verb mit einem kleinen Dreh: Wenn die Endung stumm ist, wird das e davor zu **è**: j'**achète**, tu **achètes**, il **achète**, ils **achètent**.\n\nBei **nous** und **vous** hört man die Endung, darum kein Akzent: nous **achetons**, vous **achetez**.",
      ),
      examples: [
        { fr: "J'achète des fruits au marché.", en: "I'm buying fruit at the market.", de: "Ich kaufe Obst auf dem Markt." },
        { fr: "Nous achetons une bouteille d'eau.", en: "We're buying a bottle of water.", de: "Wir kaufen eine Flasche Wasser." },
        { fr: "Ils achètent une douzaine d'œufs.", en: "They're buying a dozen eggs.", de: "Sie kaufen ein Dutzend Eier." },
      ],
      table: {
        head: [tx("person", "Person"), "acheter"],
        rows: [
          [tx("I", "ich"), "j'achète"],
          [tx("you", "du"), "tu achètes"],
          [tx("he / she", "er / sie"), "il / elle achète"],
          [tx("we", "wir"), "nous achetons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous achetez"],
          [tx("they", "sie"), "ils / elles achètent"],
        ],
      },
    },
    {
      title: tx("Un kilo de…: amounts", "Un kilo de …: Mengen"),
      body: tx(
        "After an amount, French uses just **de** (d' before a vowel), never des or du: un kilo **de** tomates, une bouteille **d'**eau, beaucoup **de** fraises.\n\nThe same after a negation: je n'achète **pas de** carottes, je n'ai **pas d'**argent. But after aimer, le / la / les stay: je n'aime pas **les** carottes.",
        "Nach einer Menge steht nur **de** (vor Vokal d'), nie des oder du: un kilo **de** tomates, une bouteille **d'**eau, beaucoup **de** fraises.\n\nGenauso nach einer Verneinung: je n'achète **pas de** carottes, je n'ai **pas d'**argent. Aber nach aimer bleiben le / la / les: je n'aime pas **les** carottes.",
      ),
      examples: [
        { fr: "Un kilo de tomates, s'il vous plaît.", en: "A kilo of tomatoes, please.", de: "Ein Kilo Tomaten, bitte." },
        { fr: "Il y a beaucoup de fraises au marché.", en: "There are lots of strawberries at the market.", de: "Auf dem Markt gibt es viele Erdbeeren." },
        { fr: "Je n'ai pas d'argent.", en: "I don't have any money.", de: "Ich habe kein Geld." },
      ],
      table: {
        head: [tx("amount", "Menge"), tx("example", "Beispiel")],
        rows: [
          [tx("a kilo of", "ein Kilo"), "un kilo de pommes"],
          [tx("a bottle of", "eine Flasche"), "une bouteille d'eau"],
          [tx("a lot of", "viel / viele"), "beaucoup de fraises"],
          [tx("a bit of", "ein bisschen"), "un peu de fromage"],
          [tx("no / not any", "kein"), "pas de carottes"],
        ],
      },
    },
    {
      title: tx("Thirty to a hundred, and prices", "Dreißig bis hundert, und Preise"),
      body: tx(
        "The tens are easy up to sixty: **trente**, **quarante**, **cinquante**, **soixante**. A hundred is just **cent**, without un.\n\nAsk **ça coûte combien ?** The answer: ça coûte / ça fait trente euros. At the market, prices are per kilo: quatre euros **le kilo**. Too much? **C'est trop cher !** Cher agrees like other adjectives: le pull est cher, les fraises sont **chères**.",
        "Die Zehner sind bis sechzig leicht: **trente**, **quarante**, **cinquante**, **soixante**. Hundert ist einfach **cent**, ohne un.\n\nFrag **ça coûte combien ?** Die Antwort: ça coûte / ça fait trente euros. Auf dem Markt gilt der Preis pro Kilo: quatre euros **le kilo**. Zu viel? **C'est trop cher !** Cher wird angepasst wie andere Adjektive: le pull est cher, les fraises sont **chères**.",
      ),
      examples: [
        { fr: "Ça coûte combien ?", en: "How much does it cost?", de: "Wie viel kostet das?" },
        { fr: "Les fraises coûtent quatre euros le kilo.", en: "The strawberries cost four euros a kilo.", de: "Die Erdbeeren kosten vier Euro das Kilo." },
        { fr: "Cent euros ? C'est trop cher !", en: "A hundred euros? That's too expensive!", de: "Hundert Euro? Das ist zu teuer!" },
      ],
      table: {
        head: [tx("number", "Zahl"), tx("French", "Französisch")],
        rows: [
          ["30", "trente"],
          ["40", "quarante"],
          ["50", "cinquante"],
          ["60", "soixante"],
          ["100", "cent"],
        ],
      },
    },
    {
      title: tx("Soixante-dix, quatre-vingts: French maths", "Soixante-dix, quatre-vingts: französisch rechnen"),
      body: tx(
        "After sixty, French counts in a funny way: 70 is **soixante-dix** (60 + 10), 80 is **quatre-vingts** (4 × 20), 90 is **quatre-vingt-dix** (4 × 20 + 10).\n\nIn Belgium and Switzerland it's easier: septante (70) and nonante (90). And twelve of something is **une douzaine**: une douzaine d'œufs.",
        "Nach sechzig zählt Französisch lustig weiter: 70 ist **soixante-dix** (60 + 10), 80 ist **quatre-vingts** (4 × 20), 90 ist **quatre-vingt-dix** (4 × 20 + 10).\n\nIn Belgien und der Schweiz ist es leichter: septante (70) und nonante (90). Und zwölf Stück sind **une douzaine**: une douzaine d'œufs.",
      ),
      examples: [
        { fr: "Ma grand-mère a quatre-vingts ans.", en: "My grandmother is eighty.", de: "Meine Großmutter ist achtzig." },
        { fr: "Le vélo coûte quatre-vingt-dix euros.", en: "The bike costs ninety euros.", de: "Das Fahrrad kostet neunzig Euro." },
        { fr: "Ils achètent une douzaine d'œufs.", en: "They're buying a dozen eggs.", de: "Sie kaufen ein Dutzend Eier." },
      ],
      table: {
        head: [tx("number", "Zahl"), tx("French", "Französisch"), tx("literally", "wörtlich")],
        rows: [
          ["70", "soixante-dix", "60 + 10"],
          ["80", "quatre-vingts", "4 × 20"],
          ["90", "quatre-vingt-dix", "4 × 20 + 10"],
        ],
      },
    },
  ],
};
