import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 17: avoir mal à, body parts, devoir. */
export const u17: Unit = {
  slug: "sante",
  n: 17,
  cefr: "A2",
  title: tx("Feeling ill", "Krank sein"),
  goal: tx("Say what hurts and understand advice", "Sagen, was wehtut, und Ratschläge verstehen"),
  emoji: "🩺",
  words: [
    { id: "j-ai-mal", fr: "j'ai mal", en: "it hurts", de: "es tut mir weh", alt: { en: ["I'm in pain", "I have a pain"], de: ["ich habe Schmerzen"] }, kind: "phrase", emoji: "🤕", note: tx("Literally «I have pain». Then à + the body part: j'ai mal à la tête.", "Wörtlich „ich habe Schmerz“. Dann à + Körperteil: j'ai mal à la tête.") },
    { id: "tete", fr: "la tête", en: "the head", de: "der Kopf", g: "f", kind: "noun", note: tx("J'ai mal à la tête: I've got a headache.", "J'ai mal à la tête: Ich habe Kopfschmerzen.") },
    { id: "ventre", fr: "le ventre", en: "the stomach", de: "der Bauch", alt: { en: ["the tummy", "the belly"] }, g: "m", kind: "noun", note: tx("J'ai mal au ventre: I've got a stomach ache.", "J'ai mal au ventre: Ich habe Bauchschmerzen.") },
    { id: "dos", fr: "le dos", en: "the back", de: "der Rücken", g: "m", kind: "noun", note: tx("The s is silent: «doh». Un sac à dos: a backpack!", "Das s ist stumm: „doh“. Un sac à dos: ein Rucksack!") },
    { id: "malade", fr: "malade", en: "ill", de: "krank", alt: { en: ["sick"] }, kind: "adj", emoji: "🤒", note: tx("The same for boys and girls: il est malade, elle est malade.", "Gleich für Jungen und Mädchen: il est malade, elle est malade.") },
    { id: "bras", fr: "le bras", en: "the arm", de: "der Arm", g: "m", kind: "noun", emoji: "💪", note: tx("It already ends in s: un bras, deux bras.", "Endet schon auf s: un bras, deux bras.") },
    { id: "jambe", fr: "la jambe", en: "the leg", de: "das Bein", g: "f", kind: "noun", emoji: "🦵" },
    { id: "main", fr: "la main", en: "the hand", de: "die Hand", g: "f", kind: "noun", emoji: "✋", note: tx("Feminine, like in German: la main, die Hand.", "Weiblich, wie im Deutschen: la main, die Hand.") },
    { id: "pied", fr: "le pied", en: "the foot", de: "der Fuß", g: "m", kind: "noun", emoji: "🦶", note: tx("The d is silent. À pied: on foot.", "Das d ist stumm. À pied: zu Fuß.") },
    { id: "dents", fr: "les dents", en: "the teeth", de: "die Zähne", g: "f", kind: "noun", emoji: "🦷", note: tx("One tooth: une dent. J'ai mal aux dents: I've got toothache.", "Ein Zahn: une dent. J'ai mal aux dents: Ich habe Zahnschmerzen.") },
    { id: "medecin", fr: "le médecin", en: "the doctor", de: "der Arzt", alt: { de: ["die Ärztin"] }, g: "m", kind: "noun", emoji: "🧑‍⚕️", note: tx("Also for women: elle est médecin, la médecin. You call her Docteur.", "Auch für Frauen: elle est médecin, la médecin. Anreden kannst du sie mit Docteur.") },
    { id: "gorge", fr: "la gorge", en: "the throat", de: "der Hals", g: "f", kind: "noun", note: tx("J'ai mal à la gorge: I've got a sore throat.", "J'ai mal à la gorge: Ich habe Halsschmerzen.") },
    { id: "fievre", fr: "la fièvre", en: "the temperature", de: "das Fieber", alt: { en: ["the fever"] }, g: "f", kind: "noun", emoji: "🌡️", note: tx("J'ai de la fièvre: I've got a temperature.", "J'ai de la fièvre: Ich habe Fieber.") },
    { id: "pharmacie", fr: "la pharmacie", en: "the chemist's", de: "die Apotheke", alt: { en: ["the pharmacy", "the chemist"] }, g: "f", kind: "noun", note: tx("Look for the green cross. Ph sounds like f.", "Achte auf das grüne Kreuz. Ph klingt wie f.") },
    { id: "oreille", fr: "l'oreille", en: "the ear", de: "das Ohr", g: "f", kind: "noun", note: tx("Before a vowel, à la becomes à l': j'ai mal à l'oreille.", "Vor einem Vokal wird à la zu à l': j'ai mal à l'oreille.") },
    { id: "je-dois", fr: "je dois", en: "I must", de: "ich muss", alt: { en: ["I have to", "I need to"] }, kind: "verb", note: tx("From devoir. After it comes an infinitive: je dois partir.", "Von devoir. Danach kommt ein Infinitiv: je dois partir.") },
    { id: "tu-dois", fr: "tu dois", en: "you must", de: "du musst", alt: { en: ["you have to", "you need to"] }, kind: "verb" },
    { id: "il-doit", fr: "il doit", en: "he must", de: "er muss", alt: { en: ["he has to", "he needs to"] }, kind: "verb", note: tx("With a t: il doit, elle doit.", "Mit t: il doit, elle doit.") },
    { id: "vous-devez", fr: "vous devez", en: "you must (plural / polite)", de: "ihr müsst / Sie müssen", alt: { en: ["you must", "you have to"], de: ["ihr müsst", "Sie müssen"] }, kind: "verb", note: tx("What the doctor says: vous devez rester au lit.", "Das sagt die Ärztin: vous devez rester au lit.") },
    { id: "medicament", fr: "le médicament", en: "the medicine", de: "das Medikament", alt: { en: ["the medication"], de: ["die Medizin"] }, g: "m", kind: "noun", emoji: "💊" },
    { id: "se-reposer", fr: "se reposer", en: "to rest", de: "sich ausruhen", alt: { en: ["rest"] }, kind: "verb", note: tx("Reflexive, like se lever: je me repose, tu dois te reposer.", "Reflexiv, wie se lever: je me repose, tu dois te reposer.") },
    { id: "ca-va-mieux", fr: "ça va mieux", en: "I'm feeling better", de: "es geht mir besser", alt: { en: ["I feel better", "it's better"], de: ["mir geht's besser"] }, kind: "phrase", note: tx("Mieux means better. Also: je vais mieux. Never je suis mieux!", "Mieux heißt besser. Auch: je vais mieux. Nie je suis mieux!") },
    { id: "nous-devons", fr: "nous devons", en: "we must", de: "wir müssen", alt: { en: ["we have to", "we need to"] }, kind: "verb" },
    { id: "ils-doivent", fr: "ils doivent", en: "they must", de: "sie müssen", alt: { en: ["they have to", "they need to"] }, kind: "verb", note: tx("Here you hear the v: ils doivent.", "Hier hört man das v: ils doivent.") },
    { id: "il-faut", fr: "il faut", en: "you have to", de: "man muss", alt: { en: ["one must", "you need to"] }, kind: "phrase", note: tx("For everyone, and it never changes: il faut dormir. Il ne faut pas: you mustn't.", "Gilt für alle und ändert sich nie: il faut dormir. Il ne faut pas: Man darf nicht.") },
    { id: "rhume", fr: "le rhume", en: "the cold", de: "die Erkältung", alt: { de: ["der Schnupfen"] }, g: "m", kind: "noun", emoji: "🤧", note: tx("J'ai un rhume: I've got a cold. Atchoum!", "J'ai un rhume: Ich bin erkältet. Hatschi!") },
    { id: "nez", fr: "le nez", en: "the nose", de: "die Nase", g: "m", kind: "noun", emoji: "👃", note: tx("The z is silent: «nay». J'ai le nez qui coule: I've got a runny nose.", "Das z ist stumm: „neh“. J'ai le nez qui coule: Mir läuft die Nase.") },
    { id: "bon-retablissement", fr: "bon rétablissement !", en: "get well soon!", de: "gute Besserung!", kind: "phrase", note: tx("What you say to someone who is ill.", "Das sagt man zu jemandem, der krank ist.") },
  ],
  gloss: [
    { fr: "mal", en: "pain / sore", de: "Schmerz / weh" },
    { fr: "a mal", en: "hurts / has a pain", de: "hat Schmerzen / tut weh" },
    { fr: "as mal", en: "hurt (you) / have a pain", de: "hast Schmerzen / tut dir weh" },
    { fr: "reste", en: "stay / stays", de: "bleibe / bleibt" },
    { fr: "trop de", en: "too much / too many", de: "zu viel / zu viele" },
    { fr: "dois", en: "must / have to", de: "muss / musst" },
    { fr: "doit", en: "must / has to", de: "muss" },
    { fr: "devez", en: "must (you, plural / polite)", de: "müsst / müssen (Sie)" },
    { fr: "doivent", en: "must (they)", de: "müssen (sie)" },
    { fr: "faut", en: "must (il faut: you have to)", de: "muss (il faut: man muss)" },
    { fr: "boire", en: "to drink", de: "trinken" },
    { fr: "manger", en: "to eat", de: "essen" },
    { fr: "prendre", en: "to take", de: "nehmen" },
    { fr: "aller", en: "to go", de: "gehen" },
    { fr: "travailler", en: "to work", de: "arbeiten" },
    { fr: "reposer", en: "rest", de: "ausruhen" },
    { fr: "mieux", en: "better", de: "besser" },
    { fr: "je vais mieux", en: "I'm feeling better", de: "es geht mir besser" },
    { fr: "docteur", en: "doctor", de: "Doktor / Frau Doktor" },
    { fr: "médicaments", en: "medicines", de: "Medikamente" },
    { fr: "qui coule", en: "runny", de: "die läuft" },
    { fr: "atchoum", en: "atishoo", de: "hatschi" },
    { fr: "trente-neuf", en: "thirty-nine", de: "neununddreißig" },
  ],
  lessons: [
    { title: tx("It hurts!", "Es tut weh!"), words: ["j-ai-mal", "tete", "ventre", "dos", "malade"] },
    { title: tx("Arms and legs", "Arme und Beine"), words: ["bras", "jambe", "main", "pied", "dents"] },
    { title: tx("At the doctor's", "Beim Arzt"), words: ["medecin", "gorge", "fievre", "pharmacie", "oreille"] },
    { title: tx("I have to…", "Ich muss …"), words: ["je-dois", "tu-dois", "il-doit", "vous-devez"] },
    { title: tx("Rest and medicine", "Ruhe und Medikamente"), words: ["medicament", "se-reposer", "ca-va-mieux"] },
    { title: tx("We have to…", "Wir müssen …"), words: ["nous-devons", "ils-doivent", "il-faut", "rhume"] },
    { title: tx("Get well soon!", "Gute Besserung!"), words: ["nez", "bon-retablissement"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u17.01", lesson: 1, fr: "J'ai mal à la tête.", en: "I have a headache.", de: "Ich habe Kopfschmerzen.", alt: { en: ["My head hurts.", "I've got a headache.", "My head aches."], de: ["Mir tut der Kopf weh.", "Ich habe Kopfweh.", "Der Kopf tut mir weh."] } },
    { id: "u17.02", lesson: 1, fr: "Hugo a mal au ventre.", en: "Hugo has a stomach ache.", de: "Hugo hat Bauchschmerzen.", alt: { en: ["Hugo has a stomachache.", "Hugo has got a stomach ache.", "Hugo's stomach hurts.", "Hugo has a tummy ache.", "Hugo has got a tummy ache."], de: ["Hugo hat Bauchweh.", "Hugo tut der Bauch weh.", "Hugos Bauch tut weh."] } },
    { id: "u17.03", lesson: 1, fr: "Je suis malade aujourd'hui.", en: "I'm ill today.", de: "Ich bin heute krank.", alt: { fr: ["Aujourd'hui, je suis malade."], en: ["I'm sick today.", "Today I'm ill.", "Today I'm sick."], de: ["Heute bin ich krank."] } },
    { id: "u17.04", lesson: 1, fr: "Tu as mal au dos ?", en: "Does your back hurt?", de: "Tut dir der Rücken weh?", alt: { fr: ["Est-ce que tu as mal au dos ?", "As-tu mal au dos ?", "Vous avez mal au dos ?", "Est-ce que vous avez mal au dos ?", "Avez-vous mal au dos ?"], en: ["Have you got backache?", "Do you have backache?", "Do you have a backache?", "Have you got a backache?", "Is your back hurting?", "Does your back ache?"], de: ["Hast du Rückenschmerzen?", "Tut dir dein Rücken weh?"] } },
    { id: "u17.05", lesson: 1, fr: "Léa est malade, elle reste à la maison.", en: "Léa is ill, she's staying at home.", de: "Léa ist krank, sie bleibt zu Hause.", alt: { en: ["Léa is sick, she's staying at home.", "Léa is ill, she's staying home.", "Léa is sick, she's staying home.", "Léa is ill, she stays at home.", "Léa is ill, so she's staying at home."], de: ["Léa ist krank, sie bleibt daheim.", "Léa ist krank und bleibt zu Hause."] } },
    { id: "u17.06", lesson: 1, fr: "J'ai mal au ventre : j'ai mangé trop de gâteau.", en: "My stomach hurts: I ate too much cake.", de: "Ich habe Bauchschmerzen: Ich habe zu viel Kuchen gegessen.", alt: { en: ["I have a stomach ache: I ate too much cake.", "I've got a stomach ache: I ate too much cake.", "My stomach hurts: I've eaten too much cake.", "I have a stomach ache: I've eaten too much cake.", "I've got a stomach ache: I've eaten too much cake.", "I have a tummy ache: I ate too much cake."], de: ["Mir tut der Bauch weh: Ich habe zu viel Kuchen gegessen.", "Ich habe Bauchweh: Ich habe zu viel Kuchen gegessen."] } },
    { id: "u17.07", lesson: 1, fr: "Ma grand-mère a mal au dos.", en: "My grandmother has backache.", de: "Meine Großmutter hat Rückenschmerzen.", alt: { en: ["My grandmother has a backache.", "My grandmother has back pain.", "My grandmother's back hurts.", "My grandma has backache.", "My grandmother has got backache."], de: ["Meiner Großmutter tut der Rücken weh.", "Meine Oma hat Rückenschmerzen.", "Meine Großmutter hat Rückenweh."] } },
    // Lesson 2
    { id: "u17.08", lesson: 2, fr: "J'ai mal aux dents.", en: "I have toothache.", de: "Ich habe Zahnschmerzen.", alt: { en: ["I've got toothache.", "I have a toothache.", "My teeth hurt.", "I've got a toothache."], de: ["Mir tun die Zähne weh.", "Ich habe Zahnweh."] } },
    { id: "u17.09", lesson: 2, fr: "Blob a mal au pied.", en: "Blob's foot hurts.", de: "Blob tut der Fuß weh.", alt: { en: ["Blob has a sore foot.", "Blob has got a sore foot.", "Blob has foot pain."], de: ["Blob hat Fußschmerzen.", "Blobs Fuß tut weh."] } },
    { id: "u17.10", lesson: 2, fr: "Tu as mal à la jambe ?", en: "Does your leg hurt?", de: "Tut dir das Bein weh?", alt: { fr: ["Est-ce que tu as mal à la jambe ?", "As-tu mal à la jambe ?", "Vous avez mal à la jambe ?", "Est-ce que vous avez mal à la jambe ?", "Avez-vous mal à la jambe ?"], en: ["Is your leg hurting?", "Have you got a sore leg?", "Do you have a sore leg?"], de: ["Tut dir dein Bein weh?", "Hast du Schmerzen im Bein?"] } },
    { id: "u17.11", lesson: 2, fr: "Il a mal au bras et à la main.", en: "His arm and his hand hurt.", de: "Ihm tun der Arm und die Hand weh.", alt: { en: ["His arm and hand hurt.", "He has a sore arm and a sore hand.", "He's got a sore arm and a sore hand."], de: ["Ihm tun Arm und Hand weh.", "Er hat Schmerzen im Arm und in der Hand."] } },
    { id: "u17.12", lesson: 2, fr: "Après le foot, j'ai mal aux jambes.", en: "After football, my legs hurt.", de: "Nach dem Fußball tun mir die Beine weh.", alt: { fr: ["J'ai mal aux jambes après le foot."], en: ["After football my legs ache.", "After football I have sore legs.", "My legs hurt after football.", "After football my legs are sore.", "After football I've got sore legs."], de: ["Nach dem Fußball tun meine Beine weh.", "Nach dem Fußballspielen tun mir die Beine weh.", "Mir tun nach dem Fußball die Beine weh."] } },
    { id: "u17.13", lesson: 2, fr: "Ma petite sœur a mal aux dents.", en: "My little sister has toothache.", de: "Meine kleine Schwester hat Zahnschmerzen.", alt: { en: ["My little sister has a toothache.", "My little sister's teeth hurt.", "My little sister has got toothache.", "My younger sister has toothache."], de: ["Meiner kleinen Schwester tun die Zähne weh.", "Meine kleine Schwester hat Zahnweh."] } },
    { id: "u17.14", lesson: 2, fr: "Hier, j'ai joué au tennis, et j'ai mal au bras.", en: "Yesterday I played tennis, and my arm hurts.", de: "Gestern habe ich Tennis gespielt, und mir tut der Arm weh.", alt: { fr: ["J'ai joué au tennis hier, et j'ai mal au bras."], en: ["Yesterday I played tennis and now my arm hurts.", "I played tennis yesterday, and my arm hurts.", "Yesterday I played tennis, and I have a sore arm.", "Yesterday I played tennis, and I've got a sore arm."], de: ["Gestern habe ich Tennis gespielt, und jetzt tut mir der Arm weh.", "Ich habe gestern Tennis gespielt, und mir tut der Arm weh.", "Gestern habe ich Tennis gespielt und habe Schmerzen im Arm."] } },
    // Lesson 3
    { id: "u17.15", lesson: 3, fr: "J'ai mal à la gorge.", en: "I have a sore throat.", de: "Ich habe Halsschmerzen.", alt: { en: ["I've got a sore throat.", "My throat hurts."], de: ["Mir tut der Hals weh.", "Ich habe Halsweh."] } },
    { id: "u17.16", lesson: 3, fr: "Il a de la fièvre.", en: "He has a temperature.", de: "Er hat Fieber.", alt: { en: ["He has a fever.", "He's got a temperature.", "He's got a fever."] } },
    { id: "u17.17", lesson: 3, fr: "Je vais chez le médecin.", en: "I'm going to the doctor's.", de: "Ich gehe zum Arzt.", alt: { en: ["I'm going to the doctor.", "I go to the doctor's.", "I go to the doctor."], de: ["Ich gehe zur Ärztin.", "Ich gehe zum Doktor."] } },
    { id: "u17.18", lesson: 3, fr: "La pharmacie est à côté de la gare.", en: "The chemist's is next to the station.", de: "Die Apotheke ist neben dem Bahnhof.", alt: { en: ["The pharmacy is next to the station.", "The chemist is next to the station.", "The chemist's is beside the station.", "The pharmacy is beside the station."] } },
    { id: "u17.19", lesson: 3, fr: "Tu as mal à l'oreille ?", en: "Does your ear hurt?", de: "Tut dir das Ohr weh?", alt: { fr: ["Est-ce que tu as mal à l'oreille ?", "As-tu mal à l'oreille ?", "Vous avez mal à l'oreille ?", "Est-ce que vous avez mal à l'oreille ?", "Avez-vous mal à l'oreille ?"], en: ["Have you got earache?", "Do you have earache?", "Do you have an earache?", "Is your ear hurting?"], de: ["Hast du Ohrenschmerzen?", "Tut dir dein Ohr weh?"] } },
    { id: "u17.20", lesson: 3, fr: "Bonjour, Docteur. J'ai de la fièvre.", en: "Hello, Doctor. I have a temperature.", de: "Guten Tag, Frau Doktor. Ich habe Fieber.", alt: { en: ["Hello, Doctor. I have a fever.", "Hello, Doctor. I've got a temperature.", "Hello, Doctor. I've got a fever.", "Good morning, Doctor. I have a temperature."], de: ["Hallo, Frau Doktor. Ich habe Fieber.", "Guten Tag, Doktor. Ich habe Fieber.", "Guten Morgen, Frau Doktor. Ich habe Fieber."] } },
    { id: "u17.21", lesson: 3, fr: "La médecin est très gentille.", en: "The doctor is very kind.", de: "Die Ärztin ist sehr nett.", alt: { fr: ["Le médecin est très gentil."], en: ["The doctor is very nice."], de: ["Die Ärztin ist sehr freundlich.", "Die Ärztin ist sehr lieb."] } },
    // Lesson 4
    { id: "u17.22", lesson: 4, fr: "Je dois aller chez le médecin.", en: "I have to go to the doctor's.", de: "Ich muss zum Arzt gehen.", alt: { en: ["I have to go to the doctor.", "I must go to the doctor's.", "I must go to the doctor.", "I need to go to the doctor's.", "I need to go to the doctor.", "I've got to go to the doctor's.", "I've got to go to the doctor."], de: ["Ich muss zum Arzt.", "Ich muss zur Ärztin gehen.", "Ich muss zur Ärztin.", "Ich muss zum Doktor gehen."] } },
    { id: "u17.23", lesson: 4, fr: "Tu dois boire beaucoup d'eau.", en: "You must drink a lot of water.", de: "Du musst viel Wasser trinken.", alt: { fr: ["Vous devez boire beaucoup d'eau."], en: ["You have to drink a lot of water.", "You must drink lots of water.", "You have to drink lots of water.", "You need to drink a lot of water.", "You should drink a lot of water."], de: ["Ihr müsst viel Wasser trinken.", "Sie müssen viel Wasser trinken.", "Du solltest viel Wasser trinken."] } },
    { id: "u17.24", lesson: 4, fr: "Il doit rester au lit.", en: "He has to stay in bed.", de: "Er muss im Bett bleiben.", alt: { en: ["He must stay in bed.", "He needs to stay in bed.", "He's got to stay in bed."] } },
    { id: "u17.25", lesson: 4, fr: "Vous devez rester à la maison, Madame Martin.", en: "You have to stay at home, Mrs Martin.", de: "Sie müssen zu Hause bleiben, Frau Martin.", alt: { fr: ["Madame Martin, vous devez rester à la maison."], en: ["You must stay at home, Mrs Martin.", "You need to stay at home, Mrs Martin.", "You have to stay home, Mrs Martin.", "Mrs Martin, you have to stay at home."], de: ["Frau Martin, Sie müssen zu Hause bleiben."] } },
    { id: "u17.26", lesson: 4, fr: "Tu ne dois pas manger de chocolat.", en: "You mustn't eat chocolate.", de: "Du darfst keine Schokolade essen.", alt: { fr: ["Vous ne devez pas manger de chocolat."], en: ["You must not eat chocolate.", "You mustn't eat any chocolate.", "You must not eat any chocolate.", "You can't eat chocolate."], de: ["Ihr dürft keine Schokolade essen.", "Sie dürfen keine Schokolade essen.", "Du sollst keine Schokolade essen."] } },
    { id: "u17.27", lesson: 4, fr: "Je dois faire mes devoirs.", en: "I have to do my homework.", de: "Ich muss meine Hausaufgaben machen.", alt: { en: ["I must do my homework.", "I need to do my homework.", "I've got to do my homework."] } },
    { id: "u17.28", lesson: 4, fr: "Hugo est malade, il doit dormir.", en: "Hugo is ill, he has to sleep.", de: "Hugo ist krank, er muss schlafen.", alt: { en: ["Hugo is sick, he has to sleep.", "Hugo is ill, he must sleep.", "Hugo is ill, he needs to sleep.", "Hugo is sick, he needs to sleep.", "Hugo is ill and he has to sleep."], de: ["Hugo ist krank und muss schlafen."] } },
    // Lesson 5
    { id: "u17.29", lesson: 5, fr: "Vous devez prendre ce médicament.", en: "You have to take this medicine.", de: "Sie müssen dieses Medikament nehmen.", alt: { fr: ["Tu dois prendre ce médicament."], en: ["You must take this medicine.", "You need to take this medicine.", "You have to take this medication.", "You must take this medication."], de: ["Ihr müsst dieses Medikament nehmen.", "Du musst dieses Medikament nehmen.", "Sie müssen diese Medizin nehmen."] } },
    { id: "u17.30", lesson: 5, fr: "Tu dois te reposer.", en: "You have to rest.", de: "Du musst dich ausruhen.", alt: { fr: ["Vous devez vous reposer."], en: ["You must rest.", "You need to rest.", "You should rest."], de: ["Ihr müsst euch ausruhen.", "Sie müssen sich ausruhen.", "Du solltest dich ausruhen."] } },
    { id: "u17.31", lesson: 5, fr: "Ça va mieux aujourd'hui ?", en: "Are you feeling better today?", de: "Geht es dir heute besser?", alt: { fr: ["Est-ce que ça va mieux aujourd'hui ?", "Tu vas mieux aujourd'hui ?", "Vous allez mieux aujourd'hui ?", "Aujourd'hui, ça va mieux ?"], en: ["Are you better today?", "Do you feel better today?", "Is it better today?"], de: ["Geht's dir heute besser?", "Geht es heute besser?", "Geht es Ihnen heute besser?"] } },
    { id: "u17.32", lesson: 5, fr: "Oui, merci, ça va mieux.", en: "Yes, thank you, I'm feeling better.", de: "Ja, danke, es geht mir besser.", alt: { fr: ["Oui, merci, je vais mieux."], en: ["Yes, thanks, I'm feeling better.", "Yes, thank you, I feel better.", "Yes, thanks, I feel better.", "Yes, thank you, I'm better.", "Yes, thanks, I'm better.", "Yes, thank you, it's better."], de: ["Ja, danke, mir geht's besser.", "Ja, danke, mir geht es besser.", "Ja, danke, es geht besser."] } },
    { id: "u17.33", lesson: 5, fr: "Je me couche tôt, je dois me reposer.", en: "I'm going to bed early, I have to rest.", de: "Ich gehe früh ins Bett, ich muss mich ausruhen.", alt: { en: ["I go to bed early, I have to rest.", "I'm going to bed early, I need to rest.", "I go to bed early, I need to rest.", "I'm going to bed early, I must rest.", "I go to bed early because I have to rest."], de: ["Ich gehe früh schlafen, ich muss mich ausruhen.", "Ich gehe früh ins Bett, weil ich mich ausruhen muss."] } },
    { id: "u17.34", lesson: 5, fr: "Je vais acheter un médicament à la pharmacie.", en: "I'm going to buy some medicine at the chemist's.", de: "Ich werde in der Apotheke ein Medikament kaufen.", alt: { en: ["I'm going to buy medicine at the chemist's.", "I will buy some medicine at the chemist's.", "I'm going to buy some medicine at the pharmacy.", "I will buy some medicine at the pharmacy.", "I'm going to buy medicine at the pharmacy.", "I'm going to buy a medicine at the chemist's."], de: ["Ich kaufe in der Apotheke ein Medikament.", "Ich werde ein Medikament in der Apotheke kaufen.", "Ich kaufe ein Medikament in der Apotheke."] } },
    { id: "u17.35", lesson: 5, fr: "Prends ton médicament, Hugo !", en: "Take your medicine, Hugo!", de: "Nimm dein Medikament, Hugo!", alt: { fr: ["Hugo, prends ton médicament !"], en: ["Hugo, take your medicine!"], de: ["Hugo, nimm dein Medikament!", "Nimm deine Medizin, Hugo!"] } },
    // Lesson 6
    { id: "u17.36", lesson: 6, fr: "Nous devons aller à la pharmacie.", en: "We have to go to the chemist's.", de: "Wir müssen in die Apotheke gehen.", alt: { fr: ["On doit aller à la pharmacie."], en: ["We must go to the chemist's.", "We need to go to the chemist's.", "We have to go to the pharmacy.", "We must go to the pharmacy.", "We need to go to the pharmacy."], de: ["Wir müssen zur Apotheke gehen.", "Wir müssen in die Apotheke.", "Wir müssen zur Apotheke."] } },
    { id: "u17.37", lesson: 6, fr: "Ils doivent rester à la maison.", en: "They have to stay at home.", de: "Sie müssen zu Hause bleiben.", alt: { fr: ["Elles doivent rester à la maison."], en: ["They must stay at home.", "They need to stay at home.", "They have to stay home."], de: ["Sie müssen daheim bleiben."] } },
    { id: "u17.38", lesson: 6, fr: "Il faut boire de l'eau.", en: "You have to drink water.", de: "Man muss Wasser trinken.", alt: { fr: ["Tu dois boire de l'eau.", "Vous devez boire de l'eau.", "On doit boire de l'eau."], en: ["One must drink water.", "You need to drink water.", "You must drink water."] } },
    { id: "u17.39", lesson: 6, fr: "J'ai un rhume, je reste à la maison.", en: "I have a cold, I'm staying at home.", de: "Ich habe eine Erkältung, ich bleibe zu Hause.", alt: { en: ["I've got a cold, I'm staying at home.", "I have a cold, I'm staying home.", "I've got a cold, I'm staying home.", "I have a cold, so I'm staying at home.", "I have a cold, I stay at home."], de: ["Ich bin erkältet, ich bleibe zu Hause.", "Ich habe einen Schnupfen, ich bleibe zu Hause.", "Ich habe eine Erkältung und bleibe zu Hause."] } },
    { id: "u17.40", lesson: 6, fr: "Avec un rhume, il faut beaucoup dormir.", en: "With a cold, you have to sleep a lot.", de: "Mit einer Erkältung muss man viel schlafen.", alt: { fr: ["Avec un rhume, il faut dormir beaucoup.", "Il faut beaucoup dormir avec un rhume.", "Il faut dormir beaucoup avec un rhume."], en: ["With a cold, you need to sleep a lot.", "With a cold, you must sleep a lot.", "With a cold, one must sleep a lot.", "When you have a cold, you have to sleep a lot."] } },
    { id: "u17.41", lesson: 6, fr: "Est-ce que je dois aller chez le médecin ?", en: "Do I have to go to the doctor's?", de: "Muss ich zum Arzt gehen?", alt: { fr: ["Je dois aller chez le médecin ?", "Dois-je aller chez le médecin ?", "Il faut aller chez le médecin ?", "Est-ce qu'il faut aller chez le médecin ?"], en: ["Do I have to go to the doctor?", "Must I go to the doctor's?", "Do I need to go to the doctor's?", "Do I need to go to the doctor?", "Should I go to the doctor's?", "Should I go to the doctor?"], de: ["Muss ich zum Arzt?", "Muss ich zur Ärztin gehen?", "Muss ich zum Doktor gehen?"] } },
    { id: "u17.42", lesson: 6, fr: "Hier, je suis resté au lit.", en: "Yesterday I stayed in bed.", de: "Gestern bin ich im Bett geblieben.", alt: { fr: ["Hier, je suis restée au lit.", "Je suis resté au lit hier.", "Je suis restée au lit hier."], en: ["I stayed in bed yesterday."], de: ["Ich bin gestern im Bett geblieben.", "Gestern blieb ich im Bett."] } },
    { id: "u17.43", lesson: 6, fr: "Mes parents doivent travailler demain.", en: "My parents have to work tomorrow.", de: "Meine Eltern müssen morgen arbeiten.", alt: { fr: ["Demain, mes parents doivent travailler."], en: ["My parents must work tomorrow.", "My parents need to work tomorrow.", "My parents have got to work tomorrow."], de: ["Morgen müssen meine Eltern arbeiten."] } },
    // Lesson 7
    { id: "u17.44", lesson: 7, fr: "J'ai le nez qui coule.", en: "I have a runny nose.", de: "Mir läuft die Nase.", alt: { en: ["I've got a runny nose.", "My nose is running."], de: ["Ich habe eine laufende Nase.", "Meine Nase läuft."] } },
    { id: "u17.45", lesson: 7, fr: "Bon rétablissement, Madame Martin !", en: "Get well soon, Mrs Martin!", de: "Gute Besserung, Frau Martin!", alt: { en: ["Get better soon, Mrs Martin!"] } },
    { id: "u17.46", lesson: 7, fr: "Tu as un rhume ? Bois du thé chaud !", en: "Have you got a cold? Drink some hot tea!", de: "Hast du eine Erkältung? Trink heißen Tee!", alt: { fr: ["Vous avez un rhume ? Buvez du thé chaud !", "Tu as un rhume ? Bois un thé chaud !"], en: ["Do you have a cold? Drink some hot tea!", "Have you got a cold? Drink hot tea!", "Do you have a cold? Drink hot tea!"], de: ["Bist du erkältet? Trink heißen Tee!", "Hast du eine Erkältung? Trink einen heißen Tee!", "Bist du erkältet? Trink einen heißen Tee!"] } },
    { id: "u17.47", lesson: 7, fr: "Il ne faut pas manger trop de bonbons.", en: "You mustn't eat too many sweets.", de: "Man darf nicht zu viele Bonbons essen.", alt: { fr: ["Tu ne dois pas manger trop de bonbons.", "Vous ne devez pas manger trop de bonbons.", "On ne doit pas manger trop de bonbons."], en: ["You must not eat too many sweets.", "One must not eat too many sweets.", "You shouldn't eat too many sweets.", "You mustn't eat too much candy."], de: ["Man soll nicht zu viele Bonbons essen.", "Man sollte nicht zu viele Süßigkeiten essen.", "Man darf nicht zu viele Süßigkeiten essen.", "Man sollte nicht zu viele Bonbons essen."] } },
    { id: "u17.48", lesson: 7, fr: "Léa a de la fièvre, elle ne va pas à l'école.", en: "Léa has a temperature, she isn't going to school.", de: "Léa hat Fieber, sie geht nicht in die Schule.", alt: { en: ["Léa has a fever, she isn't going to school.", "Léa has a temperature, so she isn't going to school.", "Léa has a fever, so she isn't going to school.", "Léa has a temperature and isn't going to school."], de: ["Léa hat Fieber, sie geht nicht zur Schule.", "Léa hat Fieber und geht nicht in die Schule.", "Léa hat Fieber und geht nicht zur Schule."] } },
    { id: "u17.49", lesson: 7, fr: "Tu as mal où ?", en: "Where does it hurt?", de: "Wo tut es dir weh?", alt: { fr: ["Où as-tu mal ?", "Où est-ce que tu as mal ?", "Où avez-vous mal ?", "Vous avez mal où ?", "Où est-ce que vous avez mal ?"], en: ["Where are you hurting?", "Where do you have pain?"], de: ["Wo tut's dir weh?", "Wo hast du Schmerzen?", "Wo tut es weh?"] } },
    { id: "u17.50", lesson: 7, fr: "Merci, Docteur, je vais mieux !", en: "Thank you, Doctor, I'm feeling better!", de: "Danke, Frau Doktor, es geht mir besser!", alt: { fr: ["Merci, Docteur, ça va mieux !"], en: ["Thank you, Doctor, I feel better!", "Thanks, Doctor, I feel better!", "Thank you, Doctor, I'm better!", "Thanks, Doctor, I'm feeling better!", "Thanks, Doctor, I'm better!"], de: ["Danke, Frau Doktor, mir geht's besser!", "Danke, Frau Doktor, mir geht es besser!", "Danke, Doktor, es geht mir besser!"] } },
  ],
  drills: [
    { id: "u17.d1", lesson: 1, fr: "J'ai mal ___ tête.", options: ["à la", "au", "à le"], answer: 0, en: "I have a headache.", de: "Ich habe Kopfschmerzen.", why: tx("Tête is feminine: à + la stays **à la**: j'ai mal **à la** tête.", "Tête ist weiblich: à + la bleibt **à la**: j'ai mal **à la** tête.") },
    { id: "u17.d2", lesson: 1, fr: "Hugo a mal ___ ventre.", options: ["au", "à la", "à le"], answer: 0, en: "Hugo has a stomach ache.", de: "Hugo hat Bauchschmerzen.", why: tx("Ventre is masculine, and à + le always becomes **au**: mal **au** ventre.", "Ventre ist männlich, und à + le wird immer zu **au**: mal **au** ventre.") },
    { id: "u17.d3", lesson: 1, fr: "Tu ___ mal au dos ?", options: ["as", "es", "est"], answer: 0, en: "Does your back hurt?", de: "Tut dir der Rücken weh?", why: tx("In French you **have** pain: avoir mal. Tu **as** mal, never tu es mal.", "Auf Französisch **hat** man Schmerz: avoir mal. Tu **as** mal, nie tu es mal.") },
    { id: "u17.d4", lesson: 2, fr: "J'ai mal ___ dents.", options: ["aux", "à les", "au"], answer: 0, en: "I have toothache.", de: "Ich habe Zahnschmerzen.", why: tx("Dents is plural: à + les becomes **aux**: mal **aux** dents.", "Dents ist Plural: à + les wird zu **aux**: mal **aux** dents.") },
    { id: "u17.d5", lesson: 2, fr: "Blob a mal ___ pied.", options: ["au", "à la", "aux"], answer: 0, en: "Blob's foot hurts.", de: "Blob tut der Fuß weh.", why: tx("Pied is masculine and singular: **au** pied. Both feet: aux pieds.", "Pied ist männlich und Singular: **au** pied. Beide Füße: aux pieds.") },
    { id: "u17.d6", lesson: 3, fr: "J'ai mal ___.", options: ["à l'oreille", "à la oreille", "au oreille"], answer: 0, en: "My ear hurts.", de: "Mir tut das Ohr weh.", why: tx("Oreille starts with a vowel: à + l' gives **à l'oreille**.", "Oreille beginnt mit einem Vokal: à + l' ergibt **à l'oreille**.") },
    { id: "u17.d7", lesson: 3, fr: "Il a ___ fièvre.", options: ["de la", "du", "des"], answer: 0, en: "He has a temperature.", de: "Er hat Fieber.", why: tx("Fièvre is feminine: **de la** fièvre.", "Fièvre ist weiblich: **de la** fièvre.") },
    { id: "u17.d8", lesson: 3, fr: "Je vais ___ le médecin.", options: ["chez", "à", "au"], answer: 0, en: "I'm going to the doctor's.", de: "Ich gehe zum Arzt.", why: tx("To a person, it's **chez**: chez le médecin, chez Léa. À is for places: à la pharmacie.", "Zu einer Person heißt es **chez**: chez le médecin, chez Léa. À steht bei Orten: à la pharmacie.") },
    { id: "u17.d9", lesson: 4, fr: "Je ___ aller chez le médecin.", options: ["dois", "doit", "devez"], answer: 0, en: "I have to go to the doctor's.", de: "Ich muss zum Arzt gehen.", why: tx("With **je**: je **dois**, with an s.", "Mit **je**: je **dois**, mit s.") },
    { id: "u17.d10", lesson: 4, fr: "Vous ___ rester à la maison, Madame Martin.", options: ["devez", "doit", "dois"], answer: 0, en: "You have to stay at home, Mrs Martin.", de: "Sie müssen zu Hause bleiben, Frau Martin.", why: tx("With **vous**: vous **devez**. Devoir changes a lot: je dois, but vous devez.", "Mit **vous**: vous **devez**. Devoir ändert sich stark: je dois, aber vous devez.") },
    { id: "u17.d11", lesson: 4, fr: "Tu dois ___ beaucoup d'eau.", options: ["boire", "bois", "boit"], answer: 0, en: "You must drink a lot of water.", de: "Du musst viel Wasser trinken.", why: tx("After **devoir**, the second verb stays in the infinitive: tu dois **boire**.", "Nach **devoir** bleibt das zweite Verb im Infinitiv: tu dois **boire**.") },
    { id: "u17.d12", lesson: 5, fr: "Tu dois ___ reposer.", options: ["te", "me", "se"], answer: 0, en: "You have to rest.", de: "Du musst dich ausruhen.", why: tx("Se reposer is reflexive: the little word matches the person. Tu dois **te** reposer, je dois me reposer.", "Se reposer ist reflexiv: Das kleine Wort passt zur Person. Tu dois **te** reposer, je dois me reposer.") },
    { id: "u17.d13", lesson: 5, fr: "Oui, merci, ça va ___.", options: ["mieux", "bon"], answer: 0, en: "Yes, thank you, I'm feeling better.", de: "Ja, danke, es geht mir besser.", why: tx("**Mieux** means better: ça va mieux. Bon means good, and it doesn't go with ça va.", "**Mieux** heißt besser: ça va mieux. Bon heißt gut und passt nicht zu ça va.") },
    { id: "u17.d14", lesson: 6, fr: "Nous ___ aller à la pharmacie.", options: ["devons", "devez", "doivent"], answer: 0, en: "We have to go to the chemist's.", de: "Wir müssen in die Apotheke gehen.", why: tx("With **nous**: nous **devons**.", "Mit **nous**: nous **devons**.") },
    { id: "u17.d15", lesson: 6, fr: "Ils ___ rester à la maison.", options: ["doivent", "doit", "devons"], answer: 0, en: "They have to stay at home.", de: "Sie müssen zu Hause bleiben.", why: tx("With **ils / elles**: ils **doivent**. Here you hear the v.", "Mit **ils / elles**: ils **doivent**. Hier hört man das v.") },
    { id: "u17.d16", lesson: 6, fr: "Hier, ___ resté au lit.", options: ["je suis", "j'ai"], answer: 0, en: "Yesterday I stayed in bed.", de: "Gestern bin ich im Bett geblieben.", why: tx("Rester takes **être** in the past, like aller: **je suis** resté, never j'ai resté.", "Rester bildet die Vergangenheit mit **être**, wie aller: **je suis** resté, nie j'ai resté.") },
    { id: "u17.d17", lesson: 7, fr: "Il ne faut pas manger ___ bonbons.", options: ["trop de", "trop des"], answer: 0, en: "You mustn't eat too many sweets.", de: "Man darf nicht zu viele Bonbons essen.", why: tx("After **trop**, just **de**, like after beaucoup: trop **de** bonbons.", "Nach **trop** steht nur **de**, wie nach beaucoup: trop **de** bonbons.") },
    { id: "u17.d18", lesson: 7, fr: "Merci, Docteur, je ___ mieux !", options: ["vais", "suis"], answer: 0, en: "Thank you, Doctor, I'm feeling better!", de: "Danke, Frau Doktor, es geht mir besser!", why: tx("Feeling better goes with aller: je **vais** mieux, ça va mieux. Not je suis mieux.", "Besser gehen heißt mit aller: je **vais** mieux, ça va mieux. Nicht je suis mieux.") },
  ],
  dialogues: [
    {
      id: "u17.dialogue",
      lesson: 5,
      title: tx("Hugo at the doctor's", "Hugo bei der Ärztin"),
      lines: [
        { who: "medecin", fr: "Bonjour, Hugo. Tu as mal où ?", en: "Hello, Hugo. Where does it hurt?", de: "Hallo, Hugo. Wo tut es dir weh?" },
        { who: "hugo", fr: "J'ai mal à la tête et à la gorge.", en: "I've got a headache and a sore throat.", de: "Ich habe Kopfschmerzen und Halsschmerzen." },
        { who: "medecin", fr: "Tu as de la fièvre ?", en: "Have you got a temperature?", de: "Hast du Fieber?" },
        { who: "hugo", fr: "Oui, trente-neuf.", en: "Yes, thirty-nine degrees.", de: "Ja, neununddreißig Grad." },
        { who: "medecin", fr: "Tu es malade. Tu dois rester au lit et boire beaucoup d'eau.", en: "You're ill. You have to stay in bed and drink a lot of water.", de: "Du bist krank. Du musst im Bett bleiben und viel Wasser trinken." },
        { who: "hugo", fr: "Et l'école ? Je dois aller à l'école demain ?", en: "And school? Do I have to go to school tomorrow?", de: "Und die Schule? Muss ich morgen in die Schule?" },
        { who: "medecin", fr: "Non, tu dois te reposer. Voilà un médicament.", en: "No, you have to rest. Here's some medicine.", de: "Nein, du musst dich ausruhen. Hier ist ein Medikament." },
        { who: "hugo", fr: "Super ! Pas d'école !", en: "Great! No school!", de: "Super! Keine Schule!" },
        { who: "medecin", fr: "Et pas de jeux vidéo ! Tu dois dormir.", en: "And no video games! You have to sleep.", de: "Und keine Videospiele! Du musst schlafen." },
        { who: "hugo", fr: "Oh non…", en: "Oh no…", de: "Oh nein …" },
      ],
      questions: [
        { q: tx("What hurts?", "Was tut Hugo weh?"), options: [tx("His head and his throat", "Kopf und Hals"), tx("His stomach", "Der Bauch"), tx("His foot", "Der Fuß")], answer: 0 },
        { q: tx("What does the doctor say?", "Was sagt die Ärztin?"), options: [tx("Stay in bed and drink a lot of water.", "Im Bett bleiben und viel Wasser trinken."), tx("Go to school tomorrow.", "Morgen in die Schule gehen."), tx("Play video games.", "Videospiele spielen.")], answer: 0 },
        { q: tx("Why does Hugo say «Oh no…»?", "Warum sagt Hugo „Oh nein …“?"), options: [tx("No video games!", "Keine Videospiele!"), tx("He has to go to school.", "Er muss in die Schule."), tx("The medicine is expensive.", "Das Medikament ist teuer.")], answer: 0 },
      ],
    },
    {
      id: "u17.dialogue2",
      lesson: 7,
      title: tx("Soup for Mrs Martin", "Suppe für Frau Martin"),
      lines: [
        { who: "lea", fr: "Bonjour, Madame Martin ! Ça va mieux ?", en: "Hello, Mrs Martin! Are you feeling better?", de: "Guten Tag, Frau Martin! Geht es Ihnen besser?" },
        { who: "madame", fr: "Non, pas encore. J'ai un rhume et j'ai le nez qui coule.", en: "No, not yet. I've got a cold and a runny nose.", de: "Nein, noch nicht. Ich bin erkältet und mir läuft die Nase." },
        { who: "blob", fr: "Voilà une soupe pour vous ! Il faut manger quand on est malade.", en: "Here's some soup for you! You have to eat when you're ill.", de: "Hier ist eine Suppe für Sie! Wenn man krank ist, muss man essen." },
        { who: "madame", fr: "Merci, Blob, c'est très gentil.", en: "Thank you, Blob, that's very kind.", de: "Danke, Blob, das ist sehr lieb." },
        { who: "lea", fr: "Vous avez des médicaments ?", en: "Have you got any medicine?", de: "Haben Sie Medikamente?" },
        { who: "madame", fr: "Non, je dois aller à la pharmacie demain.", en: "No, I have to go to the chemist's tomorrow.", de: "Nein, ich muss morgen in die Apotheke." },
        { who: "blob", fr: "Vous devez vous reposer ! Nous allons à la pharmacie pour vous.", en: "You have to rest! We'll go to the chemist's for you.", de: "Sie müssen sich ausruhen! Wir gehen für Sie in die Apotheke." },
        { who: "madame", fr: "Merci ! Vous êtes très gentils.", en: "Thank you! You're very kind.", de: "Danke! Ihr seid sehr lieb." },
        { who: "lea", fr: "Bon rétablissement, Madame Martin !", en: "Get well soon, Mrs Martin!", de: "Gute Besserung, Frau Martin!" },
        { who: "blob", fr: "Atchoum ! Oh là là… j'ai un rhume aussi !", en: "Atishoo! Oh dear… I've got a cold too!", de: "Hatschi! Oje … ich bin auch erkältet!" },
      ],
      questions: [
        { q: tx("What's wrong with Mrs Martin?", "Was hat Frau Martin?"), options: [tx("She has a cold and a runny nose.", "Sie ist erkältet und ihr läuft die Nase."), tx("She has a stomach ache.", "Sie hat Bauchschmerzen."), tx("She has a sore foot.", "Ihr tut der Fuß weh.")], answer: 0 },
        { q: tx("What does Blob bring?", "Was bringt Blob mit?"), options: [tx("Some soup", "Eine Suppe"), tx("Some medicine", "Medikamente"), tx("A cake", "Einen Kuchen")], answer: 0 },
        { q: tx("Who goes to the chemist's?", "Wer geht in die Apotheke?"), options: [tx("Léa and Blob", "Léa und Blob"), tx("Mrs Martin", "Frau Martin"), tx("The doctor", "Die Ärztin")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("J'ai mal à…: what hurts", "J'ai mal à …: Was wehtut"),
      body: tx(
        "To say what hurts, use **avoir mal à** + the body part. À joins the article, just like with places in town: **au** dos, **à la** tête, **à l'**oreille, **aux** dents.\n\nCareful: in French you **have** pain. It's **j'ai mal**, never je suis mal.",
        "Um zu sagen, was wehtut, nimmst du **avoir mal à** + Körperteil. À verbindet sich mit dem Artikel, genau wie bei Orten in der Stadt: **au** dos, **à la** tête, **à l'**oreille, **aux** dents.\n\nVorsicht: Auf Französisch **hat** man Schmerz. Es heißt **j'ai mal**, nie je suis mal.",
      ),
      examples: [
        { fr: "J'ai mal à la tête.", en: "I have a headache.", de: "Ich habe Kopfschmerzen." },
        { fr: "Hugo a mal au ventre.", en: "Hugo has a stomach ache.", de: "Hugo hat Bauchschmerzen." },
        { fr: "J'ai mal aux dents.", en: "I have toothache.", de: "Ich habe Zahnschmerzen." },
      ],
      table: {
        head: [tx("article", "Artikel"), tx("with à", "mit à"), tx("example", "Beispiel")],
        rows: [
          ["le", "au", "j'ai mal au dos"],
          ["la", "à la", "j'ai mal à la gorge"],
          ["l'", "à l'", "j'ai mal à l'oreille"],
          ["les", "aux", "j'ai mal aux jambes"],
        ],
      },
    },
    {
      title: tx("Devoir: I must", "Devoir: Ich muss"),
      body: tx(
        "**Devoir** + infinitive means must or have to: je **dois** rester au lit. The second verb doesn't change: tu dois **boire**, il doit **dormir**.\n\nDevoir is irregular, so learn it as a table. Negative: je **ne** dois **pas** manger de chocolat (I mustn't).",
        "**Devoir** + Infinitiv heißt müssen: je **dois** rester au lit. Das zweite Verb ändert sich nicht: tu dois **boire**, il doit **dormir**.\n\nDevoir ist unregelmäßig, also lern es als Tabelle. Verneint: je **ne** dois **pas** manger de chocolat (ich darf nicht).",
      ),
      examples: [
        { fr: "Je dois aller chez le médecin.", en: "I have to go to the doctor's.", de: "Ich muss zum Arzt gehen." },
        { fr: "Il doit rester au lit.", en: "He has to stay in bed.", de: "Er muss im Bett bleiben." },
        { fr: "Tu ne dois pas manger de chocolat.", en: "You mustn't eat chocolate.", de: "Du darfst keine Schokolade essen." },
      ],
      table: {
        head: [tx("person", "Person"), "devoir"],
        rows: [
          [tx("I", "ich"), "je dois"],
          [tx("you", "du"), "tu dois"],
          [tx("he / she", "er / sie"), "il / elle doit"],
          [tx("we", "wir"), "nous devons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous devez"],
          [tx("they", "sie"), "ils / elles doivent"],
        ],
      },
    },
    {
      title: tx("At the doctor's", "Beim Arzt"),
      body: tx(
        "You go **chez le médecin** (to the doctor's): chez, because it's a person. A woman doctor is **la médecin**, and you call her **Docteur**. Medicine comes from **la pharmacie**.\n\nA temperature: **j'ai de la fièvre**. Feeling better? **Ça va mieux** or **je vais mieux**, with aller, never je suis mieux.",
        "Du gehst **chez le médecin** (zum Arzt): chez, weil es eine Person ist. Eine Ärztin ist **la médecin**, und du sprichst sie mit **Docteur** an. Medikamente gibt es in der **pharmacie**.\n\nFieber: **j'ai de la fièvre**. Geht es besser? **Ça va mieux** oder **je vais mieux**, mit aller, nie je suis mieux.",
      ),
      examples: [
        { fr: "Je vais chez le médecin.", en: "I'm going to the doctor's.", de: "Ich gehe zum Arzt." },
        { fr: "Bonjour, Docteur. J'ai de la fièvre.", en: "Hello, Doctor. I have a temperature.", de: "Guten Tag, Frau Doktor. Ich habe Fieber." },
        { fr: "Oui, merci, ça va mieux.", en: "Yes, thank you, I'm feeling better.", de: "Ja, danke, es geht mir besser." },
      ],
    },
    {
      title: tx("Il faut: advice for everyone", "Il faut: Ratschläge für alle"),
      body: tx(
        "**Il faut** + infinitive means you have to, in general, for everyone. It never changes: il faut dormir, il faut boire de l'eau.\n\nThe negative is a warning: **il ne faut pas** manger trop de bonbons (you mustn't). And to someone who is ill, say **bon rétablissement !**",
        "**Il faut** + Infinitiv heißt man muss, ganz allgemein, für alle. Es ändert sich nie: il faut dormir, il faut boire de l'eau.\n\nVerneint ist es eine Warnung: **il ne faut pas** manger trop de bonbons (man darf nicht). Und zu jemandem, der krank ist: **bon rétablissement !**",
      ),
      examples: [
        { fr: "Il faut boire de l'eau.", en: "You have to drink water.", de: "Man muss Wasser trinken." },
        { fr: "Il ne faut pas manger trop de bonbons.", en: "You mustn't eat too many sweets.", de: "Man darf nicht zu viele Bonbons essen." },
        { fr: "Bon rétablissement, Madame Martin !", en: "Get well soon, Mrs Martin!", de: "Gute Besserung, Frau Martin!" },
      ],
    },
  ],
};
