import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 18: weather, seasons, months and dates. */
export const u18: Unit = {
  slug: "saisons",
  n: 18,
  cefr: "A2",
  title: tx("Seasons and weather", "Jahreszeiten und Wetter"),
  goal: tx("Talk about the weather, seasons and dates", "Über Wetter, Jahreszeiten und Daten sprechen"),
  emoji: "🍂",
  words: [
    { id: "temps", fr: "le temps", en: "the weather", de: "das Wetter", alt: { en: ["the time"], de: ["die Zeit"] }, g: "m", kind: "noun", emoji: "🌦️", note: tx("Le temps is the weather, and also time: je n'ai pas le temps (I've got no time).", "Le temps ist das Wetter und auch die Zeit: je n'ai pas le temps (ich habe keine Zeit).") },
    { id: "quel-temps", fr: "quel temps fait-il ?", en: "what's the weather like?", de: "wie ist das Wetter?", alt: { fr: ["il fait quel temps ?"], en: ["how's the weather?"] }, kind: "phrase", note: tx("Literally «what weather does it make?». The answer: il fait beau, il fait froid…", "Wörtlich „welches Wetter macht es?“. Die Antwort: il fait beau, il fait froid …") },
    { id: "il-fait-chaud", fr: "il fait chaud", en: "it's hot", de: "es ist heiß", alt: { en: ["it's warm"], de: ["es ist warm"] }, kind: "phrase", emoji: "🥵", note: tx("The weather uses faire: il fait chaud. When you feel hot: j'ai chaud.", "Beim Wetter steht faire: il fait chaud. Wenn dir heiß ist: j'ai chaud.") },
    { id: "il-fait-froid", fr: "il fait froid", en: "it's cold", de: "es ist kalt", kind: "phrase", emoji: "🥶", note: tx("And when you feel cold: j'ai froid.", "Und wenn dir kalt ist: j'ai froid.") },
    { id: "soleil", fr: "le soleil", en: "the sun", de: "die Sonne", g: "m", kind: "noun", emoji: "🌞", note: tx("Il y a du soleil: it's sunny.", "Männlich im Französischen! Il y a du soleil: Die Sonne scheint.") },
    { id: "vent", fr: "le vent", en: "the wind", de: "der Wind", g: "m", kind: "noun", emoji: "💨", note: tx("Il y a du vent: it's windy.", "Il y a du vent: Es ist windig.") },
    { id: "il-neige", fr: "il neige", en: "it's snowing", de: "es schneit", alt: { en: ["it snows"] }, kind: "phrase", emoji: "🌨️", note: tx("Like il pleut, snow has its own verb: neiger. The snow: la neige.", "Wie il pleut hat Schnee ein eigenes Verb: neiger. Der Schnee: la neige.") },
    { id: "nuage", fr: "le nuage", en: "the cloud", de: "die Wolke", g: "m", kind: "noun", emoji: "☁️", note: tx("Il y a des nuages: it's cloudy.", "Il y a des nuages: Es ist bewölkt.") },
    { id: "il-fait-mauvais", fr: "il fait mauvais", en: "the weather is bad", de: "das Wetter ist schlecht", alt: { en: ["it's bad weather"], de: ["es ist schlechtes Wetter"] }, kind: "phrase", emoji: "⛈️", note: tx("The opposite of il fait beau.", "Das Gegenteil von il fait beau.") },
    { id: "saison", fr: "la saison", en: "the season", de: "die Jahreszeit", g: "f", kind: "noun", note: tx("Les quatre saisons: the four seasons, like Vivaldi!", "Les quatre saisons: die vier Jahreszeiten, wie bei Vivaldi!") },
    { id: "printemps", fr: "le printemps", en: "the spring", de: "der Frühling", alt: { en: ["spring"], de: ["Frühling"] }, g: "m", kind: "noun", emoji: "🌷", note: tx("The odd one out: au printemps, in spring.", "Die Ausnahme: au printemps, im Frühling.") },
    { id: "ete", fr: "l'été", en: "the summer", de: "der Sommer", alt: { en: ["summer"], de: ["Sommer"] }, g: "m", kind: "noun", emoji: "🌻", note: tx("En été: in summer.", "En été: im Sommer.") },
    { id: "automne", fr: "l'automne", en: "the autumn", de: "der Herbst", alt: { en: ["autumn", "the fall"], de: ["Herbst"] }, g: "m", kind: "noun", emoji: "🍁", note: tx("The m is silent: «oh-tonn». En automne: in autumn.", "Das m ist stumm: „o-tonn“. En automne: im Herbst.") },
    { id: "hiver", fr: "l'hiver", en: "the winter", de: "der Winter", alt: { en: ["winter"], de: ["Winter"] }, g: "m", kind: "noun", emoji: "☃️", note: tx("The h is silent: «ee-vair». En hiver: in winter.", "Das h ist stumm: „i-wär“. En hiver: im Winter.") },
    { id: "mois", fr: "le mois", en: "the month", de: "der Monat", g: "m", kind: "noun", note: tx("The s is silent and it stays: un mois, deux mois.", "Das s ist stumm und bleibt: un mois, deux mois.") },
    { id: "janvier", fr: "janvier", en: "January", de: "Januar", alt: { de: ["Jänner"] }, kind: "word", note: tx("Months have no capital letter in French: janvier, février…", "Monate schreibt man auf Französisch klein: janvier, février …") },
    { id: "fevrier", fr: "février", en: "February", de: "Februar", kind: "word" },
    { id: "mars", fr: "mars", en: "March", de: "März", kind: "word", note: tx("You hear the s: «marss».", "Das s hört man: „marss“.") },
    { id: "avril", fr: "avril", en: "April", de: "April", kind: "word" },
    { id: "mai", fr: "mai", en: "May", de: "Mai", kind: "word", note: tx("Le premier mai is a holiday in France.", "Der erste Mai ist auch in Frankreich ein Feiertag.") },
    { id: "juin", fr: "juin", en: "June", de: "Juni", kind: "word" },
    { id: "juillet", fr: "juillet", en: "July", de: "Juli", kind: "word", note: tx("Le quatorze juillet: France's national day, with fireworks.", "Le quatorze juillet: der Nationalfeiertag, mit Feuerwerk.") },
    { id: "aout", fr: "août", en: "August", de: "August", kind: "word", note: tx("Short and strange: say «oot».", "Kurz und seltsam: Sprich „ut“.") },
    { id: "septembre", fr: "septembre", en: "September", de: "September", kind: "word", note: tx("La rentrée: school starts again in September.", "La rentrée: Im September beginnt die Schule wieder.") },
    { id: "octobre", fr: "octobre", en: "October", de: "Oktober", kind: "word" },
    { id: "novembre", fr: "novembre", en: "November", de: "November", kind: "word" },
    { id: "decembre", fr: "décembre", en: "December", de: "Dezember", kind: "word", note: tx("With an accent: décembre. Noël is le vingt-cinq décembre.", "Mit Akzent: décembre. Noël ist le vingt-cinq décembre.") },
    { id: "premier", fr: "premier", en: "first", de: "erster", alt: { de: ["erste"] }, kind: "adj", emoji: "🥇", note: tx("The 1st of the month is le premier: le premier mai. From the 2nd on, just the number: le deux mai.", "Der 1. des Monats ist le premier: le premier mai. Ab dem 2. nur die Zahl: le deux mai.") },
    { id: "noel", fr: "Noël", en: "Christmas", de: "Weihnachten", kind: "word", emoji: "🎄", note: tx("Joyeux Noël ! Merry Christmas! It's le vingt-cinq décembre.", "Joyeux Noël ! Frohe Weihnachten! Es ist le vingt-cinq décembre.") },
    { id: "degres", fr: "degrés", en: "degrees", de: "Grad", kind: "word", note: tx("Il fait vingt degrés: it's twenty degrees (always Celsius).", "Il fait vingt degrés: Es sind zwanzig Grad.") },
    { id: "parapluie", fr: "le parapluie", en: "the umbrella", de: "der Regenschirm", alt: { de: ["der Schirm"] }, g: "m", kind: "noun", emoji: "☂️", note: tx("Para + pluie: «against rain». The rain: la pluie.", "Para + pluie: „gegen Regen“. Der Regen: la pluie.") },
    { id: "ski", fr: "le ski", en: "skiing", de: "Skifahren", alt: { en: ["the ski"], de: ["der Ski"] }, g: "m", kind: "noun", emoji: "⛷️", note: tx("Faire du ski: to go skiing, like faire du vélo.", "Faire du ski: Ski fahren, wie faire du vélo.") },
  ],
  gloss: [
    { fr: "il fait très chaud", en: "it's very hot", de: "es ist sehr heiß" },
    { fr: "il fait très froid", en: "it's very cold", de: "es ist sehr kalt" },
    { fr: "il fait trop chaud", en: "it's too hot", de: "es ist zu heiß" },
    { fr: "il a fait", en: "it was (weather) / he did", de: "es war (Wetter) / er hat gemacht" },
    { fr: "il fait trente degrés", en: "it's thirty degrees", de: "es ist dreißig Grad" },
    { fr: "il va faire beau", en: "the weather's going to be nice", de: "das Wetter wird schön" },
    { fr: "il va neiger", en: "it's going to snow", de: "es wird schneien" },
    { fr: "il va pleuvoir", en: "it's going to rain", de: "es wird regnen" },
    { fr: "on fait", en: "we do / we make", de: "wir machen" },
    { fr: "quelle", en: "which / what", de: "welche / was für" },
    { fr: "nuages", en: "clouds", de: "Wolken" },
    { fr: "neige", en: "snow / snows", de: "Schnee / schneit" },
    { fr: "neiger", en: "to snow", de: "schneien" },
    { fr: "pleuvoir", en: "to rain", de: "regnen" },
    { fr: "saisons", en: "seasons", de: "Jahreszeiten" },
    { fr: "fleurs", en: "flowers", de: "Blumen" },
    { fr: "année", en: "year", de: "Jahr" },
    { fr: "court", en: "short", de: "kurz" },
    { fr: "souvent", en: "often", de: "oft" },
    { fr: "commencent", en: "start / begin (they)", de: "beginnen / fangen an" },
    { fr: "rentrée", en: "back to school", de: "Schulanfang" },
    { fr: "dernier", en: "last", de: "letzter" },
    { fr: "feu d'artifice", en: "fireworks", de: "Feuerwerk" },
    { fr: "regardons", en: "watch / look at (we)", de: "schauen (wir)" },
    { fr: "regardez", en: "look (you, plural)", de: "schaut / schauen Sie" },
    { fr: "vingt-cinq", en: "twenty-five", de: "fünfundzwanzig" },
    { fr: "trouve", en: "find / finds", de: "finde / findet" },
    { fr: "pique-nique", en: "picnic", de: "Picknick" },
    { fr: "peut-être", en: "maybe", de: "vielleicht" },
  ],
  lessons: [
    { title: tx("What's the weather like?", "Wie ist das Wetter?"), words: ["temps", "quel-temps", "il-fait-chaud", "il-fait-froid", "soleil"] },
    { title: tx("Wind and snow", "Wind und Schnee"), words: ["vent", "il-neige", "nuage", "il-fait-mauvais"] },
    { title: tx("The four seasons", "Die vier Jahreszeiten"), words: ["saison", "printemps", "ete", "automne", "hiver"] },
    { title: tx("January to June", "Januar bis Juni"), words: ["mois", "janvier", "fevrier", "mars", "avril", "mai", "juin"] },
    { title: tx("July to December", "Juli bis Dezember"), words: ["juillet", "aout", "septembre", "octobre", "novembre", "decembre"] },
    { title: tx("Dates and degrees", "Daten und Grad"), words: ["premier", "noel", "degres"] },
    { title: tx("Rain or snow?", "Regen oder Schnee?"), words: ["parapluie", "ski"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u18.01", lesson: 1, fr: "Quel temps fait-il aujourd'hui ?", en: "What's the weather like today?", de: "Wie ist das Wetter heute?", alt: { fr: ["Il fait quel temps aujourd'hui ?", "Aujourd'hui, quel temps fait-il ?", "Quel temps est-ce qu'il fait aujourd'hui ?"], en: ["How's the weather today?", "What's the weather today?"], de: ["Wie ist heute das Wetter?", "Was für ein Wetter ist heute?"] } },
    { id: "u18.02", lesson: 1, fr: "Il fait chaud, il y a du soleil.", en: "It's hot, it's sunny.", de: "Es ist heiß, die Sonne scheint.", alt: { fr: ["Il fait chaud et il y a du soleil."], en: ["It's hot and sunny.", "It's warm, it's sunny.", "It's hot, the sun is shining.", "It's hot and the sun is shining."], de: ["Es ist warm, die Sonne scheint.", "Es ist heiß und sonnig.", "Es ist heiß und die Sonne scheint.", "Es ist heiß, es ist sonnig."] } },
    { id: "u18.03", lesson: 1, fr: "Il fait froid aujourd'hui !", en: "It's cold today!", de: "Heute ist es kalt!", alt: { fr: ["Aujourd'hui, il fait froid !"], de: ["Es ist heute kalt!"] } },
    { id: "u18.04", lesson: 1, fr: "J'aime le soleil.", en: "I like the sun.", de: "Ich mag die Sonne.", alt: { en: ["I love the sun.", "I like sunshine.", "I like the sunshine."], de: ["Ich liebe die Sonne."] } },
    { id: "u18.05", lesson: 1, fr: "Il fait froid, je porte mon pull.", en: "It's cold, I'm wearing my jumper.", de: "Es ist kalt, ich trage meinen Pullover.", alt: { en: ["It's cold, I'm wearing my sweater.", "It's cold, so I'm wearing my jumper.", "It's cold, I wear my jumper."], de: ["Es ist kalt, ich trage meinen Pulli.", "Es ist kalt, also trage ich meinen Pullover."] } },
    { id: "u18.06", lesson: 1, fr: "Quel temps fait-il à Lyon ?", en: "What's the weather like in Lyon?", de: "Wie ist das Wetter in Lyon?", alt: { fr: ["Il fait quel temps à Lyon ?", "Quel temps est-ce qu'il fait à Lyon ?"], en: ["How's the weather in Lyon?"] } },
    { id: "u18.07", lesson: 1, fr: "Il fait trop chaud, je vais à la piscine.", en: "It's too hot, I'm going to the swimming pool.", de: "Es ist zu heiß, ich gehe ins Schwimmbad.", alt: { en: ["It's too hot, I'm going to the pool.", "It's too hot, so I'm going to the swimming pool.", "It's too hot, so I'm going to the pool.", "It's too hot, I go to the swimming pool."], de: ["Es ist zu heiß, ich gehe ins Freibad.", "Es ist zu heiß, also gehe ich ins Schwimmbad."] } },
    // Lesson 2
    { id: "u18.08", lesson: 2, fr: "Il y a du vent.", en: "It's windy.", de: "Es ist windig.", alt: { fr: ["Il fait du vent."], en: ["There's wind.", "There's some wind."], de: ["Es weht Wind.", "Es gibt Wind."] } },
    { id: "u18.09", lesson: 2, fr: "Il neige, les enfants sont contents !", en: "It's snowing, the children are happy!", de: "Es schneit, die Kinder freuen sich!", alt: { en: ["It's snowing and the children are happy!", "It's snowing, the kids are happy!"], de: ["Es schneit, die Kinder sind froh!", "Es schneit, die Kinder sind glücklich!", "Es schneit und die Kinder freuen sich!"] } },
    { id: "u18.10", lesson: 2, fr: "Il fait mauvais aujourd'hui.", en: "The weather is bad today.", de: "Heute ist das Wetter schlecht.", alt: { fr: ["Aujourd'hui, il fait mauvais."], en: ["The weather's bad today.", "It's bad weather today.", "Today the weather is bad."], de: ["Das Wetter ist heute schlecht.", "Heute ist schlechtes Wetter.", "Es ist heute schlechtes Wetter."] } },
    { id: "u18.11", lesson: 2, fr: "Il y a des nuages, mais il ne pleut pas.", en: "It's cloudy, but it isn't raining.", de: "Es ist bewölkt, aber es regnet nicht.", alt: { en: ["There are clouds, but it isn't raining.", "It's cloudy, but it doesn't rain."], de: ["Es gibt Wolken, aber es regnet nicht.", "Es ist wolkig, aber es regnet nicht."] } },
    { id: "u18.12", lesson: 2, fr: "Il pleut et il y a du vent.", en: "It's raining and it's windy.", de: "Es regnet und es ist windig.", alt: { en: ["It's raining and windy.", "It's windy and it's raining."], de: ["Es regnet und ist windig.", "Es regnet und es weht Wind."] } },
    { id: "u18.13", lesson: 2, fr: "Il neige à la montagne.", en: "It's snowing in the mountains.", de: "In den Bergen schneit es.", alt: { fr: ["À la montagne, il neige.", "Il neige en montagne."], en: ["It snows in the mountains."], de: ["Es schneit in den Bergen."] } },
    { id: "u18.14", lesson: 2, fr: "Il fait mauvais, je reste à la maison.", en: "The weather's bad, I'm staying at home.", de: "Das Wetter ist schlecht, ich bleibe zu Hause.", alt: { en: ["The weather is bad, I'm staying at home.", "The weather's bad, I'm staying home.", "The weather is bad, so I'm staying at home.", "It's bad weather, I'm staying at home."], de: ["Es ist schlechtes Wetter, ich bleibe zu Hause.", "Das Wetter ist schlecht, also bleibe ich zu Hause."] } },
    // Lesson 3
    { id: "u18.15", lesson: 3, fr: "Il y a quatre saisons.", en: "There are four seasons.", de: "Es gibt vier Jahreszeiten.", alt: { en: ["There are 4 seasons."], de: ["Es gibt 4 Jahreszeiten."] } },
    { id: "u18.16", lesson: 3, fr: "En hiver, il fait froid et il neige.", en: "In winter it's cold and it snows.", de: "Im Winter ist es kalt und es schneit.", alt: { fr: ["Il fait froid et il neige en hiver."], en: ["In winter it's cold and snowy.", "In the winter it's cold and it snows.", "It's cold and it snows in winter."], de: ["Im Winter ist es kalt und schneit."] } },
    { id: "u18.17", lesson: 3, fr: "Au printemps, il y a beaucoup de fleurs.", en: "In spring there are lots of flowers.", de: "Im Frühling gibt es viele Blumen.", alt: { fr: ["Il y a beaucoup de fleurs au printemps."], en: ["In spring there are a lot of flowers.", "In the spring there are lots of flowers.", "There are lots of flowers in spring.", "In spring there are many flowers."], de: ["Im Frühling gibt es eine Menge Blumen.", "Es gibt viele Blumen im Frühling."] } },
    { id: "u18.18", lesson: 3, fr: "En été, nous allons à la plage.", en: "In summer we go to the beach.", de: "Im Sommer gehen wir an den Strand.", alt: { fr: ["En été, on va à la plage.", "Nous allons à la plage en été.", "On va à la plage en été."], en: ["In the summer we go to the beach.", "We go to the beach in summer.", "In summer we're going to the beach."], de: ["Im Sommer fahren wir an den Strand.", "Im Sommer gehen wir zum Strand."] } },
    { id: "u18.19", lesson: 3, fr: "L'automne est ma saison préférée.", en: "Autumn is my favourite season.", de: "Der Herbst ist meine Lieblingsjahreszeit.", alt: { en: ["Autumn is my favorite season.", "The autumn is my favourite season."], de: ["Herbst ist meine Lieblingsjahreszeit."] } },
    { id: "u18.20", lesson: 3, fr: "Quelle est ta saison préférée ?", en: "What's your favourite season?", de: "Was ist deine Lieblingsjahreszeit?", alt: { fr: ["Quelle est votre saison préférée ?", "C'est quoi, ta saison préférée ?", "Ta saison préférée, c'est quoi ?"], en: ["What's your favorite season?", "Which is your favourite season?", "Which season is your favourite?"], de: ["Welche ist deine Lieblingsjahreszeit?", "Welche Jahreszeit magst du am liebsten?"] } },
    { id: "u18.21", lesson: 3, fr: "En automne, il pleut beaucoup.", en: "In autumn it rains a lot.", de: "Im Herbst regnet es viel.", alt: { fr: ["Il pleut beaucoup en automne."], en: ["In the autumn it rains a lot.", "It rains a lot in autumn.", "In autumn it rains lots."], de: ["Im Herbst regnet es oft.", "Es regnet viel im Herbst."] } },
    // Lesson 4
    { id: "u18.22", lesson: 4, fr: "Une année, c'est douze mois.", en: "A year is twelve months.", de: "Ein Jahr hat zwölf Monate.", alt: { fr: ["Une année, ça fait douze mois.", "Il y a douze mois dans une année."], en: ["A year is 12 months.", "A year has twelve months.", "A year has 12 months."], de: ["Ein Jahr sind zwölf Monate.", "Ein Jahr hat 12 Monate."] } },
    { id: "u18.23", lesson: 4, fr: "Mon anniversaire, c'est le douze mars.", en: "My birthday is on the twelfth of March.", de: "Mein Geburtstag ist am zwölften März.", alt: { fr: ["C'est le douze mars, mon anniversaire.", "Mon anniversaire est le douze mars."], en: ["My birthday is on 12 March.", "My birthday is the twelfth of March.", "My birthday is on March the twelfth.", "My birthday is on March 12.", "My birthday is on the 12th of March.", "My birthday is 12 March.", "My birthday is on March 12th."], de: ["Mein Geburtstag ist am 12. März.", "Ich habe am zwölften März Geburtstag.", "Ich habe am 12. März Geburtstag."] } },
    { id: "u18.24", lesson: 4, fr: "En janvier, il fait très froid.", en: "In January it's very cold.", de: "Im Januar ist es sehr kalt.", alt: { fr: ["Il fait très froid en janvier."], en: ["It's very cold in January."], de: ["Es ist im Januar sehr kalt."] } },
    { id: "u18.25", lesson: 4, fr: "Février est un mois court.", en: "February is a short month.", de: "Der Februar ist ein kurzer Monat.", alt: { de: ["Februar ist ein kurzer Monat."] } },
    { id: "u18.26", lesson: 4, fr: "En avril, il pleut souvent.", en: "In April it often rains.", de: "Im April regnet es oft.", alt: { fr: ["Il pleut souvent en avril."], en: ["It often rains in April.", "In April it rains often."], de: ["Es regnet oft im April."] } },
    { id: "u18.27", lesson: 4, fr: "Les vacances commencent en juin.", en: "The holidays start in June.", de: "Die Ferien beginnen im Juni.", alt: { en: ["The holidays begin in June.", "The vacation starts in June."], de: ["Die Ferien fangen im Juni an."] } },
    { id: "u18.28", lesson: 4, fr: "Ton anniversaire, c'est en mai ?", en: "Is your birthday in May?", de: "Hast du im Mai Geburtstag?", alt: { fr: ["C'est en mai, ton anniversaire ?", "Ton anniversaire est en mai ?", "Est-ce que ton anniversaire est en mai ?", "Votre anniversaire, c'est en mai ?"], de: ["Ist dein Geburtstag im Mai?"] } },
    // Lesson 5
    { id: "u18.29", lesson: 5, fr: "En juillet et en août, il fait chaud.", en: "In July and August it's hot.", de: "Im Juli und im August ist es heiß.", alt: { fr: ["Il fait chaud en juillet et en août."], en: ["It's hot in July and August.", "In July and August it's warm."], de: ["Im Juli und August ist es heiß.", "Es ist heiß im Juli und August.", "Im Juli und im August ist es warm."] } },
    { id: "u18.30", lesson: 5, fr: "La rentrée, c'est en septembre.", en: "School starts again in September.", de: "Die Schule fängt im September wieder an.", alt: { fr: ["La rentrée est en septembre."], en: ["Back to school is in September.", "The new school year starts in September."], de: ["Das neue Schuljahr beginnt im September.", "Im September fängt die Schule wieder an."] } },
    { id: "u18.31", lesson: 5, fr: "En novembre, il fait froid et il pleut.", en: "In November it's cold and it rains.", de: "Im November ist es kalt und es regnet.", alt: { fr: ["Il fait froid et il pleut en novembre."], en: ["In November it's cold and rainy.", "It's cold and it rains in November.", "In November it's cold and it's raining."], de: ["Im November ist es kalt und regnerisch.", "Im November ist es kalt und regnet."] } },
    { id: "u18.32", lesson: 5, fr: "Mon anniversaire, c'est en octobre.", en: "My birthday is in October.", de: "Mein Geburtstag ist im Oktober.", alt: { fr: ["Mon anniversaire est en octobre.", "C'est en octobre, mon anniversaire."], de: ["Ich habe im Oktober Geburtstag."] } },
    { id: "u18.33", lesson: 5, fr: "Décembre est le dernier mois.", en: "December is the last month.", de: "Der Dezember ist der letzte Monat.", alt: { de: ["Dezember ist der letzte Monat."] } },
    { id: "u18.34", lesson: 5, fr: "En août, je vais aller à la mer.", en: "In August I'm going to go to the seaside.", de: "Im August werde ich ans Meer fahren.", alt: { fr: ["Je vais aller à la mer en août."], en: ["In August I'm going to the seaside.", "In August I will go to the seaside.", "I'm going to go to the seaside in August.", "I will go to the seaside in August.", "In August I'm going to go to the sea.", "In August I will go to the sea."], de: ["Im August fahre ich ans Meer.", "Ich werde im August ans Meer fahren.", "Ich fahre im August ans Meer.", "Im August werde ich ans Meer gehen."] } },
    { id: "u18.35", lesson: 5, fr: "Le quatorze juillet, nous regardons le feu d'artifice.", en: "On the fourteenth of July we watch the fireworks.", de: "Am vierzehnten Juli schauen wir das Feuerwerk an.", alt: { fr: ["Nous regardons le feu d'artifice le quatorze juillet.", "Le quatorze juillet, on regarde le feu d'artifice."], en: ["On 14 July we watch the fireworks.", "On July the fourteenth we watch the fireworks.", "On the 14th of July we watch the fireworks.", "On July 14 we watch the fireworks.", "We watch the fireworks on the fourteenth of July."], de: ["Am 14. Juli schauen wir das Feuerwerk an.", "Am vierzehnten Juli sehen wir uns das Feuerwerk an.", "Am 14. Juli sehen wir uns das Feuerwerk an.", "Am vierzehnten Juli schauen wir uns das Feuerwerk an."] } },
    // Lesson 6
    { id: "u18.36", lesson: 6, fr: "Noël, c'est le vingt-cinq décembre.", en: "Christmas is on the twenty-fifth of December.", de: "Weihnachten ist am fünfundzwanzigsten Dezember.", alt: { fr: ["Noël est le vingt-cinq décembre."], en: ["Christmas is on 25 December.", "Christmas is the twenty-fifth of December.", "Christmas is on December the twenty-fifth.", "Christmas is on December 25.", "Christmas is on the 25th of December.", "Christmas is on December 25th."], de: ["Weihnachten ist am 25. Dezember."] } },
    { id: "u18.37", lesson: 6, fr: "Aujourd'hui, c'est le premier mai.", en: "Today is the first of May.", de: "Heute ist der erste Mai.", alt: { fr: ["C'est le premier mai aujourd'hui.", "Nous sommes le premier mai.", "On est le premier mai."], en: ["Today is 1 May.", "Today is May the first.", "Today is the 1st of May.", "Today is May 1.", "Today is May 1st.", "It's the first of May today."], de: ["Heute ist der 1. Mai.", "Wir haben heute den ersten Mai."] } },
    { id: "u18.38", lesson: 6, fr: "Il fait trente degrés !", en: "It's thirty degrees!", de: "Es ist dreißig Grad!", alt: { en: ["It's 30 degrees!"], de: ["Es sind dreißig Grad!", "Es ist 30 Grad!", "Es sind 30 Grad!", "Wir haben dreißig Grad!"] } },
    { id: "u18.39", lesson: 6, fr: "Il y a de la neige à Noël ?", en: "Is there snow at Christmas?", de: "Gibt es an Weihnachten Schnee?", alt: { fr: ["Est-ce qu'il y a de la neige à Noël ?", "À Noël, il y a de la neige ?", "Y a-t-il de la neige à Noël ?"], en: ["Is there any snow at Christmas?", "Is there snow at Christmas time?"], de: ["Gibt es zu Weihnachten Schnee?", "Liegt an Weihnachten Schnee?", "Liegt zu Weihnachten Schnee?"] } },
    { id: "u18.40", lesson: 6, fr: "Hier, il a fait très chaud.", en: "Yesterday it was very hot.", de: "Gestern war es sehr heiß.", alt: { fr: ["Il a fait très chaud hier."], en: ["It was very hot yesterday."], de: ["Es war gestern sehr heiß.", "Gestern ist es sehr heiß gewesen."] } },
    { id: "u18.41", lesson: 6, fr: "Le premier janvier, je me lève très tard.", en: "On the first of January I get up very late.", de: "Am ersten Januar stehe ich sehr spät auf.", alt: { fr: ["Je me lève très tard le premier janvier."], en: ["On 1 January I get up very late.", "On January the first I get up very late.", "On the 1st of January I get up very late.", "On New Year's Day I get up very late.", "On January 1 I get up very late."], de: ["Am 1. Januar stehe ich sehr spät auf.", "Am Neujahrstag stehe ich sehr spät auf."] } },
    { id: "u18.42", lesson: 6, fr: "Demain, il va neiger.", en: "It's going to snow tomorrow.", de: "Morgen wird es schneien.", alt: { fr: ["Il va neiger demain."], en: ["Tomorrow it's going to snow.", "It will snow tomorrow.", "Tomorrow it will snow."], de: ["Morgen schneit es.", "Es wird morgen schneien."] } },
    { id: "u18.43", lesson: 6, fr: "À Noël, nous allons à la montagne.", en: "At Christmas we're going to the mountains.", de: "An Weihnachten fahren wir in die Berge.", alt: { fr: ["Nous allons à la montagne à Noël.", "À Noël, on va à la montagne.", "On va à la montagne à Noël."], en: ["At Christmas we go to the mountains.", "We're going to the mountains at Christmas.", "We go to the mountains at Christmas."], de: ["Zu Weihnachten fahren wir in die Berge.", "An Weihnachten gehen wir in die Berge.", "Wir fahren an Weihnachten in die Berge."] } },
    // Lesson 7
    { id: "u18.44", lesson: 7, fr: "Il pleut, prends ton parapluie !", en: "It's raining, take your umbrella!", de: "Es regnet, nimm deinen Regenschirm!", alt: { fr: ["Il pleut, prenez votre parapluie !"], en: ["It's raining, take an umbrella!"], de: ["Es regnet, nimm deinen Schirm!"] } },
    { id: "u18.45", lesson: 7, fr: "En hiver, nous faisons du ski.", en: "In winter we go skiing.", de: "Im Winter fahren wir Ski.", alt: { fr: ["Nous faisons du ski en hiver.", "En hiver, on fait du ski.", "On fait du ski en hiver."], en: ["In winter we ski.", "In the winter we go skiing.", "We go skiing in winter."], de: ["Im Winter gehen wir Ski fahren.", "Wir fahren im Winter Ski."] } },
    { id: "u18.46", lesson: 7, fr: "Tu as fait du ski en février ?", en: "Did you go skiing in February?", de: "Bist du im Februar Ski gefahren?", alt: { fr: ["Est-ce que tu as fait du ski en février ?", "As-tu fait du ski en février ?", "Vous avez fait du ski en février ?", "Est-ce que vous avez fait du ski en février ?"], en: ["Did you ski in February?"], de: ["Warst du im Februar Ski fahren?", "Bist du im Februar Ski fahren gewesen?"] } },
    { id: "u18.47", lesson: 7, fr: "Demain, il va faire beau : on va à la plage !", en: "Tomorrow the weather's going to be nice: we're going to the beach!", de: "Morgen wird das Wetter schön: Wir gehen an den Strand!", alt: { fr: ["Il va faire beau demain : on va à la plage !", "Demain, il va faire beau : nous allons à la plage !"], en: ["Tomorrow the weather will be nice: we're going to the beach!", "The weather's going to be nice tomorrow: we're going to the beach!", "Tomorrow it's going to be nice: we're going to the beach!", "Tomorrow it will be nice: we're going to the beach!", "Tomorrow the weather is going to be nice: we're going to the beach!"], de: ["Morgen ist schönes Wetter: Wir gehen an den Strand!", "Morgen wird es schön: Wir gehen an den Strand!", "Morgen wird das Wetter schön: Wir fahren an den Strand!", "Das Wetter wird morgen schön: Wir gehen an den Strand!"] } },
    { id: "u18.48", lesson: 7, fr: "Je ne trouve pas mon parapluie !", en: "I can't find my umbrella!", de: "Ich finde meinen Regenschirm nicht!", alt: { de: ["Ich finde meinen Schirm nicht!"] } },
    { id: "u18.49", lesson: 7, fr: "Il fait froid, mais il y a du soleil.", en: "It's cold, but it's sunny.", de: "Es ist kalt, aber die Sonne scheint.", alt: { en: ["It's cold but sunny.", "It's cold, but the sun is shining."], de: ["Es ist kalt, aber sonnig.", "Es ist kalt, aber es ist sonnig."] } },
    { id: "u18.50", lesson: 7, fr: "Il va pleuvoir ce soir.", en: "It's going to rain this evening.", de: "Heute Abend wird es regnen.", alt: { fr: ["Ce soir, il va pleuvoir."], en: ["It will rain this evening.", "It's going to rain tonight.", "It will rain tonight.", "This evening it's going to rain."], de: ["Heute Abend regnet es.", "Es wird heute Abend regnen."] } },
  ],
  drills: [
    { id: "u18.d1", lesson: 1, fr: "Quel temps fait-il ? Il ___ chaud.", options: ["fait", "est"], answer: 0, en: "What's the weather like? It's hot.", de: "Wie ist das Wetter? Es ist heiß.", why: tx("The weather goes with **faire**: il **fait** chaud, il fait froid. Il est chaud would be a thing that is hot.", "Beim Wetter steht **faire**: il **fait** chaud, il fait froid. Il est chaud wäre ein Ding, das heiß ist.") },
    { id: "u18.d2", lesson: 1, fr: "Il y a ___ soleil.", options: ["du", "de la", "des"], answer: 0, en: "It's sunny.", de: "Die Sonne scheint.", why: tx("Soleil is masculine: il y a **du** soleil, some sunshine.", "Soleil ist männlich: il y a **du** soleil.") },
    { id: "u18.d3", lesson: 2, fr: "Il y a ___ vent aujourd'hui.", options: ["du", "de la"], answer: 0, en: "It's windy today.", de: "Heute ist es windig.", why: tx("Vent is masculine: il y a **du** vent.", "Vent ist männlich: il y a **du** vent.") },
    { id: "u18.d4", lesson: 2, fr: "Regarde, il ___ !", options: ["neige", "fait neige"], answer: 0, en: "Look, it's snowing!", de: "Schau, es schneit!", why: tx("Snow and rain have their own verbs: il **neige**, il pleut. No fait here.", "Schnee und Regen haben eigene Verben: il **neige**, il pleut. Hier kein fait.") },
    { id: "u18.d5", lesson: 2, fr: "Il y a ___ nuages, mais il ne pleut pas.", options: ["des", "du"], answer: 0, en: "It's cloudy, but it isn't raining.", de: "Es ist bewölkt, aber es regnet nicht.", why: tx("Nuages is plural: **des** nuages.", "Nuages ist Plural: **des** nuages.") },
    { id: "u18.d6", lesson: 3, fr: "___ hiver, il fait froid et il neige.", options: ["En", "Au"], answer: 0, en: "In winter it's cold and it snows.", de: "Im Winter ist es kalt und es schneit.", why: tx("Seasons take **en**: **en** hiver, en été, en automne. Only printemps takes au.", "Jahreszeiten nehmen **en**: **en** hiver, en été, en automne. Nur printemps nimmt au.") },
    { id: "u18.d7", lesson: 3, fr: "___ printemps, il y a beaucoup de fleurs.", options: ["Au", "En"], answer: 0, en: "In spring there are lots of flowers.", de: "Im Frühling gibt es viele Blumen.", why: tx("Printemps is the odd one out: **au** printemps. The other seasons take en.", "Printemps ist die Ausnahme: **au** printemps. Die anderen Jahreszeiten nehmen en.") },
    { id: "u18.d8", lesson: 3, fr: "L'automne est ma saison ___.", options: ["préférée", "préféré"], answer: 0, en: "Autumn is my favourite season.", de: "Der Herbst ist meine Lieblingsjahreszeit.", why: tx("Saison is feminine, so it's **préférée**, with an extra e.", "Saison ist weiblich, darum **préférée**, mit einem e mehr.") },
    { id: "u18.d9", lesson: 4, fr: "Mon anniversaire, c'est ___ douze mars.", options: ["le", "en", "à"], answer: 0, en: "My birthday is on the twelfth of March.", de: "Mein Geburtstag ist am zwölften März.", why: tx("A date is **le** + number + month: **le** douze mars. English says «on», German «am».", "Ein Datum ist **le** + Zahl + Monat: **le** douze mars. Im Deutschen „am“.") },
    { id: "u18.d10", lesson: 4, fr: "Les vacances commencent ___ juin.", options: ["en", "le"], answer: 0, en: "The holidays start in June.", de: "Die Ferien beginnen im Juni.", why: tx("A month on its own takes **en**: **en** juin. Le only comes with a date: le douze juin.", "Ein Monat allein nimmt **en**: **en** juin. Le steht nur bei einem Datum: le douze juin.") },
    { id: "u18.d11", lesson: 4, fr: "Ton anniversaire, c'est ___ mai ?", options: ["en", "au", "à la"], answer: 0, en: "Is your birthday in May?", de: "Hast du im Mai Geburtstag?", why: tx("In a month: **en** mai, en janvier. You can also say au mois de mai.", "In einem Monat: **en** mai, en janvier. Man kann auch au mois de mai sagen.") },
    { id: "u18.d12", lesson: 5, fr: "___ juillet et en août, il fait chaud.", options: ["En", "Au"], answer: 0, en: "In July and August it's hot.", de: "Im Juli und im August ist es heiß.", why: tx("Months take **en**: **en** juillet, en août.", "Monate nehmen **en**: **en** juillet, en août.") },
    { id: "u18.d13", lesson: 5, fr: "Décembre est le ___ mois.", options: ["dernier", "dernière"], answer: 0, en: "December is the last month.", de: "Der Dezember ist der letzte Monat.", why: tx("Mois is masculine: le **dernier** mois. Feminine: la dernière semaine.", "Mois ist männlich: le **dernier** mois. Weiblich: la dernière semaine.") },
    { id: "u18.d14", lesson: 6, fr: "Aujourd'hui, c'est le ___ mai.", options: ["premier", "un"], answer: 0, en: "Today is the first of May.", de: "Heute ist der erste Mai.", why: tx("The first day of a month is **le premier**: le premier mai. From the 2nd on, just the number: le deux mai.", "Der erste Tag im Monat ist **le premier**: le premier mai. Ab dem 2. nur die Zahl: le deux mai.") },
    { id: "u18.d15", lesson: 6, fr: "Hier, il ___ fait très chaud.", options: ["a", "est"], answer: 0, en: "Yesterday it was very hot.", de: "Gestern war es sehr heiß.", why: tx("The past of faire takes **avoir**: il **a** fait chaud, never il est fait.", "Die Vergangenheit von faire bildet man mit **avoir**: il **a** fait chaud, nie il est fait.") },
    { id: "u18.d16", lesson: 6, fr: "Demain, il va ___.", options: ["neiger", "neige"], answer: 0, en: "It's going to snow tomorrow.", de: "Morgen wird es schneien.", why: tx("After **aller** comes the infinitive: il va **neiger**, il va pleuvoir.", "Nach **aller** kommt der Infinitiv: il va **neiger**, il va pleuvoir.") },
    { id: "u18.d17", lesson: 7, fr: "En hiver, nous ___ du ski.", options: ["faisons", "faites", "font"], answer: 0, en: "In winter we go skiing.", de: "Im Winter fahren wir Ski.", why: tx("With **nous**: nous **faisons**. Faire du ski: to go skiing.", "Mit **nous**: nous **faisons**. Faire du ski: Ski fahren.") },
    { id: "u18.d18", lesson: 7, fr: "Il pleut, prends ___ parapluie !", options: ["ton", "ta"], answer: 0, en: "It's raining, take your umbrella!", de: "Es regnet, nimm deinen Regenschirm!", why: tx("Parapluie is masculine: **ton** parapluie.", "Parapluie ist männlich: **ton** parapluie.") },
  ],
  dialogues: [
    {
      id: "u18.dialogue",
      lesson: 5,
      title: tx("Summer? No, Blob!", "Sommer? Nein, Blob!"),
      lines: [
        { who: "blob", fr: "Léa, quel temps fait-il aujourd'hui ?", en: "Léa, what's the weather like today?", de: "Léa, wie ist das Wetter heute?" },
        { who: "lea", fr: "Il fait froid et il y a du vent.", en: "It's cold and windy.", de: "Es ist kalt und windig." },
        { who: "blob", fr: "Froid ? Mais c'est l'été !", en: "Cold? But it's summer!", de: "Kalt? Aber es ist Sommer!" },
        { who: "lea", fr: "Non, Blob. On est en novembre. C'est l'automne.", en: "No, Blob. It's November. It's autumn.", de: "Nein, Blob. Wir haben November. Es ist Herbst." },
        { who: "chloe", fr: "Et dans un mois, c'est l'hiver !", en: "And in a month, it's winter!", de: "Und in einem Monat ist Winter!" },
        { who: "blob", fr: "L'hiver ? Il va neiger ?", en: "Winter? Is it going to snow?", de: "Winter? Wird es schneien?" },
        { who: "chloe", fr: "Oui, peut-être, et en décembre, il fait très froid !", en: "Yes, maybe, and in December it's very cold!", de: "Ja, vielleicht, und im Dezember ist es sehr kalt!" },
        { who: "blob", fr: "Super ! J'adore la neige ! Mais… où est mon béret ?", en: "Great! I love snow! But… where's my beret?", de: "Super! Ich liebe Schnee! Aber … wo ist meine Baskenmütze?" },
        { who: "lea", fr: "Sur ta tête, Blob !", en: "On your head, Blob!", de: "Auf deinem Kopf, Blob!" },
      ],
      questions: [
        { q: tx("What's the weather like?", "Wie ist das Wetter?"), options: [tx("Cold and windy", "Kalt und windig"), tx("Hot and sunny", "Heiß und sonnig"), tx("It's snowing.", "Es schneit.")], answer: 0 },
        { q: tx("Which month is it?", "Welcher Monat ist es?"), options: [tx("November", "November"), tx("July", "Juli"), tx("December", "Dezember")], answer: 0 },
        { q: tx("Where is Blob's beret?", "Wo ist Blobs Baskenmütze?"), options: [tx("On his head", "Auf seinem Kopf"), tx("In Lyon", "In Lyon"), tx("At home", "Zu Hause")], answer: 0 },
      ],
    },
    {
      id: "u18.dialogue2",
      lesson: 7,
      title: tx("A picnic for Chloé", "Ein Picknick für Chloé"),
      lines: [
        { who: "hugo", fr: "Chloé, ton anniversaire, c'est quand ?", en: "Chloé, when's your birthday?", de: "Chloé, wann hast du Geburtstag?" },
        { who: "chloe", fr: "C'est le premier juin, samedi !", en: "It's on the first of June, on Saturday!", de: "Am ersten Juni, am Samstag!" },
        { who: "hugo", fr: "Super ! On fait un pique-nique pour ton anniversaire ?", en: "Great! Shall we have a picnic for your birthday?", de: "Super! Machen wir ein Picknick zu deinem Geburtstag?" },
        { who: "chloe", fr: "Oh oui ! Au parc, à côté de la piscine.", en: "Oh yes! In the park, next to the swimming pool.", de: "Oh ja! Im Park, neben dem Schwimmbad." },
        { who: "blob", fr: "Et il va faire beau : vingt-cinq degrés et du soleil !", en: "And the weather's going to be nice: twenty-five degrees and sunshine!", de: "Und das Wetter wird schön: fünfundzwanzig Grad und Sonne!" },
        { who: "lea", fr: "Samedi… Oh non, regardez : il pleut !", en: "Saturday… Oh no, look: it's raining!", de: "Samstag … Oh nein, schaut: Es regnet!" },
        { who: "hugo", fr: "Blob, tu as un parapluie ?", en: "Blob, have you got an umbrella?", de: "Blob, hast du einen Regenschirm?" },
        { who: "blob", fr: "Non, mais j'ai un béret !", en: "No, but I've got a beret!", de: "Nein, aber ich habe eine Baskenmütze!" },
        { who: "lea", fr: "Bon, on fait le pique-nique à la maison !", en: "Well, we'll have the picnic at home!", de: "Na gut, dann machen wir das Picknick zu Hause!" },
        { who: "chloe", fr: "D'accord ! Un pique-nique dans le salon, c'est drôle !", en: "OK! A picnic in the living room is fun!", de: "Okay! Ein Picknick im Wohnzimmer ist lustig!" },
      ],
      questions: [
        { q: tx("When is Chloé's birthday?", "Wann hat Chloé Geburtstag?"), options: [tx("On the first of June", "Am ersten Juni"), tx("On the fourteenth of July", "Am vierzehnten Juli"), tx("In December", "Im Dezember")], answer: 0 },
        { q: tx("What's the weather like on Saturday?", "Wie ist das Wetter am Samstag?"), options: [tx("It's raining.", "Es regnet."), tx("It's hot and sunny.", "Es ist heiß und sonnig."), tx("It's snowing.", "Es schneit.")], answer: 0 },
        { q: tx("Where do they have the picnic in the end?", "Wo machen sie am Ende das Picknick?"), options: [tx("At home, in the living room", "Zu Hause, im Wohnzimmer"), tx("In the park", "Im Park"), tx("At the beach", "Am Strand")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Il fait…: the weather", "Il fait …: das Wetter"),
      body: tx(
        "The weather mostly uses **il fait** + adjective: il fait **beau**, il fait **chaud**, il fait **froid**, il fait **mauvais**. Ask **quel temps fait-il ?**\n\nRain and snow have verbs of their own: **il pleut**, **il neige**. Sun, wind and clouds come with **il y a**: il y a **du** soleil, **du** vent, **des** nuages.",
        "Beim Wetter steht meist **il fait** + Adjektiv: il fait **beau**, il fait **chaud**, il fait **froid**, il fait **mauvais**. Frag **quel temps fait-il ?**\n\nRegen und Schnee haben eigene Verben: **il pleut**, **il neige**. Sonne, Wind und Wolken kommen mit **il y a**: il y a **du** soleil, **du** vent, **des** nuages.",
      ),
      examples: [
        { fr: "Quel temps fait-il aujourd'hui ?", en: "What's the weather like today?", de: "Wie ist das Wetter heute?" },
        { fr: "Il fait chaud, il y a du soleil.", en: "It's hot, it's sunny.", de: "Es ist heiß, die Sonne scheint." },
        { fr: "Il pleut et il y a du vent.", en: "It's raining and it's windy.", de: "Es regnet und es ist windig." },
      ],
      table: {
        head: [tx("weather", "Wetter"), tx("French", "Französisch")],
        rows: [
          [tx("it's nice", "es ist schön"), "il fait beau"],
          [tx("it's bad", "es ist schlecht"), "il fait mauvais"],
          [tx("it's raining / snowing", "es regnet / schneit"), "il pleut / il neige"],
          [tx("it's sunny / windy", "sonnig / windig"), "il y a du soleil / du vent"],
        ],
      },
    },
    {
      title: tx("In spring, in summer", "Im Frühling, im Sommer"),
      body: tx(
        "All four seasons are masculine. To say «in»: **en** été, **en** automne, **en** hiver, because they start with a vowel sound. Printemps doesn't, so it's **au** printemps.\n\nYour favourite: ma saison **préférée**, with -ée, because saison is feminine.",
        "Alle vier Jahreszeiten sind männlich. Für „im“: **en** été, **en** automne, **en** hiver, weil sie mit einem Vokal klingen. Printemps nicht, darum **au** printemps.\n\nDeine liebste: ma saison **préférée**, mit -ée, weil saison weiblich ist.",
      ),
      examples: [
        { fr: "Au printemps, il y a beaucoup de fleurs.", en: "In spring there are lots of flowers.", de: "Im Frühling gibt es viele Blumen." },
        { fr: "En hiver, il fait froid et il neige.", en: "In winter it's cold and it snows.", de: "Im Winter ist es kalt und es schneit." },
        { fr: "L'automne est ma saison préférée.", en: "Autumn is my favourite season.", de: "Der Herbst ist meine Lieblingsjahreszeit." },
      ],
      table: {
        head: [tx("season", "Jahreszeit"), tx("in…", "im …")],
        rows: [
          ["le printemps", "au printemps"],
          ["l'été", "en été"],
          ["l'automne", "en automne"],
          ["l'hiver", "en hiver"],
        ],
      },
    },
    {
      title: tx("Months and dates", "Monate und Daten"),
      body: tx(
        "Months are written small and they're all masculine. In a month: **en** mai, **en** octobre.\n\nA date is **le** + number + month, without «of» or a dot: **le douze mars**, **le quatorze juillet**. Only the first is different: **le premier** mai. Ask about a birthday: ton anniversaire, **c'est quand ?**",
        "Monate schreibt man klein, und sie sind alle männlich. In einem Monat: **en** mai, **en** octobre.\n\nEin Datum ist **le** + Zahl + Monat, ohne Punkt: **le douze mars**, **le quatorze juillet**. Nur der Erste ist anders: **le premier** mai. Nach dem Geburtstag fragen: ton anniversaire, **c'est quand ?**",
      ),
      examples: [
        { fr: "Mon anniversaire, c'est le douze mars.", en: "My birthday is on the twelfth of March.", de: "Mein Geburtstag ist am zwölften März." },
        { fr: "Les vacances commencent en juin.", en: "The holidays start in June.", de: "Die Ferien beginnen im Juni." },
        { fr: "Aujourd'hui, c'est le premier mai.", en: "Today is the first of May.", de: "Heute ist der erste Mai." },
      ],
      table: {
        head: [tx("January–June", "Januar–Juni"), tx("July–December", "Juli–Dezember")],
        rows: [
          ["janvier", "juillet"],
          ["février", "août"],
          ["mars", "septembre"],
          ["avril", "octobre"],
          ["mai", "novembre"],
          ["juin", "décembre"],
        ],
      },
    },
    {
      title: tx("Yesterday, today, tomorrow", "Gestern, heute, morgen"),
      body: tx(
        "The weather in the past takes **avoir**: il **a fait** beau, il **a plu**, il **a neigé**. In the future, use aller + infinitive: il **va faire** beau, il **va pleuvoir**, il **va neiger**.\n\nTemperatures: il fait vingt **degrés**, or moins cinq degrés when it's freezing.",
        "Das Wetter in der Vergangenheit nimmt **avoir**: il **a fait** beau, il **a plu**, il **a neigé**. In der Zukunft: aller + Infinitiv: il **va faire** beau, il **va pleuvoir**, il **va neiger**.\n\nTemperaturen: il fait vingt **degrés**, oder moins cinq degrés, wenn es friert.",
      ),
      examples: [
        { fr: "Hier, il a fait très chaud.", en: "Yesterday it was very hot.", de: "Gestern war es sehr heiß." },
        { fr: "Demain, il va neiger.", en: "It's going to snow tomorrow.", de: "Morgen wird es schneien." },
        { fr: "Il fait trente degrés !", en: "It's thirty degrees!", de: "Es ist dreißig Grad!" },
      ],
      table: {
        head: [tx("today", "heute"), tx("yesterday", "gestern"), tx("tomorrow", "morgen")],
        rows: [
          ["il fait beau", "il a fait beau", "il va faire beau"],
          ["il pleut", "il a plu", "il va pleuvoir"],
          ["il neige", "il a neigé", "il va neiger"],
        ],
      },
    },
  ],
};
