import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 19: vouloir, pouvoir and venir. */
export const u19: Unit = {
  slug: "sorties",
  n: 19,
  cefr: "A2",
  title: tx("Going out", "Ausgehen"),
  goal: tx("Invite friends, say yes or no politely", "Freunde einladen, höflich zu- oder absagen"),
  emoji: "🎉",
  words: [
    { id: "je-veux", fr: "je veux", en: "I want", de: "ich will", alt: { de: ["ich möchte"] }, kind: "verb", note: tx("From vouloir. A bit direct: to a waiter, je voudrais is politer.", "Von vouloir. Etwas direkt: Beim Kellner ist je voudrais höflicher.") },
    { id: "tu-veux", fr: "tu veux", en: "you want", de: "du willst", alt: { de: ["du möchtest"] }, kind: "verb", note: tx("The easy way to invite: tu veux venir ?", "So lädt man ganz einfach ein: tu veux venir ?") },
    { id: "il-veut", fr: "il veut", en: "he wants", de: "er will", alt: { de: ["er möchte"] }, kind: "verb", note: tx("With a t: il veut, elle veut.", "Mit t: il veut, elle veut.") },
    { id: "film", fr: "le film", en: "the film", de: "der Film", alt: { en: ["the movie"] }, g: "m", kind: "noun", emoji: "🎞️" },
    { id: "restaurant", fr: "le restaurant", en: "the restaurant", de: "das Restaurant", g: "m", kind: "noun", emoji: "🍴", note: tx("The final t is silent: «res-toh-ran».", "Das t am Ende ist stumm: „res-to-rã“.") },
    { id: "je-peux", fr: "je peux", en: "I can", de: "ich kann", alt: { en: ["I may"], de: ["ich darf"] }, kind: "verb", note: tx("From pouvoir. Je peux venir ? Can I come?", "Von pouvoir. Je peux venir ? Kann ich mitkommen?") },
    { id: "tu-peux", fr: "tu peux", en: "you can", de: "du kannst", alt: { de: ["du darfst"] }, kind: "verb" },
    { id: "il-peut", fr: "il peut", en: "he can", de: "er kann", alt: { de: ["er darf"] }, kind: "verb", note: tx("With a t, like il veut.", "Mit t, wie il veut.") },
    { id: "d-accord", fr: "d'accord", en: "OK", de: "okay", alt: { en: ["all right", "agreed"], de: ["einverstanden", "in Ordnung"] }, kind: "phrase", emoji: "👌", note: tx("The everyday yes. Je suis d'accord: I agree.", "Das alltägliche Ja. Je suis d'accord: Ich bin einverstanden.") },
    { id: "desole", fr: "désolé", en: "sorry", de: "tut mir leid", alt: { fr: ["désolée"], en: ["I'm sorry"], de: ["Entschuldigung"] }, kind: "adj", emoji: "😔", note: tx("A girl writes désolée. The polite no: désolé, je ne peux pas.", "Ein Mädchen schreibt désolée. Das höfliche Nein: désolé, je ne peux pas.") },
    { id: "je-viens", fr: "je viens", en: "I come", de: "ich komme", alt: { en: ["I'm coming"] }, kind: "verb", note: tx("From venir. Je viens de Lyon: I come from Lyon.", "Von venir. Je viens de Lyon: Ich komme aus Lyon.") },
    { id: "tu-viens", fr: "tu viens", en: "you come", de: "du kommst", alt: { en: ["you're coming"] }, kind: "verb", note: tx("Tu viens ? Are you coming? The quickest invitation.", "Tu viens ? Kommst du mit? Die schnellste Einladung.") },
    { id: "il-vient", fr: "il vient", en: "he comes", de: "er kommt", alt: { en: ["he's coming"] }, kind: "verb" },
    { id: "fete", fr: "la fête", en: "the party", de: "die Party", alt: { de: ["das Fest", "die Feier"] }, g: "f", kind: "noun", emoji: "🥳", note: tx("Also a festival. Faire la fête: to party!", "Auch ein Fest. Faire la fête: feiern!") },
    { id: "concert", fr: "le concert", en: "the concert", de: "das Konzert", g: "m", kind: "noun", emoji: "🎤" },
    { id: "vous-voulez", fr: "vous voulez", en: "you want (plural / polite)", de: "ihr wollt / Sie wollen", alt: { en: ["you want", "would you like"], de: ["ihr wollt", "Sie wollen", "möchten Sie"] }, kind: "verb", note: tx("Vous voulez un café ? Polite enough for an offer.", "Vous voulez un café ? Höflich genug für ein Angebot.") },
    { id: "vous-pouvez", fr: "vous pouvez", en: "you can (plural / polite)", de: "ihr könnt / Sie können", alt: { en: ["you can", "could you"], de: ["ihr könnt", "Sie können"] }, kind: "verb", note: tx("Vous pouvez répéter ? Can you say that again? Very useful!", "Vous pouvez répéter ? Können Sie das wiederholen? Sehr nützlich!") },
    { id: "rendez-vous", fr: "le rendez-vous", en: "the meeting", de: "das Treffen", alt: { en: ["the appointment", "the date"], de: ["der Termin", "die Verabredung"] }, g: "m", kind: "noun", emoji: "📍", note: tx("Meeting friends, a date, or an appointment at the doctor's. The s is silent.", "Ein Treffen mit Freunden, ein Date oder ein Arzttermin. Das s ist stumm.") },
    { id: "ensemble", fr: "ensemble", en: "together", de: "zusammen", alt: { de: ["gemeinsam"] }, kind: "adv", emoji: "👫" },
    { id: "on-y-va", fr: "on y va !", en: "let's go!", de: "los geht's!", alt: { en: ["shall we go?"], de: ["gehen wir!", "auf geht's!"] }, kind: "phrase", note: tx("Literally «we go there». As a question, on y va ? means shall we go?", "Wörtlich „wir gehen dahin“. Als Frage, on y va ?, heißt es: Gehen wir?") },
    { id: "avec-plaisir", fr: "avec plaisir", en: "with pleasure", de: "gern", alt: { en: ["I'd love to", "gladly"], de: ["gerne", "mit Vergnügen"] }, kind: "phrase", emoji: "😊", note: tx("A warm yes to an invitation. Also: je veux bien.", "Ein herzliches Ja auf eine Einladung. Auch: je veux bien.") },
    { id: "libre", fr: "libre", en: "free", de: "frei", alt: { en: ["available"] }, kind: "adj", note: tx("Tu es libre samedi ? Are you free on Saturday? Free of charge is gratuit.", "Tu es libre samedi ? Hast du Samstag Zeit? Kostenlos heißt gratuit.") },
    { id: "nous-voulons", fr: "nous voulons", en: "we want", de: "wir wollen", kind: "verb" },
    { id: "ils-veulent", fr: "ils veulent", en: "they want", de: "sie wollen", kind: "verb", note: tx("The vowel changes like in il veut: ils veulent.", "Der Vokal ändert sich wie bei il veut: ils veulent.") },
    { id: "nous-pouvons", fr: "nous pouvons", en: "we can", de: "wir können", kind: "verb" },
    { id: "ils-peuvent", fr: "ils peuvent", en: "they can", de: "sie können", kind: "verb" },
    { id: "dommage", fr: "dommage !", en: "what a pity!", de: "schade!", alt: { en: ["what a shame!", "too bad!"], de: ["wie schade!"] }, kind: "phrase", note: tx("C'est dommage: it's a pity.", "C'est dommage: Das ist schade.") },
    { id: "une-autre-fois", fr: "une autre fois", en: "another time", de: "ein anderes Mal", alt: { de: ["ein andermal"] }, kind: "phrase", note: tx("The friendly way to say not now: une autre fois, peut-être ?", "So sagt man freundlich „jetzt nicht“: une autre fois, peut-être ?") },
    { id: "vous-venez", fr: "vous venez", en: "you come (plural / polite)", de: "ihr kommt / Sie kommen", alt: { en: ["you come", "you're coming"], de: ["ihr kommt", "Sie kommen"] }, kind: "verb", note: tx("Venir: je viens, tu viens, il vient, nous venons, vous venez, ils viennent.", "Venir: je viens, tu viens, il vient, nous venons, vous venez, ils viennent.") },
  ],
  gloss: [
    { fr: "veux", en: "want", de: "will / willst" },
    { fr: "veut", en: "wants", de: "will" },
    { fr: "veulent", en: "want (they)", de: "wollen (sie)" },
    { fr: "peux", en: "can", de: "kann / kannst" },
    { fr: "peut", en: "can (he / she)", de: "kann" },
    { fr: "peuvent", en: "can (they)", de: "können (sie)" },
    { fr: "viens", en: "come", de: "komme / kommst" },
    { fr: "vient", en: "comes", de: "kommt" },
    { fr: "venir", en: "to come", de: "kommen" },
    { fr: "désolée", en: "sorry (said by a girl)", de: "tut mir leid (von einem Mädchen)" },
    { fr: "je veux bien", en: "I'd love to / yes, please", de: "gern / ja, bitte" },
    { fr: "heures", en: "o'clock / hours", de: "Uhr / Stunden" },
    { fr: "il est huit heures", en: "it's eight o'clock", de: "es ist acht Uhr" },
    { fr: "répéter", en: "to repeat", de: "wiederholen" },
    { fr: "tout le monde", en: "everybody", de: "alle" },
    { fr: "là", en: "there / here", de: "da" },
    { fr: "commence", en: "starts", de: "fängt an / beginnt" },
    { fr: "à samedi", en: "see you on Saturday", de: "bis Samstag" },
    { fr: "allés", en: "gone / went (plural)", de: "gegangen" },
    { fr: "sommes allés", en: "went (we)", de: "sind gegangen" },
    { fr: "artiste", en: "artist", de: "Künstler" },
    { fr: "concerts", en: "concerts", de: "Konzerte" },
    { fr: "pas trop fort", en: "not too loud", de: "nicht zu laut" },
    { fr: "problème", en: "problem", de: "Problem" },
    { fr: "pas de problème", en: "no problem", de: "kein Problem" },
    { fr: "allez, on y va", en: "come on, let's go", de: "los, gehen wir" },
  ],
  lessons: [
    { title: tx("I want…", "Ich will …"), words: ["je-veux", "tu-veux", "il-veut", "film", "restaurant"] },
    { title: tx("I can't, sorry", "Ich kann nicht, tut mir leid"), words: ["je-peux", "tu-peux", "il-peut", "d-accord", "desole"] },
    { title: tx("Are you coming?", "Kommst du?"), words: ["je-viens", "tu-viens", "il-vient", "fete", "concert"] },
    { title: tx("Polite invitations", "Höflich einladen"), words: ["vous-voulez", "vous-pouvez", "rendez-vous", "ensemble"] },
    { title: tx("Let's go!", "Los geht's!"), words: ["on-y-va", "avec-plaisir", "libre"] },
    { title: tx("We want, they can", "Wir wollen, sie können"), words: ["nous-voulons", "ils-veulent", "nous-pouvons", "ils-peuvent"] },
    { title: tx("Another time", "Ein anderes Mal"), words: ["dommage", "une-autre-fois", "vous-venez"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u19.01", lesson: 1, fr: "Je veux voir un film.", en: "I want to see a film.", de: "Ich will einen Film sehen.", alt: { en: ["I want to watch a film.", "I want to see a movie.", "I want to watch a movie."], de: ["Ich möchte einen Film sehen.", "Ich will einen Film anschauen.", "Ich will einen Film gucken."] } },
    { id: "u19.02", lesson: 1, fr: "Tu veux aller au restaurant ?", en: "Do you want to go to a restaurant?", de: "Willst du ins Restaurant gehen?", alt: { fr: ["Est-ce que tu veux aller au restaurant ?", "Veux-tu aller au restaurant ?", "Vous voulez aller au restaurant ?", "Est-ce que vous voulez aller au restaurant ?", "Voulez-vous aller au restaurant ?"], en: ["Do you want to go to the restaurant?", "Would you like to go to a restaurant?", "Would you like to go to the restaurant?"], de: ["Möchtest du ins Restaurant gehen?", "Willst du ins Restaurant?", "Möchtest du ins Restaurant?"] } },
    { id: "u19.03", lesson: 1, fr: "Il veut manger une pizza.", en: "He wants to eat a pizza.", de: "Er will eine Pizza essen.", alt: { en: ["He wants to have a pizza."], de: ["Er möchte eine Pizza essen."] } },
    { id: "u19.04", lesson: 1, fr: "Je ne veux pas voir ce film.", en: "I don't want to see this film.", de: "Ich will diesen Film nicht sehen.", alt: { en: ["I don't want to watch this film.", "I don't want to see this movie.", "I don't want to watch this movie.", "I don't want to see that film.", "I don't want to watch that film."], de: ["Ich will diesen Film nicht anschauen.", "Ich möchte diesen Film nicht sehen.", "Ich will den Film nicht sehen."] } },
    { id: "u19.05", lesson: 1, fr: "Le restaurant est très bon.", en: "The restaurant is very good.", de: "Das Restaurant ist sehr gut.", alt: { en: ["The restaurant's very good."] } },
    { id: "u19.06", lesson: 1, fr: "Léa veut un nouveau vélo.", en: "Léa wants a new bike.", de: "Léa will ein neues Fahrrad.", alt: { en: ["Léa wants a new bicycle."], de: ["Léa möchte ein neues Fahrrad.", "Léa will ein neues Rad."] } },
    { id: "u19.07", lesson: 1, fr: "Qu'est-ce que tu veux faire ce soir ?", en: "What do you want to do this evening?", de: "Was willst du heute Abend machen?", alt: { fr: ["Tu veux faire quoi ce soir ?", "Que veux-tu faire ce soir ?", "Qu'est-ce que vous voulez faire ce soir ?", "Vous voulez faire quoi ce soir ?", "Ce soir, tu veux faire quoi ?"], en: ["What do you want to do tonight?", "What would you like to do this evening?", "What would you like to do tonight?"], de: ["Was möchtest du heute Abend machen?", "Was willst du heute Abend tun?", "Was möchtest du heute Abend tun?"] } },
    // Lesson 2
    { id: "u19.08", lesson: 2, fr: "Je peux venir avec toi ?", en: "Can I come with you?", de: "Kann ich mit dir kommen?", alt: { fr: ["Est-ce que je peux venir avec toi ?", "Je peux venir avec vous ?", "Est-ce que je peux venir avec vous ?", "Puis-je venir avec toi ?", "Puis-je venir avec vous ?"], en: ["May I come with you?"], de: ["Kann ich mitkommen?", "Darf ich mitkommen?", "Darf ich mit dir kommen?"] } },
    { id: "u19.09", lesson: 2, fr: "Désolé, je ne peux pas.", en: "Sorry, I can't.", de: "Tut mir leid, ich kann nicht.", alt: { fr: ["Désolée, je ne peux pas.", "Désolé, je peux pas.", "Désolée, je peux pas."], en: ["I'm sorry, I can't."], de: ["Sorry, ich kann nicht.", "Leider kann ich nicht.", "Entschuldigung, ich kann nicht."] } },
    { id: "u19.10", lesson: 2, fr: "Tu peux venir samedi ?", en: "Can you come on Saturday?", de: "Kannst du am Samstag kommen?", alt: { fr: ["Est-ce que tu peux venir samedi ?", "Peux-tu venir samedi ?", "Vous pouvez venir samedi ?", "Est-ce que vous pouvez venir samedi ?", "Pouvez-vous venir samedi ?"], en: ["Can you come Saturday?", "Are you able to come on Saturday?"], de: ["Kannst du Samstag kommen?"] } },
    { id: "u19.11", lesson: 2, fr: "D'accord, on va au cinéma !", en: "OK, let's go to the cinema!", de: "Okay, gehen wir ins Kino!", alt: { fr: ["D'accord, allons au cinéma !"], en: ["All right, let's go to the cinema!", "OK, we're going to the cinema!", "OK, let's go to the movies!"], de: ["Einverstanden, wir gehen ins Kino!", "Okay, wir gehen ins Kino!", "Einverstanden, gehen wir ins Kino!"] } },
    { id: "u19.12", lesson: 2, fr: "Hugo ne peut pas venir, il est malade.", en: "Hugo can't come, he's ill.", de: "Hugo kann nicht kommen, er ist krank.", alt: { en: ["Hugo can't come, he's sick.", "Hugo can't come because he's ill.", "Hugo can't come because he's sick."], de: ["Hugo kann nicht kommen, weil er krank ist."] } },
    { id: "u19.13", lesson: 2, fr: "Il peut dormir chez nous.", en: "He can sleep at our place.", de: "Er kann bei uns schlafen.", alt: { en: ["He can sleep at our house.", "He can stay the night at our place."], de: ["Er kann bei uns übernachten."] } },
    { id: "u19.14", lesson: 2, fr: "Désolée, Hugo, je ne peux pas venir ce soir.", en: "Sorry, Hugo, I can't come this evening.", de: "Tut mir leid, Hugo, ich kann heute Abend nicht kommen.", alt: { fr: ["Désolé, Hugo, je ne peux pas venir ce soir."], en: ["Sorry, Hugo, I can't come tonight.", "I'm sorry, Hugo, I can't come this evening.", "I'm sorry, Hugo, I can't come tonight."], de: ["Sorry, Hugo, ich kann heute Abend nicht kommen.", "Tut mir leid, Hugo, heute Abend kann ich nicht kommen."] } },
    // Lesson 3
    { id: "u19.15", lesson: 3, fr: "Tu viens à ma fête ?", en: "Are you coming to my party?", de: "Kommst du zu meiner Party?", alt: { fr: ["Est-ce que tu viens à ma fête ?", "Viens-tu à ma fête ?", "Vous venez à ma fête ?", "Est-ce que vous venez à ma fête ?"], en: ["Will you come to my party?"], de: ["Kommst du zu meinem Fest?", "Kommst du zu meiner Feier?", "Kommst du auf meine Party?"] } },
    { id: "u19.16", lesson: 3, fr: "Oui, je viens avec Chloé.", en: "Yes, I'm coming with Chloé.", de: "Ja, ich komme mit Chloé.", alt: { en: ["Yes, I'll come with Chloé.", "Yes, I come with Chloé."], de: ["Ja, ich komme zusammen mit Chloé."] } },
    { id: "u19.17", lesson: 3, fr: "Le concert est à vingt heures.", en: "The concert is at eight in the evening.", de: "Das Konzert ist um zwanzig Uhr.", alt: { en: ["The concert is at 8 pm.", "The concert is at eight pm.", "The concert is at 8 in the evening.", "The concert is at eight o'clock in the evening."], de: ["Das Konzert ist um 20 Uhr.", "Das Konzert ist um acht Uhr abends.", "Das Konzert beginnt um zwanzig Uhr.", "Das Konzert beginnt um 20 Uhr."] } },
    { id: "u19.18", lesson: 3, fr: "Il vient de Lyon.", en: "He comes from Lyon.", de: "Er kommt aus Lyon.", alt: { en: ["He's from Lyon."] } },
    { id: "u19.19", lesson: 3, fr: "Chloé vient à la fête ce soir.", en: "Chloé is coming to the party this evening.", de: "Chloé kommt heute Abend zur Party.", alt: { fr: ["Ce soir, Chloé vient à la fête."], en: ["Chloé is coming to the party tonight.", "Chloé comes to the party this evening."], de: ["Chloé kommt heute Abend auf die Party.", "Heute Abend kommt Chloé zur Party.", "Chloé kommt heute Abend zum Fest."] } },
    { id: "u19.20", lesson: 3, fr: "Je veux aller au concert samedi.", en: "I want to go to the concert on Saturday.", de: "Ich will am Samstag ins Konzert gehen.", alt: { fr: ["Samedi, je veux aller au concert."], en: ["On Saturday I want to go to the concert."], de: ["Ich möchte am Samstag ins Konzert gehen.", "Ich will am Samstag zum Konzert gehen.", "Am Samstag will ich ins Konzert gehen."] } },
    { id: "u19.21", lesson: 3, fr: "Hier, je suis venu à la fête de Léa.", en: "Yesterday I came to Léa's party.", de: "Gestern bin ich zu Léas Party gekommen.", alt: { fr: ["Hier, je suis venue à la fête de Léa.", "Je suis venu à la fête de Léa hier.", "Je suis venue à la fête de Léa hier."], en: ["I came to Léa's party yesterday."], de: ["Ich bin gestern zu Léas Party gekommen.", "Gestern kam ich zu Léas Party.", "Gestern bin ich zu Léas Fest gekommen."] } },
    // Lesson 4
    { id: "u19.22", lesson: 4, fr: "Vous voulez venir avec nous ?", en: "Do you want to come with us?", de: "Wollt ihr mitkommen?", alt: { fr: ["Est-ce que vous voulez venir avec nous ?", "Voulez-vous venir avec nous ?", "Tu veux venir avec nous ?", "Est-ce que tu veux venir avec nous ?", "Veux-tu venir avec nous ?"], en: ["Would you like to come with us?"], de: ["Wollt ihr mit uns kommen?", "Wollen Sie mitkommen?", "Wollen Sie mit uns kommen?", "Möchtet ihr mitkommen?", "Möchten Sie mitkommen?"] } },
    { id: "u19.23", lesson: 4, fr: "Vous pouvez répéter, s'il vous plaît ?", en: "Can you repeat that, please?", de: "Können Sie das bitte wiederholen?", alt: { fr: ["Est-ce que vous pouvez répéter, s'il vous plaît ?", "Pouvez-vous répéter, s'il vous plaît ?", "Tu peux répéter, s'il te plaît ?"], en: ["Could you repeat that, please?", "Can you say that again, please?", "Can you repeat, please?"], de: ["Könnt ihr das bitte wiederholen?", "Können Sie bitte wiederholen?", "Kannst du das bitte wiederholen?"] } },
    { id: "u19.24", lesson: 4, fr: "On a rendez-vous à huit heures devant le cinéma.", en: "We're meeting at eight o'clock in front of the cinema.", de: "Wir treffen uns um acht Uhr vor dem Kino.", alt: { fr: ["Nous avons rendez-vous à huit heures devant le cinéma.", "Rendez-vous à huit heures devant le cinéma."], en: ["We're meeting at 8 o'clock in front of the cinema.", "We're meeting at eight in front of the cinema.", "We're meeting at 8 in front of the cinema.", "We meet at eight o'clock in front of the cinema.", "We're meeting at eight o'clock outside the cinema.", "We're meeting at 8 o'clock outside the cinema."], de: ["Wir treffen uns um 8 Uhr vor dem Kino."] } },
    { id: "u19.25", lesson: 4, fr: "On fait les devoirs ensemble ?", en: "Shall we do our homework together?", de: "Machen wir die Hausaufgaben zusammen?", alt: { fr: ["On fait nos devoirs ensemble ?", "Nous faisons les devoirs ensemble ?"], en: ["Shall we do the homework together?", "Should we do our homework together?", "Are we doing our homework together?"], de: ["Machen wir die Hausaufgaben gemeinsam?", "Machen wir zusammen Hausaufgaben?"] } },
    { id: "u19.26", lesson: 4, fr: "Monsieur Martin, vous voulez un café ?", en: "Mr Martin, would you like a coffee?", de: "Herr Martin, möchten Sie einen Kaffee?", alt: { fr: ["Vous voulez un café, Monsieur Martin ?", "Monsieur Martin, voulez-vous un café ?"], en: ["Mr Martin, do you want a coffee?", "Would you like a coffee, Mr Martin?", "Do you want a coffee, Mr Martin?"], de: ["Möchten Sie einen Kaffee, Herr Martin?", "Herr Martin, wollen Sie einen Kaffee?"] } },
    { id: "u19.27", lesson: 4, fr: "Nous allons ensemble au concert.", en: "We're going to the concert together.", de: "Wir gehen zusammen ins Konzert.", alt: { fr: ["Nous allons au concert ensemble.", "On va ensemble au concert.", "On va au concert ensemble."], en: ["We go to the concert together."], de: ["Wir gehen gemeinsam ins Konzert.", "Wir gehen zusammen zum Konzert."] } },
    { id: "u19.28", lesson: 4, fr: "Le rendez-vous, c'est où ?", en: "Where are we meeting?", de: "Wo treffen wir uns?", alt: { fr: ["C'est où, le rendez-vous ?", "Où est le rendez-vous ?"], en: ["Where's the meeting place?", "Where is the meeting point?", "Where do we meet?"], de: ["Wo ist der Treffpunkt?"] } },
    // Lesson 5
    { id: "u19.29", lesson: 5, fr: "Tu es libre samedi soir ?", en: "Are you free on Saturday evening?", de: "Hast du am Samstagabend Zeit?", alt: { fr: ["Est-ce que tu es libre samedi soir ?", "Es-tu libre samedi soir ?", "Vous êtes libre samedi soir ?", "Est-ce que vous êtes libre samedi soir ?", "Êtes-vous libre samedi soir ?", "Vous êtes libres samedi soir ?"], en: ["Are you free Saturday evening?", "Are you free on Saturday night?", "Are you free Saturday night?"], de: ["Bist du am Samstagabend frei?", "Hast du Samstagabend Zeit?", "Bist du Samstagabend frei?"] } },
    { id: "u19.30", lesson: 5, fr: "Oui, avec plaisir !", en: "Yes, with pleasure!", de: "Ja, gern!", alt: { en: ["Yes, I'd love to!", "Yes, gladly!"], de: ["Ja, gerne!", "Ja, mit Vergnügen!", "Ja, sehr gern!"] } },
    { id: "u19.31", lesson: 5, fr: "Tout le monde est là ? On y va !", en: "Is everyone here? Let's go!", de: "Sind alle da? Los geht's!", alt: { en: ["Is everybody here? Let's go!", "Is everyone there? Let's go!"], de: ["Sind alle da? Auf geht's!", "Sind alle hier? Los geht's!", "Sind alle da? Gehen wir!"] } },
    { id: "u19.32", lesson: 5, fr: "Je ne suis pas libre demain.", en: "I'm not free tomorrow.", de: "Ich habe morgen keine Zeit.", alt: { fr: ["Demain, je ne suis pas libre."], en: ["I'm not available tomorrow.", "Tomorrow I'm not free."], de: ["Morgen habe ich keine Zeit.", "Ich bin morgen nicht frei.", "Morgen bin ich nicht frei."] } },
    { id: "u19.33", lesson: 5, fr: "Il est huit heures, on y va ?", en: "It's eight o'clock, shall we go?", de: "Es ist acht Uhr, gehen wir?", alt: { en: ["It's 8 o'clock, shall we go?", "It's eight, shall we go?", "It's 8, shall we go?", "It's eight o'clock, are we going?"], de: ["Es ist 8 Uhr, gehen wir?", "Es ist acht Uhr, wollen wir los?", "Es ist acht, gehen wir?"] } },
    { id: "u19.34", lesson: 5, fr: "Je veux bien, merci !", en: "I'd love to, thank you!", de: "Gern, danke!", alt: { fr: ["Avec plaisir, merci !"], en: ["I'd love to, thanks!", "Gladly, thank you!", "Yes please, thank you!"], de: ["Gerne, danke!", "Sehr gern, danke!"] } },
    { id: "u19.35", lesson: 5, fr: "Allez, on y va, le film commence !", en: "Come on, let's go, the film's starting!", de: "Komm, los geht's, der Film fängt an!", alt: { en: ["Come on, let's go, the film is starting!", "Come on, let's go, the movie's starting!", "Come on, let's go, the movie is starting!"], de: ["Kommt, los geht's, der Film fängt an!", "Komm, los geht's, der Film beginnt!", "Kommt, los geht's, der Film beginnt!", "Los, gehen wir, der Film beginnt!"] } },
    // Lesson 6
    { id: "u19.36", lesson: 6, fr: "Nous voulons aller à la plage.", en: "We want to go to the beach.", de: "Wir wollen an den Strand gehen.", alt: { fr: ["On veut aller à la plage."], de: ["Wir wollen an den Strand.", "Wir möchten an den Strand gehen.", "Wir wollen zum Strand gehen."] } },
    { id: "u19.37", lesson: 6, fr: "Ils veulent voir le concert.", en: "They want to see the concert.", de: "Sie wollen das Konzert sehen.", alt: { fr: ["Elles veulent voir le concert."], de: ["Sie möchten das Konzert sehen."] } },
    { id: "u19.38", lesson: 6, fr: "Nous pouvons faire un pique-nique.", en: "We can have a picnic.", de: "Wir können ein Picknick machen.", alt: { fr: ["On peut faire un pique-nique."] } },
    { id: "u19.39", lesson: 6, fr: "Ils ne peuvent pas venir : ils sont en vacances.", en: "They can't come, they're on holiday.", de: "Sie können nicht kommen, sie sind im Urlaub.", alt: { fr: ["Elles ne peuvent pas venir : elles sont en vacances."], en: ["They can't come because they're on holiday.", "They can't come, they're on vacation."], de: ["Sie können nicht kommen, sie sind in den Ferien.", "Sie können nicht kommen, weil sie im Urlaub sind."] } },
    { id: "u19.40", lesson: 6, fr: "Est-ce que nous pouvons venir ensemble ?", en: "Can we come together?", de: "Können wir zusammen kommen?", alt: { fr: ["Nous pouvons venir ensemble ?", "Pouvons-nous venir ensemble ?", "On peut venir ensemble ?", "Est-ce qu'on peut venir ensemble ?"], en: ["May we come together?"], de: ["Können wir gemeinsam kommen?", "Dürfen wir zusammen kommen?"] } },
    { id: "u19.41", lesson: 6, fr: "Les enfants veulent manger des crêpes.", en: "The children want to eat crêpes.", de: "Die Kinder wollen Crêpes essen.", alt: { en: ["The kids want to eat crêpes.", "The children want to have crêpes.", "The children want to eat pancakes."], de: ["Die Kinder möchten Crêpes essen.", "Die Kinder wollen Pfannkuchen essen."] } },
    { id: "u19.42", lesson: 6, fr: "Demain, nous allons inviter nos amis.", en: "Tomorrow we're going to invite our friends.", de: "Morgen werden wir unsere Freunde einladen.", alt: { fr: ["Nous allons inviter nos amis demain.", "Demain, on va inviter nos amis.", "On va inviter nos amis demain."], en: ["We're going to invite our friends tomorrow.", "Tomorrow we will invite our friends.", "We will invite our friends tomorrow."], de: ["Morgen laden wir unsere Freunde ein.", "Wir werden morgen unsere Freunde einladen.", "Wir laden morgen unsere Freunde ein."] } },
    { id: "u19.43", lesson: 6, fr: "Ils peuvent dormir chez nous ce week-end.", en: "They can sleep at our place this weekend.", de: "Sie können dieses Wochenende bei uns schlafen.", alt: { fr: ["Elles peuvent dormir chez nous ce week-end.", "Ce week-end, ils peuvent dormir chez nous."], en: ["They can sleep at our house this weekend.", "This weekend they can sleep at our place.", "They can stay at our place this weekend."], de: ["Sie können am Wochenende bei uns schlafen.", "Dieses Wochenende können sie bei uns schlafen."] } },
    // Lesson 7
    { id: "u19.44", lesson: 7, fr: "Tu ne peux pas venir ? Dommage !", en: "You can't come? What a pity!", de: "Du kannst nicht kommen? Schade!", alt: { fr: ["Vous ne pouvez pas venir ? Dommage !", "Tu peux pas venir ? Dommage !"], en: ["You can't come? What a shame!", "You can't come? That's a pity!", "You can't come? Too bad!", "You can't come? Pity!", "You can't come? Shame!"], de: ["Du kannst nicht kommen? Wie schade!"] } },
    { id: "u19.45", lesson: 7, fr: "Une autre fois, peut-être ?", en: "Another time, maybe?", de: "Vielleicht ein anderes Mal?", alt: { fr: ["Peut-être une autre fois ?"], en: ["Maybe another time?", "Another time, perhaps?", "Perhaps another time?"], de: ["Ein anderes Mal vielleicht?", "Ein andermal vielleicht?", "Vielleicht ein andermal?"] } },
    { id: "u19.46", lesson: 7, fr: "Vous venez avec nous, Madame Martin ?", en: "Are you coming with us, Mrs Martin?", de: "Kommen Sie mit, Frau Martin?", alt: { fr: ["Est-ce que vous venez avec nous, Madame Martin ?", "Venez-vous avec nous, Madame Martin ?", "Madame Martin, vous venez avec nous ?"], en: ["Will you come with us, Mrs Martin?", "Mrs Martin, are you coming with us?"], de: ["Kommen Sie mit uns, Frau Martin?", "Frau Martin, kommen Sie mit?"] } },
    { id: "u19.47", lesson: 7, fr: "Désolé, je ne peux pas, je dois travailler.", en: "Sorry, I can't, I have to work.", de: "Tut mir leid, ich kann nicht, ich muss arbeiten.", alt: { fr: ["Désolée, je ne peux pas, je dois travailler."], en: ["I'm sorry, I can't, I have to work.", "Sorry, I can't, I must work.", "Sorry, I can't, I've got to work."], de: ["Sorry, ich kann nicht, ich muss arbeiten.", "Leider kann ich nicht, ich muss arbeiten."] } },
    { id: "u19.48", lesson: 7, fr: "D'accord, à samedi !", en: "OK, see you on Saturday!", de: "Okay, bis Samstag!", alt: { en: ["OK, see you Saturday!", "All right, see you on Saturday!", "All right, see you Saturday!"], de: ["Einverstanden, bis Samstag!", "Gut, bis Samstag!"] } },
    { id: "u19.49", lesson: 7, fr: "Vous venez à quelle heure ?", en: "What time are you coming?", de: "Um wie viel Uhr kommt ihr?", alt: { fr: ["À quelle heure vous venez ?", "À quelle heure est-ce que vous venez ?", "À quelle heure venez-vous ?", "Tu viens à quelle heure ?", "À quelle heure tu viens ?", "À quelle heure est-ce que tu viens ?"], en: ["What time will you come?", "When are you coming?"], de: ["Wann kommt ihr?", "Um wie viel Uhr kommen Sie?", "Wann kommen Sie?", "Um wieviel Uhr kommt ihr?"] } },
    { id: "u19.50", lesson: 7, fr: "Hier soir, nous sommes allés au concert ensemble.", en: "Last night we went to the concert together.", de: "Gestern Abend sind wir zusammen ins Konzert gegangen.", alt: { fr: ["Hier soir, nous sommes allées au concert ensemble.", "Hier soir, on est allés au concert ensemble.", "Nous sommes allés au concert ensemble hier soir.", "Nous sommes allées au concert ensemble hier soir.", "Hier soir, nous sommes allés ensemble au concert."], en: ["Yesterday evening we went to the concert together.", "We went to the concert together last night."], de: ["Gestern Abend gingen wir zusammen ins Konzert.", "Wir sind gestern Abend zusammen ins Konzert gegangen."] } },
  ],
  drills: [
    { id: "u19.d1", lesson: 1, fr: "Je ___ voir un film.", options: ["veux", "veut", "voulez"], answer: 0, en: "I want to see a film.", de: "Ich will einen Film sehen.", why: tx("With **je**: je **veux**, with an x. Il veut has a t.", "Mit **je**: je **veux**, mit x. Il veut hat ein t.") },
    { id: "u19.d2", lesson: 1, fr: "Tu veux ___ au restaurant ?", options: ["aller", "vas", "va"], answer: 0, en: "Do you want to go to a restaurant?", de: "Willst du ins Restaurant gehen?", why: tx("After **vouloir**, the next verb is an infinitive: tu veux **aller**.", "Nach **vouloir** steht das nächste Verb im Infinitiv: tu veux **aller**.") },
    { id: "u19.d3", lesson: 1, fr: "Léa ___ un nouveau vélo.", options: ["veut", "veux", "voulons"], answer: 0, en: "Léa wants a new bike.", de: "Léa will ein neues Fahrrad.", why: tx("Léa is elle: elle **veut**, with a t.", "Léa ist elle: elle **veut**, mit t.") },
    { id: "u19.d4", lesson: 2, fr: "Tu ___ venir samedi ?", options: ["peux", "peut", "pouvez"], answer: 0, en: "Can you come on Saturday?", de: "Kannst du am Samstag kommen?", why: tx("With **tu**: tu **peux**, with an x, just like je peux.", "Mit **tu**: tu **peux**, mit x, genau wie je peux.") },
    { id: "u19.d5", lesson: 2, fr: "Désolé, je ne ___ pas.", options: ["peux", "peut"], answer: 0, en: "Sorry, I can't.", de: "Tut mir leid, ich kann nicht.", why: tx("With **je**: je **peux**. Je ne peux pas: I can't.", "Mit **je**: je **peux**. Je ne peux pas: Ich kann nicht.") },
    { id: "u19.d6", lesson: 2, fr: "Hugo ne ___ pas venir, il est malade.", options: ["peut", "peux", "peuvent"], answer: 0, en: "Hugo can't come, he's ill.", de: "Hugo kann nicht kommen, er ist krank.", why: tx("Hugo is il: il **peut**, with a t.", "Hugo ist il: il **peut**, mit t.") },
    { id: "u19.d7", lesson: 3, fr: "Tu ___ à ma fête ?", options: ["viens", "vient", "venez"], answer: 0, en: "Are you coming to my party?", de: "Kommst du zu meiner Party?", why: tx("With **tu**: tu **viens**, with an s.", "Mit **tu**: tu **viens**, mit s.") },
    { id: "u19.d8", lesson: 3, fr: "Il ___ de Lyon.", options: ["vient", "viens", "viennent"], answer: 0, en: "He comes from Lyon.", de: "Er kommt aus Lyon.", why: tx("With **il**: il **vient**, with a t. Venir de: to come from.", "Mit **il**: il **vient**, mit t. Venir de: kommen aus.") },
    { id: "u19.d9", lesson: 3, fr: "Hier, ___ venu à la fête de Léa.", options: ["je suis", "j'ai"], answer: 0, en: "Yesterday I came to Léa's party.", de: "Gestern bin ich zu Léas Party gekommen.", why: tx("Venir takes **être** in the past: **je suis** venu (venue for a girl), never j'ai venu.", "Venir bildet die Vergangenheit mit **être**: **je suis** venu (venue für ein Mädchen), nie j'ai venu.") },
    { id: "u19.d10", lesson: 4, fr: "Vous ___ venir avec nous ?", options: ["voulez", "veux", "voulons"], answer: 0, en: "Do you want to come with us?", de: "Wollt ihr mitkommen?", why: tx("With **vous**: vous **voulez**.", "Mit **vous**: vous **voulez**.") },
    { id: "u19.d11", lesson: 4, fr: "Vous ___ répéter, s'il vous plaît ?", options: ["pouvez", "peux", "pouvons"], answer: 0, en: "Can you repeat that, please?", de: "Können Sie das bitte wiederholen?", why: tx("With **vous**: vous **pouvez**. A very useful question!", "Mit **vous**: vous **pouvez**. Eine sehr nützliche Frage!") },
    { id: "u19.d12", lesson: 5, fr: "Tu es ___ samedi soir ?", options: ["libre", "gratuit"], answer: 0, en: "Are you free on Saturday evening?", de: "Hast du am Samstagabend Zeit?", why: tx("Free, not busy, is **libre**. Gratuit means free of charge.", "Frei, also nicht beschäftigt, heißt **libre**. Gratuit heißt kostenlos.") },
    { id: "u19.d13", lesson: 5, fr: "Oui, ___ plaisir !", options: ["avec", "pour", "de"], answer: 0, en: "Yes, with pleasure!", de: "Ja, gern!", why: tx("It's **avec plaisir**: with pleasure.", "Es heißt **avec plaisir**: mit Vergnügen.") },
    { id: "u19.d14", lesson: 6, fr: "Nous ___ aller à la plage.", options: ["voulons", "veulent", "voulez"], answer: 0, en: "We want to go to the beach.", de: "Wir wollen an den Strand gehen.", why: tx("With **nous**: nous **voulons**.", "Mit **nous**: nous **voulons**.") },
    { id: "u19.d15", lesson: 6, fr: "Ils ne ___ pas venir : ils sont en vacances.", options: ["peuvent", "peut", "pouvons"], answer: 0, en: "They can't come, they're on holiday.", de: "Sie können nicht kommen, sie sind im Urlaub.", why: tx("With **ils**: ils **peuvent**. The vowel changes: il peut, ils peuvent.", "Mit **ils**: ils **peuvent**. Der Vokal ändert sich: il peut, ils peuvent.") },
    { id: "u19.d16", lesson: 6, fr: "Les enfants ___ manger des crêpes.", options: ["veulent", "veut", "voulons"], answer: 0, en: "The children want to eat crêpes.", de: "Die Kinder wollen Crêpes essen.", why: tx("Les enfants is ils: ils **veulent**.", "Les enfants ist ils: ils **veulent**.") },
    { id: "u19.d17", lesson: 7, fr: "Vous ___ avec nous, Madame Martin ?", options: ["venez", "viens", "viennent"], answer: 0, en: "Are you coming with us, Mrs Martin?", de: "Kommen Sie mit, Frau Martin?", why: tx("With **vous**: vous **venez**.", "Mit **vous**: vous **venez**.") },
    { id: "u19.d18", lesson: 7, fr: "Hier soir, nous sommes ___ au concert ensemble.", options: ["allés", "allé"], answer: 0, en: "Last night we went to the concert together.", de: "Gestern Abend sind wir zusammen ins Konzert gegangen.", why: tx("With être, the participle agrees: nous sommes **allés**, with an s for more than one.", "Mit être wird das Partizip angepasst: nous sommes **allés**, mit s bei mehreren.") },
  ],
  dialogues: [
    {
      id: "u19.dialogue",
      lesson: 5,
      title: tx("A concert in the park", "Ein Konzert im Park"),
      lines: [
        { who: "hugo", fr: "Léa, tu es libre samedi soir ?", en: "Léa, are you free on Saturday evening?", de: "Léa, hast du am Samstagabend Zeit?" },
        { who: "lea", fr: "Oui, samedi soir, je suis libre.", en: "Yes, on Saturday evening I'm free.", de: "Ja, am Samstagabend habe ich Zeit." },
        { who: "hugo", fr: "Il y a un concert au parc. Tu veux venir avec moi ?", en: "There's a concert in the park. Do you want to come with me?", de: "Im Park ist ein Konzert. Willst du mitkommen?" },
        { who: "lea", fr: "Oui, avec plaisir ! J'adore les concerts au parc.", en: "Yes, I'd love to! I love concerts in the park.", de: "Ja, gern! Ich liebe Konzerte im Park." },
        { who: "blob", fr: "Un concert ? Moi aussi, je veux venir ! Je peux ?", en: "A concert? I want to come too! Can I?", de: "Ein Konzert? Ich will auch mitkommen! Darf ich?" },
        { who: "hugo", fr: "Bien sûr, Blob ! Rendez-vous à huit heures devant le parc.", en: "Of course, Blob! We'll meet at eight in front of the park.", de: "Klar, Blob! Treffpunkt um acht Uhr vor dem Park." },
        { who: "blob", fr: "D'accord ! Je viens avec ma guitare.", en: "OK! I'm coming with my guitar.", de: "Okay! Ich komme mit meiner Gitarre." },
        { who: "lea", fr: "Ta guitare ? Pourquoi ?", en: "Your guitar? Why?", de: "Deine Gitarre? Warum?" },
        { who: "blob", fr: "Pour le concert, bien sûr ! Je suis un artiste !", en: "For the concert, of course! I'm an artist!", de: "Für das Konzert natürlich! Ich bin ein Künstler!" },
      ],
      questions: [
        { q: tx("When is the concert?", "Wann ist das Konzert?"), options: [tx("On Saturday evening", "Am Samstagabend"), tx("On Sunday morning", "Am Sonntagmorgen"), tx("Tomorrow at noon", "Morgen um zwölf")], answer: 0 },
        { q: tx("Where do they meet?", "Wo treffen sie sich?"), options: [tx("In front of the park at eight", "Um acht vor dem Park"), tx("At the cinema", "Im Kino"), tx("At Léa's house", "Bei Léa zu Hause")], answer: 0 },
        { q: tx("What does Blob bring?", "Was bringt Blob mit?"), options: [tx("His guitar", "Seine Gitarre"), tx("His umbrella", "Seinen Regenschirm"), tx("A cake", "Einen Kuchen")], answer: 0 },
      ],
    },
    {
      id: "u19.dialogue2",
      lesson: 7,
      title: tx("An invitation for the Martins", "Eine Einladung für die Martins"),
      lines: [
        { who: "lea", fr: "Madame Martin, vous voulez venir à notre fête samedi ?", en: "Mrs Martin, would you like to come to our party on Saturday?", de: "Frau Martin, möchten Sie am Samstag zu unserer Party kommen?" },
        { who: "madame", fr: "Votre fête ? Merci, c'est gentil ! Mais je ne peux pas, je dois aller chez ma sœur.", en: "Your party? Thank you, that's kind! But I can't, I have to go to my sister's.", de: "Eure Party? Danke, das ist lieb! Aber ich kann nicht, ich muss zu meiner Schwester." },
        { who: "lea", fr: "Dommage ! Et Monsieur Martin, il peut venir ?", en: "What a pity! And Mr Martin, can he come?", de: "Schade! Und Herr Martin, kann er kommen?" },
        { who: "madame", fr: "Non, il travaille samedi.", en: "No, he's working on Saturday.", de: "Nein, er arbeitet am Samstag." },
        { who: "blob", fr: "Oh non ! Une autre fois, alors ?", en: "Oh no! Another time, then?", de: "Oh nein! Dann ein anderes Mal?" },
        { who: "madame", fr: "Oui, avec plaisir ! Mais la musique, pas trop fort, d'accord ?", en: "Yes, with pleasure! But not too loud with the music, OK?", de: "Ja, gern! Aber die Musik nicht zu laut, okay?" },
        { who: "blob", fr: "Pas de problème ! Nous pouvons danser sans musique !", en: "No problem! We can dance without music!", de: "Kein Problem! Wir können ohne Musik tanzen!" },
        { who: "lea", fr: "Blob… une fête sans musique, ce n'est pas une fête !", en: "Blob… a party without music isn't a party!", de: "Blob … eine Party ohne Musik ist keine Party!" },
      ],
      questions: [
        { q: tx("Why can't Mrs Martin come?", "Warum kann Frau Martin nicht kommen?"), options: [tx("She has to go to her sister's.", "Sie muss zu ihrer Schwester."), tx("She's ill.", "Sie ist krank."), tx("She has to work.", "Sie muss arbeiten.")], answer: 0 },
        { q: tx("What about Mr Martin?", "Und Herr Martin?"), options: [tx("He's working on Saturday.", "Er arbeitet am Samstag."), tx("He's coming at eight.", "Er kommt um acht."), tx("He's on holiday.", "Er ist im Urlaub.")], answer: 0 },
        { q: tx("What does Mrs Martin ask for?", "Worum bittet Frau Martin?"), options: [tx("Music that's not too loud", "Musik, die nicht zu laut ist"), tx("A piece of cake", "Ein Stück Kuchen"), tx("An invitation for her sister", "Eine Einladung für ihre Schwester")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Vouloir: I want", "Vouloir: Ich will"),
      body: tx(
        "**Vouloir** (to want) is irregular. Put an infinitive after it: je **veux voir** un film, tu **veux venir** ?\n\n**Tu veux… ?** is the easy way to invite a friend. To a waiter or a stranger, je voudrais is politer than je veux.",
        "**Vouloir** (wollen) ist unregelmäßig. Danach kommt ein Infinitiv: je **veux voir** un film, tu **veux venir** ?\n\n**Tu veux … ?** ist die einfachste Einladung unter Freunden. Beim Kellner oder bei Fremden ist je voudrais höflicher als je veux.",
      ),
      examples: [
        { fr: "Je veux voir un film.", en: "I want to see a film.", de: "Ich will einen Film sehen." },
        { fr: "Tu veux aller au restaurant ?", en: "Do you want to go to a restaurant?", de: "Willst du ins Restaurant gehen?" },
        { fr: "Ils veulent voir le concert.", en: "They want to see the concert.", de: "Sie wollen das Konzert sehen." },
      ],
      table: {
        head: [tx("person", "Person"), "vouloir"],
        rows: [
          [tx("I", "ich"), "je veux"],
          [tx("you", "du"), "tu veux"],
          [tx("he / she", "er / sie"), "il / elle veut"],
          [tx("we", "wir"), "nous voulons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous voulez"],
          [tx("they", "sie"), "ils / elles veulent"],
        ],
      },
    },
    {
      title: tx("Pouvoir: I can", "Pouvoir: Ich kann"),
      body: tx(
        "**Pouvoir** (can, to be able to) works just like vouloir: same endings, same vowel change. Je **peux** venir ? asks if you may. **Vous pouvez répéter ?** is the question that saves you in any conversation.\n\nThe polite no: **désolé, je ne peux pas** (désolée for a girl).",
        "**Pouvoir** (können, dürfen) funktioniert genau wie vouloir: gleiche Endungen, gleicher Vokalwechsel. Je **peux** venir ? fragt, ob du darfst. **Vous pouvez répéter ?** rettet dich in jedem Gespräch.\n\nDas höfliche Nein: **désolé, je ne peux pas** (désolée für ein Mädchen).",
      ),
      examples: [
        { fr: "Je peux venir avec toi ?", en: "Can I come with you?", de: "Kann ich mit dir kommen?" },
        { fr: "Vous pouvez répéter, s'il vous plaît ?", en: "Can you repeat that, please?", de: "Können Sie das bitte wiederholen?" },
        { fr: "Désolé, je ne peux pas.", en: "Sorry, I can't.", de: "Tut mir leid, ich kann nicht." },
      ],
      table: {
        head: [tx("person", "Person"), "pouvoir"],
        rows: [
          [tx("I", "ich"), "je peux"],
          [tx("you", "du"), "tu peux"],
          [tx("he / she", "er / sie"), "il / elle peut"],
          [tx("we", "wir"), "nous pouvons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous pouvez"],
          [tx("they", "sie"), "ils / elles peuvent"],
        ],
      },
    },
    {
      title: tx("Venir: to come", "Venir: kommen"),
      body: tx(
        "**Venir** is the quickest invitation: **tu viens ?** (are you coming?). With **de** it says where you're from: je viens **de** Lyon.\n\nIn the past, venir takes **être**, like aller: je **suis venu**, Léa **est venue**.",
        "**Venir** ist die schnellste Einladung: **tu viens ?** (kommst du?). Mit **de** sagt es, woher du kommst: je viens **de** Lyon.\n\nIn der Vergangenheit nimmt venir **être**, wie aller: je **suis venu**, Léa **est venue**.",
      ),
      examples: [
        { fr: "Tu viens à ma fête ?", en: "Are you coming to my party?", de: "Kommst du zu meiner Party?" },
        { fr: "Il vient de Lyon.", en: "He comes from Lyon.", de: "Er kommt aus Lyon." },
        { fr: "Hier, je suis venu à la fête de Léa.", en: "Yesterday I came to Léa's party.", de: "Gestern bin ich zu Léas Party gekommen." },
      ],
      table: {
        head: [tx("person", "Person"), "venir"],
        rows: [
          [tx("I", "ich"), "je viens"],
          [tx("you", "du"), "tu viens"],
          [tx("he / she", "er / sie"), "il / elle vient"],
          [tx("we", "wir"), "nous venons"],
          [tx("you (plural / polite)", "ihr / Sie"), "vous venez"],
          [tx("they", "sie"), "ils / elles viennent"],
        ],
      },
    },
    {
      title: tx("Yes and no, politely", "Höflich ja und nein sagen"),
      body: tx(
        "To say yes: **d'accord**, **avec plaisir**, **je veux bien**. Ready to leave? **On y va !**\n\nTo say no kindly, add a reason and a new idea: **désolé, je ne peux pas, je dois travailler. Une autre fois ?** And when a friend can't come: **dommage !**",
        "Ja sagen: **d'accord**, **avec plaisir**, **je veux bien**. Bereit zum Losgehen? **On y va !**\n\nFreundlich nein sagen: mit Grund und neuem Vorschlag: **désolé, je ne peux pas, je dois travailler. Une autre fois ?** Und wenn ein Freund nicht kommen kann: **dommage !**",
      ),
      examples: [
        { fr: "Oui, avec plaisir !", en: "Yes, with pleasure!", de: "Ja, gern!" },
        { fr: "Désolé, je ne peux pas, je dois travailler.", en: "Sorry, I can't, I have to work.", de: "Tut mir leid, ich kann nicht, ich muss arbeiten." },
        { fr: "Une autre fois, peut-être ?", en: "Another time, maybe?", de: "Vielleicht ein anderes Mal?" },
      ],
      table: {
        head: [tx("yes", "ja"), tx("no", "nein")],
        rows: [
          ["d'accord !", "désolé, je ne peux pas"],
          ["avec plaisir !", "une autre fois ?"],
          ["je veux bien", "dommage !"],
        ],
      },
    },
  ],
};
