import { tx } from "@/i18n/text";
import type { Unit } from "../types";

/** Unit 20: comparing (plus … que) and object pronouns (je le prends). */
export const u20: Unit = {
  slug: "comparer",
  n: 20,
  cefr: "A2",
  title: tx("Which one is better?", "Welches ist besser?"),
  goal: tx("Compare things and choose", "Dinge vergleichen und auswählen"),
  emoji: "⚖️",
  words: [
    { id: "plus-que", fr: "plus … que", en: "more … than", de: "mehr … als", alt: { en: ["-er than"], de: ["-er als"] }, kind: "phrase", note: tx("Plus rapide que: faster than. Here the s of plus is silent.", "Plus rapide que: schneller als. Hier ist das s von plus stumm.") },
    { id: "moins-que", fr: "moins … que", en: "less … than", de: "weniger … als", kind: "phrase", note: tx("Moins cher que: cheaper (less expensive) than.", "Moins cher que: billiger (weniger teuer) als.") },
    { id: "rapide", fr: "rapide", en: "fast", de: "schnell", alt: { en: ["quick"] }, kind: "adj", emoji: "⚡", note: tx("The same for boys and girls: rapide.", "Gleich für Jungen und Mädchen: rapide.") },
    { id: "lent", fr: "lent", en: "slow", de: "langsam", kind: "adj", emoji: "🐢", note: tx("Feminine: lente, and then you hear the t.", "Weiblich: lente, und dann hört man das t.") },
    { id: "fort", fr: "fort", en: "strong", de: "stark", alt: { en: ["loud"], de: ["laut"] }, kind: "adj", emoji: "🏋️", note: tx("Feminine: forte. Music can be forte too: loud.", "Weiblich: forte. Musik kann auch forte sein: laut.") },
    { id: "aussi-que", fr: "aussi … que", en: "as … as", de: "so … wie", alt: { de: ["genauso … wie"] }, kind: "phrase", note: tx("Aussi grand que: as tall as. On its own, aussi means also.", "Aussi grand que: so groß wie. Allein heißt aussi auch.") },
    { id: "vieux", fr: "vieux", en: "old", de: "alt", kind: "adj", emoji: "🧓", note: tx("Before the noun: un vieux vélo. Feminine: vieille.", "Steht vor dem Nomen: un vieux vélo. Weiblich: vieille.") },
    { id: "jeune", fr: "jeune", en: "young", de: "jung", kind: "adj", emoji: "🐣", note: tx("The same for boys and girls. Plus jeune que: younger than.", "Gleich für Jungen und Mädchen. Plus jeune que: jünger als.") },
    { id: "beau", fr: "beau", en: "beautiful", de: "schön", alt: { en: ["handsome", "nice", "lovely"] }, kind: "adj", note: tx("Before the noun: un beau pull. Feminine: belle. Plural: beaux, belles.", "Steht vor dem Nomen: un beau pull. Weiblich: belle. Plural: beaux, belles.") },
    { id: "intelligent", fr: "intelligent", en: "clever", de: "klug", alt: { en: ["intelligent", "smart"], de: ["intelligent", "schlau"] }, kind: "adj", emoji: "🧠", note: tx("Feminine: intelligente.", "Weiblich: intelligente.") },
    { id: "meilleur", fr: "meilleur", en: "better", de: "besser", alt: { en: ["best"], de: ["beste"] }, kind: "adj", emoji: "⭐", note: tx("Bon → meilleur, never plus bon. Le meilleur: the best. Feminine: meilleure.", "Bon → meilleur, nie plus bon. Le meilleur: der Beste. Weiblich: meilleure.") },
    { id: "le-plus", fr: "le plus", en: "the most", de: "am meisten", kind: "phrase", note: tx("Le plus rapide: the fastest. La plus belle: the most beautiful.", "Le plus rapide: der Schnellste. La plus belle: die Schönste.") },
    { id: "telephone", fr: "le téléphone", en: "the phone", de: "das Handy", alt: { en: ["the telephone", "the mobile"], de: ["das Telefon"] }, g: "m", kind: "noun", emoji: "📱", note: tx("A mobile is also called un portable.", "Ein Handy heißt auch un portable.") },
    { id: "ordinateur", fr: "l'ordinateur", en: "the computer", de: "der Computer", alt: { en: ["the laptop"], de: ["der Rechner"] }, g: "m", kind: "noun", emoji: "💻", note: tx("Often just «l'ordi».", "Oft einfach „l'ordi“.") },
    { id: "magasin", fr: "le magasin", en: "the shop", de: "das Geschäft", alt: { en: ["the store"], de: ["der Laden"] }, g: "m", kind: "noun", emoji: "🏬", note: tx("Not a magazine: that's un magazine!", "Kein Magazin: Das ist un magazine!") },
    { id: "taille", fr: "la taille", en: "the size", de: "die Größe", g: "f", kind: "noun", emoji: "📏", note: tx("Vous faites quelle taille ? What size are you?", "Vous faites quelle taille ? Welche Größe haben Sie?") },
    { id: "essayer", fr: "essayer", en: "to try on", de: "anprobieren", alt: { en: ["to try", "try on"], de: ["probieren", "versuchen"] }, kind: "verb", note: tx("Clothes, and anything else: to try. J'essaie: I'm trying on.", "Kleider anprobieren, und auch versuchen. J'essaie: Ich probiere an.") },
    { id: "long", fr: "long", en: "long", de: "lang", kind: "adj", note: tx("Feminine: longue. Trop long: too long.", "Weiblich: longue. Trop long: zu lang.") },
    { id: "je-le-prends", fr: "je le prends", en: "I'll take it", de: "ich nehme ihn / es", alt: { de: ["ich nehme ihn", "ich nehme es"] }, kind: "phrase", note: tx("For a masculine thing: le pull → je le prends. Le comes before the verb!", "Für ein männliches Ding: le pull → je le prends. Le steht vor dem Verb!") },
    { id: "je-la-prends", fr: "je la prends", en: "I'll take it (feminine)", de: "ich nehme sie (Singular)", alt: { en: ["I'll take it"], de: ["ich nehme sie", "ich nehme es"] }, kind: "phrase", note: tx("For a feminine thing: la robe → je la prends.", "Für ein weibliches Ding: la robe → je la prends.") },
    { id: "je-les-prends", fr: "je les prends", en: "I'll take them", de: "ich nehme sie (Plural)", alt: { de: ["ich nehme sie"] }, kind: "phrase", note: tx("For more than one: les chaussures → je les prends.", "Für mehrere: les chaussures → je les prends.") },
    { id: "lunettes", fr: "les lunettes", en: "the glasses", de: "die Brille", alt: { en: ["the spectacles"] }, g: "f", kind: "noun", emoji: "👓", note: tx("Always plural: des lunettes. Lunettes de soleil: sunglasses.", "Immer Plural: des lunettes. Lunettes de soleil: Sonnenbrille.") },
    { id: "le-meme", fr: "le même", en: "the same", de: "der gleiche", alt: { de: ["derselbe", "das gleiche", "die gleiche"] }, kind: "phrase", note: tx("Feminine: la même. Le même sac que toi: the same bag as you.", "Weiblich: la même. Le même sac que toi: die gleiche Tasche wie du.") },
    { id: "different", fr: "différent", en: "different", de: "verschieden", alt: { de: ["anders", "unterschiedlich"] }, kind: "adj", note: tx("Feminine: différente.", "Weiblich: différente.") },
    { id: "paire", fr: "la paire", en: "the pair", de: "das Paar", g: "f", kind: "noun", note: tx("Une paire de chaussures: a pair of shoes.", "Une paire de chaussures: ein Paar Schuhe.") },
    { id: "mieux", fr: "mieux", en: "better (with verbs)", de: "besser (bei Verben)", alt: { en: ["better"], de: ["besser"] }, kind: "adv", note: tx("Bien → mieux, with verbs: elle chante mieux. Bon → meilleur, with nouns: un meilleur gâteau.", "Bien → mieux, bei Verben: elle chante mieux. Bon → meilleur, bei Nomen: un meilleur gâteau.") },
    { id: "le-moins", fr: "le moins", en: "the least", de: "am wenigsten", kind: "phrase", note: tx("Le moins cher: the cheapest, literally the least expensive.", "Le moins cher: der Billigste, wörtlich der am wenigsten teure.") },
  ],
  gloss: [
    { fr: "plus rapide", en: "faster", de: "schneller" },
    { fr: "plus rapide que", en: "faster than", de: "schneller als" },
    { fr: "moins rapide que", en: "slower than", de: "langsamer als" },
    { fr: "plus grand que", en: "taller than / bigger than", de: "größer als" },
    { fr: "plus fort que", en: "stronger than", de: "stärker als" },
    { fr: "plus forte que", en: "stronger than", de: "stärker als" },
    { fr: "moins chères que", en: "cheaper than", de: "billiger als" },
    { fr: "moins cher", en: "cheaper", de: "billiger" },
    { fr: "le moins cher", en: "the cheapest", de: "der / das billigste" },
    { fr: "aussi grande que", en: "as tall as", de: "so groß wie" },
    { fr: "aussi intelligent que", en: "as clever as", de: "so klug wie" },
    { fr: "plus jeune que", en: "younger than", de: "jünger als" },
    { fr: "plus petite", en: "smaller", de: "kleiner" },
    { fr: "plus beau que", en: "more beautiful than", de: "schöner als" },
    { fr: "le plus beau", en: "the most beautiful", de: "der / das schönste" },
    { fr: "le plus cher", en: "the most expensive", de: "der / das teuerste" },
    { fr: "belle", en: "beautiful (feminine)", de: "schön" },
    { fr: "meilleure", en: "better / best (feminine)", de: "besser / beste" },
    { fr: "meilleure amie", en: "best friend (girl)", de: "beste Freundin" },
    { fr: "meilleure que", en: "better than", de: "besser als" },
    { fr: "que moi", en: "than me / as me", de: "als ich / wie ich" },
    { fr: "que toi", en: "than you / as you", de: "als du / wie du" },
    { fr: "qu'un", en: "than a", de: "als ein" },
    { fr: "le meilleur", en: "the best", de: "der / das beste" },
    { fr: "la meilleure", en: "the best (feminine)", de: "die beste" },
    { fr: "ancien", en: "old / former", de: "alt / früher" },
    { fr: "fermé", en: "closed", de: "geschlossen" },
    { fr: "longue", en: "long (feminine)", de: "lang" },
    { fr: "essaie", en: "try / tries (on)", de: "probiere / probiert (an)" },
    { fr: "j'essaie", en: "I'm trying on", de: "ich probiere an" },
    { fr: "essayé", en: "tried (on)", de: "anprobiert" },
    { fr: "j'ai essayé", en: "I tried on / I have tried on", de: "ich habe anprobiert" },
    { fr: "pantalons", en: "pairs of trousers", de: "Hosen" },
    { fr: "différentes", en: "different (feminine plural)", de: "verschieden" },
    { fr: "différents", en: "different (plural)", de: "verschieden" },
    { fr: "la même", en: "the same (feminine)", de: "die gleiche / dieselbe" },
    { fr: "âge", en: "age", de: "Alter" },
    { fr: "chante", en: "sings", de: "singt" },
    { fr: "comme ça", en: "like that", de: "so" },
    { fr: "quel", en: "which / what", de: "welcher / was für" },
    { fr: "aider", en: "to help", de: "helfen" },
    { fr: "trente-huit", en: "thirty-eight", de: "achtunddreißig" },
    { fr: "gagne", en: "wins", de: "gewinnt" },
    { fr: "partez", en: "go! (at the start of a race)", de: "los!" },
    { fr: "est-il", en: "is he / is it", de: "ist er / ist es" },
    { fr: "course", en: "race", de: "Wettrennen" },
    { fr: "cabine", en: "changing room", de: "Umkleidekabine" },
    { fr: "noires", en: "black (feminine plural)", de: "schwarz" },
    { fr: "robes", en: "dresses", de: "Kleider" },
  ],
  lessons: [
    { title: tx("Faster, slower", "Schneller, langsamer"), words: ["plus-que", "moins-que", "rapide", "lent", "fort"] },
    { title: tx("As old as…", "So alt wie …"), words: ["aussi-que", "vieux", "jeune", "beau", "intelligent"] },
    { title: tx("The best", "Der Beste"), words: ["meilleur", "le-plus", "telephone", "ordinateur"] },
    { title: tx("In the shop", "Im Geschäft"), words: ["magasin", "taille", "essayer", "long"] },
    { title: tx("I'll take it!", "Ich nehme es!"), words: ["je-le-prends", "je-la-prends", "je-les-prends", "lunettes"] },
    { title: tx("The same or different?", "Gleich oder anders?"), words: ["le-meme", "different", "paire"] },
    { title: tx("Better and cheapest", "Besser und am billigsten"), words: ["mieux", "le-moins"] },
  ],
  sentences: [
    // Lesson 1
    { id: "u20.01", lesson: 1, fr: "Le train est plus rapide que le bus.", en: "The train is faster than the bus.", de: "Der Zug ist schneller als der Bus.", alt: { en: ["The train is quicker than the bus."] } },
    { id: "u20.02", lesson: 1, fr: "Hugo est plus grand que Léa.", en: "Hugo is taller than Léa.", de: "Hugo ist größer als Léa.", alt: { en: ["Hugo is bigger than Léa."] } },
    { id: "u20.03", lesson: 1, fr: "Le vélo est moins rapide que la voiture.", en: "The bike is slower than the car.", de: "Das Fahrrad ist langsamer als das Auto.", alt: { fr: ["Le vélo est plus lent que la voiture."], en: ["The bike is less fast than the car.", "The bicycle is slower than the car.", "The bike isn't as fast as the car."], de: ["Das Fahrrad ist weniger schnell als das Auto.", "Das Rad ist langsamer als das Auto.", "Das Fahrrad ist nicht so schnell wie das Auto."] } },
    { id: "u20.04", lesson: 1, fr: "Le matin, Blob est très lent.", en: "In the morning Blob is very slow.", de: "Morgens ist Blob sehr langsam.", alt: { fr: ["Blob est très lent le matin."], en: ["Blob is very slow in the morning.", "In the mornings Blob is very slow.", "Blob is very slow in the mornings."], de: ["Am Morgen ist Blob sehr langsam.", "Blob ist morgens sehr langsam."] } },
    { id: "u20.05", lesson: 1, fr: "Papa est plus fort que moi.", en: "Dad is stronger than me.", de: "Papa ist stärker als ich.", alt: { en: ["Dad is stronger than I am."] } },
    { id: "u20.06", lesson: 1, fr: "Les pommes sont moins chères que les fraises.", en: "Apples are cheaper than strawberries.", de: "Äpfel sind billiger als Erdbeeren.", alt: { en: ["The apples are cheaper than the strawberries.", "Apples are less expensive than strawberries.", "The apples are less expensive than the strawberries."], de: ["Die Äpfel sind billiger als die Erdbeeren.", "Äpfel sind günstiger als Erdbeeren.", "Die Äpfel sind günstiger als die Erdbeeren.", "Äpfel sind weniger teuer als Erdbeeren."] } },
    { id: "u20.07", lesson: 1, fr: "Ma sœur est plus forte que mon frère.", en: "My sister is stronger than my brother.", de: "Meine Schwester ist stärker als mein Bruder." },
    // Lesson 2
    { id: "u20.08", lesson: 2, fr: "Chloé est aussi grande que Léa.", en: "Chloé is as tall as Léa.", de: "Chloé ist so groß wie Léa.", alt: { en: ["Chloé is as big as Léa."], de: ["Chloé ist genauso groß wie Léa.", "Chloé ist ebenso groß wie Léa."] } },
    { id: "u20.09", lesson: 2, fr: "Mon grand-père est très vieux.", en: "My grandfather is very old.", de: "Mein Großvater ist sehr alt.", alt: { en: ["My grandad is very old.", "My granddad is very old."], de: ["Mein Opa ist sehr alt."] } },
    { id: "u20.10", lesson: 2, fr: "Ma sœur est plus jeune que moi.", en: "My sister is younger than me.", de: "Meine Schwester ist jünger als ich.", alt: { en: ["My sister is younger than I am."] } },
    { id: "u20.11", lesson: 2, fr: "Paris est une très belle ville.", en: "Paris is a very beautiful city.", de: "Paris ist eine sehr schöne Stadt.", alt: { en: ["Paris is a very beautiful town.", "Paris is a very pretty city.", "Paris is a very nice city.", "Paris is a very lovely city."] } },
    { id: "u20.12", lesson: 2, fr: "Le chat est aussi intelligent que le chien.", en: "The cat is as clever as the dog.", de: "Die Katze ist so klug wie der Hund.", alt: { en: ["The cat is as intelligent as the dog.", "The cat is as smart as the dog."], de: ["Die Katze ist genauso klug wie der Hund.", "Die Katze ist so intelligent wie der Hund.", "Die Katze ist genauso intelligent wie der Hund.", "Der Kater ist so klug wie der Hund."] } },
    { id: "u20.13", lesson: 2, fr: "Ce vieux vélo n'est pas rapide.", en: "This old bike isn't fast.", de: "Dieses alte Fahrrad ist nicht schnell.", alt: { en: ["This old bicycle isn't fast.", "That old bike isn't fast."], de: ["Das alte Fahrrad ist nicht schnell.", "Dieses alte Rad ist nicht schnell."] } },
    { id: "u20.14", lesson: 2, fr: "Il est beau, ton nouveau pull !", en: "Your new jumper is lovely!", de: "Dein neuer Pullover ist schön!", alt: { fr: ["Ton nouveau pull est beau !", "Il est beau, votre nouveau pull !", "Votre nouveau pull est beau !"], en: ["Your new jumper is nice!", "Your new jumper is beautiful!", "Your new sweater is lovely!", "It's lovely, your new jumper!"], de: ["Dein neuer Pulli ist schön!", "Der ist schön, dein neuer Pullover!"] } },
    // Lesson 3
    { id: "u20.15", lesson: 3, fr: "Ta pizza est meilleure que la pizza de Blob !", en: "Your pizza is better than Blob's pizza!", de: "Deine Pizza ist besser als Blobs Pizza!", alt: { fr: ["Votre pizza est meilleure que la pizza de Blob !", "Ta pizza est meilleure que celle de Blob !", "Votre pizza est meilleure que celle de Blob !"], en: ["Your pizza is better than Blob's!"], de: ["Deine Pizza ist besser als die Pizza von Blob!", "Deine Pizza ist besser als die von Blob!", "Deine Pizza ist besser als Blobs!"] } },
    { id: "u20.16", lesson: 3, fr: "Léa est ma meilleure amie.", en: "Léa is my best friend.", de: "Léa ist meine beste Freundin." },
    { id: "u20.17", lesson: 3, fr: "C'est le meilleur restaurant de la ville.", en: "It's the best restaurant in town.", de: "Das ist das beste Restaurant der Stadt.", alt: { en: ["It's the best restaurant in the town.", "This is the best restaurant in town.", "It's the best restaurant in the city."], de: ["Es ist das beste Restaurant der Stadt.", "Das ist das beste Restaurant in der Stadt."] } },
    { id: "u20.18", lesson: 3, fr: "Mon ordinateur est très lent.", en: "My computer is very slow.", de: "Mein Computer ist sehr langsam.", alt: { en: ["My laptop is very slow."], de: ["Mein Rechner ist sehr langsam."] } },
    { id: "u20.19", lesson: 3, fr: "C'est le téléphone le plus cher.", en: "It's the most expensive phone.", de: "Das ist das teuerste Handy.", alt: { en: ["It's the most expensive telephone.", "This is the most expensive phone.", "That's the most expensive phone."], de: ["Das ist das teuerste Telefon.", "Es ist das teuerste Handy."] } },
    { id: "u20.20", lesson: 3, fr: "Blob est le plus drôle de la classe.", en: "Blob is the funniest in the class.", de: "Blob ist der Lustigste in der Klasse.", alt: { en: ["Blob is the funniest in class.", "Blob is the funniest one in the class."], de: ["Blob ist der Witzigste in der Klasse.", "Blob ist der Lustigste der Klasse."] } },
    { id: "u20.21", lesson: 3, fr: "Mon nouveau téléphone est plus rapide que l'ancien.", en: "My new phone is faster than the old one.", de: "Mein neues Handy ist schneller als das alte.", alt: { en: ["My new phone is quicker than the old one."], de: ["Mein neues Telefon ist schneller als das alte."] } },
    // Lesson 4
    { id: "u20.22", lesson: 4, fr: "Je peux essayer ce pantalon ?", en: "Can I try on these trousers?", de: "Kann ich diese Hose anprobieren?", alt: { fr: ["Est-ce que je peux essayer ce pantalon ?", "Puis-je essayer ce pantalon ?"], en: ["Can I try these trousers on?", "May I try on these trousers?", "Can I try on this pair of trousers?"], de: ["Darf ich diese Hose anprobieren?", "Kann ich die Hose anprobieren?"] } },
    { id: "u20.23", lesson: 4, fr: "Vous faites quelle taille ?", en: "What size are you?", de: "Welche Größe haben Sie?", alt: { fr: ["Quelle taille faites-vous ?", "Tu fais quelle taille ?", "Quelle taille fais-tu ?"], en: ["What size do you take?", "What's your size?", "What size do you wear?"], de: ["Welche Größe hast du?", "Welche Größe tragen Sie?", "Was für eine Größe haben Sie?"] } },
    { id: "u20.24", lesson: 4, fr: "Le magasin est fermé le dimanche.", en: "The shop is closed on Sundays.", de: "Das Geschäft ist sonntags geschlossen.", alt: { fr: ["Le dimanche, le magasin est fermé."], en: ["The shop is closed on Sunday.", "The store is closed on Sundays."], de: ["Der Laden ist sonntags geschlossen.", "Das Geschäft ist am Sonntag geschlossen."] } },
    { id: "u20.25", lesson: 4, fr: "Cette jupe est trop longue.", en: "This skirt is too long.", de: "Dieser Rock ist zu lang.", alt: { en: ["That skirt is too long."], de: ["Der Rock ist zu lang."] } },
    { id: "u20.26", lesson: 4, fr: "J'essaie la robe bleue.", en: "I'm trying on the blue dress.", de: "Ich probiere das blaue Kleid an.", alt: { fr: ["J'essaye la robe bleue."], en: ["I try on the blue dress.", "I'm trying the blue dress on."] } },
    { id: "u20.27", lesson: 4, fr: "Il y a un nouveau magasin à côté de la gare.", en: "There's a new shop next to the station.", de: "Neben dem Bahnhof gibt es einen neuen Laden.", alt: { en: ["There's a new store next to the station.", "There's a new shop beside the station."], de: ["Es gibt einen neuen Laden neben dem Bahnhof.", "Neben dem Bahnhof gibt es ein neues Geschäft.", "Es gibt ein neues Geschäft neben dem Bahnhof."] } },
    { id: "u20.28", lesson: 4, fr: "Ce pantalon est trop long, vous avez une autre taille ?", en: "These trousers are too long, do you have another size?", de: "Diese Hose ist zu lang, haben Sie eine andere Größe?", alt: { fr: ["Ce pantalon est trop long, est-ce que vous avez une autre taille ?", "Ce pantalon est trop long, avez-vous une autre taille ?", "Ce pantalon est trop long, tu as une autre taille ?"], en: ["These trousers are too long, have you got another size?", "These trousers are too long, do you have a different size?", "These trousers are too long, have you got a different size?"], de: ["Die Hose ist zu lang, haben Sie eine andere Größe?", "Diese Hose ist zu lang, habt ihr eine andere Größe?"] } },
    // Lesson 5
    { id: "u20.29", lesson: 5, fr: "Ce pull est beau. Je le prends !", en: "This jumper is nice. I'll take it!", de: "Dieser Pullover ist schön. Ich nehme ihn!", alt: { fr: ["Il est beau, ce pull. Je le prends !"], en: ["This jumper is lovely. I'll take it!", "This jumper is beautiful. I'll take it!", "This sweater is nice. I'll take it!"], de: ["Dieser Pulli ist schön. Ich nehme ihn!", "Der Pullover ist schön. Ich nehme ihn!"] } },
    { id: "u20.30", lesson: 5, fr: "Cette robe ? Je la prends.", en: "This dress? I'll take it.", de: "Dieses Kleid? Ich nehme es.", alt: { en: ["That dress? I'll take it."], de: ["Das Kleid? Ich nehme es."] } },
    { id: "u20.31", lesson: 5, fr: "Les chaussures noires ? Je les prends.", en: "The black shoes? I'll take them.", de: "Die schwarzen Schuhe? Ich nehme sie." },
    { id: "u20.32", lesson: 5, fr: "Tu aimes mes lunettes ?", en: "Do you like my glasses?", de: "Magst du meine Brille?", alt: { fr: ["Est-ce que tu aimes mes lunettes ?", "Vous aimez mes lunettes ?", "Est-ce que vous aimez mes lunettes ?"], de: ["Gefällt dir meine Brille?"] } },
    { id: "u20.33", lesson: 5, fr: "Ces lunettes sont trop chères, je ne les prends pas.", en: "These glasses are too expensive, I won't take them.", de: "Diese Brille ist zu teuer, ich nehme sie nicht.", alt: { en: ["These glasses are too expensive, I'm not taking them.", "These glasses are too expensive, I'm not going to take them."], de: ["Die Brille ist zu teuer, ich nehme sie nicht."] } },
    { id: "u20.34", lesson: 5, fr: "Le pantalon ? Je peux l'essayer ?", en: "The trousers? Can I try them on?", de: "Die Hose? Kann ich sie anprobieren?", alt: { fr: ["Le pantalon ? Est-ce que je peux l'essayer ?"], en: ["The trousers? May I try them on?"], de: ["Die Hose? Darf ich sie anprobieren?"] } },
    { id: "u20.35", lesson: 5, fr: "Tu prends le rouge ou le bleu ?", en: "Are you taking the red one or the blue one?", de: "Nimmst du den roten oder den blauen?", alt: { fr: ["Est-ce que tu prends le rouge ou le bleu ?", "Vous prenez le rouge ou le bleu ?"], en: ["Will you take the red one or the blue one?", "Are you having the red one or the blue one?"], de: ["Nimmst du das rote oder das blaue?", "Nimmst du die rote oder die blaue?"] } },
    // Lesson 6
    { id: "u20.36", lesson: 6, fr: "J'ai le même sac que toi !", en: "I've got the same bag as you!", de: "Ich habe die gleiche Tasche wie du!", alt: { fr: ["J'ai le même sac que vous !"], en: ["I have the same bag as you!"], de: ["Ich habe dieselbe Tasche wie du!"] } },
    { id: "u20.37", lesson: 6, fr: "Ces deux robes sont différentes.", en: "These two dresses are different.", de: "Diese zwei Kleider sind verschieden.", alt: { en: ["These 2 dresses are different.", "The two dresses are different."], de: ["Diese beiden Kleider sind unterschiedlich.", "Die zwei Kleider sind verschieden.", "Diese beiden Kleider sind verschieden."] } },
    { id: "u20.38", lesson: 6, fr: "Je voudrais une paire de chaussures.", en: "I'd like a pair of shoes.", de: "Ich hätte gern ein Paar Schuhe.", alt: { de: ["Ich möchte ein Paar Schuhe.", "Ich hätte gerne ein Paar Schuhe."] } },
    { id: "u20.39", lesson: 6, fr: "Hugo et Léa ont le même âge.", en: "Hugo and Léa are the same age.", de: "Hugo und Léa sind gleich alt.", alt: { de: ["Hugo und Léa sind im selben Alter.", "Hugo und Léa haben das gleiche Alter."] } },
    { id: "u20.40", lesson: 6, fr: "Hier, j'ai essayé trois pantalons.", en: "Yesterday I tried on three pairs of trousers.", de: "Gestern habe ich drei Hosen anprobiert.", alt: { fr: ["J'ai essayé trois pantalons hier."], en: ["I tried on three pairs of trousers yesterday.", "Yesterday I tried on 3 pairs of trousers."], de: ["Ich habe gestern drei Hosen anprobiert.", "Gestern habe ich 3 Hosen anprobiert."] } },
    { id: "u20.41", lesson: 6, fr: "Ce n'est pas la même taille.", en: "It's not the same size.", de: "Das ist nicht die gleiche Größe.", alt: { en: ["That's not the same size."], de: ["Das ist nicht dieselbe Größe.", "Es ist nicht die gleiche Größe."] } },
    { id: "u20.42", lesson: 6, fr: "Mon frère et moi, nous sommes très différents.", en: "My brother and I are very different.", de: "Mein Bruder und ich sind sehr verschieden.", alt: { fr: ["Mon frère et moi sommes très différents."], de: ["Mein Bruder und ich sind sehr unterschiedlich."] } },
    { id: "u20.43", lesson: 6, fr: "Une paire de chaussettes coûte cinq euros.", en: "A pair of socks costs five euros.", de: "Ein Paar Socken kostet fünf Euro.", alt: { en: ["A pair of socks costs 5 euros.", "A pair of socks is five euros."], de: ["Ein Paar Socken kostet 5 Euro."] } },
    // Lesson 7
    { id: "u20.44", lesson: 7, fr: "Je vais acheter le téléphone le moins cher.", en: "I'm going to buy the cheapest phone.", de: "Ich werde das billigste Handy kaufen.", alt: { en: ["I will buy the cheapest phone.", "I'm going to buy the least expensive phone.", "I'm going to buy the cheapest telephone."], de: ["Ich kaufe das billigste Handy.", "Ich werde das günstigste Handy kaufen.", "Ich kaufe das günstigste Handy."] } },
    { id: "u20.45", lesson: 7, fr: "Léa chante mieux que moi.", en: "Léa sings better than me.", de: "Léa singt besser als ich.", alt: { en: ["Léa sings better than I do."] } },
    { id: "u20.46", lesson: 7, fr: "C'est mieux comme ça !", en: "It's better like that!", de: "So ist es besser!", alt: { fr: ["Comme ça, c'est mieux !"], en: ["It's better this way!", "That's better like that!"], de: ["Das ist so besser!", "So ist's besser!"] } },
    { id: "u20.47", lesson: 7, fr: "Le bus est le moins rapide.", en: "The bus is the slowest.", de: "Der Bus ist am langsamsten.", alt: { fr: ["Le bus est le plus lent."], en: ["The bus is the least fast."], de: ["Der Bus ist der langsamste."] } },
    { id: "u20.48", lesson: 7, fr: "Tu parles mieux français que moi !", en: "You speak French better than me!", de: "Du sprichst besser Französisch als ich!", alt: { fr: ["Tu parles français mieux que moi !", "Vous parlez mieux français que moi !", "Vous parlez français mieux que moi !"], en: ["You speak French better than I do!"], de: ["Du sprichst Französisch besser als ich!"] } },
    { id: "u20.49", lesson: 7, fr: "À vélo, c'est mieux !", en: "It's better by bike!", de: "Mit dem Fahrrad ist es besser!", alt: { fr: ["C'est mieux à vélo !"], en: ["By bike it's better!", "It's better on a bike!"], de: ["Mit dem Rad ist es besser!", "Mit dem Fahrrad ist's besser!"] } },
    { id: "u20.50", lesson: 7, fr: "Quel pantalon est le moins cher ?", en: "Which trousers are the cheapest?", de: "Welche Hose ist die billigste?", alt: { en: ["Which pair of trousers is the cheapest?", "Which trousers are cheapest?"], de: ["Welche Hose ist am billigsten?", "Welche Hose ist die günstigste?", "Welche Hose ist am günstigsten?"] } },
    { id: "u20.51", lesson: 7, fr: "Hier, Hugo est allé au magasin avec Chloé.", en: "Yesterday Hugo went to the shop with Chloé.", de: "Gestern ist Hugo mit Chloé in den Laden gegangen.", alt: { fr: ["Hugo est allé au magasin avec Chloé hier."], en: ["Hugo went to the shop with Chloé yesterday.", "Yesterday Hugo went to the store with Chloé."], de: ["Gestern ging Hugo mit Chloé in den Laden.", "Hugo ist gestern mit Chloé in den Laden gegangen.", "Gestern ist Hugo mit Chloé ins Geschäft gegangen."] } },
  ],
  drills: [
    { id: "u20.d1", lesson: 1, fr: "Le train est ___ rapide que le bus.", options: ["plus", "très", "beaucoup"], answer: 0, en: "The train is faster than the bus.", de: "Der Zug ist schneller als der Bus.", why: tx("To compare: **plus** + adjective + **que**. Plus rapide que: faster than.", "Zum Vergleichen: **plus** + Adjektiv + **que**. Plus rapide que: schneller als.") },
    { id: "u20.d2", lesson: 1, fr: "Hugo est plus grand ___ Léa.", options: ["que", "comme", "de"], answer: 0, en: "Hugo is taller than Léa.", de: "Hugo ist größer als Léa.", why: tx("Than is **que**: plus grand **que** Léa. Comme means like.", "Als heißt **que**: plus grand **que** Léa. Comme heißt wie.") },
    { id: "u20.d3", lesson: 1, fr: "Ma sœur est plus ___ que mon frère.", options: ["forte", "fort"], answer: 0, en: "My sister is stronger than my brother.", de: "Meine Schwester ist stärker als mein Bruder.", why: tx("The adjective agrees with ma sœur: plus **forte**, with an e.", "Das Adjektiv passt sich an ma sœur an: plus **forte**, mit e.") },
    { id: "u20.d4", lesson: 2, fr: "Chloé est aussi ___ que Léa.", options: ["grande", "grand"], answer: 0, en: "Chloé is as tall as Léa.", de: "Chloé ist so groß wie Léa.", why: tx("Chloé is a girl: aussi **grande** que Léa.", "Chloé ist ein Mädchen: aussi **grande** que Léa.") },
    { id: "u20.d5", lesson: 2, fr: "Paris est une très ___ ville.", options: ["belle", "beau"], answer: 0, en: "Paris is a very beautiful city.", de: "Paris ist eine sehr schöne Stadt.", why: tx("Ville is feminine: **belle**. Beau changes a lot: beau, belle, beaux, belles.", "Ville ist weiblich: **belle**. Beau ändert sich stark: beau, belle, beaux, belles.") },
    { id: "u20.d6", lesson: 3, fr: "Léa est ma ___ amie.", options: ["meilleure", "meilleur", "plus bonne"], answer: 0, en: "Léa is my best friend.", de: "Léa ist meine beste Freundin.", why: tx("Better or best is **meilleur**, never plus bon. Amie is feminine: **meilleure**.", "Besser oder beste heißt **meilleur**, nie plus bon. Amie ist weiblich: **meilleure**.") },
    { id: "u20.d7", lesson: 3, fr: "C'est le ___ restaurant de la ville.", options: ["meilleur", "plus bon"], answer: 0, en: "It's the best restaurant in town.", de: "Das ist das beste Restaurant der Stadt.", why: tx("**Meilleur** replaces plus bon: le **meilleur** restaurant.", "**Meilleur** ersetzt plus bon: le **meilleur** restaurant.") },
    { id: "u20.d8", lesson: 3, fr: "Blob est ___ plus drôle de la classe.", options: ["le", "très", "plus"], answer: 0, en: "Blob is the funniest in the class.", de: "Blob ist der Lustigste in der Klasse.", why: tx("The most: **le plus** + adjective: **le** plus drôle.", "Am meisten: **le plus** + Adjektiv: **le** plus drôle.") },
    { id: "u20.d9", lesson: 4, fr: "Je peux ___ ce pantalon ?", options: ["essayer", "essaie", "essayé"], answer: 0, en: "Can I try on these trousers?", de: "Kann ich diese Hose anprobieren?", why: tx("After pouvoir comes the infinitive, with -er: je peux **essayer**.", "Nach pouvoir kommt der Infinitiv, mit -er: je peux **essayer**.") },
    { id: "u20.d10", lesson: 4, fr: "Cette jupe est trop ___.", options: ["longue", "long"], answer: 0, en: "This skirt is too long.", de: "Dieser Rock ist zu lang.", why: tx("Jupe is feminine: **longue**, with -gue.", "Jupe ist weiblich: **longue**, mit -gue.") },
    { id: "u20.d11", lesson: 5, fr: "Cette robe ? Je ___ prends.", options: ["la", "le", "les"], answer: 0, en: "This dress? I'll take it.", de: "Dieses Kleid? Ich nehme es.", why: tx("Robe is feminine: je **la** prends. The little word goes before the verb.", "Robe ist weiblich: je **la** prends. Das kleine Wort steht vor dem Verb.") },
    { id: "u20.d12", lesson: 5, fr: "Les chaussures noires ? Je ___ prends.", options: ["les", "le", "la"], answer: 0, en: "The black shoes? I'll take them.", de: "Die schwarzen Schuhe? Ich nehme sie.", why: tx("Chaussures is plural: je **les** prends.", "Chaussures ist Plural: je **les** prends.") },
    { id: "u20.d13", lesson: 5, fr: "Ces lunettes sont trop chères, je ___ prends pas.", options: ["ne les", "les ne"], answer: 0, en: "These glasses are too expensive, I won't take them.", de: "Diese Brille ist zu teuer, ich nehme sie nicht.", why: tx("In the negative, ne comes first, then the little word: je **ne les** prends pas.", "In der Verneinung kommt zuerst ne, dann das kleine Wort: je **ne les** prends pas.") },
    { id: "u20.d14", lesson: 6, fr: "J'ai le ___ sac que toi !", options: ["même", "mêmes"], answer: 0, en: "I've got the same bag as you!", de: "Ich habe die gleiche Tasche wie du!", why: tx("Sac is singular: le **même** sac. Plural: les mêmes.", "Sac ist Singular: le **même** sac. Plural: les mêmes.") },
    { id: "u20.d15", lesson: 6, fr: "Ces deux robes sont ___.", options: ["différentes", "différents"], answer: 0, en: "These two dresses are different.", de: "Diese zwei Kleider sind verschieden.", why: tx("Robes is feminine and plural: **différentes**.", "Robes ist weiblich und Plural: **différentes**.") },
    { id: "u20.d16", lesson: 6, fr: "Hier, ___ essayé trois pantalons.", options: ["j'ai", "je suis"], answer: 0, en: "Yesterday I tried on three pairs of trousers.", de: "Gestern habe ich drei Hosen anprobiert.", why: tx("Essayer takes **avoir** in the past: **j'ai** essayé. Only verbs like aller and venir take être.", "Essayer bildet die Vergangenheit mit **avoir**: **j'ai** essayé. Nur Verben wie aller und venir nehmen être.") },
    { id: "u20.d17", lesson: 7, fr: "Léa chante ___ que moi.", options: ["mieux", "meilleur"], answer: 0, en: "Léa sings better than me.", de: "Léa singt besser als ich.", why: tx("With a verb (chanter), better is **mieux**. Meilleur goes with a noun: un meilleur gâteau.", "Bei einem Verb (chanter) heißt besser **mieux**. Meilleur gehört zu einem Nomen: un meilleur gâteau.") },
    { id: "u20.d18", lesson: 7, fr: "Je vais acheter le téléphone le ___ cher.", options: ["moins", "mieux"], answer: 0, en: "I'm going to buy the cheapest phone.", de: "Ich werde das billigste Handy kaufen.", why: tx("The cheapest is the least expensive: le **moins** cher.", "Das billigste ist das am wenigsten teure: le **moins** cher.") },
  ],
  dialogues: [
    {
      id: "u20.dialogue",
      lesson: 5,
      title: tx("Chloé goes shopping", "Chloé geht einkaufen"),
      lines: [
        { who: "chloe", fr: "Bonjour, Monsieur. Je voudrais essayer ce pantalon, s'il vous plaît.", en: "Hello. I'd like to try on these trousers, please.", de: "Guten Tag. Ich möchte bitte diese Hose anprobieren." },
        { who: "vendeur", fr: "Bien sûr. Vous faites quelle taille ?", en: "Of course. What size are you?", de: "Natürlich. Welche Größe haben Sie?" },
        { who: "chloe", fr: "Je fais du trente-huit.", en: "I'm a thirty-eight.", de: "Ich habe achtunddreißig." },
        { who: "vendeur", fr: "Voilà. La cabine est à droite.", en: "Here you are. The changing room is on the right.", de: "Bitte schön. Die Kabine ist rechts." },
        { who: "chloe", fr: "Oh non, il est trop long ! Vous avez une taille plus petite ?", en: "Oh no, they're too long! Do you have a smaller size?", de: "Oh nein, die ist zu lang! Haben Sie eine kleinere Größe?" },
        { who: "vendeur", fr: "Oui, voilà. Et il est moins cher : trente euros.", en: "Yes, here you are. And they're cheaper: thirty euros.", de: "Ja, bitte schön. Und die ist billiger: dreißig Euro." },
        { who: "blob", fr: "Et ce béret rouge ? Il est plus beau que mon béret ?", en: "And this red beret? Is it more beautiful than my beret?", de: "Und diese rote Baskenmütze? Ist sie schöner als meine?" },
        { who: "chloe", fr: "Non, Blob, ton béret est le plus beau !", en: "No, Blob, your beret is the most beautiful!", de: "Nein, Blob, deine Baskenmütze ist die schönste!" },
        { who: "blob", fr: "D'accord. Alors, je ne le prends pas !", en: "OK. Then I won't take it!", de: "Okay. Dann nehme ich sie nicht!" },
      ],
      questions: [
        { q: tx("What does Chloé try on?", "Was probiert Chloé an?"), options: [tx("Trousers", "Eine Hose"), tx("A dress", "Ein Kleid"), tx("A beret", "Eine Baskenmütze")], answer: 0 },
        { q: tx("What's wrong with the first trousers?", "Was stimmt mit der ersten Hose nicht?"), options: [tx("They're too long.", "Sie ist zu lang."), tx("They're too expensive.", "Sie ist zu teuer."), tx("They're too small.", "Sie ist zu klein.")], answer: 0 },
        { q: tx("Why doesn't Blob take the red beret?", "Warum nimmt Blob die rote Baskenmütze nicht?"), options: [tx("His own beret is the most beautiful.", "Seine eigene ist die schönste."), tx("It's too expensive.", "Sie ist zu teuer."), tx("It's too small.", "Sie ist zu klein.")], answer: 0 },
      ],
    },
    {
      id: "u20.dialogue2",
      lesson: 7,
      title: tx("Who's the fastest?", "Wer ist am schnellsten?"),
      lines: [
        { who: "hugo", fr: "Blob, tu es rapide ?", en: "Blob, are you fast?", de: "Blob, bist du schnell?" },
        { who: "blob", fr: "Oui ! Je suis plus rapide qu'un train !", en: "Yes! I'm faster than a train!", de: "Ja! Ich bin schneller als ein Zug!" },
        { who: "lea", fr: "Le premier au parc gagne. On fait une course ?", en: "The first one to the park wins. Shall we have a race?", de: "Wer zuerst im Park ist, gewinnt. Machen wir ein Wettrennen?" },
        { who: "hugo", fr: "D'accord ! Un, deux, trois… partez !", en: "OK! One, two, three… go!", de: "Okay! Eins, zwei, drei … los!" },
        { who: "lea", fr: "Hugo est le premier ! Et Blob, où est-il ?", en: "Hugo is first! And Blob, where is he?", de: "Hugo ist Erster! Und Blob, wo ist er?" },
        { who: "hugo", fr: "Derrière nous, avec une glace !", en: "Behind us, with an ice cream!", de: "Hinter uns, mit einem Eis!" },
        { who: "blob", fr: "Je suis moins rapide que vous, mais j'ai la meilleure glace !", en: "I'm slower than you, but I've got the best ice cream!", de: "Ich bin langsamer als ihr, aber ich habe das beste Eis!" },
        { who: "lea", fr: "Blob, tu es le plus lent… mais le plus drôle !", en: "Blob, you're the slowest… but the funniest!", de: "Blob, du bist der Langsamste … aber der Lustigste!" },
      ],
      questions: [
        { q: tx("Who is the fastest?", "Wer ist am schnellsten?"), options: ["Hugo", "Blob", "Léa"], answer: 0 },
        { q: tx("Where is Blob?", "Wo ist Blob?"), options: [tx("Behind them, with an ice cream", "Hinter ihnen, mit einem Eis"), tx("At the park, first", "Als Erster im Park"), tx("On a train", "In einem Zug")], answer: 0 },
        { q: tx("What does Léa think of Blob?", "Was denkt Léa über Blob?"), options: [tx("He's the slowest, but the funniest.", "Er ist der Langsamste, aber der Lustigste."), tx("He's the fastest.", "Er ist der Schnellste."), tx("He's the oldest.", "Er ist der Älteste.")], answer: 0 },
      ],
    },
  ],
  tips: [
    {
      title: tx("Plus, moins, aussi … que", "Plus, moins, aussi … que"),
      body: tx(
        "To compare, put **plus** (more), **moins** (less) or **aussi** (as) before the adjective, and **que** (than, as) after it: le train est **plus** rapide **que** le bus.\n\nThe adjective still agrees: Chloé est aussi grand**e** que Léa. Beau and vieux change a lot: une **belle** ville, une **vieille** maison.",
        "Zum Vergleichen kommt **plus** (mehr), **moins** (weniger) oder **aussi** (so) vor das Adjektiv und **que** (als, wie) danach: le train est **plus** rapide **que** le bus.\n\nDas Adjektiv wird trotzdem angepasst: Chloé est aussi grand**e** que Léa. Beau und vieux ändern sich stark: une **belle** ville, une **vieille** maison.",
      ),
      examples: [
        { fr: "Le train est plus rapide que le bus.", en: "The train is faster than the bus.", de: "Der Zug ist schneller als der Bus." },
        { fr: "Les pommes sont moins chères que les fraises.", en: "Apples are cheaper than strawberries.", de: "Äpfel sind billiger als Erdbeeren." },
        { fr: "Chloé est aussi grande que Léa.", en: "Chloé is as tall as Léa.", de: "Chloé ist so groß wie Léa." },
      ],
      table: {
        head: [tx("meaning", "Bedeutung"), tx("French", "Französisch")],
        rows: [
          [tx("taller than", "größer als"), "plus grand que"],
          [tx("less tall than", "weniger groß als"), "moins grand que"],
          [tx("as tall as", "so groß wie"), "aussi grand que"],
        ],
      },
    },
    {
      title: tx("The best, the most", "Der Beste, am meisten"),
      body: tx(
        "For the most, use **le plus**, **la plus** or **les plus**: Blob est **le plus** drôle, c'est la plus belle ville. After a noun, repeat the article: le téléphone **le plus** cher.\n\nGood is special: bon becomes **meilleur** (better), never plus bon. The best: **le meilleur**, **la meilleure**: Léa est ma meilleure amie.",
        "Für am meisten nimmst du **le plus**, **la plus** oder **les plus**: Blob est **le plus** drôle, c'est la plus belle ville. Nach dem Nomen wiederholt man den Artikel: le téléphone **le plus** cher.\n\nGut ist besonders: Aus bon wird **meilleur** (besser), nie plus bon. Der Beste: **le meilleur**, **la meilleure**: Léa est ma meilleure amie.",
      ),
      examples: [
        { fr: "Blob est le plus drôle de la classe.", en: "Blob is the funniest in the class.", de: "Blob ist der Lustigste in der Klasse." },
        { fr: "C'est le meilleur restaurant de la ville.", en: "It's the best restaurant in town.", de: "Das ist das beste Restaurant der Stadt." },
        { fr: "Léa est ma meilleure amie.", en: "Léa is my best friend.", de: "Léa ist meine beste Freundin." },
      ],
      table: {
        head: [tx("good", "gut"), tx("better", "besser"), tx("the best", "der / die beste")],
        rows: [
          ["bon", "meilleur", "le meilleur"],
          ["bonne", "meilleure", "la meilleure"],
        ],
      },
    },
    {
      title: tx("Je le prends: it and them", "Je le prends: ihn, sie, es"),
      body: tx(
        "To avoid repeating a thing, use **le** (masculine), **la** (feminine) or **les** (plural). They go **before** the verb: le pull → je **le** prends. Before a vowel: **l'**: je peux **l'**essayer ?\n\nIn the negative, ne comes first: je **ne les** prends **pas**.",
        "Damit du ein Ding nicht wiederholen musst, nimmst du **le** (männlich), **la** (weiblich) oder **les** (Plural). Sie stehen **vor** dem Verb: le pull → je **le** prends. Vor einem Vokal: **l'**: je peux **l'**essayer ?\n\nIn der Verneinung kommt ne zuerst: je **ne les** prends **pas**.",
      ),
      examples: [
        { fr: "Ce pull est beau. Je le prends !", en: "This jumper is nice. I'll take it!", de: "Dieser Pullover ist schön. Ich nehme ihn!" },
        { fr: "Cette robe ? Je la prends.", en: "This dress? I'll take it.", de: "Dieses Kleid? Ich nehme es." },
        { fr: "Ces lunettes sont trop chères, je ne les prends pas.", en: "These glasses are too expensive, I won't take them.", de: "Diese Brille ist zu teuer, ich nehme sie nicht." },
      ],
      table: {
        head: [tx("the thing", "das Ding"), tx("it / them", "ihn / sie / es")],
        rows: [
          ["le pull", "je le prends"],
          ["la robe", "je la prends"],
          ["les chaussures", "je les prends"],
        ],
      },
    },
    {
      title: tx("Mieux or meilleur?", "Mieux oder meilleur?"),
      body: tx(
        "Both mean better. **Meilleur** goes with a noun (it's an adjective): un meilleur gâteau. **Mieux** goes with a verb: Léa chante **mieux** que moi, c'est mieux comme ça.\n\nTwo more: **le même** / la même (the same) and **le moins** (the least): le téléphone le moins cher, the cheapest.",
        "Beide heißen besser. **Meilleur** gehört zu einem Nomen (es ist ein Adjektiv): un meilleur gâteau. **Mieux** gehört zu einem Verb: Léa chante **mieux** que moi, c'est mieux comme ça.\n\nDazu: **le même** / la même (der / die gleiche) und **le moins** (am wenigsten): le téléphone le moins cher, das billigste Handy.",
      ),
      examples: [
        { fr: "Léa chante mieux que moi.", en: "Léa sings better than me.", de: "Léa singt besser als ich." },
        { fr: "J'ai le même sac que toi !", en: "I've got the same bag as you!", de: "Ich habe die gleiche Tasche wie du!" },
        { fr: "Je vais acheter le téléphone le moins cher.", en: "I'm going to buy the cheapest phone.", de: "Ich werde das billigste Handy kaufen." },
      ],
      table: {
        head: [tx("with", "bei"), tx("good", "gut"), tx("better", "besser")],
        rows: [
          [tx("a noun", "Nomen"), "bon", "meilleur"],
          [tx("a verb", "Verb"), "bien", "mieux"],
        ],
      },
    },
  ],
};
